table 'Securities Position Fact'
	lineageTag: edc4ab73-1a02-4c56-b34f-1b3c4aa30d0a
	sourceLineageTag: 3da8a732-fd5d-48f7-8975-8ac0112d39a7

	measure Adjustment = -([Final Sch DA BACV] + [Final Sch E2 BACV])
		lineageTag: 6fda7ffe-7ae3-457d-9f1d-469a1d569f23

	measure 'Final Sch DA BACV' = CALCULATE('Securities Position Fact'[Book Value - Local], filter(Securities, DATEDIFF(Securities[Issue Dt],Securities[Maturity Date], DAY) >= 90 && DATEDIFF(Securities[Issue Dt],Securities[Maturity Date], DAY) <=365 && Securities[Issue Dt] <> BLANK() && Securities[Maturity Date] <> BLANK()),'Securities Position Fact'[GL Class] = "MM" || 'Securities Position Fact'[GL Class] = "BOND")
		lineageTag: 178cc09f-ca6d-4cc3-b15e-0e6dadb41193

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Maturity Days From Purchase Date' = DATEDIFF([Issue Dt (Sec Pos)],[Maturity Date (Sec Pos)], DAY)
		formatString: 0
		lineageTag: 39ee7ce0-6bb2-4703-969d-e1da171f1db9

	measure 'Final Sch E2 BACV' = CALCULATE('Securities Position Fact'[Book Value - Local], filter(Securities, DATEDIFF(Securities[Issue Dt],Securities[Maturity Date], DAY) < 90 && Securities[Issue Dt] <> BLANK() && Securities[Maturity Date] <> BLANK()),'Securities Position Fact'[GL Class] = "MM" || 'Securities Position Fact'[GL Class] = "BOND")
		lineageTag: 82cd2995-adaf-4505-ad29-bcaec43fc98c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Final BACV' = 'Securities Position Fact'[Carrying Value - Local] + 'Securities Position Fact'[Adjustment]
		lineageTag: 79721227-46f9-4922-b7ff-c1a4387e65d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Statement Value - STAT basis' = [Book Value - Local]
		lineageTag: 36651d2f-d8b3-42fb-acaa-84bc3a02bff3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Numeric/Alpha Des' = LEFT([NAIC Designation (Sec Pos)],3)
		lineageTag: 40c0478f-bf72-4bf3-84f0-0a692b91d227

	measure 'Final Sch DA BACV_USD' = CALCULATE(sum('Securities Position Fact'[Book Value - USD]), filter(Securities, DATEDIFF(Securities[Issue Dt],Securities[Maturity Date], DAY) >= 90 && DATEDIFF(Securities[Issue Dt],Securities[Maturity Date], DAY) <=365 && Securities[Issue Dt] <> BLANK() && Securities[Maturity Date] <> BLANK()),'Securities Position Fact'[GL Class] = "MM" || 'Securities Position Fact'[GL Class] = "BOND")
		lineageTag: 2c054102-3344-45c7-a5ac-61b8d0556551

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Final Sch E2 BACV_USD' = CALCULATE(sum('Securities Position Fact'[Book Value - USD]), filter(Securities, DATEDIFF(Securities[Issue Dt],Securities[Maturity Date], DAY) < 90 && Securities[Issue Dt] <> BLANK() && Securities[Maturity Date] <> BLANK()),'Securities Position Fact'[GL Class] = "MM" || 'Securities Position Fact'[GL Class] = "BOND")
		lineageTag: 32d825e2-9aa1-4979-9394-45206d504bde

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Adjustment_USD = -([Final Sch DA BACV_USD] + [Final Sch E2 BACV_USD])
		lineageTag: 9b25a123-8faa-4757-819f-d49ee6db7883

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Final BACV_USD' = sum('Securities Position Fact'[Carrying Value - USD]) + 'Securities Position Fact'[Adjustment_USD]
		lineageTag: 90e087c3-11b5-41d0-bcaf-b615ebaf7245

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Security Position Title' = EXTERNALMEASURE("Security Position Title", STRING, "DirectQuery to AS - Securities")
		lineageTag: 2af2a920-1c7e-46f8-8a27-5e13c34b44c0
		sourceLineageTag: fa1daf8d-ffc3-465a-a222-8436c193afd3
		dataCategory: Uncategorized

	measure 'Reporting Currency (Security Position)' = EXTERNALMEASURE("Reporting Currency (Security Position)", STRING, "DirectQuery to AS - Securities")
		lineageTag: f58efcbb-cd48-45d9-93ec-49ed64c06469
		sourceLineageTag: ec12969e-9a03-4452-9249-b0bad4baaa35
		dataCategory: Uncategorized

	measure 'Rep Rate (Security Position)' = EXTERNALMEASURE("Rep Rate (Security Position)", DOUBLE, "DirectQuery to AS - Securities")
		formatString: 0.000000
		lineageTag: 5a507765-ad5c-483f-b860-e8824fea1219
		sourceLineageTag: 9fc8528b-3f4e-425e-b775-ddf4708a6b28
		dataCategory: Uncategorized

	measure 'Fair Value Accrued - Rep (Sec Pos)' = EXTERNALMEASURE("Fair Value Accrued - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 2828f1c9-84dc-4589-8e00-b80223fbb182
		sourceLineageTag: 9543d058-02ae-4741-ac04-ecca03edf156
		dataCategory: Uncategorized

	measure 'Next Payment - Rep' = EXTERNALMEASURE("Next Payment - Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 07039bc4-442b-43b2-96fb-3003e9334d60
		sourceLineageTag: f1cb777a-d813-473a-8f84-e5191b20c089
		dataCategory: Uncategorized

	measure 'Price - Rep' = EXTERNALMEASURE("Price - Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 300f1b40-c86b-4f4c-8335-14c7f49ff4b2
		sourceLineageTag: 7e0b89a7-9636-428d-bc4f-6d760a15bfd3
		dataCategory: Uncategorized

	measure 'Withheld - Rep' = EXTERNALMEASURE("Withheld - Rep", DOUBLE, "DirectQuery to AS - Securities")
		formatString: #,0.00
		lineageTag: f55b371b-e664-4cca-af4b-93f53ab52869
		sourceLineageTag: f951c5c3-6a63-4967-a810-ca439ec5c3ca
		dataCategory: Uncategorized

	measure 'Accrual - Rep' = EXTERNALMEASURE("Accrual - Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 638f35de-d66b-4bce-9616-340fe5f0e4ca
		sourceLineageTag: 8bfbe243-ff14-4792-b4d0-a012a08c9bbb
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss - Rep (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: fcbe3c8b-ff9f-4b34-9892-01e012d440d1
		sourceLineageTag: 43b5c4fb-8bc4-4254-aabf-9a2a84a676ed
		dataCategory: Uncategorized

	measure 'Fair Value Unaccrued - Rep (Sec Pos)' = EXTERNALMEASURE("Fair Value Unaccrued - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: e8e7e5d1-de2f-4c3e-a3c1-21dffa5606de
		sourceLineageTag: 1b77f461-8b07-4060-a597-8a6230c75d53
		dataCategory: Uncategorized

	measure 'Original Cost - Rep (Sec Pos)' = EXTERNALMEASURE("Original Cost - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		formatString: #,0.00
		lineageTag: 39d3b18f-b63e-43a3-8a0b-52b5f0036304
		sourceLineageTag: 22356c03-05b6-4989-9692-ffad68d2fd5c
		dataCategory: Uncategorized

	measure 'Book Value - Rep (Sec Pos)' = EXTERNALMEASURE("Book Value - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 592cff23-113c-4042-a6a2-adef28dddf79
		sourceLineageTag: 196489a1-c153-4382-9c33-096758c3a5b1
		dataCategory: Uncategorized

	measure '% Port MV' = EXTERNALMEASURE("% Port MV", DOUBLE, "DirectQuery to AS - Securities")
		formatString: #,0.00
		lineageTag: d45ee69e-569c-465b-ab8f-cf78d58eedb8
		sourceLineageTag: 8412f6a4-28b4-416d-9d20-836c0ce4129e
		dataCategory: Uncategorized

	measure '% Port BV' = EXTERNALMEASURE("% Port BV", DOUBLE, "DirectQuery to AS - Securities")
		formatString: #,0.00
		lineageTag: d918fcda-063f-4fcc-aed0-1d5a61a32e03
		sourceLineageTag: 6b17d779-0dec-4ded-9475-f018210c66cf
		dataCategory: Uncategorized

	measure 'Position History Title' = EXTERNALMEASURE("Position History Title", STRING, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 52ff7284-5d3d-4763-b4d9-b6466930e6c8
		sourceLineageTag: 36f70a22-f93b-4b80-91f0-82342e78a081
		dataCategory: Uncategorized

	measure 'Amortized Cost - Rep' = EXTERNALMEASURE("Amortized Cost - Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: da7d2693-a863-45d0-a156-b00fdbd0c90b
		sourceLineageTag: f4f0ab44-9b72-4345-b34d-a5ede9b6a6fb
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss CCY - Rep (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss CCY - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: a50faede-a7e2-4597-ab12-e2870fac47fe
		sourceLineageTag: 8c2a3ec6-46ff-44ff-a21c-26ba91cf775d
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss Sec - Rep (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss Sec - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 1cf8dbcc-7228-47c4-bed6-e98db355feb1
		sourceLineageTag: f985dc8e-8eb7-49a5-a795-27916efa41e3
		dataCategory: Uncategorized

	measure W/H% = EXTERNALMEASURE("W/H%", DOUBLE, "DirectQuery to AS - Securities")
		formatString: #,0.00
		lineageTag: bca41ba3-935d-4746-8a7f-70b13fbc93ac
		sourceLineageTag: 14f69a81-3408-432b-8833-96f7ed3564eb
		dataCategory: Uncategorized

	measure 'Carrying Value - Rep (Sec Pos)' = EXTERNALMEASURE("Carrying Value - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 6fc3eb25-047b-40ed-aa50-4ccc86c3e375
		sourceLineageTag: 845894a4-8cea-4c41-a7e5-89c2a15ef079
		dataCategory: Uncategorized

	measure 'Exchange Rate' = EXTERNALMEASURE("Exchange Rate", DOUBLE, "DirectQuery to AS - Securities")
		formatString: 0.000000
		lineageTag: 20a6f32d-e724-476c-b46c-e7383b5ae253
		sourceLineageTag: 77922030-93cc-4759-9eb0-f14ef575a95e
		dataCategory: Uncategorized

	measure 'SCD Coupon' = EXTERNALMEASURE("SCD Coupon", DOUBLE, "DirectQuery to AS - Securities")
		formatString: 0.00
		lineageTag: fb01dba9-b5c0-4cd5-a5dd-54c5ec68c61f
		sourceLineageTag: 93df0aeb-9290-4bd6-98f5-e27750e2bef1
		dataCategory: Uncategorized

	measure 'Income Accrual - Rep' = EXTERNALMEASURE("Income Accrual - Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 769295d8-8e05-44d6-b4bb-fa5343927969
		sourceLineageTag: ef4ebf29-d8f6-480e-8ecc-99b82afc52e7
		dataCategory: Uncategorized

	measure 'Balance Expected Restitution - Rep' = EXTERNALMEASURE("Balance Expected Restitution - Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 35b98ff1-cd7f-4a65-a7cf-96b8e0d3e12b
		sourceLineageTag: 902c78f4-da14-4957-92a3-c1a5c0324ae4
		dataCategory: Uncategorized

	measure 'Amortization/Accretion - Rep (Sec Pos)' = EXTERNALMEASURE("Amortization/Accretion - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 994e853d-d41b-4140-aa41-053c6c42413c
		sourceLineageTag: a7be080b-7068-4372-82fa-16725f9ddb9d
		dataCategory: Uncategorized

	measure 'OID Amortization/Accretion - Rep (Sec Pos)' = EXTERNALMEASURE("OID Amortization/Accretion - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: a0ab081b-af32-4aa2-a01d-9e036447e849
		sourceLineageTag: a68217ba-880c-4f7c-8581-1bb75902dccb
		dataCategory: Uncategorized

	measure 'OTTI Impairment - Rep (Sec Pos)' = EXTERNALMEASURE("OTTI Impairment - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: b74301ed-1ae1-4d5c-bb53-cceef584de42
		sourceLineageTag: 84cba97c-632e-46f7-826c-5db1d18134d4
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance BV - Rep (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance BV - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: bd6583c1-f917-42af-9dbf-53ca562903ec
		sourceLineageTag: f3794653-85e2-424f-9dc8-3cde8ad942a1
		dataCategory: Uncategorized

	measure 'Balance Deferred PL - Rep (Sec Pos)' = EXTERNALMEASURE("Balance Deferred PL - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 3b5411dd-3f1b-410f-8526-a03a7c03ee08
		sourceLineageTag: 6f4b09ae-7709-472f-b27f-62f05ea83753
		dataCategory: Uncategorized

	measure 'Income Tax Withholding - Local' = EXTERNALMEASURE("Income Tax Withholding - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 47d70fb5-248e-4fe5-a712-92811280d538
		sourceLineageTag: 175f5266-762a-4505-aeae-76640d8700da
		dataCategory: Uncategorized

	measure 'ECL/CECL Impairment - Rep (Sec Pos)' = EXTERNALMEASURE("ECL/CECL Impairment - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: b17023b3-d96f-4b92-b1ae-3412a7b91bd6
		sourceLineageTag: 53bee58a-7477-4697-8d02-52402edbe434
		dataCategory: Uncategorized

	measure 'Local (Sec Pos)' = EXTERNALMEASURE("Local (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: f722187a-2300-4b9c-96dc-7e06ed24b85f
		sourceLineageTag: f18624c1-8d3e-434d-806e-e743c66935a2
		dataCategory: Uncategorized

	measure 'Units (PH)' = EXTERNALMEASURE("Units (PH)", DOUBLE, "DirectQuery to AS - Securities")
		formatString: #,0.000
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 75886d86-cafa-4064-a181-9edae0710218
		sourceLineageTag: 078e4307-8ace-4f19-b809-9102cd5bff94
		dataCategory: Uncategorized

	measure 'Fair Value Accrued - Rep (PH)' = EXTERNALMEASURE("Fair Value Accrued - Rep (PH)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: dab546cd-e3df-40f9-9860-62f45fed3f66
		sourceLineageTag: c7882166-50aa-4366-9d67-ade933c6c32b
		dataCategory: Uncategorized

	measure 'Price - Rep (PH)' = EXTERNALMEASURE("Price - Rep (PH)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 6dd40785-81ae-4735-addd-eda6939d5047
		sourceLineageTag: c2d9d569-f85e-4325-b24d-a300f00cdddb
		dataCategory: Uncategorized

	measure 'Book Value - Rep (PH)' = EXTERNALMEASURE("Book Value - Rep (PH)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: bbe39915-3fba-40ba-94fd-0dacb60d72a9
		sourceLineageTag: 3c149062-9e8f-4f63-bbd1-0f11a76d8fa0
		dataCategory: Uncategorized

	measure 'Original Cost - Rep (PH)' = EXTERNALMEASURE("Original Cost - Rep (PH)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: f5982e30-645f-4d8e-a3ef-e829d0d60d3e
		sourceLineageTag: df2da222-4f6a-4700-b8dc-a762021efffb
		dataCategory: Uncategorized

	measure 'Accrual - Local (PH)' = EXTERNALMEASURE("Accrual - Local (PH)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: f080ea12-2a8a-4b1e-aa60-3ce65941e7e6
		sourceLineageTag: b0dea1af-4bf1-473f-afb7-f8a57d6536d1
		dataCategory: Uncategorized

	measure 'Local Exchange Rate (PH)' = EXTERNALMEASURE("Local Exchange Rate (PH)", DOUBLE, "DirectQuery to AS - Securities")
		formatString: 0.000000
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: a1023ff6-9172-4924-8a8b-03fd69842ddd
		sourceLineageTag: f1cb3a5e-d347-4179-8193-05b43d9c1b4a
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss CCY - Rep (PH)' = EXTERNALMEASURE("Unrealized Gain/Loss CCY - Rep (PH)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: fb6230bf-85c2-4eef-910c-6d77cba8c0f8
		sourceLineageTag: a08e345a-d75c-4394-86c6-97e8eb8d5252
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss Sec - Rep (PH)' = EXTERNALMEASURE("Unrealized Gain/Loss Sec - Rep (PH)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 3516f55b-57ad-40ed-8105-68fc71c8e9eb
		sourceLineageTag: 32921ffa-ca0f-49fe-9c31-53bcfa31ad48
		dataCategory: Uncategorized

	measure 'Current Face (PH)' = EXTERNALMEASURE("Current Face (PH)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 63ce7011-969d-4fb7-8778-7ac14060e89f
		sourceLineageTag: 6f0a0170-08ac-40c4-b6dc-006dbd895a88
		dataCategory: Uncategorized

	measure 'ML IFRS 13 Level (Sec Pos)' = EXTERNALMEASURE("ML IFRS 13 Level (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 88aa2772-fb6b-43bf-a870-fad7969eda0a
		sourceLineageTag: 02dcfa0b-04a6-4f4f-af9e-2fbd99b07ac0
		dataCategory: Uncategorized

	measure 'Accrual Currency (Sec Pos)' = EXTERNALMEASURE("Accrual Currency (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 46dca264-443d-4281-b36e-f7fdabc48ae2
		sourceLineageTag: c8d6b516-4b83-4715-a33f-37b77382e196
		dataCategory: Uncategorized

	measure 'Country Of Issue (Sec Pos)' = EXTERNALMEASURE("Country Of Issue (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: a8f596da-ec29-429a-9734-0eb0b38a23f7
		sourceLineageTag: dfe1c04e-284c-4492-a034-991b400e27d2
		dataCategory: Uncategorized

	measure 'Default Flag (Sec Pos)' = EXTERNALMEASURE("Default Flag (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 20691f9c-3df7-4e99-bba5-3b6c27e7430e
		sourceLineageTag: ec0de4c4-ffb4-49f4-8ef3-95667f595b41
		dataCategory: Uncategorized

	measure 'Exchange Country (Sec Pos)' = EXTERNALMEASURE("Exchange Country (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 043ad7ca-4a6a-4aac-951b-0bc559289a1e
		sourceLineageTag: 42189b7d-517b-4923-9054-a14e10ba7af4
		dataCategory: Uncategorized

	measure 'Findur ID (Sec Pos)' = EXTERNALMEASURE("Findur ID (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: a747a8cc-5abc-4462-8ffa-43df8be15c83
		sourceLineageTag: e7bdd6f4-78b2-418f-964a-d9d4f1055dc0
		dataCategory: Uncategorized

	measure 'Isin (Sec Pos)' = EXTERNALMEASURE("Isin (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 5bf5cf61-4e96-43a4-a34b-0d4a8251308b
		sourceLineageTag: 083a0bb9-ab45-4bc9-a6ab-5c979978ee51
		dataCategory: Uncategorized

	measure 'Islamic Indicator (Sec Pos)' = EXTERNALMEASURE("Islamic Indicator (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 5e24114e-546d-4814-b2aa-3e303c183ca1
		sourceLineageTag: 5796959b-f865-418a-aa54-ed984eba322a
		dataCategory: Uncategorized

	measure 'Local ID (Sec Pos)' = EXTERNALMEASURE("Local ID (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 33f75402-0348-4d40-929d-ab13e28eb318
		sourceLineageTag: 91ec016b-5cd6-4934-80cb-8a203f107828
		dataCategory: Uncategorized

	measure 'Price Point (Sec Pos)' = EXTERNALMEASURE("Price Point (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: c5bf9c1e-ea61-49f9-a71c-030aacc1aeb4
		sourceLineageTag: 181e1ea7-eeaf-44a2-b695-821bfc3ef56e
		dataCategory: Uncategorized

	measure 'Principal Exchange (Sec Pos)' = EXTERNALMEASURE("Principal Exchange (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 0286154b-0cf3-4737-904c-7c4c824478b1
		sourceLineageTag: bd4f4024-9c77-4b1d-b595-20a6e9640f7c
		dataCategory: Uncategorized

	measure 'Private Placement (Sec Pos)' = EXTERNALMEASURE("Private Placement (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 7cc98ff8-b8d9-47db-a3f0-ceee9485b0cc
		sourceLineageTag: bc543b8b-6110-4bbc-9163-1764b451a05f
		dataCategory: Uncategorized

	measure 'Cusip (Sec Pos)' = EXTERNALMEASURE("Cusip (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 8ac2eb19-c3c1-4807-958f-181c706e522c
		sourceLineageTag: 7de8f897-073c-4457-bafe-e80272c8f26a
		dataCategory: Uncategorized

	measure 'Official PPN (Sec Pos)' = EXTERNALMEASURE("Official PPN (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 9994eb27-650c-42ce-b180-b080c3d39d94
		sourceLineageTag: 32b640ec-5049-48ad-8981-3a39912a5653
		dataCategory: Uncategorized

	measure 'Carrying Value - Local' = EXTERNALMEASURE("Carrying Value - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 6f908319-b14c-4308-8573-ba259ad15fac
		sourceLineageTag: 5ad0ab28-8a18-4c6f-9cd6-168247f664fd
		dataCategory: Uncategorized

	measure 'Fair Value Accrued - Local' = EXTERNALMEASURE("Fair Value Accrued - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 1f364b89-398f-4796-89dc-6f72d80268a7
		sourceLineageTag: d28f9712-5322-4a07-acc9-729529eb96e3
		dataCategory: Uncategorized

	measure 'Book Value - Local' = EXTERNALMEASURE("Book Value - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: a6e5d471-3b88-4c75-9b4a-ab73dc27c644
		sourceLineageTag: 0e34d70c-4a26-46c1-ae4e-55b4e7ea0935
		dataCategory: Uncategorized

	measure 'Original Cost - Local' = EXTERNALMEASURE("Original Cost - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 12db6e95-191d-4721-8ba7-34ceef4ec6a6
		sourceLineageTag: 7194f639-d90b-484c-ba7d-fda84b79cc3e
		dataCategory: Uncategorized

	measure 'Amortized Cost - Local' = EXTERNALMEASURE("Amortized Cost - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 529baa87-6e9d-444a-8eea-aeed39f2146a
		sourceLineageTag: 393edb9d-2beb-4c66-a89f-15ceb4620578
		dataCategory: Uncategorized

	measure 'Fair Value Unaccrued - Local' = EXTERNALMEASURE("Fair Value Unaccrued - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: f75d1d95-d762-41a9-a87c-74caf6bae343
		sourceLineageTag: d5e9414d-2130-4c73-a725-327ee5910e02
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss - Local' = EXTERNALMEASURE("Unrealized Gain/Loss - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 06ad9a77-7253-4c0d-acc6-c377b4e39966
		sourceLineageTag: 7dd9afb9-19d0-494b-b004-02c2d4ef6662
		dataCategory: Uncategorized

	measure 'Accrual - Local' = EXTERNALMEASURE("Accrual - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 075cb8e8-d614-4695-877e-fc25e8f98d36
		sourceLineageTag: 1016a272-5232-459e-aad9-74abae74a8be
		dataCategory: Uncategorized

	measure 'Withheld - Local' = EXTERNALMEASURE("Withheld - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 97951c62-687e-4d80-828d-cbb66574896f
		sourceLineageTag: 8a39135a-cd85-4a6e-9dc2-d9302c4e1fa4
		dataCategory: Uncategorized

	measure 'Book Value - Local (PH)' = EXTERNALMEASURE("Book Value - Local (PH)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: bfdb4854-45bc-4e5f-b0da-e9ea52369631
		sourceLineageTag: d0230a97-fa9f-40f2-a43c-22b0ff7a9c51
		dataCategory: Uncategorized

	measure 'Private Portf Ind (Sec Pos)' = EXTERNALMEASURE("Private Portf Ind (Sec Pos)", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		displayFolder: Portfolio Attributes
		lineageTag: 8e69177d-64bc-4861-8d4a-a593c63c256f
		sourceLineageTag: 5e658c19-cc5f-412f-ba75-7aa0cf7a9974
		dataCategory: Uncategorized

	measure 'Portfolio Sleeve Status (Sec Pos)' = EXTERNALMEASURE("Portfolio Sleeve Status (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: fee3649a-8b91-4ad6-96b4-7c34e6efeb96
		sourceLineageTag: 913c520e-4740-4ca3-aa98-216f5865e242
		dataCategory: Uncategorized

	measure 'Price - Local' = EXTERNALMEASURE("Price - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 330e2533-c9ad-4675-9782-1266cad8d6f4
		sourceLineageTag: 08297bfd-9346-4cd7-8f46-479ab877b71d
		dataCategory: Uncategorized

	measure Units = EXTERNALMEASURE("Units", DOUBLE, "DirectQuery to AS - Securities")
		formatString: #,0.000
		lineageTag: 06cb2a6a-f26e-42ef-888e-64eed3632a39
		sourceLineageTag: 945142ee-6695-4987-9e2c-a72205bed17b
		dataCategory: Uncategorized

	measure 'Moodys (Sec Pos)' = EXTERNALMEASURE("Moodys (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 29d45709-7160-4337-b269-71263ff0aa34
		sourceLineageTag: 16f3fa0e-dcdb-4963-825a-0e07b12b1e5a
		dataCategory: Uncategorized

	measure 'S&P (Sec Pos)' = EXTERNALMEASURE("S&P (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 6ca8f25d-c49b-4e90-9f86-b764615caf11
		sourceLineageTag: b9c20064-6364-41bd-b9b4-155994830dd9
		dataCategory: Uncategorized

	measure 'Fitch (Sec Pos)' = EXTERNALMEASURE("Fitch (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 3cf0b5eb-5c29-4474-bfa3-60a040be87f1
		sourceLineageTag: 846e95e5-e89e-4a2f-b87c-fbd30c660bb6
		dataCategory: Uncategorized

	measure 'Internal (Sec Pos)' = EXTERNALMEASURE("Internal (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 818801f5-9ad1-42a1-a5ba-b399ef159aed
		sourceLineageTag: 7c2aa96c-85f6-4522-931b-a337d8f72297
		dataCategory: Uncategorized

	measure 'Full Shares Outstanding (Sec Pos)' = EXTERNALMEASURE("Full Shares Outstanding (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 8f2a12cd-db15-4da8-859f-f1bcb18c869e
		sourceLineageTag: 58cbe988-0dfb-4da2-bafd-7f9192b78478
		dataCategory: Uncategorized

	measure 'Income Accrual - Local' = EXTERNALMEASURE("Income Accrual - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 1764a9d5-df2a-4ed5-9434-ebe713864201
		sourceLineageTag: cef03fe8-8503-4fe4-a915-4c5fbf41f015
		dataCategory: Uncategorized

	measure 'Current Yield Book Price' = EXTERNALMEASURE("Current Yield Book Price", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 22505f0a-b8fa-4641-8da4-fea722e5c6a0
		sourceLineageTag: e548c3de-99c3-42ce-ac6d-5f7d8ae85f9a
		dataCategory: Uncategorized

	measure 'Original Book Yield' = EXTERNALMEASURE("Original Book Yield", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 812fbefc-67ee-4eff-88ae-41ef68012959
		sourceLineageTag: 93eda38a-a82f-4829-9eb4-00649b8578b3
		dataCategory: Uncategorized

	measure 'Portfolio Owner (Sec Pos)' = EXTERNALMEASURE("Portfolio Owner (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 2cd1c436-7e3c-4705-8ed1-a565c34ae06a
		sourceLineageTag: b2fe5372-055a-4d24-a8a7-c445e37da44e
		dataCategory: Uncategorized

	measure 'Indonesian Positions Title' = EXTERNALMEASURE("Indonesian Positions Title", STRING, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: f419ff41-455e-430f-9e16-57dd0a541976
		sourceLineageTag: 08d57a09-a64d-46e4-b176-1abf78217b39
		dataCategory: Uncategorized

	measure 'Price - Local (Indo Pos)' = EXTERNALMEASURE("Price - Local (Indo Pos)", DOUBLE, "DirectQuery to AS - Securities")
		formatString: 0.000000
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 0e111ae3-855b-42de-973f-bfed52c291b7
		sourceLineageTag: 5dd764ab-4d43-4bdc-9b4b-aeb2fbcc54cd
		dataCategory: Uncategorized

	measure 'Fair Value Unaccrued - Local (Indo Pos)' = EXTERNALMEASURE("Fair Value Unaccrued - Local (Indo Pos)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 938c56a5-e500-4ad5-9e3d-9d6e64aebfdc
		sourceLineageTag: c83df3be-61a7-4475-b860-866b3e9012f1
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss - Local (Indo Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss - Local (Indo Pos)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 6a739483-9b04-44b1-ac20-536f8ea03259
		sourceLineageTag: b72c2701-1ddb-4a4f-89ef-3aa5cbd9f99e
		dataCategory: Uncategorized

	measure 'Fair Value Accrued - Local (Indo Pos)' = EXTERNALMEASURE("Fair Value Accrued - Local (Indo Pos)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: d2c9153d-59e5-40d7-8962-524c39aaf85f
		sourceLineageTag: fb23be5e-f8c0-4446-9ec3-5a4b2ca37e13
		dataCategory: Uncategorized

	measure 'Maximis Portfolio Number (Sec Pos)' = EXTERNALMEASURE("Maximis Portfolio Number (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: b55edb58-0ee4-4117-b151-c9e9af40181d
		sourceLineageTag: 0ccae87c-5818-4efc-b89e-de8524e63254
		dataCategory: Uncategorized

	measure 'IAS39 Trading Philosophy Code (Sec Pos)' = EXTERNALMEASURE("IAS39 Trading Philosophy Code (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 04f3f071-ca4a-424c-8c68-c296a3538213
		sourceLineageTag: 66a54731-a932-4ec1-bd59-b066ee0a8b48
		dataCategory: Uncategorized

	measure 'IFRS Trading Philosophy Code (Sec Pos)' = EXTERNALMEASURE("IFRS Trading Philosophy Code (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 4266c16b-61a5-409c-aa5f-6ab121218116
		sourceLineageTag: cda8740a-8ba2-4f04-8567-a6176dd2f4a2
		dataCategory: Uncategorized

	measure 'Portfolio Name (Sec Pos)' = EXTERNALMEASURE("Portfolio Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: f3596a9a-97ec-4450-93d8-a68a580b95b7
		sourceLineageTag: c26b94d5-df4d-4641-a80e-ea48b0159f9a
		dataCategory: Uncategorized

	measure 'Investment Desk (Sec Pos)' = EXTERNALMEASURE("Investment Desk (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: f40b47a0-9c74-4967-bb03-cf69cedfa942
		sourceLineageTag: bf1557c9-00ea-4a5e-aa2c-8fb3d1060117
		dataCategory: Uncategorized

	measure 'Portfolio Manager Name (Sec Pos)' = EXTERNALMEASURE("Portfolio Manager Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 21396905-d126-4120-8472-c222c0f91dbb
		sourceLineageTag: 656ac4a6-1e35-4a62-9024-f86cf50c494f
		dataCategory: Uncategorized

	measure 'Security Description (Sec Pos)' = EXTERNALMEASURE("Security Description (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: f731dee1-d1f2-4622-9bd4-9084c3982444
		sourceLineageTag: 09563ac7-a854-4a2f-a2d8-4b467e2f70f3
		dataCategory: Uncategorized

	measure 'FI Type (Sec Pos)' = EXTERNALMEASURE("FI Type (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: af0c0a33-71af-4d0d-b09e-41ed3bc4ce64
		sourceLineageTag: 456b0e03-9b3e-41f0-a437-620878d6390f
		dataCategory: Uncategorized

	measure 'Issue Dt (Sec Pos)' = EXTERNALMEASURE("Issue Dt (Sec Pos)", DATETIME, "DirectQuery to AS - Securities")
		formatString: yyyy\-mm\-dd
		displayFolder: Security Values
		lineageTag: 4bcacbf9-6b19-41c6-aebe-ec87dac5f4e6
		sourceLineageTag: 7eade2b4-4538-4b26-9e34-1c1c1ec1c2d4
		dataCategory: Uncategorized

	measure 'Private Security Position Title' = EXTERNALMEASURE("Private Security Position Title", STRING, "DirectQuery to AS - Securities")
		lineageTag: 763c0530-3d72-4d3a-b4d0-b3431f516e31
		sourceLineageTag: 5b2b25ad-1ac4-4383-94f6-c7a44259dffe
		dataCategory: Uncategorized

	measure 'SCD Instrument Type (Sec Pos)' = EXTERNALMEASURE("SCD Instrument Type (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: c58f211b-f5cd-492b-96cf-0fea1b2b3e11
		sourceLineageTag: 02b3d208-6b10-4204-acf1-a1b16f55a2e7
		dataCategory: Uncategorized

	measure 'Previous Coupon Date (Sec Pos)' = EXTERNALMEASURE("Previous Coupon Date (Sec Pos)", DATETIME, "DirectQuery to AS - Securities")
		formatString: yyyy\-mm\-dd
		displayFolder: Security Values
		lineageTag: 36091577-e68d-4dad-ae1c-cdd3bf672a87
		sourceLineageTag: 604dfb97-fbfe-43d2-a065-7fcfe75b8bb8
		dataCategory: Uncategorized

	measure 'ML Vault ID (Sec Pos)' = EXTERNALMEASURE("ML Vault ID (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: f3a26416-002b-4bb1-9545-a28ee4152b3e
		sourceLineageTag: fe519e73-b571-4ae5-a684-a8d875f8755b
		dataCategory: Uncategorized

	measure 'ML Vault Name (Sec Pos)' = EXTERNALMEASURE("ML Vault Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 2f59f59d-2c83-4506-a00a-8bd477f06a0a
		sourceLineageTag: e08d5102-0d43-4d68-a0b4-89292033a1d2
		dataCategory: Uncategorized

	measure 'Group Portfolio Manager Name (Sec Pos)' = EXTERNALMEASURE("Group Portfolio Manager Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 565baba4-7f39-46ad-96b8-8aece8fbc0e7
		sourceLineageTag: 5f14a649-ecfd-4080-a43a-f7060beef190
		dataCategory: Uncategorized

	measure Nominal = EXTERNALMEASURE("Nominal", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: f060fd8a-003b-4c98-abc6-66bcc6e16534
		sourceLineageTag: 3c4ffa8a-0f75-4cc4-a78e-9a935ac58297
		dataCategory: Uncategorized

	measure 'ID BPL Pricing Strategy (Sec Pos)' = EXTERNALMEASURE("ID BPL Pricing Strategy (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: f135a772-efcd-46e7-950f-e8579c0486d7
		sourceLineageTag: 33d3eb6a-b0d5-4a8b-983c-bd19ef2e23e9
		dataCategory: Uncategorized

	measure 'JGAAP Trading Philosophy Code (Sec Pos)' = EXTERNALMEASURE("JGAAP Trading Philosophy Code (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 8b770c0c-19d4-476d-958a-dc9fcd9e8670
		sourceLineageTag: bb8f55e0-f758-471b-a055-dc3cb179218c
		dataCategory: Uncategorized

	measure 'USGAAP Trading Philosophy Code (Sec Pos)' = EXTERNALMEASURE("USGAAP Trading Philosophy Code (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 487dcd0c-36f8-4ff6-a048-242ec45da044
		sourceLineageTag: 9344e9d9-ba29-450f-8037-155f2aa838f5
		dataCategory: Uncategorized

	measure 'ML Private Asset ID (Sec Pos)' = EXTERNALMEASURE("ML Private Asset ID (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: d89a04d8-4cfa-48c9-8005-138af38221b7
		sourceLineageTag: cccbb4d5-031f-45d0-9c97-534230a5b674
		dataCategory: Uncategorized

	measure 'Security Name (Sec Pos)' = EXTERNALMEASURE("Security Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: c0179de3-7ccb-4e76-8fb6-fc811e63bd24
		sourceLineageTag: 0ed598ba-2d18-4afb-aaf1-1b31443b07d6
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance Non BV - Rep (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance Non BV - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 9efc9009-1c5e-4884-a95b-414ee47bcb1d
		sourceLineageTag: 856ac8fc-897d-4465-a751-98973690b85f
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance Rep - Rep (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance Rep - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 7556d8b4-32fc-4f74-9a45-56d271cc1116
		sourceLineageTag: 9cc22a58-9bc9-4c4f-b470-8094c3d36502
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance BV - Local' = EXTERNALMEASURE("AOCI Remain Balance BV - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: db18a321-e00c-419c-8946-f5c732da4376
		sourceLineageTag: 06ed3639-b2e6-403e-9fb1-3f8b5eb78419
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance Non BV - Local' = EXTERNALMEASURE("AOCI Remain Balance Non BV - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 44ecd0be-664e-4158-8865-ea24a105d484
		sourceLineageTag: dbf1236a-275e-4dcc-8544-fc5933bd9188
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance Rep - Local' = EXTERNALMEASURE("AOCI Remain Balance Rep - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 97e781ae-b837-48b5-ac41-655956e571bb
		sourceLineageTag: ae083cd8-0959-4614-8392-251934212e37
		dataCategory: Uncategorized

	measure 'Coupon Type (Sec Pos)' = EXTERNALMEASURE("Coupon Type (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: bb152501-7807-449b-b4f0-a604a18ce28f
		sourceLineageTag: 5afaafcc-5faf-4cd5-88fc-d7daa4cf4f43
		dataCategory: Uncategorized

	measure 'Legacy Portfolio Code (Sec Pos)' = EXTERNALMEASURE("Legacy Portfolio Code (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 20a78271-14d9-4e10-9a6a-efa6dc462b15
		sourceLineageTag: e50009f9-3b81-4e85-a331-7460fbcba937
		dataCategory: Uncategorized

	measure 'Current Face (Sec Pos)' = EXTERNALMEASURE("Current Face (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 15558387-21e3-4040-8a02-e56cd98059f4
		sourceLineageTag: 502453de-9033-45af-b2c4-f0f032e7e969
		dataCategory: Uncategorized

	measure 'Original Face' = EXTERNALMEASURE("Original Face", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 83234d7e-63d0-48f4-aac2-34d2f1e8c6f0
		sourceLineageTag: bd6fe9f8-546e-4160-96c5-bb8736d6f8c0
		dataCategory: Uncategorized

	measure 'Std Currency (Sec Pos)' = EXTERNALMEASURE("Std Currency (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 6848bcb2-a6f6-4b5b-a3ca-9694759c6e23
		sourceLineageTag: 19a42b49-0f2c-4411-b892-1822112fb434
		dataCategory: Uncategorized

	measure 'Sleeve Manager Team List (Sec Pos)' = EXTERNALMEASURE("Sleeve Manager Team List (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 21b07f0c-74fd-48cd-817a-ad16dc39f845
		sourceLineageTag: dc33fe10-f4a3-4452-98e1-75c8dd993045
		dataCategory: Uncategorized

	measure 'Maturity Date (Sec Pos)' = EXTERNALMEASURE("Maturity Date (Sec Pos)", DATETIME, "DirectQuery to AS - Securities")
		formatString: yyyy\-mm\-dd
		isHidden
		displayFolder: Security Values
		lineageTag: c3eaf5bd-15e6-4353-83c9-848bbae56e3b
		sourceLineageTag: 74513f9f-8b9c-418a-9272-55aca75a65bd
		dataCategory: Uncategorized

	measure 'Day Count (Sec Pos)' = EXTERNALMEASURE("Day Count (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 5f8ca2e4-6f46-4087-b3fa-ef82d6564725
		sourceLineageTag: dc5d5bbc-252f-4858-9f34-5de05a974f2e
		dataCategory: Uncategorized

	measure 'ECL/CECL Impairment - Local (Sec Pos)' = EXTERNALMEASURE("ECL/CECL Impairment - Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: c413b3b1-77da-411d-b849-73594b1a3a8f
		sourceLineageTag: 2fbf0555-09ee-4ad8-b80d-e550f6a175a3
		dataCategory: Uncategorized

	measure 'Purpose Codes (Sec Pos)' = EXTERNALMEASURE("Purpose Codes (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 78f65eaf-c7a3-4d37-a2bd-0c06121c0f72
		sourceLineageTag: 14850d14-8632-4195-af4b-6b19ba6cbddf
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss CCY - Local' = EXTERNALMEASURE("Unrealized Gain/Loss CCY - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 42c53bca-737d-4217-9bda-66a49d98f8d0
		sourceLineageTag: e8a1f731-ad49-4590-b608-1c4e0251d6b1
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss Sec - Local' = EXTERNALMEASURE("Unrealized Gain/Loss Sec - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: a60f4571-7aea-4ba1-bb7e-ab5fa22fba72
		sourceLineageTag: d2cde7c4-1327-4348-b363-5b5891903f64
		dataCategory: Uncategorized

	measure 'Next Coupon Amount' = EXTERNALMEASURE("Next Coupon Amount", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: ad8096c4-4440-47bf-96bc-4073b07339ff
		sourceLineageTag: 75f1ceda-ded8-4222-9a90-fe978cfba56e
		dataCategory: Uncategorized

	measure 'Current Yield' = EXTERNALMEASURE("Current Yield", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 29526547-91e9-4f48-8e4d-8dee23657951
		sourceLineageTag: e0a37573-7fd4-4e14-8900-e59ed49eac11
		dataCategory: Uncategorized

	measure 'ML Minor Type (Sec Pos)' = EXTERNALMEASURE("ML Minor Type (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: febfa245-c25f-4e71-b0cf-417d493671a9
		sourceLineageTag: e9ef8179-5e84-44ee-bb43-d3facbe5b428
		dataCategory: Uncategorized

	measure 'Current Timestamp (Sec Pos)' = EXTERNALMEASURE("Current Timestamp (Sec Pos)", DATETIME, "DirectQuery to AS - Securities")
		formatString: yyyy\-mm\-dd hh:nn:ss AM/PM
		lineageTag: 500d29b6-94c7-4a7e-b1f1-ac285d3e4625
		sourceLineageTag: ebbc098e-7035-4cea-8bda-7bc4ced78a1e
		dataCategory: Uncategorized

	measure 'Inv Lp Port Code (Sec Pos)' = EXTERNALMEASURE("Inv Lp Port Code (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 564cf473-627f-4c45-bbf9-0cdad1f9d3f3
		sourceLineageTag: ae25f6be-a9e1-4f18-9d7c-eea0c6c54e04
		dataCategory: Uncategorized

	measure 'Lawson Legal ID (Sec Pos)' = EXTERNALMEASURE("Lawson Legal ID (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 953db3fb-4c7b-4b59-b3bc-aa44425e6398
		sourceLineageTag: 3f461001-8f32-4836-9cfe-5f9dc85009dc
		dataCategory: Uncategorized

	measure 'Liability Surplus (Sec Pos)' = EXTERNALMEASURE("Liability Surplus (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: c164f3be-c12b-4f11-b9a4-84cfd9ce02db
		sourceLineageTag: 3fc9e528-96a9-423a-9e13-5d29d5f910ac
		dataCategory: Uncategorized

	measure 'Custodian Name (Sec Pos)' = EXTERNALMEASURE("Custodian Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: cb7b8f66-9838-451a-880f-b1df3dbfd33f
		sourceLineageTag: 34159006-9526-45cc-bcf1-35e4a3709ff8
		dataCategory: Uncategorized

	measure 'S&P Short Term Rating (Sec Pos)' = EXTERNALMEASURE("S&P Short Term Rating (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 8a587e70-dd76-4b0c-b630-f66c45085f1d
		sourceLineageTag: aed822b3-ccd9-4619-a5cd-597ba5921a06
		dataCategory: Uncategorized

	measure 'Fitch Short Term Rating (Sec Pos)' = EXTERNALMEASURE("Fitch Short Term Rating (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: aa04a19c-e2af-489b-a376-f9dc92fbc20c
		sourceLineageTag: 9809c3df-9bec-4f4e-b1be-b1e41de0b764
		dataCategory: Uncategorized

	measure 'Moodys Short Term Rating (Sec Pos)' = EXTERNALMEASURE("Moodys Short Term Rating (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: a0a87007-596d-49e4-b1a6-bfbff3012e3e
		sourceLineageTag: df6ef881-a09c-40f9-9e02-318c21f072b3
		dataCategory: Uncategorized

	measure 'Dbrs (Sec Pos)' = EXTERNALMEASURE("Dbrs (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 96922392-d342-499c-a457-7538e734109c
		sourceLineageTag: a551c7f0-df4c-4079-ad08-8e7745af4f64
		dataCategory: Uncategorized

	measure 'Maturity Days (Sec Pos)' = EXTERNALMEASURE("Maturity Days (Sec Pos)", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		displayFolder: Security Values
		lineageTag: 04e7df2c-6f00-4096-a238-3a158c9ed95e
		sourceLineageTag: 39b3cbde-3437-4b64-a4d8-3f20003941da
		dataCategory: Uncategorized

	measure 'Country Of Risk (Sec Pos)' = EXTERNALMEASURE("Country Of Risk (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: bb2ad974-136a-4239-8d97-e3bdc8235148
		sourceLineageTag: 1f88eba0-b7e6-42cf-b4da-3a893b79b01a
		dataCategory: Uncategorized

	measure 'Ultimate Parent Company Name (Sec Pos)' = EXTERNALMEASURE("Ultimate Parent Company Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: fd77c4d1-853b-4096-8cb4-d3a8340d20b8
		sourceLineageTag: f4920002-5bfc-40cf-aabc-ddd6201b6b63
		dataCategory: Uncategorized

	measure 'Custodian (Sec Pos)' = EXTERNALMEASURE("Custodian (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 7ac5e726-2235-401b-b0e5-0096cef3e002
		sourceLineageTag: 23e199d4-d276-4a09-972d-cb7536b25227
		dataCategory: Uncategorized

	measure 'Sedol (Sec Pos)' = EXTERNALMEASURE("Sedol (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: d182018c-c5da-4b12-86ca-6b3f2fc250d6
		sourceLineageTag: a3a67579-c6e4-4ba3-ae66-1b0bb1046a70
		dataCategory: Uncategorized

	measure 'MRM Sector (Sec Pos)' = EXTERNALMEASURE("MRM Sector (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: abd4a53d-6543-4895-84cf-076f33297cbb
		sourceLineageTag: 9ce10e58-8266-4c4c-b505-27331082714c
		dataCategory: Uncategorized

	measure 'ML Investment Type Code (Sec Pos)' = EXTERNALMEASURE("ML Investment Type Code (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 3704fad7-3e15-4760-9a6f-220c9ef0dac3
		sourceLineageTag: e8c9ce85-255b-4a88-ac7f-f37d7db81aad
		dataCategory: Uncategorized

	measure 'Schedule BA Asset Category Code (Sec Pos)' = EXTERNALMEASURE("Schedule BA Asset Category Code (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: e6171a1f-49ce-4272-ac93-0c184ce72441
		sourceLineageTag: 1603d5a6-9fcb-4415-8bab-8da808dd1ac5
		dataCategory: Uncategorized

	measure 'Calm Category (Sec Pos)' = EXTERNALMEASURE("Calm Category (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: ed54e492-95a1-4e73-a5fe-b1c4b50bf9c3
		sourceLineageTag: 617c8479-c278-41f5-9332-665ceda3d5b1
		dataCategory: Uncategorized

	measure 'On/Off Bal Sheet (Sec Pos)' = EXTERNALMEASURE("On/Off Bal Sheet (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: a24e4314-df80-48eb-ab57-8ec9fc0b4757
		sourceLineageTag: e5e58634-6bd5-4565-badc-c8db3423132e
		dataCategory: Uncategorized

	measure 'Lawson Legal Name (Sec Pos)' = EXTERNALMEASURE("Lawson Legal Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: aa4f5a09-9ee2-4c5f-9beb-e122723f35a6
		sourceLineageTag: 1abfdc50-cefb-418c-84c6-9678a9cdaa5f
		dataCategory: Uncategorized

	measure 'Primary Asset Type (Sec Pos)' = EXTERNALMEASURE("Primary Asset Type (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 5ad677e7-95c4-46b9-9b07-281764f5d14c
		sourceLineageTag: 867d893a-896f-4450-b95e-ef019e8f0f20
		dataCategory: Uncategorized

	measure 'BICS Level2 Industry Group Desc (Sec Pos)' = EXTERNALMEASURE("BICS Level2 Industry Group Desc (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 713cd9bb-e67d-4db3-a203-a7af5599b155
		sourceLineageTag: 302c6c05-6aa5-4877-acc7-d43f7aba5fe7
		dataCategory: Uncategorized

	measure 'BICS Level1 Sector Desc (Sec Pos)' = EXTERNALMEASURE("BICS Level1 Sector Desc (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: ba80b360-b7e9-4391-8fc1-651ebe580c59
		sourceLineageTag: 317fb41f-b41b-49d1-9b32-53a651f9caa2
		dataCategory: Uncategorized

	measure 'BICS Level3 Industry Desc (Sec Pos)' = EXTERNALMEASURE("BICS Level3 Industry Desc (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 26022a33-424f-4ee6-a139-992dc238a3ab
		sourceLineageTag: b417b037-68ae-429d-ac3d-b3bbd8594974
		dataCategory: Uncategorized

	measure 'BICS Level4 Sub Industry Desc (Sec Pos)' = EXTERNALMEASURE("BICS Level4 Sub Industry Desc (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: a52533d8-3e00-4272-95ed-e1ac0f76c5e1
		sourceLineageTag: 27059813-7050-4c13-abee-dc3a48d11a97
		dataCategory: Uncategorized

	measure 'Country of Incorporation (Sec Pos)' = EXTERNALMEASURE("Country of Incorporation (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 3c71becc-3852-4da0-b34a-76e2e517f54f
		sourceLineageTag: cc6bb53e-5b28-4660-afd4-4821d4de69d2
		dataCategory: Uncategorized

	measure 'Issuer Legal Entity Identifier (Sec Pos)' = EXTERNALMEASURE("Issuer Legal Entity Identifier (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: ed50e2da-4a95-4153-82d2-2699b89c513e
		sourceLineageTag: aea19bd8-933c-4367-b0f8-e7b51682e11d
		dataCategory: Uncategorized

	measure 'Amortized Cost - Rep (Indo Pos)' = EXTERNALMEASURE("Amortized Cost - Rep (Indo Pos)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 838ebf34-c75e-40a5-902f-1df220b54f08
		sourceLineageTag: 5723811a-0ffe-4940-b27f-8892d764b939
		dataCategory: Uncategorized

	measure 'Book Value - Rep (Indo Pos)' = EXTERNALMEASURE("Book Value - Rep (Indo Pos)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: bbfece20-72ce-495d-b3bd-d0b01bb5ff22
		sourceLineageTag: 2e7ed261-8032-42bf-bc71-f1ff6e06ca86
		dataCategory: Uncategorized

	measure 'Original Cost - Rep (Indo Pos)' = EXTERNALMEASURE("Original Cost - Rep (Indo Pos)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: d60837bc-cb3f-4732-99a8-d60b7bb8c3d6
		sourceLineageTag: 07b53681-9ce5-44c8-a753-7567c2cf8e56
		dataCategory: Uncategorized

	measure 'Accrual - Rep (Indo Pos)' = EXTERNALMEASURE("Accrual - Rep (Indo Pos)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 3fa5d6c1-7e95-4ce0-8fa6-21c021dd586d
		sourceLineageTag: b387cf1d-f5df-430c-bacc-a6d966e44b22
		dataCategory: Uncategorized

	measure 'Fair Value Unaccrued - Rep (Indo Pos)' = EXTERNALMEASURE("Fair Value Unaccrued - Rep (Indo Pos)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 506d1371-b26a-4532-8d48-2fe32c83ed70
		sourceLineageTag: 54e8d38b-21ae-404b-8ef2-30aefc3efd18
		dataCategory: Uncategorized

	measure 'Fair Value Accrued - Rep (Indo Pos)' = EXTERNALMEASURE("Fair Value Accrued - Rep (Indo Pos)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: eced2b01-ae47-4599-8c7c-8d53977e4970
		sourceLineageTag: 1bc5503b-48d0-44e3-8622-d6e213d5f018
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss - Rep (Indo Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss - Rep (Indo Pos)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 2cb94410-857f-4b50-937f-76715cceea00
		sourceLineageTag: 023a7c8a-023f-4e49-a058-83a4c576b884
		dataCategory: Uncategorized

	measure 'GGI Indicator (Sec Pos)' = EXTERNALMEASURE("GGI Indicator (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 67a02810-b739-4579-bc1f-f60082dfaf01
		sourceLineageTag: 07cf2d98-663e-4a8c-a77a-cc3c74121808
		dataCategory: Uncategorized

	measure 'Is Perpetual (Sec Pos)' = EXTERNALMEASURE("Is Perpetual (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: d935ac75-f88d-4e9c-9cca-6ea9bd020406
		sourceLineageTag: e6726908-ed0c-42ff-b2e3-e8efba259715
		dataCategory: Uncategorized

	measure 'Basic Spread (Sec Pos)' = EXTERNALMEASURE("Basic Spread (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 7a99c633-05b7-42ab-ac42-1ee02924684b
		sourceLineageTag: 8aae748a-0a5e-4a64-8028-1b314eb37373
		dataCategory: Uncategorized

	measure 'Coupon Typ Reset Dt (Sec Pos)' = EXTERNALMEASURE("Coupon Typ Reset Dt (Sec Pos)", DATETIME, "DirectQuery to AS - Securities")
		formatString: yyyy\-mm\-dd
		displayFolder: Security Values
		lineageTag: ea4b9097-8246-42fc-9fa6-ac251547e2e7
		sourceLineageTag: 8a74287b-2456-4014-8ecf-bbd5cbf1cf1d
		dataCategory: Uncategorized

	measure 'Analyst Nm (Sec Pos)' = EXTERNALMEASURE("Analyst Nm (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 2e817284-048c-4e9d-8477-c4879f8a4fd9
		sourceLineageTag: e803a873-fc80-4b95-9c72-63dc4a1d9436
		dataCategory: Uncategorized

	measure 'ML NAIC Instrument Type Cd (Sec Pos)' = EXTERNALMEASURE("ML NAIC Instrument Type Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 697e7886-83a2-449c-8706-780df8079df3
		sourceLineageTag: 5ea88ed7-57f1-4c5d-984f-db8c5dec17d7
		dataCategory: Uncategorized

	measure 'ML Ba Avr Cd (Sec Pos)' = EXTERNALMEASURE("ML Ba Avr Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 10ccdc60-8a8b-4c4f-94aa-0540773f0b73
		sourceLineageTag: 43127573-1347-4338-b79e-c1acb78eb22d
		dataCategory: Uncategorized

	measure 'NAIC Designation (Sec Pos)' = EXTERNALMEASURE("NAIC Designation (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: f137afe0-8872-4d28-971f-7dde6e296957
		sourceLineageTag: 39d6f6b4-54e3-42a9-ac35-9f46981f4646
		dataCategory: Uncategorized

	measure 'ML SD Class Cd (Sec Pos)' = EXTERNALMEASURE("ML SD Class Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 90d82995-7706-40b4-ad93-80b9d4b87121
		sourceLineageTag: 76813763-a9de-447b-8f86-47845974a4fa
		dataCategory: Uncategorized

	measure 'ML SD Class Desc (Sec Pos)' = EXTERNALMEASURE("ML SD Class Desc (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 3460370b-c224-460a-bb79-3764cc44ae49
		sourceLineageTag: dde8e390-8c5e-455a-9376-aba60dacaca5
		dataCategory: Uncategorized

	measure 'ML SD Type Desc (Sec Pos)' = EXTERNALMEASURE("ML SD Type Desc (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: bff7ab4c-3d5a-4576-9017-91a672121a4d
		sourceLineageTag: 2ff4b1b0-f2aa-444c-9004-d8218d773152
		dataCategory: Uncategorized

	measure 'ML SD Subclass Cd (Sec Pos)' = EXTERNALMEASURE("ML SD Subclass Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: d6a5bdf3-ef4a-4a1e-a634-81419be95c28
		sourceLineageTag: ec473886-5acc-4ec7-83a4-a9a7cb43d6db
		dataCategory: Uncategorized

	measure 'ID Cins (Sec Pos)' = EXTERNALMEASURE("ID Cins (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: e4835ceb-9186-4d4c-80fe-c8f53dea8d46
		sourceLineageTag: 24ef8db2-78ed-4b91-8ee0-9dc5e0b43ef0
		dataCategory: Uncategorized

	measure 'ML Capital Structure Desc (Sec Pos)' = EXTERNALMEASURE("ML Capital Structure Desc (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 2818d0ff-f078-4478-aba0-212334fc80a2
		sourceLineageTag: ecbb563d-6da5-46e2-a265-2893e5ecc2a4
		dataCategory: Uncategorized

	measure 'ML Stat Collateral Type Cd (Sec Pos)' = EXTERNALMEASURE("ML Stat Collateral Type Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: f4ea5988-4eec-4de9-913f-57ff9df8c65d
		sourceLineageTag: 6204bfe9-e3e4-4dd3-a7b8-d2a4e181eb4a
		dataCategory: Uncategorized

	measure 'ML Capital Structure Cd (Sec Pos)' = EXTERNALMEASURE("ML Capital Structure Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 9c527d84-426b-4650-ac02-a9a1d12a4fc6
		sourceLineageTag: 7a2ddd51-8c97-45b8-a698-7441c92cbe4a
		dataCategory: Uncategorized

	measure 'ML NAIC Report Part Cd (Sec Pos)' = EXTERNALMEASURE("ML NAIC Report Part Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: fe9e9378-9e24-4c7b-b190-0c0eff021ead
		sourceLineageTag: 6323f40e-caaa-42f0-b5ee-ed5bc8f5ffde
		dataCategory: Uncategorized

	measure 'NAIC Rating (Sec Pos)' = EXTERNALMEASURE("NAIC Rating (Sec Pos)", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		displayFolder: Security Values
		lineageTag: 86a6fb4c-526a-4152-97ce-baf6ed96f24e
		sourceLineageTag: e179afce-84e5-42f2-81da-b8048dfb5b4a
		dataCategory: Uncategorized

	measure 'ML SD Type Cd (Sec Pos)' = EXTERNALMEASURE("ML SD Type Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: bd7ed9cc-792f-4acc-af6c-a937b7014e8d
		sourceLineageTag: df5da20a-ea27-4a42-9607-985718bc3be4
		dataCategory: Uncategorized

	measure 'Alm Segment Name (Sec Pos)' = EXTERNALMEASURE("Alm Segment Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: fd94e17a-18ba-490e-8fae-ad98b033c1d3
		sourceLineageTag: e37a3c02-9b74-42f9-95bc-1435dd431012
		dataCategory: Uncategorized

	measure 'ML MFC Equivalent Eff Dt (Sec Pos)' = EXTERNALMEASURE("ML MFC Equivalent Eff Dt (Sec Pos)", DATETIME, "DirectQuery to AS - Securities")
		formatString: yyyy\-mm\-dd
		displayFolder: Security Values
		lineageTag: 5ed936f1-0327-4cd4-b690-85c2f298bf50
		sourceLineageTag: 07fdb82e-cecd-4e68-a7f1-db8e7723b796
		dataCategory: Uncategorized

	measure 'ML Mim Na Rating Eff Dt (Sec Pos)' = EXTERNALMEASURE("ML Mim Na Rating Eff Dt (Sec Pos)", DATETIME, "DirectQuery to AS - Securities")
		formatString: yyyy\-mm\-dd
		displayFolder: Security Values
		lineageTag: b610db82-cce3-4b10-b1ba-bab6cbe15aff
		sourceLineageTag: f37c9318-3e36-45ae-b26e-775aaae0e980
		dataCategory: Uncategorized

	measure 'Primary Rating Effective Dt (Sec Pos)' = EXTERNALMEASURE("Primary Rating Effective Dt (Sec Pos)", DATETIME, "DirectQuery to AS - Securities")
		formatString: yyyy\-mm\-dd
		displayFolder: Security Values
		lineageTag: c09a4a01-9aea-4a05-a4cc-577c8a3d6990
		sourceLineageTag: 005776b8-1ef1-41c0-9cda-5b1e245f42af
		dataCategory: Uncategorized

	measure 'ML Primary Rating Code (Sec Pos)' = EXTERNALMEASURE("ML Primary Rating Code (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: caffa965-295a-4585-ba19-9e73b2f5fdac
		sourceLineageTag: e3903789-596e-4f3b-8d69-9bc7107de135
		dataCategory: Uncategorized

	measure 'Alm Segment Currency (Sec Pos)' = EXTERNALMEASURE("Alm Segment Currency (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 3e21f280-0c06-4c07-b3be-b9aca61b481c
		sourceLineageTag: b528ea55-5173-4547-9aa3-a429a9ca041b
		dataCategory: Uncategorized

	measure 'Amortization/Accretion - Local (Sec Pos)' = EXTERNALMEASURE("Amortization/Accretion - Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: c71bebc0-4e89-4e6a-a3db-951f4a74a6bf
		sourceLineageTag: fc525aeb-90e0-4976-a137-a787c573f7a9
		dataCategory: Uncategorized

	measure 'Balance Deferred PL - Local' = EXTERNALMEASURE("Balance Deferred PL - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 6172ac11-1ed4-4ff0-aff6-3ba92656297c
		sourceLineageTag: a2a292fd-cb02-4fca-9546-ccbedaa900c2
		dataCategory: Uncategorized

	measure 'Balance Expected Restitution - Local (Sec Pos)' = EXTERNALMEASURE("Balance Expected Restitution - Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: ef12b8ec-1f22-4201-9395-8762a55f51a8
		sourceLineageTag: 14115239-bcde-4db2-8cc0-cc3a04027703
		dataCategory: Uncategorized

	measure 'Next Payment - Local (Sec Pos)' = EXTERNALMEASURE("Next Payment - Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 9c6ff1d4-2e5d-4a3f-ad75-3450a8cae803
		sourceLineageTag: 9e0119e2-18dc-4956-8368-41f0d80b1afd
		dataCategory: Uncategorized

	measure 'OTTI Impairment - Local (Sec Pos)' = EXTERNALMEASURE("OTTI Impairment - Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 6fcac995-2bbb-4f54-980d-f3de37a681a7
		sourceLineageTag: 19781a99-d760-4f8c-aad4-b7193139e5d4
		dataCategory: Uncategorized

	measure 'Securities Menu Title' = EXTERNALMEASURE("Securities Menu Title", STRING, "DirectQuery to AS - Securities")
		lineageTag: be148aeb-c5df-42e3-99e3-b84d458fe414
		sourceLineageTag: 7e99b268-0892-4280-b9b0-de10667fc99e
		dataCategory: Uncategorized

	measure 'Rep Rate (Sec Pos)' = EXTERNALMEASURE("Rep Rate (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		formatString: 0.000000
		lineageTag: 496772a9-e6cb-4eb5-91d9-6dc29acdc4df
		sourceLineageTag: e980f905-1036-44d5-9445-16bb0692ce0f
		dataCategory: Uncategorized

	measure 'Current Book Value - Local (Sec Pos)' = EXTERNALMEASURE("Current Book Value - Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 6b55259c-ff1d-442a-98c0-452dde8b8c1a
		sourceLineageTag: 2bc22866-49d8-47bb-b289-eabbb9412137
		dataCategory: Uncategorized

	measure 'Current Book Value - Rep (Sec Pos)' = EXTERNALMEASURE("Current Book Value - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 4858b5b8-3c01-4bdb-a2d7-d25e627eea48
		sourceLineageTag: 8685887e-afce-4d98-a2d2-b50c5ceb4910
		dataCategory: Uncategorized

	measure 'Units - Rep (Sec Pos)' = EXTERNALMEASURE("Units - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: c5b69820-0791-46b2-b368-4cbbbeb3ef36
		sourceLineageTag: 7bdc2c3f-69ff-45d0-b08a-c61c038d4d68
		dataCategory: Uncategorized

	measure 'SR Loan (Sec Pos)' = EXTERNALMEASURE("SR Loan (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: e1f644fb-7766-4fc8-8235-bf4f1dbf1a44
		sourceLineageTag: beb10a44-e7e4-46ec-b58d-7e52b1dda81b
		dataCategory: Uncategorized

	measure 'Bpl Issuer (Sec Pos)' = EXTERNALMEASURE("Bpl Issuer (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: b9850566-a688-4452-8b1d-cdffa2359c72
		sourceLineageTag: 97493d8e-cdc1-4295-b502-91fd5afde82c
		dataCategory: Uncategorized

	measure 'Balance Write Off - Rep (Sec Pos)' = EXTERNALMEASURE("Balance Write Off - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: e63b7541-56b7-459a-a67f-1593c95f4a86
		sourceLineageTag: 4e11ce64-d8db-4618-8f29-d69d1bfcdd4f
		dataCategory: Uncategorized

	measure 'Balance CL Allowance - Rep (Sec Pos)' = EXTERNALMEASURE("Balance CL Allowance - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 6d6bd47c-d513-4610-9f40-32c273e7ef36
		sourceLineageTag: ac5f2690-341e-409c-8dd9-50d40d74e769
		dataCategory: Uncategorized

	measure 'Balance Recog CL Allowance - Rep (Sec Pos)' = EXTERNALMEASURE("Balance Recog CL Allowance - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: afb3ea10-c455-4f82-bcdf-e7c8162547d1
		sourceLineageTag: 4f91bc8b-f7af-4c47-a05c-0af3b9942fa3
		dataCategory: Uncategorized

	/// For use in Security 
	measure 'Asset Portfolio Code (Sec Pos)' = EXTERNALMEASURE("Asset Portfolio Code (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Portfolio Attributes
		lineageTag: 0ca889a0-4b50-4263-bca3-9832816f4b68
		sourceLineageTag: 6d9c3ad5-d9a4-4684-b845-de804e78b020
		dataCategory: Uncategorized

	measure 'ML Private/Public Asset ID (Sec Pos)' = EXTERNALMEASURE("ML Private/Public Asset ID (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: bebcba9a-6cf3-4373-92d5-e40d383f2914
		sourceLineageTag: 19ec01b7-d67e-48db-9ade-45567fd87c0e
		dataCategory: Uncategorized

	measure 'Coupon Frequency (Sec Pos)' = EXTERNALMEASURE("Coupon Frequency (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: f5eb91ad-37ca-489c-a1f6-366722a1a3e1
		sourceLineageTag: 83ba2e39-343c-49f2-b424-daf004d5bf1b
		dataCategory: Uncategorized

	measure 'RTG SP LT LC Issuer Credit (Sec Pos)' = EXTERNALMEASURE("RTG SP LT LC Issuer Credit (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: ead9e18f-397d-4665-b891-4d4f04420cc8
		sourceLineageTag: 8f3240ce-37d8-40dd-b861-334dd5a0df07
		dataCategory: Uncategorized

	measure 'Int Acc Date (Sec Pos)' = EXTERNALMEASURE("Int Acc Date (Sec Pos)", DATETIME, "DirectQuery to AS - Securities")
		formatString: yyyy\-mm\-dd
		displayFolder: Security Values
		lineageTag: 12a9f01b-44e1-4e05-9547-b82abc6b4aa7
		sourceLineageTag: ff58b2d7-e81b-4dd5-951d-9cf7b563ee02
		dataCategory: Uncategorized

	measure 'State Code (Sec Pos)' = EXTERNALMEASURE("State Code (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 22165e04-23f3-4936-9366-86eca3a484b6
		sourceLineageTag: f167318f-aab2-420d-8e3d-ed01b027d9cf
		dataCategory: Uncategorized

	measure 'NAIC Deposit Category (Sec Pos)' = EXTERNALMEASURE("NAIC Deposit Category (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 3dcbec30-b986-4371-97fb-b0654462db48
		sourceLineageTag: 1f1ea33f-6276-4621-a692-7a678077b9ff
		dataCategory: Uncategorized

	measure 'Final Maturity Date (Sec Pos)' = EXTERNALMEASURE("Final Maturity Date (Sec Pos)", DATETIME, "DirectQuery to AS - Securities")
		formatString: yyyy\-mm\-dd
		displayFolder: Security Values
		lineageTag: 908b3d92-ea2d-419d-9e72-e2e4f36b5659
		sourceLineageTag: 93011281-d542-48d5-93e7-095c171c6e4b
		dataCategory: Uncategorized

	measure 'Country a' = EXTERNALMEASURE("Country a", STRING, "DirectQuery to AS - Securities")
		isHidden
		lineageTag: 2d03cb34-38b8-4bf0-8475-bb58fadb8e73
		sourceLineageTag: bf9101ff-a979-44c0-8e52-5b91559e7372
		dataCategory: Uncategorized

	measure 'Issuer Long Comp Name (Sec Pos)' = EXTERNALMEASURE("Issuer Long Comp Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 26b1d9fb-0b68-49ee-ac21-068b99132b6c
		sourceLineageTag: 483b826c-0410-49ca-9448-7908e633ae88
		dataCategory: Uncategorized

	measure 'Country (Sec Pos)' = EXTERNALMEASURE("Country (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: c8491d2f-da19-4341-943c-a9816a652259
		sourceLineageTag: e92f7bcc-deef-400c-802e-d50a8dbd643a
		dataCategory: Uncategorized

	measure 'Mid Price (Sec Pos)' = EXTERNALMEASURE("Mid Price (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: a3907ed3-bff8-49d1-8709-8414d780060e
		sourceLineageTag: 63b79211-31b6-48a7-82ee-6573cb0c101e
		dataCategory: Uncategorized

	measure 'Bid Price (Sec Pos)' = EXTERNALMEASURE("Bid Price (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: f224ce9a-3684-45b3-8e05-a191df62b708
		sourceLineageTag: c1ee328e-ec11-4c8c-ad45-545f0afb5a44
		dataCategory: Uncategorized

	measure 'Last Price (Sec Pos)' = EXTERNALMEASURE("Last Price (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: a92bf547-ea11-4b43-8684-cf65869ab57a
		sourceLineageTag: d7fd8bfa-117c-48e3-baab-a8b6a688cda4
		dataCategory: Uncategorized

	measure 'Ask Price (Sec Pos)' = EXTERNALMEASURE("Ask Price (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: c2624a03-4507-4ffe-8406-b3e0ec7f1aed
		sourceLineageTag: 1b69f473-1cc9-456f-8d58-d41de8994335
		dataCategory: Uncategorized

	measure 'Ml Pricing (Sec Pos)' = EXTERNALMEASURE("Ml Pricing (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: eb08ba6b-25aa-4946-a91c-741491e27bdb
		sourceLineageTag: 7c85d0f2-772f-449a-a311-9fb936b18f99
		dataCategory: Uncategorized

	measure 'MRM Industry Group Name (Sec Pos)' = EXTERNALMEASURE("MRM Industry Group Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: cef84a29-d267-4a0d-a7d1-7cf7a5038188
		sourceLineageTag: f141b521-8f01-4e2b-9545-0f265f15ece3
		dataCategory: Uncategorized

	measure 'MRM Industry Sector Name (Sec Pos)' = EXTERNALMEASURE("MRM Industry Sector Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 20d15579-9fec-40bf-9b4c-28b654003c51
		sourceLineageTag: 63a92111-87af-4ea7-8980-485aa3d9e086
		dataCategory: Uncategorized

	measure 'MRM Industry Subgroup Name (Sec Pos)' = EXTERNALMEASURE("MRM Industry Subgroup Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 9414e66d-8a47-4ede-a757-ac900310494e
		sourceLineageTag: 5ef7dbcd-39e7-4394-b5a0-ddb6b897d952
		dataCategory: Uncategorized

	measure 'MRM Sector Name (Sec Pos)' = EXTERNALMEASURE("MRM Sector Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: d390c778-142b-46df-8874-f95d2e5bdd8a
		sourceLineageTag: 705a3f55-da63-42e1-98c3-fbc388a4e639
		dataCategory: Uncategorized

	measure 'Income Impairment - Local (Sec Pos)' = EXTERNALMEASURE("Income Impairment - Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: e5eabf75-7af8-46d7-b645-55a7e5688af5
		sourceLineageTag: 6da94c57-e7f0-45c5-b1da-504327b38373
		dataCategory: Uncategorized

	measure 'Income Impairment - Rep (Sec Pos)' = EXTERNALMEASURE("Income Impairment - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: b76cb38d-5c44-4e0b-b068-3e6dfe05e765
		sourceLineageTag: 95bb2fe5-654a-4c1e-bc68-148810bb8180
		dataCategory: Uncategorized

	measure 'Is PublicPP Ind (Sec Pos)' = EXTERNALMEASURE("Is PublicPP Ind (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: f4e94b8b-de56-4a75-9e98-56b0638252da
		sourceLineageTag: 1fc54b00-6d96-4481-a17f-94624343f3bc
		dataCategory: Uncategorized

	measure 'Unsettled Int Div Amount - Rep' = EXTERNALMEASURE("Unsettled Int Div Amount - Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: a5a2808a-15bd-4c39-a68c-105e523d9269
		sourceLineageTag: cb79590c-d142-43f4-9321-f58fcecb15a1
		dataCategory: Uncategorized

	measure 'Deposit Rate (Sec Pos)' = EXTERNALMEASURE("Deposit Rate (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: e9e93d08-c9fa-43d9-98b8-5a558131b896
		sourceLineageTag: 4ed9e3f1-cce0-4649-9b7b-57fb4ca8d357
		dataCategory: Uncategorized

	measure 'Current Book Value - Adjustment Local (Sec Pos)' = EXTERNALMEASURE("Current Book Value - Adjustment Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 241fb857-28d1-40a3-8ac4-f40464472fff
		sourceLineageTag: fe51173d-7047-4a74-b7a2-969d807e8a1c
		dataCategory: Uncategorized

	measure 'Current Book Value - Adjustment Rep (Sec Pos)' = EXTERNALMEASURE("Current Book Value - Adjustment Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 3473478b-37c8-4afd-be4b-a30fcc5ddeb0
		sourceLineageTag: 4fc3f1e8-80df-4aec-acd0-95d193435dc6
		dataCategory: Uncategorized

	measure 'Current Book Value - Position Local (Sec Pos)' = EXTERNALMEASURE("Current Book Value - Position Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		lineageTag: f21eef68-beea-47da-bbac-a5dc2c4d8e1f
		sourceLineageTag: 7752c94b-8dc2-4802-84ce-12316f265106
		dataCategory: Uncategorized

	measure 'Current Book Value - Position Rep (Sec Pos)' = EXTERNALMEASURE("Current Book Value - Position Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		lineageTag: e7b734a3-b3f4-44fe-93b0-c7f604765c0b
		sourceLineageTag: e8b0d713-8f46-49ab-9f0c-e7c715859e87
		dataCategory: Uncategorized

	measure 'ECL/CECL Impairment - Adjustment Local (Sec Pos)' = EXTERNALMEASURE("ECL/CECL Impairment - Adjustment Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 40414f81-1a50-4925-91d7-9f523daf487c
		sourceLineageTag: f393389f-3ec9-4819-bd36-d7bca158eeac
		dataCategory: Uncategorized

	measure 'ECL/CECL Impairment - Adjustment Rep (Sec Pos)' = EXTERNALMEASURE("ECL/CECL Impairment - Adjustment Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: b5bc3ba6-a230-4b3d-833f-ed9a8519ded4
		sourceLineageTag: fe638a0a-747e-469a-bf21-bb4b34b7e8f3
		dataCategory: Uncategorized

	measure 'ECL/CECL Impairment - Position Local (Sec Pos)' = EXTERNALMEASURE("ECL/CECL Impairment - Position Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 260fe267-73d2-4efe-b7e1-7c44a06c1f59
		sourceLineageTag: b5215e16-19ce-4c71-8890-2487771a8d7d
		dataCategory: Uncategorized

	measure 'ECL/CECL Impairment - Position Rep (Sec Pos)' = EXTERNALMEASURE("ECL/CECL Impairment - Position Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 0a264738-acdb-4932-8f07-4d0f7633a149
		sourceLineageTag: 52da3671-e662-43ef-99d3-872f483924bc
		dataCategory: Uncategorized

	measure 'Accrual - Position Local' = EXTERNALMEASURE("Accrual - Position Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: f6158ebd-078d-4f5f-b3ef-50c4d8af2e4d
		sourceLineageTag: 5fed799e-abfb-4dd1-ad1a-2b4964a57325
		dataCategory: Uncategorized

	measure 'Accrual - Position Rep' = EXTERNALMEASURE("Accrual - Position Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 14914f0f-1b4a-450f-bcc6-1574fbc5f672
		sourceLineageTag: 26450546-0574-4eba-9c14-250778b25357
		dataCategory: Uncategorized

	measure 'Accrual - Adjustment Local' = EXTERNALMEASURE("Accrual - Adjustment Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: ffb52568-edd2-411c-990c-8a3725a4dc9c
		sourceLineageTag: 8ffe363d-4c93-4833-aef7-0b458fbf7c6d
		dataCategory: Uncategorized

	measure 'Accrual - Adjustment Rep' = EXTERNALMEASURE("Accrual - Adjustment Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: b3ba38b5-ebf8-4672-9141-5cff762f94b2
		sourceLineageTag: 4ea0ee6e-4171-4cd1-a66e-cce2f731f619
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss - Position Local' = EXTERNALMEASURE("Unrealized Gain/Loss - Position Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 8fa2f6db-c8ff-4257-91dc-7561864ed49e
		sourceLineageTag: e3be357d-c703-4a8d-a071-d18223b44b0e
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss - Position Rep (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss - Position Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 475c23d3-40c8-4539-81cf-c692a137a69d
		sourceLineageTag: dffa7ab4-464f-400e-8bf1-a7a0e3926ba2
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss - Adjustment Rep (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss - Adjustment Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 60f9e8a9-3841-4dad-bba9-eeb5f8e613e1
		sourceLineageTag: 3c2855ea-09ec-47d8-ad14-c55fcfd52e22
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss - Adjustment Local' = EXTERNALMEASURE("Unrealized Gain/Loss - Adjustment Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: ca14b242-8203-4fdf-91d8-086d9481d41a
		sourceLineageTag: 6c6b96ec-77bb-4001-bf0f-c7c2483854fc
		dataCategory: Uncategorized

	measure 'Reset Freq Description (Sec Pos)' = EXTERNALMEASURE("Reset Freq Description (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 1670a56f-3111-4555-ba39-b5a6e7facd26
		sourceLineageTag: 2736c6e3-dfd6-476b-8412-148f8709a974
		dataCategory: Uncategorized

	measure 'Yield For Math Adj (Sec Pos)' = EXTERNALMEASURE("Yield For Math Adj (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		lineageTag: a2450dcf-7998-4c31-986a-80a3d9f8894b
		sourceLineageTag: 5c7f9050-b440-4782-b33f-5dcb8ae163b9
		dataCategory: Uncategorized

	measure 'Balance Acquisition Pre Dis Local' = EXTERNALMEASURE("Balance Acquisition Pre Dis Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 5d0faac0-f5c7-4ada-941f-7552d2032557
		sourceLineageTag: 00c3ab4a-177e-48d2-9092-6ac7658d9129
		dataCategory: Uncategorized

	measure 'Balance Acquisition Pre Dis Rep' = EXTERNALMEASURE("Balance Acquisition Pre Dis Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 2e5ed249-ecef-489e-a846-5b2b8e7e0fa3
		sourceLineageTag: 739e821b-edc2-4a47-9f87-c1135addf70c
		dataCategory: Uncategorized

	measure 'Balance Book Value Native - Local (Sec Pos)' = EXTERNALMEASURE("Balance Book Value Native - Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 27b44d6c-a00e-43b1-945a-fc5888157463
		sourceLineageTag: b5564091-2317-4095-b49d-893e0c03a210
		dataCategory: Uncategorized

	measure 'Balance Book Value Native - Rep (Sec Pos)' = EXTERNALMEASURE("Balance Book Value Native - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: e1f9f650-1d21-4ec7-a142-8c90e3ab2b70
		sourceLineageTag: 00107884-f7f1-4abb-97e4-8eb0796c4a2c
		dataCategory: Uncategorized

	measure 'NAIC Private Placement Indicator' = EXTERNALMEASURE("NAIC Private Placement Indicator", STRING, "DirectQuery to AS - Securities")
		lineageTag: 94adc2a5-999d-4e1a-b757-86d9d5be48ac
		sourceLineageTag: a038681e-f72f-4288-8dab-a12a1cd85d27
		dataCategory: Uncategorized

	measure 'Wash Sale Parent Security Id(Sec Pos)' = EXTERNALMEASURE("Wash Sale Parent Security Id(Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: cb6c0971-4d72-4e7b-ad3e-019408f2d2dd
		sourceLineageTag: 88f25d4b-fa82-4353-8a1a-440b972f9039
		dataCategory: Uncategorized

	measure 'ML LICAT Inferred Rating (Sec Pos)' = EXTERNALMEASURE("ML LICAT Inferred Rating (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 485d079a-857d-4808-967a-5a2a0e01ce5e
		sourceLineageTag: 644e774b-0a09-4ae6-971e-17347c8b5d9d
		dataCategory: Uncategorized

	measure 'ML MFC Equivalent Rating (Sec Pos)' = EXTERNALMEASURE("ML MFC Equivalent Rating (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: a5b1bad1-e829-433f-ad79-545df2e3de14
		sourceLineageTag: c0727f83-d740-4f86-8c10-e5fb531e75f3
		dataCategory: Uncategorized

	measure 'Endorsement Indicator (Sec Pos)' = EXTERNALMEASURE("Endorsement Indicator (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: c4ba10e5-6e5f-40b5-8ce9-2344a18ab1ec
		sourceLineageTag: 44f98042-7917-4da6-a064-e3dad559e0cf
		dataCategory: Uncategorized

	measure '144A Flag (Sec Pos)' = EXTERNALMEASURE("144A Flag (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 65b8950a-d410-4383-bd57-f8e4824b226a
		sourceLineageTag: 5d51ad56-df7a-4ab8-9c7f-6ec1dd7c6dd2
		dataCategory: Uncategorized

	measure 'ML IRR Rating (Sec Pos)' = EXTERNALMEASURE("ML IRR Rating (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 5dbe8dfb-8716-4eb8-9bfe-20f14ddb3364
		sourceLineageTag: 169026bf-b3ab-459f-86e3-3ef93c471268
		dataCategory: Uncategorized

	measure 'Position Book Yield(Sec Pos)' = EXTERNALMEASURE("Position Book Yield(Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 6ddf30cc-26a8-4f24-92bb-4783f0ab3c6c
		sourceLineageTag: 43cfa20a-403f-42a6-a115-f9f9daba00eb
		dataCategory: Uncategorized

	measure 'Country of Issue - Long(Sec Pos)' = EXTERNALMEASURE("Country of Issue - Long(Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 1d9dc74c-51f8-4ffd-98ae-ca8c86bb4a6d
		sourceLineageTag: 89c0877a-0516-401c-b606-c9821daf846b
		dataCategory: Uncategorized

	measure 'Country of Issue - Short(Sec Pos)' = EXTERNALMEASURE("Country of Issue - Short(Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 784a0d63-f599-4df1-9c75-0bd68a3eaab5
		sourceLineageTag: de5cd658-02e4-41c3-b793-175fc2f8fa33
		dataCategory: Uncategorized

	measure 'Effective Date Format (Sec Pos)' = EXTERNALMEASURE("Effective Date Format (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: a18d1f41-f183-42c5-aeaa-1a5102252c6a
		sourceLineageTag: ece67989-a680-459b-a24d-76704acc9562
		dataCategory: Uncategorized

	measure 'SCD Framework (Sec Pos)' = EXTERNALMEASURE("SCD Framework (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 3417de83-1788-4af8-8662-d82b911851ef
		sourceLineageTag: 561e0308-dd19-46fe-ac28-e3e013994a49
		dataCategory: Uncategorized

	measure 'JGAAP Impairment (Sec Pos)' = EXTERNALMEASURE("JGAAP Impairment (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 54ef999f-d497-4330-9084-5e260ce51f68
		sourceLineageTag: f7859280-b7a5-4210-a02a-20317da27ddc
		dataCategory: Uncategorized

	measure 'Impairment Amount Allowed (Sec Pos)' = EXTERNALMEASURE("Impairment Amount Allowed (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: cad3ee2b-5806-4b99-a0b2-85893fd878a1
		sourceLineageTag: df943b21-17e6-49ea-a438-2f5bbe8c563b
		dataCategory: Uncategorized

	measure 'Impairment Amount Allowed - Rep (Sec Pos)' = EXTERNALMEASURE("Impairment Amount Allowed - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 5d18fc63-dd36-4f08-9120-05879cf9fb8e
		sourceLineageTag: 185c8fc4-b234-4381-b87d-a1c46e647ad5
		dataCategory: Uncategorized

	measure 'Impairment Loss (OTTI Sec Pos)' = EXTERNALMEASURE("Impairment Loss (OTTI Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 0674a7d0-fb8f-4f9d-a872-708438bd7280
		sourceLineageTag: e5ad9bac-d69f-4c83-8ac0-9ea2bd321b32
		dataCategory: Uncategorized

	measure 'Impairment Loss Allowed (Sec Pos)' = EXTERNALMEASURE("Impairment Loss Allowed (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: ef17c188-f546-44c7-a296-70a11a427b8e
		sourceLineageTag: 1a3bfe7a-dcad-4c4d-997d-8b4d20fa8d7b
		dataCategory: Uncategorized

	measure 'Impairment Amount QC (Sec Pos)' = EXTERNALMEASURE("Impairment Amount QC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 04431c96-8f43-49fe-a84b-133c1f73cfc7
		sourceLineageTag: f258bbfa-ae6f-4e77-888e-a7358a2281a8
		dataCategory: Uncategorized

	measure 'Ratio of Local FV / BV (Sec Pos)' = EXTERNALMEASURE("Ratio of Local FV / BV (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 0282bac2-3c74-4e5b-a3ce-5801f7018707
		sourceLineageTag: 3567e7a1-8440-4728-837f-52ef1e79b3ae
		dataCategory: Uncategorized

	measure 'Percentage Difference (Sec Pos)' = EXTERNALMEASURE("Percentage Difference (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 2a8949d8-770e-4d54-89b9-6917801af862
		sourceLineageTag: f44ea8e5-dcb3-4377-af34-84b78e884ead
		dataCategory: Uncategorized

	measure 'Decline Category (Sec Pos)' = EXTERNALMEASURE("Decline Category (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 4ebb333e-3618-4098-bbb8-d80039530128
		sourceLineageTag: ed56b4db-cf91-4bea-adc8-adc45bd7a4f0
		dataCategory: Uncategorized

	measure 'Activity Filter (Sec Pos)' = EXTERNALMEASURE("Activity Filter (Sec Pos)", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		lineageTag: 7b306f02-419c-4294-adc3-52c72969c429
		sourceLineageTag: b0d8813e-27ca-4104-a3ea-adfeba40c99b
		dataCategory: Uncategorized

	measure 'Activity Slicer (Sec Pos)' = EXTERNALMEASURE("Activity Slicer (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 808dc33e-b466-4d0b-9415-e5452e19f654
		sourceLineageTag: 94e48c12-b8a6-419b-8619-22186bfa0b9d
		dataCategory: Uncategorized

	measure 'Impairment Candidates Title Position' = EXTERNALMEASURE("Impairment Candidates Title Position", STRING, "DirectQuery to AS - Securities")
		lineageTag: c41d0132-7245-47fc-adab-50f7dace3aa0
		sourceLineageTag: 97d1b826-bfde-4c9f-aba1-55f466263613
		dataCategory: Uncategorized

	measure 'Issuer Country Cd (Sec Pos)' = EXTERNALMEASURE("Issuer Country Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 3a4389df-9691-49a7-be86-f476255d889a
		sourceLineageTag: 38a39032-5708-44ba-af65-17b60b2da90f
		dataCategory: Uncategorized

	measure 'Maturity Date' = EXTERNALMEASURE("Maturity Date", DATETIME, "DirectQuery to AS - Securities")
		formatString: yyyy\-mm\-dd
		lineageTag: fa127e54-6457-4ca0-badf-b71807764be7
		sourceLineageTag: bee6da90-23f1-4fcf-a8d6-48d83b6f3b18
		dataCategory: Uncategorized

	measure 'Internal Sec Id Type (Sec Pos)' = EXTERNALMEASURE("Internal Sec Id Type (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 4a8ac92c-ee0c-4138-a359-122078c9fcd1
		sourceLineageTag: 79e525c4-e7aa-45a9-a06b-d1b286c0f08a
		dataCategory: Uncategorized

	measure 'ML Review CAT CD (Sec Pos)' = EXTERNALMEASURE("ML Review CAT CD (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: b5af3323-01a0-4f93-856e-3ac29e26c3f1
		sourceLineageTag: 8765ccc4-d899-4ffa-85d8-9ed72a8ebbc5
		dataCategory: Uncategorized

	measure 'ML Issue Txt (Sec Pos)' = EXTERNALMEASURE("ML Issue Txt (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 56ac33d0-25a5-465c-8d72-c7547a7e9340
		sourceLineageTag: 7417f756-44a6-4c2b-80f5-49b025ff294a
		dataCategory: Uncategorized

	measure 'Fair Value Unaccrued - Adjustment Local' = EXTERNALMEASURE("Fair Value Unaccrued - Adjustment Local", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		lineageTag: 9c5d2125-735a-4c6e-8c2a-63d5c1f95e7d
		sourceLineageTag: f3781dca-7103-4490-ae2f-4b0814602f19
		dataCategory: Uncategorized

	measure 'Fair Value Unaccrued - Adjustment Rep' = EXTERNALMEASURE("Fair Value Unaccrued - Adjustment Rep", DOUBLE, "DirectQuery to AS - Securities")
		isHidden
		lineageTag: b5e3e435-0123-490a-a905-2043443b794c
		sourceLineageTag: d1ea0d1b-1cd4-47b7-939f-3002d7866a14
		dataCategory: Uncategorized

	measure 'Carrying Value - Adjustment Local' = EXTERNALMEASURE("Carrying Value - Adjustment Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: b04c5dce-147b-4e9f-9e52-49d18ad31bdc
		sourceLineageTag: 25369c74-4afc-485d-a5da-36bb2daa3832
		dataCategory: Uncategorized

	measure 'Carrying Value - Adjustment Rep' = EXTERNALMEASURE("Carrying Value - Adjustment Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 8c74f55b-83d6-410a-aa5f-35be70ae8811
		sourceLineageTag: 3c7242f1-218b-40c1-8672-bc19267d966c
		dataCategory: Uncategorized

	measure 'Carrying Value Final - Local' = EXTERNALMEASURE("Carrying Value Final - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 9828ec3c-fcd5-4607-8428-bbbed169618c
		sourceLineageTag: 4d02d09b-9cdc-4a52-b133-41180eee7dc6
		dataCategory: Uncategorized

	measure 'Carrying Value Final - Rep' = EXTERNALMEASURE("Carrying Value Final - Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: d0959c01-02de-4b39-bea0-7312143d4356
		sourceLineageTag: bc93cd65-9fe4-41ed-bfdb-ccbcbbbbc958
		dataCategory: Uncategorized

	measure 'Legal Structure Cd (Sec Pos)' = EXTERNALMEASURE("Legal Structure Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 7fc3da56-8640-44f3-b2f0-f61616af6916
		sourceLineageTag: 2b7142d7-4eaf-493f-9b9b-bffd879ec33c
		dataCategory: Uncategorized

	measure 'Adjusted GL Class (Sec Pos)' = EXTERNALMEASURE("Adjusted GL Class (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: eba4fa9b-6629-41a4-9a1f-eaa2935cc9d2
		sourceLineageTag: ebb37aee-6652-4604-9619-3d099efd1573
		dataCategory: Uncategorized

	measure 'Balance Called Capital - Rep (Sec Pos)' = EXTERNALMEASURE("Balance Called Capital - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 6ad32a57-6144-4e41-a0d5-befd5d3f5e6e
		sourceLineageTag: 1ca69419-446c-448c-88f2-58ea16c7ff48
		dataCategory: Uncategorized

	measure 'Balance Recallable - Rep (Sec Pos)' = EXTERNALMEASURE("Balance Recallable - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: deb1faf8-72f4-4ae2-8f31-afff24b1c33e
		sourceLineageTag: 1c935592-d287-407a-ae27-a4d1fe11c7f8
		dataCategory: Uncategorized

	measure 'Balance Return Of Capital - Rep (Sec Pos)' = EXTERNALMEASURE("Balance Return Of Capital - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 08256632-1e33-4d39-b0ee-96abf7d579bb
		sourceLineageTag: 7e3f76ac-5714-4977-8842-f9bbd7f49b0b
		dataCategory: Uncategorized

	measure 'Eqy Sic Cd (Sec Pos)' = EXTERNALMEASURE("Eqy Sic Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: fa88f078-a57c-44ad-8030-90b51b8157b8
		sourceLineageTag: 121aeb5f-420b-48d8-91e3-d3d4c023d443
		dataCategory: Uncategorized

	measure 'Balance NAIC Carrying Value - Local (Sec Pos)' = EXTERNALMEASURE("Balance NAIC Carrying Value - Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: ea7b8757-9aa0-4141-9196-56fc776edd06
		sourceLineageTag: 7eb7cc87-7459-4da4-a0d1-7b4ad84d9c4f
		dataCategory: Uncategorized

	measure 'Balance NAIC Carrying Value - Rep (Sec Pos)' = EXTERNALMEASURE("Balance NAIC Carrying Value - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: cb3fda7f-77e9-41ab-a590-9aa92be8a84d
		sourceLineageTag: 3edc4955-dd68-4373-ade2-b547a5353610
		dataCategory: Uncategorized

	measure 'Balance NAIC Sec Adj - Local (Sec Pos)' = EXTERNALMEASURE("Balance NAIC Sec Adj - Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 8b5b3682-b9ab-4d4c-8a05-759654a0d3ec
		sourceLineageTag: d3c3b256-5f48-423a-9b3d-714be7e900d2
		dataCategory: Uncategorized

	measure 'Balance NAIC Sec Adj - Rep (Sec Pos)' = EXTERNALMEASURE("Balance NAIC Sec Adj - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: c7966a38-5c10-43bb-8d63-be4e398d704c
		sourceLineageTag: 834522e6-9400-4748-98f5-c7ab9e806267
		dataCategory: Uncategorized

	measure 'Accrual - CAD (Sec Pos)' = EXTERNALMEASURE("Accrual - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 96c9c967-9a4c-4f33-8b27-e578ba1ba47e
		sourceLineageTag: b80a394e-8ac3-4caa-b4a7-5b116c8d8ce7
		dataCategory: Uncategorized

	measure 'Accrual - FUNC (Sec Pos)' = EXTERNALMEASURE("Accrual - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 4ac0a826-a799-4fa2-94e9-e1f7318c70ae
		sourceLineageTag: 6f4e1432-98a0-4377-b858-adc87d2cb673
		dataCategory: Uncategorized

	measure 'Accrual - HKD (Sec Pos)' = EXTERNALMEASURE("Accrual - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 7654cae7-7376-474a-92a7-2f8ecfd7d15a
		sourceLineageTag: 35d93b6b-550e-4375-a49d-0b5c99c39f31
		dataCategory: Uncategorized

	measure 'Accrual - USD (Sec Pos)' = EXTERNALMEASURE("Accrual - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 24d8a1b2-3491-474c-accf-43224292aa91
		sourceLineageTag: 97e020b6-527a-449f-b7a9-b8cafa8bda36
		dataCategory: Uncategorized

	measure 'Amortized Cost - CAD (Sec Pos)' = EXTERNALMEASURE("Amortized Cost - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: c1a5eb05-cff5-4029-9b82-bf86f1fab72e
		sourceLineageTag: 8c599887-71d7-48b4-8bd4-b02796415688
		dataCategory: Uncategorized

	measure 'Amortized Cost - FUNC (Sec Pos)' = EXTERNALMEASURE("Amortized Cost - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: f7eda929-c4b0-4de9-98f3-43751b2d2f34
		sourceLineageTag: 5b9e520d-6170-47bb-b6df-32a51364bfc1
		dataCategory: Uncategorized

	measure 'Amortized Cost - HKD (Sec Pos)' = EXTERNALMEASURE("Amortized Cost - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 28de1006-cca6-44cb-9140-d0ca2f92bc97
		sourceLineageTag: 69d089b5-12c5-4eaa-a554-295611bbd056
		dataCategory: Uncategorized

	measure 'Amortized Cost - USD (Sec Pos)' = EXTERNALMEASURE("Amortized Cost - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: b5374ec8-53c2-4b47-803e-50be53474d4c
		sourceLineageTag: 4fe65421-d906-4faa-abe5-41c2939a187c
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance BV - CAD (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance BV - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 87f136b9-f563-4d77-b960-8180f53c48df
		sourceLineageTag: eb09a675-7ee9-4cb3-a1dc-5215a06e01a2
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance BV - FUNC (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance BV - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 961420ba-6c8f-4691-86b5-76efc0314686
		sourceLineageTag: 9c3717be-127e-42be-ab51-6afd7d7f969b
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance BV - HKD (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance BV - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 3df31374-a45f-4128-83f0-bf54f3ff1017
		sourceLineageTag: 1be4ac2a-5294-4623-8393-046778bd3ad4
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance BV - USD (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance BV - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: ec2d18bd-067f-459f-a184-1976f0868872
		sourceLineageTag: 823ef7d7-deff-4396-b267-b8653fb8fa8d
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance Non BV - CAD (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance Non BV - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 8f6ed66e-8520-4382-823e-0bf5f83eb1f6
		sourceLineageTag: 41f925c6-4cb4-486b-8829-7cf288badb5e
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance Non BV - FUNC (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance Non BV - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 0bd7c222-db1b-42fa-b9aa-6a9e926f5abe
		sourceLineageTag: 380a7fb6-c927-45a5-8263-96383b847bec
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance Non BV - HKD (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance Non BV - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: ee7bbd2b-2e8a-4fea-a1c4-2d8cb57787e4
		sourceLineageTag: 1055eec7-d3a6-436a-8289-eec3c0c8ef4f
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance Non BV - USD (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance Non BV - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: cd775c10-f21e-44d7-92a3-718a9b5e8270
		sourceLineageTag: ce0805b5-cdb5-48d7-8875-8066a1955587
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance Rep - CAD (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance Rep - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 8db6ae5e-a148-44d1-a50e-e1ec68d9ad81
		sourceLineageTag: b8275644-5bfe-435d-b311-3bf6951f5f0f
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance Rep - FUNC (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance Rep - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 8b01de0f-195e-4b79-8e55-aae8dd59a5e8
		sourceLineageTag: 7dafcaae-d936-4846-b696-1394f015b686
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance Rep - HKD (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance Rep - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 3f9969a1-1158-4fdb-9599-98703c28353d
		sourceLineageTag: faf490b0-c4fc-43bd-abf3-bcec469af086
		dataCategory: Uncategorized

	measure 'AOCI Remain Balance Rep - USD (Sec Pos)' = EXTERNALMEASURE("AOCI Remain Balance Rep - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: c425f8c3-c20f-41fa-91d6-9958f18cb0f1
		sourceLineageTag: 5f7efc87-d463-43a7-a373-b0c3d191099a
		dataCategory: Uncategorized

	measure 'Balance Deferred PL - USD (Sec Pos)' = EXTERNALMEASURE("Balance Deferred PL - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: a7482368-5193-4eea-bd01-b44115dc6aa4
		sourceLineageTag: 3a900d4e-6bfc-420d-a052-0612a725727d
		dataCategory: Uncategorized

	measure 'Balance Deferred PL - HKD (Sec Pos)' = EXTERNALMEASURE("Balance Deferred PL - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 1a40eee0-8c21-4bb8-bb26-4c08e5421a49
		sourceLineageTag: 2a427dca-6034-4a51-a9af-bae2051c5e94
		dataCategory: Uncategorized

	measure 'Balance Deferred PL - FUNC (Sec Pos)' = EXTERNALMEASURE("Balance Deferred PL - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 43d8340a-6697-46bb-8cca-a1a6b5ef623e
		sourceLineageTag: d9cf25ea-f18e-4be5-8289-72bf004b1873
		dataCategory: Uncategorized

	measure 'Balance Deferred PL - CAD (Sec Pos)' = EXTERNALMEASURE("Balance Deferred PL - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 211fd32f-2118-4ec6-b96d-496e618ae5dd
		sourceLineageTag: 4d2e1f9f-ea4c-476d-83e7-480d3a257bd3
		dataCategory: Uncategorized

	measure 'Book Value - USD (Sec Pos)' = EXTERNALMEASURE("Book Value - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 0ffc0180-8449-415d-9f36-50c1c3ca5bdd
		sourceLineageTag: 031540e5-b615-4270-a499-c7c927b2ebe9
		dataCategory: Uncategorized

	measure 'Book Value - HKD (Sec Pos)' = EXTERNALMEASURE("Book Value - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 1e6e62f6-c91a-429c-b385-53bb3b1292ac
		sourceLineageTag: 5be01d41-5fb3-428c-a45d-100ff9b4a99c
		dataCategory: Uncategorized

	measure 'Book Value - FUNC (Sec Pos)' = EXTERNALMEASURE("Book Value - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: b479e334-f6fb-4b6a-a535-3316ffc5f432
		sourceLineageTag: dfd68cf5-b7e1-4db1-a3ca-43c0acb6e6b5
		dataCategory: Uncategorized

	measure 'Book Value - CAD (Sec Pos)' = EXTERNALMEASURE("Book Value - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 8ce6ca5d-ed07-42a2-98d8-ec80ae9a66f8
		sourceLineageTag: 63c3a08b-07e4-4ab7-9950-869eefc0052f
		dataCategory: Uncategorized

	measure 'Carrying Value - USD (Sec Pos)' = EXTERNALMEASURE("Carrying Value - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 0d14e4aa-0aee-4849-89fd-862b2231c21e
		sourceLineageTag: d633761d-6223-4c2a-8399-635ec207c427
		dataCategory: Uncategorized

	measure 'Carrying Value - HKD (Sec Pos)' = EXTERNALMEASURE("Carrying Value - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 7b0d3109-81c3-4ab2-9526-adfe7d0b456a
		sourceLineageTag: 126baa44-df96-4716-9570-d6e3f1bb318f
		dataCategory: Uncategorized

	measure 'Carrying Value - FUNC (Sec Pos)' = EXTERNALMEASURE("Carrying Value - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: d78b4f46-56e7-481d-ab4d-75d5853294b8
		sourceLineageTag: 6dbd2736-ab6a-44fd-a419-42f56801daf9
		dataCategory: Uncategorized

	measure 'Carrying Value - CAD (Sec Pos)' = EXTERNALMEASURE("Carrying Value - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 687bfa4e-e014-4622-9f11-179da5273da1
		sourceLineageTag: 52590747-6efa-45e1-bc4a-7b72b79ddf14
		dataCategory: Uncategorized

	measure 'Fair Value Accrued - USD (Sec Pos)' = EXTERNALMEASURE("Fair Value Accrued - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 216398db-1386-4a8e-bc5d-aca3d9953eb4
		sourceLineageTag: ab13f06e-81c9-48ca-a7eb-b96fdae5e93a
		dataCategory: Uncategorized

	measure 'Fair Value Accrued - HKD (Sec Pos)' = EXTERNALMEASURE("Fair Value Accrued - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 10844c85-8d1d-4b57-9e20-b11d8d8c0e23
		sourceLineageTag: 225dee82-e841-4c33-b1a3-e430b016eba9
		dataCategory: Uncategorized

	measure 'Fair Value Accrued - CAD (Sec Pos)' = EXTERNALMEASURE("Fair Value Accrued - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 4b1dd8c4-5b17-45ef-b4ed-e82b9255a0db
		sourceLineageTag: 2a5852f0-47a7-48dd-94c9-d783f38429a5
		dataCategory: Uncategorized

	measure 'Fair Value Accrued - FUNC (Sec Pos)' = EXTERNALMEASURE("Fair Value Accrued - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 8de9c534-b42c-4bbb-a538-940548a1b072
		sourceLineageTag: 20dda013-b24f-4e8b-ad12-10106eedc751
		dataCategory: Uncategorized

	measure 'Fair Value Unaccrued - CAD (Sec Pos)' = EXTERNALMEASURE("Fair Value Unaccrued - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 61b4a3a1-fd56-4ab9-8ecc-51a35cb12c82
		sourceLineageTag: 2e3cc675-48d8-4d74-a64c-0b09e2f601e0
		dataCategory: Uncategorized

	measure 'Fair Value Unaccrued - FUNC (Sec Pos)' = EXTERNALMEASURE("Fair Value Unaccrued - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 99fe74c3-f695-4e43-9438-6130b7db96af
		sourceLineageTag: 74c35800-bc76-4bbc-bbc8-9bc8a913faa0
		dataCategory: Uncategorized

	measure 'Fair Value Unaccrued - HKD (Sec Pos)' = EXTERNALMEASURE("Fair Value Unaccrued - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 8948b9b2-658c-4fd1-a56d-bc56a3ffab4f
		sourceLineageTag: 736763e5-a254-4bd4-91ba-144d8fedd9e9
		dataCategory: Uncategorized

	measure 'Fair Value Unaccrued - USD (Sec Pos)' = EXTERNALMEASURE("Fair Value Unaccrued - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: df1dd147-da5f-452a-8d92-19ec7feb83fc
		sourceLineageTag: d2352520-8439-4f3d-86e0-7a47bef7f150
		dataCategory: Uncategorized

	measure 'Income Accrual - CAD (Sec Pos)' = EXTERNALMEASURE("Income Accrual - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: ce6e6ebd-2743-48da-ad30-ca4f230e8028
		sourceLineageTag: 4beb399b-694e-4d94-9698-1e986824fec3
		dataCategory: Uncategorized

	measure 'Income Accrual - FUNC (Sec Pos)' = EXTERNALMEASURE("Income Accrual - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 81965d89-7d97-4023-b5e9-d47744be67b2
		sourceLineageTag: 0c8732ca-b6f4-4a4a-9446-25a224bf9f1f
		dataCategory: Uncategorized

	measure 'Income Accrual - HKD (Sec Pos)' = EXTERNALMEASURE("Income Accrual - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: b530dee9-cdee-4d9d-a1c8-4aa3fa0be562
		sourceLineageTag: 992341e0-0c0a-4d54-9d72-d559736ecfaa
		dataCategory: Uncategorized

	measure 'Income Accrual - USD (Sec Pos)' = EXTERNALMEASURE("Income Accrual - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 83da2e74-2a0f-43ad-ba7e-ab1da3a13876
		sourceLineageTag: 53f8e4a2-164e-431b-8cbe-50b1cdb079ab
		dataCategory: Uncategorized

	measure 'Original Cost - USD (Sec Pos)' = EXTERNALMEASURE("Original Cost - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 61688172-8b9d-482d-a7eb-7302cbf99c02
		sourceLineageTag: 10e3219d-81c1-4f4c-a782-b62560d2177d
		dataCategory: Uncategorized

	measure 'Original Cost - HKD (Sec Pos)' = EXTERNALMEASURE("Original Cost - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: cf6a8988-0b93-425a-ade0-3ddc83990e72
		sourceLineageTag: 4ef7365c-8ed2-4cdb-a31c-962ea83fc40b
		dataCategory: Uncategorized

	measure 'Original Cost - FUNC (Sec Pos)' = EXTERNALMEASURE("Original Cost - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: e97fd585-a5e0-44d1-b6f3-4f4d50c8948b
		sourceLineageTag: 8659a214-8c1f-497e-ae38-e49659440eec
		dataCategory: Uncategorized

	measure 'Original Cost - CAD (Sec Pos)' = EXTERNALMEASURE("Original Cost - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: d27857ba-afe5-4fc9-9693-2a38267f606d
		sourceLineageTag: 21c7bbc1-417d-4b41-9af8-7901d1ec476c
		dataCategory: Uncategorized

	measure 'Price - USD (Sec Pos)' = EXTERNALMEASURE("Price - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 501a7c33-3771-4293-af9b-f8ace37467c8
		sourceLineageTag: aabdcaba-cc91-4668-be1e-df6d5e5202b7
		dataCategory: Uncategorized

	measure 'Price - HKD (Sec Pos)' = EXTERNALMEASURE("Price - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 09564040-fbd1-42d4-baf2-00b76cbc3fc1
		sourceLineageTag: 57fdb8a5-7845-4809-825e-5f63fdb27b70
		dataCategory: Uncategorized

	measure 'Price - FUNC (Sec Pos)' = EXTERNALMEASURE("Price - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 5cbcfdc0-edbd-44e7-93ad-49f144310426
		sourceLineageTag: c2dfe45a-bb8e-4b84-b616-22895f0e9219
		dataCategory: Uncategorized

	measure 'Price - CAD (Sec Pos)' = EXTERNALMEASURE("Price - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: eefc4942-a6a9-4d73-8801-fa0c3b8189cb
		sourceLineageTag: 2a776e93-6f18-4a85-be69-a9d39317c296
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss - HKD (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 6e7f534d-e5ae-4f98-b2c4-7cb80076709b
		sourceLineageTag: 9d815643-9b8b-4604-97df-11e703167731
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss - FUNC (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 8c41ddff-b5a1-4c60-971c-fe10b4bcd7f4
		sourceLineageTag: 2bf2ec84-01fe-4d8c-9e5d-c37b0deb8abe
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss - CAD (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 28a0d520-c989-4722-895c-073aaf161460
		sourceLineageTag: 12e1e606-1a7e-4ec8-9f33-004251f14f46
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss - USD (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 946dde89-57e7-4d73-a2b5-7cb9ffaeded9
		sourceLineageTag: dfb4d45e-47b7-4712-b62c-438c4769314c
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss CCY - CAD (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss CCY - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: e06e39ad-65a8-4120-a0dc-ec0356b91a50
		sourceLineageTag: 3ff8cf37-09df-4de6-9c67-e8b438f2c521
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss CCY - FUNC (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss CCY - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: ee612cd8-e4e3-455c-8ef9-18cc7a2cc311
		sourceLineageTag: a92583db-dfe5-4200-9d70-b03a05b433c3
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss CCY - HKD (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss CCY - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 014f2468-8744-485e-a074-baa3df3a60a5
		sourceLineageTag: 69cfa36e-49a0-4c07-a01f-bd66c60ad2a7
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss CCY - USD (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss CCY - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: c22199ae-aad2-4ac8-a8fb-aa09d57bac08
		sourceLineageTag: 9abcee92-1bfd-41cc-b1dc-d752fac26ed1
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss Sec - CAD (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss Sec - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: a2210f2f-f626-471f-b6d3-22d08cd59854
		sourceLineageTag: 71b48d99-56ab-494f-9079-b177f1e2c10d
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss Sec - FUNC (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss Sec - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 619796f8-65ca-443f-96cd-149b898f0e7a
		sourceLineageTag: fbc308d3-525e-4f98-91d1-f508836b09b8
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss Sec - HKD (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss Sec - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 4166b62b-1b44-432e-9061-4d21d10e649c
		sourceLineageTag: 7cc97279-6d26-457d-9472-b7c90d048122
		dataCategory: Uncategorized

	measure 'Unrealized Gain/Loss Sec - USD (Sec Pos)' = EXTERNALMEASURE("Unrealized Gain/Loss Sec - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 39fbc9a8-54d0-4a96-a61a-358d6f1e1de7
		sourceLineageTag: ca8482fe-428d-4c88-934f-2d531ada84a1
		dataCategory: Uncategorized

	measure 'Balance CL Allowance - CAD (Sec Pos)' = EXTERNALMEASURE("Balance CL Allowance - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 49557fbe-d568-4abd-b890-0b07effb2453
		sourceLineageTag: e37201dc-5243-467e-b619-ff45ed8cdc83
		dataCategory: Uncategorized

	measure 'Balance CL Allowance - FUNC (Sec Pos)' = EXTERNALMEASURE("Balance CL Allowance - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: d30fbaed-545c-460f-b91f-59dc2d7dd1aa
		sourceLineageTag: 44dda5e7-3dad-4c2e-9f86-48af5700ef97
		dataCategory: Uncategorized

	measure 'Balance CL Allowance - HKD (Sec Pos)' = EXTERNALMEASURE("Balance CL Allowance - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 1fd8ab3c-7cd9-489e-aa59-83c4c59999e3
		sourceLineageTag: f8ca0ad6-632b-4040-a959-c803e4aca036
		dataCategory: Uncategorized

	measure 'Balance CL Allowance - USD (Sec Pos)' = EXTERNALMEASURE("Balance CL Allowance - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: a44070a0-9b78-46a3-8b82-79837ff406d7
		sourceLineageTag: d4017005-f7d6-4d1b-9f86-024d5a0bcc16
		dataCategory: Uncategorized

	measure 'Balance Expected Restitution - CAD (Sec Pos)' = EXTERNALMEASURE("Balance Expected Restitution - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 8f817600-3638-43f6-941d-6b60ce911799
		sourceLineageTag: daebf88f-e361-4998-8fe8-d8dd41fa1a79
		dataCategory: Uncategorized

	measure 'Balance Expected Restitution - HKD (Sec Pos)' = EXTERNALMEASURE("Balance Expected Restitution - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 74920fc0-b3e4-435b-9afc-2b26435a7224
		sourceLineageTag: 5830be5c-2f75-4830-8c9f-d4e04f82084a
		dataCategory: Uncategorized

	measure 'Balance Expected Restitution - FUNC (Sec Pos)' = EXTERNALMEASURE("Balance Expected Restitution - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 4cbc858a-54a3-4840-a141-e951bb4dc9b2
		sourceLineageTag: 9e328929-b2be-4f99-9e26-b3a9463b7b1a
		dataCategory: Uncategorized

	measure 'Balance Expected Restitution - USD (Sec Pos)' = EXTERNALMEASURE("Balance Expected Restitution - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 8ef5b3c3-d9ed-4de6-bef1-c00b9ce9167a
		sourceLineageTag: 1e22781d-b789-47aa-93dc-f13c25be8925
		dataCategory: Uncategorized

	measure 'Balance Impairment - CAD (Sec Pos)' = EXTERNALMEASURE("Balance Impairment - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: c7b98be2-b0b3-4b4f-9a45-a2c33cc26657
		sourceLineageTag: c2df1861-07f4-4325-9d07-4df194c0a1de
		dataCategory: Uncategorized

	measure 'Balance Impairment - FUNC (Sec Pos)' = EXTERNALMEASURE("Balance Impairment - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 68de89ac-e890-4351-9a15-9654191b761f
		sourceLineageTag: 4d78f154-04f8-4e75-957c-82dc0dd2adba
		dataCategory: Uncategorized

	measure 'Balance Impairment - HKD (Sec Pos)' = EXTERNALMEASURE("Balance Impairment - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 2708be0e-dd13-423e-909b-cb6a0815165a
		sourceLineageTag: 41852a38-0bf5-4ba4-b263-9c96c87359dd
		dataCategory: Uncategorized

	measure 'Balance Impairment - USD (Sec Pos)' = EXTERNALMEASURE("Balance Impairment - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 3a77a652-8549-4812-9dae-16d45f493d80
		sourceLineageTag: 580e4853-e2c6-4fd5-96de-5c7b319d297d
		dataCategory: Uncategorized

	measure 'Balance Int Appr - CAD (Sec Pos)' = EXTERNALMEASURE("Balance Int Appr - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 850f70b8-1697-44b1-869e-c229a0726253
		sourceLineageTag: 801aadd7-9802-404f-b87d-d2a0437b755c
		dataCategory: Uncategorized

	measure 'Balance Int Appr - FUNC (Sec Pos)' = EXTERNALMEASURE("Balance Int Appr - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 2722bdb0-255f-4464-854f-024112c0137f
		sourceLineageTag: 35755df4-f1a0-4e96-9898-fcefda9e1fc7
		dataCategory: Uncategorized

	measure 'Balance Int Appr - HKD (Sec Pos)' = EXTERNALMEASURE("Balance Int Appr - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 3136ec3d-e114-49c7-a7ee-a223e855633a
		sourceLineageTag: 9025b49a-b414-4299-ae57-b4caff82845b
		dataCategory: Uncategorized

	measure 'Balance Int Appr - USD (Sec Pos)' = EXTERNALMEASURE("Balance Int Appr - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: c8dd05a9-52ef-4f4f-ba0b-ea19fe04ceec
		sourceLineageTag: 7202a0c2-5420-4e41-a22a-885230f6a401
		dataCategory: Uncategorized

	measure 'Balance OID Appr - CAD (Sec Pos)' = EXTERNALMEASURE("Balance OID Appr - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: cd094ea6-808a-4bcf-aafd-cbfd4936c811
		sourceLineageTag: 63cab1a1-133e-403e-9952-bb9b2c25ff5b
		dataCategory: Uncategorized

	measure 'Balance OID Appr - FUNC (Sec Pos)' = EXTERNALMEASURE("Balance OID Appr - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: ecc7617a-2a7a-465d-b74f-2b15cfa02e96
		sourceLineageTag: dedd2e62-dde1-4635-bbc8-b9375124bb19
		dataCategory: Uncategorized

	measure 'Balance OID Appr - HKD (Sec Pos)' = EXTERNALMEASURE("Balance OID Appr - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 47173a95-4274-4515-b2cd-87002262ed9e
		sourceLineageTag: 6eb4afce-369b-42c7-a3bd-c64c81885802
		dataCategory: Uncategorized

	measure 'Balance OID Appr - USD (Sec Pos)' = EXTERNALMEASURE("Balance OID Appr - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 3cce1846-3964-491b-bef5-42221bd1885e
		sourceLineageTag: de474dbe-9cdb-4b25-94be-fc1c6ad48197
		dataCategory: Uncategorized

	measure 'Balance Recog CL Allowance - CAD (Sec Pos)' = EXTERNALMEASURE("Balance Recog CL Allowance - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: dbfb87e4-f077-4968-a479-1dc0515f40da
		sourceLineageTag: ec344bf9-ba61-4f20-aeee-bf96fc921c57
		dataCategory: Uncategorized

	measure 'Balance Recog CL Allowance - FUNC (Sec Pos)' = EXTERNALMEASURE("Balance Recog CL Allowance - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: bf6d56bb-ee0c-43ad-a571-588338192e7d
		sourceLineageTag: 3642412a-4694-4b69-bc41-1e272ce14c38
		dataCategory: Uncategorized

	measure 'Balance Recog CL Allowance - HKD (Sec Pos)' = EXTERNALMEASURE("Balance Recog CL Allowance - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 59b9c30b-ad14-412e-8a17-d7b338b2d0b1
		sourceLineageTag: 5fccefe3-8134-4084-963b-91890a26f6bf
		dataCategory: Uncategorized

	measure 'Balance Recog CL Allowance - USD (Sec Pos)' = EXTERNALMEASURE("Balance Recog CL Allowance - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 8f1a3beb-2300-43d0-b29d-43da169e4a8b
		sourceLineageTag: 93562432-df04-40ef-86e5-060a8b14cf45
		dataCategory: Uncategorized

	measure 'Balance Write Off - CAD (Sec Pos)' = EXTERNALMEASURE("Balance Write Off - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 387d231b-c02a-4a83-b451-412b7a495af7
		sourceLineageTag: 56fb54f6-1162-4987-bba0-895ca1eea898
		dataCategory: Uncategorized

	measure 'Balance Write Off - FUNC (Sec Pos)' = EXTERNALMEASURE("Balance Write Off - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: c3cacab6-72e7-4132-98f6-38bbf63e207a
		sourceLineageTag: 12b5e96b-b164-4228-bc6e-0d10a895ac10
		dataCategory: Uncategorized

	measure 'Balance Write Off - HKD (Sec Pos)' = EXTERNALMEASURE("Balance Write Off - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 1f1567f5-07ea-431d-a9b5-0c8b3a9e8e32
		sourceLineageTag: ff68eb39-551b-49ee-9984-d8022a136f1e
		dataCategory: Uncategorized

	measure 'Balance Write Off - USD (Sec Pos)' = EXTERNALMEASURE("Balance Write Off - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 1c737d9c-a48e-44d2-a61c-a55cf48c4602
		sourceLineageTag: 29f7609b-72d0-4b46-a1e0-a1d5baa4f744
		dataCategory: Uncategorized

	measure 'Next Payment - CAD (Sec Pos)' = EXTERNALMEASURE("Next Payment - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 426461d4-cf07-4ab9-a88a-dd5ce2919768
		sourceLineageTag: 07063cd8-78d7-41dd-adf6-123a58465474
		dataCategory: Uncategorized

	measure 'Next Payment - FUNC (Sec Pos)' = EXTERNALMEASURE("Next Payment - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: a24099dd-fb59-4294-bd92-22c05e51a009
		sourceLineageTag: 9bcd3538-399c-43a9-be23-9b6c6856d639
		dataCategory: Uncategorized

	measure 'Next Payment - HKD (Sec Pos)' = EXTERNALMEASURE("Next Payment - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 78f7f073-9b7a-4711-9fbd-5169473f94e7
		sourceLineageTag: b8b9f12c-94bf-4c18-9348-a7d7c809193f
		dataCategory: Uncategorized

	measure 'Next Payment - USD (Sec Pos)' = EXTERNALMEASURE("Next Payment - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: b92a6d91-c3b1-46fe-93af-2d1da4f616f8
		sourceLineageTag: b8a30e97-5b69-4cbc-814e-c8e6b6517358
		dataCategory: Uncategorized

	measure 'Withheld - USD (Sec Pos)' = EXTERNALMEASURE("Withheld - USD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 74cc73c2-71d9-4e36-874f-303abf56f288
		sourceLineageTag: 28b21861-890c-4218-b6e0-bd6013a3f193
		dataCategory: Uncategorized

	measure 'Withheld - HKD (Sec Pos)' = EXTERNALMEASURE("Withheld - HKD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 7aefe9f5-7f86-4dc4-8ecd-7cb39ff0ff9d
		sourceLineageTag: bfcb85e5-b78a-4319-87ab-2375a5dffbc4
		dataCategory: Uncategorized

	measure 'Withheld - FUNC (Sec Pos)' = EXTERNALMEASURE("Withheld - FUNC (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 52a65147-c51e-43a3-b6ae-2fb83d5f279c
		sourceLineageTag: 7cee5fce-4bd7-49a6-a18a-1e33c948e971
		dataCategory: Uncategorized

	measure 'Withheld - CAD (Sec Pos)' = EXTERNALMEASURE("Withheld - CAD (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Currency Measures
		lineageTag: 6d8f3bae-6c55-4945-aa4c-3a7bbe113daa
		sourceLineageTag: 6207f07b-4907-45c9-a610-2f0904e9f3b0
		dataCategory: Uncategorized

	measure 'FV Final - Local (Sec Pos)' = EXTERNALMEASURE("FV Final - Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 37bc258f-7695-426a-b79f-b5bfc8fe1999
		sourceLineageTag: 2713e153-31c0-41f3-83c8-b03ab5d5260b
		dataCategory: Uncategorized

	measure 'FV Final - Rep (Sec Pos)' = EXTERNALMEASURE("FV Final - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 6c409fc2-6936-48c2-94a2-c8db72ef1492
		sourceLineageTag: 3d3f9f9e-0609-40b3-9486-ab24cff97bbb
		dataCategory: Uncategorized

	measure 'SCD MTG Exp Maturity Dt (Sec Pos)' = EXTERNALMEASURE("SCD MTG Exp Maturity Dt (Sec Pos)", DATETIME, "DirectQuery to AS - Securities")
		formatString: General Number
		lineageTag: db73d8d3-6648-40c9-acf4-3db43806b4ea
		sourceLineageTag: ac44639f-b50b-4e65-bc05-a1f66585be28
		dataCategory: Uncategorized

	measure 'Ultimate parent company (Sec Pos)' = EXTERNALMEASURE("Ultimate parent company (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: a9965548-daf3-4238-82d3-d54bd93953c4
		sourceLineageTag: a0a0b337-18df-4e75-b55a-f1ee6c551925
		dataCategory: Uncategorized

	measure 'Ultimate parent LEI (Sec Pos)' = EXTERNALMEASURE("Ultimate parent LEI (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 191dc1c5-79de-4a10-94ea-003b9837b3cc
		sourceLineageTag: bdacfa1a-90d4-4a48-ba4d-9d92af91d76d
		dataCategory: Uncategorized

	measure 'Ultimate parent location (Sec Pos)' = EXTERNALMEASURE("Ultimate parent location (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 148177f0-288f-4ae8-83c8-383e3704b78a
		sourceLineageTag: 7e38ca77-19bb-4e7d-959f-66882d18b7f8
		dataCategory: Uncategorized

	measure 'NAIC Designation Modifier (Sec Pos)' = EXTERNALMEASURE("NAIC Designation Modifier (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 0d743c8f-b359-4aae-99e9-04ee2a438cfc
		sourceLineageTag: e57137d6-ee1d-4e52-a582-32b2af6d6d3a
		dataCategory: Uncategorized

	measure 'SCD Svo Suffix (Sec Pos)' = EXTERNALMEASURE("SCD Svo Suffix (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Values
		lineageTag: 57f7c1cc-2af0-412a-a6fa-63c9e67e1708
		sourceLineageTag: 067143d9-c9eb-4083-9e04-1090827f2261
		dataCategory: Uncategorized

	measure 'Make Whole Call Spread Num (Sec Pos)' = EXTERNALMEASURE("Make Whole Call Spread Num (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 988994c7-06cf-41a9-85e1-0c7187f25a57
		sourceLineageTag: e3950232-5031-4ee4-8df0-9adcf6e7e50d
		dataCategory: Uncategorized

	measure 'Make Whole Termination Dt (Sec Pos)' = EXTERNALMEASURE("Make Whole Termination Dt (Sec Pos)", DATETIME, "DirectQuery to AS - Securities")
		formatString: yyyy\-mm\-dd
		lineageTag: 6268cf75-d5d6-4e2f-ae8b-8fa28d620720
		sourceLineageTag: ae5e93db-e35e-497a-ad93-8e75136954a4
		dataCategory: Uncategorized

	measure 'Payment Method Name (Sec Pos)' = EXTERNALMEASURE("Payment Method Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 7b0dbee3-eeba-49d9-9f46-65f281a719fb
		sourceLineageTag: a08518c0-1497-483e-b8a8-8c467d9fd760
		dataCategory: Uncategorized

	measure 'SCD GL Classification (Sec Pos)' = EXTERNALMEASURE("SCD GL Classification (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 92250ce8-178f-4e8f-8d3c-87bdfe006fc7
		sourceLineageTag: 9daaeb2a-13ff-4474-8e72-2a97542f486b
		dataCategory: Uncategorized

	measure 'Make Whole Call (Sec Pos)' = EXTERNALMEASURE("Make Whole Call (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: abd6a64d-bc2c-4eb0-a0ea-96d8e7d40f7b
		sourceLineageTag: 97cda364-6816-4d82-bced-c1b8ea2c7343
		dataCategory: Uncategorized

	measure 'MFC Equivalent(Risk) (Sec Pos)' = EXTERNALMEASURE("MFC Equivalent(Risk) (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 66022289-b536-4c49-a14e-b4d4db9be7cc
		sourceLineageTag: 9ed99053-6f17-4b2f-9994-b9e1a40d1cd7
		dataCategory: Uncategorized

	measure 'SCD Instrument Category (Sec Pos)' = EXTERNALMEASURE("SCD Instrument Category (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: bcb60ec1-7ba9-4594-b631-45a598f34acd
		sourceLineageTag: 4a1739a6-5fa5-45d4-af1d-bd3252f9ee28
		dataCategory: Uncategorized

	measure 'Structure (Sec Pos)' = EXTERNALMEASURE("Structure (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 9bb3b06e-dc45-4078-8e54-ff6f8f5b7e27
		sourceLineageTag: 78694abf-4c7e-435d-a63b-39177e074463
		dataCategory: Uncategorized

	measure 'Issue Volume (Sec Pos)' = EXTERNALMEASURE("Issue Volume (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 98d5e223-d860-43a8-bca9-fc64d8acd0ea
		sourceLineageTag: 2f4ca94b-cb33-438c-9b94-c5b86d8aedfe
		dataCategory: Uncategorized

	measure 'Bank Account (Sec Pos)' = EXTERNALMEASURE("Bank Account (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 8cf272e0-c665-4a9f-8ee3-3f24173942be
		sourceLineageTag: 8409b1af-2464-478a-9714-01e92c4de2e9
		dataCategory: Uncategorized

	measure 'MIM Indicator (Sec Pos)' = EXTERNALMEASURE("MIM Indicator (Sec Pos)", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		lineageTag: f6ecec1e-c84a-473f-a560-23608811eb40
		sourceLineageTag: 0843e34c-4d53-424a-893c-6eb24f274f33
		dataCategory: Uncategorized

	measure 'Regulated Account Indicator (Sec Pos)' = EXTERNALMEASURE("Regulated Account Indicator (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: acb1fa22-ad98-475b-af15-2b7a6b59983e
		sourceLineageTag: 4d4d2bcf-3efa-4645-894b-11988c8ab44c
		dataCategory: Uncategorized

	measure 'Next Call Date (Sec Pos)' = EXTERNALMEASURE("Next Call Date (Sec Pos)", DATETIME, "DirectQuery to AS - Securities")
		formatString: yyyy\-mm\-dd
		lineageTag: bce6fa7b-d270-4529-be55-c25ea4de3426
		sourceLineageTag: 790f73f9-89a2-436d-8ba4-76e729ca9a2c
		dataCategory: Uncategorized

	measure 'MRM Issuer Name (Sec Pos)' = EXTERNALMEASURE("MRM Issuer Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 96c458d9-3cf9-45c8-ae10-e02201abab93
		sourceLineageTag: 9a6b34e8-062a-455d-a384-d913984f1c66
		dataCategory: Uncategorized

	measure 'MRM Issuer Irr Rating Cd (Sec Pos)' = EXTERNALMEASURE("MRM Issuer Irr Rating Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 5e8b6c64-4f18-4d86-8632-4d24ca09f4af
		sourceLineageTag: 51310178-0153-411b-84fd-dcc24e9f8884
		dataCategory: Uncategorized

	measure 'MRM Issuer Country Name (Sec Pos)' = EXTERNALMEASURE("MRM Issuer Country Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 41f18da7-b465-4aa6-b557-dc938efed485
		sourceLineageTag: 4ef77f9f-0efd-490a-992e-300db3de4cf3
		dataCategory: Uncategorized

	measure 'MRM Issuer Parent Name (Sec Pos)' = EXTERNALMEASURE("MRM Issuer Parent Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 05f80c0f-5872-458d-8221-840b3dcc8354
		sourceLineageTag: 7ed4412f-4900-493f-8ada-e15b523f36b2
		dataCategory: Uncategorized

	measure 'MRM Issuer Parent Country Name (Sec Pos)' = EXTERNALMEASURE("MRM Issuer Parent Country Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: b6b49bdb-d258-4b89-9e5d-6d904c9e2b43
		sourceLineageTag: fdfeb272-f9ea-4da8-ba91-808cd62a3158
		dataCategory: Uncategorized

	measure 'MRM Issuer Parent Irr Rating Cd (Sec Pos)' = EXTERNALMEASURE("MRM Issuer Parent Irr Rating Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: c4d46f34-b2da-48d0-9e82-4cdd3d7559c8
		sourceLineageTag: 129413f6-effe-4542-8279-68c1c90cf725
		dataCategory: Uncategorized

	measure 'MRM Issuer Ultparent Name (Sec Pos)' = EXTERNALMEASURE("MRM Issuer Ultparent Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: cd5a404e-6c06-4c3c-870f-5e3e67140888
		sourceLineageTag: 295995ee-34fd-4b53-a9c7-af19ae4bbf30
		dataCategory: Uncategorized

	measure 'MRM Issuer Ultparent Country Name (Sec Pos)' = EXTERNALMEASURE("MRM Issuer Ultparent Country Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 53bf2f43-27e6-451e-943e-258459fb42c1
		sourceLineageTag: 34b8c4a7-52e4-43f5-8e85-630af57e02d5
		dataCategory: Uncategorized

	measure 'MRM Issuer Ultparent Irr Rating Cd (Sec Pos)' = EXTERNALMEASURE("MRM Issuer Ultparent Irr Rating Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 5696cbab-297b-4eb6-83bc-182b0bb49155
		sourceLineageTag: da97bb3b-f456-4329-80e2-033c95461a51
		dataCategory: Uncategorized

	measure 'Equity Fund Ind (Sec Pos)' = EXTERNALMEASURE("Equity Fund Ind (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 62774836-b62c-435b-877a-e8078d40e35c
		sourceLineageTag: 600003b3-1504-4800-ab59-45711a5def2c
		dataCategory: Uncategorized

	measure 'GCLMS Collateral Quality Cd (Sec Pos)' = EXTERNALMEASURE("GCLMS Collateral Quality Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 4fc94ef0-9745-4dd3-8bca-2bc847f0c55a
		sourceLineageTag: 7aeb3b1b-501c-48d7-9e6b-1454d932227e
		dataCategory: Uncategorized

	measure 'MRM Issuer Cascade Rating Cd (Sec Pos)' = EXTERNALMEASURE("MRM Issuer Cascade Rating Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: c7fc2fc0-83f7-477e-a857-77347303e680
		sourceLineageTag: 6021c734-8c2d-4409-9533-689c5280df67
		dataCategory: Uncategorized

	measure 'MRM Issuer Parent Cascade Rating Cd (Sec Pos)' = EXTERNALMEASURE("MRM Issuer Parent Cascade Rating Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 340a0582-8f45-411b-91b8-3353af1e0fd8
		sourceLineageTag: da249cd6-dafd-4b60-abbd-b86b6820bfed
		dataCategory: Uncategorized

	measure 'MRM Issuer Ultparent Cascade Rating Cd (Sec Pos)' = EXTERNALMEASURE("MRM Issuer Ultparent Cascade Rating Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: a85280cc-1423-4de8-97e3-663bd353040d
		sourceLineageTag: 2edb1ab6-6728-4b33-b5af-b8c36c18e1be
		dataCategory: Uncategorized

	measure 'Cur Cpn (Sec Pos)' = EXTERNALMEASURE("Cur Cpn (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 8a45ec86-b8e6-479d-9395-c14ad9d6a6d1
		sourceLineageTag: 0b71dfa9-bacc-49b5-9f99-c7e42b78be02
		dataCategory: Uncategorized

	measure 'GCLMS Issuer Parent Cascade Rtg Cd (Sec Pos)' = EXTERNALMEASURE("GCLMS Issuer Parent Cascade Rtg Cd (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 362f7c37-45b9-49f2-b0b8-34e245b5c0e8
		sourceLineageTag: bf4f550c-1b17-453d-beaf-24bc99f5178d
		dataCategory: Uncategorized

	measure 'Guarantor Name (Sec Pos)' = EXTERNALMEASURE("Guarantor Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: f0e1fcc4-db66-43ac-b6fe-376a9ef5b08c
		sourceLineageTag: a34a5d2a-cbdb-4fdc-adff-591764dffd85
		dataCategory: Uncategorized

	measure 'Capital Structure Name (Sec Pos)' = EXTERNALMEASURE("Capital Structure Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: f897afbe-8dfd-4e9c-bd92-6f2972939b7b
		sourceLineageTag: 58fb3eaa-34c0-4dbb-b547-1410f1e02774
		dataCategory: Uncategorized

	measure 'Accrued Interest EOP - Rep (Sec Pos)' = EXTERNALMEASURE("Accrued Interest EOP - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 20028a15-5f2a-4328-af62-83f421a331d1
		sourceLineageTag: 6b5c84b2-41d1-4e72-b2e9-07a826be9a34
		dataCategory: Uncategorized

	measure 'Alt Fee Asset Name (Sec Pos)' = EXTERNALMEASURE("Alt Fee Asset Name (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: ca019dc5-3712-48ce-b3ac-7b1d8657c74b
		sourceLineageTag: 6902dd61-d6a0-4488-9a6a-9b7cbed339ac
		dataCategory: Uncategorized

	measure 'Callable (Sec Pos)' = EXTERNALMEASURE("Callable (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 8e7a9413-29f3-4b3c-b4fc-ea2423a23630
		sourceLineageTag: 15345207-98f9-457a-baad-d44a70d74723
		dataCategory: Uncategorized

	measure 'Accrued Interest PC Static(Sec Pos)' = EXTERNALMEASURE("Accrued Interest PC Static(Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 0fc7545a-e900-473c-9e3a-849967adc6b4
		sourceLineageTag: 1cfa9d8c-05e3-43ab-bb88-fd7a7efe4356
		dataCategory: Uncategorized

	measure 'Accrued Interest QC Static(Sec Pos)' = EXTERNALMEASURE("Accrued Interest QC Static(Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 0335aa3f-1d48-45ec-95bb-4bdcde3faeee
		sourceLineageTag: dc2d77a8-6531-48b9-b5a7-0a1f7d8c85f2
		dataCategory: Uncategorized

	measure 'Multi Cpn Schedule Typ (Sec Pos)' = EXTERNALMEASURE("Multi Cpn Schedule Typ (Sec Pos)", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		lineageTag: 57008a98-f0c2-4b9c-8b5c-8f68b5acd2fc
		sourceLineageTag: d7cd07f5-766b-4815-b13a-3f81514a1dac
		dataCategory: Uncategorized

	measure 'Ram Rating(Sec Pos)' = EXTERNALMEASURE("Ram Rating(Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 51cd232a-9925-46f7-b05e-fa5e69e5c7e2
		sourceLineageTag: ace8927b-39c4-499b-aa4a-b210d36b016f
		dataCategory: Uncategorized

	measure 'Marc Rating(Sec Pos)' = EXTERNALMEASURE("Marc Rating(Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 68b9bfa0-40e0-46a9-b8d2-091a5cf61e9e
		sourceLineageTag: 6698e8c0-cd2f-4504-8020-ec005a7359b2
		dataCategory: Uncategorized

	measure 'Trading Philosophy Code - IAS39 (Sec Pos)' = EXTERNALMEASURE("Trading Philosophy Code - IAS39 (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: d0c3c2ba-145d-4c2c-a55f-0cb744a006df
		sourceLineageTag: 040d093b-61f4-4485-b713-15c197bb0d59
		dataCategory: Uncategorized

	measure 'Trading Philosophy Code - IFRS (Sec Pos)' = EXTERNALMEASURE("Trading Philosophy Code - IFRS (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 03d307b7-8867-4c26-88e3-a8346ee89b62
		sourceLineageTag: 4848e043-56c9-44f4-aaee-8d6b5db7ed65
		dataCategory: Uncategorized

	measure 'Trading Philosophy Code - JGAAP (Sec Pos)' = EXTERNALMEASURE("Trading Philosophy Code - JGAAP (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 07faef04-56b3-4b62-b350-c5466e6a77d4
		sourceLineageTag: 18f978d5-8a51-4c73-bc1a-fcba9fca1bf2
		dataCategory: Uncategorized

	measure 'Trading Philosophy Code - USGAAP (Sec Pos)' = EXTERNALMEASURE("Trading Philosophy Code - USGAAP (Sec Pos)", STRING, "DirectQuery to AS - Securities")
		lineageTag: ad521c0d-d9f8-42ae-b935-edc67cfa34b9
		sourceLineageTag: 768dcfe1-946d-4912-aacf-6bdda8bc1da1
		dataCategory: Uncategorized

	measure 'Purpose Codes (Sec Pos) - TP' = EXTERNALMEASURE("Purpose Codes (Sec Pos) - TP", STRING, "DirectQuery to AS - Securities")
		lineageTag: b5b15373-1199-4a64-aa47-ee0cd06d630d
		sourceLineageTag: 24917079-629c-4ee6-9157-663c2143a0a2
		dataCategory: Uncategorized

	measure DupTradeDateCalc = ```
			/*var a = IF (
			    COUNTROWS ( 'Securities Position Fact' ) > 0,
			    CALCULATE (
			        min('Securities Transaction GA Fact'[Trade Date]),
			        TREATAS (
			            VALUES ( 'Securities Position Fact'[Src Position ID] ),
			            'Securities Transaction GA Fact'[POS Trans Link]
			        ),
			       
			        'Securities Transaction GA Fact'[Trans Status] = "Active",
			               ALLSELECTED ( Securities ),
			        VALUES ( Securities[Primary Security ID] )
			    )) return  CALCULATE('Securities Position Fact'[Book Value - Local], filter(Securities, DATEDIFF(a,Securities[Maturity Date], DAY) >= 90 && DATEDIFF(a,Securities[Maturity Date], DAY) <=365 && Securities[Maturity Date] <> BLANK()),'Securities Position Fact'[GL Class] = "MM" || 'Securities Position Fact'[GL Class] = "BOND")*/
			
			    // CALCULATE (
			    //     MIN ( 'Securities Transaction GA Fact'[Trade Date] ),
			    //     TREATAS (
			    //         VALUES ( 'Securities Position Fact'[Src Position ID] ),
			    //         'Securities Transaction GA Fact'[POS Trans Link]
			    //     ),
			    //     'Securities Transaction GA Fact'[Trans Status] = "Active",
			    //     ALLSELECTED ( Securities[Primary Security ID] )
			    // )
			
			    // CALCULATE (
			    //     MIN ( 'Securities Transaction GA Fact'[Trade Date] ),
			    //     TREATAS (
			    //        CALCULATETABLE( VALUES ( 'Securities Position Fact'[Src Position ID] ), 'Securities Position Fact'[GL Class] in {"MM","BOND"}),
			    //         'Securities Transaction GA Fact'[POS Trans Link]
			    //     ),
			    //     'Securities Transaction GA Fact'[Trans Status] = "Active",
			    //     ALLSELECTED(Securities[Primary Security ID]),
			    //     VALUES(Securities[Primary Security ID])
			    // )
			
			// VAR PosIDs =
			//     SELECTCOLUMNS (
			//         VALUES ( 'Securities Position Fact'[Src Position ID] ),
			//         "ID", FORMAT ( [Src Position ID], "0" )
			//     )
			// RETURN
			// CALCULATE (
			//     MIN ( 'Securities Transaction GA Fact'[Trade Date] ),
			//     'Securities Transaction GA Fact'[Trans Status] = "Active",
			//     'Securities Transaction GA Fact'[POS Trans Link] IN PosIDs
			// )
			// VAR PosIDs =
			//     SELECTCOLUMNS (
			//         VALUES ( 'Securities Position Fact'[Src Position ID] ),
			//         "Link", FORMAT ( 'Securities Position Fact'[Src Position ID], "0" )
			//     )
			
			// VAR TxnLinks =
			//     VALUES ( 'Securities Transaction GA Fact'[POS Trans Link] )
			
			// VAR CommonIDs =
			//     INTERSECT ( TxnLinks, PosIDs )
			
			// RETURN
			// CALCULATE (
			//     MIN ( 'Securities Transaction GA Fact'[Trade Date] ),
			//     'Securities Transaction GA Fact'[POS Trans Link] IN CommonIDs,
			//     'Securities Transaction GA Fact'[Trans Status] = "Active"
			// )
			
			// VAR PosIDs =
			//     VALUES ( 'Securities Position Fact'[Src Position ID] )
			
			// RETURN
			// CALCULATE (
			//     MIN ( 'Securities Transaction GA Fact'[Trade Date] ),
			//     'Securities Transaction GA Fact'[Trans Status] = "Active",
			//     'Securities Transaction GA Fact'[POS Trans Link] IN PosIDs
			// )
			// VAR FilteredPositions =
			//     CALCULATETABLE (
			//         DISTINCT ( 'Securities Position Fact'[Src Position ID] ),
			//         'Securities Position Fact'[GL Class] IN { "MM", "BOND" }
			//     )
			
			// RETURN
			// CALCULATE (
			//     MIN ( 'Securities Transaction GA Fact'[Trade Date] ),
			//     TREATAS (
			//         FilteredPositions,
			//         'Securities Transaction GA Fact'[POS Trans Link]
			//     ),
			//     'Securities Transaction GA Fact'[Trans Status] = "Active",
			//     KEEPFILTERS ( VALUES ( Securities[Primary Security ID] ) )
			// )
			VAR PositionIDs =
			    DISTINCT ( 'Securities Position Fact'[Src Position ID] )
			
			RETURN
			CALCULATE (
			    MIN ( 'Securities Transaction GA Fact'[Trade Date] ),
			    TREATAS (
			        PositionIDs,
			        'Securities Transaction GA Fact'[POS Trans Link]
			    ),
			    'Securities Transaction GA Fact'[Trans Status] = "Active",
			    KEEPFILTERS ( VALUES ( Securities[Primary Security ID] ) )
			)
			```
		formatString: General Date
		lineageTag: bc5772b0-c243-4ec6-b4ba-a101f07e5b78

		changedProperty = Name

	measure 'Income Impairment Details - Local (Sec Pos)' = EXTERNALMEASURE("Income Impairment Details - Local (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: b35e0011-ed41-4402-aa68-44d74bc0ab16
		sourceLineageTag: 57a78b81-e68c-4f8c-b404-0100ce5e7bdc
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income Impairment Details - Rep (Sec Pos)' = EXTERNALMEASURE("Income Impairment Details - Rep (Sec Pos)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: a222b679-9304-4309-9049-94f772fd8eab
		sourceLineageTag: ee49c0b1-a9e9-4dc8-bdea-aec82425e5cb
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dup Final Sch DA BACV' = ```
			
			// VAR TradeDate = CALCULATE (
			//         MIN ( 'Securities Transaction GA Fact'[Trade Date] ),
			//         TREATAS (
			//             VALUES ( 'Securities Position Fact'[Src Position ID] ),
			//             'Securities Transaction GA Fact'[POS Trans Link]
			//         ),
			//         'Securities Transaction GA Fact'[Trans Status] = "Active",
			//         ALLSELECTED ( Securities[Primary Security ID] )
			//     )
			// VAR TradeDate = [DupTradeDateCalc]    
			// VAR MaturityDate = MAX(Securities[Maturity Date])
			// VAR DaystoMat = MaturityDate-TradeDate
			// RETURN
			// IF(NOT ISBLANK(TradeDate) && NOT ISBLANK(MaturityDate) && DaystoMat>=90 && DaystoMat<=365,CALCULATE([Book Value - Local],'Securities Position Fact'[GL Class] in {"MM" ,"BOND"}))
			// VAR TradeDate =
			//     CALCULATE (
			//         [DupTradeDateCalc],
			//         REMOVEFILTERS ( Securities )  
			//     )
			
			// VAR MaturityDate =
			//     MAX ( Securities[Maturity Date] )
			
			// VAR DaystoMat =
			//     MaturityDate - TradeDate
			
			// RETURN
			// IF (
			//     NOT ISBLANK ( TradeDate )
			//         && NOT ISBLANK ( MaturityDate )
			//         && DaystoMat >= 90
			//         && DaystoMat <= 365,
			//     CALCULATE (
			//         [Book Value - Local],
			//         KEEPFILTERS ( 'Securities Position Fact'[GL Class] IN { "MM", "BOND" } )
			//     )
			// )
			// RETURN MaturityDate>=90 && MaturityDate<=365
			// VAR Days90 = TradeDate+90
			// VAR Days365 = TradeDate+365
			// VAR isindatarange = not ISBLANK(MaturityDate) && MaturityDate>=Days90 && MaturityDate<=Days365
			// var maturitydates = filter(all(Securities[Maturity Date]), Securities[Maturity Date] <> BLANK() && Securities[Maturity Date]>=Days90 && Securities[Maturity Date]<=Days365)
			// VAR validGLKeys = CALCULATETABLE(VALUES('Securities Position Fact'[Security NK]),'Securities Position Fact'[GL Class] in {"MM" ,"BOND"})
			// RETURN
			// IF (NOT ISBLANK(TradeDate) && isindatarange, CALCULATE([Book Value - Local],'Securities Position Fact'[GL Class] in {"MM" ,"BOND"}))
			// // IF (NOT ISBLANK(TradeDate), CALCULATE([Book Value - Local],maturitydates,TREATAS(validGLKeys,Securities[Security NK])))
			
			// var a = [DupTradeDateCalc] 
			// var maturitydates = filter(all(Securities[Maturity Date]), not ISBLANK( Securities[Maturity Date]) && DATEDIFF(a,Securities[Maturity Date], DAY) >= 90 && DATEDIFF(a,Securities[Maturity Date], DAY) <=365 )
			// return 
			// if (not ISBLANK(a), CALCULATE([Book Value - Local],maturitydates,'Securities Position Fact'[GL Class] in {"MM" ,"BOND"}))
			// //  CALCULATE('Securities Position Fact'[Book Value - Local], filter(Securities, DATEDIFF(a,Securities[Maturity Date], DAY) >= 90 && DATEDIFF(a,Securities[Maturity Date], DAY) <=365 && Securities[Maturity Date] <> BLANK()),'Securities Position Fact'[GL Class] = "MM" || 'Securities Position Fact'[GL Class] = "BOND")
			CALCULATE (
			    [Book Value - Local],
			    'Securities Position Fact'[GL Class] IN { "MM", "BOND" },
			    FILTER (
			        ALL ( Securities ),
			        VAR TradeDate =
			            CALCULATE (
			                MIN ( 'Securities Transaction GA Fact'[Trade Date] ),
			                TREATAS (
			                    DISTINCT ( 'Securities Position Fact'[Src Position ID] ),
			                    'Securities Transaction GA Fact'[POS Trans Link]
			                ),
			
			                'Securities Transaction GA Fact'[Trans Status] = "Active"
			            )
			        VAR MaturityDate = Securities[Maturity Date]
			        VAR DaysToMat = MaturityDate - TradeDate
			        RETURN
			            NOT ISBLANK ( TradeDate )
			                && NOT ISBLANK ( MaturityDate )
			                && DaysToMat >= 90
			                && DaysToMat <= 365
			    )
			)
			
			```
		lineageTag: 201f13b3-4c0b-4342-bdf0-fb55b3b23ed2

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Portfolio Code Extract' = MID('Securities Position Fact'[Portfolio Code], 2, 4)
		lineageTag: 37b7817f-c171-4b4a-bf78-fd8ba74baf01
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Primary ID_Final_Derived' = ```
			if(LEFT(related(Securities[Primary Security ID]),2) = "IE", related(Securities[ML Private Asset ID]),  
			if(isblank(related(Securities[Primary Security ID])), 'Securities Position Fact'[SCD Security ID], related(Securities[Primary Security ID])))
			```
		lineageTag: d5eb4136-1005-461a-a96c-a58d5b065bc6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PortSecKey
		dataType: string
		lineageTag: d296c881-7cf7-4bbf-a6ca-7e852feb5f48
		sourceLineageTag: 956b545b-7ff7-4fd2-a33c-4d7ddb5ec55b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: PortSecKey

		annotation SummarizationSetBy = Automatic

	column 'Month End Pos'
		dataType: string
		lineageTag: 0ed762ed-c39e-40b7-8713-312404a03fec
		sourceLineageTag: e9e68a8d-2585-465b-85ae-56509e1ac90c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Month End Pos

		annotation SummarizationSetBy = Automatic

	column 'Asset Group (Sec Pos)'
		dataType: string
		displayFolder: Security Values
		lineageTag: 76fa3173-bd89-4128-afdc-7ad18900b7cd
		sourceLineageTag: d31eff90-468b-4ef3-8d2e-366338725581
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asset Group (Sec Pos)

		annotation SummarizationSetBy = Automatic

	column 'Security ID (Slicer -Sec Pos)'
		dataType: string
		lineageTag: 4d352a4b-8481-43f3-8cf1-872c73b576ea
		sourceLineageTag: 89a3034e-34a7-41ee-8b8a-e8fc62d6b4dc
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security ID (Slicer -Sec Pos)

		annotation SummarizationSetBy = Automatic

	column 'Asset Type (Sec Pos)'
		dataType: string
		displayFolder: Security Values
		lineageTag: 7f19513f-a139-48be-a4bd-63d7f2babfa1
		sourceLineageTag: a71e5033-c78c-402d-bf20-8a5e63c3ddf1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asset Type (Sec Pos)

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID & Desc (Sec Pos)'
		dataType: string
		lineageTag: 40dff3ed-6927-424f-b645-ce0fa6e1962c
		sourceLineageTag: bb46d145-0607-4444-acbf-fd6b8c11ec5c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Primary Security ID & Desc (Sec Pos)

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID (Sec Pos)'
		dataType: string
		lineageTag: 6aae4f78-ccf9-479f-9a80-9d113d4dc104
		sourceLineageTag: 3de0f8e2-592f-425e-b6af-0e6adc65351e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Primary Security ID (Sec Pos)

		annotation SummarizationSetBy = Automatic

	column 'Company Code & Name Display'
		dataType: string
		lineageTag: aa06dfa3-6ded-46d9-9e69-9e270f68be67
		sourceLineageTag: 62b9ab91-61ef-4a71-85d0-b2f08fb708b2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Company Code & Name Display

		annotation SummarizationSetBy = Automatic

	column 'Accounting Unit Code & Name Display'
		dataType: string
		lineageTag: 41fe7d31-6f3f-43dd-8e1b-57dad2897152
		sourceLineageTag: 9f8cc959-f238-4994-af26-4526b6ff02fe
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Accounting Unit Code & Name Display

		annotation SummarizationSetBy = Automatic

	column 'Public/Private Indicator'
		dataType: string
		lineageTag: 5a247ad2-51f9-4081-8963-9e7286ff1f25
		sourceLineageTag: c2ac8829-304b-4d18-b93b-11068c14de31
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Public/Private Indicator

		annotation SummarizationSetBy = Automatic

	column 'FX Join Key'
		dataType: string
		lineageTag: f8039bf6-e10b-44a2-8c0e-a3a6ee21c3a0
		sourceLineageTag: 0498295e-6d22-45e7-a7e3-3a32f984bc2c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: FX Join Key

		annotation SummarizationSetBy = Automatic

	column 'Coupon Freq Description'
		dataType: string
		lineageTag: 20e9756f-3a51-4d64-bb34-4a75d02c43be
		sourceLineageTag: d5b182c4-02c9-4958-993e-ae568f1816c7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Coupon Freq Description

		annotation SummarizationSetBy = Automatic

	column Country_Blank_nk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8f861124-35f2-4127-8270-91b5037898dd
		sourceLineageTag: 4a3a34eb-be24-4725-8066-d785b28467cc
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Country_Blank_nk

		annotation SummarizationSetBy = Automatic

	column 'Ml Pricing Source'
		dataType: string
		isHidden
		lineageTag: f6650a06-28e9-4993-ba44-3e50d5c6a537
		sourceLineageTag: 77e2dbd3-b9e8-4102-ab05-c537d62d3af6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Ml Pricing Source

		annotation SummarizationSetBy = Automatic

	column 'Latest As of Dt Slicer(Sec Pos)'
		dataType: string
		isHidden
		lineageTag: be8b5da1-a254-483d-90d3-a79842753810
		sourceLineageTag: 9c80448d-46de-4e5c-bfbe-2ad2974f6275
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Latest As of Dt Slicer(Sec Pos)

		annotation SummarizationSetBy = Automatic

	column 'Indonesian Price (Indo Pos)'
		dataType: double
		displayFolder: Indonesian Positions Attributes
		lineageTag: a05e4c9f-fe92-44a7-8500-ff8a22c13362
		sourceLineageTag: 4e5ae060-ff89-4e86-b3a6-6e367c2c0c85
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Indonesian Price (Indo Pos)

		annotation SummarizationSetBy = Automatic

	column 'Reset Freq Description'
		dataType: string
		lineageTag: 02e92111-c629-4254-aabe-9574461ef0d7
		sourceLineageTag: 0fb3c1a8-f584-4532-98ed-61b78e231ade
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Reset Freq Description

		annotation SummarizationSetBy = Automatic

	column 'ML IRR Rating'
		dataType: string
		lineageTag: dbca12f8-8f2f-415a-bc02-6200f6dcf03c
		sourceLineageTag: 19a18f13-d184-4d02-b9ba-33e1a7e55078
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML IRR Rating

		annotation SummarizationSetBy = Automatic

	column 'Process Flag'
		dataType: string
		lineageTag: b5b3489d-5756-44a2-88bb-3b77a06ea867
		sourceLineageTag: 2499c9ae-dc75-4100-ad7e-f60d91ebac48
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Process Flag

		annotation SummarizationSetBy = Automatic

	column 'SCD Impairment Tran Code'
		dataType: string
		lineageTag: 7861f964-4d0d-4db0-9218-1e81a4a466ac
		sourceLineageTag: 546833b7-1226-4ee3-b383-23b51a998975
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Impairment Tran Code

		annotation SummarizationSetBy = Automatic

	column 'Original Drop %'
		dataType: double
		lineageTag: 6d024818-b771-49e1-81b3-fd14fdf6620f
		sourceLineageTag: fcc1ea21-51b5-495b-be9c-8400f33a53e5
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Original Drop %

		annotation SummarizationSetBy = Automatic

	column 'Current Drop %'
		dataType: double
		lineageTag: 4240d99d-e337-47c4-b8f7-2ae736e81ba2
		sourceLineageTag: b23ce307-9feb-4874-913f-48c8ea0da820
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Current Drop %

		annotation SummarizationSetBy = Automatic

	column 'Company Code'
		dataType: string
		lineageTag: 4f3120e7-3aac-4136-a6b1-52e518dc5140
		sourceLineageTag: 155ad89b-3300-4fff-82fe-0bd1a6c9f1ca
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Company Code

		annotation SummarizationSetBy = Automatic

	column 'Accounting Unit Code'
		dataType: string
		lineageTag: 04e5659a-157d-4fa8-986d-b6686d3d2e5d
		sourceLineageTag: c4c3cd3d-def3-4540-ba65-2a383e1457aa
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Accounting Unit Code

		annotation SummarizationSetBy = Automatic

	column 'Asset Class (Sec Pos)'
		dataType: string
		lineageTag: b0bdb16f-b378-4df7-aa92-cd7402d2d2c9
		sourceLineageTag: 631a0c36-4db9-4163-aa8e-874d44a1f781
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asset Class (Sec Pos)

		annotation SummarizationSetBy = Automatic

	column 'As of date Slicer Formatted'
		dataType: string
		lineageTag: eedbcef6-9590-4ec8-bad8-8e54413152f3
		sourceLineageTag: 1922a073-c55b-48d5-aba0-18de1e625a33
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: As of date Slicer Formatted

		annotation SummarizationSetBy = Automatic

	column 'Blue Book Code (Position Only OIA Securities)'
		dataType: string
		lineageTag: af061e7c-0b74-4f73-a891-c96188f899b9
		sourceLineageTag: 519b5cae-073f-4fc3-8914-7179ab06138a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Blue Book Code (Position Only OIA Securities)

		annotation SummarizationSetBy = Automatic

	column 'Security NK'
		dataType: string
		lineageTag: a83ee990-8b77-4170-82d1-5b6e52ec9169
		sourceLineageTag: 53ebc379-12e9-47e7-bbec-be4f34f626d3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security NK

		annotation SummarizationSetBy = Automatic

	column 'Security Payment NK'
		dataType: string
		lineageTag: 45f45c74-c1ba-43ff-b921-fd05391ca16c
		sourceLineageTag: 3ad9e90a-2bb8-40ca-9885-4314f8b0aa3d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security Payment NK

		annotation SummarizationSetBy = Automatic

	column 'As Of Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: d0442a0d-ffa3-4e14-b868-ed0bd4755782
		sourceLineageTag: ac99b5f9-7ca1-47ce-a117-11982c959412
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: As Of Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column 'As Of Period'
		dataType: int64
		formatString: 0
		lineageTag: 64916355-b64e-4ff7-add5-fcfc670c2165
		sourceLineageTag: 4d702d53-544a-46b3-936b-4f5f48a357c1
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: As Of Period

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 6f9bbb27-2e78-42e2-b738-4fa014423c06
		sourceLineageTag: 165dd14b-de90-4935-9630-d39478105890
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Src Position ID'
		dataType: int64
		formatString: 0
		lineageTag: 494a3752-76e2-459e-952a-d721b59223b9
		sourceLineageTag: 655af53f-e837-4bd4-98bb-7601a516ac19
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: Src Position ID

		annotation SummarizationSetBy = Automatic

	column 'Src Security ID'
		dataType: string
		lineageTag: 3465d854-0a60-4c6b-9e80-d6723f7dcae8
		sourceLineageTag: 0f8f1474-5562-4882-a5df-5013c5001487
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Src Security ID

		annotation SummarizationSetBy = Automatic

	column 'Src Market ID'
		dataType: string
		lineageTag: c8f78f3d-0871-4510-ae84-47fcfd4072e4
		sourceLineageTag: 68ffff22-72b4-4697-9fea-d16d386da6af
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Src Market ID

		annotation SummarizationSetBy = Automatic

	column 'Src Security'
		dataType: string
		lineageTag: d9861d75-fc6f-4310-aff8-fdd52523df88
		sourceLineageTag: 2b9679e7-a31c-4199-8000-5a2abd1d302e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Src Security

		annotation SummarizationSetBy = Automatic

	column 'Asset Portfolio Code'
		dataType: string
		lineageTag: db8a27e6-1a7e-4932-a5d5-4f549689ae58
		sourceLineageTag: 83f101bc-e65f-463e-bd40-18acf7c75b49
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asset Portfolio Code

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Group Code'
		dataType: string
		lineageTag: 0cb22f95-2aee-432b-8ae6-1abf1146539e
		sourceLineageTag: 2ceed88d-d0b9-452a-9543-8d3b6f0df96e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Portfolio Group Code

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Code'
		dataType: string
		lineageTag: 0213560d-1dc6-4744-bc24-b9572f21aae0
		sourceLineageTag: 167a632e-40a9-4c34-b39f-75f7275342b2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Portfolio Code

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Nk'
		dataType: string
		lineageTag: ebb57d05-8238-4453-8bf9-418ee0f7335e
		sourceLineageTag: a090c229-8caf-4b37-938b-1d13b4ccbec0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Portfolio Nk

		annotation SummarizationSetBy = Automatic

	column 'Framework Code'
		dataType: string
		lineageTag: 582ddaf2-6663-401e-94e1-816753bd75b2
		sourceLineageTag: 5fbe28e6-6405-49c2-8512-ec6a5ecdbb2a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Framework Code

		annotation SummarizationSetBy = Automatic

	column 'GL Class'
		dataType: string
		lineageTag: 8ad772ec-152e-4a29-b719-ccccdcc687c6
		sourceLineageTag: b3c1a642-e125-41bc-a052-a9a88999b04a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: GL Class

		annotation SummarizationSetBy = Automatic

	column 'Wash Sale Parent Security ID'
		dataType: string
		lineageTag: 8813391c-a648-4d51-97b4-2d023428b0c3
		sourceLineageTag: 1287b767-777d-4983-89e4-99c3a4c8b9dc
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Wash Sale Parent Security ID

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Code & Name'
		dataType: string
		lineageTag: d5de806c-92b7-48e2-a956-53d5a2a7aade
		sourceLineageTag: 4270fdd6-60df-487e-a818-f9c647c600c2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Portfolio Code & Name

		annotation SummarizationSetBy = Automatic

	column 'Accounting Unit Code & Name'
		dataType: string
		lineageTag: cac2282a-6aba-4459-8054-7d69e5907355
		sourceLineageTag: c9d453a3-4982-4d16-9208-746df5a55d60
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Accounting Unit Code & Name

		annotation SummarizationSetBy = Automatic

	column 'Company Code & Name'
		dataType: string
		lineageTag: d43c2c41-733b-46a7-89fc-0376ab03c8bc
		sourceLineageTag: 87d340d8-c102-4987-9cd1-0f2d1a08d338
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Company Code & Name

		annotation SummarizationSetBy = Automatic

	column 'SCD Security ID'
		dataType: string
		lineageTag: 19fb9237-bcef-44b3-98dc-3891d57c7bcd
		sourceLineageTag: 5c8b5f4f-1937-4407-b0a3-de3579d23c3a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Security ID

		annotation SummarizationSetBy = Automatic

	column Leg
		dataType: double
		lineageTag: 3458c15b-809a-460a-bc5e-a58773b6bce7
		sourceLineageTag: 305d252f-3ad8-4d37-8cce-d02f1fe139c1
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Leg

		annotation SummarizationSetBy = Automatic

	column 'Calculated Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd hh:nn:ss AM/PM
		lineageTag: 76ec2b00-fb5f-4580-b967-da4de436cc75
		sourceLineageTag: 74d61306-9fb8-4fa6-809b-2048565c5ea9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Calculated Date

		annotation SummarizationSetBy = Automatic

	column 'Units (D)'
		dataType: double
		lineageTag: 5cf8294f-aeda-4a80-9d5b-387cdcdde0eb
		sourceLineageTag: b6dd429c-b72a-4801-8f6d-df55476d64aa
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Units (D)

		annotation SummarizationSetBy = Automatic

	column Contracts
		dataType: double
		lineageTag: 74bfe967-1d07-41d8-b9ca-faad448facc0
		sourceLineageTag: be3cfdda-429d-4843-a1c6-cde61f28c602
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Contracts

		annotation SummarizationSetBy = Automatic

	column 'Settle Trade Balance'
		dataType: double
		lineageTag: 79eb4613-cb92-4e48-b8cd-87c2a262502a
		sourceLineageTag: b587b345-e7a9-4847-8a17-675511b6d477
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Settle Trade Balance

		annotation SummarizationSetBy = Automatic

	column 'Original Face (D)'
		dataType: double
		lineageTag: 4a0f95fb-74af-44e6-97c4-52ed50fceca4
		sourceLineageTag: e0ee0949-0115-4715-a0bf-92948c94160e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Original Face (D)

		annotation SummarizationSetBy = Automatic

	column 'Pool Factor'
		dataType: double
		lineageTag: 582912cb-7aa7-432d-961c-5e62a9fd1c63
		sourceLineageTag: ca18e94f-deb8-44a3-b7a2-32d0c59eb44c
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Pool Factor

		annotation SummarizationSetBy = Automatic

	column 'Unit Basis'
		dataType: string
		lineageTag: e5e41feb-fe1b-4593-92bc-e556d3ea81a8
		sourceLineageTag: 0ffd1a17-b791-483e-824f-137dc5b0b090
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Unit Basis

		annotation SummarizationSetBy = Automatic

	column 'Nominal (D)'
		dataType: double
		lineageTag: d26c043b-77bd-4777-a589-213773b465b4
		sourceLineageTag: d305b1cf-9e7c-4a9c-89c1-3d98ff251275
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Nominal (D)

		annotation SummarizationSetBy = Automatic

	column 'Quote Factor'
		dataType: double
		lineageTag: 7547d2d2-cfdf-47ef-a3fb-82ade1ce2963
		sourceLineageTag: 8a002358-1b02-4283-8fb3-dfc25c5ca5c4
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Quote Factor

		annotation SummarizationSetBy = Automatic

	column 'Current Face (D)'
		dataType: double
		lineageTag: 7dacf846-f774-4f1a-b996-bb860304e581
		sourceLineageTag: 2f9514fa-fdc1-4221-b2df-a2e76e276522
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Current Face (D)

		annotation SummarizationSetBy = Automatic

	column 'Fair Value Accrued - Base'
		dataType: double
		lineageTag: 04a05762-b6e1-4d9d-814f-178526b735b8
		sourceLineageTag: c14e5ae7-52f7-4ef3-ab8b-23e6071482fe
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Fair Value Accrued - Base

		annotation SummarizationSetBy = Automatic

	column 'Fair Value Unaccrued - Base'
		dataType: double
		lineageTag: 5475fced-9a07-4745-9c87-57a41a5f06d0
		sourceLineageTag: e7939490-ecd2-4d28-84de-0daa59aa8449
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Fair Value Unaccrued - Base

		annotation SummarizationSetBy = Automatic

	column 'Original Cost - Base'
		dataType: double
		lineageTag: 8f4baa59-767f-4407-a8b5-bc58c63f022e
		sourceLineageTag: fb41c3e9-3efd-4953-9d3c-8a58474ef95f
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Original Cost - Base

		annotation SummarizationSetBy = Automatic

	column 'Price - Base'
		dataType: double
		lineageTag: f74bd69b-f1fd-4553-af58-40b0598d0ae7
		sourceLineageTag: b9056c3e-05ab-4d1d-96d0-2378a4d4f44e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Price - Base

		annotation SummarizationSetBy = Automatic

	column 'Unit Cost - Base'
		dataType: double
		lineageTag: 27f3b494-f2f0-460d-a3ad-64cecb511f3a
		sourceLineageTag: 92562e9d-0572-446b-bc14-fef355b20e7b
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Unit Cost - Base

		annotation SummarizationSetBy = Automatic

	column 'Unrealized Gain/Loss CCY - Base'
		dataType: double
		lineageTag: aa87fd35-511a-4272-aab1-c1957e39c9e2
		sourceLineageTag: dbb4743a-4a0e-4b5d-8b20-9b4f777cace8
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss CCY - Base

		annotation SummarizationSetBy = Automatic

	column 'Unrealized Gain/Loss Sec - Base'
		dataType: double
		lineageTag: 88d0cac2-d875-48d8-9809-d4d6cade820b
		sourceLineageTag: 5229cb96-0f28-4355-bd24-8703994f8434
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss Sec - Base

		annotation SummarizationSetBy = Automatic

	column 'Unrealized Gain/Loss - Base'
		dataType: double
		lineageTag: aef8babc-c545-4616-b80d-a7135f51d384
		sourceLineageTag: 8da742e5-caf2-4911-8f8e-e755ef58419f
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss - Base

		annotation SummarizationSetBy = Automatic

	column 'Accrual - Base'
		dataType: double
		lineageTag: 09f00b57-3a9c-45bb-aff1-9262d2a3e020
		sourceLineageTag: 892181c6-1807-40af-a9ae-de7634b75de9
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Accrual - Base

		annotation SummarizationSetBy = Automatic

	column 'Withheld - Base'
		dataType: double
		lineageTag: 4ed47f78-9927-4738-9fb7-8007288138b8
		sourceLineageTag: 577091a2-f77e-47ac-8e31-281ea0d42215
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Withheld - Base

		annotation SummarizationSetBy = Automatic

	column 'Withholding Rate'
		dataType: double
		lineageTag: b9dfd036-d9b3-4593-88c5-482e11a093e1
		sourceLineageTag: f080fc22-10b7-4b81-8c32-82d7ab7aa840
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Withholding Rate

		annotation SummarizationSetBy = Automatic

	column 'Local Exchange Rate'
		dataType: double
		lineageTag: d88b6ede-438c-423a-8e9e-c51cb62f839e
		sourceLineageTag: 4860150d-5a45-4fc4-9748-ff5782299f48
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Local Exchange Rate

		annotation SummarizationSetBy = Automatic

	column 'Fair Value Accrued - Local (D)'
		dataType: double
		lineageTag: a98d2c0a-33f3-4d05-9b86-3c7f6969853e
		sourceLineageTag: 4161339a-401a-4b6f-92cd-bea67cdfad60
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Fair Value Accrued - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Accounting Status'
		dataType: string
		lineageTag: 67b43ed1-cc54-4a2f-9a46-f10b1abfb95b
		sourceLineageTag: c8d7a23a-6a59-4272-9469-28eb3cae5f06
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Accounting Status

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Calculation'
		dataType: string
		lineageTag: 260e6946-90da-44f1-bd33-8738fad50ec1
		sourceLineageTag: c7860a14-6faa-49f6-afc7-0e2e79c5bd79
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Portfolio Calculation

		annotation SummarizationSetBy = Automatic

	column 'Fair Value Unaccrued - Local (D)'
		dataType: double
		lineageTag: 60f285e2-56dd-46ae-a200-c3165e8c6568
		sourceLineageTag: 823b86e7-fd78-4632-ba0e-789f408f4aa1
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Fair Value Unaccrued - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Price - Local (D)'
		dataType: double
		lineageTag: b5b5c7c5-7a92-4011-b662-cea1c56e66e5
		sourceLineageTag: 63c0c6f4-536b-4a9e-8f91-481c0a62c6b5
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Price - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Original Cost - Local (D)'
		dataType: double
		lineageTag: 765e277d-7020-4cdd-a49d-ce4894deee2d
		sourceLineageTag: 12f738cb-f1ce-4189-91b0-7d277dea398e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Original Cost - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Unit Cost - Local (D)'
		dataType: double
		lineageTag: ba7daaea-eea6-440b-828e-cf498e1c5739
		sourceLineageTag: 0d603ea5-fc14-4108-a6ee-9773b4bd33bf
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Unit Cost - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Unrealized Gain/Loss CCY - Local (D)'
		dataType: double
		lineageTag: 5170df86-3595-4bac-ad57-5370d815cf03
		sourceLineageTag: dc30070c-4db4-4f66-bac6-4626386f7258
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss CCY - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Unrealized Gain/Loss Sec - Local (D)'
		dataType: double
		lineageTag: edd5bf13-7fed-4e31-9fbc-0569d8193040
		sourceLineageTag: 90215048-425c-498c-a7df-1365927b477f
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss Sec - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Unrealized Gain/Loss - Local (D)'
		dataType: double
		lineageTag: 68a6a59e-d7ee-4be4-9458-ed05705caf4a
		sourceLineageTag: fb6efe40-43f9-4fc2-be22-760bfb544265
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Accrual - Local (D)'
		dataType: double
		lineageTag: 32ed4416-6f26-4142-b040-9387b87be34d
		sourceLineageTag: 162d0b50-20fb-4c0b-9fc9-f611454e9da8
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Accrual - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Withheld - Local (D)'
		dataType: double
		lineageTag: 0095b0a4-e0d3-4bdc-a782-11192e9fa591
		sourceLineageTag: 7dc18825-e479-48e5-84d4-55edca5850f8
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Withheld - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Amortized Cost - Base'
		dataType: double
		lineageTag: c768dc0d-9637-4483-87e1-beee811fae72
		sourceLineageTag: a7885a77-3511-4966-b770-eb1bb5c540d1
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Amortized Cost - Base

		annotation SummarizationSetBy = Automatic

	column Yield
		dataType: double
		lineageTag: 9deb3ebf-5ed9-4d3c-8f7f-8126b42de8da
		sourceLineageTag: 02b9ce97-366e-4430-9cf6-eea07a380343
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Yield

		annotation SummarizationSetBy = Automatic

	column 'Yield To Worst'
		dataType: double
		lineageTag: 5ed09a26-b81b-4649-a0b5-60946856a76a
		sourceLineageTag: 8b0c6ca0-948c-4ee0-9bba-09d08c487a49
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Yield To Worst

		annotation SummarizationSetBy = Automatic

	column 'Underlier Security Nk'
		dataType: string
		lineageTag: 3916e307-462c-4a12-8bff-6a9ecc5ccfe2
		sourceLineageTag: f128ddf1-463f-4c82-8da8-1f285c92e6cd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Underlier Security Nk

		annotation SummarizationSetBy = Automatic

	column Local
		dataType: string
		lineageTag: 53e3dccf-afc2-44ef-a57c-18813a77fee1
		sourceLineageTag: 991591fa-83c1-40ef-8ba1-c0dc20fbb9fd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Local

		annotation SummarizationSetBy = Automatic

	column Base
		dataType: string
		lineageTag: dd5f428a-8a13-45ed-b32e-a0ef600fb277
		sourceLineageTag: 928b6905-2f1f-414c-8a39-da35b88a3b29
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Base

		annotation SummarizationSetBy = Automatic

	column 'Local Currency'
		dataType: string
		lineageTag: 4de86916-b3d2-4f31-883c-d2ae379f1fc7
		sourceLineageTag: 5bf69dcd-3c83-4895-b367-892ed0ed42ce
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Local Currency

		annotation SummarizationSetBy = Automatic

	column 'SCD Country'
		dataType: string
		lineageTag: 1595eb68-56a6-49bc-ac2c-843bd121a8c2
		sourceLineageTag: feba8fcd-62a1-4de2-8d68-6e3fec44fa8d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Country

		annotation SummarizationSetBy = Automatic

	column 'Country Name'
		dataType: string
		lineageTag: d8a75667-eb91-4a15-aa50-bb390fc43bf2
		sourceLineageTag: c6887d68-69e6-4f34-a833-27d1cd3c52d0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Country Name

		annotation SummarizationSetBy = Automatic

	column 'Maturity Date Final'
		dataType: dateTime
		isHidden
		formatString: yyyy\-mm\-dd
		lineageTag: 806efad6-5004-4e95-9543-4b8dcd87e8a0
		sourceLineageTag: 1ef9349a-0b58-454a-ae68-a192a2b95360
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Maturity Date Final

		annotation SummarizationSetBy = Automatic

	column 'SCD Coupon (D)'
		dataType: double
		lineageTag: 24a010cd-73f8-4d60-854b-98517b33374f
		sourceLineageTag: cd59abc0-eedd-466b-baf2-d179bab122bb
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: SCD Coupon (D)

		annotation SummarizationSetBy = Automatic

	column 'Next Payment - Local'
		dataType: double
		lineageTag: aed4cb05-3a91-43eb-8716-fb1ff43065b2
		sourceLineageTag: 6de685bf-1df4-4651-bb20-aa4b45254dd8
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Next Payment - Local

		annotation SummarizationSetBy = Automatic

	column 'Next Payment - Base'
		dataType: double
		lineageTag: e2bd53c6-6e2a-49f0-9e7b-d65a85f769b6
		sourceLineageTag: b0cfcda0-9407-4ef8-b6d0-60fddeb6f3ec
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Next Payment - Base

		annotation SummarizationSetBy = Automatic

	column 'Repo Maturity Amount'
		dataType: double
		lineageTag: 82f80b86-4a8f-4a56-b33d-9b458503d15c
		sourceLineageTag: 06d73a4f-c2ca-4d84-acfd-aa845b931af3
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Repo Maturity Amount

		annotation SummarizationSetBy = Automatic

	column 'Index Value'
		dataType: double
		lineageTag: 50a39ee9-cab9-4084-8ce0-037a5cd83fb7
		sourceLineageTag: f248a229-c64d-4aa8-b7c6-9d7466806669
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Index Value

		annotation SummarizationSetBy = Automatic

	column 'Composite ID BB Global'
		dataType: string
		lineageTag: 1dc3e455-aa3c-4af7-8ecd-87386f24b0ca
		sourceLineageTag: 7e304bf6-469c-401a-98a3-a24875189673
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Composite ID BB Global

		annotation SummarizationSetBy = Automatic

	column Counterparty
		dataType: string
		lineageTag: ac6cc9c6-9e22-4890-bd3c-e28a06264ed5
		sourceLineageTag: 0cd077bf-a6a3-4622-853f-0af8ccbcf28e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Counterparty

		annotation SummarizationSetBy = Automatic

	column 'Ultimate Parent Country'
		dataType: string
		lineageTag: 401ca8fd-08e2-45eb-a021-632b95fad546
		sourceLineageTag: d87fab2a-6157-4b99-87fc-34287e097e44
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Ultimate Parent Country

		annotation SummarizationSetBy = Automatic

	column 'Next Coupon Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: bd07f8bf-9fe7-46f2-b393-764774b43a20
		sourceLineageTag: 266cd908-687d-4eb9-a725-067a9d1ca21e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Next Coupon Date

		annotation SummarizationSetBy = Automatic

	column 'SCD Security Type'
		dataType: string
		lineageTag: 9d0c9f18-f06f-44ed-970b-94005bf2586e
		sourceLineageTag: 909cf378-d0fe-4512-8ae9-c7bb858ad716
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Security Type

		annotation SummarizationSetBy = Automatic

	column 'St Classification'
		dataType: string
		lineageTag: 31ae1b0e-1e84-4868-85fe-d4a8146ee927
		sourceLineageTag: 5d15c606-6d1b-4e16-b212-259cb55a5718
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: St Classification

		annotation SummarizationSetBy = Automatic

	column 'Equity Asset Class'
		dataType: string
		lineageTag: f9f639a4-a7a9-47f2-8498-75eafb12e72a
		sourceLineageTag: a42ba4f4-236d-48cf-bbda-dbde71052d96
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Equity Asset Class

		annotation SummarizationSetBy = Automatic

	column 'Fixed Income Asset Class'
		dataType: string
		lineageTag: 15a7aba3-053f-4af7-890f-9e4a2cef89cb
		sourceLineageTag: 9c1c09cf-8102-4ca5-825f-f400f85fac46
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Fixed Income Asset Class

		annotation SummarizationSetBy = Automatic

	column 'Security ID 2'
		dataType: string
		lineageTag: 3732d75c-ccf9-4eee-8eb6-9eb9e6881014
		sourceLineageTag: 29035763-3c47-4b03-9765-9e229225071e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security ID 2

		annotation SummarizationSetBy = Automatic

	column 'Issuer Name'
		dataType: string
		lineageTag: d5148035-6744-46f1-8a06-ec1830c4d2df
		sourceLineageTag: 0aa9b098-4314-4371-91cc-e1f704c49ed8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Issuer Name

		annotation SummarizationSetBy = Automatic

	column 'Jr ID'
		dataType: string
		lineageTag: 05b2c238-b0ef-4495-b213-87d6a06f2f68
		sourceLineageTag: 40ac37e2-e9fc-467b-b7b5-63b980d46b8c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Jr ID

		annotation SummarizationSetBy = Automatic

	column 'Jr Name'
		dataType: string
		lineageTag: 4424b37d-7a4d-4bfd-bbdf-85286c0364c9
		sourceLineageTag: 9a109ab7-1da9-4cd5-bb9b-847bb2bd5fa1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Jr Name

		annotation SummarizationSetBy = Automatic

	column 'Parent Issuer'
		dataType: string
		lineageTag: 93cc0475-7745-4622-b1ff-2656bfa30bb1
		sourceLineageTag: d7d5e601-4f1f-41ce-a842-dc216202d37f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Parent Issuer

		annotation SummarizationSetBy = Automatic

	column Portamv
		dataType: double
		lineageTag: 35167cab-a4a6-40e8-937e-62a91a4fb8a0
		sourceLineageTag: 84a01dff-6136-4146-bfb7-829f85c8f0b2
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Portamv

		annotation SummarizationSetBy = Automatic

	column Portbc
		dataType: double
		lineageTag: f42b2b7d-3770-4cdb-801e-6a5b26ec5a21
		sourceLineageTag: aa8fda3e-eb1f-4511-bbad-48161159cdd4
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Portbc

		annotation SummarizationSetBy = Automatic

	column Groupamv
		dataType: double
		lineageTag: bfaad7db-07f6-4a69-9318-6fe45e145882
		sourceLineageTag: 3df77cad-3ff2-479a-9548-dd919b4ecead
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Groupamv

		annotation SummarizationSetBy = Automatic

	column Groupbc
		dataType: double
		lineageTag: a063f2fb-7c60-4e43-ac31-c5bc320e210a
		sourceLineageTag: 7f328042-d0e7-4483-ada5-ffd5409660b2
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Groupbc

		annotation SummarizationSetBy = Automatic

	column 'Blocktrade Bbg ID'
		dataType: string
		lineageTag: 730e7551-6139-4a68-8a39-58ce663368a7
		sourceLineageTag: 3b0eb8cb-e72f-4640-a041-75e710b4a981
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Blocktrade Bbg ID

		annotation SummarizationSetBy = Automatic

	column 'Off Balance Cost'
		dataType: double
		lineageTag: 38c2a4b0-b407-4097-9e60-e54d1ca056ee
		sourceLineageTag: 7662871a-2e13-4d5d-83da-4678fc9f8ec7
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Off Balance Cost

		annotation SummarizationSetBy = Automatic

	column 'Swap Index'
		dataType: string
		lineageTag: f544c0e0-18e9-4b21-815c-f77a4231fafe
		sourceLineageTag: bb9cf256-f286-4495-8c63-9b6fe4cc9859
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Swap Index

		annotation SummarizationSetBy = Automatic

	column 'Day Count'
		dataType: string
		lineageTag: 39fc194d-6b90-4d58-a290-7abcb1ea3bf3
		sourceLineageTag: c5c715fe-41b9-485d-a64a-9e8556ad75ee
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Day Count

		annotation SummarizationSetBy = Automatic

	column 'Pay Frequency'
		dataType: string
		lineageTag: 637b14ea-6ca3-46ae-9c13-274c51540c2e
		sourceLineageTag: cf5fabaa-e16b-4156-93cf-60a9823374e6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Pay Frequency

		annotation SummarizationSetBy = Automatic

	column 'Reset Frequency'
		dataType: string
		lineageTag: c303ff5d-b2e9-4c12-8b44-6e60ae3b1f4b
		sourceLineageTag: 2829aba3-8614-45a3-985b-c3d8ef073b7d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Reset Frequency

		annotation SummarizationSetBy = Automatic

	column 'Month End Status'
		dataType: string
		lineageTag: 9e6f4e17-17d0-468b-95be-2a7f7723e6ef
		sourceLineageTag: cb7140ea-0e93-4039-83f1-e1e77d1ace91
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Month End Status

		annotation SummarizationSetBy = Automatic

	column 'Price Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: f50c819e-b392-42ac-a291-93ad19c96d2e
		sourceLineageTag: 893d94c5-f1c4-47cb-b773-33753cd028e8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Price Date

		annotation SummarizationSetBy = Automatic

	column 'Domicile Country Code'
		dataType: string
		lineageTag: f9e93f8c-18fb-4ad8-9eed-da9dd0d3f739
		sourceLineageTag: 8f5456ae-4e3f-4942-81ed-a36276042393
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Domicile Country Code

		annotation SummarizationSetBy = Automatic

	column 'Asia Asset Class Code Indonesia'
		dataType: string
		lineageTag: 500550ac-150f-481a-b364-008f003cbea1
		sourceLineageTag: cf38fcb2-4c42-48e2-980f-bda35139a4f3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asia Asset Class Code Indonesia

		annotation SummarizationSetBy = Automatic

	column 'Asia Asset Class Code Vietnam'
		dataType: string
		lineageTag: 614a2dc3-f897-4c21-a949-3b7714d3c09b
		sourceLineageTag: b103d0df-4ace-4e9c-a731-c45ad664b5ce
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asia Asset Class Code Vietnam

		annotation SummarizationSetBy = Automatic

	column 'Asia Asset Class Desc Indonesia'
		dataType: string
		lineageTag: d25dbe52-2b92-49ca-aaf8-f8a7b6f0093f
		sourceLineageTag: dcf97d8c-8365-4e89-9c03-42e4da994827
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asia Asset Class Desc Indonesia

		annotation SummarizationSetBy = Automatic

	column 'Asia Asset Class Desc Vietnam'
		dataType: string
		lineageTag: e56e86b3-5333-4771-a5ef-4c9d5eea9b14
		sourceLineageTag: 67575036-d494-4f2e-ba3c-24859bdff7bd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asia Asset Class Desc Vietnam

		annotation SummarizationSetBy = Automatic

	column 'Functional Ccy Code'
		dataType: string
		lineageTag: 5e3e57b7-40b4-4324-8a4c-d9df137936ea
		sourceLineageTag: 6d6ff986-a594-4fd1-85fe-7bdad51d5ce1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Functional Ccy Code

		annotation SummarizationSetBy = Automatic

	column 'Local to Func Rate'
		dataType: double
		lineageTag: d7660cd8-e869-4766-82c7-94d5e1b3fdf0
		sourceLineageTag: f8a5009e-a92e-408f-a961-283028c61deb
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Local to Func Rate

		annotation SummarizationSetBy = Automatic

	column 'Local to CAD Rate'
		dataType: double
		lineageTag: b4bb7750-88ea-4a43-9445-8445f136b04c
		sourceLineageTag: 40863a46-e083-4af9-80c9-ebd2553048c3
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Local to CAD Rate

		annotation SummarizationSetBy = Automatic

	column 'Local to USD Rate'
		dataType: double
		lineageTag: 99600f0c-4879-4371-af5e-61a30876a23c
		sourceLineageTag: e39c1fe5-b96a-4905-9b45-026d47d606ef
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Local to USD Rate

		annotation SummarizationSetBy = Automatic

	column 'Local to HKD Rate'
		dataType: double
		lineageTag: 8d467189-0911-458b-b629-7563ca6240a5
		sourceLineageTag: b51ed1cd-f8a2-4e1a-961b-84b1bfa36282
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Local to HKD Rate

		annotation SummarizationSetBy = Automatic

	column 'Next Coupon Amount (D)'
		dataType: double
		lineageTag: 66e9e92c-00d9-410e-87aa-488e3e498300
		sourceLineageTag: 3b53e091-234b-490c-8209-c8ff45d6fef1
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Next Coupon Amount (D)

		annotation SummarizationSetBy = Automatic

	column 'AOCI Hedge Par'
		dataType: double
		lineageTag: 914f3730-bc5a-4180-a4de-2f4d2ad6fab7
		sourceLineageTag: ff486cd4-cd4a-464c-b9cf-efc1a46b5485
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: AOCI Hedge Par

		annotation SummarizationSetBy = Automatic

	column 'AOCI Remain Balance Non BV - Base'
		dataType: double
		lineageTag: bf917758-0959-4739-b08e-999127cca2e3
		sourceLineageTag: 8d7177ab-9e31-475a-b078-e6dbe94e868e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance Non BV - Base

		annotation SummarizationSetBy = Automatic

	column 'AOCI Remain Balance Non BV - Local (D)'
		dataType: double
		lineageTag: f4732e34-9ed1-4b13-931e-8ab0b46008f8
		sourceLineageTag: 40bc7fe1-8d02-4941-8f60-27f6fb7eb6fe
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance Non BV - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'AOCI Remain Balance Rep - Base'
		dataType: double
		lineageTag: f2acdfd0-426f-4521-a2e1-b9d984aef6dc
		sourceLineageTag: 9ddfee99-2fc2-4b41-8ac1-b1c1a988dbb0
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance Rep - Base

		annotation SummarizationSetBy = Automatic

	column 'AOCI Remain Balance Rep - Local (D)'
		dataType: double
		lineageTag: 80dc1976-a3b8-4299-b424-e06c28e1b51c
		sourceLineageTag: a22810b9-f230-4fd6-ab13-fd696797052b
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance Rep - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Balance Commitment - Local'
		dataType: double
		lineageTag: 7fc4cd34-6d14-4ce6-a976-a9842b85c277
		sourceLineageTag: defd010f-894f-4d80-bdb3-32e270396291
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Commitment - Local

		annotation SummarizationSetBy = Automatic

	column 'Income Default Amount - Local (D)'
		dataType: double
		lineageTag: b4d72740-8cbb-47e4-8c13-da0c29b15a45
		sourceLineageTag: b24e01e7-f428-4f5f-8713-d50bd4e0d722
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Income Default Amount - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Income Default Amount - Base'
		dataType: double
		lineageTag: 1f352cb0-9f46-403d-b071-1d941d4e8993
		sourceLineageTag: b09cda7e-8e8c-4c90-9f72-a21a129abcf4
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Income Default Amount - Base

		annotation SummarizationSetBy = Automatic

	column 'Next Interest Payment - Local'
		dataType: double
		lineageTag: f30afdf7-cae7-4e1e-b0ab-eceb20e09ffb
		sourceLineageTag: f15b322a-7cef-4361-94bb-75b4d3444f86
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Next Interest Payment - Local

		annotation SummarizationSetBy = Automatic

	column 'Next Interest Payment - Base'
		dataType: double
		lineageTag: 13fbb509-4f23-40c7-bb21-614bdfd8a297
		sourceLineageTag: 2d77060b-46c5-4e1a-b2ac-5137e08328a9
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Next Interest Payment - Base

		annotation SummarizationSetBy = Automatic

	column 'Next Principal Payment - Local'
		dataType: double
		lineageTag: 832911b4-0138-4a40-a4d5-18ae2f4a1e3c
		sourceLineageTag: e329e8da-d888-4055-989f-300c9f787e77
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Next Principal Payment - Local

		annotation SummarizationSetBy = Automatic

	column 'Next Principal Payment - Base'
		dataType: double
		lineageTag: 8ce50211-72fa-46df-bb2d-3e69affa80ce
		sourceLineageTag: fe66df12-78d8-49cd-a0f6-9c8ee3ae729f
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Next Principal Payment - Base

		annotation SummarizationSetBy = Automatic

	column 'Pos Accrual - Base'
		dataType: double
		lineageTag: b1074782-3aa6-4c9b-93c6-aed4a23e7d37
		sourceLineageTag: 4a51553b-c44c-41ea-b58d-8e61707f4fe7
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Pos Accrual - Base

		annotation SummarizationSetBy = Automatic

	column 'Next Dividend - Local (D)'
		dataType: double
		lineageTag: 24cb9be1-ebbc-4ba9-bc57-f1e7b376ea0f
		sourceLineageTag: 87989cad-2bdc-4202-819f-94a4b8405a4b
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Next Dividend - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Current Yield Book Price (D)'
		dataType: double
		lineageTag: 162552f3-a1d7-4ecb-88b9-4392a0f4ce2a
		sourceLineageTag: 864ce250-2713-427d-a3d9-aeaf9d25a971
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Current Yield Book Price (D)

		annotation SummarizationSetBy = Automatic

	column Convexity
		dataType: double
		lineageTag: 5d09b19c-2e86-4fbc-97fd-477b264cf85c
		sourceLineageTag: 67527ab2-6221-46e1-8f28-b019b77025e2
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Convexity

		annotation SummarizationSetBy = Automatic

	column 'Current Yield (D)'
		dataType: double
		lineageTag: 4387b0e2-3b05-4c69-811f-e7983ec6b5d9
		sourceLineageTag: 8fa8bd49-25f5-4b76-82e7-3b01b1fcaf3d
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Current Yield (D)

		annotation SummarizationSetBy = Automatic

	column 'Dirty Price'
		dataType: double
		lineageTag: bd3b1a33-022f-4f84-9423-e442c5255678
		sourceLineageTag: 9f148561-0079-48ec-9f45-221a34d366a3
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Dirty Price

		annotation SummarizationSetBy = Automatic

	column 'Modified Duration YTM'
		dataType: double
		lineageTag: 734b9238-61a9-4dbf-a258-2602598d38e1
		sourceLineageTag: 6af5cd29-8b7d-473c-af4f-9d53cb7faaaa
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Modified Duration YTM

		annotation SummarizationSetBy = Automatic

	column 'Modified Duration YC'
		dataType: double
		lineageTag: ec864499-91d6-4c3e-9487-1251fd973127
		sourceLineageTag: a0c82686-13b1-4c07-8698-2e964ba8ea0c
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Modified Duration YC

		annotation SummarizationSetBy = Automatic

	column 'Original Book Yield (D)'
		dataType: double
		lineageTag: 8e208f94-c7ad-46a1-9fed-f84df85aa140
		sourceLineageTag: 6aed75b2-21bc-4b99-aa98-cbc2c99bfdaf
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Original Book Yield (D)

		annotation SummarizationSetBy = Automatic

	column 'Balance Cost Value - Local'
		dataType: double
		lineageTag: 4bdc6648-b975-42fa-8f30-13969430dff8
		sourceLineageTag: 4313e513-9f3b-42a5-a902-44cdecd10ffd
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Cost Value - Local

		annotation SummarizationSetBy = Automatic

	column 'Balance Cost Value - Base'
		dataType: double
		lineageTag: 5faa946e-c25c-4be5-ad16-71f0da70fc68
		sourceLineageTag: 7e661569-a007-4990-ba79-2e957a6416aa
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Cost Value - Base

		annotation SummarizationSetBy = Automatic

	column 'Book Value - Local (D)'
		dataType: double
		lineageTag: 5891d304-32af-4d51-b5c6-ede2a8a0b92e
		sourceLineageTag: 68fde057-d560-44d6-92dc-d0f8654a8f5d
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Book Value - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Book Value - Base'
		dataType: double
		lineageTag: 540dcf88-07a5-44fd-8a6a-da526b5c7d4e
		sourceLineageTag: 5d209ffc-92f9-401d-9285-d86bdfc2a5ff
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Book Value - Base

		annotation SummarizationSetBy = Automatic

	column 'Balance Int Appr - Local'
		dataType: double
		lineageTag: e3ab5243-43be-4700-a093-a629a4131ba3
		sourceLineageTag: b9625fa5-d9d9-468e-b76c-706514ea386f
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Int Appr - Local

		annotation SummarizationSetBy = Automatic

	column 'Balance Int Appr - Base'
		dataType: double
		lineageTag: 174b905d-56c4-4452-b8ea-07dea53a337a
		sourceLineageTag: 7b956b4a-ac46-4636-8b05-a07cc11335ba
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Int Appr - Base

		annotation SummarizationSetBy = Automatic

	column 'Balance OID Appr - Local'
		dataType: double
		lineageTag: 8958e0c6-0cde-45a6-8722-1117649f8abd
		sourceLineageTag: 971d7831-57e8-4011-87be-e6aaee412999
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance OID Appr - Local

		annotation SummarizationSetBy = Automatic

	column 'Balance OID Appr - Base'
		dataType: double
		lineageTag: 08a1f244-586d-4a0b-99de-5dedfff8e49e
		sourceLineageTag: 7e51362f-28a5-42bf-bdc1-8ffdabcf6e19
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance OID Appr - Base

		annotation SummarizationSetBy = Automatic

	column 'Balance CL Allowance - Local'
		dataType: double
		lineageTag: 544fb6e1-5a2e-4c5d-800d-47c25b72d994
		sourceLineageTag: ac33c782-b605-4479-8f9a-01a522b19266
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance CL Allowance - Local

		annotation SummarizationSetBy = Automatic

	column 'Balance CL Allowance - Base'
		dataType: double
		lineageTag: 00b18851-c416-41b8-bcdb-988b3cd9d9ca
		sourceLineageTag: aaea43bb-e94f-42f8-9865-5d54bdf70110
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance CL Allowance - Base

		annotation SummarizationSetBy = Automatic

	column 'Balance Recog CL Allowance - Local'
		dataType: double
		lineageTag: d6529c5c-0bf2-47e7-8c0f-71d949e0695f
		sourceLineageTag: 1d24650a-2d35-403a-a63a-94828bf749a6
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Recog CL Allowance - Local

		annotation SummarizationSetBy = Automatic

	column 'Balance Recog CL Allowance - Base'
		dataType: double
		lineageTag: f4fe996a-f68b-4fce-97fe-4b7f4c0cc26b
		sourceLineageTag: 2e653219-959c-4ef0-b006-2627f526fe25
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Recog CL Allowance - Base

		annotation SummarizationSetBy = Automatic

	column 'Balance Write Off - Local'
		dataType: double
		lineageTag: 1b86734f-4ac4-4fd9-9aa3-aec1d059214b
		sourceLineageTag: 6b37b71c-f23a-40f6-9ba3-cc955b3295bf
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Write Off - Local

		annotation SummarizationSetBy = Automatic

	column 'Balance Write Off - Base'
		dataType: double
		lineageTag: 53be70e1-60ea-41d5-afd6-01552abf1cd6
		sourceLineageTag: 6766f4ce-08d4-46fe-b510-346ac66b5d98
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Write Off - Base

		annotation SummarizationSetBy = Automatic

	column 'Balance Impairment - Local'
		dataType: double
		lineageTag: 7ce97bc1-b721-4a08-bada-cd05aad0472f
		sourceLineageTag: c4302e49-4e32-4f6c-a7be-4a1e90bf46d2
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Impairment - Local

		annotation SummarizationSetBy = Automatic

	column 'Balance Impairment - Base'
		dataType: double
		lineageTag: d26e82cd-1c3b-4e63-8ca5-c758165ccfba
		sourceLineageTag: 23be3aa1-ba34-4605-bc30-cea9409bfb31
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Impairment - Base

		annotation SummarizationSetBy = Automatic

	column 'AOCI Remain Balance BV - Local (D)'
		dataType: double
		lineageTag: d4f9608b-2dda-400a-b2ef-2ac8c6bd873d
		sourceLineageTag: 86a8d99f-92fc-46bc-8e7a-6ed3bba94e9e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance BV - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'AOCI Remain Balance BV - Base'
		dataType: double
		lineageTag: ad4873e3-abf2-4f1e-89f5-28dbdf0978ed
		sourceLineageTag: 2ef58381-d7f2-4452-bbf5-ebb2747a5682
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance BV - Base

		annotation SummarizationSetBy = Automatic

	column 'Balance Deferred PL - Local (D)'
		dataType: double
		lineageTag: 199cc5bf-5e19-40f4-84d8-9c7fec458c1c
		sourceLineageTag: 630d27c5-e314-4c35-92a1-59f1f9fff777
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Deferred PL - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Balance Deferred PL - Base'
		dataType: double
		lineageTag: d944cb30-6be0-4268-b214-32df9f731c93
		sourceLineageTag: 2f424abd-05ed-4bcf-addf-53749e6ce2cc
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Deferred PL - Base

		annotation SummarizationSetBy = Automatic

	column 'Income Accrual - Local (D)'
		dataType: double
		lineageTag: a0c4a3a0-1c0a-4f82-a828-9f9f622bfc5f
		sourceLineageTag: 915228e4-9395-4405-bc41-b1bab194af3d
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Income Accrual - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Income Accrual - Base'
		dataType: double
		lineageTag: 59a04c91-3f92-44c7-85c1-28ba4703d64f
		sourceLineageTag: 13db261c-5c41-48d4-ab91-37dfbf54cfab
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Income Accrual - Base

		annotation SummarizationSetBy = Automatic

	column 'Balance Expected Restitution - Local'
		dataType: double
		lineageTag: 527dd7d6-c631-41f8-ac57-2a0caae5f2da
		sourceLineageTag: b13a64be-32d0-4854-9deb-fc94533be5d2
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Expected Restitution - Local

		annotation SummarizationSetBy = Automatic

	column 'Balance Expected Restitution - Base'
		dataType: double
		lineageTag: 12cdd3f1-ee39-452d-8c32-e74dc88cc5e5
		sourceLineageTag: 4ff75c62-a3a0-4565-adc5-1c9d5e8326c2
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Expected Restitution - Base

		annotation SummarizationSetBy = Automatic

	column 'Carrying Value - Local (D)'
		dataType: double
		lineageTag: 659d14d0-80ce-412e-bcdf-134bda235743
		sourceLineageTag: c7ad0920-f4b5-48b8-bde3-d69d92ed0406
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Carrying Value - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Carrying Value - Base'
		dataType: double
		lineageTag: db5b4ee3-11b1-469a-b790-4178ecca30af
		sourceLineageTag: 5484a76f-2443-4d9a-b20e-fd180075c431
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Carrying Value - Base

		annotation SummarizationSetBy = Automatic

	column 'Updated Ts'
		dataType: dateTime
		formatString: yyyy\-mm\-dd hh:nn:ss AM/PM
		lineageTag: 92d8c235-f302-47f2-a306-4143dfc14e03
		sourceLineageTag: 2df0be10-e3c5-41e9-bdc9-3558fd82b5f4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Updated Ts

		annotation SummarizationSetBy = Automatic

	column 'Adjusted Book Value Local'
		dataType: double
		lineageTag: 13454647-f882-4e4b-beea-96ea63a76ce4
		sourceLineageTag: df95898d-dd05-4693-b2bd-568ca170b8f3
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Adjusted Book Value Local

		annotation SummarizationSetBy = Automatic

	column 'Adjusted Book Value Base'
		dataType: double
		lineageTag: 91c21f20-e1a6-43aa-ac70-4020816b78c8
		sourceLineageTag: d960b131-5d79-4294-be8f-d44b0ce3ba77
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Adjusted Book Value Base

		annotation SummarizationSetBy = Automatic

	column 'SCD Issuer Long Company Name'
		dataType: string
		lineageTag: a18270e2-b47c-4e64-858a-a6e9e3209ec5
		sourceLineageTag: 7cabd884-08ba-4dd1-ad86-c058e86cf626
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Issuer Long Company Name

		annotation SummarizationSetBy = Automatic

	column 'SCD Default Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: dfca1d56-96fe-4b07-85de-cd9e694df079
		sourceLineageTag: 8896093c-db8d-41c9-bc84-ef1dd91b7a80
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Default Date

		annotation SummarizationSetBy = Automatic

	column 'Accrue In Default'
		dataType: string
		lineageTag: f2c26557-5a55-4241-b7f3-a952860114f4
		sourceLineageTag: b9e1305d-f230-48be-abe9-7da6d57a0494
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Accrue In Default

		annotation SummarizationSetBy = Automatic

	column 'Unsettled Int Div Amount Base CCY'
		dataType: double
		lineageTag: 7ab9d8c0-f852-473e-bfd3-bf083c532390
		sourceLineageTag: 4612ac3d-ad06-4281-b42b-7e6ef2296ecf
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Unsettled Int Div Amount Base CCY

		annotation SummarizationSetBy = Automatic

	column 'Unsettled Int Div Amount Local CCY'
		dataType: double
		lineageTag: 6689dffd-3033-45d7-a90a-c0463479081f
		sourceLineageTag: 95a15a43-dd2a-453a-89fd-5e5e675e5b62
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Unsettled Int Div Amount Local CCY

		annotation SummarizationSetBy = Automatic

	column 'Balance Acquisition Pre Dis Base CCY'
		dataType: double
		lineageTag: 21e190c4-d5f8-40b4-8d4e-472919b29389
		sourceLineageTag: 6be2027d-4390-41d8-a0e0-688f8d0d5451
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Acquisition Pre Dis Base CCY

		annotation SummarizationSetBy = Automatic

	column 'Balance Acquisition Pre Dis Local CCY'
		dataType: double
		lineageTag: 9b0e4e76-675e-4130-95ac-1ae64e084d5e
		sourceLineageTag: 0eb5fef9-8003-400b-bf6b-2f1b485fd2dc
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Acquisition Pre Dis Local CCY

		annotation SummarizationSetBy = Automatic

	column Purpose
		dataType: string
		lineageTag: ed409fac-1eb5-4e64-8e9a-7d7b75e616bb
		sourceLineageTag: 4213af6a-9973-4e43-8c6f-d0ceb36b1a83
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Purpose

		annotation SummarizationSetBy = Automatic

	column 'IFRS9 Purpose'
		dataType: string
		lineageTag: fcec3105-3632-43a7-9597-4dbbf132b265
		sourceLineageTag: 8a62a695-401f-4e46-b0be-3ac2842877ee
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: IFRS9 Purpose

		annotation SummarizationSetBy = Automatic

	column 'Balance Book Value Local Native'
		dataType: double
		lineageTag: 03ff5be9-5645-4711-a55a-40bb678f9a32
		sourceLineageTag: 5c950ff0-9744-4140-bee2-6d28b2796f7b
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Book Value Local Native

		annotation SummarizationSetBy = Automatic

	column 'Balance Book Value Base Native'
		dataType: double
		lineageTag: ee62483e-a75a-4b83-9e94-ad7ea600e56c
		sourceLineageTag: 460c0d5e-b33b-4b1b-9f72-8dab0cd99523
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Book Value Base Native

		annotation SummarizationSetBy = Automatic

	column 'Calculation Date Full'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: a83d7882-96e5-43f4-9937-e7c7f4fee348
		sourceLineageTag: 5f7553f3-cf81-4e38-995d-db97d88c5ec0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Calculation Date Full

		annotation SummarizationSetBy = Automatic

	column 'Long Short Indicator'
		dataType: string
		lineageTag: fa67906b-9032-4da4-81ce-14ac7a36205e
		sourceLineageTag: 53d73d3c-8354-46b1-9608-e8d27029bb02
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Long Short Indicator

		annotation SummarizationSetBy = Automatic

	column 'Accrued Interest EOP Local'
		dataType: double
		lineageTag: d87c1ea6-1431-4943-b723-6eeb11a30d31
		sourceLineageTag: 1d3da0bf-b92f-4a4a-8286-4094e1788b77
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Accrued Interest EOP Local

		annotation SummarizationSetBy = Automatic

	column 'Accrued Interest EOP Base'
		dataType: double
		lineageTag: abf6a987-91c8-4974-8aba-a73ce5d2935d
		sourceLineageTag: 824436cf-c316-43a7-83e8-4169f30e6597
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Accrued Interest EOP Base

		annotation SummarizationSetBy = Automatic

	column 'Balance Return Of Capital Base'
		dataType: double
		lineageTag: 85b36295-c0de-40af-97c7-2e1a242c989b
		sourceLineageTag: 3f3d20d1-f096-44ad-938b-695fea02763c
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Return Of Capital Base

		annotation SummarizationSetBy = Automatic

	column 'Balance Return Of Capital Local'
		dataType: double
		lineageTag: a700e040-85de-4f8c-a986-6cc5a8a42385
		sourceLineageTag: 31f3397a-6d60-4dc0-8484-7aa1d5554ad4
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Return Of Capital Local

		annotation SummarizationSetBy = Automatic

	column 'Balance Called Capital Base'
		dataType: double
		lineageTag: 0e1091a1-e023-487b-b801-103c966dc941
		sourceLineageTag: 6da14a77-738d-4f6b-9fed-d2bfea7527f3
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Called Capital Base

		annotation SummarizationSetBy = Automatic

	column 'Balance Called Capital Local'
		dataType: double
		lineageTag: 3ad61b74-519b-49b8-880f-a247a3d2a180
		sourceLineageTag: 195d3cc2-a818-47d1-b405-1c6c8d4b26c4
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Called Capital Local

		annotation SummarizationSetBy = Automatic

	column 'Balance Recallable Base'
		dataType: double
		lineageTag: f1bf6009-7a9b-458e-8423-d14c37b49e8a
		sourceLineageTag: a43fd929-95df-43b9-8a63-f0dead107a09
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Recallable Base

		annotation SummarizationSetBy = Automatic

	column 'Balance Recallable Local'
		dataType: double
		lineageTag: dbe541d2-1a5f-41c7-bbd2-a4864b10eca4
		sourceLineageTag: bfe5c6e8-a315-49f9-92ce-2e501df9e319
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Recallable Local

		annotation SummarizationSetBy = Automatic

	column 'Balance NAIC Carrying Value Local'
		dataType: double
		lineageTag: 1a46e306-49e0-421f-aa09-ae2a24bad769
		sourceLineageTag: aac06614-f875-429d-8784-091afbfbb444
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance NAIC Carrying Value Local

		annotation SummarizationSetBy = Automatic

	column 'Balance NAIC Carrying Value Base'
		dataType: double
		lineageTag: b6248f85-8546-4b55-8b42-d9f5bfc3f346
		sourceLineageTag: 3487ef99-e2f8-4bc2-b057-d3e16e9aecfb
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance NAIC Carrying Value Base

		annotation SummarizationSetBy = Automatic

	column 'Balance NAIC Sec Adj Local'
		dataType: double
		lineageTag: 799503bf-65ee-42b8-ada6-b11511819daa
		sourceLineageTag: 02aa18fb-fb8c-4428-af56-87e53c4e55ec
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance NAIC Sec Adj Local

		annotation SummarizationSetBy = Automatic

	column 'Balance NAIC Sec Adj Base'
		dataType: double
		lineageTag: 894b5986-859a-4771-8332-ba8e9ef918c9
		sourceLineageTag: e9aadb73-3b70-46ca-9c46-a93baf815e16
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance NAIC Sec Adj Base

		annotation SummarizationSetBy = Automatic

	column 'Amortized Cost - Local (D)'
		dataType: double
		lineageTag: 48b1b292-588d-475f-9026-fa27893c1cd1
		sourceLineageTag: 256d9392-c529-484a-a627-ce331a7fa94d
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Amortized Cost - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Calculated Unrealized Gain/Loss – Local'
		dataType: double
		lineageTag: c4faf6c1-ed49-4220-bb61-b0e3a4ac9f35
		sourceLineageTag: 8c166774-6f13-4bce-8487-ca6c90906c5e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Calculated Unrealized Gain/Loss – Local

		annotation SummarizationSetBy = User

	column 'ML Business Group'
		dataType: string
		lineageTag: bd54caef-edec-4b95-a8e4-474598d60786
		sourceLineageTag: 342161b5-43f3-4277-992e-e099adf67170
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Business Group

		annotation SummarizationSetBy = User

	column 'SCD GL Classification'
		dataType: string
		lineageTag: 4740d201-26af-4a04-9d95-48d349f5884d
		sourceLineageTag: 3f82517e-3c3a-45a9-b87a-7d88d2389b2d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD GL Classification

		annotation SummarizationSetBy = User

	column 'Issue Volume'
		dataType: double
		lineageTag: 8a52c435-c145-4fd4-898c-3d73527c3396
		sourceLineageTag: b53e1cf4-dc17-477e-ab43-6ab6ca151103
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Issue Volume

		annotation SummarizationSetBy = User

	column Structure
		dataType: string
		lineageTag: e387f9d3-a937-47be-ac6f-39bca1cbe555
		sourceLineageTag: 05bb8e34-1fbb-4aaf-a785-0c447710527c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Structure

		annotation SummarizationSetBy = User

	column 'Accrued Interest QC (Static)'
		dataType: double
		lineageTag: cffb9ef0-459e-42b5-8509-aceac4bdbc81
		sourceLineageTag: e03d51f0-a757-49f9-9e3d-1331a839a576
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Accrued Interest QC (Static)

		annotation SummarizationSetBy = User

	column 'Accrued Interest PC (Static)'
		dataType: double
		lineageTag: c13cd2f1-729d-4dc9-b740-f5edaa2d18a3
		sourceLineageTag: d96e70a2-9127-45ad-989d-828f3cadc2c7
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Accrued Interest PC (Static)

		annotation SummarizationSetBy = User

	column 'Portfolio Group1'
		dataType: string
		lineageTag: 8c6c901c-2819-4ca1-b39e-14e4135e5b35
		sourceLineageTag: 97bbab40-0a20-4499-9b8c-397552fae702
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Portfolio Group1

		annotation SummarizationSetBy = User

	column 'Balance Unpaid Commitment'
		dataType: double
		lineageTag: eb7aed5e-739e-43cb-abd7-abee271b6330
		sourceLineageTag: fec48f80-32dc-4f07-808f-b8a2c8d6c65c
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Unpaid Commitment

		annotation SummarizationSetBy = User

	partition 'Securities Position Fact-d0f2a559-daf6-46a6-85f2-cf762c6e0cf0' = entity
		mode: directQuery
		source
			entityName: Securities Position Fact
			expressionSource: 'DirectQuery to AS - Securities'

