table Securities
	lineageTag: 1810b563-7fdb-4884-ae8d-fff4ca795aa7
	sourceLineageTag: 19dbf567-4319-496c-aa31-a20ea241218a

	measure 'Maturity Days' = EXTERNALMEASURE("Maturity Days", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		lineageTag: ba63e3ff-00ba-409b-ba78-0814e100ce63
		sourceLineageTag: fdd208a4-3e62-43da-a680-caca14b4903d
		dataCategory: Uncategorized

	measure 'Days to Maturity' = EXTERNALMEASURE("Days to Maturity", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		lineageTag: a50ce3bd-adbc-49ad-b6fc-82007bd9be61
		sourceLineageTag: c4fed4e6-e213-48d3-be0c-fd5e4c2cb095
		dataCategory: Uncategorized

	measure 'Held Securities Title DQ' = EXTERNALMEASURE("Held Securities Title DQ", STRING, "DirectQuery to AS - Securities")
		lineageTag: 229dd853-9a21-4b0d-b119-eb81f9c035c3
		sourceLineageTag: e173b355-d6cc-4675-935e-225738be5e08
		dataCategory: Uncategorized

	measure 'All Securities Title_' = EXTERNALMEASURE("All Securities Title_", STRING, "DirectQuery to AS - Securities")
		isHidden
		lineageTag: 5929ea12-fb1c-4e19-bacd-c2486a326777
		sourceLineageTag: 7f178edf-50d2-44ae-8814-f49b2ffca998
		dataCategory: Uncategorized

	measure 'Primary Security ID - Change' = EXTERNALMEASURE("Primary Security ID - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: b27338a9-50a9-493f-9472-3defa8eb3931
		sourceLineageTag: 47f729ad-01fd-4771-8398-59602f7e87d0
		dataCategory: Uncategorized

	measure 'Next Call Date - Change' = EXTERNALMEASURE("Next Call Date - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 7e53ee33-86bd-409c-bfa1-430d03e967d4
		sourceLineageTag: 526995c5-7397-41a9-9374-7de6542caa97
		dataCategory: Uncategorized

	measure 'Asset Class - Change' = EXTERNALMEASURE("Asset Class - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: fab1c398-2660-4756-b8bc-32e6f935f56b
		sourceLineageTag: f447e7c7-9914-4259-8726-9224236ebcee
		dataCategory: Uncategorized

	measure 'Asset Group - Change' = EXTERNALMEASURE("Asset Group - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 7d458517-060b-454f-94be-477ae9a0e986
		sourceLineageTag: 44f4f7a1-aaad-47c9-9b95-a8417ba0601c
		dataCategory: Uncategorized

	measure 'Asset Type - Change' = EXTERNALMEASURE("Asset Type - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 34960a80-dbe0-4cf4-b9ad-bcb1a721ef07
		sourceLineageTag: 3759fa7c-40ca-480d-86a3-0599b98efc5e
		dataCategory: Uncategorized

	measure 'Security Description - Change' = EXTERNALMEASURE("Security Description - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: fd8cbfae-419d-4c4a-8cae-05194f121b3d
		sourceLineageTag: a3589622-dcc6-44e3-92df-9aede7500b69
		dataCategory: Uncategorized

	measure 'Cusip - Change' = EXTERNALMEASURE("Cusip - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 066631c2-f68e-4bdc-bd41-bdeb3294913d
		sourceLineageTag: 740d4156-8135-4151-91d2-5e12f1e92213
		dataCategory: Uncategorized

	measure 'Coupon - Change' = EXTERNALMEASURE("Coupon - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 2ffa7dde-f7a5-413f-8bbb-8a5b5e14cce8
		sourceLineageTag: 09439cfb-60fb-4077-be9f-eeba0f842f99
		dataCategory: Uncategorized

	measure 'Maturity Date - Change' = EXTERNALMEASURE("Maturity Date - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 9094d7b1-269a-434a-b96f-79f483fd1587
		sourceLineageTag: 10b04a51-0c60-4f18-a90e-9a4e9a42b2b8
		dataCategory: Uncategorized

	measure 'Next Call Price - Change' = EXTERNALMEASURE("Next Call Price - Change", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 9841d80a-7896-4343-aabf-5bc9029b9a14
		sourceLineageTag: b97540cf-8338-4fac-9bf4-b4d22ed5d00c
		dataCategory: Uncategorized

	measure 'Next Sink Date - Change' = EXTERNALMEASURE("Next Sink Date - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 3114c6e1-bb5f-4d22-9e2e-157c51accef7
		sourceLineageTag: e7f46c9a-0311-49d6-a6c2-6b1b94bef5b1
		dataCategory: Uncategorized

	measure 'Shares Outstanding - Change' = EXTERNALMEASURE("Shares Outstanding - Change", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: e1047ee6-63fc-4f9d-a727-01d6b1cbf95a
		sourceLineageTag: 9c4896b4-8e2c-401a-ae6c-597e7104882b
		dataCategory: Uncategorized

	measure 'Moodys Short Term Rating - Change' = EXTERNALMEASURE("Moodys Short Term Rating - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: efef4583-4932-4595-a77a-953210f781b2
		sourceLineageTag: d43096e0-d210-4b64-920d-c9f59b5ebde6
		dataCategory: Uncategorized

	measure 'Asia Rating - Change' = EXTERNALMEASURE("Asia Rating - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 637757f2-07a5-487b-925b-53352e616512
		sourceLineageTag: de981c87-b144-4cfb-b190-11080e8d63fd
		dataCategory: Uncategorized

	measure 'Fitch Short Term Rating - Change' = EXTERNALMEASURE("Fitch Short Term Rating - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 3964b1ea-0ec0-496b-a0da-00c875874a13
		sourceLineageTag: 8873e0f9-6d87-4220-9410-d015e9a81ecb
		dataCategory: Uncategorized

	measure 'S&P Short Term Rating - Change' = EXTERNALMEASURE("S&P Short Term Rating - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: a28c3629-88b6-41f7-955f-bdd7242cb87d
		sourceLineageTag: f37f4805-47f5-4e6c-8e60-d83db6f8d185
		dataCategory: Uncategorized

	measure 'Internal Risk Rating - Change' = EXTERNALMEASURE("Internal Risk Rating - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: a19b11f1-72aa-4cd7-b5d7-4a7fe19ed02b
		sourceLineageTag: d0e70e81-3881-40f2-b0c6-1832cf92ec57
		dataCategory: Uncategorized

	measure 'ML MFC Equivalent Rating - Change' = EXTERNALMEASURE("ML MFC Equivalent Rating - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: ab16393c-e1a1-4407-b61b-501748217aca
		sourceLineageTag: a9a318ce-25a6-472a-a34c-427a0c6c6e8e
		dataCategory: Uncategorized

	measure 'SCD Instrument Category - Change' = EXTERNALMEASURE("SCD Instrument Category - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 0253b17f-8ffa-41de-ab01-f999825d0af7
		sourceLineageTag: 4b252dc9-690a-4c70-bed3-9ebaeb51a56d
		dataCategory: Uncategorized

	measure 'Held Securities Changes Title DQ' = EXTERNALMEASURE("Held Securities Changes Title DQ", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: c48e16a0-5b9c-42fc-baed-5c7f6f1bc29e
		sourceLineageTag: 6824d37e-8c6c-4adc-ab0a-d5a11f684583
		dataCategory: Uncategorized

	measure 'Primary Security ID & Desc Latest' = EXTERNALMEASURE("Primary Security ID & Desc Latest", STRING, "DirectQuery to AS - Securities")
		lineageTag: 548c1144-16e7-4142-85dd-40223240ce6e
		sourceLineageTag: f7db2289-cb7d-402a-bfa4-1a6992b4bb29
		dataCategory: Uncategorized

	measure 'Security - Change' = EXTERNALMEASURE("Security - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 9e7d3cae-6ec7-41a0-a6a2-295c24f6314b
		sourceLineageTag: 1ae38230-ff4b-4860-8ee4-7e0f4302c2a7
		dataCategory: Uncategorized

	measure 'Security - Change Filter' = EXTERNALMEASURE("Security - Change Filter", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		displayFolder: Security Changes Measures
		lineageTag: 473b2d81-f811-4aad-88a4-63161fd8234d
		sourceLineageTag: d947fa76-fae5-4a07-8162-af06bbe1e8c6
		dataCategory: Uncategorized

	measure '#Secs - Changes' = EXTERNALMEASURE("#Secs - Changes", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		displayFolder: Security Changes Measures
		lineageTag: 9f7bc2d3-d9f3-4d95-946f-2cbd553d4960
		sourceLineageTag: 0379e59a-ed79-4678-b262-16ba396fbfcc
		dataCategory: Uncategorized

	measure 'Company Code & Name (Held Sec)' = EXTERNALMEASURE("Company Code & Name (Held Sec)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 112dce55-63c8-48e5-9559-e13b7c579254
		sourceLineageTag: 96114bd3-6cfe-4eb4-bec3-2dbd042f2213
		dataCategory: Uncategorized

	measure 'Accounting Unit Code Name (Held Sec)' = EXTERNALMEASURE("Accounting Unit Code Name (Held Sec)", STRING, "DirectQuery to AS - Securities")
		lineageTag: ffe80c19-bdc8-468b-9e1b-1aaecba0ec2d
		sourceLineageTag: c0a670bf-120b-4c7f-844f-a08d41d209f7
		dataCategory: Uncategorized

	measure 'Asia Asset Class Code Vietnam (Held Sec)' = EXTERNALMEASURE("Asia Asset Class Code Vietnam (Held Sec)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 9958b92c-febf-4f6f-9ab6-bb04e2e22ff6
		sourceLineageTag: d2a97378-ad76-4a93-8e45-26d1ff2388b5
		dataCategory: Uncategorized

	measure 'Asia Asset Class Desc Vietnam (Held Sec)' = EXTERNALMEASURE("Asia Asset Class Desc Vietnam (Held Sec)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 6b93314d-8ece-4663-8815-9a6b2af80440
		sourceLineageTag: 070cb9ef-ffef-472a-a1bf-485276430b29
		dataCategory: Uncategorized

	measure 'Asia Asset Class Code Indonesia (Held Sec)' = EXTERNALMEASURE("Asia Asset Class Code Indonesia (Held Sec)", STRING, "DirectQuery to AS - Securities")
		lineageTag: b8264249-11c4-4832-a5aa-49e7a190f62e
		sourceLineageTag: 53e40b06-4dbd-49fe-aa1b-bc8e560b209e
		dataCategory: Uncategorized

	measure 'Asia Asset Class Desc Indonesia (Held Sec)' = EXTERNALMEASURE("Asia Asset Class Desc Indonesia (Held Sec)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 8a8e46a0-44e7-407c-8583-3de96b223430
		sourceLineageTag: 0e6b359d-34d0-4c7c-8703-49b332141e95
		dataCategory: Uncategorized

	measure #SrcSecID = EXTERNALMEASURE("#SrcSecID", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		lineageTag: a3dcc500-d808-45ae-9442-906a64635b8b
		sourceLineageTag: c9531b7f-bf95-4e66-8c53-3c1a96cb62b5
		dataCategory: Uncategorized

	measure #PortCount = EXTERNALMEASURE("#PortCount", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		lineageTag: bae34428-3741-400f-90a3-81a82bb55933
		sourceLineageTag: be418c1d-1239-4886-a570-8d98b37d0b22
		dataCategory: Uncategorized

	measure '#Secs Count' = EXTERNALMEASURE("#Secs Count", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		lineageTag: 6cac69f0-1606-4980-815f-1facb9216c1a
		sourceLineageTag: 80c5c2b7-f857-43b6-aece-5796b8eaacac
		dataCategory: Uncategorized

	measure 'Coupon Spread - Change' = EXTERNALMEASURE("Coupon Spread - Change", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 8762cfb7-01a4-421d-9721-889eae9c5eaf
		sourceLineageTag: d6ab8af0-7e4d-43d7-8fd6-d618e84bb6f5
		dataCategory: Uncategorized

	measure 'Last Refix Date - Change' = EXTERNALMEASURE("Last Refix Date - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 99261cf3-fb7b-4bdd-a105-4334f08bb639
		sourceLineageTag: 723179e1-95b3-4f4f-9fda-4e3ebe58c029
		dataCategory: Uncategorized

	measure 'Moodys - Change' = EXTERNALMEASURE("Moodys - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 06c27d1a-50a7-45fb-aba4-a82d13c0ee7c
		sourceLineageTag: bf7c1abd-bf46-42c2-beba-fc1530e20530
		dataCategory: Uncategorized

	measure 'S&P - Change' = EXTERNALMEASURE("S&P - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: d594d0e4-ff81-46e5-906e-1be9d68161a2
		sourceLineageTag: 6bd1ad16-f6bb-4523-9872-18b64712c464
		dataCategory: Uncategorized

	measure 'Fitch - Change' = EXTERNALMEASURE("Fitch - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: fe7a6ca5-8fac-4468-963d-bc6e4ce54bf3
		sourceLineageTag: 49e3a0c0-fc09-4da9-9dd8-bbc03a9fb7f2
		dataCategory: Uncategorized

	measure 'Dbrs - Change' = EXTERNALMEASURE("Dbrs - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: c3fef752-13f7-4112-834b-7c744e149b6c
		sourceLineageTag: 0396e384-4c59-4820-9bd7-1839e6e1e8be
		dataCategory: Uncategorized

	measure 'Internal - Change' = EXTERNALMEASURE("Internal - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: be0d9057-6560-4cc7-93ae-deac193de0ed
		sourceLineageTag: 71bd5784-fe9d-47b9-b605-063854f40fb3
		dataCategory: Uncategorized

	measure 'RTG Fitch Long - Change' = EXTERNALMEASURE("RTG Fitch Long - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 85b87825-2e58-4b5a-8c04-9c5672ebe5a9
		sourceLineageTag: 9ddbd91d-4f5a-49af-8b43-69102743206b
		dataCategory: Uncategorized

	measure 'RTG MDY Issuer - Change' = EXTERNALMEASURE("RTG MDY Issuer - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 766dab6c-354a-4c04-b578-d42950d2bb3c
		sourceLineageTag: 06007a1a-3994-4b82-b0ac-7975f7fedc14
		dataCategory: Uncategorized

	measure 'RTG S&P Long - Change' = EXTERNALMEASURE("RTG S&P Long - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: b3607d1b-f5da-4aec-887b-6a25f14f76e4
		sourceLineageTag: 61da3e89-4134-4044-89b5-ae05347cebf1
		dataCategory: Uncategorized

	measure 'RTG MDY Long Issue Level - Change' = EXTERNALMEASURE("RTG MDY Long Issue Level - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 1c654287-1d74-4b17-be28-296b9591756c
		sourceLineageTag: 2eb69cc3-1716-44e2-a4e9-dd683f184d27
		dataCategory: Uncategorized

	measure 'S&P Rating Outlook - Change' = EXTERNALMEASURE("S&P Rating Outlook - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 78867c43-ff24-497f-8cfb-7989e8a86de5
		sourceLineageTag: cf7a8564-4c15-4b28-b3a2-e021e330f04a
		dataCategory: Uncategorized

	measure 'ML Ifrs 13 Level - Change' = EXTERNALMEASURE("ML Ifrs 13 Level - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 5216537d-15ae-4b6a-9518-4e039503cfe1
		sourceLineageTag: e072cc46-439f-412d-af82-d50b2d715495
		dataCategory: Uncategorized

	measure 'ML NAIC Instrument Type Cd - Change' = EXTERNALMEASURE("ML NAIC Instrument Type Cd - Change", STRING, "DirectQuery to AS - Securities")
		displayFolder: Security Changes Measures
		lineageTag: 3245be60-ded2-4aed-9aa6-659d3294e5af
		sourceLineageTag: d3b478cb-eae9-4c1a-9350-1b03f53f9bb8
		dataCategory: Uncategorized

	measure 'Filter Date' = EXTERNALMEASURE("Filter Date", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		isHidden
		lineageTag: 2d91e84e-049c-4875-a211-6433097eb69e
		sourceLineageTag: 53d7cc80-17ac-4cec-a876-dc91ee9e0a82
		dataCategory: Uncategorized

	measure 'All Security Filter (Held/Transacted/Minor Type)' = EXTERNALMEASURE("All Security Filter (Held/Transacted/Minor Type)", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		isHidden
		lineageTag: f2ee2002-30b2-46ba-83e1-1875698e45b0
		sourceLineageTag: 18f5ec62-82f5-4992-b588-f3566d650be0
		dataCategory: Uncategorized

	measure 'Is Active Security' = EXTERNALMEASURE("Is Active Security", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		lineageTag: 52243a65-5706-4113-9dfd-da2f93f34810
		sourceLineageTag: 0cb8fade-ee3f-4f7c-994d-c2473ddc4356
		dataCategory: Uncategorized

	measure 'Ultimate parent LEI (Entities)' = EXTERNALMEASURE("Ultimate parent LEI (Entities)", STRING, "DirectQuery to AS - Securities")
		lineageTag: cbb0d508-69cc-4795-993f-a4b0d3573646
		sourceLineageTag: ccb99281-b2ff-4083-9042-b45f71c9635f
		dataCategory: Uncategorized

	measure 'Ultimate parent location (Entities)' = EXTERNALMEASURE("Ultimate parent location (Entities)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 9c80b41b-b914-4662-97f5-6d475ccc6f8a
		sourceLineageTag: 01e58b84-4045-4382-88e2-acb44e865e01
		dataCategory: Uncategorized

	measure 'Ultimate parent company (Entities)' = EXTERNALMEASURE("Ultimate parent company (Entities)", STRING, "DirectQuery to AS - Securities")
		lineageTag: f5fed9be-65e3-45ef-b637-acbbe784c34b
		sourceLineageTag: 05d5ac2f-f54b-42a0-9ec1-5234e83364c1
		dataCategory: Uncategorized

	measure 'Trade Date_dup' = CALCULATE(RLATED(min('Securities Transaction GA Fact'[Trade Date]),'Securities Transaction GA Fact'[Framework Code]="NAIC"))
		lineageTag: bb2ed2da-8e8e-4632-a4c4-9ff31c57197d

		changedProperty = Name

	column '144A Flag_Derived' = ```
			if(ISBLANK(Securities[144A Flag]), "N", 
			if(Securities[144A Flag] = BLANK(), "N", 
			if(Securities[144A Flag] = "", "N",
			if(Securities[144A Flag] = "NULL", "N",
			Securities[144A Flag]))))
			```
		lineageTag: f56c81a2-1bac-441c-822a-efedc6035fd3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Security NK'
		dataType: string
		isNullable: false
		lineageTag: d298470f-bc44-4227-bd01-0385da663dcd
		sourceLineageTag: 984a471c-a048-44d0-9cb9-99151e1fcd1b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security NK

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID'
		dataType: string
		lineageTag: 5fd3c233-c77e-4f0b-8f0e-ff8794fbe294
		sourceLineageTag: 32b0d54d-31e8-4293-8c6c-5a607bc9f63b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Primary Security ID

		annotation SummarizationSetBy = Automatic

	column 'Security Description'
		dataType: string
		lineageTag: 2a747c7b-bfc6-4e9b-bccd-726c45019b16
		sourceLineageTag: 9c7d0909-c1dc-4e60-96df-37090ebfad1a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security Description

		annotation SummarizationSetBy = Automatic

	column 'As Of Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 2d820810-ed33-49ad-ba6c-fef6d4341e23
		sourceLineageTag: c9f7d2ed-3218-4a93-9d4d-592b877ea61e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: As Of Dt

		annotation SummarizationSetBy = Automatic

	column Src
		dataType: string
		lineageTag: 749e156e-9c34-45ce-9146-7bebcdb5a167
		sourceLineageTag: 8e189d56-2b1a-4865-b600-421397d57df7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Src

		annotation SummarizationSetBy = Automatic

	column 'Src Security ID'
		dataType: string
		lineageTag: 141a7f5f-e82d-4700-a8f3-1eba0120f6fc
		sourceLineageTag: 43a778c0-0d73-40c9-85ee-431edc0c1982
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Src Security ID

		annotation SummarizationSetBy = Automatic

	column 'Src Market ID'
		dataType: string
		lineageTag: 97e82117-33b7-42cd-9bda-34b44b9a195b
		sourceLineageTag: 47deb3c1-730f-49b4-8a74-6e6f39b8e354
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Src Market ID

		annotation SummarizationSetBy = Automatic

	column 'SCD Security ID'
		dataType: string
		lineageTag: ceb479f3-214f-41a6-b424-fd120d5a94fc
		sourceLineageTag: edae8978-8a4a-433d-af43-e78cc4f90091
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Security ID

		annotation SummarizationSetBy = Automatic

	column 'Security ID 2'
		dataType: string
		lineageTag: 13f674da-ca27-4657-9b36-cfd7d9685e29
		sourceLineageTag: 4dab984a-845e-445a-b6f8-86036f5a4736
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security ID 2

		annotation SummarizationSetBy = Automatic

	column 'Ticker Isin'
		dataType: string
		lineageTag: 9c6a9c68-82fd-4622-bd84-715a5ff829e1
		sourceLineageTag: 32f39ea0-a0f6-4cd1-b1c2-e473da9b3a33
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Ticker Isin

		annotation SummarizationSetBy = Automatic

	column 'Official PPN'
		dataType: string
		lineageTag: cf4bc583-c236-4b8c-b42d-0e92def925a8
		sourceLineageTag: 90ca00d6-b104-4349-8660-67082f9885b5
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Official PPN

		annotation SummarizationSetBy = Automatic

	column 'Security Name'
		dataType: string
		lineageTag: 51817569-8f3f-4c75-9ea0-aea232879961
		sourceLineageTag: 02c90708-72a4-43d2-b606-89279f9a5fa1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security Name

		annotation SummarizationSetBy = Automatic

	column 'Bloomberg ID'
		dataType: string
		lineageTag: 44eb0e39-77c3-497b-bfbd-0d2061d0d054
		sourceLineageTag: d90f59c9-b3d5-430b-b724-fece2021914b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Bloomberg ID

		annotation SummarizationSetBy = Automatic

	column 'ID PRPL'
		dataType: string
		lineageTag: ee6b288d-493e-4f9e-85fb-38d2fcab072c
		sourceLineageTag: 3676fa20-2b31-4c2a-bddc-04eea011f8a9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ID PRPL

		annotation SummarizationSetBy = Automatic

	column 'ID BB Global'
		dataType: string
		lineageTag: d6682210-2bbd-4a72-9e63-cbbf32ec73d7
		sourceLineageTag: 6703dd11-bf0b-4e49-b059-b9cfcc4c4913
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ID BB Global

		annotation SummarizationSetBy = Automatic

	column Cusip
		dataType: string
		lineageTag: 8d9a9e60-f0cf-416a-9a02-a25d727d6bc1
		sourceLineageTag: 2631ca71-3a54-486d-aca7-ed6dd698021f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Cusip

		annotation SummarizationSetBy = Automatic

	column Isin
		dataType: string
		lineageTag: 49e6adf3-e782-42f5-aded-dc568bd31fcd
		sourceLineageTag: 13e5fd95-89c4-4156-be25-7bc2ad27cb43
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Isin

		annotation SummarizationSetBy = Automatic

	column Ticker
		dataType: string
		lineageTag: 990d3b9a-27fb-4cc8-bee9-3373a14bd8ef
		sourceLineageTag: e5ab363c-0982-44b7-a724-d881603f00b9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Ticker

		annotation SummarizationSetBy = Automatic

	column 'Principal Exchange'
		dataType: string
		lineageTag: b87275d3-5962-4cfd-b84b-567db90aeaa5
		sourceLineageTag: 1cd49b0a-23d6-4d84-b98c-eacb135654d7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Principal Exchange

		annotation SummarizationSetBy = Automatic

	column Sedol
		dataType: string
		lineageTag: bc147121-2706-4559-bcc4-599df9d55e5f
		sourceLineageTag: 3a4fc141-f2d4-4375-bc05-12fa5bc34929
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Sedol

		annotation SummarizationSetBy = Automatic

	column 'Collateral Type'
		dataType: string
		lineageTag: ac8fc219-ffd6-4083-9f46-6b7535d1eeb1
		sourceLineageTag: 45c21843-83d8-47aa-9041-99cd7fa4edc6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Collateral Type

		annotation SummarizationSetBy = Automatic

	column Factor
		dataType: double
		formatString: 0.000000
		lineageTag: 06819c98-f9f4-42da-9dce-ed5098ed644d
		sourceLineageTag: e1e9b875-ff3a-4606-9e98-a485aa4b4015
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Factor

		annotation SummarizationSetBy = Automatic

	column Local
		dataType: string
		lineageTag: 0254e9d1-4185-43e7-b73b-71b9a132922d
		sourceLineageTag: 55d502a7-bfa4-41bb-80a0-598288d49585
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Local

		annotation SummarizationSetBy = Automatic

	column Moodys
		dataType: string
		lineageTag: 99e3ad7b-8aaf-4710-93d0-b9e13c857f0a
		sourceLineageTag: 6fdf0aeb-3ae0-4d19-a430-0691b8ce0a26
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Moodys

		annotation SummarizationSetBy = Automatic

	column 'Moodys Rating Change Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: d1de471e-ac88-4297-bcef-8d5c4a641634
		sourceLineageTag: f5b0651a-029c-4f96-96ea-879779e5ccac
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Moodys Rating Change Date

		annotation SummarizationSetBy = Automatic

	column S&P
		dataType: string
		lineageTag: cd1b59aa-e9a6-48e1-8bfe-31f42dd657fb
		sourceLineageTag: f6ab5386-9326-490f-8c5d-d53c2022d84d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: S&P

		annotation SummarizationSetBy = Automatic

	column 'S&P Rating Change Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 67900e30-f947-4bee-8e0e-4ad4b57ed892
		sourceLineageTag: 3844b9df-c4dc-4f26-a8ca-141085775023
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: S&P Rating Change Date

		annotation SummarizationSetBy = Automatic

	column 'S&P Rating Outlook'
		dataType: string
		lineageTag: d7259a01-1cad-46fd-905a-2494be1068c5
		sourceLineageTag: 0d4526af-ef16-4bb9-84ec-3c928ee635f3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: S&P Rating Outlook

		annotation SummarizationSetBy = Automatic

	column Fitch
		dataType: string
		lineageTag: a2d9b9b4-c793-41ac-93a1-caa961c0f438
		sourceLineageTag: fda4adb6-50db-42df-867c-c6d548b24e45
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Fitch

		annotation SummarizationSetBy = Automatic

	column 'Fitch Rating Change Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 64762335-f24f-4e59-88e4-120e1c647fbc
		sourceLineageTag: 82d23089-2b04-46e0-bb43-6b2966a4509f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Fitch Rating Change Date

		annotation SummarizationSetBy = Automatic

	column Dbrs
		dataType: string
		lineageTag: 9324dd48-c405-4973-b54e-70669373d524
		sourceLineageTag: 0128b3e7-749d-42e5-87f4-194b9a28b6a6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Dbrs

		annotation SummarizationSetBy = Automatic

	column 'Dbrs Rating Change Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 53830cff-193c-4181-912b-87e99d0079c2
		sourceLineageTag: caaec76e-96cf-4e63-a996-69f15ed05917
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Dbrs Rating Change Date

		annotation SummarizationSetBy = Automatic

	column Internal
		dataType: string
		lineageTag: b9f7390c-5d09-450d-a8d7-99cb58a3913d
		sourceLineageTag: f9bc8628-acb3-4968-9816-2c92fa3dff2d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Internal

		annotation SummarizationSetBy = Automatic

	column 'Mam Rating'
		dataType: string
		lineageTag: 2cba7032-e1aa-4ce0-989f-b94f11ea7466
		sourceLineageTag: 339a5509-dc43-4229-ab8e-e0632ca4d287
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Mam Rating

		annotation SummarizationSetBy = Automatic

	column Issuer
		dataType: string
		lineageTag: c11521c9-f8d6-4e78-9860-4ecad57245db
		sourceLineageTag: 0d2cb903-b848-4be5-9abf-3620fc899d35
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Issuer

		annotation SummarizationSetBy = Automatic

	column 'Bpl Issuer'
		dataType: string
		lineageTag: cae08d15-118e-49e3-9443-bfc6b4708f6c
		sourceLineageTag: d5a91c71-b0eb-4680-ac1a-4606dea25ded
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Bpl Issuer

		annotation SummarizationSetBy = Automatic

	column 'Internal Fund'
		dataType: string
		lineageTag: e9b89106-fe71-422f-a1d2-f3c540b2a149
		sourceLineageTag: 088a7a9c-10b3-47be-9425-2674db526617
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Internal Fund

		annotation SummarizationSetBy = Automatic

	column Coupon
		dataType: string
		lineageTag: a697da38-48dd-49dc-b7d2-6afe782a00db
		sourceLineageTag: 3a5e8a14-c9fb-4e40-87ad-4154d29181fc
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Coupon

		annotation SummarizationSetBy = Automatic

	column 'Asset Class'
		dataType: string
		lineageTag: 57ee245c-4eac-4f81-abf5-25d83aa27386
		sourceLineageTag: 172e6180-3f3c-4579-99c4-70e0e547f1fa
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asset Class

		annotation SummarizationSetBy = Automatic

	column 'Asset Group'
		dataType: string
		lineageTag: 271a806f-914a-4ffa-89a2-3dfe0318920d
		sourceLineageTag: 02d68a57-2538-4bed-bb2e-33e938c72e57
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asset Group

		annotation SummarizationSetBy = Automatic

	column 'Repo Type'
		dataType: string
		lineageTag: 352fcb5a-1dc1-4c80-8930-b00aa4c03cea
		sourceLineageTag: 6f856c92-6a63-4500-aa81-a9da8370d7e0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Repo Type

		annotation SummarizationSetBy = Automatic

	column 'Security Type 2'
		dataType: string
		lineageTag: e5afc728-c8a3-4fe6-a375-cd1fcf1f9bc2
		sourceLineageTag: b0f57334-3d65-4259-8f81-90e8eb995d75
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security Type 2

		annotation SummarizationSetBy = Automatic

	column 'Security Fund Type'
		dataType: string
		lineageTag: 5acd9a4c-31c6-4461-8f88-5203f0713cf1
		sourceLineageTag: 678ee6fd-f1d6-4c37-9a4e-4ad76b117931
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security Fund Type

		annotation SummarizationSetBy = Automatic

	column 'SCD Instrument Category'
		dataType: string
		lineageTag: bb894f0c-dbf5-4239-9887-8df2491eeede
		sourceLineageTag: 88a1da38-8ede-457f-bc5a-5521a3f063ba
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Instrument Category

		annotation SummarizationSetBy = Automatic

	column 'Inflation Linked'
		dataType: string
		lineageTag: dd37ae73-e960-4a27-91a5-a17299eecd64
		sourceLineageTag: c3ffb2d9-53bb-42af-b739-41d13f7acc3f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Inflation Linked

		annotation SummarizationSetBy = Automatic

	column 'Variable Coupon'
		dataType: string
		lineageTag: 9f3ab307-34e1-4194-9e53-63420588e4d0
		sourceLineageTag: d37ecbac-45b7-4202-8544-c1567a9135c2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Variable Coupon

		annotation SummarizationSetBy = Automatic

	column 'Next Coupon Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 94de3f18-6313-474a-9d34-757e521b7400
		sourceLineageTag: 604c06d3-6532-47b9-9f4c-02bd0d10f650
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Next Coupon Date

		annotation SummarizationSetBy = Automatic

	column 'Previous Coupon Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 1bdd54d4-987a-4d95-b0da-5483b1cff67e
		sourceLineageTag: a8e6af7f-e237-4eed-bae5-033e70dda5f6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Previous Coupon Date

		annotation SummarizationSetBy = Automatic

	column 'Maturity Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: a4a2f1b9-985d-4427-9dca-29615f82334a
		sourceLineageTag: bf00eeab-de11-4415-bb53-efc923c59097
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Maturity Date

		annotation SummarizationSetBy = Automatic

	column 'Maturity Days (D)'
		dataType: int64
		formatString: 0
		lineageTag: c54ae643-adaa-453b-a5d7-6400fd1bb99a
		sourceLineageTag: 36136b2a-0aac-4951-9365-c1e326ffbb37
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Maturity Days (D)

		annotation SummarizationSetBy = Automatic

	column 'Maturity Days 2 (D)'
		dataType: int64
		formatString: 0
		lineageTag: db831fa4-18b9-4987-84f1-9e2b665170ca
		sourceLineageTag: a52cee6f-bcbd-4a6d-bbcd-2be9551fced7
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Maturity Days 2 (D)

		annotation SummarizationSetBy = Automatic

	column 'Reset Days'
		dataType: int64
		formatString: 0
		lineageTag: 02078b65-6aa5-485a-86f0-29b4c1370d75
		sourceLineageTag: 2ce12cca-d84b-43b3-96dd-bc0483c1f374
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Reset Days

		annotation SummarizationSetBy = Automatic

	column 'Dividend Ex Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: a3919b9e-63af-471d-9db5-bbd2302390fc
		sourceLineageTag: 0aa6e1ce-2aa8-4c98-ad0a-d22892a2aa5c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Dividend Ex Date

		annotation SummarizationSetBy = Automatic

	column 'Dividend Pay Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 9c9bda79-1573-4094-a1ac-f0a117fbad45
		sourceLineageTag: a96c6be3-c18d-4de7-bda2-3284547642da
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Dividend Pay Date

		annotation SummarizationSetBy = Automatic

	column 'Dividend Record Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 53c573d8-3fee-43a0-ad60-0270e91e86d0
		sourceLineageTag: 133430f6-ed49-4ac6-bc63-19cb54cf8b52
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Dividend Record Date

		annotation SummarizationSetBy = Automatic

	column 'Dividend Rate'
		dataType: double
		lineageTag: d4844833-7d03-4b38-83a3-0998e46bf886
		sourceLineageTag: 9a01dbb4-a8b5-4b0b-8c01-53beb33c2f88
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Dividend Rate

		annotation SummarizationSetBy = Automatic

	column 'Shares Outstanding'
		dataType: double
		lineageTag: 2efe5434-44ff-4459-883e-08f838e9bd41
		sourceLineageTag: 262e402b-1a76-4b52-a805-f840eeba20c0
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Shares Outstanding

		annotation SummarizationSetBy = Automatic

	column 'Full Shares Outstanding'
		dataType: double
		lineageTag: 9dfacd42-a2a0-4e66-8951-a4002992d62d
		sourceLineageTag: fa845b0c-d254-47d5-ba77-322b3a45a33b
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Full Shares Outstanding

		annotation SummarizationSetBy = Automatic

	column 'Price Source'
		dataType: string
		lineageTag: b7c4111d-b748-4b1e-ae39-0c47b04b66bc
		sourceLineageTag: 3d53f072-a82f-436f-9d01-cf4bc89bc684
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Price Source

		annotation SummarizationSetBy = Automatic

	column 'Issue Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: d284e670-3536-4e7d-9430-6841aae9908c
		sourceLineageTag: a5a40b52-2a83-4b8c-a79d-2558fe7f554b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Issue Dt

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 92f698be-73fc-42e2-9e43-055be39a5d5c
		sourceLineageTag: bb4180b9-7504-4cdc-bbc9-f5bb2d248a01
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Country Of Risk'
		dataType: string
		lineageTag: 0a798d50-539c-4b77-b1ea-0ae1b3a62c3e
		sourceLineageTag: 1cf25477-7605-4000-b1c8-03cef0aa15b4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Country Of Risk

		annotation SummarizationSetBy = Automatic

	column 'Country Of Issue'
		dataType: string
		lineageTag: a0f801ff-69f1-4dd2-9bd3-f0bb2adac69a
		sourceLineageTag: b827e487-a5e7-4c6d-b86b-fdcc75d4cdf0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Country Of Issue

		annotation SummarizationSetBy = Automatic

	column 'Country Of Domicile'
		dataType: string
		lineageTag: 360efdbd-9322-4354-94de-aeda2e8d3df2
		sourceLineageTag: 06580a89-b69d-48d7-9794-adea60acd3e7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Country Of Domicile

		annotation SummarizationSetBy = Automatic

	column 'Amount Issued'
		dataType: double
		lineageTag: 1bcef422-a419-4c22-8ee0-79fd44fcc626
		sourceLineageTag: c22478b2-8613-4d10-89db-274ad63cb868
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Amount Issued

		annotation SummarizationSetBy = Automatic

	column 'Amount Outstanding'
		dataType: double
		lineageTag: 9c4c5fe4-449b-4722-8158-7b1b96eef701
		sourceLineageTag: b31ce779-0b09-48d6-87f1-fb486970af2e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Amount Outstanding

		annotation SummarizationSetBy = Automatic

	column 'Market Sector'
		dataType: string
		lineageTag: a765dd7d-ed65-4901-9de6-f0e5d15a37c2
		sourceLineageTag: 16094615-c6aa-4370-85e5-641c74707d92
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Market Sector

		annotation SummarizationSetBy = Automatic

	column 'Underlying Asset Type'
		dataType: string
		lineageTag: ce17b4c1-798c-4200-876f-6aeb4cec0765
		sourceLineageTag: a2e48172-e7db-4090-96fa-dea3dc517429
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Underlying Asset Type

		annotation SummarizationSetBy = Automatic

	column 'Fund Geographic Focus'
		dataType: string
		lineageTag: 1341a5d0-1f1e-4537-aad1-e0112f0d7e70
		sourceLineageTag: a291c651-5aea-4615-a738-acdaeb185f29
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Fund Geographic Focus

		annotation SummarizationSetBy = Automatic

	column 'Conversion Ratio'
		dataType: double
		lineageTag: f535e5e0-823a-4754-8e6f-f6d6e5ef6731
		sourceLineageTag: 2964bd74-816d-4eff-a250-d970d2c7ec6e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Conversion Ratio

		annotation SummarizationSetBy = Automatic

	column 'Conversion Start Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: bfd43794-88e8-435e-8802-6a46d9c8ef56
		sourceLineageTag: 7f944797-0be2-4c5f-8eae-7aacbf9cd1e8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Conversion Start Date

		annotation SummarizationSetBy = Automatic

	column 'Conversion To Ticker'
		dataType: string
		lineageTag: cf4b6952-b0e0-477a-bf5b-af3b4fdf1744
		sourceLineageTag: 636bf640-f4dd-47f9-b7f3-68b6d54c1169
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Conversion To Ticker

		annotation SummarizationSetBy = Automatic

	column 'Voting Rights'
		dataType: double
		lineageTag: a16f2d4e-4877-4a8a-93a9-ea3f3bca5012
		sourceLineageTag: 776ea03a-e027-4ead-a5cd-71914c469a5a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Voting Rights

		annotation SummarizationSetBy = Automatic

	column 'Convertible Indicator'
		dataType: string
		lineageTag: 7d340587-91d9-421e-bae2-ee97a91ba270
		sourceLineageTag: 1c72f36d-17ad-48ce-8453-ebbb7f76b85c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Convertible Indicator

		annotation SummarizationSetBy = Automatic

	column 'Issuer State Of Domicile'
		dataType: string
		lineageTag: 5e5ac44f-0223-4671-9e68-bd51d97b1f03
		sourceLineageTag: fccbcabf-8325-40d7-a0d4-73d13c5e95a8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Issuer State Of Domicile

		annotation SummarizationSetBy = Automatic

	column 'Issuer State Of Incorporation'
		dataType: string
		lineageTag: c61b25db-c9a8-4fa4-a93d-c795519cb152
		sourceLineageTag: 7527dff1-7577-47de-a5b8-dbe0df37f070
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Issuer State Of Incorporation

		annotation SummarizationSetBy = Automatic

	column '144A Flag'
		dataType: string
		lineageTag: 50613c32-4edc-4fcc-b4c5-f02314664817
		sourceLineageTag: 21843bbf-f019-4b0c-9b9e-50a8f9f1933a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: 144A Flag

		annotation SummarizationSetBy = Automatic

	column 'Agency Backed Mortgage'
		dataType: string
		lineageTag: 93acd412-831a-491e-a096-8a727957badb
		sourceLineageTag: 16c772a1-0146-40d1-9a30-f7f02d3c3348
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Agency Backed Mortgage

		annotation SummarizationSetBy = Automatic

	column 'Reset Index'
		dataType: string
		lineageTag: 3836e9cd-0716-4aa7-9d5c-8717087800ba
		sourceLineageTag: c473bd71-d203-4eac-810d-42898f2b2cbb
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Reset Index

		annotation SummarizationSetBy = Automatic

	column 'Mortgage Tranche Type Full'
		dataType: string
		lineageTag: d2d80458-3acf-420e-964b-72f4c34ab6b9
		sourceLineageTag: 8b20fae1-7de2-4aea-bd48-98aba555691f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Mortgage Tranche Type Full

		annotation SummarizationSetBy = Automatic

	column 'Mortgage Tranche Description'
		dataType: string
		lineageTag: 1982a3b3-6fae-4b8e-99a5-a838317da1e9
		sourceLineageTag: c3d23c93-15a5-4711-8f49-f0e5e4d4df13
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Mortgage Tranche Description

		annotation SummarizationSetBy = Automatic

	column 'Calc Type Description'
		dataType: string
		lineageTag: c4a60b22-fff1-408c-bf24-905dd027654e
		sourceLineageTag: 49fdb63b-3869-4077-bd8d-bf449f75b706
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Calc Type Description

		annotation SummarizationSetBy = Automatic

	column 'Next Reset Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: d342189e-82b8-414f-affb-63ea1193e33f
		sourceLineageTag: 9e403aba-69d4-4f98-b2ff-f26fc4aaf199
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Next Reset Date

		annotation SummarizationSetBy = Automatic

	column 'Contract Size'
		dataType: double
		lineageTag: eed2e6dd-b6be-458d-87a8-e1355c584460
		sourceLineageTag: 2c896789-dd0a-4d83-a3c0-fbb686695fa3
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Contract Size

		annotation SummarizationSetBy = Automatic

	column 'Exercise Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 0edd7ac7-2244-4fab-bd8b-00cb8c80c351
		sourceLineageTag: a5e254b5-4616-44e1-88d2-6b081975a910
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Exercise Date

		annotation SummarizationSetBy = Automatic

	column 'Expiry Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: b6addd3f-cc8f-42ed-b1f0-ec41dbfbc0f3
		sourceLineageTag: fc399c5a-1aca-4982-95a8-68cbc7b5e1e0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Expiry Date

		annotation SummarizationSetBy = Automatic

	column 'Contract Side'
		dataType: string
		lineageTag: 71243669-9562-4e44-8f83-79b270a45c90
		sourceLineageTag: 096eb22c-e518-41a8-883a-06c733c670bc
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Contract Side

		annotation SummarizationSetBy = Automatic

	column 'Future Contract Date'
		dataType: string
		lineageTag: ed208227-bcbf-4735-8e8f-d87de8928e68
		sourceLineageTag: bd9c4b52-b438-41ba-9527-98a740c0fdc3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Future Contract Date

		annotation SummarizationSetBy = Automatic

	column 'Ultimate Parent Company Name'
		dataType: string
		lineageTag: f3c2b856-561f-45de-a8e9-7da94625354b
		sourceLineageTag: 5d1279d9-b6f6-4b72-b359-48d9ef96cf7f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Ultimate Parent Company Name

		annotation SummarizationSetBy = Automatic

	column 'Us Illiquid'
		dataType: string
		lineageTag: 1fb7df11-14aa-4ed4-b149-eb6056729599
		sourceLineageTag: 19bdff00-aff1-4a9f-a026-b3849cd9f807
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Us Illiquid

		annotation SummarizationSetBy = Automatic

	column 'Ca Illiquid'
		dataType: string
		lineageTag: 69204b31-4e7b-4861-aa45-ce7ba4e56636
		sourceLineageTag: 83379730-e91a-4b75-aed8-a35ba12755cb
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Ca Illiquid

		annotation SummarizationSetBy = Automatic

	column 'Municipal Lease Obligation'
		dataType: string
		lineageTag: c31cd1e7-0061-4242-a6ff-2c9a2cb69ddb
		sourceLineageTag: c5791e92-970a-410a-b38c-89ffb00062e3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Municipal Lease Obligation

		annotation SummarizationSetBy = Automatic

	column 'Regulatory Type'
		dataType: string
		lineageTag: 952168c6-3272-470a-80c5-7573c70a12bc
		sourceLineageTag: bd4a10dc-7d87-4a55-9170-1cbc3f73c9d1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Regulatory Type

		annotation SummarizationSetBy = Automatic

	column 'Reg S'
		dataType: string
		lineageTag: 16fa097f-572d-4a8d-a31f-1e607884922d
		sourceLineageTag: 29c9272d-5574-4177-9c1e-73f0d1636895
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Reg S

		annotation SummarizationSetBy = Automatic

	column 'Sinkable Indicator'
		dataType: string
		lineageTag: 8736b064-ac70-4c9a-8512-8ad40cc7b366
		sourceLineageTag: e5dc55eb-dc50-425e-bf31-7b498cf29f05
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Sinkable Indicator

		annotation SummarizationSetBy = Automatic

	column 'Next Sink Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: f2a92c9b-32cb-4bc8-8db2-943e1fd9470b
		sourceLineageTag: 2b68b766-35c7-4664-9dc3-a268683cf1db
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Next Sink Date

		annotation SummarizationSetBy = Automatic

	column 'Islamic Indicator'
		dataType: string
		lineageTag: 58b117b2-0586-47ce-905a-fbaf0b4d4af3
		sourceLineageTag: e574065b-38b0-44b3-9f65-c787a0b6f480
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Islamic Indicator

		annotation SummarizationSetBy = Automatic

	column 'Mortgage Principal Losses'
		dataType: double
		lineageTag: b65006ec-6a24-416e-ae8b-05577922e118
		sourceLineageTag: b71ecb8a-75ae-430d-a9ef-ab5e98c20940
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Mortgage Principal Losses

		annotation SummarizationSetBy = Automatic

	column 'Mortgage Interest Shortfall'
		dataType: double
		lineageTag: 7af1bf09-bea1-43c3-8ca4-fc07d916bdaa
		sourceLineageTag: d6ee1d9b-7bf5-4f51-ac5e-6c19329f8ea7
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Mortgage Interest Shortfall

		annotation SummarizationSetBy = Automatic

	column 'Local ID'
		dataType: string
		lineageTag: 12ab3baa-4594-4501-883f-3f76f2cd487c
		sourceLineageTag: 7ac50d65-1001-4b6f-a469-cb2336620d22
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Local ID

		annotation SummarizationSetBy = Automatic

	column 'Local Sector'
		dataType: string
		lineageTag: c3cb1436-ce11-478c-8a56-703b2e869f01
		sourceLineageTag: 4ed30597-fd65-4291-8df5-93cfe1d98473
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Local Sector

		annotation SummarizationSetBy = Automatic

	column 'Asia Rating'
		dataType: string
		lineageTag: 59f91c71-7a9a-482a-bb34-4105070f5141
		sourceLineageTag: fbc8ff72-eeb5-4b30-890c-e40b836b5c85
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asia Rating

		annotation SummarizationSetBy = Automatic

	column 'Ram Rating'
		dataType: string
		lineageTag: be9c3c43-5885-48c2-b60f-0ae65a37c72e
		sourceLineageTag: 0a66d151-6b78-4b5f-8bd6-8d7bb5971da7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Ram Rating

		annotation SummarizationSetBy = Automatic

	column 'Marc Rating'
		dataType: string
		lineageTag: 11035872-e041-4685-9279-4291c739fb4f
		sourceLineageTag: 12f38dc2-54ec-4d24-84f7-19f2f754d012
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Marc Rating

		annotation SummarizationSetBy = Automatic

	column 'ML Liquidity Change'
		dataType: string
		lineageTag: fbd4a73a-93d3-420e-8183-48ccfcdbc606
		sourceLineageTag: de487fd9-e8a8-4144-a363-0a57589013c1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Liquidity Change

		annotation SummarizationSetBy = Automatic

	column 'ML Municipal Obligor'
		dataType: string
		lineageTag: c82e3f67-50e0-4f8f-8965-93a227700a70
		sourceLineageTag: ef2cc9b3-0712-48fd-9fd3-d87328a710aa
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Municipal Obligor

		annotation SummarizationSetBy = Automatic

	column 'Offering Type'
		dataType: string
		lineageTag: 8dba0028-3274-42b8-856b-74c18cae1935
		sourceLineageTag: 5147a549-4f55-4dc6-a618-63d299aa3384
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Offering Type

		annotation SummarizationSetBy = Automatic

	column 'Regulatory Structure'
		dataType: string
		lineageTag: abeb2ac1-29e9-4ecd-9cdc-80adaa07c39e
		sourceLineageTag: 76ad6a88-36a4-4cf1-a15e-652aa6902176
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Regulatory Structure

		annotation SummarizationSetBy = Automatic

	column 'Exchange Country'
		dataType: string
		lineageTag: 398bd798-8914-4f75-a016-83c54b4f9145
		sourceLineageTag: 4847aae1-22cb-4e20-9e0b-dd6f42b89490
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Exchange Country

		annotation SummarizationSetBy = Automatic

	column 'Issuer Type'
		dataType: string
		lineageTag: d7e6d37e-4fb5-4ef1-94b3-f2ff88d65bab
		sourceLineageTag: 19d50e15-a667-4866-a118-717ef7c63d94
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Issuer Type

		annotation SummarizationSetBy = Automatic

	column 'My Local Sec Type'
		dataType: string
		lineageTag: 7755fd10-b600-4edc-9c05-90e0e13cc9e8
		sourceLineageTag: 097127d8-c291-4664-91d9-504ec1e848de
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: My Local Sec Type

		annotation SummarizationSetBy = Automatic

	column 'Private Placement'
		dataType: string
		lineageTag: db523cb9-d7c8-42d6-9592-a7245f5af21e
		sourceLineageTag: 62b8d173-dc48-4e8e-ad0a-7a29e79b0299
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Private Placement

		annotation SummarizationSetBy = Automatic

	column 'Default Flag'
		dataType: string
		lineageTag: 83a76b39-113b-4289-b3d4-13bc54367e71
		sourceLineageTag: 0ee112c3-58a3-42f6-8d43-68a04477aafa
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Default Flag

		annotation SummarizationSetBy = Automatic

	column 'Fi Type'
		dataType: string
		lineageTag: 848fc4a9-6421-434e-8161-0775002551cc
		sourceLineageTag: a7fadc91-ea9c-446e-a93e-419bb2e34528
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Fi Type

		annotation SummarizationSetBy = Automatic

	column 'S&P Short Term Rating'
		dataType: string
		lineageTag: 2bdcc3cf-54aa-4c13-82fc-20c5bc4d6fab
		sourceLineageTag: ffa875a3-37a6-4ac0-a909-bb55bbd49880
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: S&P Short Term Rating

		annotation SummarizationSetBy = Automatic

	column 'Moodys Short Term Rating'
		dataType: string
		lineageTag: e89de895-8cbe-4ddb-ba1b-60854bc46f25
		sourceLineageTag: 364b199a-4437-4d81-9b71-5d67717b6e95
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Moodys Short Term Rating

		annotation SummarizationSetBy = Automatic

	column 'Fitch Short Term Rating'
		dataType: string
		lineageTag: ec0af077-46ba-4e68-8dda-cff607947e43
		sourceLineageTag: 822c5108-8b7b-4075-9a2e-27320e1c129e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Fitch Short Term Rating

		annotation SummarizationSetBy = Automatic

	column 'Bpl Country'
		dataType: string
		lineageTag: 501d0165-e245-447e-8e9b-e8626fa11eff
		sourceLineageTag: 43b78144-6c5f-4759-852d-8bbcc0aedc36
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Bpl Country

		annotation SummarizationSetBy = Automatic

	column 'Discount Indicator'
		dataType: string
		lineageTag: ea0161f5-dd40-4a40-a320-980be2b04d05
		sourceLineageTag: 43a6c56a-605c-42ac-836f-226fbfbeb2b7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Discount Indicator

		annotation SummarizationSetBy = Automatic

	column 'St Comprehensive'
		dataType: string
		lineageTag: 5009c35a-a85b-442c-a1f2-99cc96ae97fd
		sourceLineageTag: f1dec84f-d9b1-433a-83e2-76cca3bb1787
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: St Comprehensive

		annotation SummarizationSetBy = Automatic

	column 'Eq Sector'
		dataType: string
		lineageTag: 3df5d3f1-e677-4821-b687-e9aab5631051
		sourceLineageTag: 13bb6ef0-55bd-4ecf-a419-2e6058a87632
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Eq Sector

		annotation SummarizationSetBy = Automatic

	column 'Accrual Currency'
		dataType: string
		lineageTag: 691290c2-f9bd-422f-adaa-1a905bb18e1f
		sourceLineageTag: 27dd5347-4402-49a9-ab65-76ff3e1a8f2a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Accrual Currency

		annotation SummarizationSetBy = Automatic

	column 'Settlement Type'
		dataType: string
		lineageTag: 8ae6ad4a-384f-424d-abeb-a3b35b8d159d
		sourceLineageTag: d0a65e8b-1663-4e81-92ff-55955d0c4ed4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Settlement Type

		annotation SummarizationSetBy = Automatic

	column Sector
		dataType: string
		lineageTag: 58d026da-a7c3-46f1-b35f-7f7fc12aba5d
		sourceLineageTag: dd30e98a-5c98-4613-88eb-20d7db8fd883
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Sector

		annotation SummarizationSetBy = Automatic

	column 'Industry Group'
		dataType: string
		lineageTag: 723a85fb-3d1f-4e90-82c3-bd5cdeefa8d1
		sourceLineageTag: 9f6da36e-5dce-4461-8b67-abb7ca7b2ba3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Industry Group

		annotation SummarizationSetBy = Automatic

	column Industry
		dataType: string
		lineageTag: 52a0c39b-1f09-48f1-ab25-5611efb25c05
		sourceLineageTag: e1f7cdbe-c4ab-49a7-89fe-ec4969d3a4f3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Industry

		annotation SummarizationSetBy = Automatic

	column 'Sub Industry'
		dataType: string
		lineageTag: e8bacf6c-b0a7-4e2b-855e-06d1987f0a5a
		sourceLineageTag: 7d1c185c-e37b-4a1f-b927-0ff735a762a1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Sub Industry

		annotation SummarizationSetBy = Automatic

	column 'Gics Bics'
		dataType: string
		lineageTag: d59e10af-0ded-4c1c-8090-5be4640621c7
		sourceLineageTag: e682e4dd-346c-409c-8425-9fecdd1c4b03
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Gics Bics

		annotation SummarizationSetBy = Automatic

	column 'Subord Type'
		dataType: string
		lineageTag: 068101b0-59af-4faa-9bf6-df279647a020
		sourceLineageTag: 09366bcb-3108-43d1-8b9e-70f540034fc4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Subord Type

		annotation SummarizationSetBy = Automatic

	column 'ML Ifrs 13 Level'
		dataType: string
		lineageTag: bf238785-2925-4b92-93f4-63ba0769bb8e
		sourceLineageTag: 61d777f5-3114-4faf-970d-94d810fa12ec
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Ifrs 13 Level

		annotation SummarizationSetBy = Automatic

	column 'Price Point'
		dataType: string
		lineageTag: e05845f8-30db-40c3-ac9f-3df710505560
		sourceLineageTag: 78ed48a0-f522-4ed0-a7de-db357abe39ff
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Price Point

		annotation SummarizationSetBy = Automatic

	column 'Day Count'
		dataType: string
		lineageTag: f82547af-b118-4df3-bc7d-2d584d0e0665
		sourceLineageTag: 84ab69cf-77c5-474e-a8c6-2bc307e617cf
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Day Count

		annotation SummarizationSetBy = Automatic

	column 'Findur ID'
		dataType: string
		lineageTag: acfcdb07-e49e-4be7-b567-fbc646fe79d3
		sourceLineageTag: 0cd6167d-cf75-4ad7-bc42-6062b288615c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Findur ID

		annotation SummarizationSetBy = Automatic

	column 'Manulife Local Price'
		dataType: double
		lineageTag: f7c9321c-49b9-449b-b2bc-b98c52d79789
		sourceLineageTag: 07c46b26-d42b-4aca-bdce-30d19eb3f89a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Manulife Local Price

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 2f7c74fd-e72e-46c3-bace-9dab9c615630
		sourceLineageTag: aa828db3-e613-47b7-82bf-463f1118908d
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Payment Rank'
		dataType: string
		lineageTag: 6a406622-23a2-415e-bfb2-a6a3c5e11a4e
		sourceLineageTag: 76943de4-041d-4dd6-a609-d1d37ef98984
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Payment Rank

		annotation SummarizationSetBy = Automatic

	column 'ML Investment Id'
		dataType: string
		lineageTag: dec729ff-7fbe-4bdb-b25a-98f612c0c106
		sourceLineageTag: 57366eef-0187-4617-bd0d-e7ff34be4f6a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Investment Id

		annotation SummarizationSetBy = Automatic

	column 'ML Investment Type Cd'
		dataType: string
		lineageTag: 87c5b651-a6b0-4faa-ba93-5f3f59d845c7
		sourceLineageTag: b4c98bc4-301a-4fbe-b78e-da574b22338f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Investment Type Cd

		annotation SummarizationSetBy = Automatic

	column 'Coupon Frequency'
		dataType: string
		lineageTag: 879022f2-8f6b-4eef-93c6-61451fc2299b
		sourceLineageTag: bb02a4c9-ea58-415d-ad1e-96f5158943bb
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Coupon Frequency

		annotation SummarizationSetBy = Automatic

	column 'SCD GL Classification'
		dataType: string
		lineageTag: 11ef69eb-46d8-46d2-9608-0fedc4fbf6da
		sourceLineageTag: 93ab23d1-e15a-4018-a5f3-dd0420fe3a9f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD GL Classification

		annotation SummarizationSetBy = Automatic

	column 'SCD GL Classification JGAAP'
		dataType: string
		lineageTag: f0029ed6-b055-4c93-a8d5-c16eafad20dc
		sourceLineageTag: 4a13e311-16cc-4273-80de-f7a36ad59603
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD GL Classification JGAAP

		annotation SummarizationSetBy = Automatic

	column 'SCD GL Classification NAIC'
		dataType: string
		lineageTag: 5e883777-2d51-419a-b520-2cd8457a8fc4
		sourceLineageTag: b5cc7833-ba76-43ec-a565-21c32b17ae3c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD GL Classification NAIC

		annotation SummarizationSetBy = Automatic

	column 'ML Private Asset ID'
		dataType: string
		lineageTag: 6d7d4c07-516a-478f-b2ba-f85f1a84df31
		sourceLineageTag: c4553a99-ab3c-4961-8109-6d5b06b60ea2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Private Asset ID

		annotation SummarizationSetBy = Automatic

	column 'Japan Credit Rating Cd'
		dataType: string
		lineageTag: b9029e04-2484-4b89-8f2f-e7a9e548f651
		sourceLineageTag: 3ddedc9e-115a-4024-827f-b20e288655cf
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Japan Credit Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'RI Rating Cd'
		dataType: string
		lineageTag: 4cdc226a-d2cb-4845-b18b-4b5aea1c8ca1
		sourceLineageTag: 68029965-9368-42d7-b52d-477ea5d55a70
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: RI Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'ML Local China ID'
		dataType: string
		lineageTag: ac12865d-d221-4dba-b7b6-36be48046e7f
		sourceLineageTag: 4e4ddcb4-a548-4240-96fd-ec0406150ef5
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Local China ID

		annotation SummarizationSetBy = Automatic

	column 'ML Vault ID'
		dataType: string
		lineageTag: 151accd0-80f4-44c1-b8a1-f7a50cb743b0
		sourceLineageTag: a34006d6-6998-4173-a85f-3853719ec4b5
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Vault ID

		annotation SummarizationSetBy = Automatic

	column 'ML Vault Name'
		dataType: string
		lineageTag: b3dfd699-7cf4-4bf3-8ecd-28889c9de695
		sourceLineageTag: 8e66de88-2f1c-4dae-8f25-43b7abc12a2c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Vault Name

		annotation SummarizationSetBy = Automatic

	column 'ML IRR Rating'
		dataType: string
		lineageTag: c91627ef-5e85-4817-ba46-fe7229d62118
		sourceLineageTag: cd388e5d-e0c8-4892-9921-be672e58364c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML IRR Rating

		annotation SummarizationSetBy = Automatic

	column 'ML MFC Equivalent Rating'
		dataType: string
		isHidden
		lineageTag: c070a83b-14f1-4a7d-80f2-4d06530cfbdb
		sourceLineageTag: f3be8307-fa06-4d5b-ac1b-efda2185fb0c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML MFC Equivalent Rating

		annotation SummarizationSetBy = Automatic

	column 'ML Primary Rating Cd'
		dataType: string
		lineageTag: 5984252d-878f-42f6-94dc-7b833679a880
		sourceLineageTag: 9634f54b-4527-4760-9b11-3cd5ed8361d4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Primary Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'ML JH Rating Cd'
		dataType: string
		lineageTag: 52062450-8a9f-404c-b7b4-e51a831ce8b9
		sourceLineageTag: 26fbe0c9-6b2d-435b-968e-3d527cf1f8e5
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML JH Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'Has Coupon Variable'
		dataType: string
		lineageTag: f8f55f18-e4cd-4e8a-a5f1-98fb796e350e
		sourceLineageTag: a7c8b0d6-79e5-493f-8537-efc4ee870d03
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Has Coupon Variable

		annotation SummarizationSetBy = Automatic

	column 'Next Call Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 855aa9e3-43f0-4cd4-8042-0833fe448bcd
		sourceLineageTag: 34fc218d-4f87-4a42-a9a6-36ae0ea984dd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Next Call Date

		annotation SummarizationSetBy = Automatic

	column 'Price Currency'
		dataType: string
		lineageTag: 09cccbbc-31e6-46be-9807-115363818fab
		sourceLineageTag: e8b0f1eb-7174-4313-ba93-a366ac80f62c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Price Currency

		annotation SummarizationSetBy = Automatic

	column 'Next Call PX'
		dataType: double
		lineageTag: 2d8b1022-1315-4d93-a83d-b70582867b10
		sourceLineageTag: 7b7f09b9-c3bb-41fc-b3cb-d4c4fa9a1a6e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Next Call PX

		annotation SummarizationSetBy = Automatic

	column 'Next Put PX'
		dataType: double
		lineageTag: b92f45c8-eea8-4aad-8004-996b141db138
		sourceLineageTag: 02da532d-63a9-4941-a3a0-335ee3b6e120
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Next Put PX

		annotation SummarizationSetBy = Automatic

	column 'Next Put Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 6c3e801f-8016-4e1a-8712-fa74264b3de6
		sourceLineageTag: ff0cbd43-1a15-4f24-a191-600906314faf
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Next Put Dt

		annotation SummarizationSetBy = Automatic

	column 'Make Whole Call'
		dataType: string
		lineageTag: 96517ab9-dd3b-4aa2-aa41-562eda81939e
		sourceLineageTag: c6a54014-9dcb-4f79-ba10-cf96422d8626
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Make Whole Call

		annotation SummarizationSetBy = Automatic

	column Callable
		dataType: string
		lineageTag: 4f753be1-3d5f-46a3-a4b7-305c666e569c
		sourceLineageTag: ed2f242b-4f22-4464-bcc4-f5c0295661fd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Callable

		annotation SummarizationSetBy = Automatic

	column Putable
		dataType: string
		lineageTag: 6d57be6b-7be3-4b81-b844-be332f4324c6
		sourceLineageTag: 45ace53e-6234-4afd-8b61-3f83f8684fe1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Putable

		annotation SummarizationSetBy = Automatic

	column 'Std Currency'
		dataType: string
		lineageTag: f0263eb9-f5ee-40f1-a7f5-43c0714db76c
		sourceLineageTag: dca5bfb4-6f89-44c3-adef-82b6a10da3cd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Std Currency

		annotation SummarizationSetBy = Automatic

	column 'Coupon Type'
		dataType: string
		lineageTag: d6c6c363-1735-481f-a55d-6f4533b3d751
		sourceLineageTag: 409b147f-6997-44d8-93f3-47e736cf3783
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Coupon Type

		annotation SummarizationSetBy = Automatic

	column 'ID BPL Pricing Strategy'
		dataType: string
		lineageTag: 4b2125e2-f463-4e5b-b6b2-6071422c58fd
		sourceLineageTag: 0f197b67-3d1b-4cd4-879f-c7d5c8d92067
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ID BPL Pricing Strategy

		annotation SummarizationSetBy = Automatic

	column 'ID BPL Price Point'
		dataType: string
		lineageTag: 9d0241e9-e656-475d-a74f-e2cbc165eb77
		sourceLineageTag: 723f6b5e-fca7-4ce6-9e58-91fd48cf949a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ID BPL Price Point

		annotation SummarizationSetBy = Automatic

	column 'Indonesian Price'
		dataType: double
		lineageTag: 8ceab7fa-a465-4ac0-82f2-7e189eb9ca76
		sourceLineageTag: 97f74dce-a00c-4a07-be74-0610faf5b6da
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Indonesian Price

		annotation SummarizationSetBy = Automatic

	column 'MRM Sector (Private Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: b31f7acd-a577-482b-bbeb-bf8f83620551
		sourceLineageTag: 431ef170-5298-4fe9-a35d-a76a12474146
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Sector (Private Sec)

		annotation SummarizationSetBy = Automatic

	column 'Calm Category'
		dataType: string
		lineageTag: 9bb4a13b-e327-4b02-ae0d-b11c078acd1a
		sourceLineageTag: 7c6dcd3c-e418-4cd9-b10e-f5ab8aefad80
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Calm Category

		annotation SummarizationSetBy = Automatic

	column 'Schedule BA Asset Category Code'
		dataType: string
		lineageTag: 665dc08c-3496-4f42-88d1-4527257d350d
		sourceLineageTag: 0881a3ec-1c65-49a6-809d-1af88df541b0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Schedule BA Asset Category Code

		annotation SummarizationSetBy = Automatic

	column 'Seed Money Ind'
		dataType: string
		lineageTag: 4c429bd2-fb30-45e7-ba4e-9d664a228a8a
		sourceLineageTag: 9a13730c-8e7d-4c34-8322-5558e8953b0d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Seed Money Ind

		annotation SummarizationSetBy = Automatic

	column 'ML Minor Type'
		dataType: string
		lineageTag: b5caf6f5-b344-4951-96d7-d2652e32dd7e
		sourceLineageTag: 2e619a5a-cfd2-4910-a841-941c2af9db91
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Minor Type

		annotation SummarizationSetBy = Automatic

	column 'BICS Level2 Industry Group Desc'
		dataType: string
		lineageTag: af6ca923-a2de-413f-bb94-4761fb850f26
		sourceLineageTag: 5a21f03f-a7b6-45f1-ba0c-944b398aebb4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: BICS Level2 Industry Group Desc

		annotation SummarizationSetBy = Automatic

	column 'SCD Security Type'
		dataType: string
		lineageTag: 37b460c4-45e7-4e05-a032-a8f1328cf322
		sourceLineageTag: 18141fe2-9a57-4c2c-b07c-51467e3638c5
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Security Type

		annotation SummarizationSetBy = Automatic

	column 'Issuer Long Comp Name'
		dataType: string
		lineageTag: aefa1df3-eafa-4101-85f8-222e38200026
		sourceLineageTag: b81d42d9-755f-496e-b417-e057a79fcec1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Issuer Long Comp Name

		annotation SummarizationSetBy = Automatic

	column 'Issuer Name'
		dataType: string
		lineageTag: e7520aee-0d9b-4651-adc0-187991865479
		sourceLineageTag: fad30931-7182-4e69-a528-db86059909f4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Issuer Name

		annotation SummarizationSetBy = Automatic

	column 'Paying Agent'
		dataType: string
		lineageTag: 764a11b8-c082-432c-b76d-e8a2417abd4c
		sourceLineageTag: 753c6fef-424b-424e-85b4-e1aa4fb3ef56
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Paying Agent

		annotation SummarizationSetBy = Automatic

	column 'Long Company Name'
		dataType: string
		lineageTag: 479db44a-64d4-427e-81ad-3a22a15751d7
		sourceLineageTag: 1d70912a-e423-4239-bf27-75d731fa8fa1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Long Company Name

		annotation SummarizationSetBy = Automatic

	column 'BICS Level1 Sector Desc'
		dataType: string
		lineageTag: 073c28da-7b7e-4739-a5bc-53d41d3a55c1
		sourceLineageTag: bb310859-54fe-4164-a6a6-71ea86f092ac
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: BICS Level1 Sector Desc

		annotation SummarizationSetBy = Automatic

	column 'BICS Level3 Industry Desc'
		dataType: string
		lineageTag: 655a6d1b-8762-4151-be22-43f7fdc0dc7d
		sourceLineageTag: d0e53a3a-f4ba-46be-be52-92677eebdfb9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: BICS Level3 Industry Desc

		annotation SummarizationSetBy = Automatic

	column 'BICS Level4 Sub Industry Desc'
		dataType: string
		lineageTag: 489d310e-0773-4e43-8c0a-1432141f532e
		sourceLineageTag: ffebe8df-da35-4189-b684-a4a35e54adbc
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: BICS Level4 Sub Industry Desc

		annotation SummarizationSetBy = Automatic

	column 'Analyst Team'
		dataType: string
		lineageTag: fb2c7fb2-a32c-4f0d-87d6-1563ee2cfb64
		sourceLineageTag: 901e438d-0ace-41b4-a02b-1237d91933da
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Analyst Team

		annotation SummarizationSetBy = Automatic

	column 'ID BB Company'
		dataType: string
		lineageTag: 8be22a31-4d38-4be4-a2ce-6bbb0f7af25c
		sourceLineageTag: 0e22bc62-f95e-4314-a2a5-a3bffd8400b9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ID BB Company

		annotation SummarizationSetBy = Automatic

	column 'ID BB Global Company'
		dataType: string
		lineageTag: 109837fd-374d-4409-99c4-acdccfb0a1b2
		sourceLineageTag: f3e8b010-4300-4c9e-bf84-3c8c89cd72f3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ID BB Global Company

		annotation SummarizationSetBy = Automatic

	column 'Asset Type'
		dataType: string
		lineageTag: 26847965-52c4-407a-b94d-e0d5463980ed
		sourceLineageTag: 7f40e837-3797-410c-89cc-01766eb30394
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asset Type

		annotation SummarizationSetBy = Automatic

	column 'Coupon Spread'
		dataType: double
		lineageTag: c303e4c4-5919-4486-870b-4667ddc9c501
		sourceLineageTag: 478316ce-02fb-4792-8242-441bf3367e15
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Coupon Spread

		annotation SummarizationSetBy = Automatic

	column 'ML Ifrs Accounting Method'
		dataType: string
		lineageTag: ae9c7103-fd0b-4c4e-88c7-384404fba67f
		sourceLineageTag: fd67a412-bd85-4793-ac69-3b8d7af7ae9c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Ifrs Accounting Method

		annotation SummarizationSetBy = Automatic

	column 'ML Lgaap Accounting Method'
		dataType: string
		lineageTag: 7b8f30fc-a781-4db7-95d9-1d2818d320ad
		sourceLineageTag: 1b81605c-dadf-487f-89f0-2a92ebdcb791
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Lgaap Accounting Method

		annotation SummarizationSetBy = Automatic

	column 'ML Stat Accounting Method'
		dataType: string
		lineageTag: 4ea60ecd-7986-4c02-a83d-ba29a5009916
		sourceLineageTag: 2b35f58b-69ad-49e2-bde8-0b5301e45a0f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Stat Accounting Method

		annotation SummarizationSetBy = Automatic

	column 'ML Ba Avr Cd'
		dataType: string
		lineageTag: aeaf60f4-bcba-4376-b1e4-0cdca8a68326
		sourceLineageTag: 9be7ed19-e01a-4384-a245-1da33e1575c7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Ba Avr Cd

		annotation SummarizationSetBy = Automatic

	column 'Called Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: d1790d40-5a2a-48f6-b182-249cfdb128ef
		sourceLineageTag: 4b8faac1-910d-4112-a140-1a1e0d9e8a01
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Called Dt

		annotation SummarizationSetBy = Automatic

	column 'Called Px'
		dataType: double
		lineageTag: 800d2d71-6ef5-4fb9-937b-661b861d6267
		sourceLineageTag: c978a306-04ae-490d-b85c-733c5db4bf5d
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Called Px

		annotation SummarizationSetBy = Automatic

	column 'Is Perpetual'
		dataType: string
		lineageTag: e252e180-c3bf-4829-bc58-5ec2c0037dac
		sourceLineageTag: 0586420d-5731-492a-a319-4cada893b5a6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Is Perpetual

		annotation SummarizationSetBy = Automatic

	column 'Basic Spread'
		dataType: double
		lineageTag: ab75516b-7aed-4b34-bdb2-a4c182da6ac1
		sourceLineageTag: a5dbf4a4-a869-4051-b939-7037dcb71711
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Basic Spread

		annotation SummarizationSetBy = Automatic

	column 'Fix To Float Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: f44169af-715f-4c95-8932-aada68d398dc
		sourceLineageTag: 89e29b02-e133-4a95-aa57-797160e19c4b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Fix To Float Date

		annotation SummarizationSetBy = Automatic

	column 'GGI Indicator'
		dataType: string
		lineageTag: 4f3cb79e-145b-4aa7-996f-bf4a5c974197
		sourceLineageTag: 21049ea4-11a0-4487-aa2f-bf05624ae34b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: GGI Indicator

		annotation SummarizationSetBy = Automatic

	column 'ML SD Class Desc'
		dataType: string
		lineageTag: 2d21c2ad-d9ed-4740-91ab-f0a9980bce42
		sourceLineageTag: c8181aca-a379-4533-9a43-1e8aaf72637b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML SD Class Desc

		annotation SummarizationSetBy = Automatic

	column 'Dg Issuer Cd'
		dataType: string
		lineageTag: 06d4dc12-821f-4540-a6d9-69a753cd7fcc
		sourceLineageTag: 8f7d6604-ef02-4684-8edf-2f704e306cd4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Dg Issuer Cd

		annotation SummarizationSetBy = Automatic

	column 'ML MFC Equivalent Eff Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: c9dfcf4e-bfff-43b4-a989-ea18ce58bb05
		sourceLineageTag: e508750f-c2ec-4460-86d5-1d8bcf445ca5
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML MFC Equivalent Eff Dt

		annotation SummarizationSetBy = Automatic

	column 'ML Mim Na Rating Eff Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 5929e302-d021-400b-85cd-238c8c2d6847
		sourceLineageTag: 938e2464-0d0a-494a-8e54-9414b973e0b9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Mim Na Rating Eff Dt

		annotation SummarizationSetBy = Automatic

	column 'ML Mim Asia Rating Eff Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 6ffbb1ec-e8e0-4996-b2ac-57bfa3e6f21d
		sourceLineageTag: 93724d86-c086-455d-98ee-ab087c05be12
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Mim Asia Rating Eff Dt

		annotation SummarizationSetBy = Automatic

	column 'ML Speq Rating'
		dataType: string
		lineageTag: 35dc390f-2743-478e-a5f4-4cbbcae3fe74
		sourceLineageTag: 6ea937f5-ae2d-4142-b0ff-49fc66d35086
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Speq Rating

		annotation SummarizationSetBy = Automatic

	column 'ML Speq Eff Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 37627351-56f0-42ba-a73d-490afaae21bc
		sourceLineageTag: f00a363c-94bf-45b3-8aa2-6d1930099b35
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Speq Eff Dt

		annotation SummarizationSetBy = Automatic

	column 'ML JH Rating Effective Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 1ddbb30a-cf73-495c-b2a2-caf0e69a21dc
		sourceLineageTag: cde7df24-fd14-46ef-82fb-2096414973fd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML JH Rating Effective Dt

		annotation SummarizationSetBy = Automatic

	column 'Japan Credit Rating Effective Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: d8ddbc38-503c-4337-9524-5f85a5245927
		sourceLineageTag: 26bc9aa7-5749-44c1-be70-1a4a5a9dd686
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Japan Credit Rating Effective Dt

		annotation SummarizationSetBy = Automatic

	column 'ML IRR Eff Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: ec7df79c-c307-47ab-b20e-767e327760d2
		sourceLineageTag: c37f33fc-953e-46de-b90c-85217a7dee6a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML IRR Eff Dt

		annotation SummarizationSetBy = Automatic

	column 'RI Rating Effective Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 95468403-e9d9-4fb5-bc3e-c08ae0f28d45
		sourceLineageTag: 54e4cf11-c6ed-4a13-91a6-478f936f75f4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: RI Rating Effective Dt

		annotation SummarizationSetBy = Automatic

	column 'ML SD Type Desc'
		dataType: string
		lineageTag: c80de268-4b39-4e27-b95b-0aa342eccd09
		sourceLineageTag: 4e4d4e30-d2e0-4f67-b06b-60accd25570b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML SD Type Desc

		annotation SummarizationSetBy = Automatic

	column 'ID Cins'
		dataType: string
		lineageTag: 049096a6-45e7-4089-a1bb-e4acd8a2fc09
		sourceLineageTag: d870952f-8440-4508-95e6-cd2f4ed8919b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ID Cins

		annotation SummarizationSetBy = Automatic

	column 'ML Capital Structure Cd'
		dataType: string
		lineageTag: 75671d35-c798-4298-8ea3-a1f321d0fb9a
		sourceLineageTag: 20153e8b-7fab-400f-81c7-cacb9258c4c7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Capital Structure Cd

		annotation SummarizationSetBy = Automatic

	column 'ML Capital Structure Desc'
		dataType: string
		lineageTag: 17be2029-6b94-4acc-947c-8b9b36a0616f
		sourceLineageTag: 95218bd5-ab13-4f1b-aa19-2a32ceb3c9b9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Capital Structure Desc

		annotation SummarizationSetBy = Automatic

	column 'ML Stat Collateral Type Cd'
		dataType: string
		lineageTag: ba97a3ab-1e53-464d-8a61-ce17ae604375
		sourceLineageTag: 16358a45-a9a2-4f2a-85b0-642002643616
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Stat Collateral Type Cd

		annotation SummarizationSetBy = Automatic

	column 'ML NAIC Report Part Cd'
		dataType: string
		lineageTag: cb530306-11a4-4dfc-a0fc-23c6c64d5601
		sourceLineageTag: ceddbbed-6ebb-47e7-b71e-6ad479d20011
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML NAIC Report Part Cd

		annotation SummarizationSetBy = Automatic

	column 'NAIC Designation'
		dataType: string
		lineageTag: e447ae30-efd7-4258-9f9a-be6504ecaeeb
		sourceLineageTag: e9fce774-bc98-4896-9559-f319c6fb9109
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: NAIC Designation

		annotation SummarizationSetBy = Automatic

	column 'NAIC Rating'
		dataType: int64
		formatString: 0
		lineageTag: de1b81ef-8f77-40a5-bc4b-a64a68badce6
		sourceLineageTag: 25131bd2-cdc5-4e14-ab23-e5869f73a4b8
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: NAIC Rating

		annotation SummarizationSetBy = Automatic

	column 'Analyst ID'
		dataType: string
		lineageTag: 6a9d013b-c3fc-4fba-b70e-bb9ce43b5072
		sourceLineageTag: fa6f4b99-1626-4924-9b09-351efde63b81
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Analyst ID

		annotation SummarizationSetBy = Automatic

	column 'Analyst Nm'
		dataType: string
		lineageTag: 6f29598c-7290-4c57-b832-e5c25df1e105
		sourceLineageTag: 17447f35-ed92-414b-a3da-ea53be6bddd3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Analyst Nm

		annotation SummarizationSetBy = Automatic

	column 'Analyst Role Cd'
		dataType: string
		lineageTag: ffcde0f3-dfcb-4a03-8484-cdd95802b974
		sourceLineageTag: ae4c29c4-7d32-4f0d-bc36-d106b10881ea
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Analyst Role Cd

		annotation SummarizationSetBy = Automatic

	column 'Primary Rating Effective Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: bd56eabb-ec86-4ba4-9077-3027fb683ca4
		sourceLineageTag: a92f99ec-a3fb-4ad1-afbd-9cddb9d5217d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Primary Rating Effective Dt

		annotation SummarizationSetBy = Automatic

	column 'ML NAIC Instrument Type Cd'
		dataType: string
		lineageTag: 1b3e7277-42c4-4d10-b530-3546c2a6430a
		sourceLineageTag: f9f4d490-0f75-4d27-b6c0-70546aad0fc9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML NAIC Instrument Type Cd

		annotation SummarizationSetBy = Automatic

	column 'ML SD Class Cd'
		dataType: string
		lineageTag: 9d296e7d-3653-4d55-b6ac-f087e5d74749
		sourceLineageTag: dacd9b1e-d8b0-4bab-967a-142dbacc8409
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML SD Class Cd

		annotation SummarizationSetBy = Automatic

	column 'ML SD Subclass Cd'
		dataType: string
		lineageTag: c81cfd33-e900-4cd3-b4e2-2f6fa92691f6
		sourceLineageTag: c0ffa7f3-5c09-47fc-8a75-f72283219079
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML SD Subclass Cd

		annotation SummarizationSetBy = Automatic

	column 'ML SD Type Cd'
		dataType: string
		lineageTag: 0519de04-2d6e-4458-91f6-5834d4e0e92b
		sourceLineageTag: 8231ae4c-502a-4577-a58a-88605e2b6f85
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML SD Type Cd

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID & Desc'
		dataType: string
		lineageTag: 88250bf2-a2ec-403b-8b72-4afe1a113950
		sourceLineageTag: ace9c8ae-25e0-463b-a093-79a090583889
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Primary Security ID & Desc

		annotation SummarizationSetBy = Automatic

	column 'Country Of Issue - NoBlank'
		dataType: string
		lineageTag: 169dca3b-e1db-491c-8816-40ab09eea340
		sourceLineageTag: 60b004f1-959f-49ed-9ed6-39dd5479fb32
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Country Of Issue - NoBlank

		annotation SummarizationSetBy = Automatic

	column 'Country - NoBlank'
		dataType: string
		lineageTag: ad4e5a23-2173-42ec-897c-e611ad01bbbb
		sourceLineageTag: 9700af55-180d-481e-ac65-5b75b2b983ec
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Country - NoBlank

		annotation SummarizationSetBy = Automatic

	column 'Public/Private Indicator'
		dataType: string
		lineageTag: 56e09db2-c308-4dbd-b0b0-33c04eddb921
		sourceLineageTag: e2ac4830-99d2-4588-acc8-dce491666271
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Public/Private Indicator

		annotation SummarizationSetBy = Automatic

	column 'As Of Period'
		dataType: int64
		formatString: 0
		lineageTag: 95d2442a-63c9-41b5-aef7-886580408408
		sourceLineageTag: ad49522b-b92b-4f04-b73d-dc6eb46b6cbd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: As Of Period

		annotation SummarizationSetBy = User

	column 'SCD Instrument Type'
		dataType: string
		lineageTag: 2572cf97-447e-454a-9431-67a7f0bf402b
		sourceLineageTag: 2c1044de-193e-421e-857e-b296484e61a8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Instrument Type

		annotation SummarizationSetBy = Automatic

	column 'SCD Latest Flag'
		dataType: string
		lineageTag: c911ddc4-4b0d-4926-8d94-aa33e47e7951
		sourceLineageTag: eabb732f-2352-44fd-a653-e0411edb8290
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Latest Flag

		annotation SummarizationSetBy = Automatic

	column 'RTG MDY Long Issue Level'
		dataType: string
		lineageTag: a33a8e07-153b-450a-b313-c7dc644e76fd
		sourceLineageTag: 3d990814-3ae4-4492-a69b-0129e1376a7a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: RTG MDY Long Issue Level

		annotation SummarizationSetBy = Automatic

	column 'RTG Fitch Long'
		dataType: string
		lineageTag: a89e1537-4d6c-4a7c-8468-e245ad4e0332
		sourceLineageTag: 5420038d-0594-4d9a-837f-a49ddae6fc37
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: RTG Fitch Long

		annotation SummarizationSetBy = Automatic

	column 'RTG MDY Issuer'
		dataType: string
		lineageTag: 2791e9aa-d987-4022-a1f2-ac1831056923
		sourceLineageTag: c53375bb-3da8-4d3a-b0ee-e38403895496
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: RTG MDY Issuer

		annotation SummarizationSetBy = Automatic

	column 'RTG S&P Long'
		dataType: string
		lineageTag: ea29687a-f279-4c33-add6-e8327adc9818
		sourceLineageTag: 72f1efb2-3faf-44b9-b72b-65b4eb2aa4d2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: RTG S&P Long

		annotation SummarizationSetBy = Automatic

	column 'Last Refix Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 61ef3e39-507c-4604-84d1-e02468c1cd1e
		sourceLineageTag: cbdea0cf-79ba-40b3-9a49-164c0e3d0810
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Last Refix Date

		annotation SummarizationSetBy = Automatic

	column 'SR Loan'
		dataType: string
		lineageTag: 6fa7a61f-a766-4290-9d80-71904962a516
		sourceLineageTag: 6619aa88-76cb-428c-b31a-a5f1b0ed7c24
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SR Loan

		annotation SummarizationSetBy = Automatic

	column 'Country of Incorporation'
		dataType: string
		lineageTag: 1398fd5f-845d-4bb1-89ad-7473ebd688fd
		sourceLineageTag: 4a21c21b-6cd0-4a07-8258-45552c02be10
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Country of Incorporation

		annotation SummarizationSetBy = Automatic

	column 'Primary Asset Type'
		dataType: string
		lineageTag: 9856cf94-92e4-412c-8dcb-11ef7867c0f6
		sourceLineageTag: 6ee75cdf-9f77-4730-a370-715a09ec2043
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Primary Asset Type

		annotation SummarizationSetBy = Automatic

	column 'NAIC Deposit Category'
		dataType: string
		lineageTag: 352ff2a4-2303-4e73-9384-a9c73f6a02c5
		sourceLineageTag: 39ba84aa-a838-46f9-b590-af47866cb992
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: NAIC Deposit Category

		annotation SummarizationSetBy = Automatic

	column 'Int Acc Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: a9d882b2-8699-4a7b-a431-13671bad6987
		sourceLineageTag: d3d5e9b7-9026-4f03-bb4f-fc666cc5c9df
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Int Acc Date

		annotation SummarizationSetBy = Automatic

	column 'State Code'
		dataType: string
		lineageTag: 258384db-89bc-4fb1-8a63-0f439d28b8ce
		sourceLineageTag: 0b81d1f2-a69f-4d08-aba2-d6583ab880f9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: State Code

		annotation SummarizationSetBy = Automatic

	column 'Final Maturity Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 8e0df395-1673-4c4f-94d6-32a162fc7b6b
		sourceLineageTag: 12e83ce2-4002-4707-8cec-e2cd882f279c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Final Maturity Date

		annotation SummarizationSetBy = Automatic

	column 'Ask Price'
		dataType: double
		lineageTag: aabef54c-3006-4cb1-9a3e-f0e4da6d0c55
		sourceLineageTag: a91c888a-4d94-412b-9549-e75631228961
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Ask Price

		annotation SummarizationSetBy = Automatic

	column 'Bid Price'
		dataType: double
		lineageTag: c57d0f0e-46db-46d8-a1d5-8cfeb717fec1
		sourceLineageTag: 8b3c3764-cb4d-4bb8-9696-c33ac6893a9a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Bid Price

		annotation SummarizationSetBy = Automatic

	column 'Mid Price'
		dataType: double
		lineageTag: 404350cc-bbc8-454b-9758-1d78072ea2b7
		sourceLineageTag: d4dcc90b-b155-4bfc-9160-013e5bb3f742
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Mid Price

		annotation SummarizationSetBy = Automatic

	column 'Ml Pricing Source'
		dataType: string
		lineageTag: c09595b2-b7e6-4de3-8c43-99ff0f1d36a1
		sourceLineageTag: f85af0e6-e916-4016-93bf-0f622a75e4d7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Ml Pricing Source

		annotation SummarizationSetBy = Automatic

	column 'Security Description - Restated'
		dataType: string
		isHidden
		lineageTag: 563a0ca0-2ad7-428b-96c3-f98173b7f630
		sourceLineageTag: 0eb02102-7346-4330-af7f-9c5ac4c0e290
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security Description - Restated

		annotation SummarizationSetBy = Automatic

	column 'Security ID 2 - Restated'
		dataType: string
		isHidden
		lineageTag: c8d4477f-ef4e-42f6-a6bd-98102f1e10e7
		sourceLineageTag: 846dd223-22ff-46fa-af1a-37eaac70a700
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security ID 2 - Restated

		annotation SummarizationSetBy = Automatic

	column 'Isin - Restated'
		dataType: string
		isHidden
		lineageTag: 1349a58a-cb62-4b06-99d0-2f599876f4da
		sourceLineageTag: a0eaaf77-4146-4949-95cf-4de51475a25d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Isin - Restated

		annotation SummarizationSetBy = Automatic

	column 'Sedol - Restated'
		dataType: string
		isHidden
		lineageTag: 7c6a3a2d-422d-4bc6-9d12-73df63a200c7
		sourceLineageTag: a077db62-6c75-449d-9018-3de08a4b38a7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Sedol - Restated

		annotation SummarizationSetBy = Automatic

	column 'Ticker - Restated'
		dataType: string
		isHidden
		lineageTag: cbeac999-1857-4b93-8685-e4da431ef5dd
		sourceLineageTag: cf7afece-f1d4-4428-9f3c-56d4f21b5474
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Ticker - Restated

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID - Restated'
		dataType: string
		isHidden
		lineageTag: f591d1f9-7c72-48f1-b252-419305196483
		sourceLineageTag: b71810dd-1201-4486-bca6-77296892b8e8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Primary Security ID - Restated

		annotation SummarizationSetBy = Automatic

	column 'SCD Security ID - Restated'
		dataType: string
		isHidden
		lineageTag: 2db0ea49-0dda-4884-a414-44b159adacf3
		sourceLineageTag: 7f9703e1-084c-4a72-8e7e-b5f59685a03e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Security ID - Restated

		annotation SummarizationSetBy = Automatic

	column 'Cusip - Restated'
		dataType: string
		isHidden
		lineageTag: 3b376cda-bc8d-4fb1-8dde-3f5d8e5554a6
		sourceLineageTag: 52f57547-32af-4d67-94df-ba44600be7dc
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Cusip - Restated

		annotation SummarizationSetBy = Automatic

	column 'Official PPN - Restated'
		dataType: string
		isHidden
		lineageTag: 6b2dd099-b0c8-418b-8cef-cf3c7d7010fe
		sourceLineageTag: 71de06e5-cbfb-4e30-a475-1df63a63e2b0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Official PPN - Restated

		annotation SummarizationSetBy = Automatic

	column 'ML Private Asset ID - Restated'
		dataType: string
		isHidden
		lineageTag: 58e0ae43-a77c-4dfb-88a5-c0006a39612e
		sourceLineageTag: 1dbcf4c8-a7b9-4c2e-a007-be996ebb2f27
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Private Asset ID - Restated

		annotation SummarizationSetBy = Automatic

	column 'SecurityID Slicer - Restated'
		dataType: string
		lineageTag: c6b74fe8-394b-472b-a9b3-74be2496f94a
		sourceLineageTag: 46e5874c-0fea-418a-8f62-a72ae60eef6d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SecurityID Slicer - Restated

		annotation SummarizationSetBy = Automatic

	column 'ID BB Global - Restated'
		dataType: string
		isHidden
		lineageTag: d639b0e0-f393-4ddc-a06c-26f903e0b23e
		sourceLineageTag: 62e34c0c-4382-465b-bfa9-01b5333e1bc1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ID BB Global - Restated

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Sector Name (Private Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: 29533925-c46e-4d81-b1b7-f7e200cc0c8e
		sourceLineageTag: 38b733ba-e388-4d49-acca-16fc836479dd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Industry Sector Name (Private Sec)

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Group Name (Private Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: 7f912012-17c1-4a51-b3f6-883515e13a75
		sourceLineageTag: 922275b7-75bc-4761-a981-07020e69c6a7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Industry Group Name (Private Sec)

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Subgroup Name (Private Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: 950c0331-b82a-48f5-8fd6-e5b0a26448c0
		sourceLineageTag: 633827c0-e010-4640-bc9b-1eb0adf4cca4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Industry Subgroup Name (Private Sec)

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Sector Name (Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: 9fc17ddd-a5ee-4364-9e6f-d6b4c35ee2dc
		sourceLineageTag: 38fc5344-ae6f-4be3-a0ea-c920e70cd7b2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Industry Sector Name (Sec)

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Group Name (Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: ca444eb6-c651-47cb-a96e-d1fa2e4cb2fe
		sourceLineageTag: 03377b3f-14e4-43a0-8d3b-e1d4d53e439e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Industry Group Name (Sec)

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Subgroup Name (Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: 5aadd791-61d1-4af2-9291-835f63607030
		sourceLineageTag: efce9913-e209-4320-8094-2d7e114f6e81
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Industry Subgroup Name (Sec)

		annotation SummarizationSetBy = Automatic

	column 'MRM Sector Name (Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: a85cee11-bf73-4f27-8071-fddaf88325b0
		sourceLineageTag: bd1af01e-fc55-4983-9cb0-d72bccc36c58
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Sector Name (Sec)

		annotation SummarizationSetBy = Automatic

	column 'MRM Sector Name'
		dataType: string
		displayFolder: MRM Fields
		lineageTag: 227d0514-6f49-4b56-aa29-9fc313e30fed
		sourceLineageTag: ccd1301f-643b-4481-b5ce-e16f6b0eb62f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Sector Name

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Sector Name'
		dataType: string
		displayFolder: MRM Fields
		lineageTag: 270e260a-52e6-41fa-8c13-c82d711fd32b
		sourceLineageTag: f0774273-5a62-43a7-a53c-bd9196ca9ba2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Industry Sector Name

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Group Name'
		dataType: string
		displayFolder: MRM Fields
		lineageTag: 82b9e173-c14a-46ec-a156-19fff044932a
		sourceLineageTag: 2c7a9c62-feb1-4f63-b264-2812135cee49
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Industry Group Name

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Subgroup Name'
		dataType: string
		displayFolder: MRM Fields
		lineageTag: 3dfff576-d437-4683-b5fa-f51704a4b503
		sourceLineageTag: d335d504-c3b8-479b-b3a5-56d3c99601a5
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Industry Subgroup Name

		annotation SummarizationSetBy = Automatic

	column 'Step-down Floater Ind'
		dataType: string
		lineageTag: eeb2f60b-6456-40d9-917a-d2abfa01c226
		sourceLineageTag: e157ad39-456c-49ce-b44f-100aaf84bbd7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Step-down Floater Ind

		annotation SummarizationSetBy = Automatic

	column 'Step-up Floater Ind'
		dataType: string
		lineageTag: 03c8b2ec-bfe3-435c-96ad-957d555c0b3f
		sourceLineageTag: dc6f81c8-7948-4c6e-bc1f-c238c91df723
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Step-up Floater Ind

		annotation SummarizationSetBy = Automatic

	column 'Income Rate Ind'
		dataType: string
		lineageTag: ea085baf-4d28-4d9d-b852-4e5b50e747ee
		sourceLineageTag: 6ba7345c-175e-44de-99fc-2fc09b291281
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Income Rate Ind

		annotation SummarizationSetBy = Automatic

	column 'Float Not Var Ind'
		dataType: string
		lineageTag: 2618aecb-06a5-4fbe-83ca-5417b62e2560
		sourceLineageTag: 8245a1b8-c45d-426d-a7ba-c247b0c78d76
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Float Not Var Ind

		annotation SummarizationSetBy = Automatic

	column 'Accrue In Default Ind'
		dataType: string
		lineageTag: 91daff78-ce03-4e32-8a4e-99fa7b0b0061
		sourceLineageTag: 692ef2b0-b9c7-430b-8ca6-9a320aa3cf6d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Accrue In Default Ind

		annotation SummarizationSetBy = Automatic

	column 'Pre Payment Risk'
		dataType: string
		lineageTag: 6375f938-1982-4ae3-a321-02c65eec1cfb
		sourceLineageTag: c90d2726-5474-42aa-95bd-40fde15a5bdf
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Pre Payment Risk

		annotation SummarizationSetBy = Automatic

	column 'Next Refix Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: abfc7d24-d8c8-4c22-8fd3-c4c3a691d52f
		sourceLineageTag: 47302b8d-4581-4e3e-8fe7-499aa13a009d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Next Refix Date

		annotation SummarizationSetBy = Automatic

	column 'First Coupon Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 761bd118-ca35-43cb-8663-18bec3a13aad
		sourceLineageTag: 5dbe1d2e-1b71-42ef-9327-e0fb0b3c4fd2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: First Coupon Date

		annotation SummarizationSetBy = Automatic

	column 'Default Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 3f4b6464-6260-480d-b8c5-8b6837d0b844
		sourceLineageTag: 7bf902d2-48e8-424f-8d71-135a9a65bd99
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Default Date

		annotation SummarizationSetBy = Automatic

	column 'Sink Fund PRN'
		dataType: double
		lineageTag: 9d260114-a64b-44e6-9ac9-4772f6534a22
		sourceLineageTag: 48d4174b-a464-4b13-b352-18adc7dcfdab
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Sink Fund PRN

		annotation SummarizationSetBy = Automatic

	column 'Coupon Floor'
		dataType: double
		lineageTag: 36d1ffac-3c27-45db-8729-fac7e2ddf653
		sourceLineageTag: 59faa012-8dea-4c3d-9264-a727398144bc
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Coupon Floor

		annotation SummarizationSetBy = Automatic

	column 'Coupon Cap'
		dataType: double
		lineageTag: bbaccf0c-a806-494c-87cd-6c8fb79ca13f
		sourceLineageTag: 5e93b21e-e4db-44de-a949-726008d444bd
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Coupon Cap

		annotation SummarizationSetBy = Automatic

	column 'Is PublicPP Ind'
		dataType: string
		lineageTag: 4c9da5a9-8822-4ac7-b7f0-794d7fa1c471
		sourceLineageTag: ed7adff9-1876-47f9-be57-5918201d43f8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Is PublicPP Ind

		annotation SummarizationSetBy = Automatic

	column 'Mxms Id'
		dataType: string
		lineageTag: 72dccc3c-fc00-43a6-8632-205b922b396c
		sourceLineageTag: e1d94d86-e784-4e6e-8341-b165d906be55
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Mxms Id

		annotation SummarizationSetBy = Automatic

	column 'SCD Deposit Rate'
		dataType: double
		lineageTag: 92c7107e-659c-475d-85b6-f79a3046f3f7
		sourceLineageTag: f8701b63-9490-479c-b830-0b9ae9b5046b
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: SCD Deposit Rate

		annotation SummarizationSetBy = Automatic

	column 'Reset Freq Description'
		dataType: string
		lineageTag: 18ec066e-0718-4642-8fce-7bae3b865b63
		sourceLineageTag: 694fcf9f-440c-411c-9ed7-67b7bdee2cf1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Reset Freq Description

		annotation SummarizationSetBy = Automatic

	column 'Latest As of Dt'
		dataType: string
		lineageTag: fb5a27b7-e5bd-43d9-be7a-32c81a88920a
		sourceLineageTag: 26a267ac-2cf1-49de-8ef6-974d8638e32d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Latest As of Dt

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID & Desc - Never Use'
		dataType: string
		isHidden
		lineageTag: 992087ac-82cc-4876-b3d5-6d0d0c18c64b
		sourceLineageTag: efde13c3-a4d8-47c7-9392-769d9f92372a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Primary Security ID & Desc - Never Use
		sortByColumn: 'As Of Dt'

		annotation SummarizationSetBy = Automatic

	column 'Wash Sale Parent Security Id'
		dataType: string
		lineageTag: be1d135e-476f-4dcf-b60a-79dba916ebf7
		sourceLineageTag: 0ac88fbc-78ba-4e45-af51-87798df0ef75
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Wash Sale Parent Security Id

		annotation SummarizationSetBy = Automatic

	column 'ML LICAT Inferred Rating ORG'
		dataType: string
		lineageTag: 9f574e8b-1100-4040-9174-41a27aef078b
		sourceLineageTag: 228f0f03-2613-41ba-b07b-8cc36fa9970f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML LICAT Inferred Rating ORG

		annotation SummarizationSetBy = Automatic

	column 'Scd Private Placement Indicator'
		dataType: string
		lineageTag: e8f5be93-46fe-464e-b5e8-6c9613b0532f
		sourceLineageTag: 12976378-01bc-4367-bc50-d9f1cd42303c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Scd Private Placement Indicator

		annotation SummarizationSetBy = Automatic

	column 'Actual S&P'
		dataType: string
		lineageTag: 602b9ab0-f07e-4c88-800c-1ad096b232d0
		sourceLineageTag: 609192a7-0653-4671-b8c0-c15cc8d5783d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Actual S&P

		annotation SummarizationSetBy = Automatic

	column 'Country of Issue - Long'
		dataType: string
		lineageTag: b1d96352-134d-4cd6-a886-e78441f89c81
		sourceLineageTag: e5ff7ff8-c1c2-4d53-b1a4-f052ed2fc63e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Country of Issue - Long

		annotation SummarizationSetBy = Automatic

	column 'Country of Issue - Short'
		dataType: string
		lineageTag: 657fb15f-50cc-4bde-85f7-f7ce5dbe5495
		sourceLineageTag: 071044d1-e97a-4b1b-af6f-58617eaf47cd
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Country of Issue - Short

		annotation SummarizationSetBy = Automatic

	column 'Issuer Country Cd'
		dataType: string
		lineageTag: 18a5bcd4-1a28-49c1-820b-4b3ddde83bf1
		sourceLineageTag: 1cfb66ab-99a3-46b9-b28e-3c82738153fe
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Issuer Country Cd

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID Type'
		dataType: string
		lineageTag: 323b34cb-652d-4ac2-ae8a-a0d72d805b3f
		sourceLineageTag: 942578e0-9a22-4e78-96e1-ac6bdd78059c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Primary Security ID Type

		annotation SummarizationSetBy = Automatic

	column 'Internal Sec Id Type'
		dataType: string
		lineageTag: 41d22e13-578d-4e1b-9107-831ac7d7f5e5
		sourceLineageTag: a26492a0-a154-4352-b644-90752f83a252
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Internal Sec Id Type

		annotation SummarizationSetBy = Automatic

	column 'ML Review CAT CD'
		dataType: string
		lineageTag: a72c7fcb-af3d-46e8-991a-6c3089e5fee2
		sourceLineageTag: 3b94f499-245e-42d8-a5f2-6c287893369c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Review CAT CD

		annotation SummarizationSetBy = Automatic

	column 'ML Issue Txt'
		dataType: string
		lineageTag: de66cf9a-1573-4701-89b8-7de596b5b19f
		sourceLineageTag: badc4736-9636-41cd-b79f-3c58d7f9731a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML Issue Txt

		annotation SummarizationSetBy = Automatic

	column 'ML IRR Rating (Adj)'
		dataType: string
		lineageTag: e1ea4b46-f1a5-4184-bf74-b01745c1dfde
		sourceLineageTag: 9b6761e5-ede2-4cc2-a0a8-04e4219735e9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML IRR Rating (Adj)

		annotation SummarizationSetBy = Automatic

	column 'ML MFC Equivalent Rtg'
		dataType: string
		lineageTag: 2faa7a45-7c4f-40a0-91f8-c86cfe580671
		sourceLineageTag: b405fd62-5ac6-4aea-ac10-a52cfaeba04b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML MFC Equivalent Rtg

		annotation SummarizationSetBy = Automatic

	column 'Private Placement (Adj)'
		dataType: string
		lineageTag: 063449d5-3552-413a-9ee9-3723a5d2b22d
		sourceLineageTag: 443d90b0-455f-4aab-895a-f6c1100d792d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Private Placement (Adj)

		annotation SummarizationSetBy = Automatic

	column 'ML LICAT Inferred Rating'
		dataType: string
		lineageTag: b692269b-7a87-4702-8a12-ac04a8f27a66
		sourceLineageTag: 16c1b665-c7b9-4b6f-9c22-6705528ba9b6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ML LICAT Inferred Rating

		annotation SummarizationSetBy = Automatic

	column 'Endorsement Indicator'
		dataType: string
		lineageTag: 60267f11-676d-4b6a-a609-ca8bb65ad724
		sourceLineageTag: 2cd6c299-3776-41cf-9089-9d924ac4ecf8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Endorsement Indicator

		annotation SummarizationSetBy = Automatic

	column 'Legal Structure Cd'
		dataType: string
		lineageTag: ddf1c5f2-cab0-48b5-b8ed-fdc23174f890
		sourceLineageTag: b2db8b36-dca2-4bba-8e49-b5851bc8b9b5
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Legal Structure Cd

		annotation SummarizationSetBy = Automatic

	column 'Gics Sector Cd'
		dataType: string
		lineageTag: 6f029892-13c8-4e21-b5f0-3fdf0b8cfe75
		sourceLineageTag: afd06abc-5dc4-44db-8954-269da7aa0902
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Gics Sector Cd

		annotation SummarizationSetBy = Automatic

	column 'Gics Industry Cd'
		dataType: string
		lineageTag: 23666223-7843-4870-8184-c959c5a3a537
		sourceLineageTag: adafddef-6602-49ac-8156-98449aa64c0c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Gics Industry Cd

		annotation SummarizationSetBy = Automatic

	column 'Gics Sub Industry Cd'
		dataType: string
		lineageTag: ead57a19-be35-45ce-adf8-6b0412d366b9
		sourceLineageTag: 0a28ad66-5bfc-4cc2-b6fc-8927bb71c179
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Gics Sub Industry Cd

		annotation SummarizationSetBy = Automatic

	column 'Gics Industry Group Cd'
		dataType: string
		lineageTag: f9fdea41-8f8a-41fc-822e-91f82f86e2e6
		sourceLineageTag: 017ea77a-3df7-4132-9add-58bd181f4649
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Gics Industry Group Cd

		annotation SummarizationSetBy = Automatic

	column 'Opt Put Call'
		dataType: string
		lineageTag: 6035756a-09a3-48f2-86ee-9d029a06a1d5
		sourceLineageTag: f856d0f6-69a6-484e-91fc-43246a01a776
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Opt Put Call

		annotation SummarizationSetBy = Automatic

	column 'Eqy Sic Cd'
		dataType: string
		lineageTag: 2a4996ad-0a72-42c0-a90d-d74ef9bbcbdc
		sourceLineageTag: 694f6010-5f84-4ac6-b875-b6cee3699daf
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Eqy Sic Cd

		annotation SummarizationSetBy = Automatic

	column 'Entity Join Key'
		dataType: string
		lineageTag: c67c598e-dc09-461f-b54e-b39af80566de
		sourceLineageTag: be434b08-0dd5-4f7c-ad2b-8aa88e6d598d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Entity Join Key

		annotation SummarizationSetBy = Automatic

	column 'SCD MTG EXP Maturity Dt'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 051cad88-221f-4c7b-977b-53359b51ac9b
		sourceLineageTag: a7eb1e90-f2c5-43f3-8fa4-2b6d8bc8307e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD MTG EXP Maturity Dt

		annotation SummarizationSetBy = User

	column 'Eqy Sic Name'
		dataType: string
		lineageTag: 69d2dd42-5385-4616-8b14-6ffd391962f7
		sourceLineageTag: b7552b42-2885-468e-8804-2473c04d82ff
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Eqy Sic Name

		annotation SummarizationSetBy = User

	column 'NAIC Designation Modifier'
		dataType: string
		lineageTag: 82614bc7-7852-410b-96bd-85e72e264526
		sourceLineageTag: d976ef6a-b51a-47ea-ba7c-61e03187f638
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: NAIC Designation Modifier

		annotation SummarizationSetBy = User

	column 'SCD Svo Suffix'
		dataType: string
		lineageTag: 3b7a94d6-7696-4fd5-b2e5-3b3aa35abd3a
		sourceLineageTag: c48fad69-1fce-4a70-a649-7c1ea6c18423
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Svo Suffix

		annotation SummarizationSetBy = User

	column 'Issue px'
		dataType: string
		lineageTag: e8d54ea0-2247-4d74-9c47-9cd99ad7246e
		sourceLineageTag: f18184bf-70ba-4181-8cfa-ca95ed8a2438
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Issue px

		annotation SummarizationSetBy = User

	column 'First settle dt'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3486cdf2-6b9e-4022-a77e-d9ac6991d665
		sourceLineageTag: 7dc55c2b-aa77-4afc-8769-b9f606f51fa4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: First settle dt

		annotation SummarizationSetBy = User

	column 'Start acc dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: 1c5bbd18-ee77-450b-a984-52304d348f25
		sourceLineageTag: f402a43f-1881-4cf6-85c6-4f0fb65dc9ed
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Start acc dt

		annotation SummarizationSetBy = User

	column 'Exch code'
		dataType: string
		lineageTag: 7873432a-c89c-40dc-b246-64ab939db47d
		sourceLineageTag: 1e03b075-d4c3-4fb0-9b54-110db04463f5
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Exch code

		annotation SummarizationSetBy = User

	column 'Id mic1'
		dataType: string
		lineageTag: 7153dd71-973f-4bf2-80d7-15ca82640719
		sourceLineageTag: 5312e791-d09a-446a-b6b1-27430b1b1bcb
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Id mic1

		annotation SummarizationSetBy = User

	column 'MTG start acc dt set dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: f3177965-c39e-4279-ab4f-2cbb382d2dfd
		sourceLineageTag: 00c87ed5-665c-412e-b9c4-d0ec4c2b6f5e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MTG start acc dt set dt

		annotation SummarizationSetBy = User

	column 'Make Whole Call Spread Num'
		dataType: double
		lineageTag: bf88989d-4483-4cba-b7a0-a177ccf1e6b6
		sourceLineageTag: 6261ffac-7f39-4a1e-ad0a-53957fff7ea9
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Make Whole Call Spread Num

		annotation SummarizationSetBy = User

	column 'Make Whole Termination Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: ea65e442-0ca9-434e-9558-f976f48d01b4
		sourceLineageTag: 3f13e851-eb1b-4324-8fce-210f58aa3afc
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Make Whole Termination Dt

		annotation SummarizationSetBy = User

	column 'Payment Method Name'
		dataType: string
		lineageTag: c7b5b334-e703-4f0e-81b4-7c10a5d016b0
		sourceLineageTag: fdc0e969-3e48-4e9c-a6c1-3069a0401ea0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Payment Method Name

		annotation SummarizationSetBy = User

	column 'MRM Issuer Name'
		dataType: string
		lineageTag: 6ca29f4f-db44-4753-be3b-4dc7633213ae
		sourceLineageTag: b42d3928-f34f-41c9-adb0-8fc08008d127
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Issuer Name

		annotation SummarizationSetBy = User

	column 'MRM Issuer Country Name'
		dataType: string
		lineageTag: 1df02d31-3946-4628-9e8e-3805883f755a
		sourceLineageTag: 7ec98a3b-f352-4582-b602-2e484e0dc322
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Issuer Country Name

		annotation SummarizationSetBy = User

	column 'MRM Issuer Irr Rating Cd'
		dataType: string
		lineageTag: 0ccb1c5f-f77b-4fc2-b850-9cdb701a20ab
		sourceLineageTag: 8674969f-37ed-4d61-a84e-3a92b7038b5f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Issuer Irr Rating Cd

		annotation SummarizationSetBy = User

	column 'MRM Issuer Parent Name'
		dataType: string
		lineageTag: 2079e190-9328-4e26-a923-afba0705c8d5
		sourceLineageTag: 2da081aa-b8ff-4fb7-a25f-35cc7b47be8d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Issuer Parent Name

		annotation SummarizationSetBy = User

	column 'MRM Issuer Parent Country Name'
		dataType: string
		lineageTag: 081e429f-9f09-4e51-b811-95c3dda5aa48
		sourceLineageTag: 59f772f7-b09d-4ae7-8f14-e5683c2b3066
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Issuer Parent Country Name

		annotation SummarizationSetBy = User

	column 'MRM Issuer Parent Irr Rating Cd'
		dataType: string
		lineageTag: 7736a4f1-6cfc-4e6e-a800-4bb44c378591
		sourceLineageTag: f72a4a83-b99e-4546-ae09-05203697c0aa
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Issuer Parent Irr Rating Cd

		annotation SummarizationSetBy = User

	column 'MRM Issuer Ultparent Name'
		dataType: string
		lineageTag: 1c24b842-7f2f-4f8a-bf43-61cb44cb0a5b
		sourceLineageTag: f4e0eaab-1e4f-4751-a2a1-9e7b7b59e188
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Issuer Ultparent Name

		annotation SummarizationSetBy = User

	column 'MRM Issuer Ultparent Country Name'
		dataType: string
		lineageTag: 508e6a2e-18da-4d47-8b75-218f9d91daeb
		sourceLineageTag: 9b452a1f-af2d-451c-8ee3-4cea49c00bef
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Issuer Ultparent Country Name

		annotation SummarizationSetBy = User

	column 'MRM Issuer Ultparent Irr Rating Cd'
		dataType: string
		lineageTag: b6a561ca-ebf5-4108-8277-117c8035727a
		sourceLineageTag: f20c0128-3a9f-4578-bc00-f9d60f57db9b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Issuer Ultparent Irr Rating Cd

		annotation SummarizationSetBy = User

	column 'Equity Fund Ind'
		dataType: string
		lineageTag: 5372c56d-ed86-4f29-821e-33cc9041226c
		sourceLineageTag: ed734371-47d9-463a-9243-e5fb817136ac
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Equity Fund Ind

		annotation SummarizationSetBy = User

	column 'GCLMS Collateral Quality Cd'
		dataType: string
		lineageTag: cbff594e-b180-4bc4-aa2f-2c4bb3438e1e
		sourceLineageTag: 937f8583-ec2f-4557-893d-6b7a7a04ac86
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: GCLMS Collateral Quality Cd

		annotation SummarizationSetBy = User

	column 'MRM Issuer Cascade Rating Cd'
		dataType: string
		lineageTag: ddceb8ad-c7e7-468e-b963-e27535c17288
		sourceLineageTag: 6806fb48-322c-4358-b82f-14a05f9dc503
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Issuer Cascade Rating Cd

		annotation SummarizationSetBy = User

	column 'MRM Issuer Parent Cascade Rating Cd'
		dataType: string
		lineageTag: 9ecc11cb-d575-4ef5-8428-be7fc9b11a00
		sourceLineageTag: 7f7abfe5-0bc9-4b3b-a805-40b76b870a63
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Issuer Parent Cascade Rating Cd

		annotation SummarizationSetBy = User

	column 'MRM Issuer Ultparent Cascade Rating Cd'
		dataType: string
		lineageTag: df4a5bca-f08c-42b4-9baa-33a7cee4bd56
		sourceLineageTag: 8f143af0-643c-4521-9676-c05a500f4aa6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: MRM Issuer Ultparent Cascade Rating Cd

		annotation SummarizationSetBy = User

	column 'Cur Cpn'
		dataType: double
		lineageTag: 1619cdf7-30c6-495b-b8ae-6c0c00c96996
		sourceLineageTag: 40a44894-8316-43df-a4d6-b81c9b3cfbff
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Cur Cpn

		annotation SummarizationSetBy = User

	column 'GCLMS Issuer Parent Cascade Rtg Cd'
		dataType: string
		lineageTag: b53cc956-0d17-4b3a-b304-e6eb69ab8140
		sourceLineageTag: 9b13d087-b32b-4d7f-9129-c3d2a15b2c02
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: GCLMS Issuer Parent Cascade Rtg Cd

		annotation SummarizationSetBy = User

	column 'Guarantor Name'
		dataType: string
		lineageTag: b4e3f606-76da-40b1-ab50-abf0a1c749ca
		sourceLineageTag: b00656d2-d1fd-404b-a2b1-4ebf2cc5167e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Guarantor Name

		annotation SummarizationSetBy = User

	column 'Capital Structure Name'
		dataType: string
		lineageTag: f0ee81e4-91bf-43c5-9841-ad1f4b9414b9
		sourceLineageTag: 3c8e1b6c-5aad-465a-a572-d90ab54677e0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Capital Structure Name

		annotation SummarizationSetBy = User

	column 'Alt Fee Asset Name'
		dataType: string
		lineageTag: 478671b6-2d07-4c18-8753-6a9847d6710d
		sourceLineageTag: fd9fb985-5a6a-46ba-914f-4ce9767e84ef
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Alt Fee Asset Name

		annotation SummarizationSetBy = User

	column 'Multi Cpn Schedule Typ'
		dataType: int64
		formatString: 0
		lineageTag: 4ddbc4c7-caa9-4b70-bd76-cb493d8c398a
		sourceLineageTag: 972aee69-f6bc-4172-bdac-decc87871d10
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Multi Cpn Schedule Typ

		annotation SummarizationSetBy = User

	partition Securities-f1d2496c-4072-46d6-8919-8b7c1323f98f = entity
		mode: directQuery
		source
			entityName: Securities
			expressionSource: 'DirectQuery to AS - Securities'

