table 'Securities Sublot Fact'
	lineageTag: 31c370e9-3658-448a-834f-32aeb54aec11
	sourceLineageTag: 14d7f8dc-6853-439f-8d36-a256e695cbd9

	measure 'Balanced Amortized AOCI - Local' = EXTERNALMEASURE("Balanced Amortized AOCI - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 07f6d361-3063-4f1a-9102-74bb8f7f105f
		sourceLineageTag: 9159c207-cfb8-4b1b-a880-0959f9f24e91
		dataCategory: Uncategorized

	measure 'Balance Remaining AOCI - Local' = EXTERNALMEASURE("Balance Remaining AOCI - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 8d0f8cbc-3a74-4289-8fd0-dab084bd49e2
		sourceLineageTag: 2e758712-549b-42d1-bc1c-fc7127c67f58
		dataCategory: Uncategorized

	measure 'Reporting Currency (Sublot)' = EXTERNALMEASURE("Reporting Currency (Sublot)", STRING, "DirectQuery to AS - Securities")
		lineageTag: 419f125c-3b90-45bb-8b1d-cd538b15fbe9
		sourceLineageTag: 4ed43c4f-5074-4a2a-a014-89b1ff74503f
		dataCategory: Uncategorized

	measure 'Balance Remaining AOCI - Rep' = EXTERNALMEASURE("Balance Remaining AOCI - Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 7a48a70c-d8b8-44e6-94bd-17726f4ea736
		sourceLineageTag: 0ffcae09-1bcb-471f-8329-2880595b93f5
		dataCategory: Uncategorized

	measure 'Balanced Amortized AOCI - Rep' = EXTERNALMEASURE("Balanced Amortized AOCI - Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: d8da894d-d5e4-44d3-8587-d6f3e715ae2f
		sourceLineageTag: 9e17710a-548d-4fca-be1d-9487bfa526ce
		dataCategory: Uncategorized

	measure 'Balance Original AOCI - Rep' = EXTERNALMEASURE("Balance Original AOCI - Rep", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 990c6d29-2059-4be9-9dbe-fbd476d0aafa
		sourceLineageTag: 9eacafd7-de0a-4bac-a3d8-e6c09241ae2a
		dataCategory: Uncategorized

	measure 'Balance Original AOCI - Local' = EXTERNALMEASURE("Balance Original AOCI - Local", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 4b82e582-6b72-4169-9ee0-e2118daf1492
		sourceLineageTag: be7d6af4-3846-410c-851b-121c910421e6
		dataCategory: Uncategorized

	measure 'AOCI Hedge Par' = EXTERNALMEASURE("AOCI Hedge Par", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: ca338427-94f4-4fe1-b2ae-7d683d7b1a5a
		sourceLineageTag: aeff63cb-d819-4295-9914-dba8e2da3e92
		dataCategory: Uncategorized

	measure 'Sublot Hedges Positions Title' = EXTERNALMEASURE("Sublot Hedges Positions Title", STRING, "DirectQuery to AS - Securities")
		lineageTag: 48f20bfb-da8a-4f9d-9dfe-0e6cc0b6eeea
		sourceLineageTag: 172331a2-2852-4516-99be-af1a9aa55489
		dataCategory: Uncategorized

	measure 'Non Zero Filter(Sublot Hedge)' = EXTERNALMEASURE("Non Zero Filter(Sublot Hedge)", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		isHidden
		lineageTag: 26717c2f-827a-455a-8f32-534be2d89417
		sourceLineageTag: 178863c4-7a1d-460c-85ec-ec19fd7654e0
		dataCategory: Uncategorized

	measure 'AOCI Book Yield' = EXTERNALMEASURE("AOCI Book Yield", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 8ef5f19c-b3e8-4b08-b8e7-7695beaa4370
		sourceLineageTag: 9286ee63-b3a6-4b07-88eb-4c24da0b74ad
		dataCategory: Uncategorized

	measure 'AOCI Amortized - Local (SPH)' = EXTERNALMEASURE("AOCI Amortized - Local (SPH)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Sublot Rollforward Attributes
		lineageTag: 0e3e3f72-d2c0-4195-8a34-d6bdb24a460c
		sourceLineageTag: 5ad299e8-6091-42b7-8358-510833558756
		dataCategory: Uncategorized

	measure 'AOCI Amortized - Rep (SPH)' = EXTERNALMEASURE("AOCI Amortized - Rep (SPH)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Sublot Rollforward Attributes
		lineageTag: 6925001b-60fd-4a2c-81ba-26fac052c5f5
		sourceLineageTag: 9feb3c02-4e36-4eda-8294-7d3c1d4eb8cb
		dataCategory: Uncategorized

	measure 'AOCI Original - Rep (SPH)' = EXTERNALMEASURE("AOCI Original - Rep (SPH)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Sublot Rollforward Attributes
		lineageTag: 4b0e5bf2-0580-4aea-bcd7-3eed3065bbb5
		sourceLineageTag: 47929781-a697-4c4f-b0fe-bf70fa10fb19
		dataCategory: Uncategorized

	measure 'AOCI Original - Local (SPH)' = EXTERNALMEASURE("AOCI Original - Local (SPH)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Sublot Rollforward Attributes
		lineageTag: db72389b-f064-416d-856c-782f80510fd3
		sourceLineageTag: 1427c19f-36aa-4464-9761-8630e05a0297
		dataCategory: Uncategorized

	measure 'AOCI Remaining - Rep (SPH)' = EXTERNALMEASURE("AOCI Remaining - Rep (SPH)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Sublot Rollforward Attributes
		lineageTag: e2febb1e-20f6-4c19-96da-efff0db37005
		sourceLineageTag: f7aad67f-2f83-493c-806a-ddecd143f8a5
		dataCategory: Uncategorized

	measure 'AOCI Remaining - Local (SPH)' = EXTERNALMEASURE("AOCI Remaining - Local (SPH)", DOUBLE, "DirectQuery to AS - Securities")
		displayFolder: Sublot Rollforward Attributes
		lineageTag: 25d688a1-dc2c-4f4e-95d6-7ef65eca6b6e
		sourceLineageTag: cfb249c8-5e7e-4799-94cb-5137d4b6ecb9
		dataCategory: Uncategorized

	measure 'Sublot Position History Title' = EXTERNALMEASURE("Sublot Position History Title", STRING, "DirectQuery to AS - Securities")
		displayFolder: Sublot Rollforward Attributes
		lineageTag: ee5b4f59-20cc-4ead-a41e-383da220534e
		sourceLineageTag: e152f348-f967-405d-a832-d71a416998be
		dataCategory: Uncategorized

	measure 'AOCI Hedge Findur ID Sublot (SPH)' = EXTERNALMEASURE("AOCI Hedge Findur ID Sublot (SPH)", INTEGER, "DirectQuery to AS - Securities")
		formatString: 0
		displayFolder: Sublot Rollforward Attributes
		lineageTag: c8323059-5d74-44e1-8218-1eaeb7dbf218
		sourceLineageTag: f5b1275e-a038-46fa-a704-38eb179bc72c
		dataCategory: Uncategorized

	measure 'Rep Rate (Sec Sublot)' = EXTERNALMEASURE("Rep Rate (Sec Sublot)", DOUBLE, "DirectQuery to AS - Securities")
		formatString: 0.000000
		lineageTag: cdf02720-6978-43da-904c-d5bc92ee2e76
		sourceLineageTag: 3d157f31-362c-4754-967d-d8689c48587f
		dataCategory: Uncategorized

	column 'Security NK'
		dataType: string
		lineageTag: 4c63b014-a67e-4e04-8e11-f0a692efe5f4
		sourceLineageTag: eb9c2371-a7a3-42d6-b79c-aa6a7f334e67
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security NK

		annotation SummarizationSetBy = Automatic

	column 'Src Positions ID'
		dataType: int64
		formatString: 0
		lineageTag: e746365b-d564-4f26-a689-3ba110234459
		sourceLineageTag: 281a43f3-9fe7-4409-a963-c2373ad2c3b9
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: Src Positions ID

		annotation SummarizationSetBy = Automatic

	column 'As of Date'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: f95514e0-a103-4f56-a888-5a6ca2e405f8
		sourceLineageTag: c95fcc22-aff7-44e4-bcf8-9a2cb3b05b28
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: As of Date

		annotation SummarizationSetBy = Automatic

	column 'As of Period'
		dataType: int64
		formatString: 0
		lineageTag: 1d0c2e8a-dd93-4225-b269-a03f608b15b1
		sourceLineageTag: 2e0d5abe-f28d-46f4-ac71-1a376b6669ff
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: As of Period

		annotation SummarizationSetBy = Automatic

	column 'AOCI Allocation ID'
		dataType: int64
		formatString: 0
		lineageTag: 3afa83e0-2ea8-4c60-be1c-4ce4a73e5a50
		sourceLineageTag: 051decd8-a612-460b-8aa7-2fe64b8675a4
		dataCategory: Uncategorized
		summarizeBy: count
		sourceColumn: AOCI Allocation ID

		annotation SummarizationSetBy = Automatic

	column 'AOCI Inception Index'
		dataType: int64
		formatString: 0
		lineageTag: 31b42bd5-b387-4c79-8956-5bebc49fd623
		sourceLineageTag: f4ca4592-9514-478e-88ad-327c5faee488
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: AOCI Inception Index

		annotation SummarizationSetBy = Automatic

	column 'Component No'
		dataType: int64
		formatString: 0
		lineageTag: 0849aaeb-b10b-44e2-8030-f9d308d300f0
		sourceLineageTag: b7e6b1d2-1984-4fba-b6ff-744b0e421f6e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Component No

		annotation SummarizationSetBy = Automatic

	column 'Originating System No'
		dataType: int64
		formatString: 0
		lineageTag: 6a60a23f-0443-4e3b-9a3c-e550f88a3d1f
		sourceLineageTag: 79697fed-a3f3-4f0f-afd6-c3914a815977
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Originating System No

		annotation SummarizationSetBy = User

	column 'Asset Portfolio Code'
		dataType: string
		lineageTag: e96933db-a9fb-4c18-b9f8-f4eb4ce40002
		sourceLineageTag: 5a1a1651-c3c4-4abe-98d2-22329c4b1fc3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asset Portfolio Code

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Code'
		dataType: string
		lineageTag: 70cca10f-57f4-4e4c-8ae2-a5763c478b46
		sourceLineageTag: 8d184db4-1412-43d4-925e-9b3eef60968f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Portfolio Code

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Name'
		dataType: string
		lineageTag: ecc6fed5-1f49-48d0-80ab-5394cd88687e
		sourceLineageTag: 38d13d01-f060-49cb-b812-6a4ed3ee5b1e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Portfolio Name

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Code & Name'
		dataType: string
		lineageTag: bec86547-8b58-4a47-9c25-ba1c730e85c0
		sourceLineageTag: be742ee9-0d97-45c4-8993-e56b5d994c16
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Portfolio Code & Name

		annotation SummarizationSetBy = Automatic

	column 'Portfolio NK'
		dataType: string
		lineageTag: d001f8ec-84c5-4d9c-a415-72d6395c2f40
		sourceLineageTag: d3ed84fd-1b91-477c-98ba-b865d7a10caa
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Portfolio NK

		annotation SummarizationSetBy = Automatic

	column 'Accounting Unit Code & Name'
		dataType: string
		lineageTag: a203b4e1-a0fa-42db-8b80-b5c58b9804c9
		sourceLineageTag: 7697bd46-adb2-4d6a-ab76-cd3d7e71243f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Accounting Unit Code & Name

		annotation SummarizationSetBy = Automatic

	column 'Company Code & Name'
		dataType: string
		lineageTag: da0a7495-3f2a-4303-9a35-3812974362c7
		sourceLineageTag: 63758c1f-07f3-4f33-9cfd-03469a3f3aa3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Company Code & Name

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Group Code'
		dataType: string
		lineageTag: cccfb551-10fa-4c98-a43f-bc17599ef6fa
		sourceLineageTag: 1ff9888f-e6ba-4227-a600-716f66a99b7a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Portfolio Group Code

		annotation SummarizationSetBy = Automatic

	column Local
		dataType: string
		lineageTag: 81ed6445-97bf-4b06-bc93-42953cd8bb6b
		sourceLineageTag: 7313d884-3de3-4971-ae6e-66749f9e3473
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Local

		annotation SummarizationSetBy = Automatic

	column Base
		dataType: string
		lineageTag: f4534e3e-fc4d-4766-b5c5-aa7029d2a2d3
		sourceLineageTag: 4ad77fb8-8262-4cb6-afc0-8bb1bef50b2e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Base

		annotation SummarizationSetBy = Automatic

	column 'Framework Code'
		dataType: string
		lineageTag: b0cb4d8a-7564-4a6d-8953-cd3e68ae7d8d
		sourceLineageTag: 5113fbe8-c0b9-4596-9bc7-3f1e6d454629
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Framework Code

		annotation SummarizationSetBy = Automatic

	column 'SCD Security ID'
		dataType: string
		lineageTag: 9cef5c18-88a4-4b98-837c-6ded5072f65f
		sourceLineageTag: bae9b6af-d2f9-4b72-b2f7-ee8b1eda7674
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Security ID

		annotation SummarizationSetBy = Automatic

	column 'SCD Security Name'
		dataType: string
		lineageTag: 4a64a7a9-cdec-4c4d-a6c5-2d27d86849fc
		sourceLineageTag: ff92fb26-a2a2-4673-a86b-fc7257bbd696
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Security Name

		annotation SummarizationSetBy = Automatic

	column 'SCD Instrument Category'
		dataType: string
		lineageTag: 2e158ed4-fc44-42f7-a4a5-6b271b0e11a6
		sourceLineageTag: 19a3bdba-0c6a-426d-afdc-9da06ad9522a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SCD Instrument Category

		annotation SummarizationSetBy = Automatic

	column 'Instrument Type'
		dataType: string
		lineageTag: 4b308545-422b-4a64-b6f3-4cb376805104
		sourceLineageTag: 23c6eb70-850f-4cce-b2cc-05835188a3d4
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Instrument Type

		annotation SummarizationSetBy = Automatic

	column 'Asset Class'
		dataType: string
		lineageTag: 9aa84bc3-28e6-4a67-82c1-e0b1758a6df6
		sourceLineageTag: 5764976a-8214-4fdf-8c8d-1be53fe7ea7b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asset Class

		annotation SummarizationSetBy = Automatic

	column 'Lot ID'
		dataType: string
		lineageTag: 8b035570-22bc-4e68-bb82-722c8eadb08e
		sourceLineageTag: 9db6ad5f-edce-486a-a841-5f717847250a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Lot ID

		annotation SummarizationSetBy = Automatic

	column 'Underlier Src Security ID'
		dataType: string
		lineageTag: 418a890a-c74b-4831-8018-6e3b0ce9af43
		sourceLineageTag: 5c29a7a7-4012-4d72-9c56-910eda37b459
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Underlier Src Security ID

		annotation SummarizationSetBy = Automatic

	column 'Underlier Src Market ID'
		dataType: string
		lineageTag: 6204c65b-386a-42ef-a33a-85ff991e1d03
		sourceLineageTag: 03c8f2c9-a80b-4124-bf33-2e26a94d90d9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Underlier Src Market ID

		annotation SummarizationSetBy = Automatic

	column 'Underlier Src Security'
		dataType: string
		lineageTag: 7d78f6a7-69d0-45b0-9edc-91814fea562b
		sourceLineageTag: cda5234f-7eec-41a1-ba30-a3e93712048c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Underlier Src Security

		annotation SummarizationSetBy = Automatic

	column 'Underlier Security NK'
		dataType: string
		lineageTag: 51aac221-1e4d-4cb1-9107-c07f64d91776
		sourceLineageTag: a09ede1b-7d7c-45eb-86ec-ad1cc65250cb
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Underlier Security NK

		annotation SummarizationSetBy = Automatic

	column 'Functional CCY Code'
		dataType: string
		lineageTag: 24caa42b-6065-496e-b5ab-d972082fcf24
		sourceLineageTag: 87f925fe-d2ba-4993-b980-54ebe0400c98
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Functional CCY Code

		annotation SummarizationSetBy = Automatic

	column 'Local To Func Rate'
		dataType: double
		lineageTag: 32a56548-5692-4959-9df7-5e88c3f52f25
		sourceLineageTag: 0cc3cd4e-b66e-4d4c-97d3-f4eca630a875
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Local To Func Rate

		annotation SummarizationSetBy = Automatic

	column 'Local To CAD Rate'
		dataType: double
		lineageTag: e29f49fb-636c-49c0-8933-bc75b9b7da47
		sourceLineageTag: c7169d93-33ab-4746-a64e-51c17308e1c6
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Local To CAD Rate

		annotation SummarizationSetBy = Automatic

	column 'Local To USD Rate'
		dataType: double
		lineageTag: dfb3de56-98c3-4e15-82c1-ed631fec70ae
		sourceLineageTag: 6e5fc5d4-c56c-4b7e-9361-d810f462c723
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Local To USD Rate

		annotation SummarizationSetBy = Automatic

	column 'Local To HKD Rate'
		dataType: double
		lineageTag: 3df2a453-6e8b-48a8-a326-7acc21faa2ff
		sourceLineageTag: 1f83376e-466c-4bf4-9ded-63fe5fad17bd
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Local To HKD Rate

		annotation SummarizationSetBy = Automatic

	column 'AOCI Hedge Findur ID'
		dataType: string
		lineageTag: c6874821-05f5-4413-a77a-0bd1f3eef6f3
		sourceLineageTag: 6b671eb7-81aa-4ff4-9970-ff5bb6e98716
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: AOCI Hedge Findur ID

		annotation SummarizationSetBy = Automatic

	column 'AOCI Hedge Type'
		dataType: string
		lineageTag: d3a89156-ce67-4274-aa97-88ced5ed05e3
		sourceLineageTag: ad1c90c5-ee8b-449c-bdf0-6c2d81e75a29
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: AOCI Hedge Type

		annotation SummarizationSetBy = Automatic

	column 'AOCI Book Yield (D)'
		dataType: double
		lineageTag: 0718a3c1-7fc2-4254-aa6f-9b9528c842a8
		sourceLineageTag: dca0fd6e-1ed4-4bf6-a6be-e6d05172f160
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: AOCI Book Yield (D)

		annotation SummarizationSetBy = Automatic

	column 'AOCI Hedge Par (D)'
		dataType: double
		lineageTag: 4b72ae71-c350-4718-9129-a0b333c08021
		sourceLineageTag: 798165f9-e4d1-4b0a-b8db-c38c4a680447
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: AOCI Hedge Par (D)

		annotation SummarizationSetBy = Automatic

	column 'Month End Status'
		dataType: string
		lineageTag: 82f12a30-caf1-4836-9639-1a1fd5911ce6
		sourceLineageTag: 568a069b-ce90-4aad-9317-260a49a6339d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Month End Status

		annotation SummarizationSetBy = Automatic

	column 'Balanced Amortized AOCI - Base'
		dataType: double
		lineageTag: 66bd3479-6099-497c-a82b-7a3ea8ce79de
		sourceLineageTag: 056dd922-9930-4bb0-a7c8-2baadd2417ad
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balanced Amortized AOCI - Base

		annotation SummarizationSetBy = Automatic

	column 'Balance Remaining AOCI - Base'
		dataType: double
		lineageTag: d0318a9f-4b5e-48e1-a562-d61756c9e2e4
		sourceLineageTag: 705e372b-6e00-4d03-a430-9ba582c077cb
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Remaining AOCI - Base

		annotation SummarizationSetBy = Automatic

	column 'Balanced Amortized AOCI - Local (D)'
		dataType: double
		lineageTag: 50024266-d60d-4831-9971-d09db48af0f8
		sourceLineageTag: 2db62c9c-f660-46b0-ae6a-ccf082e2c5a7
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balanced Amortized AOCI - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Balance Remaining AOCI - Local (D)'
		dataType: double
		lineageTag: 3b0b7276-878d-4105-bb81-8a85783404ec
		sourceLineageTag: e5a434c6-682a-4e05-8cf4-5a2866c5649a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Balance Remaining AOCI - Local (D)

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID & Desc (Sublot)'
		dataType: string
		lineageTag: 4412d5ed-730c-46e2-9fcd-d33eadd2dd7a
		sourceLineageTag: f0c2a762-517e-43e0-972a-48361fff1921
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Primary Security ID & Desc (Sublot)

		annotation SummarizationSetBy = Automatic

	column 'Asset Class (Sublot)'
		dataType: string
		lineageTag: eb045176-0efb-4b9e-954f-962c9ebe0afb
		sourceLineageTag: fa78bcab-3016-4677-8c6f-da9d7f8f105d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asset Class (Sublot)

		annotation SummarizationSetBy = Automatic

	column 'Asset Group (Sublot)'
		dataType: string
		lineageTag: a8739f49-7599-4ca9-9171-6b408ab59f80
		sourceLineageTag: aa6f0811-dc8c-4c7d-97ca-16c480a98009
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asset Group (Sublot)

		annotation SummarizationSetBy = Automatic

	column 'Asset Type (Sublot)'
		dataType: string
		lineageTag: 5684adf9-28e7-4531-ae3a-7b21ce119ce1
		sourceLineageTag: 38d3480c-36a5-4c1d-b105-d89726ddeb30
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Asset Type (Sublot)

		annotation SummarizationSetBy = Automatic

	column 'Bus Trans Num'
		dataType: string
		lineageTag: 3517c724-1c18-4a36-b405-cfed64ce665a
		sourceLineageTag: 99ce9bde-41a8-4aab-95b0-17a0b38c1f02
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Bus Trans Num

		annotation SummarizationSetBy = Automatic

	column 'Company Code & Name Display'
		dataType: string
		lineageTag: 75f01193-7f48-4e28-80e8-c62d5b4270cd
		sourceLineageTag: 34fed896-52f7-4691-9430-2122ac15e487
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Company Code & Name Display

		annotation SummarizationSetBy = Automatic

	column 'Accounting Unit Code & Name Display'
		dataType: string
		lineageTag: aa56422c-37c8-4827-ac7b-c7feb59a00d5
		sourceLineageTag: b0a38400-de5f-46b2-9e8e-bb09d3eb564b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Accounting Unit Code & Name Display

		annotation SummarizationSetBy = Automatic

	column 'Src Security ID'
		dataType: string
		lineageTag: fdb5a95f-075f-4c4c-b9e0-94a32be831ba
		sourceLineageTag: 5c5dd402-22ba-4bbe-b694-e9e5d5c5a7cf
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Src Security ID

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 6b7a008a-2f45-49a7-b750-701e2b9ba218
		sourceLineageTag: 5f1318e0-d853-4790-a010-d292edfb0600
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Updated Ts'
		dataType: dateTime
		formatString: yyyy\-mm\-dd hh:nn:ss AM/PM
		lineageTag: df743b8c-2545-4f13-9b9b-63a51fdf00fd
		sourceLineageTag: da1f1db1-ce3a-4bad-a590-4f28ede1f5c9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Updated Ts

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID (Sublot)'
		dataType: string
		lineageTag: a7efe398-4eed-4b63-bf77-628fc85a4fb4
		sourceLineageTag: f037fafa-dcd2-4441-b260-96a5748881c2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Primary Security ID (Sublot)

		annotation SummarizationSetBy = Automatic

	column 'FX Join Key'
		dataType: string
		lineageTag: d8b8c71a-1394-41ee-a7d6-986670306c97
		sourceLineageTag: 4d12f3dd-7fd2-4360-8ba6-af14836d4c45
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: FX Join Key

		annotation SummarizationSetBy = Automatic

	column 'Unique Sublot ID'
		dataType: string
		lineageTag: 1c662106-8039-42db-972d-f86e77a98f87
		sourceLineageTag: 8d50d671-28c7-4de1-b775-d78b6bb3088b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Unique Sublot ID

		annotation SummarizationSetBy = Automatic

	partition 'Securities Sublot Fact-0f554d27-6f8e-49bc-9c11-a6909515671d' = entity
		mode: directQuery
		source
			entityName: Securities Sublot Fact
			expressionSource: 'DirectQuery to AS - Securities'

