table 'Securities GL Txn fact - Elim'
	lineageTag: 65a773e5-b2c3-4394-8ac4-c01fcfa3a6d1
	sourceLineageTag: 7f3a52b5-aeca-4c84-a284-d1db5074f072

	measure 'Unreal Pl BV - Local (Sec Elim Adj)' = EXTERNALMEASURE("Unreal Pl BV - Local (Sec Elim Adj)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 7330a3bf-808c-4e67-b763-fe4fbc37a8cf
		sourceLineageTag: f3a18c40-0041-4e4d-b6f2-d7ab2af22b58
		dataCategory: Uncategorized

	measure 'Unreal Pl BV - Rep (Sec Elim Adj)' = EXTERNALMEASURE("Unreal Pl BV - Rep (Sec Elim Adj)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: f683faa3-8f67-4f66-a0b9-ecc7089f6084
		sourceLineageTag: 6cb84352-c1f8-4750-8b4e-c0b457472ef1
		dataCategory: Uncategorized

	measure 'Balance Book Value - Local(Sec Elim Adj)' = EXTERNALMEASURE("Balance Book Value - Local(Sec Elim Adj)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 2e3c4628-f18d-4deb-8470-c0d491927de4
		sourceLineageTag: d9876c13-39be-4bde-b033-9d785eafd8b9
		dataCategory: Uncategorized

	measure 'Balance Book Value - Rep(Sec Elim Adj)' = EXTERNALMEASURE("Balance Book Value - Rep(Sec Elim Adj)", DOUBLE, "DirectQuery to AS - Securities")
		lineageTag: 96d12f6b-027d-423f-844e-a333609115c0
		sourceLineageTag: 33e5de26-6a61-4fe0-a3be-11970e185c74
		dataCategory: Uncategorized

	measure 'Security Elim Adjustment Title' = EXTERNALMEASURE("Security Elim Adjustment Title", STRING, "DirectQuery to AS - Securities")
		lineageTag: 7026159f-f88f-4385-8106-c1a12f3f3fec
		sourceLineageTag: 9dd16b1f-c0b0-428e-b980-16c288a994fb
		dataCategory: Uncategorized

	column 'Company Accounting Unit'
		dataType: string
		lineageTag: 57322683-1605-4e43-9ff1-1f125cffee5f
		sourceLineageTag: 157d461b-10c6-4f7c-a54d-61a2b9c8d6e8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Company Accounting Unit

		annotation SummarizationSetBy = User

	column 'Portfolio NK'
		dataType: string
		lineageTag: 7ffdb0b7-cc4a-46d6-9ab4-dfb0b72d3ba6
		sourceLineageTag: 8b9cc68c-332e-4da6-8678-56e700d7ed3a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Portfolio NK

		annotation SummarizationSetBy = User

	column 'Framework Cd'
		dataType: string
		lineageTag: 41a31f9a-4a93-4a5f-9240-3f54d6403558
		sourceLineageTag: f0db623c-7059-4cae-9a6c-0672c84f0b63
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Framework Cd

		annotation SummarizationSetBy = User

	column 'Txn Dt'
		dataType: dateTime
		formatString: yyyy\-mm\-dd
		lineageTag: b8bf4af5-1e46-478f-96c0-a01c5e0cf4da
		sourceLineageTag: 45d72454-af54-4a98-b049-cac8ea723f1f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Txn Dt

		annotation SummarizationSetBy = User

	column 'Fx Join Key'
		dataType: string
		lineageTag: ccec6c92-e80c-422f-a4e0-eb6cce3f5611
		sourceLineageTag: 05e9846c-a200-41d0-918c-c60d68140de6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Fx Join Key

		annotation SummarizationSetBy = Automatic

	column 'Security Nk'
		dataType: string
		lineageTag: 8ee85c83-ccf5-464a-9148-c090c402368a
		sourceLineageTag: 175e263f-8d33-4aff-b326-36b386f884b2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Security Nk

		annotation SummarizationSetBy = User

	column 'GL Acct Num'
		dataType: string
		lineageTag: 72ef2b20-f5c8-417b-a70b-848ab6ba6fc7
		sourceLineageTag: 2836e4b2-8bca-491f-83cc-9cdad656ba5c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: GL Acct Num

		annotation SummarizationSetBy = User

	column 'Acct Category'
		dataType: string
		lineageTag: 4897b6e7-47cb-4dee-9fe7-218c8b5e1453
		sourceLineageTag: e38674a6-0a14-4bb4-9eb2-dd390c81bdb2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Acct Category

		annotation SummarizationSetBy = User

	column 'ISO3 Currency Cd'
		dataType: string
		lineageTag: 03e54a59-cadd-4066-b33d-3532725ccb6a
		sourceLineageTag: 3964cfa5-dfe4-4e80-9953-c168a25da9f0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ISO3 Currency Cd

		annotation SummarizationSetBy = User

	column 'Functional CCY Cd'
		dataType: string
		lineageTag: 967afc12-b75b-41ef-8654-15595456603a
		sourceLineageTag: cc1dc380-753b-49f8-926c-70ad18c61df5
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Functional CCY Cd

		annotation SummarizationSetBy = User

	column 'Txn Num'
		dataType: string
		lineageTag: 0f37feb0-95cd-440b-9898-7b6a4b484b6c
		sourceLineageTag: 9812e047-815c-4345-ac71-d3e45a5cbc25
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Txn Num

		annotation SummarizationSetBy = User

	column Comments
		dataType: string
		lineageTag: ea692dcb-8d40-4b3f-ac7e-3836f598f647
		sourceLineageTag: fff8c91b-753f-465c-aa21-6eac849da434
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = User

	column 'CAT Adjusted Elements Txt'
		dataType: string
		lineageTag: 9b76802c-ed4a-4172-a895-92c3a8cb6051
		sourceLineageTag: 83e07bf9-7d60-41a9-a770-7fa93b17d2a0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: CAT Adjusted Elements Txt

		annotation SummarizationSetBy = User

	column 'Bus Trans No'
		dataType: string
		lineageTag: b624f7e4-f4e5-4c73-ae6b-7ed6c1f3c90f
		sourceLineageTag: e94789c1-af91-4b8c-a798-df2587707dd6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Bus Trans No

		annotation SummarizationSetBy = User

	column 'Local Txn Amt'
		dataType: double
		lineageTag: 8535065d-edce-4717-8468-61594720a4c4
		sourceLineageTag: 2adbbe09-1851-4494-8809-92290c9956a6
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Local Txn Amt

		annotation SummarizationSetBy = User

	column Src
		dataType: string
		lineageTag: f5a4e2d6-af94-4cac-8716-4be1b06a5277
		sourceLineageTag: 526d1e93-75c0-4ec6-b125-388460e41146
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Src

		annotation SummarizationSetBy = User

	column Account
		dataType: string
		lineageTag: 6f10988d-6add-40f9-aa34-6946285a4aa1
		sourceLineageTag: 732186b4-c44d-4b5a-9fda-21916af9c88b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Account

		annotation SummarizationSetBy = User

	column 'Accounting Unit'
		dataType: string
		lineageTag: 3dad2db1-ae8d-48d6-865b-ece1b19b1694
		sourceLineageTag: 23d32be5-2cc7-4cf7-b64a-af37884b49ed
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Accounting Unit

		annotation SummarizationSetBy = User

	column Company
		dataType: string
		lineageTag: d3112be6-9a56-4b98-89f8-c7053ca4ef61
		sourceLineageTag: 09d15776-fb1b-47bd-ba4e-5038596d0e8f
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = User

	column 'Group Structure Company'
		dataType: int64
		formatString: 0
		lineageTag: 5dfc181e-f517-4016-972d-671b273ab7a0
		sourceLineageTag: 2b2b08fe-244e-408f-94d8-fb2089ad900a
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Group Structure Company

		annotation SummarizationSetBy = User

	partition 'Securities GL Txn fact - Elim' = entity
		mode: directQuery
		source
			entityName: Securities GL Txn fact - Elim
			expressionSource: 'DirectQuery to AS - Securities'

