table 'Cat Staging Text Fact'
	lineageTag: a0a735df-025c-4043-b0f6-3aad4e565c3d

	column 'Framework Cd'
		dataType: string
		lineageTag: 4bcaa4f3-039c-4536-893f-390ba8bb4838
		summarizeBy: none
		sourceColumn: Framework Cd

		annotation SummarizationSetBy = Automatic

	column 'Txn Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: e28aa790-f5ab-4ac4-8b9e-9ed3d39f72d2
		summarizeBy: none
		sourceColumn: Txn Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Txn Period'
		dataType: int64
		formatString: 0
		lineageTag: dc576c09-a9d7-4bb4-876f-0b272e1d2d58
		summarizeBy: sum
		sourceColumn: Txn Period

		annotation SummarizationSetBy = Automatic

	column 'Asset Id'
		dataType: string
		lineageTag: 9f39aa46-97fe-4bb5-8576-a655249c54e6
		summarizeBy: none
		sourceColumn: Asset Id

		annotation SummarizationSetBy = Automatic

	column 'Cat Asset Type Cd'
		dataType: string
		lineageTag: 6fb1bbea-936a-44ff-930a-e12ac5b78035
		summarizeBy: none
		sourceColumn: Cat Asset Type Cd

		annotation SummarizationSetBy = Automatic

	column 'Txn Num'
		dataType: string
		lineageTag: 92669d29-ab94-4102-8169-9761b3795ed6
		summarizeBy: none
		sourceColumn: Txn Num

		annotation SummarizationSetBy = Automatic

	column 'Staging Txt'
		dataType: string
		lineageTag: f6437efa-effb-424e-b1ab-d2d1518cef2d
		summarizeBy: none
		sourceColumn: Staging Txt

		annotation SummarizationSetBy = Automatic

	column 'Company Num Cd'
		dataType: string
		lineageTag: 07f9334f-999e-4e5a-ae96-7ca58b8396db
		summarizeBy: none
		sourceColumn: Company Num Cd

		annotation SummarizationSetBy = Automatic

	partition 'Cat Staging Text Fact-094061e4-b59a-424d-a11c-78232f3a25cc' = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs(HostName, HTTPPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null,CommandTimeout= #duration(0,5,0,0), EnableQueryResultDownload="0"]),
				    hive_metastore_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    inv_semantic_ga_Schema = hive_metastore_Database{[Name="inv_semantic_ga",Kind="Schema"]}[Data],
				    EDL_cat_staging_text_fact_dq = inv_semantic_ga_Schema{[Name="cat_staging_text_fact_dq",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(EDL_cat_staging_text_fact_dq,{{"framework_cd", "Framework Cd"}, {"txn_dt", "Txn Dt"}, {"txn_period", "Txn Period"}, {"asset_id", "Asset Id"}, {"cat_asset_type_cd", "Cat Asset Type Cd"}, {"txn_num", "Txn Num"}, {"staging_txt", "Staging Txt"}, {"company_num_cd", "Company Num Cd"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"Framework Cd", "Txn Dt", "Txn Period", "Asset Id", "Cat Asset Type Cd", "Txn Num", "Staging Txt", "Company Num Cd"})
				in
				    #"Removed Other Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

