table 'CAT Adjmt Config Table'
	lineageTag: aae186ca-ffde-48c3-8ea6-d19f18b43b3c

	column 'Measure Name'
		dataType: string
		lineageTag: 883281cf-4992-4d96-bb2e-ec8e5c60039d
		summarizeBy: none
		sourceColumn: Measure Name

		annotation SummarizationSetBy = Automatic

	column 'GL Acct Num'
		dataType: int64
		formatString: 0
		lineageTag: bd9462a9-5be0-4d82-a2fe-a91e28698fd5
		summarizeBy: sum
		sourceColumn: GL Acct Num

		annotation SummarizationSetBy = Automatic

	partition 'CAT Adjmt Config Table-82a69eba-fcea-4bb8-b286-748673bc1edb' = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs(HostName, HTTPPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null,CommandTimeout= #duration(0,5,0,0), EnableQueryResultDownload="0"]),
				    hive_metastore_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    inv_semantic_ga_Schema = hive_metastore_Database{[Name="inv_semantic_ga",Kind="Schema"]}[Data],
				    EDL_cat_config_mapping_data = inv_semantic_ga_Schema{[Name="cat_config_mapping_data",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(EDL_cat_config_mapping_data,{{"MEASURE_NAME", "Measure Name"}, {"GL_ACCT_NUM", "GL Acct Num"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

