table 'Securities Transaction GA Fact'
	lineageTag: c44dc4d5-bb32-4570-bed2-86711ac4d3c2

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: month
		rollingWindowPeriods: 16
		incrementalGranularity: month
		incrementalPeriods: 16
		pollingExpression = Securities_Transaction_Fact_PBI_Config
		sourceExpression =
			let
			    Source = Databricks.Catalogs(HostName, HTTPPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null,CommandTimeout= #duration(0,5,0,0), EnableQueryResultDownload="0"]),
			    hive_metastore_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
			    inv_semantic_ga_Schema = hive_metastore_Database{[Name="inv_semantic_ga",Kind="Schema"]}[Data],
			    EDL_securities_transaction_ga_fact_dq = inv_semantic_ga_Schema{[Name="securities_transaction_ga_fact_dq",Kind="Table"]}[Data],
			    #"Removed Other Columns" = Table.SelectColumns(EDL_securities_transaction_ga_fact_dq,{"TRANSACTION_NO", "LEG", "REVERSAL", "TRANS_STATUS", "PORTFOLIO_CD", "POST_DT", "PORTFOLIO_CODE_NM", "ACCOUNTING_UNIT_CODE_NAME", "COMPANY_CODE_NAME", "TRANS_CATEGORY", "BUS_TRANS_SUBCATEGORY", "TRANS_TYPE", "FRAMEWORK_CD", "GL_CLASS", "ELEMENTARY_TRANS_CODE", "PERIOD_CLOSE_DT", "POSTING_LAG", "TRADE_DT", "SETTLE_DT", "ACTUAL_SETTLE_DATE", "FINAL_REPORTING_DATE", "PAYMENT_DATE", "AS_OF_PERIOD", "PORTFOLIO_NK", "BLOOMBERG_NO", "MASTER_TICKET", "ORDER_NO", "SOURCE_ID", "MATCH_SRC_TRANSACTION_ID", "USER_NM", "SETTLE_CCY_CD", "SETTLE_CURRENCY", "LOCAL_CCY_CD", "LOCAL_CURRENCY", "UNDERLIER_MATURITY_DATE", "UNDERLIER_NEXT_COUPON_DATE", "UNDERLIER_COUPON", "SETTLE_EXCHANGE_RATE", "LOCAL_EXCHANGE_RATE", "SIGN", "UNITS", "POOL_FACTOR", "ORIGINAL_FACE", "CONTRACTS", "CURRENT_FACE", "NOMINAL_BASIS", "BROKER_CD", "BROKER_NM", "COUNTERPARTY_CODE", "COUNTERPARTY_NAME", "CMMT", "CLASS_CD", "BUS_TRANS_CODE", "MATERIALITY", "BASE_AMT", "SETTLE_AMT", "BASE_PRINCIPAL", "SETTLE_PRINCIPAL", "BASE_INTEREST", "SETTLE_INTEREST", "BASE_MATURITY_AMOUNT", "SETTLE_MATURITY_AMOUNT", "CURRENT_VALUE_CCY_LOCAL", "TRANS_PRICE_LOCAL", "BASE_PRICE", "PRICE_LOCAL", "SETTLE_PRICE", "ORIGINAL_COST_BASE", "ORIGINAL_COST_LOCAL", "AMORTIZED_COST_BASE", "AMORTIZED_COST_LOCAL", "REALIZED_G_L_ON_CURRENCY_BASE", "REALIZED_G_L_ON_INVESTMENT_BASE", "REALIZED_G_L_BASE", "REALIZED_G_L_LOCAL", "TRANSACTION_YIELD", "FUNCTIONAL_CCY_CD", "LOCAL_TO_FUNC_RATE", "LOCAL_TO_CAD_RATE", "LOCAL_TO_USD_RATE", "LOCAL_TO_HKD_RATE", "TRANSACTION_AMOUNT", "OID_AMORT_CCY_BASE", "OID_AMORT_CCY_LOCAL", "IMPAMT_CCY_BASE", "IMPAMT_CCY_LOCAL", "INCOME_GROSS_AMOUNT_CCY_BASE", "INCOME_GROSS_AMOUNT_CCY_LOCAL", "LIABILITY_PORTF_CODE", "BASE_CCY_CD", "PAYMENT_PURPOSE", "PURPOSE", "COUNTRY", "COUNTRY_NM", "GROUPCODE", "BANK_CODE", "BANK_ACCOUNT_CODE", "SCD_SECURITY_ID", "TRAN_HUB_ID", "SECURITY_NK", "UNDERLIER_SEC_KEY", "SCD_SECURITY_TYPE", "UNDERLIER_SRC_SECURITY_ID", "SRC_SECURITY_ID", "FX_SWAP_TICKET_NUMBER", "SUB_BROKER", "SUB_BROKER_DES", "IPO", "LONG_NOTE_3", "LONG_NOTE_4", "LONG_NOTE_5", "TRADER_DESK", "SETTLE_DAYS", "TRANSASOFDATE", "HAIRCUT", "TRADING_COMMENT", "TRANSACTION_PURPOSE", "ORIGINAL_SYSTEM_TRAN_NUMBER", "INTEREST_DATE", "REGION", "VALUATION_CYCLE", "POST_TIME", "BACKPOST_MONTH", "TAX_LOT_IX", "LOT_SOURCE_TRANSACTION_ID", "BUS_TRANS_NO", "LOT_ID", "ASIA_ASSET_CLASS_CODE_IN", "ASIA_ASSET_CLASS_CODE_VI", "ASIA_ASSET_CLASS_DESC_IN", "ASIA_ASSET_CLASS_DESC_VI", "GROUP_STRUCTURE_RELATION", "BALANCE_BOOK_VALUE_CCY_LOCAL", "BALANCE_BOOK_VALUE_CCY_BASE", "INT_APR_CCY_LOCAL", "INT_APR_CCY_BASE", "ECL_LOSS_CCY_LOCAL", "ECL_LOSS_CCY_BASE", "CECL_LOSS_CCY_LOCAL", "CECL_LOSS_CCY_BASE", "IMPAIRMENT_CCY_LOCAL", "IMPAIRMENT_CCY_BASE", "REA_AOCI_BV_CCY_LOCAL", "REA_AOCI_BV_CCY_BASE", "DEFERRED_PL_CCY_LOCAL", "DEFERRED_PL_CCY_BASE", "P_OR_L_BOOK_CCY_LOCAL", "P_OR_L_BOOK_CCY_BASE", "COST_VALUE_CCY_LOCAL", "COST_VALUE_CCY_BASE", "OID_INT_APPR_CCY_LOCAL", "OID_INT_APPR_CCY_BASE", "REAL_INT_APPR_CCY_BASE", "REAL_INT_APPR_CCY_LOCAL", "CON_CL_ALLOW_CCY_BASE", "CON_CL_ALLOW_CCY_LOCAL", "CHANGE_AOCI_BV_CCY_BASE", "CHANGE_AOCI_BV_CCY_LOCAL", "CHANGE_AOCI_NONBV_CCY_BASE", "CHANGE_AOCI_NONBV_CCY_LOCAL", "LOT_NOMINAL", "UNPAID_AMOUNT_CCY_LOCAL", "PAYMENT_AMOUNT_CCY_BASE", "NOMINAL_OUTGOING_AMOUNT", "NOMINAL_INCOMING_AMOUNT", "NET_AMOUNT_LOCAL", "TRADER_LOGIN", "BLOOMBERG_TIMESTAMP", "AOCI_HEDGE_FINDUR_ID", "TR_FREECOMMENT", "TRANS_STATUS_ACTUAL", "TOTAL_CASH_PROCEEDS", "INTEREST_TRADE_LOCAL", "UNITS_QUANTITY", "SRC", "UPDATED_TS", "REFERENCE_SECURITY_ID", "MASTER_TICKET_NUMBER", "ORIGINAL_SYSTEM", "originating_system_no", "dgl_inception_trans_no", "changed_date", "ALT_INV_TRANS_TYPE", "NOMINAL_TO_MATCH", "POS_TRANS_LINK", "TXN_LONG_SHORT_INDICATOR", "SCD_COUPON_RATE", "YIELD_FOR_MATH_ADJ", "WASH_SALE_TRANSACTION_ID", "BLOOMBERG_TRANSACTION_IDENTIFIER", "WASH_SALE_PARENT_LOT_ID", "P_OR_L_BOOK_SEC_BASE_CCY", "P_OR_L_BOOK_CCY_BASE_CCY", "WASH_SALE_PROCESS_ID", "MANULIFE_LOCAL_PRICE", "REAL_AMORTISATION_BASE_CCY", "REAL_AMORTISATION_LOCAL_CCY", "UNREAL_OID_ACCRETION_BASE_CCY", "UNREAL_OID_ACCRETION_LOCAL_CCY", "BOOKED_CURRENT_VALUE_LOCAL_CCY", "BOOKED_CURRENT_VALUE_BASE_CCY", "AMORTISED_COST_CCY_CORR_BASE_CCY", "AMORTISED_COST_CCY_RESULT_BASE_CCY", "AMORTISED_COST_SEC_BASE_CCY", "AMORTISED_COST_LOCAL_CCY", "REAL_OID_AMORTISATION_BASE_CCY", "REAL_OID_AMORTISATION_LOCAL_CCY", "BUCKET", "SRC_CREATED_TS", "SRC_UPDATED_TS", "FX_JOIN_KEY", "Settle_status_PBI", "REALISED_IMPAIRMENT_LOCAL_CCY", "REALISED_IMPAIRMENT_SEC_BASE_CCY", "REALISED_IMPAIRMENT_CCY_BASE_CCY", "ORIGINAL_POST_DT", "IFRS9PURPOSE", "long_note_2", "long_note_1", "long_note_6", "long_note_7", "long_note_8", "short_note_1", "short_note_2", "short_note_3", "short_note_4", "short_note_5", "short_note_6", "short_note_7", "short_note_8", "custodian_name", "user_change_id", "user_change_name", "processing_group_nm"}),
			    #"Load data from specific date"= Table.SelectRows(#"Removed Other Columns",each [TRANSASOFDATE] >= pCutOffDate),
			    #"Renamed Columns" = Table.RenameColumns(#"Load data from specific date",{{"TRANSACTION_NO", "Transaction No"}, {"LEG", "Leg"}, {"REVERSAL", "Reversal"}, {"TRANS_STATUS", "Trans Status"}, {"PORTFOLIO_CD", "Portfolio Code"}, {"POST_DT", "Post Date"}, {"PORTFOLIO_CODE_NM", "Portfolio Code & Name"}, {"ACCOUNTING_UNIT_CODE_NAME", "Accounting Unit Code & Name"}, {"COMPANY_CODE_NAME", "Company Code & Name"}, {"TRANS_CATEGORY", "Trans Category"}, {"BUS_TRANS_SUBCATEGORY", "Bus Trans Subcategory"}, {"TRANS_TYPE", "Trans Type"}, {"FRAMEWORK_CD", "Framework Code"}, {"GL_CLASS", "GL Class"}, {"ELEMENTARY_TRANS_CODE", "Elementary Trans Code "}, {"PERIOD_CLOSE_DT", "Period Close Date"}, {"POSTING_LAG", "Posting Lag"}, {"TRADE_DT", "Trade Date"}, {"SETTLE_DT", "Settle Date"}, {"ACTUAL_SETTLE_DATE", "Actual Settle Date"}, {"FINAL_REPORTING_DATE", "Final Reporting Date"}, {"PAYMENT_DATE", "Payment Date"}, {"AS_OF_PERIOD", "As Of Period"}, {"PORTFOLIO_NK", "Portfolio NK"}, {"BLOOMBERG_NO", "Bloomberg No"}, {"MASTER_TICKET", "Master Ticket"}, {"ORDER_NO", "Order No"}, {"SOURCE_ID", "Source ID"}, {"MATCH_SRC_TRANSACTION_ID", "Match Src Transaction ID"}, {"USER_NM", "User Name"}, {"SETTLE_CCY_CD", "Settle Ccy Code"}, {"SETTLE_CURRENCY", "Settle Currency"}, {"LOCAL_CCY_CD", "Local"}, {"LOCAL_CURRENCY", "Local Currency"}, {"UNDERLIER_MATURITY_DATE", "Underlier Maturity Date"}, {"UNDERLIER_NEXT_COUPON_DATE", "Underlier Next Coupon Date"}, {"UNDERLIER_COUPON", "Underlier Coupon"}, {"SETTLE_EXCHANGE_RATE", "Settle Exchange Rate"}, {"LOCAL_EXCHANGE_RATE", "Local Exchange Rate"}, {"SIGN", "Sign"}, {"UNITS", "Units"}, {"POOL_FACTOR", "Pool Factor"}, {"ORIGINAL_FACE", "Original Face"}, {"CONTRACTS", "Contracts"}, {"CURRENT_FACE", "Current Face"}, {"NOMINAL_BASIS", "Nominal Basis"}, {"BROKER_CD", "Broker Code"}, {"BROKER_NM", "Broker Name"}, {"COUNTERPARTY_CODE", "Counterparty Code"}, {"COUNTERPARTY_NAME", "Counterparty Name"}, {"CMMT", "Cmmt"}, {"CLASS_CD", "ClassCode"}, {"BUS_TRANS_CODE", "Bus Trans Code"}, {"MATERIALITY", "Materiality"}, {"BASE_AMT", "Amount - Base"}, {"SETTLE_AMT", "Settle Amount (D)"}, {"BASE_PRINCIPAL", "Principal - Base"}, {"SETTLE_PRINCIPAL", "Settle Principal"}, {"BASE_INTEREST", "Interest - Base"}, {"SETTLE_INTEREST", "Settle Interest"}, {"BASE_MATURITY_AMOUNT", "Maturity Amount - Base"}, {"SETTLE_MATURITY_AMOUNT", "Settle Maturity Amount"}, {"CURRENT_VALUE_CCY_LOCAL", "Current Value - Local"}, {"TRANS_PRICE_LOCAL", "Trans Price Local"}, {"BASE_PRICE", "Price - Base"}, {"PRICE_LOCAL", "Price - Local (D)"}, {"SETTLE_PRICE", "Settle Price"}, {"ORIGINAL_COST_BASE", "Original Cost - Base"}, {"ORIGINAL_COST_LOCAL", "Original Cost - Local"}, {"AMORTIZED_COST_BASE", "Amortized Cost - Base"}, {"AMORTIZED_COST_LOCAL", "Sec Amortization Cost Local"}, {"REALIZED_G_L_ON_CURRENCY_BASE", "Realized Gain/Loss CCY - Base"}, {"REALIZED_G_L_ON_INVESTMENT_BASE", "Realized Gain/Loss Sec - Base"}, {"REALIZED_G_L_BASE", "Realized Gain/Loss - Base"}, {"REALIZED_G_L_LOCAL", "Realized Gain/Loss - Local"}, {"TRANSACTION_YIELD", "Transaction Yield"}, {"FUNCTIONAL_CCY_CD", "Functional Ccy Code"}, {"LOCAL_TO_FUNC_RATE", "Local To FUNC Rate"}, {"LOCAL_TO_CAD_RATE", "Local To CAD Rate"}, {"LOCAL_TO_USD_RATE", "Local To USD Rate"}, {"LOCAL_TO_HKD_RATE", "Local To HKD Rate"}, {"TRANSACTION_AMOUNT", "Transaction Amount"}, {"OID_AMORT_CCY_BASE", "OID Amortization/Accretion - Base"}, {"OID_AMORT_CCY_LOCAL", "OID Amortization/Accretion - Local"}, {"IMPAMT_CCY_BASE", "Imp Amount - Base"}, {"IMPAMT_CCY_LOCAL", "Imp Amount - Local"}, {"INCOME_GROSS_AMOUNT_CCY_BASE", "Income Gross Amount - Base"}, {"INCOME_GROSS_AMOUNT_CCY_LOCAL", "Income Gross Amount - Local"}, {"LIABILITY_PORTF_CODE", "Liability Portf Code"}, {"BASE_CCY_CD", "Base"}, {"PAYMENT_PURPOSE", "Payment Purpose"}, {"PURPOSE", "Purpose"}, {"COUNTRY", "Country"}, {"COUNTRY_NM", "Country Name"}, {"GROUPCODE", "Groupcode"}, {"BANK_CODE", "Bank Code"}, {"BANK_ACCOUNT_CODE", "Bank Account Code"}, {"SCD_SECURITY_ID", "SCD Security ID"}, {"TRAN_HUB_ID", "Tran Hub ID"}, {"SECURITY_NK", "Security NK"}, {"UNDERLIER_SEC_KEY", "Underlier Sec Key"}, {"SCD_SECURITY_TYPE", "SCD Security Type"}, {"UNDERLIER_SRC_SECURITY_ID", "Underlier Src Security ID"}, {"SRC_SECURITY_ID", "Src Security ID"}, {"FX_SWAP_TICKET_NUMBER", "Fx Swap Ticket Number"}, {"SUB_BROKER", "Sub Broker"}, {"SUB_BROKER_DES", "Sub Broker Des"}, {"IPO", "Ipo"}, {"LONG_NOTE_3", "Long Note 3"}, {"LONG_NOTE_4", "Long Note 4"}, {"LONG_NOTE_5", "Long Note 5"}, {"TRADER_DESK", "Trader Desk"}, {"SETTLE_DAYS", "Settle Days"}, {"TRANSASOFDATE", "Transasofdate"}, {"HAIRCUT", "Haircut"}, {"TRADING_COMMENT", "Trading Comment"}, {"TRANSACTION_PURPOSE", "Transaction Purpose"}, {"ORIGINAL_SYSTEM_TRAN_NUMBER", "Original System Tran Number"}, {"INTEREST_DATE", "Interest Date"}, {"REGION", "Region"}, {"VALUATION_CYCLE", "Valuation Cycle"}, {"POST_TIME", "Post Time"}, {"BACKPOST_MONTH", "Backpost Month"}, {"TAX_LOT_IX", "Tax Lot Ix"}, {"LOT_SOURCE_TRANSACTION_ID", "Lot Source Transaction ID"}, {"BUS_TRANS_NO", "Bus Trans Number"}, {"LOT_ID", "Lot ID"}, {"ASIA_ASSET_CLASS_CODE_IN", "Asia Asset Class Code Indonesia"}, {"ASIA_ASSET_CLASS_CODE_VI", "Asia Asset Class Code Vietnam"}, {"ASIA_ASSET_CLASS_DESC_IN", "Asia Asset Class Desc Indonesia"}, {"ASIA_ASSET_CLASS_DESC_VI", "Asia Asset Class Desc Vietnam"}, {"GROUP_STRUCTURE_RELATION", "Group Structure Relation"}, {"BALANCE_BOOK_VALUE_CCY_LOCAL", "Book Value - Local unsigned"}, {"BALANCE_BOOK_VALUE_CCY_BASE", "Book Value - Base unsigned"}, {"INT_APR_CCY_LOCAL", "Int Apr - Local"}, {"INT_APR_CCY_BASE", "Int Apr - Base"}, {"ECL_LOSS_CCY_LOCAL", "ECL Loss - Local"}, {"ECL_LOSS_CCY_BASE", "ECL Loss - Base"}, {"CECL_LOSS_CCY_LOCAL", "CECL Loss - Local"}, {"CECL_LOSS_CCY_BASE", "CECL Loss - Base"}, {"IMPAIRMENT_CCY_LOCAL", "Impairment - Local"}, {"IMPAIRMENT_CCY_BASE", "Impairment - Base"}, {"REA_AOCI_BV_CCY_LOCAL", "REA AOCI BV - Local"}, {"REA_AOCI_BV_CCY_BASE", "REA AOCI BV - Base"}, {"DEFERRED_PL_CCY_LOCAL", "Deferred PL - Local"}, {"DEFERRED_PL_CCY_BASE", "Deferred PL - Base"}, {"P_OR_L_BOOK_CCY_LOCAL", "Realized Gain/Loss Book - Local"}, {"P_OR_L_BOOK_CCY_BASE", "Realized Gain/Loss Book - Base"}, {"COST_VALUE_CCY_LOCAL", "Cost Value - Local unsigned"}, {"COST_VALUE_CCY_BASE", "Cost Value - Base unsigned"}, {"OID_INT_APPR_CCY_LOCAL", "OID Int Appr - Local"}, {"OID_INT_APPR_CCY_BASE", "OID Int Appr - Base"}, {"REAL_INT_APPR_CCY_BASE", "Real Int Appr - Base"}, {"REAL_INT_APPR_CCY_LOCAL", "Real Int Appr - Local"}, {"CON_CL_ALLOW_CCY_BASE", "Con CL Allow - Base"}, {"CON_CL_ALLOW_CCY_LOCAL", "Con CL Allow - Local"}, {"CHANGE_AOCI_BV_CCY_BASE", "Change AOCI BV - Base"}, {"CHANGE_AOCI_BV_CCY_LOCAL", "Change AOCI BV - Local"}, {"CHANGE_AOCI_NONBV_CCY_BASE", "Change AOCI NONBV - Base"}, {"CHANGE_AOCI_NONBV_CCY_LOCAL", "Change AOCI NONBV - Local"}, {"LOT_NOMINAL", "Lot Nominal"}, {"UNPAID_AMOUNT_CCY_LOCAL", "Unpaid Amount - Local (D)"}, {"PAYMENT_AMOUNT_CCY_BASE", "Payment Amount - Base"}, {"NOMINAL_OUTGOING_AMOUNT", "Nominal Outgoing Amount"}, {"NOMINAL_INCOMING_AMOUNT", "Nominal Incoming Amount"}, {"NET_AMOUNT_LOCAL", "Net Amount - Local"}, {"TRADER_LOGIN", "Trader Login"}, {"BLOOMBERG_TIMESTAMP", "Bloomberg Timestamp"}, {"AOCI_HEDGE_FINDUR_ID", "AOCI Hedge Findur ID"}, {"SRC", "Source"}, {"UPDATED_TS", "Updated Ts"}, {"ALT_INV_TRANS_TYPE", "ALT INV TRANS TYPE"}, {"WASH_SALE_PROCESS_ID", "Wash Sale Process ID"}, {"long_note_1", "Long Note 1"}, {"long_note_2", "Long Note 2"}, {"long_note_6", "Long Note 6"}, {"long_note_7", "Long Note 7"}, {"long_note_8", "Long Note 8"}, {"short_note_1", "Short Note 1"}, {"short_note_2", "Short Note 2"}, {"short_note_3", "Short Note 3"}, {"short_note_4", "Short Note 4"}, {"short_note_5", "Short Note 5"}, {"short_note_6", "Short Note 6"}, {"short_note_7", "Short Note 7"}, {"short_note_8", "Short Note 8"}, {"custodian_name", "Custodian Name"}, {"TR_FREECOMMENT", "Tr Freecomment"}, {"TRANS_STATUS_ACTUAL", "Trans Status Actual"}, {"TOTAL_CASH_PROCEEDS", "Total Cash Proceeds"}, {"INTEREST_TRADE_LOCAL", "Interest Trade Local"}, {"UNITS_QUANTITY", "Units/Quantity"}, {"AMORTISED_COST_LOCAL_CCY", "Amortized Cost Local"}, {"user_change_id", "User Change ID"}, {"user_change_name", "User Change Name"}, {"POS_TRANS_LINK", "POS Trans Link"}, {"BLOOMBERG_TRANSACTION_IDENTIFIER", "Bloomberg Tansaction Identifier"}, {"WASH_SALE_PARENT_LOT_ID", "Wash Sale Parent Lot Id"}, {"WASH_SALE_TRANSACTION_ID", "Wash Sale Transaction Id"}, {"P_OR_L_BOOK_CCY_BASE_CCY", "P Or L Book CCY Local"}, {"P_OR_L_BOOK_SEC_BASE_CCY", "P Or L Book Sec Base CCY"}, {"BOOKED_CURRENT_VALUE_LOCAL_CCY", "Booked Current Value Local"}, {"BOOKED_CURRENT_VALUE_BASE_CCY", "Booked Current Value Base"}, {"UNREAL_OID_ACCRETION_BASE_CCY", "Unreal OID Accretion - Base"}, {"UNREAL_OID_ACCRETION_LOCAL_CCY", "Unreal OID Accretion -  Local"}, {"REAL_OID_AMORTISATION_BASE_CCY", "Real OID Amortisation - Base"}, {"REAL_OID_AMORTISATION_LOCAL_CCY", "Real OID Amortisation - Local"}, {"ORIGINAL_SYSTEM", "Original System"}, {"REFERENCE_SECURITY_ID", "Reference Security ID"}, {"MASTER_TICKET_NUMBER", "Master Ticket Number"}, {"NOMINAL_TO_MATCH", "Nominal To Match"}, {"TXN_LONG_SHORT_INDICATOR", "Long Short Ind"}, {"SCD_COUPON_RATE", "SCD Coupon Rate"}, {"MANULIFE_LOCAL_PRICE", "Manulife Local Price"}, {"originating_system_no", "Originating System No"}, {"YIELD_FOR_MATH_ADJ", "Yield For Math Adj"}, {"REAL_AMORTISATION_BASE_CCY", "Real Amortisation Base"}, {"REAL_AMORTISATION_LOCAL_CCY", "Real Amortisation Local"}, {"AMORTISED_COST_SEC_BASE_CCY", "Amortized Cost Sec Base"}, {"AMORTISED_COST_CCY_CORR_BASE_CCY", "Amortized Cost Ccy Corr Base"}, {"AMORTISED_COST_CCY_RESULT_BASE_CCY", "Amortized Cost Ccy Result Base"}, {"SRC_CREATED_TS", "Src Created Ts"}, {"SRC_UPDATED_TS", "Src Updated Ts"}, {"BUCKET", "Bucket"}, {"ORIGINAL_POST_DT", "Original Post Date"}, {"Settle_status_PBI", "Settled Status"}, {"FX_JOIN_KEY", "FX Join Key"}, {"REALISED_IMPAIRMENT_LOCAL_CCY", "Realised Impairment Local"}, {"REALISED_IMPAIRMENT_SEC_BASE_CCY", "Realised Impairment Sec Base"}, {"REALISED_IMPAIRMENT_CCY_BASE_CCY", "Realised Impairment Ccy Base"}, {"dgl_inception_trans_no", "Dgl Inception Trans No"}, {"IFRS9PURPOSE", "IFRS9 Purpose"}, {"processing_group_nm", "Processing Group Name"}, {"changed_date", "Changed Date"}}),
			    #"Filtered Rows - Incremental Refresh" = Table.SelectRows(#"Renamed Columns", each [Transasofdate] >= Date.From(RangeStart) and [Transasofdate] < Date.From(RangeEnd))
			in
			    #"Filtered Rows - Incremental Refresh"

	measure '# of Transactions' = COUNT ( 'Securities Transaction GA Fact'[Transaction No] )
		formatString: #,0
		lineageTag: 11afa9bf-16d3-4906-aea1-3911a2baf20f

	measure 'Max of Post Hour' =
			
			Hour(MAX('Securities Transaction GA Fact'[Post Time]))
		formatString: 0
		lineageTag: 84812f66-1478-4e10-b707-7db68f750a48

	measure 'Security Transactions Title' = ```
			
			VAR maxdate =
			    MAX ( 'Securities Transaction GA Fact'[Transasofdate] )
			VAR mindate =
			    MIN ( 'Securities Transaction GA Fact'[Transasofdate] )
			VAR fw =
			    SELECTEDVALUE ( Framework[Framework Display] )
			VAR Rep =
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) 
			RETURN
			    "Security Transactions" & ", " & Rep & ", " & fw & ", "
			        & FORMAT ( mindate, "dd-mmm-yy" ) & " - "
			        & FORMAT ( maxdate, "dd-mmm-yy" )
			
			```
		lineageTag: 92bc6fd6-8e74-4a79-a411-f335f119492a

	measure 'Security Description (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Security Description], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: fb13ea9c-7b70-43a2-8d6e-c9f106f180e3

	measure '# Trans Src ID' = COUNT ( 'Securities Transaction GA Fact'[Source ID] )
		formatString: #,0
		lineageTag: b999f91c-0c34-4f5a-bef5-df95b7921745

	measure 'Reporting Currency (Security Transaction)' = ```
			
			VAR SelectedCurrency =
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] )
			VAR ReportingCurrency =
			    IF (
			        NOT ISEMPTY ( 'Securities Transaction GA Fact' ),
			        IF (
			            SelectedCurrency = "Company",
			            FIRSTNONBLANK ( 'Securities Transaction GA Fact'[Functional Ccy Code], TRUE () ),
			            IF (
			                SelectedCurrency = "SCD Base",
			                FIRSTNONBLANK ( 'Securities Transaction GA Fact'[Base], TRUE () ),
			                SelectedCurrency
			            )
			        )
			    )
			RETURN
			    ReportingCurrency
			
			```
		lineageTag: 1bb67709-32da-4e82-82c2-fbef76edb227

	measure 'Rep Rate (Security Transaction)' = ```
			
			VAR maxd =
			    MAX ( 'Period'[Period] )
			VAR fxrate =
			    SWITCH (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			        "USD",
			            CALCULATE (
			                MIN ( 'Securities Transaction GA Fact'[Local To USD Rate] ),
			                FILTER (
			                    'Securities Transaction GA Fact',
			                    'Securities Transaction GA Fact'[As Of Period] = maxd
			                )
			            ),
			        "CAD",
			            CALCULATE (
			                MIN ( 'Securities Transaction GA Fact'[Local To CAD Rate] ),
			                FILTER (
			                    'Securities Transaction GA Fact',
			                    'Securities Transaction GA Fact'[As Of Period] = maxd
			                )
			            ),
			        "HKD",
			            CALCULATE (
			                MIN ( 'Securities Transaction GA Fact'[Local To HKD Rate] ),
			                FILTER (
			                    'Securities Transaction GA Fact',
			                    'Securities Transaction GA Fact'[As Of Period] = maxd
			                )
			            ),
			        "Company",
			            CALCULATE (
			                MIN ( 'Securities Transaction GA Fact'[Local To FUNC Rate] ),
			                FILTER (
			                    'Securities Transaction GA Fact',
			                    'Securities Transaction GA Fact'[As Of Period] = maxd
			                )
			            )
			        ,"SCD Base",
			            CALCULATE (
			                MIN ( 'Securities Transaction GA Fact'[Local Exchange Rate] ),
			                FILTER (
			                    'Securities Transaction GA Fact',
			                    'Securities Transaction GA Fact'[As Of Period] = maxd
			                )
			            )
			    )
			RETURN
			    fxrate
			
			
			```
		formatString: 0.000000
		lineageTag: 82a4ce43-ca73-4525-a849-d95a0309f985

	measure 'Amortized Cost - Rep (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			RETURN
			    CALCULATE (
			        IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Transaction GA Fact'[Amortized Cost - Base] ),
			 SUMX (
			        'Securities Transaction GA Fact',
			        'Securities Transaction GA Fact'[Sec Amortization Cost Local]  * 'Fx Rate DQ'[Rep Rate]
			    )
				),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 400085c1-2a71-49a5-8aef-be07cedf10bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Original Cost - Rep (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			
			RETURN
			    CALCULATE (
			        IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Transaction GA Fact'[Cost Value - Base] ),
			 SUMX (
			        'Securities Transaction GA Fact',
			        'Securities Transaction GA Fact'[Cost Value - Local (D)]  * 'Fx Rate DQ'[Rep Rate]
			    )
				),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: fe06e0db-f5ed-4a56-a3f5-be3369c32594

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Realized Gain/Loss - Rep (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			RETURN
			    CALCULATE (
			        IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Transaction GA Fact'[Realized Gain/Loss - Base] ),
			 SUMX (
			        'Securities Transaction GA Fact',
			        'Securities Transaction GA Fact'[Realized Gain/Loss - Local]  * 'Fx Rate DQ'[Rep Rate]
			    )
				),
			                ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 13058e7e-7953-461a-a477-7bd44a6e47f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Transaction History Title' = ```
			
			VAR maxdate =
			    CALCULATE (
			        MAX ( 'Securities Transaction GA Fact'[Transasofdate] ),
			        ALLEXCEPT (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Transasofdate]
			        )
			    )
			RETURN
			    "Transaction History" & ", "
			        & SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) & ", "
			        & SELECTEDVALUE ( Framework[Framework Display] ) & ", "
			        & FORMAT ( maxdate, "dd-mmm-yy" )
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 952e5478-7e4b-4c0f-ba86-f6c5ed21b7c4

	measure 'Units - Trans Level (TH)' = ```
			
			 
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR calc =
			    CALCULATE(SUMX (
			            SUMMARIZE ('Securities Transaction GA Fact',
			'Securities Transaction GA Fact'[Company Code & Name Display],
			'Securities Transaction GA Fact'[Accounting Unit Code & Name Display],
			'Securities Transaction GA Fact'[Portfolio Code & Name],
			'Securities Transaction GA Fact'[Trans Type],
			'Securities Transaction GA Fact'[Primary Security ID (Sec Tran)],
			'Securities Transaction GA Fact'[Transaction No],
			                "test-sum",
			                    
			                           CALCULATE (
			        AVERAGE('Securities Transaction GA Fact'[Units]),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			                    
			            ),
			        [test-sum]
			    ),ALL ( 'Period' ))
			RETURN
			    calc
			
			```
		formatString: #,0.000
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 55a2db18-11c0-4680-887f-15a3e642eb2a

	measure 'Asset Type (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Asset Type], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: b28124ec-ca98-4d4b-bcb7-2aa541901865

	measure 'Factor (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Factor], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: e7f15d2a-7ee7-471d-9861-3f324019c591

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Isin (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Isin], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: bd03b4ca-ee71-463b-968e-a29a9f624172

	measure 'Local ID (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Local ID], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 50b3a661-f4c5-408d-9948-8d7a5c99b171

	measure 'ML IFRS 13 Level (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML IFRS 13 Level], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: c2e28f5e-54f8-451f-9b78-558295e198d7

	measure 'Sector (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Sector], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 5dc78e0d-f199-4464-81d1-0b383e2e3e38

	measure 'Book Value - Rep (Sec Trans)' = [Book Value - Trans rep (Sec Trans)] + [Book Value - Adjustment Rep (Sec Trans)]
		displayFolder: SCD Transactions + CAT Adjustments
		lineageTag: 36880490-0b5d-4175-a6ae-08ecb2ce6997

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Amortization/Accretion - Rep (Sec Trans)' = [Amortization/Accretion - Trans Rep (Sec Trans)]+[Amortization/Accretion - Adjustment Rep (Sec Trans)]
		displayFolder: SCD Transactions + CAT Adjustments
		lineageTag: 8f1d5243-38b7-49d1-b63f-6581528542bc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OID Amortization/Accretion - Rep (Sec Trans)' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			    SUM ( 'Securities Transaction GA Fact'[OID Int Appr - Base] ),
			    
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[OID Int Appr - Local] * 'Fx Rate DQ'[Rep Rate]
			        )
			)
			/*
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Transaction GA Fact'[OID Int Appr - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Transaction GA Fact'[OID Int Appr - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Transaction GA Fact'[OID Int Appr - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Transaction GA Fact'[OID Int Appr - FUNC] ),
							SUM ( 'Securities Transaction GA Fact'[OID Int Appr - HKD] )
							)
						)
					)
				)
			*/
			
			```
		lineageTag: dc5e8f3e-7497-49f2-9b8b-c283c4026aa8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTTI Impairment - Rep (Sec Trans)' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			        
			        SUM ( 'Securities Transaction GA Fact'[Impairment - Base] ),
			           
			 
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Impairment - Local] * 'Fx Rate DQ'[Rep Rate]
			        )
			    )
			/*
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Transaction GA Fact'[Impairment - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Transaction GA Fact'[Impairment - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Transaction GA Fact'[Impairment - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Transaction GA Fact'[Impairment - FUNC] ),
							SUM ( 'Securities Transaction GA Fact'[Impairment - HKD] )
							)
						)
					)
				)
			    */
			
			```
		lineageTag: e5089b9b-d433-4f5b-a511-d1baf30a1f14

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Change AOCI BV - Rep' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			       
			        SUM ( 'Securities Transaction GA Fact'[Change AOCI BV - Base] ),
			           
			    
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Change AOCI BV - Local] * 'Fx Rate DQ'[Rep Rate]
			        )
			)
			/*
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Transaction GA Fact'[Change AOCI BV - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Transaction GA Fact'[Change AOCI BV - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Transaction GA Fact'[Change AOCI BV - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Transaction GA Fact'[Change AOCI BV - FUNC] ),
							SUM ( 'Securities Transaction GA Fact'[Change AOCI BV - HKD] )
							)
						)
					)
				)
			*/
			```
		lineageTag: 947dbd86-0017-4aed-b339-4edd6b99705b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Deferred PL - Rep (Sec Trans)' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			       
			        SUM ( 'Securities Transaction GA Fact'[Deferred PL - Base] ),
			            
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Deferred PL - Local] * 'Fx Rate DQ'[Rep Rate]
			        )
			)
			/*
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Transaction GA Fact'[Deferred PL - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Transaction GA Fact'[Deferred PL - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Transaction GA Fact'[Deferred PL - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Transaction GA Fact'[Deferred PL - FUNC] ),
							SUM ( 'Securities Transaction GA Fact'[Deferred PL - HKD] )
							)
						)
					)
				)
			*/
			
			```
		lineageTag: 30cef575-bd83-4408-876b-868e6e38391b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Realized Gain/Loss Book - Rep (Sec Trans)' = [Realized Gain/Loss Book - Trans Rep (Sec Trans)]+[Realized Gain/Loss - Adjustment Rep (Sec Trans)]
		displayFolder: SCD Transactions + CAT Adjustments
		lineageTag: e7777796-84f9-42fe-ae9a-9e5005ed4464

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income Gross Amount - Rep (Sec Trans)' = [Income Gross Amount - Trans Rep (Sec Trans)]+[Income Gross Amount - Adjustment Rep (Sec Trans)]
		displayFolder: SCD Transactions + CAT Adjustments
		lineageTag: 7b5d8180-e43e-45cd-88ce-94cfb710d4d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cost Value - Rep' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			            
			        SUM ( 'Securities Transaction GA Fact'[Cost Value - Base] ),
			        
			  
			   
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Cost Value - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ))
			/*
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Transaction GA Fact'[Cost Value - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Transaction GA Fact'[Cost Value - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Transaction GA Fact'[Cost Value - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Transaction GA Fact'[Cost Value - FUNC] ),
							SUM ( 'Securities Transaction GA Fact'[Cost Value - HKD] )
							)
						)
					)
				)
			*/
			```
		lineageTag: 4289b7ca-70fe-4f44-92c2-9303732bf9d2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Settle Amount (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			
			VAR calc =
			    CALCULATE(SUMX (
			            SUMMARIZE ('Securities Transaction GA Fact',
			'Securities Transaction GA Fact'[Company Code & Name Display],
			'Securities Transaction GA Fact'[Accounting Unit Code & Name Display],
			'Securities Transaction GA Fact'[Portfolio Code & Name],
			'Securities Transaction GA Fact'[Trans Type],
			'Securities Transaction GA Fact'[Primary Security ID (Sec Tran)],
			'Securities Transaction GA Fact'[Transaction No],
			                "test-sum",
			                    
			                            CALCULATE (
			    AVERAGE ( 'Securities Transaction GA Fact'[Settle Amount (D)] ),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			                    
			            ),
			        [test-sum]
			    ),ALL ( 'Period' ))
			RETURN
			    calc
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: d750d6c6-c301-4dd6-b198-d6eca4614150

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Settle Price (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Settle Price]
			        ),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 2331e484-bcb1-49b0-98ca-80f68ba80862

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Settle (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			        SELECTEDVALUE(
			            'Securities Transaction GA Fact'[Settle Ccy Code]
			        ),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 24f0fba9-2e93-4333-8271-8fbe49d7169f

	measure '#Lots (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			       COUNT('Securities Transaction GA Fact'[Lot ID]),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		formatString: 0
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: e55fd73e-bc71-4ad4-bc5c-89586b541b22

	measure 'Post Date (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			        SELECTEDVALUE('Securities Transaction GA Fact'[Post Date]),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: abc7b536-d1fe-4644-bd54-a5bb8b63dd21

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Settle Date (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			        SELECTEDVALUE('Securities Transaction GA Fact'[Settle Date]),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		formatString: yyyy-mm-dd
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 3d6797cd-340b-48dc-b301-97737485c5c9

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Transaction No (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			        SELECTEDVALUE('Securities Transaction GA Fact'[Transaction No]),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 4a3ba943-efa8-4bb7-9a1a-d29fa40ff0a1

	measure 'Slicer filter (TH)' =
			
			VAR portChange = [Trans Type (TH)]
			VAR slicer =
			    VALUES ( 'Transaction History Slicer'[Trans Type] )
			RETURN
			    SWITCH ( TRUE (), portChange IN slicer, 1, 0 )
		formatString: 0
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 4ea321bc-ad73-45bc-b4e0-69ae899f479b

	measure 'User (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			        SELECTEDVALUE('Securities Transaction GA Fact'[User Name]),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 0eb44bce-e15a-474e-836d-98225770b56d

	measure 'Transaction Yield (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			        SELECTEDVALUE('Securities Transaction GA Fact'[Transaction Yield]),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 0af957db-160c-4c5c-938b-440a6a8efc0e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Local (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			        SUM('Securities Transaction GA Fact'[Book Value - Local (D)]),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: ac4fb0a5-756f-4044-8e98-09ba2b4b2be7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Transaction Amount (Sec Tran)' = ```
			
			VAR test =
			    SUMX (
			        ADDCOLUMNS (
			            SUMMARIZE (
			                'Securities Transaction GA Fact',
			                'Securities Transaction GA Fact'[Transaction No],
			                "test-sum",
			                  
			                            AVERAGE ( 'Securities Transaction GA Fact'[Transaction Amount] )
			            ),
			            "test2", [test-sum]
			        ),
			        [test2]
			    )
			RETURN
			    test
			```
		lineageTag: bc910c0d-9bbf-4764-8081-497e80fb05b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Settle Principal (Tran)' = ```
			
			VAR calc =
			    SUMX (
			        SUMMARIZE (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Company Code & Name Display],
			            'Securities Transaction GA Fact'[Accounting Unit Code & Name Display],
			            'Securities Transaction GA Fact'[Portfolio Code & Name],
			            'Securities Transaction GA Fact'[Trans Type],
			            'Securities Transaction GA Fact'[Primary Security ID (Sec Tran)],
			            'Securities Transaction GA Fact'[Transaction No],
			            "test-sum",AVERAGE ( 'Securities Transaction GA Fact'[Settle Principal] )
			        ),
			        [test-sum]
			    )
			RETURN
			    ROUND(calc,2)
			
			```
		formatString: #,0.00
		lineageTag: e30714c0-354b-4ae9-93f5-ea7c53f22bc0

		changedProperty = FormatString

	measure 'Trans Type (TH)' =
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			        FIRSTNONBLANK ( 'Securities Transaction GA Fact'[Trans Type], TRUE () ),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: a085f707-6e6d-47c1-a8d0-f97ba59e66df

	measure 'Settle Interest (Tran)' = ```
			
			VAR test =
			    SUMX (
			        ADDCOLUMNS (
			            SUMMARIZE (
			                'Securities Transaction GA Fact',
			                'Securities Transaction GA Fact'[Transaction No],
			                "test-sum",AVERAGE ( 'Securities Transaction GA Fact'[Settle Interest] )
			            ),
			            "test2", [test-sum]
			        ),
			        [test2]
			    )
			RETURN
			    test
			
			```
		lineageTag: fbcdeab4-b896-43d6-80de-0f02cd17ab4e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cusip (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Cusip], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 9cd3f862-e20a-4119-99b6-07eafcd309e5

	measure 'Accrual Currency (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Accrual Currency], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: bd49e06a-1a1a-4a60-8b01-21e344022f0e

	measure 'Portfolio Owner (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Portfolio Owner (D)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: dfaadfa7-f706-4049-b207-e7e0998e56d6

	measure 'Portfolio Sleeve Status (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Portfolio Sleeve Status],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 0b30ff14-802c-48df-87ba-fd40f6a1b887

	measure 'Private Portf Ind (Sec Tran)' =
			
			CALCULATE (
			    SUM('Portfolios Attributes'[Private Portf Ind (D)]),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		formatString: 0
		displayFolder: Portfolio Attributes
		lineageTag: f9e677be-85ae-41fe-a6da-bb1b8a5c3fd4

	measure 'Amortization/Accretion Realized - Rep (Sec Trans)' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			      
			                SUM ( 'Securities Transaction GA Fact'[Real Int Appr - Base] ),
			      
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Real Int Appr - Local] * 'Fx Rate DQ'[Rep Rate]
			        )
			)
			/*
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Transaction GA Fact'[Real Int Appr - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Transaction GA Fact'[Real Int Appr - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Transaction GA Fact'[Real Int Appr - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Transaction GA Fact'[Real Int Appr - FUNC] ),
							SUM ( 'Securities Transaction GA Fact'[Real Int Appr - HKD] )
							)
						)
					)
				)
			*/
			```
		lineageTag: 0923761e-470c-4c57-9275-fdecf0945ac2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Maximis Portfolio Number (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Maximis Portfolio Number],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 6e8c88df-c530-4cec-9384-0b79bcbc7d53

	measure 'IAS39 Trading Philosophy Code (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[IAS39 Trading Philosophy Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: d9ba4e8d-215f-4f03-8581-8fae696fc4b3

	measure 'IFRS Trading Philosophy Code (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[IFRS Trading Philosophy Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: abfcea17-f23f-4598-b6bb-3ed0eb21258c

	measure 'Portfolio Name (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Portfolio Name],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: a82bf43c-0ec0-490e-8b1e-9e2b4849d0d0

	measure 'Investment Desk (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Investment Desk (D)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 9846809f-f2b5-4328-8905-fd897336b1bb

	measure 'Portfolio Manager Name (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Portfolio Manager Name (D)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 0919eb54-46c1-418a-a28d-023751b923c1

	measure 'FI Type (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Fi Type], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 2842a818-08ab-48d8-92e2-353d6fcb8f7c

	measure 'Issue Dt (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Issue Dt], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		formatString: yyyy-mm-dd
		displayFolder: Security Values
		lineageTag: 2b3404d7-f9b3-483f-ba24-216db92d47c9

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Transaction Amount (BackPosted)' = SUM ( 'Securities Transaction GA Fact'[Payment Amount - Base] )
		lineageTag: 820ab9be-683b-4c49-80c8-fd9240c467c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Report Portfolio Value' = ```
			
			VAR test =
			    SUMX (
			        ADDCOLUMNS (
			            SUMMARIZE (
			                'Securities Transaction GA Fact',
			                'Securities Transaction GA Fact'[Portfolio Code & Name],
			                "test-sum",
			                AVERAGE ( 'Securities Transaction GA Fact'[Base Portfolio Value] )
			            ),
			            "test2", [test-sum]
			        ),
			        [test2]
			    )
			RETURN
			    test
			
			```
		lineageTag: 64a26d70-45e8-4afe-a06c-446982492990

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Materiality (BPS)' = ```
			
			VAR BPS =
			    IF (
			        [Report Portfolio Value] <> 0,
			        CALCULATE ( DIVIDE ( [Transaction Amount (BackPosted)], [Report Portfolio Value] ) ),
			        BLANK ()
			    )
			RETURN
			    BPS *10000
			
			```
		formatString: 0.000000
		lineageTag: 7f8f0017-2a7f-41f8-8390-1ab17f4a73fe

	measure 'Back-Posted Transactions Title' = ```
			
			VAR maxdate =
			    MAX ( 'Securities Transaction GA Fact'[Transasofdate] )
			VAR mindate =
			    MIN ( 'Securities Transaction GA Fact'[Transasofdate] )
			VAR fw =
			    SELECTEDVALUE ( Framework[Framework Display] )
			VAR Rep =
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) 
			RETURN
			    "Back-Posted Transactions" & ", " & Rep & ", " & fw & ", "
			        & FORMAT ( mindate, "dd-mmm-yy" ) & " - "
			        & FORMAT ( maxdate, "dd-mmm-yy" )
			
			```
		lineageTag: 43a01740-42cf-4f75-be70-a21d7e7ab6ba

	measure 'Client Reporting Required Ind (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Client Reporting Required Ind],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		formatString: 0
		displayFolder: Portfolio Attributes
		lineageTag: d25182ec-f53e-4154-a6b0-cc6e171e874f

	measure 'Unpaid Amount - Local' = ```
			
			VAR calc =
			SUMX (
			        SUMMARIZE (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Portfolio Code & Name],
			            'Securities Transaction GA Fact'[Primary Security ID (Sec Tran)],
			            'Securities Transaction GA Fact'[Transaction No],
			            'Securities Transaction GA Fact'[Unpaid Amount - Local (D)]
			        ),
			        'Securities Transaction GA Fact'[Unpaid Amount - Local (D)]
			    )
			RETURN
			    calc
			
			```
		lineageTag: 7bb7897b-bdc2-4aee-bf3f-dc94eb3d72b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Timestamp (Sec Trans)' = ```
			
			IF (
			    NOT ISEMPTY ( 'Securities Transaction GA Fact' ),
			    NOW (),
			    BLANK ()
			)
			
			```
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		lineageTag: e2778e10-d1a1-4fdf-8620-42f6510c3328

	measure 'Day Count (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Day Count], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 458569d7-71ac-4b9a-8cd8-bc6361abd3bd

	measure 'Maturity Date (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Maturity Date], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		formatString: yyyy-mm-dd
		displayFolder: Security Values
		lineageTag: 0ed9e275-b77f-484d-9911-2559e959bd27

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Inv Lp Port Code (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Inv Lp Port Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: a04cffe8-dc8c-4475-9645-5702bbf1b785

	measure 'Lawson Legal ID (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Lawson Legal ID (D)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: b48f9608-b8e7-4700-a60a-4d57fb9cdfdd

	measure 'Liability Surplus (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Liability Surplus (D)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 2b8a0371-11c8-439b-916e-58f79feb4135

	measure 'Custodian Name (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Custodian Name (D)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: a68aac4b-4b7d-4ac7-bb4a-e25333840b5b

	measure 'Official PPN (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Official PPN], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: b4c9d724-8e98-452a-9d80-a87603edb3f0

	measure 'Coupon (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Coupon], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 4540458e-c111-4d45-a102-95cdb55fb8c2

	measure 'S&P Short Term Rating (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[S&P Short Term Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 092b167e-444f-4649-96b3-ca9c784915fd

	measure 'Moodys Short Term Rating (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Moodys Short Term Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 1d1e2495-d454-42b3-a261-f8b1980a4949

	measure 'Fitch Short Term Rating (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Fitch Short Term Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 29882453-3a7c-452d-a255-eceffd0064fc

	measure 'Dbrs (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Dbrs], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 0fd3b92b-79ad-47ad-8132-da288c0b6b8f

	measure 'Internal (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Internal], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 8b5d4cc5-e8cd-4d8d-89d0-8da91071b603

	measure 'Maturity Days (Sec Tran)' =
			
			VAR mat =
			    CALCULATE (
			        FIRSTNONBLANK ( 'Securities'[Maturity Days (D)], TRUE () ),
			        CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			    )
			VAR calc =
			    IF ( mat < 0, mat * -1, mat )
			RETURN
			    calc
		formatString: 0
		displayFolder: Security Values
		lineageTag: d99fd85e-3718-4bae-b497-bb59134f439a

	measure 'Realized Gain/Loss - Rep (Sec Trans)' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			        
			            SUMX(
			                SUMMARIZE(
			                    'Securities Transaction GA Fact',
			                    'Securities Transaction GA Fact'[Bus Trans Number],
			                    'Securities Transaction GA Fact'[Realized Gain/Loss - Base]
			                ),
			                'Securities Transaction GA Fact'[Realized Gain/Loss - Base]
			            )
			    ,
			    SUMX(
			        SUMMARIZE(
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Bus Trans Number],
			            'Securities Transaction GA Fact'[Realized Gain/Loss - Local],
			            "@Rep Rate",[Rep Rate]
			        ),
			        'Securities Transaction GA Fact'[Realized Gain/Loss - Local]* [@Rep Rate]
			    )
			)
			
			/*
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Transaction GA Fact'[Realized Gain/Loss - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Transaction GA Fact'[Realized Gain/Loss - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Transaction GA Fact'[Realized Gain/Loss - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Transaction GA Fact'[Realized Gain/Loss - FUNC] ),
							SUM ( 'Securities Transaction GA Fact'[Realized Gain/Loss - HKD] )
							)
						)
					)
				)
			*/
			
			```
		lineageTag: 76302c47-c777-4d46-b067-f97590444a53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sedol (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Sedol], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 184065f9-8675-4e5d-967a-10be7e098574

	measure 'Legal Entity (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Portfolios Attributes'[Lawson Legal ID (D)], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 8f46eeb6-d229-4bcd-a655-f394d52ebe18

	measure 'Segment (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Portfolios Attributes'[Lawson Segment Name], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: e818f9f6-c2fa-44dd-b379-f3b47ed30401

	measure 'Security Transfers Title' = ```
			
			VAR maxdate =
			    MAX ( 'Securities Transaction GA Fact'[Transasofdate] )
			VAR mindate =
			    MIN ( 'Securities Transaction GA Fact'[Transasofdate] )
			VAR fw =
			    SELECTEDVALUE ( Framework[Framework Display] )
			VAR Rep =
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] )
			RETURN
			    "Security Transfers" & ", " & Rep & ", " & fw & ", "
			        & FORMAT ( mindate, "dd-mmm-yy" ) & " - "
			        & FORMAT ( maxdate, "dd-mmm-yy" )
			
			```
		lineageTag: 43da29df-8e75-40e2-bdf5-4dbad213fb20

	measure 'JGAAP Trading Philosophy Code (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[JGAAP Trading Philosophy Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 7d037a12-a042-4544-91fe-6caf2c341eb9

	measure 'S&P (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[S&P], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: c24fb872-c635-40fa-a279-a0474bce9c34

	measure 'Issuer (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Issuer], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: a861513e-074d-4c27-946a-4b7440030973

	measure 'AOCI Amortized - Rep (STH)' = ```
			
			VAR closePerd =
			    MAX ( 'Period'[Date] )
			
			VAR CALC = 
			    CALCULATE (
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
			            SUM ( 'Securities Transaction AOCI GA Fact'[Sublot Amort AOCI - Local] ),
			            SUMX( 'Securities Transaction AOCI GA Fact','Securities Transaction AOCI GA Fact'[Sublot Amort AOCI - Local]* 'Fx Rate DQ'[Rep Rate])
			--SUM('Securities Transaction GA Fact'[Sublot Amort AOCI - CAD])
			),
			        ALL('Period'), 'Securities Transaction AOCI GA Fact'[Transasofdate] <= closePerd 
			    )
			RETURN CALC
			```
		displayFolder: Sublot Rollforward Attributes
		lineageTag: 55fff6af-0bcc-4900-8328-511521590cf3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Amortized - Local (STH)' = ```
			
			VAR closePerd =
			    max('Period'[Date])
			RETURN
			 
			  CALCULATE (
			        SUM ('Securities Transaction AOCI GA Fact'[Sublot Amort AOCI - Local] ),
			          ALL('Period'),'Securities Transaction AOCI GA Fact'[Transasofdate] <= closePerd)
			   
			```
		displayFolder: Sublot Rollforward Attributes
		lineageTag: 8dce1a46-8fc0-48d2-b6ea-f4e698915bd1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Original - Rep (STH)' = ```
			
			VAR closePerd =
			    MAX ( 'Period'[Date] )
			RETURN
			
			    CALCULATE (
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
			            SUM ( 'Securities Transaction AOCI GA Fact'[Sublot AOCI - Base] ),
			SUMX('Securities Transaction AOCI GA Fact','Securities Transaction AOCI GA Fact'[Sublot AOCI - Local]* 'Fx Rate DQ'[Rep Rate])
			        ),
			        All('Period'), 'Securities Transaction AOCI GA Fact'[Transasofdate] <= closePerd 
			    )
			```
		displayFolder: Sublot Rollforward Attributes
		lineageTag: 52f2b129-5fd8-46c6-9c30-8a41cd5172a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Original - Local (STH)' =
			
			VAR closePerd =
			    MAX ( 'Period'[Date] )
			RETURN
			
			CALCULATE (
			        SUM ( 'Securities Transaction AOCI GA Fact'[Sublot AOCI - Local] ),
			        All('Period'), 'Securities Transaction AOCI GA Fact'[Transasofdate] <= closePerd )
		displayFolder: Sublot Rollforward Attributes
		lineageTag: 3bfe71f9-4c85-43ab-9528-f791ba4b98a3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Infor Acquisition Rate (Sec Trans)' = ```
			
			VAR Amt =SUM ( 'Securities Transaction GA Fact'[Cost Value - Local unsigned] )
			VAR local =
			    IF ( Amt = 0, 1, Amt )
			RETURN
			    SWITCH (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			        "SCD Base",
			        SUM ( 'Securities Transaction GA Fact'[Cost Value - Base unsigned] ) / local,    
			        SUMX (
			                'Securities Transaction GA Fact',
			                'Securities Transaction GA Fact'[Cost Value - Local unsigned] * 'Fx Rate DQ'[Rep Rate] / Local
			            )
			    )
			
			/*
			var local =  if(SUM ( 'Securities Transaction GA Fact'[Cost Value - Local] )=0,1,SUM ( 'Securities Transaction GA Fact'[Cost Value - Local] ))
			Return
			IF (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
			        SUM ( 'Securities Transaction GA Fact'[Cost Value - Base] )/local,
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			            SUM ( 'Securities Transaction GA Fact'[Cost Value - USD] )/local,
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			                SUM ( 'Securities Transaction GA Fact'[Cost Value - CAD] )/local,
			
			            IF (
			                SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
			                    SUM ( 'Securities Transaction GA Fact'[Cost Value - FUNC] )/local,
			                    SUM ( 'Securities Transaction GA Fact'[Cost Value - HKD] )/local
			                )
			            )
			        )
			    )
			    */
			```
		formatString: 0.000000
		lineageTag: 36a7a52e-19a4-473f-b7fc-b5bc4b962a65

	measure 'USGAAP Trading Philosophy Code (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[USGAAP Trading Philosophy Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 35c43c57-4d81-4dfd-8de9-c0c5f41c1c61

	measure 'Coupon Type (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Coupon Type], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 2c8ae5aa-0f2f-44a0-b16d-e56aef1e9856

	measure 'ML MFC Equivalent Rating (Sec Trans)' =
			
			CALCULATE(
			    FIRSTNONBLANK(Securities[ML MFC Equivalent Rtg],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 9bd40eec-2395-46d0-ae74-cca6431f4b4e

	measure 'Schedule BA Asset Category Code (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Schedule BA Asset Category Code], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 4d966ddf-c8d6-4806-8b43-4771571bb643

	measure 'Primary Asset Type (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Primary Asset Type], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 66da5cba-b54e-4ece-9248-d28b09bf2747

	measure 'PM City (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Sleeve Manager City],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 56762d6f-5c49-4c8e-9ae8-195774790de9

	measure 'Portfolio Valuation Date (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[As of Date (D)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		formatString: yyyy-mm-dd
		displayFolder: Portfolio Attributes
		lineageTag: b11136fc-cfb0-4210-9a6c-610b652b5feb

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Settle Amount By Portfolio' = ```
			
			VAR fw =
			    SELECTEDVALUE ( Framework[Framework] )
			VAR Op =
			    CALCULATE (
			       
			            SUM ( 'Securities Transaction GA Fact'[Settle Amount (D)] ),
			        ALLEXCEPT (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Company Code & Name Display],
			            'Securities Transaction GA Fact'[Accounting Unit Code & Name Display],
			            'Securities Transaction GA Fact'[Portfolio Code & Name]
			        ),
			        'Securities Transaction GA Fact'[Framework Code] = fw
			    )
			RETURN
			    Op
			
			```
		lineageTag: c655c4bb-9397-44e8-b739-060ade9ebe1e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Settle Amount By Security' = ```
			
			VAR fw =
			    SELECTEDVALUE ( Framework[Framework] )
			VAR Op =
			    CALCULATE (
			     
			        SUM ( 'Securities Transaction GA Fact'[Settle Amount (D)] ),
			        ALLEXCEPT (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Company Code & Name Display],
			            'Securities Transaction GA Fact'[Accounting Unit Code & Name Display],
			            'Securities Transaction GA Fact'[Portfolio Code & Name],
			            'Securities Transaction GA Fact'[Primary Security ID & Desc (Sec Tran)]
			        ),
			        'Securities Transaction GA Fact'[Framework Code] = fw
			    )
			RETURN
			    Op
			
			```
		lineageTag: 804fcf1e-38fa-4da6-aa08-8b8d88d80a84

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Materiality (BPS at Portfolio)' = ```
			
			VAR BPS =
			    IF (
			        [Report Portfolio Value] <> 0,
			        CALCULATE ( DIVIDE ( [Settle Amount By Portfolio], [Report Portfolio Value] ) ),
			        BLANK ()
			    )
			RETURN
			    BPS 
			
			```
		formatString: 0.000000
		lineageTag: 02a3f2ac-2536-47e1-9fc6-615e256503b9

	measure 'Materiality (BPS at Security)' = ```
			
			VAR BPS =
			    IF (
			        [Report Portfolio Value] <> 0,
			        CALCULATE ( DIVIDE ( [Settle Amount By Security], [Report Portfolio Value] ) ),
			        BLANK ()
			    )
			RETURN
			    BPS 
			
			```
		formatString: 0.000000
		lineageTag: 3a585a91-832b-4e1c-bf71-612cf07049fc

	measure 'Ticker (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Ticker], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 1e4bf2a0-8c60-4710-a3cc-8e783d71a347

	measure 'FindurId - Slicer Sync Filter (STH)' = ```
			
			VAR closePerd =  MAX('Period'[Period])
			var sublot_aoci = SELECTEDVALUE('Securities Sublot Fact'[AOCI Hedge Findur ID])
			var trans_aoci =
			CALCULATE( FIRSTNONBLANK('Securities Transaction GA Fact'[AOCI Hedge Findur ID],TRUE()),
			All('Period'), 'Securities Transaction GA Fact'[As of Period] <= closePerd
			    )
			var calc = 
			
			if(sublot_aoci =trans_aoci || sublot_aoci = BLANK(),1,0)
			return calc
			```
		formatString: 0
		displayFolder: Sublot Rollforward Attributes
		lineageTag: 2a6ff253-a5f3-48e0-a669-d6de77f9eed7

	measure 'AOCI Hedge Findur ID Trans (STH)' =
			
			VAR closePerd =
			    max('Period'[Period])
			RETURN
			
			    CALCULATE (
			        COUNT('Securities Transaction GA Fact'[AOCI Hedge Findur ID]),
			         All('Period'), 'Securities Transaction GA Fact'[As of Period] <= closePerd
			    )
		formatString: 0
		displayFolder: Sublot Rollforward Attributes
		lineageTag: bd28efc2-2b47-417b-94f3-695d91c80528

	measure 'Sublot Transaction History Title' =
			
			VAR maxdate =
			    CALCULATE (
			        MAX ( 'Securities Transaction GA Fact'[Transasofdate] ),
			        ALLEXCEPT (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Transasofdate]
			        )
			    )
			RETURN
			    "Sublot Transaction History" & ", "
			        & SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) & ", "
			        & SELECTEDVALUE ( Framework[Framework Display] ) & ", "
			        & FORMAT ( maxdate, "dd-mmm-yy" )
		displayFolder: Sublot Rollforward Attributes
		lineageTag: 0ed0aa7b-3ae3-45eb-ba23-ff36e76fc18e

	measure 'AOCI Remaining - Local (STH)' =
			
			[AOCI Original - Local (STH)] - [AOCI Amortized - Local (STH)]
		displayFolder: Sublot Rollforward Attributes
		lineageTag: efc45e23-912d-4c65-ba6a-142c32e9f8d1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Remaining - Rep (STH)' = [AOCI Original - Rep (STH)] - [AOCI Amortized - Rep (STH)]
		displayFolder: Sublot Rollforward Attributes
		lineageTag: b6457f03-a826-48a7-98fd-be02732b1aa6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NAIC Designation (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[NAIC Designation], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 19e72cb0-5570-4896-8e90-1a53b361dfa9

	measure 'NAIC Rating (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[NAIC Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		formatString: 0
		displayFolder: Security Values
		lineageTag: 7f18d14d-62d3-49d2-a669-f2b1cb78a5b4

	measure 'Units - Trans Level' = ```
			
			SUMX (
			    SUMMARIZE (
			        'Securities Transaction GA Fact',
			        'Securities Transaction GA Fact'[Company Code & Name Display],
			        'Securities Transaction GA Fact'[Accounting Unit Code & Name Display],
			        'Securities Transaction GA Fact'[Portfolio Code & Name],
			        'Securities Transaction GA Fact'[Trans Type],
			        'Securities Transaction GA Fact'[Primary Security ID (Sec Tran)],
			        'Securities Transaction GA Fact'[Transaction No],
			        "test-sum",AVERAGE ( 'Securities Transaction GA Fact'[Units] )
			    ),
			    [test-sum]
			)
			
			/*
			VAR calc =
			    SUMX (
			            SUMMARIZE ('Securities Transaction GA Fact',
			'Securities Transaction GA Fact'[Company Code & Name Display],
			'Securities Transaction GA Fact'[Accounting Unit Code & Name Display],
			'Securities Transaction GA Fact'[Portfolio Code & Name],
			'Securities Transaction GA Fact'[Trans Type],
			'Securities Transaction GA Fact'[Primary Security ID (Sec Tran)],
			'Securities Transaction GA Fact'[Transaction No],
			                "test-sum",
			                    
			                        AVERAGE ( 'Securities Transaction GA Fact'[Units] )
			                    
			            ),
			        [test-sum]
			    )
			RETURN
			    calc*/
			```
		lineageTag: 0688978f-5e14-4664-ba95-f34c6c7e9928

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Settle Amount - Trans level' =
			
			VAR calc =
			SUMX (
			        SUMMARIZE (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Company Code & Name Display],
			            'Securities Transaction GA Fact'[Accounting Unit Code & Name Display],
			            'Securities Transaction GA Fact'[Portfolio Code & Name],
			            'Securities Transaction GA Fact'[Trans Type],
			            'Securities Transaction GA Fact'[Primary Security ID (Sec Tran)],
			            'Securities Transaction GA Fact'[Transaction No],
			            'Securities Transaction GA Fact'[Settle Amount (D)]
			        ),
			        'Securities Transaction GA Fact'[Settle Amount (D)]
			    )
			RETURN
			    calc
		lineageTag: 15721bc3-5192-44be-a581-528469867906

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Price - Local (Sec Tran)' = AVERAGE ( 'Securities Transaction GA Fact'[Price - Local (D)] )
		lineageTag: 70cec9dd-413e-42fa-9d1f-e438daad9cc2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Settle Amount' = SUM ( 'Securities Transaction GA Fact'[Settle Amount (D)] )
		isHidden
		lineageTag: 65143e34-b466-41eb-adcb-fc0663aabd6d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Base Interest' = SUM ( 'Securities Transaction GA Fact'[Interest - Base] )
		lineageTag: d85c82df-48ce-4559-9b3e-c4f955e7ec9a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Units - Lots Level' = SUM ( 'Securities Transaction GA Fact'[Lot Nominal] )
		isHidden
		lineageTag: 9950d7a7-19a3-4de3-8751-aa1241547d36

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rep Rate (Sec Trans)' = AVERAGEX( 'Securities Transaction GA Fact', 1 * 'Fx Rate DQ'[Rep Rate])
		formatString: 0.000000
		lineageTag: 55097e2a-4d02-4107-af92-22745e6b670e

	measure 'Units - Lot Level (TH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			        SUM('Securities Transaction GA Fact'[Lot Nominal]),
			        ALL ( 'Period' ),
			        'Securities Transaction GA Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 954e6b94-67f6-4d14-a0da-d22d25de3619

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Trade Date TH' = CALCULATE(SELECTEDVALUE('Securities Transaction GA Fact'[Trade Date]), ALL(Period))
		formatString: yyyy-mm-dd
		isHidden
		lineageTag: 4caf19f2-f619-4f84-9010-69e821917e2a

		changedProperty = IsHidden

	measure 'Book Value - Local (Sec Trans)' = [Book Value - Trans Local (Sec Trans)] + [Book Value - Adjustment Local (Sec Trans)]
		displayFolder: SCD Transactions + CAT Adjustments
		lineageTag: 3a7bc8c9-4101-4a01-be9c-7e1a2a55232d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cost Value - Local' = SUM ( 'Securities Transaction GA Fact'[Cost Value - Local (D)] )
		lineageTag: 46d1acef-ec87-42ee-bec6-00a4fccaed4e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Asset Portfolio Code (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Asset Portfolio Code],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: ea2d69ae-aef4-4b36-a892-c3c091446289

	measure 'ML Private Asset ID (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Private Asset ID], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: ea5950f8-e5c8-436e-9e60-11249fd0b458

	measure 'ML Private/Public Asset ID (Sec Tran)' = ```
			
			var priv = CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Private Asset ID], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			        )
			
			var pub = CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Primary Security ID], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			        )
			
			return
			COALESCE(priv,pub)
			
			```
		displayFolder: Security Values
		lineageTag: 5afb4568-dd9e-40f4-b1be-8107df2e510d

	measure 'Coupon Frequency (Sec Tran)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Coupon Frequency], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 0febe173-88ca-411f-a5d4-6431714da4da

	measure '144A Flag (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[144A Flag], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 21fea4b8-ca5c-4ec8-845f-8eca3d3b69fd

	measure 'Custodian (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Custodian (D)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		lineageTag: b53377fa-8899-4810-8067-227575a3cbef

	measure 'OTTI Impairment - Local (Sec Tran)' = SUM('Securities Transaction GA Fact'[Impairment - Local])
		lineageTag: 85965986-6396-4df5-86eb-9fe3c6f8d359

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lot Level Unit' = ```
			SUM ( 'Securities Transaction GA Fact'[Nominal To Match])
			           
			
			```
		lineageTag: 27c281c0-172f-4da4-8b20-2c20f597a995

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MRM Industry Group Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Industry Group Name], TRUE () ),
			    'Securities Transaction GA Fact'
			)
		lineageTag: 7ed53789-e9e0-4eae-ae9e-7b942f7dc117

	measure 'MRM Industry Sector Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Industry Sector Name], TRUE () ),
			    'Securities Transaction GA Fact'
			)
		lineageTag: 26008709-3d2c-4938-89c2-19de60f09630

	measure 'MRM Industry Subgroup Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Industry Subgroup Name], TRUE () ),
			    'Securities Transaction GA Fact'
			)
		lineageTag: 7fcd1a57-5dfe-482a-9521-338c4b531968

	measure 'MRM Sector Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Sector Name], TRUE () ),
			    'Securities Transaction GA Fact'
			)
		lineageTag: f4011ce7-831c-4c9d-99ea-5752814e4032

	measure 'Is PublicPP Ind (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[Is PublicPP Ind], TRUE () ),
			    'Securities Transaction GA Fact'
			)
		lineageTag: bac36d3f-0923-47d9-ac66-cc92dd30af58

	measure 'Deposit Rate (Sec Trans)' =
			
			CALCULATE (
			    Sum( Securities[SCD Deposit Rate]),
			    'Securities Transaction GA Fact'
			)
		lineageTag: 7bda29c0-1bc8-4e83-a1ce-a8fc2c9d3181

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Realized Gain/Loss – Local(Sec Trans)' = ```
			
			SUMX(
			    SUMMARIZE(
			        'Securities Transaction GA Fact',
			        'Securities Transaction GA Fact'[Bus Trans Number],
			        'Securities Transaction GA Fact'[Realized Gain/Loss - Local]
			    ),
			    'Securities Transaction GA Fact'[Realized Gain/Loss - Local]
			)
			
			```
		lineageTag: d4a82396-bed9-4e3f-b733-3b24a97f76fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NAIC Initial SVO Rating' = ```
			
			VAR vMatchSourceTransID=SELECTEDVALUE('Securities Transaction GA Fact'[Match Src Transaction ID])
			VAR vTradeDate = 
			IF(
			    COUNTROWS('Securities Transaction GA Fact')>0,
			    CALCULATE(
			        MAX('Securities Transaction GA Fact'[Trade Date]),
			        'Securities Transaction GA Fact'[Source ID]=vMatchSourceTransID,
			        REMOVEFILTERS('Securities Transaction GA Fact')
			    )
			)
			VAR vSecurityNK =  SELECTEDVALUE('Securities Transaction GA Fact'[Security NK])
			VAR vSrcSecurityIDMarketID = IF(LEN(vSecurityNK)>0,LEFT(vSecurityNK,LEN(vSecurityNK)-12))
			VAR vLatestSecurityAsOfDate = 
			IF(
			    COUNTROWS('Securities Transaction GA Fact')>0,
			    CALCULATE(
			        MAX('Securities'[As Of Dt]),
			        Securities[Src Security ID]&"/"&Securities[Src Market ID]&"/"=vSrcSecurityIDMarketID,
			        Securities[As Of Dt]<=vTradeDate,
			        REMOVEFILTERS(Securities)
			    )
			)
			
			RETURN
			IF(
			    COUNTROWS('Securities Transaction GA Fact')>0,
			    IF(
			        ISINSCOPE('Securities Transaction GA Fact'[Transaction No]),
			        CALCULATE(
			            SELECTEDVALUE(Securities[NAIC Rating]),
			            Securities[Security NK]=vSrcSecurityIDMarketID&FORMAT(vLatestSecurityAsOfDate,"YYYYMMDD")&"/SCD"
			        )
			    )
			)
			
			
			```
		formatString: 0
		lineageTag: 34de1575-d198-4796-9b4e-5d43a70086f4

	measure 'NAIC Final SVO Rating' = ```
			
			VAR vTradeDate = SELECTEDVALUE('Securities Transaction GA Fact'[Trade Date])
			VAR vSecurityNK =  SELECTEDVALUE('Securities Transaction GA Fact'[Security NK])
			VAR vSrcSecurityIDMarketID = IF(LEN(vSecurityNK)>0,LEFT(vSecurityNK,LEN(vSecurityNK)-12))
			VAR vLatestSecurityAsOfDate = 
			IF(
			    COUNTROWS('Securities Transaction GA Fact')>0,
			    CALCULATE(
			        MAX('Securities'[As Of Dt]),
			        Securities[Src Security ID]&"/"&Securities[Src Market ID]&"/"=vSrcSecurityIDMarketID,
			        Securities[As Of Dt]<=vTradeDate,
			        REMOVEFILTERS(Securities)
			    )
			)
			
			RETURN 
			IF(
			    COUNTROWS('Securities Transaction GA Fact')>0,
			    IF(  
			        ISINSCOPE('Securities Transaction GA Fact'[Transaction No]),
			        CALCULATE(
			            SELECTEDVALUE(Securities[NAIC Rating]),
			            Securities[Security NK]=vSrcSecurityIDMarketID&FORMAT(vLatestSecurityAsOfDate,"YYYYMMDD")&"/SCD"
			        )
			    )
			)
			```
		formatString: 0
		lineageTag: 69106b21-4f86-4f80-89c2-4aafa5799548

	measure 'Wash Sale Parent Security Id(Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Wash Sale Parent Security Id], TRUE () ),
			    CROSSFILTER ( 'Securities transaction Ga Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 08ba4eeb-2a2d-4599-a022-3f6b12e837e0

	measure 'Real Amortisation - Rep (Sec Trans)' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			        SUM ( 'Securities Transaction GA Fact'[Real Amortisation Base] ),
			  
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Real Amortisation Local] * 'Fx Rate DQ'[Rep Rate]
			        )
			)
			```
		lineageTag: 3f3ab391-80cc-427f-9614-2a4f58d73231

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Real Int Appr - Rep (Sec Trans)' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			        SUM ( 'Securities Transaction GA Fact'[Real Int Appr - Base] ),
			  
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Real Int Appr - Local] * 'Fx Rate DQ'[Rep Rate]
			        )
			)
			```
		lineageTag: 075d9cd5-4ec8-460e-8eba-021f6cefe919

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Endorsement Indicator (Sec Trans)' =
			calculate(FIRSTNONBLANK('Securities'[Endorsement Indicator],TRUE ()),
			CROSSFILTER ('Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 55ecad33-c4f7-4af5-b489-d3cde014c4e3

	measure 'ML IRR Rating (Sec Trans)' = ```
			CALCULATE(
			    FIRSTNONBLANK(Securities[ML IRR Rating (Adj)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH ))	
			```
		displayFolder: Security Values
		lineageTag: 5f2b44e7-80d2-4eeb-81d5-220cb163cdb0

	measure 'Private Placement (Sec Trans)' =
			CALCULATE(
			    FIRSTNONBLANK(Securities[Private Placement (Adj)],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH ))
		displayFolder: Security Values
		lineageTag: be17872f-c0e2-4c06-bd77-597c49e8dd08

		changedProperty = IsHidden

	measure 'ML LICAT Inferred Rating (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML LICAT Inferred Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 08e229e4-c635-413e-81bb-204eb960c56c

	measure 'Settle Amount - Rep (Sec Trans)' =
			
			VAR calc =
			SUMX (
			        SUMMARIZE (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Company Code & Name Display],
			            'Securities Transaction GA Fact'[Accounting Unit Code & Name Display],
			            'Securities Transaction GA Fact'[Portfolio Code & Name],
			            'Securities Transaction GA Fact'[Trans Type],
			            'Securities Transaction GA Fact'[Primary Security ID (Sec Tran)],
			            'Securities Transaction GA Fact'[Transaction No],
			            'Securities Transaction GA Fact'[Settle Amount (D)],
			            'Fx Rate DQ'[FX Join Key]
			        ),
			        'Securities Transaction GA Fact'[Settle Amount (D)] *[Rep Rate]
			    )
			RETURN
			    calc
		lineageTag: 6f1bd684-ec1a-41d3-ac74-781ba61dc688

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Settle Principal - Rep (Sec Trans)' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			        MAX ( 'Securities Transaction GA Fact'[Settle Principal] ),
			  
			        MAXX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Settle Principal] * 'Fx Rate DQ'[Rep Rate]
			        )
			)
			```
		lineageTag: 6a6dc0e2-be00-47c7-b907-4ed2821e29b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Issuer Country Cd (Sec Trans)' =
			
			CALCULATE (
			 FIRSTNONBLANK ( 'Securities'[Issuer Country Cd], TRUE () ),
			 CROSSFILTER ( 'Securities'[Security NK],'Securities Transaction GA Fact'[Security NK], BOTH ))
		lineageTag: 43421676-1744-4e42-8e4c-42a828cabad7

	measure 'Unreal OID Accretion - Local (Sec Trans)' = SUM('Securities Transaction GA Fact'[Unreal OID Accretion -  Local])
		lineageTag: 2feb366f-cf7e-45d5-b241-65f57c38a544

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unreal OID Accretion - Rep (Sec Trans)' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			        SUM ( 'Securities Transaction GA Fact'[Unreal OID Accretion - Base] ),
			  
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Unreal OID Accretion -  Local] * 'Fx Rate DQ'[Rep Rate]
			        )
			)
			```
		lineageTag: 4b0310ed-4011-4dbe-8b84-4b7038e43761

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Amortized Cost - Rep (Sec Trans)' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			        VAR vSummarizeTable = 
			        SUMMARIZE(
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Functional Ccy Code],
			            'Securities Transaction GA Fact'[Base],
			            'Securities Transaction GA Fact'[As Of Period],
			            'Securities Transaction GA Fact'[FX Join Key]
			        )
			        VAR vSummarizeTableWithFXRate =
			        ADDCOLUMNS(
			            vSummarizeTable,
			            "@AmortizedCostLocal",
			            CALCULATE(
			                SUM('Securities Transaction GA Fact'[Amortized Cost Local])
			            ),
			            "@LocalToFuncFXRate",
			            VAR vLocalToFuncFXJoinKey = 'Securities Transaction GA Fact'[FX Join Key]
			            RETURN
			            CALCULATE(
			                MAX('Fx Rate DQ'[Func BS Rate]),
			                'Fx Rate DQ'[FX Join Key]=vLocalToFuncFXJoinKey,
			                ALL('Fx Rate DQ')
			            ),
			        
			            "@FuncToBaseFXRate",
			            VAR FuncToBaseFXJoinKey = 'Securities Transaction GA Fact'[Functional Ccy Code]&"/"&'Securities Transaction GA Fact'[Base]&"/"&'Securities Transaction GA Fact'[As Of Period]
			            RETURN
			            CALCULATE(
			                MAX('Fx Rate DQ'[Func BS Rate]),
			                'Fx Rate DQ'[FX Join Key]=FuncToBaseFXJoinKey,
			                ALL('Fx Rate DQ')
			            )
			        )
			        RETURN
			        SUMX(
			            vSummarizeTableWithFXRate,
			            [@AmortizedCostLocal]*[@LocalToFuncFXRate]*[@FuncToBaseFXRate]
			        ),
			
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Amortized Cost Local] * 'Fx Rate DQ'[Rep Rate]
			        )
			)
			```
		lineageTag: 67e85eb4-4f0e-462b-a6c7-e87bff2edcce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Realised Impairment - Rep (Sec Trans)' = ```
			
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			        VAR vSummarizeTable = 
			        SUMMARIZE(
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Functional Ccy Code],
			            'Securities Transaction GA Fact'[Base],
			            'Securities Transaction GA Fact'[As Of Period],
			            'Securities Transaction GA Fact'[FX Join Key]
			        )
			        VAR vSummarizeTableWithFXRate =
			        ADDCOLUMNS(
			            vSummarizeTable,
			            "@RealisedImpairmentLocal",
			            CALCULATE(
			                SUM('Securities Transaction GA Fact'[Realised Impairment Local])
			            ),
			            "@LocalToFuncFXRate",
			            VAR vLocalToFuncFXJoinKey = 'Securities Transaction GA Fact'[FX Join Key]
			            RETURN
			            CALCULATE(
			                MAX('Fx Rate DQ'[Func BS Rate]),
			                'Fx Rate DQ'[FX Join Key]=vLocalToFuncFXJoinKey,
			                ALL('Fx Rate DQ')
			            ),
			        
			            "@FuncToBaseFXRate",
			            VAR FuncToBaseFXJoinKey = 'Securities Transaction GA Fact'[Functional Ccy Code]&"/"&'Securities Transaction GA Fact'[Base]&"/"&'Securities Transaction GA Fact'[As Of Period]
			            RETURN
			            CALCULATE(
			                MAX('Fx Rate DQ'[Func BS Rate]),
			                'Fx Rate DQ'[FX Join Key]=FuncToBaseFXJoinKey,
			                ALL('Fx Rate DQ')
			            )
			        )
			        RETURN
			        SUMX(
			            vSummarizeTableWithFXRate,
			            [@RealisedImpairmentLocal]*[@LocalToFuncFXRate]*[@FuncToBaseFXRate]
			        ),
			
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Realised Impairment Local] * 'Fx Rate DQ'[Rep Rate]
			        )
			)
			
			```
		lineageTag: 06272f41-de9c-4d3d-83f6-77e8120e1f3d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - CAD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Book Value - Local (D)]
			        * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 0839b6be-6c57-49f8-8698-e1528d08dad7

	measure 'Book Value - FUNC (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Book Value - Local (D)]
			        * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 80e7dffb-10ed-41e0-b48d-f6caada05462

	measure 'Book Value - HKD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Book Value - Local (D)]
			        * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 6417019c-398e-4ab2-a75b-bc5590212de9

	measure 'Book Value - USD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Book Value - Local (D)]
			        * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: d9b633d2-fcfa-4542-854d-98c879872c75

	measure 'Change AOCI BV - CAD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Change AOCI BV - Local]
			        * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 967fa8e2-f4f5-4868-90d0-31b83d5243a0

	measure 'Change AOCI BV - FUNC (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Change AOCI BV - Local]
			        * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 682cc720-07d3-4c5f-91eb-faef24165ba6

	measure 'Change AOCI BV - HKD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Change AOCI BV - Local]
			        * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 2186ae6a-12c2-4c38-9f8c-dcb5be788100

	measure 'Change AOCI BV - USD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Change AOCI BV - Local]
			        * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: e11fe43c-2a02-4370-8c0f-a13cee21ae36

	measure 'Cost Value - CAD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Cost Value - Local]
			        * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 90c8898c-e359-4fdc-9e30-2069e5b8c5ae

	measure 'Cost Value - FUNC (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Cost Value - Local]
			        * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: ac49f3a5-b38d-4eef-ba52-54fcec370a25

	measure 'Cost Value - HKD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Cost Value - Local]
			        * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 3216c4f8-8c6f-4844-96ca-894f63c76645

	measure 'Cost Value - USD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Cost Value - Local]
			        * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 41d036dd-1301-4dc9-9b48-2ef58ceb024c

	measure 'Deferred PL - CAD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Deferred PL - Local]
			        * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 85ac8550-7ade-49a3-afdd-37733556e737

	measure 'Deferred PL - FUNC (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Deferred PL - Local]
			        * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 4f1c0210-a261-4885-8f03-28d2690d443b

	measure 'Deferred PL - HKD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Deferred PL - Local]
			        * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 910c8a66-03f3-45c3-ac0e-270863df8e13

	measure 'Deferred PL - USD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Deferred PL - Local]
			        * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 79970ac2-f95e-4556-aa7b-0895d675965f

	measure 'Impairment - CAD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Impairment - Local]
			        * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: f32a5811-dd67-42e7-be28-88b5da1f5cd5

	measure 'Impairment - FUNC (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Impairment - Local]
			        * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 84b700a4-3552-4d88-8e81-d398a5c0cf74

	measure 'Impairment - HKD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Impairment - Local]
			        * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 57cfe2e8-eac9-48ad-b354-5b3806fbe510

	measure 'Impairment - USD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Impairment - Local]
			        * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: b0fdb29f-cbc2-4572-a8fd-7a58e7f79ded

	measure 'Income Gross Amount - CAD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Income Gross Amount - Local]
			        * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 99287928-bb54-4e6c-8467-ce557e54130f

	measure 'Income Gross Amount - FUNC (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Income Gross Amount - Local]
			        * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 1ac088ca-92cb-443e-8588-635f55ca83de

	measure 'Income Gross Amount - HKD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Income Gross Amount - Local]
			        * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 1595062e-c3dd-4c66-832b-d9e213b83033

	measure 'Income Gross Amount - USD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Income Gross Amount - Local]
			        * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 84f66c79-dda4-4914-ba1b-668804db9f97

	measure 'Int Apr - CAD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Int Apr - Local]
			        * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 1b811a15-d99a-49a2-ae50-362baecf9a23

	measure 'Int Apr - FUNC (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Int Apr - Local]
			        * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 1c754051-338b-4d9b-8dbb-03f6aeee7690

	measure 'Int Apr - HKD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Int Apr - Local]
			        * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 8ebc38d5-9318-4ad0-92f0-7402a5487c4c

	measure 'Int Apr - USD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Int Apr - Local]
			        * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 04fd89bd-633d-46d1-935b-3e226f94798d

	measure 'OID Int Appr - CAD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[OID Int Appr - Local]
			        * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: a4bc84b2-60f4-47ba-910b-ef6b08abc5cb

	measure 'OID Int Appr - FUNC (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[OID Int Appr - Local]
			        * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 385b8fcf-ec28-4fcc-9dd8-87dffd224dc4

	measure 'OID Int Appr - HKD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[OID Int Appr - Local]
			        * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 1cfe0a70-3a3b-4d3a-9cee-2ac03a483239

	measure 'OID Int Appr - USD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[OID Int Appr - Local]
			        * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 1ffd0085-912c-4c62-b3e3-f9a67d21e7a3

	measure 'Original Cost - CAD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Original Cost - Local]
			        * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: eef137c9-58ad-49d0-81c1-4303d9d6551f

	measure 'Original Cost - FUNC (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Original Cost - Local]
			        * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 1bf89316-6658-4a2a-a948-c5085a92bc25

	measure 'Original Cost - HKD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Original Cost - Local]
			        * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: c87a39b0-ce6d-4f43-af89-074c554280d0

	measure 'Original Cost - USD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Original Cost - Local]
			        * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 66e0bfa0-33da-4aaa-936e-bfa6b4c72524

	measure 'Real Int Appr - CAD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Real Int Appr - Local]
			        * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 900d8f16-17ce-4bee-a4a8-b156286cf2eb

	measure 'Real Int Appr - FUNC (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Real Int Appr - Local]
			        * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: b863afe9-e0e9-4084-abaf-a232a5a8b5dd

	measure 'Real Int Appr - HKD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Real Int Appr - Local]
			        * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 95892e58-689a-40da-a7c0-36fc32be8ffb

	measure 'Real Int Appr - USD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Real Int Appr - Local]
			        * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: ee991a19-32f8-4a35-8c18-9081379d6587

	measure 'Realized Gain/Loss - CAD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Realized Gain/Loss - Local]
			        * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: bc12f1e2-512a-4b34-b229-aeebd83018c2

	measure 'Realized Gain/Loss - FUNC (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Realized Gain/Loss - Local]
			        * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: efe5ec51-b31b-45a5-bb1d-aed734d4eece

	measure 'Realized Gain/Loss - HKD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Realized Gain/Loss - Local]
			        * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 75d172b1-85cc-4630-ab32-6b5d41f63a73

	measure 'Realized Gain/Loss - USD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Realized Gain/Loss - Local]
			        * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 2f44dabd-2295-494d-8e32-3ad084c5efe9

	measure 'Realized Gain/Loss Book - CAD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Realized Gain/Loss Book - Local]
			        * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 223b56ad-be9b-48d8-9afa-0a0cdd5df32e

	measure 'Realized Gain/Loss Book - FUNC (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Realized Gain/Loss Book - Local]
			        * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 72981db1-4f97-4a7c-bd74-c101986288d5

	measure 'Realized Gain/Loss Book - HKD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Realized Gain/Loss Book - Local]
			        * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 51b593f0-6c28-4528-bdd9-4e9dd43dfbb3

	measure 'Realized Gain/Loss Book - USD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Realized Gain/Loss Book - Local]
			        * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: ba8472de-3d6e-49c4-b7be-9e7bfeb66247

	measure 'Amortized Cost - HKD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Amortized Cost Local]
			        * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: c3dc85e9-ac5e-4035-beaf-87c99d18acbd

	measure 'Amortized Cost - USD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Amortized Cost Local]
			        * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 30d2c195-5488-4fdc-8db5-fd11a8c97d1f

	measure 'Amortized Cost - CAD (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Amortized Cost Local]
			        * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: 3d496378-0934-43e0-81d6-d3f6415f74c0

	measure 'Amortized Cost - FUNC (Sec Trans)' =
			SUMX (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Amortized Cost Local]
			        * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			)
		displayFolder: Currency Measures
		lineageTag: b50ee4a0-4bde-4db5-948b-bcefa5e5314e

	measure 'Sublot AOCI - Local (Sec Trans)' = ```
			
			var vAoci_key =
			SUMMARIZE (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Originating System No],
			    'Securities Transaction GA Fact'[Match Src Transaction ID],
			    'Securities Transaction GA Fact'[Source Id],
			    'Securities Transaction GA Fact'[Portfolio Code],
			    'Securities Transaction GA Fact'[Bus Trans Number],
			    'Securities Transaction GA Fact'[Framework Code],
			    'Securities Transaction GA Fact'[Dgl Inception Trans No]
			)
			var vResult = 
			CALCULATE( 
			    SUM('Securities Transaction AOCI GA Fact'[Sublot AOCI - Local]),
			    TREATAS (
			        vAoci_key,
			        'Securities Transaction AOCI GA Fact'[Originating System No],
			        'Securities Transaction GA Fact'[Match Src Transaction ID],
			        'Securities Transaction AOCI GA Fact'[Src Transaction Id],
			        'Securities Transaction AOCI GA Fact'[Portfolio Code],
			        'Securities Transaction AOCI GA Fact'[Bus Trans no],
			        'Securities Transaction AOCI GA Fact'[Framework Code],
			        'Securities Transaction AOCI GA Fact'[Dgl Inception Trans No]
			    )
			)
			
			RETURN vResult
			```
		lineageTag: 3a363f09-1e05-441f-b167-a4b117c6214f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sublot AOCI - Rep (Sec Trans)' = ```
			
			var vAoci_key =
			SUMMARIZE (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Originating System No],
			    'Securities Transaction GA Fact'[Match Src Transaction ID],
			    'Securities Transaction GA Fact'[Source Id],
			    'Securities Transaction GA Fact'[Portfolio Code],
			    'Securities Transaction GA Fact'[Bus Trans Number],
			    'Securities Transaction GA Fact'[Framework Code],
			    'Securities Transaction GA Fact'[Dgl Inception Trans No]
			)
			var vResult = 
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			    CALCULATE( 
			        SUM('Securities Transaction AOCI GA Fact'[Sublot AOCI - Base]),
			        TREATAS (
			            vAoci_key,
			            'Securities Transaction AOCI GA Fact'[Originating System No],
			            'Securities Transaction GA Fact'[Match Src Transaction ID],
			            'Securities Transaction AOCI GA Fact'[Src Transaction Id],
			            'Securities Transaction AOCI GA Fact'[Portfolio Code],
			            'Securities Transaction AOCI GA Fact'[Bus Trans no],
			            'Securities Transaction AOCI GA Fact'[Framework Code],
			            'Securities Transaction AOCI GA Fact'[Dgl Inception Trans No]
			        )
			    ),
			    CALCULATE( 
			        SUMX(
			            'Securities Transaction AOCI GA Fact',
			            'Securities Transaction AOCI GA Fact'[Sublot AOCI - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        TREATAS (
			            vAoci_key,
			            'Securities Transaction AOCI GA Fact'[Originating System No],
			            'Securities Transaction GA Fact'[Match Src Transaction ID],
			            'Securities Transaction AOCI GA Fact'[Src Transaction Id],
			            'Securities Transaction AOCI GA Fact'[Portfolio Code],
			            'Securities Transaction AOCI GA Fact'[Bus Trans no],
			            'Securities Transaction AOCI GA Fact'[Framework Code],
			            'Securities Transaction AOCI GA Fact'[Dgl Inception Trans No]
			        )
			    )
			)
			
			RETURN vResult
			```
		lineageTag: 52d0a8d7-0392-413d-9f55-e1324d2ab06f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sublot Amort AOCI - Local (Sec Trans)' = ```
			
			var vAoci_key =
			SUMMARIZE (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Originating System No],
			    'Securities Transaction GA Fact'[Match Src Transaction ID],
			    'Securities Transaction GA Fact'[Source Id],
			    'Securities Transaction GA Fact'[Portfolio Code],
			    'Securities Transaction GA Fact'[Bus Trans Number],
			    'Securities Transaction GA Fact'[Framework Code],
			    'Securities Transaction GA Fact'[Dgl Inception Trans No]
			)
			var vResult = 
			CALCULATE( 
			    SUM('Securities Transaction AOCI GA Fact'[Sublot Amort AOCI - Local]),
			    TREATAS (
			        vAoci_key,
			        'Securities Transaction AOCI GA Fact'[Originating System No],
			        'Securities Transaction GA Fact'[Match Src Transaction ID],
			        'Securities Transaction AOCI GA Fact'[Src Transaction Id],
			        'Securities Transaction AOCI GA Fact'[Portfolio Code],
			        'Securities Transaction AOCI GA Fact'[Bus Trans no],
			        'Securities Transaction AOCI GA Fact'[Framework Code],
			        'Securities Transaction AOCI GA Fact'[Dgl Inception Trans No]
			    )
			)
			
			RETURN vResult
			```
		lineageTag: 853d0c46-a934-415d-ac0d-674dc10869ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sublot Amort AOCI - Rep (Sec Trans)' = ```
			
			var vAoci_key =
			SUMMARIZE (
			    'Securities Transaction GA Fact',
			    'Securities Transaction GA Fact'[Originating System No],
			    'Securities Transaction GA Fact'[Match Src Transaction ID],
			    'Securities Transaction GA Fact'[Source Id],
			    'Securities Transaction GA Fact'[Portfolio Code],
			    'Securities Transaction GA Fact'[Bus Trans Number],
			    'Securities Transaction GA Fact'[Framework Code],
			    'Securities Transaction GA Fact'[Dgl Inception Trans No]
			)
			var vResult = 
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			    CALCULATE( 
			        SUM('Securities Transaction AOCI GA Fact'[Sublot Amort AOCI - Base]),
			        TREATAS (
			            vAoci_key,
			            'Securities Transaction AOCI GA Fact'[Originating System No],
			            'Securities Transaction GA Fact'[Match Src Transaction ID],
			            'Securities Transaction AOCI GA Fact'[Src Transaction Id],
			            'Securities Transaction AOCI GA Fact'[Portfolio Code],
			            'Securities Transaction AOCI GA Fact'[Bus Trans no],
			            'Securities Transaction AOCI GA Fact'[Framework Code],
			            'Securities Transaction AOCI GA Fact'[Dgl Inception Trans No]
			        )
			    ),
			    CALCULATE( 
			        SUMX(
			            'Securities Transaction AOCI GA Fact',
			            'Securities Transaction AOCI GA Fact'[Sublot Amort AOCI - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        TREATAS (
			            vAoci_key,
			            'Securities Transaction AOCI GA Fact'[Originating System No],
			            'Securities Transaction GA Fact'[Match Src Transaction ID],
			            'Securities Transaction AOCI GA Fact'[Src Transaction Id],
			            'Securities Transaction AOCI GA Fact'[Portfolio Code],
			            'Securities Transaction AOCI GA Fact'[Bus Trans no],
			            'Securities Transaction AOCI GA Fact'[Framework Code],
			            'Securities Transaction AOCI GA Fact'[Dgl Inception Trans No]
			        )
			    )
			)
			
			RETURN vResult
			```
		lineageTag: 5c12c29f-409e-4f0e-8b70-63f0ebfa4d87

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SCD MTG Exp Maturity Dt (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[SCD MTG EXP Maturity Dt], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		formatString: General Date
		lineageTag: efd5ab97-b268-497e-b340-9c437ea744cc

	measure 'Ultimate parent company (Sec Trans)' = ```
			
			    CALCULATE(
			        [Ultimate parent company (Entities)],
			        CROSSFILTER(Securities[Security NK],'Securities Transaction GA Fact'[Security NK],BOTH)
			        )
			```
		lineageTag: c022cac1-5432-47da-990d-55e6986ef9a1

	measure 'Ultimate parent LEI (Sec Trans)' = ```
			
			    CALCULATE(
			        [Ultimate parent LEI (Entities)],
			        CROSSFILTER(Securities[Security NK],'Securities Transaction GA Fact'[Security NK],BOTH)
			        )
			```
		lineageTag: 04af8e20-8891-4ed0-9b7e-4cffc7b199f8

	measure 'Ultimate parent location (Sec Trans)' = ```
			
			    CALCULATE(
			        [Ultimate parent location (Entities)],
			        CROSSFILTER(Securities[Security NK],'Securities Transaction GA Fact'[Security NK],BOTH)
			        )
			```
		lineageTag: 82cbef80-859e-4d1e-978b-1d4a898c984c

	measure 'NAIC Designation Modifier (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[NAIC Designation Modifier], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 3eab3e5f-8f7a-4768-9346-f6dab0b712d9

	measure 'SCD Svo suffix (Sec Tran)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[SCD Svo Suffix], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 9f7f91db-06c9-4ee3-b0a9-6323d555a5a0

	measure 'Book Value - Adjustment Local (Sec Trans)' = ```
			
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Book Value" )
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// RETURN 
			// SUMX(summarize('Securities Transaction GA Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//     SUM('Securities GL Txn fact'[Local Txn Amt]),
			//     TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//     TREATAS(VALUES('Securities Transaction GA Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//     vDateRange
			//     )
			// )
			// )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Book Value"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SUM ( 'Consolidated GL Balance Fact'[Local Balance Amt] ),
			                TREATAS ( vListofGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Transaction GA Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		displayFolder: CAT Adjustments
		lineageTag: b89f8a59-4642-47ef-9d9a-e1cc3bb5b844

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Adjustment Rep (Sec Trans)' = ```
			
			// VAR vSelectedCurrency = SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency])
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Book Value" )
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// VAR vBVRep= 
			// SUMX(summarize('Securities Transaction GA Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//         SWITCH (
			//                 vSelectedCurrency,
			//                 "CAD",[Adjustment Amount (CAD)],
			//                 "USD",[Adjustment Amount (USD)],
			//                 "HKD",[Adjustment Amount (HKD)],
			//                 [Adjustment Amount (Func)]
			//         ),
			//     TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//     TREATAS(VALUES('Securities Transaction GA Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//     vDateRange
			// )
			// )
			// )
			// RETURN vBVRep
			VAR vSelectedCurrency =
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Book Value"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SWITCH (
			                    vSelectedCurrency,
			                    "CAD", [Adjustment_Amount (CAD)],
			                    "USD", [Adjustment_Amount (USD)],
			                    "HKD", [Adjustment_Amount (HKD)],
			                    [Adjustment_Amount (Func)]
			                ),
			                TREATAS ( vListofGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Transaction GA Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		displayFolder: CAT Adjustments
		lineageTag: 41d5f037-e768-436d-91ab-7bdd48706295

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Trans Local (Sec Trans)' = SUM ( 'Securities Transaction GA Fact'[Book Value - Local (D)] )
		displayFolder: SCD Transactions
		lineageTag: f82b5cf8-62cf-4d50-8364-238f95206aea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Trans Rep (Sec Trans)' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			        SUM ( 'Securities Transaction GA Fact'[Book Value - Base] )
			        ,
			            
			        SUMX(
			           
			                    'Securities Transaction GA Fact',
			                    'Securities Transaction GA Fact'[Book Value - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			                )
			)
			```
		displayFolder: SCD Transactions
		lineageTag: 049934db-d496-4f36-ba01-f15b64184228

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Adjustment Local (Sec Trans)' = ```
			
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Unrealized" )
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// RETURN 
			// SUMX(summarize('Securities Transaction GA Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//     SUM('Securities GL Txn fact'[Local Txn Amt]),
			//     TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//     TREATAS(VALUES('Securities Transaction GA Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//     vDateRange
			//     )
			// )
			// )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Unrealized"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SUM ( 'Consolidated GL Balance Fact'[Local Balance Amt] ),
			                TREATAS ( vListofGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Transaction GA Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		displayFolder: CAT Adjustments
		lineageTag: 45a63c76-bd1c-450d-94a7-de593640ba5f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Adjustment Rep (Sec Trans)' = ```
			
			// VAR vSelectedCurrency = SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency])
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Unrealized")
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// VAR vURRep= 
			// SUMX(summarize('Securities Transaction GA Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//         SWITCH (
			//                 vSelectedCurrency,
			//                 "CAD",[Adjustment Amount (CAD)],
			//                 "USD",[Adjustment Amount (USD)],
			//                 "HKD",[Adjustment Amount (HKD)],
			//                 [Adjustment Amount (Func)]
			//         ),
			//     TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//     TREATAS(VALUES('Securities Transaction GA Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//     vDateRange
			// )
			// )
			// )
			// RETURN vURRep
			VAR vSelectedCurrency =
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Unrealized"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SWITCH (
			                    vSelectedCurrency,
			                    "CAD", [Adjustment_Amount (CAD)],
			                    "USD", [Adjustment_Amount (USD)],
			                    "HKD", [Adjustment_Amount (HKD)],
			                    [Adjustment_Amount (Func)]
			                ),
			                TREATAS ( vListofGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Transaction GA Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		displayFolder: CAT Adjustments
		lineageTag: 000a624b-a0b8-4cb9-98a6-7a5b934ce80b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carrying Value - Adjustment Local (Sec Trans)' = [Book Value - Adjustment Local (Sec Trans)] +[Unrealized Gain/Loss - Adjustment Local (Sec Trans)]
		displayFolder: CAT Adjustments
		lineageTag: 28efb352-27bb-4c4a-ae71-f52c678b291c

	measure 'Carrying Value - Adjustment Rep (Sec Trans)' = [Book Value - Adjustment Rep (Sec Trans)] + [Unrealized Gain/Loss - Adjustment Rep (Sec Trans)]
		displayFolder: CAT Adjustments
		lineageTag: 74f5b7c1-b73d-4974-a0f4-a0eafb0aba8d

	measure 'Realized Gain/Loss - Adjustment Local (Sec Trans)' = ```
			
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Realized" )
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// RETURN 
			// SUMX(summarize('Securities Transaction GA Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//     SUM('Securities GL Txn fact'[Local Txn Amt]),
			//     TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//     TREATAS(VALUES('Securities Transaction GA Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//     vDateRange
			//     )
			// )
			// )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Realized"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SUM ( 'Consolidated GL Balance Fact'[Local Balance Amt] ),
			                TREATAS ( vListofGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Transaction GA Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		displayFolder: CAT Adjustments
		lineageTag: 6cbc681d-2ca6-4248-98c5-24977e200066

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Realized Gain/Loss - Adjustment Rep (Sec Trans)' = ```
			
			// VAR vSelectedCurrency = SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency])
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Realized")
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// VAR vRRep= 
			// SUMX(summarize('Securities Transaction GA Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//         SWITCH (
			//                 vSelectedCurrency,
			//                 "CAD",[Adjustment Amount (CAD)],
			//                 "USD",[Adjustment Amount (USD)],
			//                 "HKD",[Adjustment Amount (HKD)],
			//                 [Adjustment Amount (Func)]
			//         ),
			//     TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//     TREATAS(VALUES('Securities Transaction GA Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//     vDateRange
			// )
			// )
			// )
			// RETURN vRRep
			VAR vSelectedCurrency =
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Realized"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SWITCH (
			                    vSelectedCurrency,
			                    "CAD", [Adjustment_Amount (CAD)],
			                    "USD", [Adjustment_Amount (USD)],
			                    "HKD", [Adjustment_Amount (HKD)],
			                    [Adjustment_Amount (Func)]
			                ),
			                TREATAS ( vListofGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Transaction GA Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		displayFolder: CAT Adjustments
		lineageTag: 70891925-2c23-46eb-a2a8-eb51075d2778

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Realized Gain/Loss Book - Trans Rep (Sec Trans)' = ```
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			        
			        SUM ( 'Securities Transaction GA Fact'[Realized Gain/Loss Book - Base] ),
			            
			   
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Realized Gain/Loss Book - Local] * 'Fx Rate DQ'[Rep Rate]
			        )
			)
			```
		displayFolder: SCD Transactions
		lineageTag: 28f99d39-6c47-4c6e-acea-4f26dd5f35b9

	measure 'Realized Gain/Loss Book - Trans Local (Sec Trans)' = SUM ( 'Securities Transaction GA Fact'[Realized Gain/Loss Book - Local] )
		displayFolder: SCD Transactions
		lineageTag: 6348786f-7a78-4632-a6e8-ee9beb555bac

	measure 'Realized Gain/Loss Book - Local (Sec Trans)' = [Realized Gain/Loss Book - Trans Local (Sec Trans)]+[Realized Gain/Loss - Adjustment Local (Sec Trans)]
		displayFolder: SCD Transactions + CAT Adjustments
		lineageTag: 21a1dee5-3f36-47d2-abd0-1cde7fd207dc

	measure 'Income Gross Amount - Trans Rep (Sec Trans)' = ```
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			        SUMX(
			            VALUES('Securities Transaction GA Fact'[Transaction No]),
			            CALCULATE(MAX ( 'Securities Transaction GA Fact'[Income Gross Amount - Base] ))
			        ),
			            
			        SUMX(
			            SUMMARIZE(
			                ADDCOLUMNS(
			                    'Securities Transaction GA Fact',
			                    "@BVRepAmt",'Securities Transaction GA Fact'[Income Gross Amount - Local] * 'Fx Rate DQ'[Rep Rate]
			                ),
			            'Securities Transaction GA Fact'[Transaction No],[@BVRepAmt]
			            ),
			            [@BVRepAmt]
			        )
			)
			```
		displayFolder: SCD Transactions
		lineageTag: 08fa22a3-66c7-4620-9824-8360b9649863

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income Gross Amount - Trans Local (Sec Trans)' =
			SUMX(
			    VALUES('Securities Transaction GA Fact'[Transaction No]),
			    CALCULATE(MAX ( 'Securities Transaction GA Fact'[Income Gross Amount - Local]))
			)
		displayFolder: SCD Transactions
		lineageTag: 1f6cd369-6478-4f10-a6e5-a736dbc594af

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income Gross Amount - Adjustment Local (Sec Trans)' = ```
			
			//  VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Income Gross" )
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// RETURN 
			// SUMX(summarize('Securities Transaction GA Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//     SUM('Securities GL Txn fact'[Local Txn Amt]),
			//     TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//     TREATAS(VALUES('Securities Transaction GA Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//     vDateRange
			//     )
			// )
			// )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Income Gross"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SUM ( 'Consolidated GL Balance Fact'[Local Balance Amt] ),
			                TREATAS ( vListofGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Transaction GA Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		displayFolder: CAT Adjustments
		lineageTag: af87219d-c836-47ff-aa20-4d2b3b26feca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income Gross Amount - Adjustment Rep (Sec Trans)' = ```
			
			// VAR vSelectedCurrency = SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency])
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Income Gross")
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// VAR vIncomeRep= 
			// SUMX(summarize('Securities Transaction GA Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//         SWITCH (
			//                 vSelectedCurrency,
			//                 "CAD",[Adjustment Amount (CAD)],
			//                 "USD",[Adjustment Amount (USD)],
			//                 "HKD",[Adjustment Amount (HKD)],
			//                 [Adjustment Amount (Func)]
			//         ),
			//     TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//     TREATAS(VALUES('Securities Transaction GA Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//     vDateRange
			// )
			// )
			// )
			// RETURN vIncomeRep
			VAR vSelectedCurrency =
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Income Gross"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SWITCH (
			                    vSelectedCurrency,
			                    "CAD", [Adjustment_Amount (CAD)],
			                    "USD", [Adjustment_Amount (USD)],
			                    "HKD", [Adjustment_Amount (HKD)],
			                    [Adjustment_Amount (Func)]
			                ),
			                TREATAS ( vListofGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Transaction GA Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		displayFolder: CAT Adjustments
		lineageTag: 3cf574fb-79ed-4563-9356-7229669eda88

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income Gross Amount - Local (Sec Trans)' = [Income Gross Amount - Trans Local (Sec Trans)]+[Income Gross Amount - Adjustment Local (Sec Trans)]
		displayFolder: SCD Transactions + CAT Adjustments
		lineageTag: 20c851ca-cf89-4519-ab2a-2cde86402479

	measure 'Amortization/Accretion - Adjustment Local (Sec Trans)' = ```
			
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Amortization/Accretion" )
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// RETURN 
			// SUMX(summarize('Securities Transaction GA Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//     SUM('Securities GL Txn fact'[Local Txn Amt]),
			//     TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//     TREATAS(VALUES('Securities Transaction GA Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//     vDateRange
			//     )
			// )
			// )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Amortization/Accretion"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SUM ( 'Consolidated GL Balance Fact'[Local Balance Amt] ),
			                TREATAS ( vListofGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Transaction GA Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		displayFolder: CAT Adjustments
		lineageTag: b012bec0-a769-4e1d-a42a-827dcceedd04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Amortization/Accretion - Adjustment Rep (Sec Trans)' = ```
			
			//  VAR vSelectedCurrency = SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency])
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Amortization/Accretion")
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// VAR vAmortRep= 
			// SUMX(summarize('Securities Transaction GA Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//         SWITCH (
			//                 vSelectedCurrency,
			//                 "CAD",[Adjustment Amount (CAD)],
			//                 "USD",[Adjustment Amount (USD)],
			//                 "HKD",[Adjustment Amount (HKD)],
			//                 [Adjustment Amount (Func)]
			//         ),
			//     TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//     TREATAS(VALUES('Securities Transaction GA Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//     vDateRange
			// )
			// )
			// )
			// RETURN vAmortRep
			VAR vSelectedCurrency =
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Amortization/Accretion"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SWITCH (
			                    vSelectedCurrency,
			                    "CAD", [Adjustment_Amount (CAD)],
			                    "USD", [Adjustment_Amount (USD)],
			                    "HKD", [Adjustment_Amount (HKD)],
			                    [Adjustment_Amount (Func)]
			                ),
			                TREATAS ( vListofGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Transaction GA Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		displayFolder: CAT Adjustments
		lineageTag: e221a778-3832-424f-896a-545ee42db9eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Amortization/Accretion - Trans Rep (Sec Trans)' = ```
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			        SUM ( 'Securities Transaction GA Fact'[Int Apr - Base] ),
			  
			        SUMX (
			            'Securities Transaction GA Fact',
			            'Securities Transaction GA Fact'[Int Apr - Local] * 'Fx Rate DQ'[Rep Rate]
			        )
			)
			```
		displayFolder: SCD Transactions
		lineageTag: cbfeb2b1-9276-4a1f-89ad-20650658ad43

	measure 'Amortization/Accretion - Trans Local (Sec Trans)' = SUM ( 'Securities Transaction GA Fact'[Int Apr - Local] )
		displayFolder: SCD Transactions
		lineageTag: da054b3c-d65b-45b2-b0a2-7cbdf8706610

	measure 'Amortization/Accretion - Local (Sec Trans)' = [Amortization/Accretion - Trans Local (Sec Trans)]+[Amortization/Accretion - Adjustment Local (Sec Trans)]
		displayFolder: SCD Transactions + CAT Adjustments
		lineageTag: 6e9c6632-8e97-4e66-b543-2681f12f40fe

	measure 'Make Whole Termination Dt (Sec Trans)' =
			
			CALCULATE (MAX('Securities'[Make Whole Termination Dt]),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		formatString: yyyy-mm-dd
		lineageTag: 8fbb7bd6-611c-462c-9577-2c1d2b462984

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Make Whole Call Spread Num (Sec Trans)' =
			
			CALCULATE (MAX('Securities'[Make Whole Call Spread Num]),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 9f545aa0-9342-4ea7-a9db-d0893ceb8531

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Payment Method Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Payment Method Name], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: dd48ec28-8c7e-45e2-8419-a9ac1fd2c8bf

	measure 'Make Whole Call (Sec Trans)' =
			
			CALCULATE (MAX('Securities'[Make Whole Call]),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 5750fafa-8097-4e54-b80a-eb1567852f02

	measure 'Custodian Name(Sec TransGA)' =
			
			VAR maxPred =
			    MAX ( 'Period'[Period] )
			VAR SecTrans =
			    CALCULATE (
			        MAX ('Securities Transaction GA Fact'[Custodian Name]),
			        FILTER('Securities Transaction GA Fact', 'Securities Transaction GA Fact'[As of Period] = maxPred)
			    )
			RETURN
			    SecTrans
		lineageTag: 83ce11b0-5e4d-44fe-828b-68ae03cede49

	measure 'SCD Instrument Category (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[SCD Instrument Category], TRUE () ),
			    CROSSFILTER ('Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: f377f708-c52c-487a-9471-18b78a35aa27

	measure 'MRM Issuer Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Name], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 6d88de8f-e408-44ef-9065-02c184748334

	measure 'MRM Issuer Country Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Country Name], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 94eaf047-9876-45c4-a4c1-9a9e7fd48dbd

	measure 'MRM Issuer Irr Rating Cd (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Irr Rating Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 8555a3ee-61ae-4a53-9267-9c2ef0293c7b

	measure 'MRM Issuer Parent Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Parent Name], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 411be619-66da-4489-bec2-9b4efc9b1c92

	measure 'MRM Issuer Parent Country Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Parent Country Name], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 2ca780cd-77b2-445e-b6e4-4de2230402a8

	measure 'MRM Issuer Parent Irr Rating Cd (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Parent Irr Rating Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 24f71ad1-1e8a-4cbf-95aa-ed40cac19a7a

	measure 'MRM Issuer Ultparent Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Ultparent Name], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 3a0fa3d6-beb7-41dc-964c-bbeee7191a54

	measure 'MRM Issuer Ultparent Country Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Ultparent Country Name], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 2ac510da-38ba-4955-9b03-63dea8ecafff

	measure 'MRM Issuer Ultparent Irr Rating Cd (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Ultparent Irr Rating Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: c66dfbf9-751b-4912-9f82-b5fabd20676e

	measure 'Equity Fund Ind (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[Equity Fund Ind], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 1c3a64b8-8b31-4bfb-98c4-20ddd44085b2

	measure 'GCLMS Collateral Quality Cd (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[GCLMS Collateral Quality Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 79c49d76-26e8-43e5-b54d-d7d1c456765c

	measure 'MRM Issuer Cascade Rating Cd (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Cascade Rating Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 7ce5c6a5-83b7-4f09-a18f-56cc3edbff8d

	measure 'MRM Issuer Parent Cascade Rating Cd (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Parent Cascade Rating Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: fd8b81a1-a0e4-4223-8cac-7d8d41424c53

	measure 'MRM Issuer Ultparent Cascade Rating Cd (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Ultparent Cascade Rating Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 7c0f6b91-c492-4eb2-946c-984bba9f688c

	measure 'Cur Cpn (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[Cur Cpn], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: cd7e425e-6bcd-41f8-8e1f-91e20c51283f

	measure 'GCLMS Issuer Parent Cascade Rtg Cd (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[GCLMS Issuer Parent Cascade Rtg Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 3848f56b-bc58-4e83-b80a-92fefe708f63

	measure 'Guarantor Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[Guarantor Name], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 04d8a10f-db3c-429d-8f1b-76806aa2a24d

	measure 'ML Capital Structure Desc (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Capital Structure Desc], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: d29fdd3b-8016-40ef-83f2-ca0dbd1d2430

	measure 'Legal Structure Cd (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Securities'[Legal Structure Cd],TRUE()),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: bb2c43ab-7a17-4f08-9d8a-1a6ae2c6656c

	measure 'Capital Structure Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Capital Structure Name], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: dcfdefad-875b-4f58-8768-b05a1e5a7285

	measure 'User Change ID (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities Transaction GA Fact'[User Change ID], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 2f28e4b3-e084-4b8f-8c5b-93c9df235b08

	measure 'User Change Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities Transaction GA Fact'[User Change Name], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: affa6937-4edb-4b06-891d-1e1d71edbf16

	measure 'Alt Fee Asset Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Alt Fee Asset Name], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 5ebf8026-a160-4f45-af73-6a13bbec7ad5

	measure 'Transfer Market Value Amt (Sec Trans)' =
			
			CALCULATE(
					SUMX(
						'Securities Transaction GA Fact',
						VAR vNominal = 'Securities Transaction GA Fact'[Lot Nominal]
						VAR vPosTransLink = VALUE('Securities Transaction GA Fact'[POS Trans Link])
						VAR vTradeDate = 'Securities Transaction GA Fact'[Trade Date]
						VAR vPrice = CALCULATE(
							MAX('Securities Position Fact'[Price - Local (D)]),
							ALL('Period'),
							'Period'[Date] = vTradeDate,
							'Securities Position Fact'[Src Position ID] = vPosTransLink
						)
						RETURN
							vPrice * vNominal
					),
					'Securities Transaction GA Fact'[Trans Type] IN {
						"Reallocation Custodian+Custody External",
						"Reallocation Custody and Portfolio",
						"Reallocation Custody Internal",
						"Reallocation free codes",
						"Reallocation, Model Portfolio",
						"Reallocation, Security No.",
						"Reallocation, Security No.SD",
						"Rev. Reallocation Custody and Portfolio",
						"Rev.Reallocation Custody",
						"Rev.Reallocation custody + custodian",
						"Rev.Reallocation free codes",
						"Rev.Reallocation security ID",
						"Rev.Reallocation security IDSD",
						"Rev.Reallocation, Model Portfolio"
					},
					'Securities Transaction GA Fact'[Transaction Purpose] IN {
						"Inter-Company",
						"Intra-Company"
					},
					'Securities Transaction GA Fact'[Trans Status] = "Active"
				)
		lineageTag: 3a0f7c9f-8ee9-4b59-881d-0533c0286dc8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Processing Group Name (Sec Trans)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities Transaction GA Fact'[Processing Group Name], TRUE () ),
			    CROSSFILTER ( 'Securities Transaction GA Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: f96e569e-ce9f-46b0-babb-8731b56a9015

	measure 'Trading Philosophy Code - IAS39 (Sec Tran)' = ```
			
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] > MaxAsOfDate
			    )
			RETURN
			IF(COUNTROWS('Securities Transaction GA Fact')>0,
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Transaction GA Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    // TREATAS(BusEffFromTo,'Securities Transaction GA Fact'[Trade Date]),
			    BusEffFromTo,
			    KEEPFILTERS('Securities Transaction GA Fact'[Framework Code] = "IAS39")
			))
			 
			```
		lineageTag: c3a57792-d544-458a-8e3a-d8bef2ff58ec

	measure 'Trading Philosophy Code - IFRS (Sec Tran)' = ```
			
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] > MaxAsOfDate
			    )
			RETURN
			IF(COUNTROWS('Securities Transaction GA Fact')>0,
			
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Transaction GA Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    // TREATAS(BusEffFromTo,'Securities Transaction GA Fact'[Trade Date]),
			    BusEffFromTo,
			    KEEPFILTERS('Securities Transaction GA Fact'[Framework Code] = "IFRS9")
			))
			 
			```
		lineageTag: c41cfbe0-da71-4efe-86d6-8e70ce785843

	measure 'Trading Philosophy Code - JGAAP (Sec Tran)' =
			
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] > MaxAsOfDate
			    )
			RETURN
			IF(COUNTROWS('Securities Transaction GA Fact')>0,
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Transaction GA Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    // TREATAS(BusEffFromTo,'Securities Transaction GA Fact'[Trade Date]),
			    BusEffFromTo,
			    KEEPFILTERS('Securities Transaction GA Fact'[Framework Code] = "JGAAP")
			))
		lineageTag: 342cbf64-ea8d-42cb-8e35-2f47dd0279c7

	measure 'Trading Philosophy Code - USGAAP (Sec Tran)' = ```
			
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] > MaxAsOfDate
			    )
			RETURN
			IF(COUNTROWS('Securities Transaction GA Fact')>0,
			
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Transaction GA Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    // TREATAS(BusEffFromTo,'Securities Transaction GA Fact'[Trade Date]),
			    BusEffFromTo,
			    KEEPFILTERS('Securities Transaction GA Fact'[Framework Code] = "USGAAP")
			))
			 
			```
		lineageTag: e184bb03-5c59-4dd5-a4b8-7fc18487275a

	column 'Transaction No'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 720992dc-4fa1-4a62-88c2-0c9d58d0da40
		summarizeBy: none
		sourceColumn: Transaction No

		annotation SummarizationSetBy = Automatic

	column Leg
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 432ec010-5b67-4b2a-bf08-98163d595754
		summarizeBy: sum
		sourceColumn: Leg

		annotation SummarizationSetBy = Automatic

	column Reversal
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 590c310c-855b-4ae9-8d79-f3e8bd40fa48
		summarizeBy: none
		sourceColumn: Reversal

		annotation SummarizationSetBy = Automatic

	column 'Trans Status'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: a2c3c6ce-0519-498d-b6f2-4f08ce5592bf
		summarizeBy: none
		sourceColumn: Trans Status

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Code'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 7d416e78-1485-4709-a5de-bde2fb8e29e2
		summarizeBy: none
		sourceColumn: Portfolio Code

		annotation SummarizationSetBy = Automatic

	column 'Post Date'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		sourceProviderType: datetime2
		lineageTag: f2e06ae3-10cf-495f-8913-8279dd68328e
		summarizeBy: none
		sourceColumn: Post Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Period Close Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		sourceProviderType: date
		lineageTag: c1857eb4-1486-45f3-932f-29f38f0902e0
		summarizeBy: none
		sourceColumn: Period Close Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Posting Lag'
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 89ff4d03-9fac-4920-aaf2-60b9bdcb959f
		summarizeBy: sum
		sourceColumn: Posting Lag

		annotation SummarizationSetBy = Automatic

	column 'Settle Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		sourceProviderType: date
		lineageTag: 382794b9-2d82-4dd8-9072-1d71aeb16c45
		summarizeBy: none
		sourceColumn: Settle Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Bloomberg No'
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: a83ab664-876e-4379-b78a-dcc9c1d8109f
		summarizeBy: sum
		sourceColumn: Bloomberg No

		annotation SummarizationSetBy = Automatic

	column 'Master Ticket'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: b2cd7501-9250-424a-99db-91878cdfd15e
		summarizeBy: none
		sourceColumn: Master Ticket

		annotation SummarizationSetBy = Automatic

	column 'Order No'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: b0aef321-b3e8-4e0a-a398-fe41902b869c
		summarizeBy: none
		sourceColumn: Order No

		annotation SummarizationSetBy = Automatic

	column 'Source ID'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: aa9cbe3c-4d5a-4f0e-aae4-0b3497df257c
		summarizeBy: none
		sourceColumn: Source ID

		annotation SummarizationSetBy = Automatic

	column 'User Name'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: ee4bce61-204c-4f79-aacb-11809f3e36ee
		summarizeBy: none
		sourceColumn: User Name

		annotation SummarizationSetBy = Automatic

	column 'Settle Ccy Code'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 202d07e0-e8fc-4b0a-afc4-96230b63a4ee
		summarizeBy: none
		sourceColumn: Settle Ccy Code

		annotation SummarizationSetBy = Automatic

	column 'Settle Currency'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 04f97fb9-20ca-47ac-9fbc-458d06997fff
		summarizeBy: none
		sourceColumn: Settle Currency

		annotation SummarizationSetBy = Automatic

	column Local
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 4d5bf456-e132-4382-bb06-9d8b0ba3be5b
		summarizeBy: none
		sourceColumn: Local

		annotation SummarizationSetBy = Automatic

	column 'Local Currency'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 0ed31ed3-49da-42d1-b09b-807341a83424
		summarizeBy: none
		sourceColumn: Local Currency

		annotation SummarizationSetBy = Automatic

	column 'Settle Exchange Rate'
		dataType: double
		sourceProviderType: float
		lineageTag: d7c9d414-15ff-4d86-b163-daae959de691
		summarizeBy: sum
		sourceColumn: Settle Exchange Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local Exchange Rate'
		dataType: double
		formatString: 0.000000
		sourceProviderType: float
		lineageTag: 8a37ec8c-fc5d-4f41-88b8-1f962bf6b8a7
		summarizeBy: sum
		sourceColumn: Local Exchange Rate

		annotation SummarizationSetBy = User

	column Sign
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 38523b4f-7bbf-4570-a80f-5f92f3429f45
		summarizeBy: sum
		sourceColumn: Sign

		annotation SummarizationSetBy = Automatic

	column Units
		dataType: double
		formatString: #,0.000
		lineageTag: 39a188dd-6b9d-4a4a-93fd-93bc2105f8d2
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	column 'Pool Factor'
		dataType: double
		sourceProviderType: float
		lineageTag: b4533dad-b99c-465e-85ad-b006a592b913
		summarizeBy: sum
		sourceColumn: Pool Factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Original Face'
		dataType: double
		sourceProviderType: float
		lineageTag: 0c4522d1-dd21-4954-bae0-f96aa318de17
		summarizeBy: sum
		sourceColumn: Original Face

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Current Face'
		dataType: double
		sourceProviderType: float
		lineageTag: 803a0ed0-0933-4cfb-8fff-ba7480645779
		summarizeBy: sum
		sourceColumn: Current Face

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nominal Basis'
		dataType: double
		sourceProviderType: float
		lineageTag: 87bf0698-2897-4f67-a10d-998ec6e88c74
		summarizeBy: sum
		sourceColumn: Nominal Basis

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Broker Code'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 9b4b9ae1-4295-48c6-ab27-18b3bbd347ae
		summarizeBy: none
		sourceColumn: Broker Code

		annotation SummarizationSetBy = Automatic

	column 'Broker Name'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: ca8c076e-fd62-44db-b02d-098ff7c90835
		summarizeBy: none
		sourceColumn: Broker Name

		annotation SummarizationSetBy = Automatic

	column Cmmt
		dataType: string
		sourceProviderType: varchar(500)
		lineageTag: c553b900-28e5-4aac-9dbb-88bdacd530cb
		summarizeBy: none
		sourceColumn: Cmmt

		annotation SummarizationSetBy = Automatic

	column 'Amount - Base'
		dataType: double
		sourceProviderType: float
		lineageTag: eb0b6113-c7c2-45d3-9d3b-8d213764b677
		summarizeBy: sum
		sourceColumn: Amount - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Settle Amount (D)'
		dataType: double
		isHidden
		formatString: #,0.00
		sourceProviderType: float
		lineageTag: 01cb6a3c-2384-43cf-8fc1-8775b9792dcf
		summarizeBy: sum
		sourceColumn: Settle Amount (D)

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Principal - Base'
		dataType: double
		sourceProviderType: float
		lineageTag: 966725c4-da53-425a-ab08-86b4b3840cd4
		summarizeBy: sum
		sourceColumn: Principal - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Settle Principal'
		dataType: double
		sourceProviderType: float
		lineageTag: e9e5c0f0-d941-4a97-b6f8-da91f732824c
		summarizeBy: sum
		sourceColumn: Settle Principal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Interest - Base'
		dataType: double
		sourceProviderType: float
		lineageTag: 34086ce1-26aa-409d-a532-0f06d0ded209
		summarizeBy: sum
		sourceColumn: Interest - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Settle Interest'
		dataType: double
		sourceProviderType: float
		lineageTag: 08997df3-cb9b-4e82-bc92-7c3e79786ac0
		summarizeBy: sum
		sourceColumn: Settle Interest

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Maturity Amount - Base'
		dataType: double
		sourceProviderType: float
		lineageTag: 1a4c3cd4-9412-4e48-9b74-088171c559a6
		summarizeBy: sum
		sourceColumn: Maturity Amount - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Settle Maturity Amount'
		dataType: double
		sourceProviderType: float
		lineageTag: cba67343-cc27-443c-8682-f02e0571d184
		summarizeBy: sum
		sourceColumn: Settle Maturity Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price - Base'
		dataType: double
		sourceProviderType: float
		lineageTag: 0bca8896-60f6-404d-81b4-044851eea768
		summarizeBy: sum
		sourceColumn: Price - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Settle Price'
		dataType: double
		sourceProviderType: float
		lineageTag: 9e03533c-58b4-4005-ad85-32cdade49d54
		summarizeBy: max
		sourceColumn: Settle Price

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Transaction Yield'
		dataType: double
		sourceProviderType: float
		lineageTag: 8cc06fc3-3a78-45eb-9715-da2a0f8b22c8
		summarizeBy: max
		sourceColumn: Transaction Yield

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Liability Portf Code'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: f675c64a-8f05-4928-aa11-327ef40744de
		summarizeBy: none
		sourceColumn: Liability Portf Code

		annotation SummarizationSetBy = Automatic

	column Base
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 5606d51d-f766-46d9-92e6-784b565bb8e0
		summarizeBy: none
		sourceColumn: Base

		annotation SummarizationSetBy = Automatic

	column 'Payment Purpose'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 29386580-54fc-4310-a8fe-0352536714a1
		summarizeBy: none
		sourceColumn: Payment Purpose

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 3f666997-6769-41f4-bd21-31e7e94f2102
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Groupcode
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: a4400f10-64a4-4837-973f-ba1e13030340
		summarizeBy: none
		sourceColumn: Groupcode

		annotation SummarizationSetBy = Automatic

	column 'Bank Code'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 46c33fa2-c85d-46db-9ccb-7fd19a3cef22
		summarizeBy: none
		sourceColumn: Bank Code

		annotation SummarizationSetBy = Automatic

	column 'Bank Account Code'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 52ca9d9a-69d1-4f50-9026-a0c085173b09
		summarizeBy: none
		sourceColumn: Bank Account Code

		annotation SummarizationSetBy = Automatic

	column 'SCD Security ID'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: e7451821-241e-42f2-bb48-e8c3661fce09
		summarizeBy: none
		sourceColumn: SCD Security ID

		annotation SummarizationSetBy = Automatic

	column 'Underlier Sec Key'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 22904e54-67cb-47ed-99b5-759d752a3d46
		summarizeBy: none
		sourceColumn: Underlier Sec Key

		annotation SummarizationSetBy = Automatic

	column 'SCD Security Type'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 7af896c0-4eba-449d-b011-bcdcb98fa014
		summarizeBy: none
		sourceColumn: SCD Security Type

		annotation SummarizationSetBy = Automatic

	column 'Underlier Src Security ID'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 93788ff3-a1e6-424b-b384-4766977b37e9
		summarizeBy: none
		sourceColumn: Underlier Src Security ID

		annotation SummarizationSetBy = Automatic

	column 'Sub Broker'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 58007596-7d59-4107-bb5e-8449ea3531dd
		summarizeBy: none
		sourceColumn: Sub Broker

		annotation SummarizationSetBy = Automatic

	column 'Sub Broker Des'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 85de5129-6375-4e8c-89ba-403a07416d35
		summarizeBy: none
		sourceColumn: Sub Broker Des

		annotation SummarizationSetBy = Automatic

	column Ipo
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 3b42427d-d48b-4fc1-ad4b-17ef166255ab
		summarizeBy: none
		sourceColumn: Ipo

		annotation SummarizationSetBy = Automatic

	column 'Long Note 3'
		dataType: string
		sourceProviderType: varchar(500)
		lineageTag: d585f516-9c29-44a1-9fae-fc48af81b479
		summarizeBy: none
		sourceColumn: Long Note 3

		annotation SummarizationSetBy = Automatic

	column 'Long Note 4'
		dataType: string
		sourceProviderType: varchar(500)
		lineageTag: a43ddfc0-29db-4ab6-8b9b-8c9ddfb39520
		summarizeBy: none
		sourceColumn: Long Note 4

		annotation SummarizationSetBy = Automatic

	column 'Long Note 5'
		dataType: string
		sourceProviderType: varchar(500)
		lineageTag: 70a14639-2e07-45b7-a8cf-d81ce5004ed1
		summarizeBy: none
		sourceColumn: Long Note 5

		annotation SummarizationSetBy = Automatic

	column 'Trader Desk'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 0cec54e6-cbcd-40d3-8189-fa24a2c02791
		summarizeBy: none
		sourceColumn: Trader Desk

		annotation SummarizationSetBy = Automatic

	column 'Settle Days'
		dataType: double
		lineageTag: febcbd69-29cf-44a6-a6cb-95073e91b45c
		summarizeBy: none
		sourceColumn: Settle Days

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Transasofdate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: b242fa5e-8ed7-41db-afc5-5c4dedb644b4
		summarizeBy: none
		sourceColumn: Transasofdate

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Haircut
		dataType: double
		sourceProviderType: float
		lineageTag: 9f18be0c-6658-453d-b31e-606b6889cff6
		summarizeBy: sum
		sourceColumn: Haircut

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Trading Comment'
		dataType: string
		sourceProviderType: varchar(500)
		lineageTag: 5778744c-e638-4067-8e47-3cdea8cd9e40
		summarizeBy: none
		sourceColumn: Trading Comment

		annotation SummarizationSetBy = Automatic

	column 'Transaction Purpose'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: cf05f759-33e1-4616-81a9-4c5a3495a7fd
		summarizeBy: none
		sourceColumn: Transaction Purpose

		annotation SummarizationSetBy = Automatic

	column 'Original System Tran Number'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: a1fea357-001a-49da-a903-a94fc8c5f978
		summarizeBy: none
		sourceColumn: Original System Tran Number

		annotation SummarizationSetBy = Automatic

	column 'Interest Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		sourceProviderType: datetime2
		lineageTag: 86706d64-02c1-49ae-9c4d-984f80454e48
		summarizeBy: none
		sourceColumn: Interest Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Region
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: d28b2323-9fdb-4563-819b-6e0f4b5868b1
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Valuation Cycle'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: f548c6f5-31e4-485e-9615-9e74e77b9e0b
		summarizeBy: none
		sourceColumn: Valuation Cycle

		annotation SummarizationSetBy = Automatic

	column 'Post Time'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: a88a067b-ae65-46cd-b1b5-ac25f6edc5ef
		summarizeBy: none
		sourceColumn: Post Time

		annotation SummarizationSetBy = Automatic

	column 'Backpost Month'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 3c615ac8-c4bb-4df0-9573-188681b7eaea
		summarizeBy: none
		sourceColumn: Backpost Month

		annotation SummarizationSetBy = Automatic

	column 'Trader Login'
		dataType: string
		sourceProviderType: varchar(100)
		lineageTag: 9b58071f-172f-44f2-ae9d-ae7f89ec4cf8
		summarizeBy: none
		sourceColumn: Trader Login

		annotation SummarizationSetBy = Automatic

	column 'Bloomberg Timestamp'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		sourceProviderType: datetime
		lineageTag: 6e790eba-83b5-48b7-85c9-d65ca742469e
		summarizeBy: none
		sourceColumn: Bloomberg Timestamp

		annotation SummarizationSetBy = Automatic

	column Backposted = ```
			
			IF (
			    'Securities Transaction GA Fact'[Backpost Month] = "Y",
			    "Backposted",
			    BLANK ()
			)
			
			```
		lineageTag: ba733489-14a8-4322-b95c-5d1a9dec8d7c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Accounting Unit Code & Name'
		dataType: string
		lineageTag: feefdd95-63e0-48cf-9f21-3d4a054dca3e
		summarizeBy: none
		sourceColumn: Accounting Unit Code & Name

		annotation SummarizationSetBy = Automatic

	column 'Company Code & Name'
		dataType: string
		lineageTag: f76bb1e2-f7a1-4d06-b577-8d8f08f10eae
		summarizeBy: none
		sourceColumn: Company Code & Name

		annotation SummarizationSetBy = Automatic

	column 'Trans Category'
		dataType: string
		lineageTag: bed5fd7c-5777-4efc-97d1-4274b8095f73
		summarizeBy: none
		sourceColumn: Trans Category

		annotation SummarizationSetBy = Automatic

	column 'Trans Type'
		dataType: string
		lineageTag: 7e5f4be7-e564-45bb-90a4-69739d08fdd1
		summarizeBy: none
		sourceColumn: Trans Type

		annotation SummarizationSetBy = Automatic

	column 'Framework Code'
		dataType: string
		lineageTag: e2e37f6d-72af-4d5c-9473-4e2c4090a868
		summarizeBy: none
		sourceColumn: Framework Code

		annotation SummarizationSetBy = Automatic

	column 'GL Class'
		dataType: string
		lineageTag: 58d7cf54-bb23-4722-a866-b1114f81f650
		summarizeBy: none
		sourceColumn: GL Class

		annotation SummarizationSetBy = Automatic

	column 'Counterparty Code'
		dataType: string
		lineageTag: b873ed2d-b191-4883-8fc9-b08000d534d5
		summarizeBy: none
		sourceColumn: Counterparty Code

		annotation SummarizationSetBy = Automatic

	column 'Counterparty Name'
		dataType: string
		lineageTag: 558f0246-5048-4720-b974-0125108c8cbe
		summarizeBy: none
		sourceColumn: Counterparty Name

		annotation SummarizationSetBy = Automatic

	column 'Functional Ccy Code'
		dataType: string
		lineageTag: 8ba88b3a-90db-4540-aaf3-2942a2f39ef9
		summarizeBy: none
		sourceColumn: Functional Ccy Code

		annotation SummarizationSetBy = Automatic

	column 'Local To FUNC Rate'
		dataType: double
		lineageTag: 215cae2e-4a21-4c83-94fa-3709d2f27c5f
		summarizeBy: none
		sourceColumn: Local To FUNC Rate

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local To CAD Rate'
		dataType: double
		lineageTag: 9f51a32e-8c8e-4517-b34a-209a9e4111ad
		summarizeBy: none
		sourceColumn: Local To CAD Rate

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local To USD Rate'
		dataType: double
		lineageTag: 1cb4b689-fa46-4d14-94dc-97e672df0b0c
		summarizeBy: none
		sourceColumn: Local To USD Rate

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local To HKD Rate'
		dataType: double
		lineageTag: 16539fdd-2c59-4166-8b64-2b14d8b20e9f
		summarizeBy: none
		sourceColumn: Local To HKD Rate

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Transaction Amount'
		dataType: double
		lineageTag: c445309a-4cc8-4ea6-acc9-967de47162ef
		summarizeBy: sum
		sourceColumn: Transaction Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Month End Trans' = ```
			
			IF (
			    'Securities Transaction GA Fact'[Transasofdate]
			        = EOMONTH ( 'Securities Transaction GA Fact'[Transasofdate], 0 ),
			    "Month End",
			    "Non Month End"
			)
			
			```
		lineageTag: 3c5649c6-4470-4aa6-893c-65d1ddd5adca
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column PortSecKey = ```
			
			'Securities Transaction GA Fact'[Portfolio Code] & " - "
			    & 'Securities Transaction GA Fact'[Src Security ID]
			
			```
		lineageTag: 3f336662-cb20-4733-8ac7-421870745dc3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Code & Name'
		dataType: string
		lineageTag: 8387212e-a393-4e2a-be86-5ad15c218a9f
		summarizeBy: none
		sourceColumn: Portfolio Code & Name

		annotation SummarizationSetBy = Automatic

	column 'Asset Type (Sec Tran-Slicer)' = RELATED('Securities'[Asset Type])
		lineageTag: 5f9437b0-3c63-4772-8474-091decd8bce8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Asset Class (Sec Tran)' = RELATED('Securities'[Asset Class])
		lineageTag: 968c4f65-041c-4502-b804-351f7152bac8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'SCD Sec Type (Sec Tran-Slicer)' = RELATED('Securities'[SCD Security Type])
		lineageTag: 76c88d23-7269-4d36-8506-5db8406bd55b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Actual Settle Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 82dc2b93-3670-49d0-ae5f-c7e49abbf335
		summarizeBy: none
		sourceColumn: Actual Settle Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'As Of Period'
		dataType: int64
		formatString: 0
		lineageTag: c7776414-d1a0-4ad7-8a20-52bc93f4e0bd
		summarizeBy: max
		sourceColumn: As Of Period

		annotation SummarizationSetBy = User

	column 'Portfolio NK'
		dataType: string
		lineageTag: 0cd10dfc-e649-4292-a5f1-83cfe2e21c94
		summarizeBy: none
		sourceColumn: Portfolio NK

		annotation SummarizationSetBy = Automatic

	column 'Match Src Transaction ID'
		dataType: string
		lineageTag: fe293f11-7bd5-43d3-859c-1a3e60d4d134
		summarizeBy: none
		sourceColumn: Match Src Transaction ID

		annotation SummarizationSetBy = Automatic

	column 'Bus Trans Code'
		dataType: string
		lineageTag: 6462d425-c86a-4798-8230-14651b897193
		summarizeBy: none
		sourceColumn: Bus Trans Code

		annotation SummarizationSetBy = Automatic

	column Materiality
		dataType: double
		lineageTag: c1b43c9b-ddc8-4f32-b33c-d4ea6a2d0f2e
		summarizeBy: none
		sourceColumn: Materiality

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Late days' =
			
			--Add Late, i.e Post date minus trade date
			SUBSTITUTE(DATEDIFF('Securities Transaction GA Fact'[Post Date],'Securities Transaction GA Fact'[Transasofdate],DAY),"-","")
		lineageTag: 630f274a-ecd8-4c9b-8043-d77ed2c9a18e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Grand Total' = "Total"
		lineageTag: 77327dd4-9bfd-4fed-8ade-ce94644d62f5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Bus Trans Number'
		dataType: int64
		formatString: 0
		lineageTag: b901d228-537e-473c-972a-87eedc795386
		summarizeBy: sum
		sourceColumn: Bus Trans Number

		annotation SummarizationSetBy = Automatic

	column 'Settle days CC' =
			
			--DATEDIFF(DAY,TRADE_DT,SETTLE_DT)
			DATEDIFF('Securities Transaction GA Fact'[Transasofdate],'Securities Transaction GA Fact'[Settle Date],DAY)
		formatString: 0
		lineageTag: dc6eb9dc-8fba-49cf-819f-ac5f1e752a18
		summarizeBy: none

		annotation SummarizationSetBy = User

	column 'Src Security ID'
		dataType: string
		lineageTag: e946cd8c-a8c8-4de8-8f53-9d86fca53502
		summarizeBy: none
		sourceColumn: Src Security ID

		annotation SummarizationSetBy = Automatic

	column 'Final Reporting Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 7c30b08d-7a3b-4963-a999-3bace6bb39ae
		summarizeBy: none
		sourceColumn: Final Reporting Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Price - Local (D)'
		dataType: double
		lineageTag: 2df6f7c5-fa02-47d9-bedf-7202bb334681
		summarizeBy: sum
		sourceColumn: Price - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Primary Security ID & Desc (Sec Tran)' =
			
			RELATED('Securities'[Primary Security ID & Desc])
		lineageTag: 824498c0-cfdf-4fbe-aa58-4e4bc44d9a81
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Post Date Filter' = IF ( DATEVALUE ( [Transasofdate] ) < DATEVALUE ( [Post Date] ), 1, 0 )
		formatString: 0
		lineageTag: 07a9438d-a855-4c1b-bdeb-9d2a4dcd71b4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Base Portfolio Value' = RELATED(Portfolios[Base Portfolio Value (D)])
		isHidden
		lineageTag: fcb89b5a-99ba-4e3c-a62c-97d4181f4dc5
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Primary Security ID (Sec Tran)' = RELATED('Securities'[Primary Security ID])
		lineageTag: 81d4d661-61ff-4c84-9585-760f9c9ab2b2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Bus Trans Subcategory'
		dataType: string
		lineageTag: 84f01725-4e6a-438b-995b-ad87955a3f96
		summarizeBy: none
		sourceColumn: Bus Trans Subcategory

		annotation SummarizationSetBy = Automatic

	column 'Elementary Trans Code '
		dataType: string
		lineageTag: 232be965-d18f-4477-b8b8-c700d269ee05
		summarizeBy: none
		sourceColumn: "Elementary Trans Code "

		annotation SummarizationSetBy = Automatic

	column 'Payment Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 21f99644-582f-4d06-9ddc-987e8429818a
		summarizeBy: none
		sourceColumn: Payment Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Underlier Maturity Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 59263fb3-9424-43c3-81ef-0e8537ba086b
		summarizeBy: none
		sourceColumn: Underlier Maturity Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Underlier Next Coupon Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: c955a855-29b1-47f0-957d-eb7106ff1404
		summarizeBy: none
		sourceColumn: Underlier Next Coupon Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Underlier Coupon'
		dataType: string
		lineageTag: 36bb54ac-d9ce-43c8-9785-dcfb2b912dd1
		summarizeBy: none
		sourceColumn: Underlier Coupon

		annotation SummarizationSetBy = Automatic

	column Contracts
		dataType: double
		lineageTag: 40d6f3c6-28df-47d8-97b8-0ace78602100
		summarizeBy: sum
		sourceColumn: Contracts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ClassCode
		dataType: string
		lineageTag: fdccbd83-4091-4902-8295-fc3ff8425e0c
		summarizeBy: none
		sourceColumn: ClassCode

		annotation SummarizationSetBy = Automatic

	column 'Current Value - Local'
		dataType: double
		lineageTag: 92d2c439-fce5-4a98-a737-d07deafb5c42
		summarizeBy: sum
		sourceColumn: Current Value - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Trans Price Local'
		dataType: double
		lineageTag: 65d93c84-350b-48c8-b0e6-f7c9e11f2572
		summarizeBy: sum
		sourceColumn: Trans Price Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Original Cost - Base'
		dataType: double
		lineageTag: 296145f4-b649-4f73-aece-2f8c16b415d4
		summarizeBy: sum
		sourceColumn: Original Cost - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Original Cost - Local'
		dataType: double
		lineageTag: d1b235d5-dee0-44d6-a88a-17bdba9b3b4a
		summarizeBy: sum
		sourceColumn: Original Cost - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Amortized Cost - Base'
		dataType: double
		isHidden
		lineageTag: 3bca74a0-0212-4fab-87d4-922f81de4a3e
		summarizeBy: sum
		sourceColumn: Amortized Cost - Base

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Based on User request, we have unhidden the "Amortized Cost - Local" column in the "Securities" and "Current Year’s Securities" reports, and renamed it to "Sec Amortization Cost Local" to prevent confusion. For more details, please refer to Jira #GOGARPT-2154.
	column 'Sec Amortization Cost Local'
		dataType: double
		lineageTag: 3c277974-23ab-4a9b-9c53-611fca058787
		summarizeBy: sum
		sourceColumn: Sec Amortization Cost Local

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Realized Gain/Loss CCY - Base'
		dataType: double
		lineageTag: 3266cb57-d62a-4a25-ae82-17e9474a78de
		summarizeBy: sum
		sourceColumn: Realized Gain/Loss CCY - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Realized Gain/Loss Sec - Base'
		dataType: double
		lineageTag: e1a37aad-8400-4277-b9c6-1bced35e3710
		summarizeBy: sum
		sourceColumn: Realized Gain/Loss Sec - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Realized Gain/Loss - Base'
		dataType: double
		lineageTag: 40b3dd1b-c8d2-4747-a370-9388bbea1583
		summarizeBy: sum
		sourceColumn: Realized Gain/Loss - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Realized Gain/Loss - Local'
		dataType: double
		lineageTag: b4e63211-0227-458d-9f59-f2f0f9c6bb56
		summarizeBy: sum
		sourceColumn: Realized Gain/Loss - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'OID Amortization/Accretion - Base'
		dataType: double
		lineageTag: 224143dd-1338-42c6-b8ce-eadf90dcb97d
		summarizeBy: sum
		sourceColumn: OID Amortization/Accretion - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'OID Amortization/Accretion - Local'
		dataType: double
		lineageTag: 30836419-28fa-4182-a274-1d3793c3d68f
		summarizeBy: sum
		sourceColumn: OID Amortization/Accretion - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Imp Amount - Base'
		dataType: double
		lineageTag: 4381946c-682a-4b75-b41d-76d927f80ddf
		summarizeBy: sum
		sourceColumn: Imp Amount - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Imp Amount - Local'
		dataType: double
		lineageTag: 50eb2b11-4e83-43d2-b647-427432c1ecc2
		summarizeBy: sum
		sourceColumn: Imp Amount - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Income Gross Amount - Base'
		dataType: double
		lineageTag: a36b50de-684b-48fa-9a1a-5ce458724a30
		summarizeBy: sum
		sourceColumn: Income Gross Amount - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Income Gross Amount - Local'
		dataType: double
		lineageTag: cf93a9f5-e635-4a98-a907-65cadb9d0a7b
		summarizeBy: sum
		sourceColumn: Income Gross Amount - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Purpose
		dataType: string
		lineageTag: c7310ec9-cf29-480d-8069-7fa390ce7f40
		summarizeBy: none
		sourceColumn: Purpose

		annotation SummarizationSetBy = Automatic

	column 'Country Name'
		dataType: string
		lineageTag: 65699a67-cd20-4b7c-8ad7-e44d4db72450
		summarizeBy: none
		sourceColumn: Country Name

		annotation SummarizationSetBy = Automatic

	column 'Tran Hub ID'
		dataType: string
		lineageTag: b3f3b4e7-fb1c-4c69-aba1-8502108d81e8
		summarizeBy: none
		sourceColumn: Tran Hub ID

		annotation SummarizationSetBy = Automatic

	column 'Fx Swap Ticket Number'
		dataType: string
		lineageTag: fff76d5f-92ab-4d4a-98f0-98b5762e2e0c
		summarizeBy: none
		sourceColumn: Fx Swap Ticket Number

		annotation SummarizationSetBy = Automatic

	column 'Tax Lot Ix'
		dataType: string
		lineageTag: b1c8472c-e751-44af-889a-3c31c26b94a5
		summarizeBy: none
		sourceColumn: Tax Lot Ix

		annotation SummarizationSetBy = Automatic

	column 'Lot Source Transaction ID'
		dataType: string
		lineageTag: a972e05a-1b5c-4181-a9de-6f48881236fc
		summarizeBy: none
		sourceColumn: Lot Source Transaction ID

		annotation SummarizationSetBy = Automatic

	column 'Lot ID'
		dataType: string
		lineageTag: 27e0385b-8a7c-45b7-985c-273ecb728a93
		summarizeBy: none
		sourceColumn: Lot ID

		annotation SummarizationSetBy = Automatic

	column 'Asia Asset Class Code Indonesia'
		dataType: string
		lineageTag: 34fdaa1c-36be-441c-9999-d48c2a0a32ca
		summarizeBy: none
		sourceColumn: Asia Asset Class Code Indonesia

		annotation SummarizationSetBy = Automatic

	column 'Asia Asset Class Code Vietnam'
		dataType: string
		lineageTag: 813fd898-9b93-4482-b562-d2e3b767ded4
		summarizeBy: none
		sourceColumn: Asia Asset Class Code Vietnam

		annotation SummarizationSetBy = Automatic

	column 'Asia Asset Class Desc Indonesia'
		dataType: string
		lineageTag: 4c24db07-a71e-4eb2-98b9-829ad8b56374
		summarizeBy: none
		sourceColumn: Asia Asset Class Desc Indonesia

		annotation SummarizationSetBy = Automatic

	column 'Asia Asset Class Desc Vietnam'
		dataType: string
		lineageTag: 0f9fa2c1-eb98-454c-bf74-9dbf502eae80
		summarizeBy: none
		sourceColumn: Asia Asset Class Desc Vietnam

		annotation SummarizationSetBy = Automatic

	column 'Group Structure Relation'
		dataType: string
		lineageTag: b255b62f-de19-4743-80d4-b030772d5a42
		summarizeBy: none
		sourceColumn: Group Structure Relation

		annotation SummarizationSetBy = Automatic

	column 'Book Value - Local unsigned'
		dataType: double
		lineageTag: 6bcf9db6-954b-456f-9512-d767beff9722
		summarizeBy: sum
		sourceColumn: Book Value - Local unsigned

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Book Value - Base unsigned'
		dataType: double
		lineageTag: 58574750-bcb7-40f6-9e36-5c511d6c5dac
		summarizeBy: sum
		sourceColumn: Book Value - Base unsigned

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Int Apr - Local'
		dataType: double
		lineageTag: 3001c79d-f976-4a08-ba76-042092480030
		summarizeBy: sum
		sourceColumn: Int Apr - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Int Apr - Base'
		dataType: double
		lineageTag: b116e855-842d-4e34-b471-6cb190f186ab
		summarizeBy: sum
		sourceColumn: Int Apr - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ECL Loss - Local'
		dataType: double
		lineageTag: 251d42f5-51c9-433f-a5f4-32953d0a5173
		summarizeBy: sum
		sourceColumn: ECL Loss - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ECL Loss - Base'
		dataType: double
		lineageTag: 05c136ca-6e0b-4315-ae51-043ee4b930b5
		summarizeBy: sum
		sourceColumn: ECL Loss - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CECL Loss - Local'
		dataType: double
		lineageTag: 7db912a4-cf64-4dd1-af11-6b7b7b8c7c61
		summarizeBy: sum
		sourceColumn: CECL Loss - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CECL Loss - Base'
		dataType: double
		lineageTag: ce51f332-0caf-4b88-8e62-bd66d86ae75d
		summarizeBy: sum
		sourceColumn: CECL Loss - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Impairment - Local'
		dataType: double
		lineageTag: f8a2f695-cbfe-41a4-b16f-4b7fe44a1b7c
		summarizeBy: sum
		sourceColumn: Impairment - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Impairment - Base'
		dataType: double
		lineageTag: d5a11b77-b01a-417d-a2b7-2e2b487467c7
		summarizeBy: sum
		sourceColumn: Impairment - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'REA AOCI BV - Local'
		dataType: double
		lineageTag: 8550c980-0365-41c4-9587-3214f8d58f65
		summarizeBy: sum
		sourceColumn: REA AOCI BV - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'REA AOCI BV - Base'
		dataType: double
		lineageTag: 8ea050a2-161a-45aa-8d26-c2475c514a81
		summarizeBy: sum
		sourceColumn: REA AOCI BV - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Deferred PL - Local'
		dataType: double
		lineageTag: e080cee5-758c-4f0f-9d82-9828cecfa557
		summarizeBy: sum
		sourceColumn: Deferred PL - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Deferred PL - Base'
		dataType: double
		lineageTag: 0752b501-aa45-426a-b348-e39a060a05b7
		summarizeBy: sum
		sourceColumn: Deferred PL - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Realized Gain/Loss Book - Local'
		dataType: double
		lineageTag: 6f2d51b0-752d-4d12-a84a-9615621f5944
		summarizeBy: sum
		sourceColumn: Realized Gain/Loss Book - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Realized Gain/Loss Book - Base'
		dataType: double
		lineageTag: edad4db6-d09e-442d-ba30-882e294bac9d
		summarizeBy: sum
		sourceColumn: Realized Gain/Loss Book - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost Value - Local unsigned'
		dataType: double
		lineageTag: 29b52580-4a83-4d5f-81c7-95bd81899617
		summarizeBy: sum
		sourceColumn: Cost Value - Local unsigned

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost Value - Base unsigned'
		dataType: double
		lineageTag: bdaf1e6b-2294-49c0-8fae-cb168b936570
		summarizeBy: sum
		sourceColumn: Cost Value - Base unsigned

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'OID Int Appr - Local'
		dataType: double
		lineageTag: 80b3586d-2519-42b7-b03f-181dd0d7d9af
		summarizeBy: sum
		sourceColumn: OID Int Appr - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'OID Int Appr - Base'
		dataType: double
		lineageTag: e8fa9c06-1992-45cd-8927-41fb57e7b05e
		summarizeBy: sum
		sourceColumn: OID Int Appr - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Real Int Appr - Base'
		dataType: double
		lineageTag: 6b468796-04e5-4aee-b08f-b0e9c1818a08
		summarizeBy: sum
		sourceColumn: Real Int Appr - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Real Int Appr - Local'
		dataType: double
		lineageTag: 5853c3dd-8bcd-4fbb-a59c-5b07b8c11eea
		summarizeBy: sum
		sourceColumn: Real Int Appr - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Con CL Allow - Base'
		dataType: double
		lineageTag: 82d1a3bd-34f4-4cd7-9d77-a7333f5d0d8f
		summarizeBy: sum
		sourceColumn: Con CL Allow - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Con CL Allow - Local'
		dataType: double
		lineageTag: 272e4675-553d-45f6-8b67-9ed9fd92a33c
		summarizeBy: sum
		sourceColumn: Con CL Allow - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Change AOCI BV - Base'
		dataType: double
		lineageTag: a859abcf-42c3-4ed4-9cf5-72cd386d4678
		summarizeBy: sum
		sourceColumn: Change AOCI BV - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Change AOCI BV - Local'
		dataType: double
		lineageTag: a8471795-703b-4260-8b33-2a0cf4909000
		summarizeBy: sum
		sourceColumn: Change AOCI BV - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Change AOCI NONBV - Base'
		dataType: double
		lineageTag: 838a140c-e1b1-42dc-a715-1d3f8f2849f7
		summarizeBy: sum
		sourceColumn: Change AOCI NONBV - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Change AOCI NONBV - Local'
		dataType: double
		lineageTag: 3314de99-3028-43ca-af79-31541820635b
		summarizeBy: sum
		sourceColumn: Change AOCI NONBV - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Lot Nominal'
		dataType: double
		lineageTag: 476fe9cf-a63e-4bfe-9c3b-5a6876654417
		summarizeBy: sum
		sourceColumn: Lot Nominal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unpaid Amount - Local (D)'
		dataType: double
		lineageTag: 4b61cc82-56ef-4cdc-b3a2-e74cdd04fc96
		summarizeBy: sum
		sourceColumn: Unpaid Amount - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Payment Amount - Base'
		dataType: double
		lineageTag: 560179c1-7186-46d0-8800-629bbc726760
		summarizeBy: sum
		sourceColumn: Payment Amount - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nominal Outgoing Amount'
		dataType: double
		lineageTag: 46032af5-086b-4ebb-ab55-3cfd4736bb0d
		summarizeBy: sum
		sourceColumn: Nominal Outgoing Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nominal Incoming Amount'
		dataType: double
		lineageTag: 01a0a167-9835-4be6-a2d4-ce7b72667bd7
		summarizeBy: sum
		sourceColumn: Nominal Incoming Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Amount - Local'
		dataType: double
		lineageTag: 03a6daaa-89c3-4438-b2fc-e1d266b91eca
		summarizeBy: sum
		sourceColumn: Net Amount - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Hedge Findur ID'
		dataType: string
		lineageTag: e2f96347-4c6d-49aa-83fe-4f2eb7e5cacb
		summarizeBy: none
		sourceColumn: AOCI Hedge Findur ID

		annotation SummarizationSetBy = Automatic

	column 'Updated Ts'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		lineageTag: 8560bb8c-5cba-4379-bce2-2e02b2b1675b
		summarizeBy: none
		sourceColumn: Updated Ts

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column From/To = ```
			
			SWITCH(TRUE(),
			    'Securities Transaction GA Fact'[Nominal Incoming Amount] <> 0, "To",
			    'Securities Transaction GA Fact'[Nominal Outgoing Amount] <> 0,"From",
			    BLANK ()
			    )
			
			```
		lineageTag: cac364dc-4288-4bc3-b30c-40b20abbb3db
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Par/NonPar = RELATED(Portfolios[Par Nonpar])
		lineageTag: 48142acd-bab7-4d5b-a954-ae85aa6e3722
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Product = RELATED('Accounting Unit'[Insurance Product Name])
		lineageTag: 3d149c2e-649b-46d6-a75d-fe55c151d2c7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Transfer Type (BV vs MV)' = ```
			
			SWITCH (
			    TRUE(),
			    NOT ( ISBLANK ( 'Securities Transaction GA Fact'[Transaction Purpose] ) ),"BV Transfer",
			    NOT ( ISBLANK ( 'Securities Transaction GA Fact'[Group Structure Relation] ) ),"MV Transfer",
			    BLANK ()
			    )
			
			
			```
		lineageTag: e930c894-103d-4618-a26a-742f449bf395
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Transfer Purpose (Inter or Intra)' = ```
			
			COALESCE (
			    'Securities Transaction GA Fact'[Transaction Purpose],
			    'Securities Transaction GA Fact'[Group Structure Relation]
			)
			
			```
		lineageTag: 34fb593b-8d1c-4b1f-922a-ba4066bd4a03
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'SCD Security Type (Sec Tran)' = RELATED('Securities'[SCD Security Type])
		displayFolder: Security Values
		lineageTag: b785f5b0-3ad6-4bbe-9cdb-0461b3023fc4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Asset Group (Sec Tran)' = RELATED('Securities'[Asset Group])
		displayFolder: Security Values
		lineageTag: dd4e3f22-ab8b-441a-b3a6-e871db0af5e9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Company Code & Name Display' =
			
			IF (
			    'Securities Transaction GA Fact'[Company Code & Name]
			        IN { "Not Applicable - Not Applicable", "Not Available - Not Available" },
			    "9999 - Off Balance Sheet Company",
			    'Securities Transaction GA Fact'[Company Code & Name]
			)
		lineageTag: 3261fa5f-efa6-4415-9eb3-c84bb947e501
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Accounting Unit Code & Name Display' =
			
			IF (
			    'Securities Transaction GA Fact'[Accounting Unit Code & Name]
			        IN {"Not Applicable - Not Applicable", "Not Available - Not Available" },
			    "9999 - Off Balance Sheet Acct Unit",
			    'Securities Transaction GA Fact'[Accounting Unit Code & Name]
			)
		lineageTag: d5a49bfa-36aa-4655-9c58-e21e807416a4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Tr Freecomment'
		dataType: string
		lineageTag: 3b6aa99d-dcd5-4b1f-84c9-e822e8a4c482
		summarizeBy: none
		sourceColumn: Tr Freecomment

		annotation SummarizationSetBy = Automatic

	column 'Trans Status Actual'
		dataType: string
		lineageTag: c1f6059b-ab3d-49b5-8cec-f101c123f765
		summarizeBy: none
		sourceColumn: Trans Status Actual

		annotation SummarizationSetBy = Automatic

	column 'Total Cash Proceeds'
		dataType: double
		lineageTag: c23d005b-0461-4def-ab89-0aec95c5a551
		summarizeBy: max
		sourceColumn: Total Cash Proceeds

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Interest Trade Local'
		dataType: double
		lineageTag: e7d2dd62-e579-475f-95db-9b9656fd19ba
		summarizeBy: sum
		sourceColumn: Interest Trade Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Units/Quantity
		dataType: double
		lineageTag: 93f0d281-e520-4101-8f8c-7855993a3a1a
		summarizeBy: sum
		sourceColumn: Units/Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Processed Ind' = "Y"
		lineageTag: 04a7f6ee-c794-4f7c-9454-a8b162a8a74e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Data Source' = "TOA"
		lineageTag: 1ac6c738-0a04-4886-9bb6-fda846a5bf8d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Post Hour' = HOUR('Securities Transaction GA Fact'[Post Time])
		formatString: 0
		lineageTag: 71cdb13a-2d91-4aab-bbb4-27795beebb95
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Reference Security ID'
		dataType: string
		sourceProviderType: nvarchar(20)
		lineageTag: a931dadb-c754-43d7-ab6c-0e314e909c32
		summarizeBy: none
		sourceColumn: Reference Security ID

		annotation SummarizationSetBy = Automatic

	column 'Master Ticket Number'
		dataType: string
		sourceProviderType: nvarchar(50)
		lineageTag: 0912e7bb-22ff-44ad-8100-513edc1faf1a
		summarizeBy: none
		sourceColumn: Master Ticket Number

		annotation SummarizationSetBy = Automatic

	column 'Original System'
		dataType: string
		sourceProviderType: nvarchar(20)
		lineageTag: 350f76ef-85af-40be-9582-9a07d373efb4
		summarizeBy: none
		sourceColumn: Original System

		annotation SummarizationSetBy = Automatic

	column 'Trade Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		sourceProviderType: date
		lineageTag: ae72462c-c81f-4d16-8cc9-d1a1037411e4
		summarizeBy: none
		sourceColumn: Trade Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Changed Date'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		sourceProviderType: datetime2
		lineageTag: e9cebe1c-80f0-44d2-82e9-7f96f5cf7d41
		summarizeBy: none
		sourceColumn: Changed Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Book Value - Base' = 'Securities Transaction GA Fact'[Book Value - Base unsigned]*'Securities Transaction GA Fact'[Sign]
		isHidden
		lineageTag: f71d904a-b3c6-4df9-bb6d-87aa5858cb65
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Book Value - Local (D)' = 'Securities Transaction GA Fact'[Book Value - Local unsigned]*'Securities Transaction GA Fact'[Sign]
		isHidden
		lineageTag: 921c696d-9bd3-487e-a5ac-feecd110d3ea
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost Value - Local (D)' = 'Securities Transaction GA Fact'[Cost Value - Local unsigned]*'Securities Transaction GA Fact'[Sign]
		isHidden
		lineageTag: 8ad767cf-98cc-4365-8d5c-c651576c37d1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost Value - Base' = 'Securities Transaction GA Fact'[Cost Value - Base unsigned]*'Securities Transaction GA Fact'[Sign]
		lineageTag: 61bd6f85-a43f-4f71-be7b-1081abc3905f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Security NK'
		dataType: string
		lineageTag: 19748016-aac8-49ea-a64b-f012f84c1326
		summarizeBy: none
		sourceColumn: Security NK

		annotation SummarizationSetBy = Automatic

	column 'ALT INV TRANS TYPE'
		dataType: string
		lineageTag: 6453c473-fb82-4ccc-b390-0afd40922231
		summarizeBy: none
		sourceColumn: ALT INV TRANS TYPE

		annotation SummarizationSetBy = Automatic

	column Cost_NK =
			
			'Securities Transaction GA Fact'[Originating System No]&"/"&
			'Securities Transaction GA Fact'[Source]&"/"&
			'Securities Transaction GA Fact'[Bus Trans Number]&"/"&
			'Securities Transaction GA Fact'[Source ID]
		lineageTag: 4767d05e-2270-4627-a127-0a61e392d56d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 6ff56ccf-37f7-4428-970a-6e80500fd405
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column 'Originating System No'
		dataType: double
		lineageTag: 6cc9cf26-db9c-4ea4-b432-99786d38ddc9
		summarizeBy: sum
		sourceColumn: Originating System No

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Nominal To Match'
		dataType: double
		lineageTag: ff786b9f-8a82-4849-a7b4-9e4918f5b400
		summarizeBy: sum
		sourceColumn: Nominal To Match

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Country (Sec Tran)' = RELATED('Securities'[Country])
		lineageTag: 746e02e4-b007-431c-948e-8ff8048127d3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Issuer Long Comp Name (Sec Tran)' = RELATED(Securities[Issuer Long Comp Name])
		lineageTag: 05f2fd41-6844-4b46-8b76-3f4e666cad66
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'POS Trans Link'
		dataType: string
		lineageTag: ea180778-e1a9-4898-8282-c3beae6c8b30
		summarizeBy: none
		sourceColumn: POS Trans Link

		annotation SummarizationSetBy = Automatic

	column 'Long Short Ind'
		dataType: string
		lineageTag: 9443692c-789e-42ba-9699-88bcae00170c
		summarizeBy: none
		sourceColumn: Long Short Ind

		annotation SummarizationSetBy = Automatic

	column 'SCD Coupon Rate'
		dataType: double
		lineageTag: a406f5a5-a9c7-477a-92e7-f7846eb41eea
		summarizeBy: sum
		sourceColumn: SCD Coupon Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Yield For Math Adj'
		dataType: double
		lineageTag: 61f02fa0-8d3c-4bd2-a8e1-524e1f2b0807
		summarizeBy: max
		sourceColumn: Yield For Math Adj

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Bloomberg Tansaction Identifier'
		dataType: double
		lineageTag: f78270d2-96ef-4452-b7fd-0fe4e8b2f785
		summarizeBy: none
		sourceColumn: Bloomberg Tansaction Identifier

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Wash Sale Parent Lot Id'
		dataType: int64
		formatString: 0
		lineageTag: 937eb448-bf12-4cba-ba11-02743bd9f924
		summarizeBy: none
		sourceColumn: Wash Sale Parent Lot Id

		annotation SummarizationSetBy = User

	column 'Wash Sale Transaction Id'
		dataType: double
		lineageTag: 8a90060a-09ed-4be6-8c70-004955ffb528
		summarizeBy: none
		sourceColumn: Wash Sale Transaction Id

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'P Or L Book CCY Local'
		dataType: double
		lineageTag: 0c811354-674d-4e8e-96f7-655eb8e91bd1
		summarizeBy: sum
		sourceColumn: P Or L Book CCY Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'P Or L Book Sec Base CCY'
		dataType: double
		lineageTag: 057e546b-ea46-43a4-bda6-bc84b0021975
		summarizeBy: sum
		sourceColumn: P Or L Book Sec Base CCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Wash Sale Process ID'
		dataType: string
		lineageTag: e3a927e2-1912-4dcb-9f51-db50d386a760
		summarizeBy: none
		sourceColumn: Wash Sale Process ID

		annotation SummarizationSetBy = Automatic

	column 'Src Market Id (Sec Trans)' = RELATED(Securities[Src Market ID])
		lineageTag: 47de0e76-d52b-48e1-9c71-3fd252e18434
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Manulife Local Price'
		dataType: int64
		formatString: 0
		lineageTag: 6d0e8bb4-a9d3-4a75-bbba-57e145d99573
		summarizeBy: sum
		sourceColumn: Manulife Local Price

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Real Amortisation Base'
		dataType: double
		lineageTag: b76299c2-4b4b-4199-83a8-459eade907c4
		summarizeBy: sum
		sourceColumn: Real Amortisation Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Real Amortisation Local'
		dataType: double
		lineageTag: 00a735ad-6898-4384-8a00-6fdf0426c4b6
		summarizeBy: sum
		sourceColumn: Real Amortisation Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Booked Current Value Local'
		dataType: double
		lineageTag: e567c459-928f-4cd5-bff4-ed9439f098cb
		summarizeBy: sum
		sourceColumn: Booked Current Value Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Booked Current Value Base'
		dataType: double
		lineageTag: d36d247c-2e3a-4512-9e82-a9b739f1c2e7
		summarizeBy: sum
		sourceColumn: Booked Current Value Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unreal OID Accretion - Base'
		dataType: double
		lineageTag: 401d742f-e261-42eb-bdb3-b4f35c3f0e94
		summarizeBy: sum
		sourceColumn: Unreal OID Accretion - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unreal OID Accretion -  Local'
		dataType: double
		lineageTag: 148b0918-0099-4fde-9922-753c8d434556
		summarizeBy: sum
		sourceColumn: Unreal OID Accretion -  Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Actual Settle Date w/o Null' = COALESCE('Securities Transaction GA Fact'[Actual Settle Date],DATE(1900,1,1))
		formatString: yyyy-mm-dd
		lineageTag: 03dcb413-4ba5-443b-a4f2-26db65cc4ed0
		summarizeBy: none

		changedProperty = FormatString

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

		annotation UnderlyingDateTimeDataType = Date

	column 'Real OID Amortisation - Base'
		dataType: double
		lineageTag: 26ad56d5-7019-4e16-af3b-99a996264049
		summarizeBy: sum
		sourceColumn: Real OID Amortisation - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Real OID Amortisation - Local'
		dataType: double
		lineageTag: 4dcf18fc-5a92-4625-a109-80e848cfb3bb
		summarizeBy: sum
		sourceColumn: Real OID Amortisation - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Amortized Cost Ccy Corr Base'
		dataType: double
		lineageTag: 5eeb6cd6-86ab-4008-a415-07a5ddc1f668
		summarizeBy: sum
		sourceColumn: Amortized Cost Ccy Corr Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Amortized Cost Ccy Result Base'
		dataType: double
		lineageTag: fe352162-0dc3-4d65-a256-efa98dabbc35
		summarizeBy: sum
		sourceColumn: Amortized Cost Ccy Result Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Amortized Cost Sec Base'
		dataType: double
		lineageTag: 3d020fd0-bd87-4913-8047-fecec00c526e
		summarizeBy: sum
		sourceColumn: Amortized Cost Sec Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Amortized Cost Local'
		dataType: double
		lineageTag: 4e79cd71-897f-4121-8077-2fae67fe446c
		summarizeBy: sum
		sourceColumn: Amortized Cost Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Src Created Ts'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		lineageTag: 4243387f-5672-4a24-aeaf-baca56af03f2
		summarizeBy: none
		sourceColumn: Src Created Ts

		annotation SummarizationSetBy = Automatic

	column 'Src Updated Ts'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		lineageTag: 7bd0a692-a050-456f-9bfc-bdb093d86f18
		summarizeBy: none
		sourceColumn: Src Updated Ts

		annotation SummarizationSetBy = Automatic

	column Bucket
		dataType: string
		lineageTag: e397ebfc-1fc6-4f6e-8a10-cf07f902ab5c
		summarizeBy: none
		sourceColumn: Bucket

		annotation SummarizationSetBy = Automatic

	column 'Original Post Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d012f2e2-33e6-49c1-b403-44eb91d42af8
		summarizeBy: none
		sourceColumn: Original Post Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Settled Status'
		dataType: string
		lineageTag: 8474f52e-f073-46bd-baa5-df4d342b937f
		summarizeBy: none
		sourceColumn: Settled Status

		annotation SummarizationSetBy = Automatic

	column 'FX Join Key'
		dataType: string
		lineageTag: beaae7f1-8897-42bc-b3d4-256cc69428cb
		summarizeBy: none
		sourceColumn: FX Join Key

		annotation SummarizationSetBy = Automatic

	column 'Realised Impairment Local'
		dataType: double
		lineageTag: e9e4cb11-f087-4ebb-a99b-b020ddbffded
		summarizeBy: sum
		sourceColumn: Realised Impairment Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Realised Impairment Sec Base'
		dataType: double
		lineageTag: 6648f86f-005e-4e7a-86da-4173816c9975
		summarizeBy: sum
		sourceColumn: Realised Impairment Sec Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Realised Impairment Ccy Base'
		dataType: double
		lineageTag: d45251da-ae3f-4249-a3f3-1e1ede4fd611
		summarizeBy: sum
		sourceColumn: Realised Impairment Ccy Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dgl Inception Trans No'
		dataType: int64
		formatString: 0
		lineageTag: 9ba001e0-bc62-46a2-a92a-c819cbeddc28
		summarizeBy: sum
		sourceColumn: Dgl Inception Trans No

		annotation SummarizationSetBy = Automatic

	column 'IFRS9 Purpose'
		dataType: string
		sourceProviderType: varchar(250)
		lineageTag: 8cff7277-ca30-4075-bbfd-e551cc941983
		summarizeBy: none
		sourceColumn: IFRS9 Purpose

		annotation SummarizationSetBy = Automatic

	column 'Long Note 1'
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: 9f640d65-89e8-40ef-ad2a-fbd38b236079
		summarizeBy: none
		sourceColumn: Long Note 1

		annotation SummarizationSetBy = Automatic

	column 'Long Note 2'
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: f077e1c8-a35e-4e45-9fa0-dddd85c3d857
		summarizeBy: none
		sourceColumn: Long Note 2

		annotation SummarizationSetBy = Automatic

	column 'Long Note 6'
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: eed920e9-436d-4043-b2cb-17fe90be161d
		summarizeBy: none
		sourceColumn: Long Note 6

		annotation SummarizationSetBy = Automatic

	column 'Long Note 7'
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: 16263bbc-e15b-4aad-9f3d-2d6b3d68eb43
		summarizeBy: none
		sourceColumn: Long Note 7

		annotation SummarizationSetBy = Automatic

	column 'Long Note 8'
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: 7c292be5-e47a-408c-a56b-d2c3f8a86c3e
		summarizeBy: none
		sourceColumn: Long Note 8

		annotation SummarizationSetBy = Automatic

	column 'Short Note 1'
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: ca6d4b3e-44e9-442d-99d7-a6a2cfd32c59
		summarizeBy: none
		sourceColumn: Short Note 1

		annotation SummarizationSetBy = Automatic

	column 'Short Note 2'
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: c31b7f18-e069-4af6-be33-729ff66ecaaf
		summarizeBy: none
		sourceColumn: Short Note 2

		annotation SummarizationSetBy = Automatic

	column 'Short Note 3'
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: 4e9ef845-db7f-40e9-951b-c9024d5d61dc
		summarizeBy: none
		sourceColumn: Short Note 3

		annotation SummarizationSetBy = Automatic

	column 'Short Note 4'
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: ff36e406-ecb2-42a8-9297-eec9cdb6676d
		summarizeBy: none
		sourceColumn: Short Note 4

		annotation SummarizationSetBy = Automatic

	column 'Short Note 5'
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: 49df63e3-3f59-4611-afab-5028ab45171d
		summarizeBy: none
		sourceColumn: Short Note 5

		annotation SummarizationSetBy = Automatic

	column 'Short Note 6'
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: dffcca35-e4f2-4bc0-82b1-0abe91b4e8a5
		summarizeBy: none
		sourceColumn: Short Note 6

		annotation SummarizationSetBy = Automatic

	column 'Short Note 7'
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: 784bc202-c1f4-4dc1-9ee5-b323c1770713
		summarizeBy: none
		sourceColumn: Short Note 7

		annotation SummarizationSetBy = Automatic

	column 'Short Note 8'
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: bc82ef52-87f3-49f7-b2fc-6a0236b8bee6
		summarizeBy: none
		sourceColumn: Short Note 8

		annotation SummarizationSetBy = Automatic

	column 'Custodian Name'
		dataType: string
		lineageTag: fa24e031-a38b-45c5-8b8c-903bee0af8c0
		summarizeBy: none
		sourceColumn: Custodian Name

		annotation SummarizationSetBy = Automatic

	column 'User Change ID'
		dataType: string
		lineageTag: 05a9ce89-3ef5-4fce-a619-274a44b86ee1
		summarizeBy: none
		sourceColumn: User Change ID

		annotation SummarizationSetBy = Automatic

	column 'User Change Name'
		dataType: string
		lineageTag: bf60f1e4-7297-461b-a865-c85d62d207bc
		summarizeBy: none
		sourceColumn: User Change Name

		annotation SummarizationSetBy = Automatic

	column 'Processing Group Name'
		dataType: string
		lineageTag: b31f1943-8e56-408a-a7e9-4ed573001a6e
		summarizeBy: none
		sourceColumn: Processing Group Name

		annotation SummarizationSetBy = Automatic

	partition 'Securities Transaction GA Fact-e2d5e2aa-a5c1-4ab0-a001-ae4b2606fd03' = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs(HostName, HTTPPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null,CommandTimeout= #duration(0,5,0,0), EnableQueryResultDownload="0"]),
				    hive_metastore_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    inv_semantic_ga_Schema = hive_metastore_Database{[Name="inv_semantic_ga",Kind="Schema"]}[Data],
				    EDL_securities_transaction_ga_fact_dq = inv_semantic_ga_Schema{[Name="securities_transaction_ga_fact_dq",Kind="Table"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(EDL_securities_transaction_ga_fact_dq,{"TRANSACTION_NO", "LEG", "REVERSAL", "TRANS_STATUS", "PORTFOLIO_CD", "POST_DT", "PORTFOLIO_CODE_NM", "ACCOUNTING_UNIT_CODE_NAME", "COMPANY_CODE_NAME", "TRANS_CATEGORY", "BUS_TRANS_SUBCATEGORY", "TRANS_TYPE", "FRAMEWORK_CD", "GL_CLASS", "ELEMENTARY_TRANS_CODE", "PERIOD_CLOSE_DT", "POSTING_LAG", "TRADE_DT", "SETTLE_DT", "ACTUAL_SETTLE_DATE", "FINAL_REPORTING_DATE", "PAYMENT_DATE", "AS_OF_PERIOD", "PORTFOLIO_NK", "BLOOMBERG_NO", "MASTER_TICKET", "ORDER_NO", "SOURCE_ID", "MATCH_SRC_TRANSACTION_ID", "USER_NM", "SETTLE_CCY_CD", "SETTLE_CURRENCY", "LOCAL_CCY_CD", "LOCAL_CURRENCY", "UNDERLIER_MATURITY_DATE", "UNDERLIER_NEXT_COUPON_DATE", "UNDERLIER_COUPON", "SETTLE_EXCHANGE_RATE", "LOCAL_EXCHANGE_RATE", "SIGN", "UNITS", "POOL_FACTOR", "ORIGINAL_FACE", "CONTRACTS", "CURRENT_FACE", "NOMINAL_BASIS", "BROKER_CD", "BROKER_NM", "COUNTERPARTY_CODE", "COUNTERPARTY_NAME", "CMMT", "CLASS_CD", "BUS_TRANS_CODE", "MATERIALITY", "BASE_AMT", "SETTLE_AMT", "BASE_PRINCIPAL", "SETTLE_PRINCIPAL", "BASE_INTEREST", "SETTLE_INTEREST", "BASE_MATURITY_AMOUNT", "SETTLE_MATURITY_AMOUNT", "CURRENT_VALUE_CCY_LOCAL", "TRANS_PRICE_LOCAL", "BASE_PRICE", "PRICE_LOCAL", "SETTLE_PRICE", "ORIGINAL_COST_BASE", "ORIGINAL_COST_LOCAL", "AMORTIZED_COST_BASE", "AMORTIZED_COST_LOCAL", "REALIZED_G_L_ON_CURRENCY_BASE", "REALIZED_G_L_ON_INVESTMENT_BASE", "REALIZED_G_L_BASE", "REALIZED_G_L_LOCAL", "TRANSACTION_YIELD", "FUNCTIONAL_CCY_CD", "LOCAL_TO_FUNC_RATE", "LOCAL_TO_CAD_RATE", "LOCAL_TO_USD_RATE", "LOCAL_TO_HKD_RATE", "TRANSACTION_AMOUNT", "OID_AMORT_CCY_BASE", "OID_AMORT_CCY_LOCAL", "IMPAMT_CCY_BASE", "IMPAMT_CCY_LOCAL", "INCOME_GROSS_AMOUNT_CCY_BASE", "INCOME_GROSS_AMOUNT_CCY_LOCAL", "LIABILITY_PORTF_CODE", "BASE_CCY_CD", "PAYMENT_PURPOSE", "PURPOSE", "COUNTRY", "COUNTRY_NM", "GROUPCODE", "BANK_CODE", "BANK_ACCOUNT_CODE", "SCD_SECURITY_ID", "TRAN_HUB_ID", "SECURITY_NK", "UNDERLIER_SEC_KEY", "SCD_SECURITY_TYPE", "UNDERLIER_SRC_SECURITY_ID", "SRC_SECURITY_ID", "FX_SWAP_TICKET_NUMBER", "SUB_BROKER", "SUB_BROKER_DES", "IPO", "LONG_NOTE_3", "LONG_NOTE_4", "LONG_NOTE_5", "TRADER_DESK", "SETTLE_DAYS", "TRANSASOFDATE", "HAIRCUT", "TRADING_COMMENT", "TRANSACTION_PURPOSE", "ORIGINAL_SYSTEM_TRAN_NUMBER", "INTEREST_DATE", "REGION", "VALUATION_CYCLE", "POST_TIME", "BACKPOST_MONTH", "TAX_LOT_IX", "LOT_SOURCE_TRANSACTION_ID", "BUS_TRANS_NO", "LOT_ID", "ASIA_ASSET_CLASS_CODE_IN", "ASIA_ASSET_CLASS_CODE_VI", "ASIA_ASSET_CLASS_DESC_IN", "ASIA_ASSET_CLASS_DESC_VI", "GROUP_STRUCTURE_RELATION", "BALANCE_BOOK_VALUE_CCY_LOCAL", "BALANCE_BOOK_VALUE_CCY_BASE", "INT_APR_CCY_LOCAL", "INT_APR_CCY_BASE", "ECL_LOSS_CCY_LOCAL", "ECL_LOSS_CCY_BASE", "CECL_LOSS_CCY_LOCAL", "CECL_LOSS_CCY_BASE", "IMPAIRMENT_CCY_LOCAL", "IMPAIRMENT_CCY_BASE", "REA_AOCI_BV_CCY_LOCAL", "REA_AOCI_BV_CCY_BASE", "DEFERRED_PL_CCY_LOCAL", "DEFERRED_PL_CCY_BASE", "P_OR_L_BOOK_CCY_LOCAL", "P_OR_L_BOOK_CCY_BASE", "COST_VALUE_CCY_LOCAL", "COST_VALUE_CCY_BASE", "OID_INT_APPR_CCY_LOCAL", "OID_INT_APPR_CCY_BASE", "REAL_INT_APPR_CCY_BASE", "REAL_INT_APPR_CCY_LOCAL", "CON_CL_ALLOW_CCY_BASE", "CON_CL_ALLOW_CCY_LOCAL", "CHANGE_AOCI_BV_CCY_BASE", "CHANGE_AOCI_BV_CCY_LOCAL", "CHANGE_AOCI_NONBV_CCY_BASE", "CHANGE_AOCI_NONBV_CCY_LOCAL", "LOT_NOMINAL", "UNPAID_AMOUNT_CCY_LOCAL", "PAYMENT_AMOUNT_CCY_BASE", "NOMINAL_OUTGOING_AMOUNT", "NOMINAL_INCOMING_AMOUNT", "NET_AMOUNT_LOCAL", "TRADER_LOGIN", "BLOOMBERG_TIMESTAMP", "AOCI_HEDGE_FINDUR_ID", "TR_FREECOMMENT", "TRANS_STATUS_ACTUAL", "TOTAL_CASH_PROCEEDS", "INTEREST_TRADE_LOCAL", "UNITS_QUANTITY", "SRC", "UPDATED_TS", "REFERENCE_SECURITY_ID", "MASTER_TICKET_NUMBER", "ORIGINAL_SYSTEM", "originating_system_no", "dgl_inception_trans_no", "changed_date", "ALT_INV_TRANS_TYPE", "NOMINAL_TO_MATCH", "POS_TRANS_LINK", "TXN_LONG_SHORT_INDICATOR", "SCD_COUPON_RATE", "YIELD_FOR_MATH_ADJ", "WASH_SALE_TRANSACTION_ID", "BLOOMBERG_TRANSACTION_IDENTIFIER", "WASH_SALE_PARENT_LOT_ID", "P_OR_L_BOOK_SEC_BASE_CCY", "P_OR_L_BOOK_CCY_BASE_CCY", "WASH_SALE_PROCESS_ID", "MANULIFE_LOCAL_PRICE", "REAL_AMORTISATION_BASE_CCY", "REAL_AMORTISATION_LOCAL_CCY", "UNREAL_OID_ACCRETION_BASE_CCY", "UNREAL_OID_ACCRETION_LOCAL_CCY", "BOOKED_CURRENT_VALUE_LOCAL_CCY", "BOOKED_CURRENT_VALUE_BASE_CCY", "AMORTISED_COST_CCY_CORR_BASE_CCY", "AMORTISED_COST_CCY_RESULT_BASE_CCY", "AMORTISED_COST_SEC_BASE_CCY", "AMORTISED_COST_LOCAL_CCY", "REAL_OID_AMORTISATION_BASE_CCY", "REAL_OID_AMORTISATION_LOCAL_CCY", "BUCKET", "SRC_CREATED_TS", "SRC_UPDATED_TS", "FX_JOIN_KEY", "Settle_status_PBI", "REALISED_IMPAIRMENT_LOCAL_CCY", "REALISED_IMPAIRMENT_SEC_BASE_CCY", "REALISED_IMPAIRMENT_CCY_BASE_CCY", "ORIGINAL_POST_DT", "IFRS9PURPOSE", "long_note_2", "long_note_1", "long_note_6", "long_note_7", "long_note_8", "short_note_1", "short_note_2", "short_note_3", "short_note_4", "short_note_5", "short_note_6", "short_note_7", "short_note_8", "custodian_name", "user_change_id", "user_change_name", "processing_group_nm"}),
				    #"Load data from specific date"= Table.SelectRows(#"Removed Other Columns",each [TRANSASOFDATE] >= pCutOffDate),
				    #"Renamed Columns" = Table.RenameColumns(#"Load data from specific date",{{"TRANSACTION_NO", "Transaction No"}, {"LEG", "Leg"}, {"REVERSAL", "Reversal"}, {"TRANS_STATUS", "Trans Status"}, {"PORTFOLIO_CD", "Portfolio Code"}, {"POST_DT", "Post Date"}, {"PORTFOLIO_CODE_NM", "Portfolio Code & Name"}, {"ACCOUNTING_UNIT_CODE_NAME", "Accounting Unit Code & Name"}, {"COMPANY_CODE_NAME", "Company Code & Name"}, {"TRANS_CATEGORY", "Trans Category"}, {"BUS_TRANS_SUBCATEGORY", "Bus Trans Subcategory"}, {"TRANS_TYPE", "Trans Type"}, {"FRAMEWORK_CD", "Framework Code"}, {"GL_CLASS", "GL Class"}, {"ELEMENTARY_TRANS_CODE", "Elementary Trans Code "}, {"PERIOD_CLOSE_DT", "Period Close Date"}, {"POSTING_LAG", "Posting Lag"}, {"TRADE_DT", "Trade Date"}, {"SETTLE_DT", "Settle Date"}, {"ACTUAL_SETTLE_DATE", "Actual Settle Date"}, {"FINAL_REPORTING_DATE", "Final Reporting Date"}, {"PAYMENT_DATE", "Payment Date"}, {"AS_OF_PERIOD", "As Of Period"}, {"PORTFOLIO_NK", "Portfolio NK"}, {"BLOOMBERG_NO", "Bloomberg No"}, {"MASTER_TICKET", "Master Ticket"}, {"ORDER_NO", "Order No"}, {"SOURCE_ID", "Source ID"}, {"MATCH_SRC_TRANSACTION_ID", "Match Src Transaction ID"}, {"USER_NM", "User Name"}, {"SETTLE_CCY_CD", "Settle Ccy Code"}, {"SETTLE_CURRENCY", "Settle Currency"}, {"LOCAL_CCY_CD", "Local"}, {"LOCAL_CURRENCY", "Local Currency"}, {"UNDERLIER_MATURITY_DATE", "Underlier Maturity Date"}, {"UNDERLIER_NEXT_COUPON_DATE", "Underlier Next Coupon Date"}, {"UNDERLIER_COUPON", "Underlier Coupon"}, {"SETTLE_EXCHANGE_RATE", "Settle Exchange Rate"}, {"LOCAL_EXCHANGE_RATE", "Local Exchange Rate"}, {"SIGN", "Sign"}, {"UNITS", "Units"}, {"POOL_FACTOR", "Pool Factor"}, {"ORIGINAL_FACE", "Original Face"}, {"CONTRACTS", "Contracts"}, {"CURRENT_FACE", "Current Face"}, {"NOMINAL_BASIS", "Nominal Basis"}, {"BROKER_CD", "Broker Code"}, {"BROKER_NM", "Broker Name"}, {"COUNTERPARTY_CODE", "Counterparty Code"}, {"COUNTERPARTY_NAME", "Counterparty Name"}, {"CMMT", "Cmmt"}, {"CLASS_CD", "ClassCode"}, {"BUS_TRANS_CODE", "Bus Trans Code"}, {"MATERIALITY", "Materiality"}, {"BASE_AMT", "Amount - Base"}, {"SETTLE_AMT", "Settle Amount (D)"}, {"BASE_PRINCIPAL", "Principal - Base"}, {"SETTLE_PRINCIPAL", "Settle Principal"}, {"BASE_INTEREST", "Interest - Base"}, {"SETTLE_INTEREST", "Settle Interest"}, {"BASE_MATURITY_AMOUNT", "Maturity Amount - Base"}, {"SETTLE_MATURITY_AMOUNT", "Settle Maturity Amount"}, {"CURRENT_VALUE_CCY_LOCAL", "Current Value - Local"}, {"TRANS_PRICE_LOCAL", "Trans Price Local"}, {"BASE_PRICE", "Price - Base"}, {"PRICE_LOCAL", "Price - Local (D)"}, {"SETTLE_PRICE", "Settle Price"}, {"ORIGINAL_COST_BASE", "Original Cost - Base"}, {"ORIGINAL_COST_LOCAL", "Original Cost - Local"}, {"AMORTIZED_COST_BASE", "Amortized Cost - Base"}, {"AMORTIZED_COST_LOCAL", "Sec Amortization Cost Local"}, {"REALIZED_G_L_ON_CURRENCY_BASE", "Realized Gain/Loss CCY - Base"}, {"REALIZED_G_L_ON_INVESTMENT_BASE", "Realized Gain/Loss Sec - Base"}, {"REALIZED_G_L_BASE", "Realized Gain/Loss - Base"}, {"REALIZED_G_L_LOCAL", "Realized Gain/Loss - Local"}, {"TRANSACTION_YIELD", "Transaction Yield"}, {"FUNCTIONAL_CCY_CD", "Functional Ccy Code"}, {"LOCAL_TO_FUNC_RATE", "Local To FUNC Rate"}, {"LOCAL_TO_CAD_RATE", "Local To CAD Rate"}, {"LOCAL_TO_USD_RATE", "Local To USD Rate"}, {"LOCAL_TO_HKD_RATE", "Local To HKD Rate"}, {"TRANSACTION_AMOUNT", "Transaction Amount"}, {"OID_AMORT_CCY_BASE", "OID Amortization/Accretion - Base"}, {"OID_AMORT_CCY_LOCAL", "OID Amortization/Accretion - Local"}, {"IMPAMT_CCY_BASE", "Imp Amount - Base"}, {"IMPAMT_CCY_LOCAL", "Imp Amount - Local"}, {"INCOME_GROSS_AMOUNT_CCY_BASE", "Income Gross Amount - Base"}, {"INCOME_GROSS_AMOUNT_CCY_LOCAL", "Income Gross Amount - Local"}, {"LIABILITY_PORTF_CODE", "Liability Portf Code"}, {"BASE_CCY_CD", "Base"}, {"PAYMENT_PURPOSE", "Payment Purpose"}, {"PURPOSE", "Purpose"}, {"COUNTRY", "Country"}, {"COUNTRY_NM", "Country Name"}, {"GROUPCODE", "Groupcode"}, {"BANK_CODE", "Bank Code"}, {"BANK_ACCOUNT_CODE", "Bank Account Code"}, {"SCD_SECURITY_ID", "SCD Security ID"}, {"TRAN_HUB_ID", "Tran Hub ID"}, {"SECURITY_NK", "Security NK"}, {"UNDERLIER_SEC_KEY", "Underlier Sec Key"}, {"SCD_SECURITY_TYPE", "SCD Security Type"}, {"UNDERLIER_SRC_SECURITY_ID", "Underlier Src Security ID"}, {"SRC_SECURITY_ID", "Src Security ID"}, {"FX_SWAP_TICKET_NUMBER", "Fx Swap Ticket Number"}, {"SUB_BROKER", "Sub Broker"}, {"SUB_BROKER_DES", "Sub Broker Des"}, {"IPO", "Ipo"}, {"LONG_NOTE_3", "Long Note 3"}, {"LONG_NOTE_4", "Long Note 4"}, {"LONG_NOTE_5", "Long Note 5"}, {"TRADER_DESK", "Trader Desk"}, {"SETTLE_DAYS", "Settle Days"}, {"TRANSASOFDATE", "Transasofdate"}, {"HAIRCUT", "Haircut"}, {"TRADING_COMMENT", "Trading Comment"}, {"TRANSACTION_PURPOSE", "Transaction Purpose"}, {"ORIGINAL_SYSTEM_TRAN_NUMBER", "Original System Tran Number"}, {"INTEREST_DATE", "Interest Date"}, {"REGION", "Region"}, {"VALUATION_CYCLE", "Valuation Cycle"}, {"POST_TIME", "Post Time"}, {"BACKPOST_MONTH", "Backpost Month"}, {"TAX_LOT_IX", "Tax Lot Ix"}, {"LOT_SOURCE_TRANSACTION_ID", "Lot Source Transaction ID"}, {"BUS_TRANS_NO", "Bus Trans Number"}, {"LOT_ID", "Lot ID"}, {"ASIA_ASSET_CLASS_CODE_IN", "Asia Asset Class Code Indonesia"}, {"ASIA_ASSET_CLASS_CODE_VI", "Asia Asset Class Code Vietnam"}, {"ASIA_ASSET_CLASS_DESC_IN", "Asia Asset Class Desc Indonesia"}, {"ASIA_ASSET_CLASS_DESC_VI", "Asia Asset Class Desc Vietnam"}, {"GROUP_STRUCTURE_RELATION", "Group Structure Relation"}, {"BALANCE_BOOK_VALUE_CCY_LOCAL", "Book Value - Local unsigned"}, {"BALANCE_BOOK_VALUE_CCY_BASE", "Book Value - Base unsigned"}, {"INT_APR_CCY_LOCAL", "Int Apr - Local"}, {"INT_APR_CCY_BASE", "Int Apr - Base"}, {"ECL_LOSS_CCY_LOCAL", "ECL Loss - Local"}, {"ECL_LOSS_CCY_BASE", "ECL Loss - Base"}, {"CECL_LOSS_CCY_LOCAL", "CECL Loss - Local"}, {"CECL_LOSS_CCY_BASE", "CECL Loss - Base"}, {"IMPAIRMENT_CCY_LOCAL", "Impairment - Local"}, {"IMPAIRMENT_CCY_BASE", "Impairment - Base"}, {"REA_AOCI_BV_CCY_LOCAL", "REA AOCI BV - Local"}, {"REA_AOCI_BV_CCY_BASE", "REA AOCI BV - Base"}, {"DEFERRED_PL_CCY_LOCAL", "Deferred PL - Local"}, {"DEFERRED_PL_CCY_BASE", "Deferred PL - Base"}, {"P_OR_L_BOOK_CCY_LOCAL", "Realized Gain/Loss Book - Local"}, {"P_OR_L_BOOK_CCY_BASE", "Realized Gain/Loss Book - Base"}, {"COST_VALUE_CCY_LOCAL", "Cost Value - Local unsigned"}, {"COST_VALUE_CCY_BASE", "Cost Value - Base unsigned"}, {"OID_INT_APPR_CCY_LOCAL", "OID Int Appr - Local"}, {"OID_INT_APPR_CCY_BASE", "OID Int Appr - Base"}, {"REAL_INT_APPR_CCY_BASE", "Real Int Appr - Base"}, {"REAL_INT_APPR_CCY_LOCAL", "Real Int Appr - Local"}, {"CON_CL_ALLOW_CCY_BASE", "Con CL Allow - Base"}, {"CON_CL_ALLOW_CCY_LOCAL", "Con CL Allow - Local"}, {"CHANGE_AOCI_BV_CCY_BASE", "Change AOCI BV - Base"}, {"CHANGE_AOCI_BV_CCY_LOCAL", "Change AOCI BV - Local"}, {"CHANGE_AOCI_NONBV_CCY_BASE", "Change AOCI NONBV - Base"}, {"CHANGE_AOCI_NONBV_CCY_LOCAL", "Change AOCI NONBV - Local"}, {"LOT_NOMINAL", "Lot Nominal"}, {"UNPAID_AMOUNT_CCY_LOCAL", "Unpaid Amount - Local (D)"}, {"PAYMENT_AMOUNT_CCY_BASE", "Payment Amount - Base"}, {"NOMINAL_OUTGOING_AMOUNT", "Nominal Outgoing Amount"}, {"NOMINAL_INCOMING_AMOUNT", "Nominal Incoming Amount"}, {"NET_AMOUNT_LOCAL", "Net Amount - Local"}, {"TRADER_LOGIN", "Trader Login"}, {"BLOOMBERG_TIMESTAMP", "Bloomberg Timestamp"}, {"AOCI_HEDGE_FINDUR_ID", "AOCI Hedge Findur ID"}, {"SRC", "Source"}, {"UPDATED_TS", "Updated Ts"}, {"ALT_INV_TRANS_TYPE", "ALT INV TRANS TYPE"}, {"WASH_SALE_PROCESS_ID", "Wash Sale Process ID"}, {"long_note_1", "Long Note 1"}, {"long_note_2", "Long Note 2"}, {"long_note_6", "Long Note 6"}, {"long_note_7", "Long Note 7"}, {"long_note_8", "Long Note 8"}, {"short_note_1", "Short Note 1"}, {"short_note_2", "Short Note 2"}, {"short_note_3", "Short Note 3"}, {"short_note_4", "Short Note 4"}, {"short_note_5", "Short Note 5"}, {"short_note_6", "Short Note 6"}, {"short_note_7", "Short Note 7"}, {"short_note_8", "Short Note 8"}, {"custodian_name", "Custodian Name"}, {"TR_FREECOMMENT", "Tr Freecomment"}, {"TRANS_STATUS_ACTUAL", "Trans Status Actual"}, {"TOTAL_CASH_PROCEEDS", "Total Cash Proceeds"}, {"INTEREST_TRADE_LOCAL", "Interest Trade Local"}, {"UNITS_QUANTITY", "Units/Quantity"}, {"AMORTISED_COST_LOCAL_CCY", "Amortized Cost Local"}, {"user_change_id", "User Change ID"}, {"user_change_name", "User Change Name"}, {"POS_TRANS_LINK", "POS Trans Link"}, {"BLOOMBERG_TRANSACTION_IDENTIFIER", "Bloomberg Tansaction Identifier"}, {"WASH_SALE_PARENT_LOT_ID", "Wash Sale Parent Lot Id"}, {"WASH_SALE_TRANSACTION_ID", "Wash Sale Transaction Id"}, {"P_OR_L_BOOK_CCY_BASE_CCY", "P Or L Book CCY Local"}, {"P_OR_L_BOOK_SEC_BASE_CCY", "P Or L Book Sec Base CCY"}, {"BOOKED_CURRENT_VALUE_LOCAL_CCY", "Booked Current Value Local"}, {"BOOKED_CURRENT_VALUE_BASE_CCY", "Booked Current Value Base"}, {"UNREAL_OID_ACCRETION_BASE_CCY", "Unreal OID Accretion - Base"}, {"UNREAL_OID_ACCRETION_LOCAL_CCY", "Unreal OID Accretion -  Local"}, {"REAL_OID_AMORTISATION_BASE_CCY", "Real OID Amortisation - Base"}, {"REAL_OID_AMORTISATION_LOCAL_CCY", "Real OID Amortisation - Local"}, {"ORIGINAL_SYSTEM", "Original System"}, {"REFERENCE_SECURITY_ID", "Reference Security ID"}, {"MASTER_TICKET_NUMBER", "Master Ticket Number"}, {"NOMINAL_TO_MATCH", "Nominal To Match"}, {"TXN_LONG_SHORT_INDICATOR", "Long Short Ind"}, {"SCD_COUPON_RATE", "SCD Coupon Rate"}, {"MANULIFE_LOCAL_PRICE", "Manulife Local Price"}, {"originating_system_no", "Originating System No"}, {"YIELD_FOR_MATH_ADJ", "Yield For Math Adj"}, {"REAL_AMORTISATION_BASE_CCY", "Real Amortisation Base"}, {"REAL_AMORTISATION_LOCAL_CCY", "Real Amortisation Local"}, {"AMORTISED_COST_SEC_BASE_CCY", "Amortized Cost Sec Base"}, {"AMORTISED_COST_CCY_CORR_BASE_CCY", "Amortized Cost Ccy Corr Base"}, {"AMORTISED_COST_CCY_RESULT_BASE_CCY", "Amortized Cost Ccy Result Base"}, {"SRC_CREATED_TS", "Src Created Ts"}, {"SRC_UPDATED_TS", "Src Updated Ts"}, {"BUCKET", "Bucket"}, {"ORIGINAL_POST_DT", "Original Post Date"}, {"Settle_status_PBI", "Settled Status"}, {"FX_JOIN_KEY", "FX Join Key"}, {"REALISED_IMPAIRMENT_LOCAL_CCY", "Realised Impairment Local"}, {"REALISED_IMPAIRMENT_SEC_BASE_CCY", "Realised Impairment Sec Base"}, {"REALISED_IMPAIRMENT_CCY_BASE_CCY", "Realised Impairment Ccy Base"}, {"dgl_inception_trans_no", "Dgl Inception Trans No"}, {"IFRS9PURPOSE", "IFRS9 Purpose"}, {"processing_group_nm", "Processing Group Name"}, {"changed_date", "Changed Date"}}),
				    #"Filtered Rows - Incremental Refresh" = Table.SelectRows(#"Renamed Columns", each [Transasofdate] >= Date.From(RangeStart) and [Transasofdate] < Date.From(RangeEnd))
				in
				    #"Filtered Rows - Incremental Refresh"

	annotation PBI_ResultType = Table

	annotation PBI_IsMQueryFoldable = True

	annotation PBI_NavigationStepName = Navigation

