table 'Securities Lots Fact'
	lineageTag: 2e3a56f1-5beb-4926-aca4-885e65837652

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: month
		rollingWindowPeriods: 16
		incrementalGranularity: month
		incrementalPeriods: 16
		pollingExpression = Securities_Lots_Fact_PBI_Config
		sourceExpression =
			let
			    Source = Databricks.Catalogs(HostName, HTTPPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null,CommandTimeout= #duration(0,5,0,0), EnableQueryResultDownload="0"]),
			    hive_metastore_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
			    inv_semantic_ga_Schema = hive_metastore_Database{[Name="inv_semantic_ga",Kind="Schema"]}[Data],
			    EDL_securities_lots_fact_dq = inv_semantic_ga_Schema{[Name="securities_lots_fact_dq",Kind="Table"]}[Data],
			    #"Removed Other Columns" = Table.SelectColumns(EDL_securities_lots_fact_dq,{"FRAMEWORK_CD", "SECURITY_NK", "PORTFOLIO_NK", "EFFECTIVE_DATE", "REGION", "AS_OF_PERIOD", "MATURITY_DATE", "PENPAR_TRADE_DATE", "LOT_TRADE_DATE", "SEC_MATURITY_DATE", "ACCOUNTING_UNIT_CODE_NAME", "COMPANY_CODE_NAME", "PORTFOLIO_CODE_NM", "GL_CLASS", "LOCAL_CURRENCY_CODE", "LOT_ID", "TRANSACTION_NO", "EXT_TAX_LOT_NO_IK", "SRC_SECURITY_ID", "SCD_SECURITY_ID", "SRC_POSITIONS_ID", "SRC", "SRC_MARKET_ID", "MONTH_END_STATUS", "INT_TRANS_NUMBER_ORIG_TRANS", "BASE_CURRENCY_CODE", "CALCULATION_DATE_FULL", "PORTFOLIO_GROUP_OBJECTIVE", "ASSET_PORTFOLIO_CODE", "POOL_FACTOR", "CREDIT_IMPAIRMENT_STAGE", "LONG_SHORT_INDICATOR", "ISSUER_NAME", "POSITION_LONG_SHORT_INDICATOR", "MATCH_INDEX", "SECURITY_INTERNAL_RATING", "ORIG_ML_RATING", "PRVT_PLACE", "COUPON", "EFFECTIVE_MATCHING_DATE", "IMPAIRED_BEFORE", "FIRST_LOST_DATE", "IMPAIRED_BEFORE_DATE", "NUM_OF_DAYS_IMPAIR", "NUM_OF_DAYS_IN_LOST_POSITION", "FUNCTIONAL_CCY_CD", "LOCAL_EXCHANGE_RATE", "LOCAL_TO_FUNC_RATE", "LOCAL_TO_CAD_RATE", "LOCAL_TO_USD_RATE", "LOCAL_TO_HKD_RATE", "ORIGINAL_COST_BASE", "ORIGINAL_COST_LOCAL", "BAL_INTEREST_APPRECIATION_CCY_BASE", "BAL_INTEREST_APPRECIATION_CCY_LOCAL", "BALANCE_OID_APPR_CCY_BASE", "BALANCE_OID_APPR_CCY_LOCAL", "BALANCE_CL_ALLOWANCE_CCY_BASE", "BALANCE_CL_ALLOWANCE_CCY_LOCAL", "BALANCE_RECOG_CL_ALLOWANCE_CCY_BASE", "BALANCE_RECOG_CL_ALLOWANCE_CCY_LOCAL", "BALANCE_IMPAIRMENT_CCY_BASE", "BALANCE_IMPAIRMENT_CCY_LOCAL", "BALANCE_CCY_IMPAIRMENT_CCY_BASE", "AOCI_REMAIN_BALANCE_BV_CCY_BASE", "AOCI_REMAIN_BALANCE_BV_CCY_LOCAL", "BALANCE_DEFERRED_PL_CCY_BASE", "BALANCE_DEFERRED_PL_CCY_LOCAL", "CARRYING_VALUE_CCY_BASE", "CARRYING_VALUE_CCY_LOCAL", "AOCI_HEDGE_PAR", "AOCI_REMAIN_BALANCE_NON_BV_CCY_BASE", "AOCI_REMAIN_BALANCE_NON_BV_CCY_LOCAL", "AOCI_REMAIN_BALANCE_REP_CCY_BASE", "AOCI_REMAIN_BALANCE_REP_CCY_LOCAL", "BOOK_YIELD", "CURRENT_YIELD", "MODIFIED_DURATION", "NOMINAL", "BV_PER_UNIT_BASE", "BV_PER_UNIT_LOCAL", "COST_PER_UNIT_BASE", "COST_PER_UNIT_LOCAL", "PAR_AMT", "MARKET_VALUE_LOCAL", "MARKET_VALUE_BASE", "BALANCE_BOOK_VALUE_CCY_BASE", "BALANCE_BOOK_VALUE_CCY_LOCAL", "UNREAL_PL_BOOK_SEC_CCY_BASE", "UNREAL_CCY_PL_BOOK_CCY_BASE", "UNREALIZED_GAIN_LOSS_BASE", "UNREAL_PL_BOOK_SEC_CCY_LOCAL", "UNREAL_CCY_PL_BOOK_CCY_LOCAL", "UNREALIZED_GAIN_LOSS_LOCAL", "BALANCE_WRITE_OFF_LOCAL_CCY", "BALANCE_WRITE_OFF_BASE_CCY", "CREATED_TS", "UPDATED_TS", "component_no", "portfolio_calculation_ik", "originating_system_no", "ADJUSTED_BOOK_VALUE_LOCAL", "ADJUSTED_BOOK_VALUE_BASE", "GL_BUCKET", "SCD_DEFAULT_DATE", "SCD_DEFAULT_DATE_FC", "UNITS", "PURPOSE", "UNREAL_REAL_INT_APPR_DISC_LOCAL_CCY", "UNREAL_REAL_INT_APPR_PREM_LOCAL_CCY", "BAL_INTEREST_APPRECIATION_LOCAL_CCY", "UNREAL_OID_ACCRETION_LOCAL_CCY", "INITIAL_SVO_RATING", "BALANCE_AMORTISED_COST_CCY_BASE_CCY", "BALANCE_AMORTISED_COST_SEC_BASE_CCY", "BALANCE_AMORTISED_COST_LOCAL_CCY", "DE_MINIMIS_RULE_IK", "OID_DE_MINIMIS_RULE_IK", "IFRS9PURPOSE", "BALANCE_BOOK_VALUE_LOCAL_CCY_NATIVE", "BALANCE_BOOK_VALUE_BASE_CCY_NATIVE", "MARKET_PER_UNIT_LOCAL", "MARKET_PER_UNIT_BASE", "YIELD_FOR_MATH_ADJ", "MARKET_PRICE_LOCAL", "INITIAL_TRANS_TYPE", "UNIQUE_SUBLOT_ID", "FX_JOIN_KEY", "BALANCE_NAIC_CARRYING_VALUE_LOCAL_CCY", "BALANCE_NAIC_CARRYING_VALUE_BASE_CCY", "BALANCE_NAIC_SEC_ADJ_LOCAL_CCY", "BALANCE_NAIC_SEC_ADJ_BASE_CCY", "average_cost_yield"}),
			    #"Load data from specific date"= Table.SelectRows(#"Removed Other Columns",each [EFFECTIVE_DATE] >= pCutOffDate),
			    #"Renamed Columns" = Table.RenameColumns(#"Load data from specific date",{{"FRAMEWORK_CD", "Framework Code"}, {"SECURITY_NK", "Security NK"}, {"PORTFOLIO_NK", "Portfolio NK"}, {"EFFECTIVE_DATE", "As Of Date"}, {"REGION", "Region"}, {"AS_OF_PERIOD", "As Of Period"}, {"MATURITY_DATE", "Maturity Date"}, {"PENPAR_TRADE_DATE", "PenPar Trade Date"}, {"LOT_TRADE_DATE", "Lot Trade Date"}, {"SEC_MATURITY_DATE", "Sec Maturity Date"}, {"ACCOUNTING_UNIT_CODE_NAME", "Accounting Unit Code & Name"}, {"COMPANY_CODE_NAME", "Company Code & Name"}, {"PORTFOLIO_CODE_NM", "Portfolio Code & Name"}, {"GL_CLASS", "GL Class"}, {"LOCAL_CURRENCY_CODE", "Local"}, {"LOT_ID", "Lot ID"}, {"TRANSACTION_NO", "Transaction No"}, {"EXT_TAX_LOT_NO_IK", "Ext Tax Lot No IK"}, {"SRC_SECURITY_ID", "Src Security ID"}, {"SRC_POSITIONS_ID", "Src Positions ID"}, {"SRC", "Src"}, {"SRC_MARKET_ID", "Src Market ID"}, {"MONTH_END_STATUS", "Month End Status"}, {"INT_TRANS_NUMBER_ORIG_TRANS", "Int Trans Number Orig Trans"}, {"BASE_CURRENCY_CODE", "Base Currency Code"}, {"CALCULATION_DATE_FULL", "Calculation Date Full"}, {"PORTFOLIO_GROUP_OBJECTIVE", "Portfolio Group Objective"}, {"ASSET_PORTFOLIO_CODE", "Asset Portfolio Code"}, {"POOL_FACTOR", "Pool Factor"}, {"CREDIT_IMPAIRMENT_STAGE", "Credit Impairment Stage"}, {"LONG_SHORT_INDICATOR", "Long Short Indicator"}, {"ISSUER_NAME", "Issuer Name"}, {"POSITION_LONG_SHORT_INDICATOR", "Position Long Short Indicator"}, {"MATCH_INDEX", "Match Index"}, {"SECURITY_INTERNAL_RATING", "Security Internal Rating"}, {"ORIG_ML_RATING", "Original ML Rating"}, {"PRVT_PLACE", "Private Place"}, {"COUPON", "Coupon"}, {"EFFECTIVE_MATCHING_DATE", "Effective Matching Date"}, {"IMPAIRED_BEFORE", "Impaired Before"}, {"FIRST_LOST_DATE", "First Loss Date"}, {"IMPAIRED_BEFORE_DATE", "Impaired Before Date"}, {"NUM_OF_DAYS_IMPAIR", "Num of Days Impair"}, {"NUM_OF_DAYS_IN_LOST_POSITION", "Num of Days in Lost Position"}, {"FUNCTIONAL_CCY_CD", "Functional Ccy Code"}, {"LOCAL_EXCHANGE_RATE", "Local Exchange Rate"}, {"LOCAL_TO_FUNC_RATE", "Local To FUNC Rate"}, {"LOCAL_TO_CAD_RATE", "Local To CAD Rate"}, {"LOCAL_TO_USD_RATE", "Local To USD Rate"}, {"LOCAL_TO_HKD_RATE", "Local To HKD Rate"}, {"ORIGINAL_COST_BASE", "Original Cost - Base"}, {"ORIGINAL_COST_LOCAL", "Original Cost - Local"}, {"BAL_INTEREST_APPRECIATION_CCY_BASE", "Balance Int Appr - Base"}, {"BAL_INTEREST_APPRECIATION_CCY_LOCAL", "Balance Int Appr - Local"}, {"BALANCE_OID_APPR_CCY_BASE", "Balance OID Appr - Base"}, {"BALANCE_OID_APPR_CCY_LOCAL", "Balance OID Appr - Local"}, {"BALANCE_CL_ALLOWANCE_CCY_BASE", "Balance CL Allowance - Base"}, {"BALANCE_CL_ALLOWANCE_CCY_LOCAL", "Balance CL Allowance - Local"}, {"BALANCE_RECOG_CL_ALLOWANCE_CCY_BASE", "Balance Recog CL Allowance - Base"}, {"BALANCE_RECOG_CL_ALLOWANCE_CCY_LOCAL", "Balance Recog CL Allowance - Local"}, {"BALANCE_IMPAIRMENT_CCY_BASE", "Balance Impairment - Base"}, {"BALANCE_IMPAIRMENT_CCY_LOCAL", "Balance Impairment - Local"}, {"BALANCE_CCY_IMPAIRMENT_CCY_BASE", "Balance CCY Impairment - Base"}, {"BALANCE_DEFERRED_PL_CCY_BASE", "Balance Deferred PL - Base"}, {"BALANCE_DEFERRED_PL_CCY_LOCAL", "Balance Deferred PL - Local"}, {"CARRYING_VALUE_CCY_BASE", "Carrying Value - Base"}, {"CARRYING_VALUE_CCY_LOCAL", "Carrying Value - Local"}, {"AOCI_HEDGE_PAR", "AOCI Hedge Par"}, {"BOOK_YIELD", "Book Yield"}, {"CURRENT_YIELD", "Current Yield"}, {"MODIFIED_DURATION", "Modified Duration"}, {"NOMINAL", "Nominal"}, {"BV_PER_UNIT_BASE", "BV / Unit - Base"}, {"BV_PER_UNIT_LOCAL", "BV / Unit - Local"}, {"COST_PER_UNIT_BASE", "Cost / Unit - Base"}, {"COST_PER_UNIT_LOCAL", "Cost / Unit - Local"}, {"PAR_AMT", "Par Amount"}, {"MARKET_VALUE_LOCAL", "Fair Value Unaccrued - Local"}, {"MARKET_VALUE_BASE", "Fair Value Unaccrued - Base"}, {"BALANCE_BOOK_VALUE_CCY_LOCAL", "Book Value - Local"}, {"BALANCE_BOOK_VALUE_CCY_BASE", "Book Value - Base"}, {"UNREAL_PL_BOOK_SEC_CCY_BASE", "Unrealized Gain/Loss Sec - Base"}, {"UNREAL_CCY_PL_BOOK_CCY_BASE", "Unrealized Gain/Loss CCY - Base"}, {"UNREALIZED_GAIN_LOSS_BASE", "Unrealized Gain/Loss - Base"}, {"UNREAL_PL_BOOK_SEC_CCY_LOCAL", "Unrealized Gain/Loss Sec - Local"}, {"UNREAL_CCY_PL_BOOK_CCY_LOCAL", "Unrealized Gain/Loss CCY - Local"}, {"UNREALIZED_GAIN_LOSS_LOCAL", "Unrealized Gain/Loss - Local"}, {"CREATED_TS", "Created Ts"}, {"UPDATED_TS", "Updated Ts"}, {"BALANCE_AMORTISED_COST_SEC_BASE_CCY", "Balance Amortised Cost Sec Base CCY"}, {"BALANCE_AMORTISED_COST_LOCAL_CCY", "Balance Amortised Cost Local CCY"}, {"BALANCE_AMORTISED_COST_CCY_BASE_CCY", "Balance Amortised Cost CCY Base CCY"},{"DE_MINIMIS_RULE_IK","De Minimis Rule Id"},{"OID_DE_MINIMIS_RULE_IK","Oid De Minimis Rule Id"},{"MARKET_PER_UNIT_LOCAL","FV / Unit - Local"},{"MARKET_PER_UNIT_BASE","FV / Unit - Base"},{"MARKET_PRICE_LOCAL","Price - Local (D)"},{"FX_JOIN_KEY","FX Join Key"},{"UNIQUE_SUBLOT_ID","Unique Lot ID"},{"SCD_SECURITY_ID", "SCD Security ID"},{"ADJUSTED_BOOK_VALUE_BASE", "Adjusted Book Value Base"}, {"ADJUSTED_BOOK_VALUE_LOCAL", "Adjusted Book Value Local"},{"SCD_DEFAULT_DATE", "SCD Default Date"}, {"SCD_DEFAULT_DATE_FC", "Accrue In Default"}, {"UNITS", "Units"}, {"UNREAL_REAL_INT_APPR_DISC_LOCAL_CCY", "Unreal Real Int Appr Disc Local CCY"}, {"UNREAL_REAL_INT_APPR_PREM_LOCAL_CCY", "Unreal Real Int Appr Prem Local CCY"}, {"UNREAL_OID_ACCRETION_LOCAL_CCY", "Unreal Oid Accretion Local CCY"}, {"BAL_INTEREST_APPRECIATION_LOCAL_CCY", "Bal Interest Appreciation Local CCY"},{"INITIAL_SVO_RATING", "Initial SVO Rating"}, {"IFRS9PURPOSE", "IFRS9 Purpose"}, {"PURPOSE", "Purpose"}, {"BALANCE_BOOK_VALUE_LOCAL_CCY_NATIVE", "Balance Book Value Local Native"}, {"BALANCE_BOOK_VALUE_BASE_CCY_NATIVE", "Balance Book Value Base Native"}, {"YIELD_FOR_MATH_ADJ", "Yield For Math Adj"}, {"INITIAL_TRANS_TYPE", "Initial Trans Type"}, {"BALANCE_NAIC_CARRYING_VALUE_LOCAL_CCY", "Balance NAIC Carrying Value Local"}, {"BALANCE_NAIC_CARRYING_VALUE_BASE_CCY", "Balance NAIC Carrying Value Base"}, {"BALANCE_NAIC_SEC_ADJ_LOCAL_CCY", "Balance NAIC Sec Adj Local"}, {"BALANCE_NAIC_SEC_ADJ_BASE_CCY", "Balance NAIC Sec Adj Base"},{"average_cost_yield","Average Cost Yield"},{"AOCI_REMAIN_BALANCE_BV_CCY_BASE", "AOCI Remain Balance BV - Base"}, {"AOCI_REMAIN_BALANCE_BV_CCY_LOCAL", "AOCI Remain Balance BV - Local"}, {"AOCI_REMAIN_BALANCE_NON_BV_CCY_BASE", "AOCI Remain Balance Non BV - Base"}, {"AOCI_REMAIN_BALANCE_NON_BV_CCY_LOCAL", "AOCI Remain Balance Non BV - Local"}, {"AOCI_REMAIN_BALANCE_REP_CCY_BASE", "AOCI Remain Balance Rep - Base"}, {"AOCI_REMAIN_BALANCE_REP_CCY_LOCAL", "AOCI Remain Balance Rep - Local"}, {"BALANCE_WRITE_OFF_LOCAL_CCY", "Balance Write Off - Local"}, {"BALANCE_WRITE_OFF_BASE_CCY", "Balance Write Off - Base"}}),
			    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Transaction No", type text},{"Lot ID", type text}}),
			    #"Filtered Rows - Incremental Refresh" = Table.SelectRows(#"Changed Type", each [As Of Date] >= Date.From(RangeStart) and [As Of Date] < Date.From(RangeEnd))
			in
			    #"Filtered Rows - Incremental Refresh"

	measure 'Security Lots Title' = ```
			
			VAR maxdate =
			    MAX ( 'Securities Lots Fact'[As Of Date] )
			RETURN
			    "Security Lots" & ", "
			        & SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) & ", "
			        & SELECTEDVALUE ( Framework[Framework Display] ) & ", "
			        & FORMAT ( maxdate, "dd-mmm-yy" )
			
			```
		lineageTag: 5234d812-33b3-4dbf-a32c-6d1373c8bf25

	measure 'Rep Rate (Security Lots)' = ```
			
			VAR maxd =
			    MAX ( 'Period'[Period] )
			VAR fxrate =
			    SWITCH (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			        "USD",
			            CALCULATE (
			                MIN ( 'Securities Lots Fact'[Local To USD Rate] ),
			                FILTER (
			                    'Securities Lots Fact',
			                    'Securities Lots Fact'[As Of Period] = maxd
			                )
			            ),
			        "CAD",
			            CALCULATE (
			                MIN ( 'Securities Lots Fact'[Local To CAD Rate] ),
			                FILTER (
			                    'Securities Lots Fact',
			                    'Securities Lots Fact'[As Of Period] = maxd
			                )
			            ),
			        "HKD",
			            CALCULATE (
			                MIN ( 'Securities Lots Fact'[Local To HKD Rate] ),
			                FILTER (
			                    'Securities Lots Fact',
			                    'Securities Lots Fact'[As Of Period] = maxd
			                )
			            ),
			        "Company",
			            CALCULATE (
			                MIN ( 'Securities Lots Fact'[Local To FUNC Rate] ),
			                FILTER (
			                    'Securities Lots Fact',
			                    'Securities Lots Fact'[As Of Period] = maxd
			                )
			            )
			        ,"SCD Base",
			            CALCULATE (
			                MIN ( 'Securities Lots Fact'[Local Exchange Rate] ),
			                FILTER (
			                    'Securities Lots Fact',
			                    'Securities Lots Fact'[As Of Period] = maxd
			                )
			            )
			    )
			RETURN
			    fxrate
			
			```
		formatString: 0.000000
		lineageTag: b427a513-aca3-483c-811f-6badb56b7e0e

	measure 'Reporting Currency (Security Lots)' = ```
			
			VAR SelectedCurrency =
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] )
			VAR ReportingCurrency =
			    IF (
			        NOT ISEMPTY ( 'Securities Lots Fact' ),
			        IF (
			            SelectedCurrency = "Company",
			            FIRSTNONBLANK ( 'Securities Lots Fact'[Functional Ccy Code], TRUE () ),
			            IF (
			                SelectedCurrency = "SCD Base",
			                FIRSTNONBLANK ( 'Securities Lots Fact'[Base Currency Code], TRUE () ),
			                SelectedCurrency
			            )
			        )
			    )
			RETURN
			    ReportingCurrency
			
			```
		lineageTag: 68e410f4-f0e1-438a-9379-be700e4cb4a2

	measure 'Original Cost - Rep (Sec Lots)' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Original Cost - Base]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Original Cost - Base]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Original Cost - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Original Cost - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			))
			/*IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Original Cost - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[Original Cost - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[Original Cost - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Lots Fact'[Original Cost - FUNC] ),
							SUM ( 'Securities Lots Fact'[Original Cost - HKD] )
							)
						)
					)
				)
			*/
		lineageTag: 6a5d6d10-c85d-4cff-8fad-361eb7ec092f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Amortization/Accretion - Rep (Sec Lots)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance Int Appr - Base]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Balance Int Appr - Base]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Int Appr - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Int Appr - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			))
			/*IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Balance Int Appr - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[Balance Int Appr - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[Balance Int Appr - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Lots Fact'[Balance Int Appr - FUNC] ),
							SUM ( 'Securities Lots Fact'[Balance Int Appr - HKD] )
							)
						)
					)
				)*/
			
			```
		lineageTag: e187e935-076d-42dd-bf10-4cf9775a6765

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OID Amortization/Accretion - Rep (Sec Lots)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance OID Appr - Base]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Balance OID Appr - Base]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance OID Appr - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance OID Appr - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			))
			/*IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Balance OID Appr - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[Balance OID Appr - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[Balance OID Appr - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Lots Fact'[Balance OID Appr - FUNC] ),
							SUM ( 'Securities Lots Fact'[Balance OID Appr - HKD] )
							)
						)
					)
				)*/
			
			```
		lineageTag: 637c13a5-5142-46e1-b0c3-f47836b92630

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTTI Impairment - Rep (Sec Lots)' = [OTTI Impairment - Lots Rep (Sec Lots)]+[OTTI Impairment - Adjustment Rep (Sec Lots)]
		lineageTag: 2bfe5789-b4e0-4012-a134-96cd0eef253f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Remain Balance BV - Rep (Sec Lots)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[AOCI Remain Balance BV - Base]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[AOCI Remain Balance BV - Base]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance BV - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance BV - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			))
			/*IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[AOCI Remain Balance BV - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[AOCI Remain Balance BV - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[AOCI Remain Balance BV - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Lots Fact'[AOCI Remain Balance BV - FUNC] ),
							SUM ( 'Securities Lots Fact'[AOCI Remain Balance BV - HKD] )
							)
						)
					)
				)*/
			
			```
		lineageTag: 8615ccb8-121e-42d8-aa88-bed919cde654

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Deferred PL - Rep (Sec Lots)' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance Deferred PL - Base]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Balance Deferred PL - Base]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Deferred PL - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Deferred PL - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			))
			/*IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Balance Deferred PL - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[Balance Deferred PL - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[Balance Deferred PL - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Lots Fact'[Balance Deferred PL - FUNC] ),
							SUM ( 'Securities Lots Fact'[Balance Deferred PL - HKD] )
							)
						)
					)
				)*/
			)
		lineageTag: 2db1c037-3d61-47a8-91e2-a3ec84eeb198

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carrying Value - Rep (Sec Lots)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Carrying Value - Base]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Carrying Value - Base]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Carrying Value - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Carrying Value - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			))
			/*IF (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
			    SUM ( 'Securities Lots Fact'[Carrying Value - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[Carrying Value - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[Carrying Value - CAD] ),
			            IF (
			                SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
			                SUM ( 'Securities Lots Fact'[Carrying Value - FUNC] ),
			                SUM ( 'Securities Lots Fact'[Carrying Value - HKD] )
			            )
			        )
			    )
			)
			*/
			
			```
		lineageTag: be42625c-24d9-4dc4-bb69-4929d61ae623

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ECL/CECL Impairment - Rep (Sec Lots)' = ```
			
			VAR FW =
			    SELECTEDVALUE ( Framework[Framework] )
			VAR IFRS9_FW = 'Securities Lots Fact'[Balance CL Allowance - Rep (Sec Lots)] + 'Securities Lots Fact'[Balance Write Off - Rep (Sec Lots)]
			VAR USGAAP_FW = 'Securities Lots Fact'[Balance Recog CL Allowance - Rep (Sec Lots)] + 'Securities Lots Fact'[Balance Write Off - Rep (Sec Lots)]
			VAR IAS39_JGAAP_NAIC_FW = 'Securities Lots Fact'[OTTI Impairment - Rep (Sec Lots)] + 'Securities Lots Fact'[Balance Write Off - Rep (Sec Lots)]
			RETURN
			    SWITCH(
			        TRUE(),
			        FW = "IFRS9",IFRS9_FW,
			        FW = "USGAAP",USGAAP_FW,
			        FW = "IAS39"|| FW = "JGAAP"|| FW = "NAIC" ,IAS39_JGAAP_NAIC_FW,
			        BLANK ()
			    )
			
			/*VAR FW =
			    SELECTEDVALUE ( Framework[Framework] )
			VAR IFRS9_FW =
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Balance CL Allowance - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[Balance CL Allowance - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[Balance CL Allowance - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Lots Fact'[Balance CL Allowance - FUNC] ),
							SUM ( 'Securities Lots Fact'[Balance CL Allowance - HKD] )
							)
						)
					)
				)
			
			VAR USGAAP_FW =
			    IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Balance Recog CL Allowance - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[Balance Recog CL Allowance - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[Balance Recog CL Allowance - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Lots Fact'[Balance Recog CL Allowance - FUNC] ),
							SUM ( 'Securities Lots Fact'[Balance Recog CL Allowance - HKD] )
							)
						)
					)
				)
			
			
			VAR IAS39_JGAAP_NAIC_FW =
			    IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Balance Impairment - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[Balance Impairment - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[Balance Impairment - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Lots Fact'[Balance Impairment - FUNC] ),
							SUM ( 'Securities Lots Fact'[Balance Impairment - HKD] )
							)
						)
					)
				)
			
			
			RETURN
			    IF (
			        FW = "IFRS9",
			        IFRS9_FW,
			        IF (
			            FW = "USGAAP",
			            USGAAP_FW,
			        IF(
			            (FW="IAS39" || FW= "JGAAP" || FW= "NAIC"),
			            IAS39_JGAAP_NAIC_FW,
			            BLANK()
			        )
			        )
			    )*/
			
			```
		lineageTag: f70d00eb-aa46-4aa3-88ef-da8a43e9d6fd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Rep (Sec Lots)' = [Unrealized Gain/Loss - Lots Rep (Sec Lots)]+[Unrealized Gain/Loss - Adjustment Rep (Sec Lots)]
		lineageTag: 3a747dd0-8985-49d9-b673-931b787bee8b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fair Value Unaccrued - Rep (Sec Lots)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Fair Value Unaccrued - Base]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Fair Value Unaccrued - Base]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Fair Value Unaccrued - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Fair Value Unaccrued - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			))
			/*IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Fair Value Unaccrued - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[Fair Value Unaccrued - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[Fair Value Unaccrued - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Lots Fact'[Fair Value Unaccrued - FUNC] ),
							SUM ( 'Securities Lots Fact'[Fair Value Unaccrued - HKD] )
							)
						)
					)
				)*/
			
			```
		lineageTag: 4b6dc290-db20-41ab-9d45-55fcd2b01497

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Rep (Sec Lots)' = [Book Value - Lots Rep (Sec Lots)]+[Book Value - Adjustment Rep (Sec Lots)]
		lineageTag: 043a044c-76f2-41b0-ab30-9c91bfea4504

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Purpose Codes (Sec Lots)' = ```
			
			VAR FW =
			    SELECTEDVALUE ( Framework[Framework] )
			RETURN
			    CALCULATE (
			        IF (
			            FW = "IAS39",
			            SELECTEDVALUE ( Portfolios[IAS39 Trading Philosophy Code (D)] ),
			            IF (
			                FW = "USGAAP",
			                SELECTEDVALUE ( Portfolios[USGAAP Trading Philosophy Code (D)] ),
			                IF (
			                    FW = "JGAAP",
			                    SELECTEDVALUE ( Portfolios[JGAAP Trading Philosophy Code (D)] ),
			                    IF (
			                        FW = "IFRS9",
			                        
			                        SELECTEDVALUE ( Portfolios[IFRS Trading Philosophy Code (D)] ),
			                        --(FW= "USTAX" || FW= "NAIC"),
			                        IF (
			                            NOT (
			                                ISEMPTY ( 'Securities Lots Fact' )
			                            ),
			                            "AFS"
			                        )
			                    )
			                )
			            )
			        ),
			        FILTER (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[As Of Date]
			                = MAX ( 'Securities Lots Fact'[As Of Date] )
			        )
			    )
			```
		lineageTag: 97110c99-bd0a-4ff9-8583-f2bfdadae1e8

	measure 'Impairment Candidates Title' = ```
			
			VAR maxdate =
			    MAX ( 'Securities Lots Fact'[As Of Date] )
			RETURN
			    "Impairment Candidates" & ", "
			        & SELECTEDVALUE ( Framework[Framework Display] ) & ", "
			        & FORMAT ( maxdate, "dd-mmm-yy" )
			
			```
		lineageTag: c41eb072-b3fa-4134-8dec-864427f65751

	measure 'Impairment Amount Local' = ```
			
			var selact = SELECTEDVALUE('Impairment Slicer'[Values])
			var losspct= SELECTEDVALUE('Target Loss'[Loss Percent])
			RETURN
			SWITCH(
			TRUE(),
			selact="Equity OTTI Impairment",
			SUMX (
			    'Securities Lots Fact',
			    'Securities Lots Fact'[Fair Value Unaccrued - Local] - 'Securities Lots Fact'[Original Cost - Local]
			),
			selact="Credit Impairment",
			SUMX (
			    'Securities Lots Fact',
			    'Securities Lots Fact'[Book Value - Base]-'Securities Lots Fact'[Nominal]*(losspct)  
			),
			
			SUMX (
			    'Securities Lots Fact',
			     -'Securities Lots Fact'[Book Value - Base]+'Securities Lots Fact'[Nominal]*(losspct)  
			)
			)
			
			
			```
		lineageTag: 2a9f5aaa-caf1-49bb-a403-c6a76efc4680

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ratio of Local FV / BV' =
			
			DIVIDE(SUM ( 'Securities Lots Fact'[Fair Value Unaccrued - Local] ),SUM ( 'Securities Lots Fact'[Original Cost - Local] ),0)
		lineageTag: cdc152cc-cf09-406a-bf0f-f41e696c9b52

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ECL/CECL Impairment - Local (Sec Lots)' = ```
			
			
			SWITCH(SELECTEDVALUE ( Framework[Framework] ),
			"IFRS9",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			            SUM ( 'Securities Lots Fact'[Balance CL Allowance - Local] )
			            + SUM ( 'Securities Lots Fact'[Balance Write Off - Local] ),
			    CALCULATE (
			                SUM ( 'Securities Lots Fact'[Balance CL Allowance - Local] )
			            + SUM ( 'Securities Lots Fact'[Balance Write Off - Local] ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )),
			"USGAAP",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			        SUM ( 'Securities Lots Fact'[Balance Recog CL Allowance - Local] )
			            + SUM ( 'Securities Lots Fact'[Balance Write Off - Local] ),
			    CALCULATE (
			        SUM ( 'Securities Lots Fact'[Balance Recog CL Allowance - Local] )
			            + SUM ( 'Securities Lots Fact'[Balance Write Off - Local] ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )),
			"IAS39",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			        SUM ( 'Securities Lots Fact'[Balance Impairment - Local] )
			            + SUM ( 'Securities Lots Fact'[Balance Write Off - Local] ),
			    CALCULATE (
			        SUM ( 'Securities Lots Fact'[Balance Impairment - Local] )
			            + SUM ( 'Securities Lots Fact'[Balance Write Off - Local] ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )),
			"JGAAP",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			        SUM ( 'Securities Lots Fact'[Balance Impairment - Local] )
			            + SUM ( 'Securities Lots Fact'[Balance Write Off - Local] ),
			    CALCULATE(
			        SUM ( 'Securities lots Fact'[Balance Impairment - Local] )
			            + SUM ( 'Securities Lots Fact'[Balance Write Off - Local] ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )),
			"NAIC",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			        SUM ( 'Securities Lots Fact'[Balance Impairment - Local] )
			            + SUM ( 'Securities Lots Fact'[Balance Write Off - Local] ),
			    CALCULATE (
			        SUM ( 'Securities Lots Fact'[Balance Impairment - Local] )
			            + SUM ( 'Securities Lots Fact'[Balance Write Off - Local] ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    ))
			,BLANK())
			
			```
		lineageTag: 97dd621a-f860-4618-882a-b4074de703e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'JGAAP Impairment' = IF(SELECTEDVALUE(Framework[Framework])="JGAAP","IMPAIRMENT",BLANK())
		lineageTag: 780da7c2-3536-4e79-83a9-b926ff963298

	measure 'Activity Slicer' = ```
			
			var activityType= SELECTEDVALUE('Impairment Slicer'[Values])
			var sectype = SELECTEDVALUE('Securities Lots Fact'[Asset Class (Sec Lots)])
			var ret = 
			SWITCH(TRUE(),  activityType = "Private Equity OTTI Impairment",  "Private",
			AND(activityType = "Public Equity OTTI Impairment" ,NOT(sectype="Fixed Income")),"Public",
			"Fixed Income"
			)
			return ret
			```
		lineageTag: 60aa0544-7bf8-4dbe-9705-9c9a495a08df

	measure 'Activity Filter' = ```
			
			var activitytype = SELECTEDVALUE('Impairment Slicer'[Values])
			return
			SWITCH(
			    TRUE(),
			    AND(activitytype = "Private Equity OTTI Impairment",SELECTEDVALUE('Securities Lots Fact'[Public/Private Ind]) = [Activity Slicer]), 1, 
			    AND(activitytype = "Public Equity OTTI Impairment",AND(SELECTEDVALUE('Securities Lots Fact'[Public/Private Ind]) = [Activity Slicer],[Activity Slicer]<>"Fixed Income")), 1, 
			     AND(FIND("Credit",activitytype,1,0) = 1,SELECTEDVALUE('Securities Lots Fact'[Asset Class (Sec Lots)]) = [Activity Slicer]),1,0)
			```
		formatString: 0
		lineageTag: 136ccee4-c1a6-4042-b3ed-0e5130fc5bcd

	measure 'Impairment Amount QC' = ```
			
			VAR curr = 
			SELECTEDVALUE('Securities Lots Fact'[Local])
			VAR activity =
			    SELECTEDVALUE ( 'Impairment Slicer'[Values] )
			VAR target =
			    SWITCH(TRUE(),
			    NOT curr IN {"KRW","VND","JPY","IDR"},
			        SELECTEDVALUE(  'Securities Lots Fact'[Nominal] ) * (1-SELECTEDVALUE ( 'Target Loss'[Loss Percent] )/100),
			        ROUND(SELECTEDVALUE(  'Securities Lots Fact'[Nominal] ) * (1-SELECTEDVALUE ( 'Target Loss'[Loss Percent] )/100),0))
			
			VAR BV =
			    SUM ( 'Securities Lots Fact'[Book Value - Base] )
			VAR calc =
			    IF (
			        activity = "Credit Impairment",
			        BV - target,
			        IF (
			            activity = "Credit Recovery",
			            target - BV,
			            SELECTEDVALUE( 'Securities Lots Fact'[Fair Value Unaccrued - Local] ) - BV
			        )
			    )
			RETURN
			    calc
			```
		formatString: #,0.00
		lineageTag: c9cea669-ad5d-4234-85c2-7da195b8d16b

		changedProperty = FormatString

	measure '144A Flag (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[144A Flag], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 4aa5782d-9a8a-481a-b076-509a066a13f5

	measure 'Measurement Level' = ```
			
			var frmwrk = SELECTEDVALUE(Framework[Framework])
			var SecPort = SELECTEDVALUE('Securities Lots Fact'[Src Security Id]) & " - " & MID(SELECTEDVALUE('Securities Lots Fact'[Portfolio Code & Name]),1,8)
			var Lot = IF(frmwrk = "IAS39" || frmwrk = "NAIC",SELECTEDVALUE('Securities Lots Fact'[Transaction No]),SecPort)
			return Lot
			
			```
		lineageTag: 5c113b89-3aae-4c83-93ed-2487b0b512c8

	measure 'Impairment Loss Allowed' = ```
			SELECTEDVALUE('Securities Lots Fact'[Book Value - Base]) - SELECTEDVALUE('Securities Lots Fact'[Fair Value Unaccrued - Local])
			
			```
		formatString: #,0
		lineageTag: cbc0dfd6-0d40-4cff-8550-9ff9d9cbd662

		changedProperty = FormatString

	measure 'Impairment Loss (OTTI)' = ```
			
			var frmwrk = SELECTEDVALUE(Framework[Framework])
			VAR ias39 = SELECTEDVALUE('Securities Lots Fact'[Original Cost - Local])- SELECTEDVALUE('Securities Lots Fact'[Fair Value Unaccrued - Local])
			var naic_jgaap = SELECTEDVALUE('Securities Lots Fact'[Book Value - Base])-SELECTEDVALUE('Securities Lots Fact'[Fair Value Unaccrued - Local])
			var calc = IF(frmwrk = "IAS39", ias39, naic_jgaap)
			return calc
			
			```
		lineageTag: d27b95a1-1ad6-483d-909c-c00081b4af67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Effective Date Format' = FORMAT(SELECTEDVALUE('Securities Lots Fact'[As Of Date]),"YYYYMMDD")
		lineageTag: 90bcf92d-f218-471e-a188-b97940ff6f8c

	measure 'Impairment Amount Allowed' = ```
			
			var bv = SELECTEDVALUE('Book Values'[Book Values])
			var curr = SELECTEDVALUE('Securities Lots Fact'[Local])
			return
			SWITCH(TRUE(),
			bv = "Original Book Value" && curr in {"IDR","JPY","KRW","VND"}, 
			    ROUND(SUM('Securities Lots Fact'[Fair Value Unaccrued - Local])-SUM('Securities Lots Fact'[Original Cost - Local]),0),
			bv = "Original Book Value",
			    SUM('Securities Lots Fact'[Fair Value Unaccrued - Local])-SUM('Securities Lots Fact'[Original Cost - Local]),
			curr in {"IDR","JPY","KRW","VND"},
			    ROUND(SUM('Securities Lots Fact'[Fair Value Unaccrued - Local])-SUM('Securities Lots Fact'[Book Value - Local]),0),
			SUM('Securities Lots Fact'[Fair Value Unaccrued - Local])-SUM('Securities Lots Fact'[Book Value - Local]))
			```
		formatString: 0.00
		lineageTag: ab9b0157-3100-48ef-9bbb-f87e28013bff

		changedProperty = FormatString

	measure 'SCD Framework' =
			
			var fw = SELECTEDVALUE('Securities Lots Fact'[Framework Code])
			return
			IF(fw = "NAIC","STAT",fw)
		lineageTag: 4b910322-0e6b-4c80-810f-9e2a8f998a0c

	measure 'Accrual Currency (Sec Lots)' = ```
			
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Accrual Currency], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 5d79786f-55dd-4d27-b8a7-98d33b29c037

	measure 'Cusip (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Cusip], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 9032d100-eaf2-4bc4-b260-a2f09a11875a

	measure 'Isin (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Isin], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 084795f4-c404-4b6b-ad37-7c3d5212f121

	measure 'Portfolio Owner (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Portfolio Owner (D)],TRUE()),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 23e67aeb-f103-43e4-93ef-8280863a58aa

	measure 'Portfolio Sleeve Status (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Portfolio Sleeve Status],TRUE()),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 9be51800-7a15-4cdb-9e5c-0e3f851bbc0a

	measure 'Private Portf Ind (Sec Lots)' =
			
			CALCULATE (
			    SUM('Portfolios Attributes'[Private Portf Ind (D)]),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		formatString: 0
		displayFolder: Portfolio Attributes
		lineageTag: 1fea0f75-c204-4129-a5c2-d1d894956885

	measure 'Maximis Portfolio Number (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Maximis Portfolio Number],TRUE()),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: f29971ae-0a8f-46db-9096-163bf4d30d2c

	measure 'IAS39 Trading Philosophy Code (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[IAS39 Trading Philosophy Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 388d40aa-8181-4e15-9346-8b450449cd74

	measure 'IFRS Trading Philosophy Code (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[IFRS Trading Philosophy Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: b5b87fe8-cfa5-4ae7-b508-802e3c58f14b

	measure 'Portfolio Name (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Portfolio Name],TRUE()),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 2a89c0ed-220b-47f4-93c3-a8f5777d1762

	measure 'Investment Desk (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Investment Desk (D)],TRUE()),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 70efde08-e0e5-4325-a6f5-0066d0049600

	measure 'Portfolio Manager Name (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Portfolio Manager Name (D)],TRUE()),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 587edfd1-72b2-4a12-be9a-e9aaa01e3607

	measure 'Security Description (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Security Description], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 74bd3c2f-4e71-4e53-893b-a79a038cdb52

	measure 'FI Type (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Fi Type], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 826ac5eb-f1b2-4632-8cb3-30d29133501f

	measure 'Issue Dt (Sec Lot)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Issue Dt], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		formatString: yyyy-mm-dd
		displayFolder: Security Values
		lineageTag: 3e9baa1c-f344-407b-b2ca-9b87372c62ce

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'AOCI Remain Balance Non BV - Rep (Sec Lots)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[AOCI Remain Balance Non BV - Base]),
			    CALCULATE(
			        SUM('Securities Lots Fact'[AOCI Remain Balance Non BV - Base]),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance Non BV - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance Non BV - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			))
			/*IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[AOCI Remain Balance Non BV - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[AOCI Remain Balance Non BV - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[AOCI Remain Balance Non BV - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Lots Fact'[AOCI Remain Balance Non BV - FUNC] ),
							SUM ( 'Securities Lots Fact'[AOCI Remain Balance Non BV - HKD] )
							)
						)
					)
				)*/
			
			
			
			```
		lineageTag: e2d4c1ee-ab36-4ddd-b2f1-a932dbd9217e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Remain Balance Rep - Rep (Sec Lots)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[AOCI Remain Balance Rep - Base]),
			    CALCULATE(
			        SUM('Securities Lots Fact'[AOCI Remain Balance Rep - Base]),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance Rep - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance Rep - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			))
			/*IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[AOCI Remain Balance Rep - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[AOCI Remain Balance Rep - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[AOCI Remain Balance Rep - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Lots Fact'[AOCI Remain Balance Rep - FUNC] ),
							SUM ( 'Securities Lots Fact'[AOCI Remain Balance Rep - HKD] )
							)
						)
					)
				)*/
			
			
			```
		lineageTag: 174f3ea3-78d3-42f8-be86-52ea8b682f86

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Percentage Difference' = ```
			
			DIVIDE(
			    SUM('Securities Lots Fact'[Fair Value Unaccrued - Local])-SUM('Securities Lots Fact'[Book Value - Local]),
			    SUM('Securities Lots Fact'[Book Value - Local]),0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c3a8e05b-da0c-4323-91e2-db4a4d8ab087

		changedProperty = FormatString

	measure 'Decline Category' =
			
			SWITCH(
			    TRUE(),
			    [Percentage Difference]>0,"Gain",
			    AND([Percentage Difference]<0,[Percentage Difference]>=-0.1),"0%-10%",
			    AND([Percentage Difference]<-0.1,[Percentage Difference]>=-0.2),"11%-20%",
			    AND([Percentage Difference]<-0.2,[Percentage Difference]>=-0.3),"21%-30%",
			    AND([Percentage Difference]<-0.3,[Percentage Difference]>=-0.4),"31%-40%",
			    AND([Percentage Difference]<-0.4,[Percentage Difference]>=-0.5),"41%-50%",
			    AND([Percentage Difference]<-0.5,[Percentage Difference]>=-0.6),"51%-60%",
			    AND([Percentage Difference]<-0.6,[Percentage Difference]>=-0.7),"61%-70%",
			    AND([Percentage Difference]<-0.7,[Percentage Difference]>=-0.8),"71%-80%",
			    AND([Percentage Difference]<-0.8,[Percentage Difference]>=-0.9),"81%-90%",
			    "100%")
		lineageTag: 339a41dc-edb8-4498-9c4d-9d64381431d2

	measure 'Issuer Name (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[Issuer], TRUE () ),
			   FILTER(
			       'Securities Position Fact',
			       'Securities Position Fact'[Security NK]=SELECTEDVALUE('Securities Lots Fact'[Security NK])))
			
			```
		lineageTag: 0ed62692-a693-46a3-875b-5a440c91ce5f

	measure 'Day Count (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Day Count], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 8fd700ba-46a9-4d4f-99b6-c913c2937f55

	measure 'Inv Lp Port Code (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Inv Lp Port Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 01b40578-f170-4c3a-882a-9f86fa7eba17

	measure 'Custodian Name (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Custodian Name (D)],TRUE()),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 9cc1c33b-ba93-49a6-8bc8-f6292bc29ad0

	measure 'Liability Surplus (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Liability Surplus (D)],TRUE()),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 7474b2d5-e634-4226-9115-240143ba3381

	measure 'Lawson Legal Id (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Lawson Legal ID (D)],TRUE()),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: af1e4753-ec4b-4964-84cf-106ef2a6dafd

	measure 'Maturity Days (Sec Lots)' = ```
			
			var mat = 
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Maturity Days (D)], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			var calc = 
			IF (
			    mat < 0,
			    mat * -1,
			    mat
			)
			return calc
			
			```
		formatString: 0
		displayFolder: Security Values
		lineageTag: 77fe43bd-8ce6-46ab-b7ac-688a8d457fbd

	measure 'S&P Short Term Rating (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[S&P Short Term Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 8d23a05f-51d8-4dd2-b3b3-ae3fc513787b

	measure 'Fitch Short Term Rating (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Fitch Short Term Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 2d503318-396c-49f8-a026-6fb3dd424044

	measure 'Dbrs (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Dbrs], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: b2e819b1-ea3b-45f3-9c3f-ad27c89efa69

	measure 'Moodys Short Term Rating (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Moodys Short Term Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 85a36690-34b5-41fe-bea7-8b1ed671cf18

	measure 'Internal (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Internal], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: c3518000-09a4-4931-89a3-3a795574c3bd

	measure 'Sedol (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Sedol], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: c10cf1ca-69bb-4ba3-a558-d7ae8ff266c6

	measure 'Official PPN (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Official PPN], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 0be19ac0-52d4-49b1-bec2-c156364075b3

	measure 'Infor Acquisition Rate (Sec Lots)' = ```
			
			var local =  if(SUM ( 'Securities Lots Fact'[Original Cost - Local] )=0,1,SUM ( 'Securities Lots Fact'[Original Cost - Local] ))
			return
			
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE('Reporting Currency'[Rep in Currency])="SCD Base",SUM ( 'Securities Lots Fact'[Original Cost - Base] )/local,
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",SUMX ( 'Securities Lots Fact',RELATED('Fx Rate DQ'[USD BS Rate]) )/local,
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",SUMX ( 'Securities Lots Fact',RELATED('Fx Rate DQ'[CAD BS Rate]) )/local,
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company", SUMX ( 'Securities Lots Fact',RELATED('Fx Rate DQ'[FUNC BS Rate]) )/local,
			    SUMX ( 'Securities Lots Fact',RELATED('Fx Rate DQ'[HKD BS Rate]) )/local
			)
			
			```
		formatString: 0.000000
		lineageTag: d463c1dd-bc41-4090-929b-a21706c12b8b

	measure 'Primary Asset Type (Sec Lots)' = ```
			
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Primary Asset Type], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: e15bc50a-ff0b-455e-a805-27f8b5fac7ed

	measure 'Units (LH)' = ```
			
			VAR closePeriod =
			    MAX ( Period[Period] )
			VAR Dt =
			    CALCULATE (
			        SUM (
			            'Securities Lots Fact'[Nominal]
			        ),
			        ALL ( 'Period' ),
			        'Securities Lots Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		isHidden
		displayFolder: Lots Research Attributes
		lineageTag: f97657ea-a0c5-4e5a-9b2e-9e71eb721c23

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Local (LH)' = ```
			
			VAR closePeriod =
			    MAX ( Period[Period] )
			VAR Dt =
			    CALCULATE (
			        SUM(
			            'Securities Lots Fact'[Book Value - Local]
			        ),
			        ALL ( 'Period' ),
			        'Securities Lots Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		isHidden
		displayFolder: Lots Research Attributes
		lineageTag: 66f26379-1802-437e-b18d-6eb0ff1614b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Position Lots History Title' = ```
			
			VAR maxdate =
			    MAX ('Securities Lots Fact'[As Of Date])
			RETURN
			    "Position Lots History" & ", "
			        & SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) & ", "
			        & SELECTEDVALUE ( Framework[Framework Display] ) & ", "
			        & FORMAT ( maxdate, "dd-mmm-yy" )
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 93091d2d-5df1-4262-972e-16b50774cdb3

	measure 'Fair Value Unaccrued - Rep (LH)' = ```
			
			VAR Prd =
			    MAX ( Period[Period] )
			RETURN
			    CALCULATE (
			        IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Fair Value Unaccrued - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUMX ('Securities Lots Fact','Securities Lots Fact'[Fair Value Unaccrued - Local]*RELATED('Fx Rate DQ'[USD BS Rate])),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUMX ('Securities Lots Fact','Securities Lots Fact'[Fair Value Unaccrued - Local]*RELATED('Fx Rate DQ'[CAD BS Rate])),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUMX ('Securities Lots Fact','Securities Lots Fact'[Fair Value Unaccrued - Local]*RELATED('Fx Rate DQ'[FUNC BS Rate])),
							SUMX ('Securities Lots Fact','Securities Lots Fact'[Fair Value Unaccrued - Local]*RELATED('Fx Rate DQ'[HKD BS Rate]))
							)
						)
					)
				),
			        ALL(Period),
			        'Securities Lots Fact'[As Of Period] <= Prd
			        
			    )
			
			```
		isHidden
		displayFolder: Lots Research Attributes
		lineageTag: e71a6c4b-89cb-42d1-b2ac-275b977b53d1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Rep (LH)' = ```
			
			VAR Prd =
			    MAX ( Period[Period] )
			RETURN
			    CALCULATE (
			        IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Book Value - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUMX ('Securities Lots Fact','Securities Lots Fact'[Book Value - Local]*RELATED('Fx Rate DQ'[USD BS Rate]) ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUMX ('Securities Lots Fact','Securities Lots Fact'[Book Value - Local]*RELATED('Fx Rate DQ'[CAD BS Rate]) ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUMX ('Securities Lots Fact','Securities Lots Fact'[Book Value - Local]*RELATED('Fx Rate DQ'[FUNC BS Rate]) ),
							SUMX ('Securities Lots Fact','Securities Lots Fact'[Book Value - Local]*RELATED('Fx Rate DQ'[HKD BS Rate]) )
							)
						)
					)
				),
			        ALL ( PERIOD ),
			        'Securities Lots Fact'[As Of Period] <= Prd
			    )
			
			```
		isHidden
		displayFolder: Lots Research Attributes
		lineageTag: 9e10f0df-a405-483b-a161-86e67ef60bbc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Original Cost - Rep (LH)' = ```
			
			VAR Prd =
			    MAX ( Period[Period] )
			RETURN
			    CALCULATE (
			        IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Original Cost - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUMX ('Securities Lots Fact', 'Securities Lots Fact'[Original Cost - Local]*RELATED('Fx Rate DQ'[USD BS Rate]) ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUMX ('Securities Lots Fact', 'Securities Lots Fact'[Original Cost - Local]*RELATED('Fx Rate DQ'[CAD BS Rate]) ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUMX ('Securities Lots Fact', 'Securities Lots Fact'[Original Cost - Local]*RELATED('Fx Rate DQ'[FUNC BS Rate]) ),
							SUMX ('Securities Lots Fact', 'Securities Lots Fact'[Original Cost - Local]*RELATED('Fx Rate DQ'[HKD BS Rate]) )
							)
						)
					)
				),
			        ALL ( PERIOD ),
			        'Securities Lots Fact'[As Of Period] <= Prd
			    )
			
			```
		isHidden
		displayFolder: Lots Research Attributes
		lineageTag: 017b8c9b-82d0-40e3-a34a-a265444eaad4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss CCY - Rep (LH)' = ```
			
			VAR Prd = MAX ( Period[Period] )
			
			RETURN
			    CALCULATE (
			        IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Unrealized Gain/Loss CCY - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUMX ('Securities Lots Fact', 'Securities Lots Fact'[Unrealized Gain/Loss CCY - Local]*RELATED('Fx Rate DQ'[USD BS Rate]) ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUMX ('Securities Lots Fact', 'Securities Lots Fact'[Unrealized Gain/Loss CCY - Local]*RELATED('Fx Rate DQ'[CAD BS Rate]) ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUMX ('Securities Lots Fact', 'Securities Lots Fact'[Unrealized Gain/Loss CCY - Local]*RELATED('Fx Rate DQ'[FUNC BS Rate]) ),
							SUMX ('Securities Lots Fact', 'Securities Lots Fact'[Unrealized Gain/Loss CCY - Local]*RELATED('Fx Rate DQ'[HKD BS Rate]) )
							)
						)
					)
				),
			        ALL ( PERIOD ),
			        'Securities Lots Fact'[As Of Period] <= Prd
			    )
			
			```
		isHidden
		displayFolder: Lots Research Attributes
		lineageTag: c06e9a27-f018-4eb8-ad6f-7f82e617a5ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss Sec - Rep (LH)' = ```
			
			VAR Prd = MAX ( Period[Period] )
			
			RETURN
			    CALCULATE (
			        IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Unrealized Gain/Loss Sec - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUMX ('Securities Lots Fact', 'Securities Lots Fact'[Unrealized Gain/Loss Sec - Local]*RELATED('Fx Rate DQ'[USD BS Rate]) ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUMX ('Securities Lots Fact', 'Securities Lots Fact'[Unrealized Gain/Loss Sec - Local]*RELATED('Fx Rate DQ'[CAD BS Rate]) ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUMX ('Securities Lots Fact', 'Securities Lots Fact'[Unrealized Gain/Loss Sec - Local]*RELATED('Fx Rate DQ'[FUNC BS Rate]) ),
							SUMX ('Securities Lots Fact', 'Securities Lots Fact'[Unrealized Gain/Loss Sec - Local]*RELATED('Fx Rate DQ'[HKD BS Rate]) )
							)
						)
					)
				),
			        ALL ( PERIOD ),
			        'Securities Lots Fact'[As Of Period] <= Prd
			    )
			
			```
		isHidden
		displayFolder: Lots Research Attributes
		lineageTag: 7869f0a8-8254-41cb-bbf3-74a75c8c002f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Local Exchange Rate (LH)' = ```
			
			VAR closePeriod =
			    MAX ( Period[Period] )
			VAR Dt =
			    CALCULATE (
			        FIRSTNONBLANK ( 'Securities Lots Fact'[Local Exchange Rate], TRUE () ),
			        ALL ( 'Period' ),
			        'Securities Lots Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		formatString: 0.000000
		isHidden
		displayFolder: Lots Research Attributes
		lineageTag: 9d6a4e82-8d1b-44aa-ae69-edcbf870e034

	measure 'Original Cost - Local (LH)' = ```
			
			VAR closePeriod =
			    MAX ( Period[Period] )
			VAR Dt =
			    CALCULATE (
			        SUM (
			            'Securities Lots Fact'[Original Cost - Local]
			        ),
			        ALL ( 'Period' ),
			        'Securities Lots Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		isHidden
		displayFolder: Lots Research Attributes
		lineageTag: e36c1835-aee4-4d6b-b671-976c368631b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fair Value Unaccrued - Local (LH)' = ```
			
			VAR closePeriod =
			    MAX ( Period[Period] )
			VAR Dt =
			    CALCULATE (
			        SUM (
			            'Securities Lots Fact'[Fair Value Unaccrued - Local]
			        ),
			        ALL ( 'Period' ),
			        'Securities Lots Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		isHidden
		displayFolder: Lots Research Attributes
		lineageTag: 08742d80-e056-4391-9a97-731fa46cf0ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Units (Sec Lots)' =
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Lots Fact'[Units] ),
			    CALCULATE (
			        SUM ( 'Securities Lots Fact'[Units]),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			)
		lineageTag: 491d40dd-737f-4f71-ac1d-963b8034bc80

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Amortization/Accretion - Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance Int Appr - Local]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Balance Int Appr - Local]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		lineageTag: 50982fe2-afa4-4e33-b68f-1301a2b4289b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Remain Balance BV - Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[AOCI Remain Balance BV - Local]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[AOCI Remain Balance BV - Local]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		lineageTag: 34324d21-9326-4601-835a-c26f9fafa7d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Remain Balance Non BV - Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[AOCI Remain Balance Non BV - Local]),
			    CALCULATE(
			        SUM('Securities Lots Fact'[AOCI Remain Balance Non BV - Local]),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			)
		lineageTag: f795f733-d8d8-427b-b711-c30905ad8790

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Remain Balance Rep - Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[AOCI Remain Balance Rep - Local]),
			    CALCULATE(
			        SUM('Securities Lots Fact'[AOCI Remain Balance Rep - Local]),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			)
		lineageTag: 89fd2f03-f5a6-44c6-80e7-13d4f8a4310e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Deferred PL - Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance Deferred PL - Local]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Balance Deferred PL - Local]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		lineageTag: fe8c3166-d636-4b82-818e-8526b281d198

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTTI Impairment - Local (Sec Lots)' = [OTTI Impairment - Lots Local (Sec Lots)]+[OTTI Impairment - Adjustment Local (Sec Lots)]
		lineageTag: a4ebefa5-c625-4810-b24d-3d37fb33b487

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OID Amortization/Accretion - Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance OID Appr - Local]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Balance OID Appr - Local]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		lineageTag: dae8cc79-c2f5-4673-952d-5b9ea319c143

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Local (Sec Lots)' = [Book Value - Lots Local (Sec Lots)]+[Book Value - Adjustment Local (Sec Lots)]
		lineageTag: 2f3b6279-fc1e-4a62-ab66-ac8814117ef8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carrying Value - Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Carrying Value - Local]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Carrying Value - Local]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		lineageTag: 937d12bb-c683-4331-b550-ecf34d28aec3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fair Value Unaccrued - Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Fair Value Unaccrued - Local]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Fair Value Unaccrued - Local]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		lineageTag: e00c8f27-2d32-4b5f-b426-55671c3fc142

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Original Cost - Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Original Cost - Local]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Original Cost - Local]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		lineageTag: efb93537-7240-451b-83d0-c3c3a99e5345

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Local (Sec Lots)' = [Unrealized Gain/Loss - Lots Local (Sec Lots)]+[Unrealized Gain/Loss - Adjustment Local (Sec Lots)]
		lineageTag: 489b0f3b-2012-4da5-909a-14fec1cfc4a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rep Rate (Sec Lots)' = AVERAGEX( 'Securities Lots Fact', 1 * 'Fx Rate DQ'[Rep Rate])
		formatString: 0.000000
		lineageTag: d15628ae-9cdb-44f6-9677-3635b69e70fb

	measure 'ML NAIC Report Part Cd (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML NAIC Report Part Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 0e0d28b3-8fe5-4389-a40d-72c638e1d1ac

	measure 'ML NAIC Instrument Type Cd (Sec Lots)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML NAIC Instrument Type Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 499fa9ef-04ad-4553-89a3-e491ab05b212

	measure 'Current Book Value - Rep (Sec Lots)' =
			
			/*'Securities Lots Fact'[Book Value - Rep (Sec Lots)]+'Securities Lots Fact'[OTTI Impairment - Rep (Sec Lots)]+'Securities Lots Fact'[AOCI Remain Balance BV - Rep (Sec Lots)]*/
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Adjusted Book Value Base]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Adjusted Book Value Base]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Adjusted Book Value Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Adjusted Book Value Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			))
		lineageTag: fee5d2e9-fff6-4e8b-9ba3-c5779b04f334

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Timestamp (Sec Lots)' = ```
			
			IF (
			    NOT ISEMPTY ( 'Securities Lots Fact' ),
			    NOW (),
			    BLANK ()
			)
			
			```
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		lineageTag: e7d37a17-a4f9-473e-8701-d0bdfa347679

		changedProperty = FormatString

	measure 'Units - Rep (Sec Lots)' = ```
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX('Securities Lots Fact', 'Securities Lots Fact'[Units] *'Securities Lots Fact' [Local Exchange Rate]),
			    CALCULATE (
			            SUMX('Securities Lots Fact','Securities Lots Fact'[Units] *'Securities Lots Fact' [Local Exchange Rate]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX('Securities Lots Fact', 'Securities Lots Fact'[Units] *'Fx Rate DQ'[Rep Rate]),
			
			            CALCULATE (
			                    SUMX('Securities Lots Fact', 'Securities Lots Fact'[Units] *'Fx Rate DQ'[Rep Rate]),
			                LASTDATE('Securities Lots Fact'[As Of Date])
			            )
			        ))
			
			```
		lineageTag: ecc9688c-11bc-4395-bea7-2479a02b4960

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance CL Allowance - Rep (Sec Lots)' =
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance CL Allowance - Base]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Balance CL Allowance - Base]),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance CL Allowance - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance CL Allowance - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			))
		lineageTag: d2450bf1-936b-4e57-b296-2b830d91d64c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Recog CL Allowance - Rep (Sec Lots)' =
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance Recog CL Allowance - Base]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Balance Recog CL Allowance - Base]),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Recog CL Allowance - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Recog CL Allowance - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			))
		lineageTag: 8ca116f1-df85-4f89-ad60-6994d6c45e10

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Write Off - Rep (Sec Lots)' =
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance Write Off - Base]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Balance Write Off - Base]),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Write Off - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Write Off - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			))
		lineageTag: 1d910dcd-643a-43e1-b5a2-6d79c3ed331a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Impairment Amount Allowed - Rep' =
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    [Impairment Amount Allowed],
			    CALCULATE (
			[Impairment Amount Allowed],
			LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			)
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        [Impairment Amount Allowed] * [Rep Rate (IS)]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            [Impairment Amount Allowed] *  [Rep Rate (IS)]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			))
		lineageTag: 56d4d4c9-9470-4529-a942-f369ef7a3d75

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Maximis Lot Number (Sec Lots)' = CALCULATE(MAx('Securities Transaction GA Fact'[Trading Comment]),TREATAS(VALUES('Securities Lots Fact'[Transaction No]),'Securities Transaction GA Fact'[Transaction No]))
		lineageTag: 0f3647a0-a1be-4866-84db-8a3819c85d26

	measure 'MRM Sector Name (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Sector Name], TRUE () ),
			    'Securities Lots Fact'
			)
		lineageTag: 88d8450f-1855-4842-b7e8-29a3549c4c3f

	measure 'MRM Industry Subgroup Name (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Industry Subgroup Name], TRUE () ),
			    'Securities Lots Fact'
			)
		lineageTag: 53146cd9-1475-4b67-97a0-4e5d4219989c

	measure 'MRM Industry Sector Name (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Industry Sector Name], TRUE () ),
			    'Securities Lots Fact'
			)
		lineageTag: 9b590194-b5c0-4459-a752-ddd608319a1c

	measure 'MRM Industry Group Name (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Industry Group Name], TRUE () ),
			    'Securities Lots Fact'
			)
		lineageTag: 417b437d-0aae-4891-a4fc-487f2a4760a8

	measure 'Income Impairment - Local (Sec Lots)' =
			
			IF (
			    COUNTROWS ( 'Securities Lots Fact' ) > 0,
			    CALCULATE (
			        SUM ( 'Securities Transaction GA Fact'[Book Value - Local unsigned] ) * -1,
			        //Step1: Identify the impairments for the position
			        TREATAS (
			            VALUES ( 'Securities Lots Fact'[Src Positions ID] ),
			            'Securities Transaction GA Fact'[POS Trans Link]
			        ),
			        TREATAS (
			            VALUES ( 'Securities Lots Fact'[Lot ID] ),
			            'Securities Transaction GA Fact'[Match Src Transaction ID]
			        ),
			        'Securities Transaction GA Fact'[Bus Trans Code] = "TaxLotCorr",
			        'Securities Transaction GA Fact'[Transaction Purpose]
			            IN { "Income Impairment Reversal", "Income Impairment" },
			        'Securities Transaction GA Fact'[Trans Status] = "Active",
			        //Step2: Aggregate the cummulative impairment for the position
			        FILTER (
			            ALL ( Period[Date] ),
			            Period[Date] <= MAX ( Period[Date] )
			        ),
			        ALLSELECTED ( Securities ),
			        VALUES ( Securities[Primary Security ID] )
			    )
			)
		lineageTag: 5d14ee44-6948-4c23-95b6-e57a149e5186

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income Impairment - Rep (Sec Lots)' =
			
			IF (
			    COUNTROWS ( 'Securities Lots Fact' ) > 0,
			    CALCULATE (
			        SWITCH (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			            "SCD Base", SUM ( 'Securities Transaction GA Fact'[Book Value - Base unsigned] ) * -1,
			            SUMX (
			                'Securities Transaction GA Fact',
			                'Securities Transaction GA Fact'[Book Value - Local unsigned] * [Rep Rate]
			            ) * -1
			        ),
			        //Step1: Identify the impairments for the position
			        TREATAS (
			            VALUES ( 'Securities Lots Fact'[Src Positions ID] ),
			            'Securities Transaction GA Fact'[POS Trans Link]
			        ),
			        TREATAS (
			            VALUES ( 'Securities Lots Fact'[Lot ID] ),
			            'Securities Transaction GA Fact'[Match Src Transaction ID]
			        ),
			        'Securities Transaction GA Fact'[Bus Trans Code] = "TaxLotCorr",
			        'Securities Transaction GA Fact'[Transaction Purpose]
			            IN { "Income Impairment Reversal", "Income Impairment" },
			        'Securities Transaction GA Fact'[Trans Status] = "Active",
			        //Step2: Aggregate the cummulative impairment for the position
			        FILTER (
			            ALL ( Period[Date] ),
			            Period[Date] <= MAX ( Period[Date] )
			        ),
			        ALLSELECTED ( Securities ),
			        VALUES ( Securities[Primary Security ID] )
			    )
			)
		lineageTag: 44196ab4-0278-4e66-a0e7-6084cf297608

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Is PublicPP Ind (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[Is PublicPP Ind], TRUE () ),
			    'Securities Lots Fact'
			)
		lineageTag: 77becc78-5bbb-467d-b829-55d43a4647e6

	measure 'Yield For Math Adj (Sec Lots)' =
			
			CALCULATE(
			    MAX('Securities Transaction GA Fact'[Yield For Math Adj]),
			        TREATAS(
			        VALUES('Securities Lots Fact'[Unique Lot ID]),
			        'Securities Transaction GA Fact'[Lot ID]
			    ))
		isHidden
		lineageTag: eb501d4b-fbd8-4fe1-bb71-5c873bf4472a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Amortised Cost Local' =
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance Amortised Cost Local CCY]),
			    CALCULATE(
			        SUM('Securities Lots Fact'[Balance Amortised Cost Local CCY]),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			)
		lineageTag: c502a474-1475-4a64-b3f5-0bf7017a00ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bal Interest Appreciation Local' =
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Bal Interest Appreciation Local CCY]),
			    CALCULATE(
			        SUM('Securities Lots Fact'[Bal Interest Appreciation Local CCY]),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			)
		lineageTag: a1baa84d-d558-4638-a5a8-6db11873a22b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unreal Real Int Appr Disc Local' =
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Unreal Real Int Appr Disc Local CCY]),
			    CALCULATE(
			        SUM('Securities Lots Fact'[Unreal Real Int Appr Disc Local CCY]),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			)
		lineageTag: 35d76305-d969-40af-974c-de5feafa5fe6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unreal Real Int Appr Prem Local' =
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Unreal Real Int Appr Prem Local CCY] ),
			    CALCULATE(
			        SUM('Securities Lots Fact'[Unreal Real Int Appr Prem Local CCY] ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			)
		lineageTag: 4829e831-e2b8-4196-99c6-40ec99b4a24f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unreal Oid Accretion Local' =
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Unreal Oid Accretion Local CCY] ),
			    CALCULATE(
			        SUM('Securities Lots Fact'[Unreal Oid Accretion Local CCY] ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			)
		lineageTag: 319203ad-953d-4c0d-8bdf-b0c353174061

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Adjustment Local (Sec Lots)' = ```
			
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Book Value" )
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// RETURN 
			// SUMX(summarize('Securities Lots Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//  SUM('Securities GL Txn fact'[Local Txn Amt]),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  TREATAS(VALUES('Securities Lots Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//  vDateRange
			//  )
			// )
			// )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Book Value"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SUM ( 'Consolidated GL Balance Fact'[Local Balance Amt] ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Lots Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: 8559195e-b4a2-42c6-812a-88bee55a2ac5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Adjustment Rep (Sec Lots)' = ```
			
			// VAR vSelectedCurrency = SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency])
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Book Value" )
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// VAR vBVRep= 
			// SUMX(summarize('Securities Lots Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//      SWITCH (
			//              vSelectedCurrency,
			//              "CAD",[Adjustment Amount (CAD)],
			//                 "USD",[Adjustment Amount (USD)],
			//                 "HKD",[Adjustment Amount (HKD)],
			//                 [Adjustment Amount (Func)]
			//      ),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  TREATAS(VALUES('Securities Lots Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//     vDateRange
			// )
			// )
			// )
			// RETURN vBVRep
			VAR vSelectedCurrency =
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Book Value"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SWITCH (
			                    vSelectedCurrency,
			                    "CAD", [Adjustment_Amount (CAD)],
			                    "USD", [Adjustment_Amount (USD)],
			                    "HKD", [Adjustment_Amount (HKD)],
			                    [Adjustment_Amount (Func)]
			                ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Lots Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: ee02ae28-ae82-4e01-99dd-79764cb325c9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Adjustment Local (Sec Lots)' = ```
			
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Unrealized" )
			
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			
			// RETURN 
			// SUMX(summarize('Securities Lots Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//  SUM('Securities GL Txn fact'[Local Txn Amt]),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  TREATAS(VALUES('Securities Lots Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//  vDateRange
			//  )
			// )
			// )
			VAR vListofGLAccts=CALCULATETABLE(
			            VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			            'CAT Adjmt Config Table'[Measure Name] ="Unrealized")
			
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SUM ( 'Consolidated GL Balance Fact'[Local Balance Amt] ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Lots Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: d3051a37-f4de-4611-a68c-e1c16b5e5a7d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Adjustment Rep (Sec Lots)' = ```
			
			// VAR vSelectedCurrency = SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency])
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="Unrealized")
			
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// VAR vURRep= 
			// SUMX(summarize('Securities Lots Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//      SWITCH (
			//              vSelectedCurrency,
			//              "CAD",[Adjustment Amount (CAD)],
			//                 "USD",[Adjustment Amount (USD)],
			//                 "HKD",[Adjustment Amount (HKD)],
			//                 [Adjustment Amount (Func)]
			//      ),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  TREATAS(VALUES('Securities Lots Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//     vDateRange
			// )
			// )
			// )
			// RETURN vURRep
			VAR vSelectedCurrency = SELECTEDVALUE ('Reporting Currency'[Rep In Currency])
			VAR vListofGLAccts=CALCULATETABLE(
			            VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			            'CAT Adjmt Config Table'[Measure Name] ="Unrealized")
			
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SWITCH (
			                    vSelectedCurrency,
			                    "CAD", [Adjustment_Amount (CAD)],
			                    "USD", [Adjustment_Amount (USD)],
			                    "HKD", [Adjustment_Amount (HKD)],
			                    [Adjustment_Amount (Func)]
			                ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Lots Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: 6b5b2445-8b28-4aa7-8dd8-226fbbb3ff46

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTTI Impairment - Adjustment Local (Sec Lots)' = ```
			
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="ECL Impairment" )
			
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			
			// RETURN 
			// SUMX(summarize('Securities Lots Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//  SUM('Securities GL Txn fact'[Local Txn Amt]),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  TREATAS(VALUES('Securities Lots Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//  vDateRange
			//  )
			// )
			// )
			VAR vListofGLAccts=CALCULATETABLE(
			            VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			            'CAT Adjmt Config Table'[Measure Name] ="ECL Impairment")
			
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SUM ( 'Consolidated GL Balance Fact'[Local Balance Amt] ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Lots Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: 9bdab7ea-4d10-422f-80f2-fbd7c30f413e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTTI Impairment - Adjustment Rep (Sec Lots)' = ```
			
			// VAR vSelectedCurrency = SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency])
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//             'CAT Adjmt Config Table'[Measure Name] ="ECL Impairment")
			
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			
			// VAR vOTTIRep= 
			// SUMX(summarize('Securities Lots Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			// CALCULATE(
			//      SWITCH (
			//              vSelectedCurrency,
			//              "CAD",[Adjustment Amount (CAD)],
			//                 "USD",[Adjustment Amount (USD)],
			//                 "HKD",[Adjustment Amount (HKD)],
			//                 [Adjustment Amount (Func)]
			//      ),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  TREATAS(VALUES('Securities Lots Fact'[Transaction No]),'Securities GL Txn fact'[SCD Lot Id]),
			//     vDateRange
			// )
			// )
			// )
			        
			// RETURN vOTTIRep
			VAR vSelectedCurrency = SELECTEDVALUE ('Reporting Currency'[Rep In Currency])
			VAR vListofGLAccts=CALCULATETABLE(
			            VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			            'CAT Adjmt Config Table'[Measure Name] ="ECL Impairment")
			
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SWITCH (
			                    vSelectedCurrency,
			                    "CAD", [Adjustment_Amount (CAD)],
			                    "USD", [Adjustment_Amount (USD)],
			                    "HKD", [Adjustment_Amount (HKD)],
			                    [Adjustment_Amount (Func)]
			                ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                TREATAS (
			                    VALUES ( 'Securities Lots Fact'[Transaction No] ),
			                    'Consolidated GL Balance Fact'[SCD Lot Id]
			                ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: 8e5bd08b-bb04-47df-8b28-c61d84a206eb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Lots Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Book Value - Local]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Book Value - Local]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		lineageTag: 615f05e5-29ef-4564-9c2d-04aeff455a61

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Lots Rep (Sec Lots)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Book Value - Base]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Book Value - Base]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Book Value - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Book Value - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			))
			/*IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Book Value - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[Book Value - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[Book Value - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Lots Fact'[Book Value - FUNC] ),
							SUM ( 'Securities Lots Fact'[Book Value - HKD] )
							)
						)
					)
				)*/
			
			```
		lineageTag: ff8608a2-8d5e-4d51-8e92-30574a31555b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Lots Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Unrealized Gain/Loss - Local]),
			    CALCULATE (
			SUM('Securities Lots Fact'[Unrealized Gain/Loss - Local]),
			LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			)
			)
		lineageTag: 4ab5b1d3-34e3-4c1f-883f-13516c54da8b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Lots Rep (Sec Lots)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Unrealized Gain/Loss - Base]),
			    CALCULATE (
			SUM('Securities Lots Fact'[Unrealized Gain/Loss - Base]),
			LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			)
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Unrealized Gain/Loss - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Unrealized Gain/Loss - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			))
			
			
			```
		lineageTag: f9252bb2-12d2-49b7-a792-063c8866af01

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTTI Impairment - Lots Local (Sec Lots)' =
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance Impairment - Local]),
			    CALCULATE (
			SUM('Securities Lots Fact'[Balance Impairment - Local]),
			LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			)
			)
		lineageTag: 7ac45b0b-729d-4e73-b755-eed3f5fcd020

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTTI Impairment - Lots Rep (Sec Lots)' =
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance Impairment - Base]),
			    CALCULATE (
			SUM('Securities Lots Fact'[Balance Impairment - Base]),
			LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			)
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Impairment - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Impairment - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			))
			/*
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Lots Fact'[Balance Impairment - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Lots Fact'[Balance Impairment - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Lots Fact'[Balance Impairment - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Lots Fact'[Balance Impairment - FUNC] ),
							SUM ( 'Securities Lots Fact'[Balance Impairment - HKD] )
							)
						)
					)
				)
			*/
		lineageTag: a17999ed-10a4-459d-8374-c535f82c0f7f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Book Value Native - Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance Book Value Local Native]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Balance Book Value Local Native]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		lineageTag: 123248ae-bcab-496b-8e0b-4b6d55c37552

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Book Value - Rep (Sec Lots)' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Book Value - Base]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Book Value - Base]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Book Value - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Book Value - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			))
		lineageTag: fe6910cb-6f2b-47b3-a44d-e12735003b0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Book Value Native - Rep (Sec Lots)' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance Book Value Base Native]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Balance Book Value Base Native]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Book Value Local Native] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Book Value Local Native] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			))
		lineageTag: f1afe200-d139-4a2f-8958-0f6049a1d41c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Wash Sale Parent Security Id(Sec Lot)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Wash Sale Parent Security Id], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 2e20f3de-bccd-45bf-9b0e-a4172e11e7de

	measure 'JGAAP Trading Philosophy Code (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[JGAAP Trading Philosophy Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Lots Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		lineageTag: faf8b3a4-c056-4fb7-bd5b-4f682d761ce6

	measure 'Final Staging text' = ```
			
			VAR vCreditimpairmentStage = MAX('Securities Lots Fact'[Credit Impairment Stage])
			RETURN
			IF(
			    ISINSCOPE(Securities[Primary Security ID & Desc]),
			    VAR vCATStagingText =
			    MAXX(
			        'Securities Lots Fact',
			        VAR vAssetID = 'Securities Lots Fact'[SCD Security ID]
			        VAR vFramework='Securities Lots Fact'[Framework Code]
			        VAR vPeriod='Securities Lots Fact'[As Of Period]
			        VAR vLatestDate = 
			        CALCULATE(
			            MAX('Cat Staging Text Fact'[Txn Dt]),
			            'Cat Staging Text Fact'[Asset Id]=vAssetID,
			            'Cat Staging Text Fact'[Framework Cd]=vFramework,
			            'Cat Staging Text Fact'[Txn Period]<=vPeriod
			        )
			        RETURN
			        
			        CALCULATE(
			            MAX('Cat Staging Text Fact'[Staging Txt]),
			            'Cat Staging Text Fact'[Asset Id]=vAssetID,
			            'Cat Staging Text Fact'[Framework Cd]=vFramework,
			            'Cat Staging Text Fact'[Txn Dt]=vLatestDate
			        )
			    )
			    RETURN
			    COALESCE(vCATStagingText,vCreditimpairmentStage)
			)
			
			```
		lineageTag: c0bfaec5-3393-43d1-8ba3-f5a65f919904

	measure 'Staging Text' = ```
			
			IF(
			    ISINSCOPE(Securities[Primary Security ID & Desc]),
			    VAR vCATStagingText =
			    MAXX(
			        'Securities Lots Fact',
			        VAR vAssetID = 'Securities Lots Fact'[SCD Security ID]
			        VAR vFramework='Securities Lots Fact'[Framework Code]
			        VAR vPeriod='Securities Lots Fact'[As Of Period]
			        VAR vLatestDate = 
			        CALCULATE(
			            MAX('Cat Staging Text Fact'[Txn Dt]),
			            'Cat Staging Text Fact'[Asset Id]=vAssetID,
			            'Cat Staging Text Fact'[Framework Cd]=vFramework,
			            'Cat Staging Text Fact'[Txn Period]<=vPeriod
			        )
			        RETURN
			        
			        CALCULATE(
			            MAX('Cat Staging Text Fact'[Staging Txt]),
			            'Cat Staging Text Fact'[Asset Id]=vAssetID,
			            'Cat Staging Text Fact'[Framework Cd]=vFramework,
			            'Cat Staging Text Fact'[Txn Dt]=vLatestDate
			        )
			    )
			    RETURN
			   vCATStagingText)
			```
		lineageTag: 3e767e15-248b-4158-8ce8-39af8e0ccb7f

	measure 'Carrying Value - Adjustment Local (Sec Lots)' =
			[Book Value - Adjustment Local (Sec Lots)] +[Unrealized Gain/Loss - Adjustment Local (Sec Lots)]
			/*
			IF(NOT (ISBLANK('Securities Lots Fact'[Carrying Value - Local (Sec Lots)]) )&& NOT(ISBLANK('Securities Lots Fact'[Fair Value Unaccrued - Local (Sec Lots)])),
			IF (
			     'Securities Lots Fact'[Carrying Value - Local (Sec Lots)]='Securities Lots Fact'[Fair Value Unaccrued - Local (Sec Lots)], 'Securities Lots Fact'[Unrealized Gain/Loss - Adjustment Local (Sec Lots)])
			)*/
		lineageTag: 6a5beac7-59fd-4c45-a25d-e39cca1a99ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carrying Value - Adjustment Rep (Sec Lots)' =
			[Book Value - Adjustment Rep (Sec Lots)] + [Unrealized Gain/Loss - Adjustment Rep (Sec Lots)]
			/*
			IF(NOT (ISBLANK([Carrying Value - Rep (Sec Lots)]) )&& NOT(ISBLANK([Fair Value Unaccrued - Rep (Sec Lots)])),
			IF (
			     [Carrying Value - Rep (Sec Lots)]=[Fair Value Unaccrued - Rep (Sec Lots)], [Unrealized Gain/Loss - Adjustment Rep (Sec Lots)])
			)*/
		lineageTag: 94e3960b-d299-439e-89c3-7ff4e5b1cd69

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fair Value Unaccrued - Adjustment Local (Sec Lots)' = [Book Value - Adjustment Local (Sec Lots)]+ [Unrealized Gain/Loss - Adjustment Local (Sec Lots)]
		isHidden
		lineageTag: 57d95c4f-4efb-4507-9e1c-b72c2a4f38b5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fair Value Unaccrued - Adjustment Rep (Sec Lots)' = [Book Value - Adjustment Rep (Sec Lots)]+ [Unrealized Gain/Loss - Adjustment Rep (Sec Lots)]
		isHidden
		lineageTag: 3a0c35ea-33f7-4ef2-ae6e-0f93e3ffe10e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carrying Value Final - Local (Sec Lots)' = [Carrying Value - Local (Sec Lots)]+[Carrying Value - Adjustment Local (Sec Lots)]
		lineageTag: 21b5cdbf-b71d-4bf6-90b3-e33161d2de44

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carrying Value Final - Rep (Sec Lots)' = [Carrying Value - Rep (Sec Lots)]+[Carrying Value - Adjustment Rep (Sec Lots)]
		lineageTag: 2eddaea9-d5e4-4ecb-a663-c7b5ea613dd2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Adjusted GL Class (Sec Lots)' = ```
			
			VAR vMaxPeriodDate = MAX(Period[Date])
			VAR vLotId = VALUES('Securities Lots Fact'[Transaction No])
			VAR vAddRankFlagTable = 
			CALCULATETABLE(
			    ADDCOLUMNS(
			        'Adjust GL Reclass Fact',
			        "@Rank",RANKX('Adjust GL Reclass Fact','Adjust GL Reclass Fact'[Txn Dt])
			    ),
			    REMOVEFILTERS(period),
			    'Adjust GL Reclass Fact'[Txn Dt]<=vMaxPeriodDate,
			    TREATAS(vLotId,'Adjust GL Reclass Fact'[Scd Lot Id])
			)
			
			RETURN
			IF(COUNTROWS('Securities Lots Fact')>0, 
			MAXX(
			    vAddRankFlagTable, IF ([@Rank]=1 , 'Adjust GL Reclass Fact'[gl classification] )
			)
			)
			```
		lineageTag: 82beb634-439a-460e-b66b-c001610c0cc5

	measure 'Balance NAIC Carrying Value - Rep (Sec Lots)' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance NAIC Carrying Value Base]),
			    CALCULATE(
			        SUM('Securities Lots Fact'[Balance NAIC Carrying Value Base]),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance NAIC Carrying Value Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance NAIC Carrying Value Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			))
		lineageTag: 2193ccf8-865f-427c-bad0-4552c5bd3904

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance NAIC Carrying Value - Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance NAIC Carrying Value Local]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Balance NAIC Carrying Value Local]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		lineageTag: cdf6bef0-e3e9-44d6-88a9-d2c1f0998a86

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance NAIC Sec Adj - Local (Sec Lots)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance NAIC Sec Adj Local]),
			    CALCULATE (
			        SUM('Securities Lots Fact'[Balance NAIC Sec Adj Local]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		lineageTag: b9d61932-89e4-4ba7-a728-a4a0d65c3c7c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance NAIC Sec Adj - Rep (Sec Lots)' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Lots Fact'[Balance NAIC Sec Adj Base]),
			    CALCULATE(
			        SUM('Securities Lots Fact'[Balance NAIC Sec Adj Base]),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance NAIC Sec Adj Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance NAIC Sec Adj Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Lots Fact'[As Of Date])
			    )
			))
		lineageTag: 439a63b8-ccfc-40c3-a705-929c45087e65

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Remain Balance BV - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance BV - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance BV - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 2858f648-f205-4765-8702-a059271d1372

	measure 'AOCI Remain Balance BV - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance BV - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance BV - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: f56f8f89-5d7e-4139-89d0-3ee41ddf0ec3

	measure 'AOCI Remain Balance BV - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance BV - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance BV - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 236b7832-a7d1-4a3a-bb15-049fef173ec4

	measure 'AOCI Remain Balance BV - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance BV - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance BV - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: a807e846-ccbe-43d0-bf52-2556449a290f

	measure 'AOCI Remain Balance Non BV - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance Non BV - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance Non BV - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 964226e1-48dd-4cb0-af47-95187e1c7f73

	measure 'AOCI Remain Balance Non BV - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance Non BV - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance Non BV - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 7b4f13dd-4218-49fa-b7c8-40b90c30be5a

	measure 'AOCI Remain Balance Non BV - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance Non BV - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance Non BV - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 8d1d336c-7887-43a5-9f3d-54d2efd998e9

	measure 'AOCI Remain Balance Non BV - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance Non BV - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance Non BV - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 1f359246-25ac-4d04-bc87-c9fa2f8c9f8a

	measure 'AOCI Remain Balance Rep - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance Rep - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance Rep - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 81af09d7-ced7-4118-9166-13963bd4f5d9

	measure 'AOCI Remain Balance Rep - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance Rep - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance Rep - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: e5aca497-7fa0-4618-95d3-2b36a7dcd4dc

	measure 'AOCI Remain Balance Rep - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance Rep - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance Rep - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 06fa8ccb-919a-4067-9e91-5fc818450049

	measure 'AOCI Remain Balance Rep - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[AOCI Remain Balance Rep - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[AOCI Remain Balance Rep - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 7464c490-9104-4bfd-bfc9-e5f88961f360

	measure 'Balance CL Allowance - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: c1a93849-1c50-4f48-afff-d7496b660472

	measure 'Balance CL Allowance - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 56bd4085-6e75-4709-812c-78d85e0f0d22

	measure 'Balance CL Allowance - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: bd9e0df2-3d49-4150-a514-69f1bc945b13

	measure 'Balance CL Allowance - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 622f658a-28ff-4e21-8296-59bac0143f22

	measure 'Balance Deferred PL - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Deferred PL - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Deferred PL - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 9c521113-6d62-4cc1-acb7-fa33127b9e75

	measure 'Balance Deferred PL - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Deferred PL - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Deferred PL - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 8ebb4fec-e662-450e-acbf-749c7eb57dd2

	measure 'Balance Deferred PL - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Deferred PL - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Deferred PL - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: fdaea5a9-14d7-44fe-ac6a-d08ae32bdb1c

	measure 'Balance Deferred PL - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Deferred PL - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Deferred PL - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 8e23be7b-ee67-4b0a-8711-bb3c17dbfc68

	measure 'Balance Impairment - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Impairment - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Impairment - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 4a20e9d9-9bbb-488c-a0d1-4262c8c98ecc

	measure 'Balance Impairment - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Impairment - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Impairment - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: a5361e8a-7496-486e-9a7e-39f7df977937

	measure 'Balance Impairment - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Impairment - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Impairment - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: bcf73e11-fb73-4642-b496-8f8e9335e89a

	measure 'Balance Impairment - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Impairment - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Impairment - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 0b525221-2236-49b4-963f-5aa9c745203c

	measure 'Balance Int Appr - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Int Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Int Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 2b8404b2-d5c5-4043-bf35-5ef2877ca737

	measure 'Balance Int Appr - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Int Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Int Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 71130261-32fa-4962-9d79-419dc9a44555

	measure 'Balance Int Appr - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Int Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Int Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 41fee0d4-cdb4-412c-ad9a-7da136c02771

	measure 'Balance Int Appr - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Int Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Int Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: d57a1953-ae3d-47fd-90b2-04d4bc5c02bd

	measure 'Balance OID Appr - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance OID Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance OID Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 251be881-f368-4de2-84af-697970491055

	measure 'Balance OID Appr - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance OID Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance OID Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 3143426c-b86f-48d5-a9c7-334bbc645f22

	measure 'Balance OID Appr - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance OID Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance OID Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 29a6c3a6-49ba-4eab-9bcb-a14c6394d35c

	measure 'Balance OID Appr - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance OID Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance OID Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 060b1d56-064f-4968-bf59-386533135ad8

	measure 'Balance Recog CL Allowance - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Recog CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Recog CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 7be2fab4-0bd1-4fba-bfa4-08cf3e398c48

	measure 'Balance Recog CL Allowance - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Recog CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Recog CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: adb97e88-3d8d-4273-9ce7-f23dad641325

	measure 'Balance Recog CL Allowance - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Recog CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Recog CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 0ca4d515-a0c6-4032-83a5-8f25a3fb26a8

	measure 'Balance Recog CL Allowance - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Balance Recog CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Balance Recog CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 9ce1f167-f4b0-4638-85fb-00f3138b5c7b

	measure 'Book Value - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Book Value - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Book Value - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: cbe908c7-8bf1-4b41-b160-27df4fe8d519

	measure 'Book Value - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Book Value - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Book Value - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 2758fe04-dcd2-4e45-b43f-40aa1accb254

	measure 'Book Value - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Book Value - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Book Value - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 0aea63d4-4842-4617-9ba5-4492b506aadb

	measure 'Book Value - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Book Value - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Book Value - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 3bfa11e1-203e-4832-b56f-6097265d228d

	measure 'Carrying Value - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Carrying Value - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Carrying Value - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: c323c390-1624-43e5-8cf3-5b8a7e3f9899

	measure 'Carrying Value - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Carrying Value - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Carrying Value - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 923fa3a1-c6e7-4b66-8281-d00099ddf12a

	measure 'Carrying Value - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Carrying Value - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Carrying Value - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 01680497-d111-4d41-bb9e-b100f1139113

	measure 'Carrying Value - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Carrying Value - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Carrying Value - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 85934db2-7185-476a-bbb9-6f37bc48dd63

	measure 'Fair Value Unaccrued - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Fair Value Unaccrued - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Fair Value Unaccrued - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: aeb84a41-063f-4f6b-9bd5-51cb4db5242a

	measure 'Fair Value Unaccrued - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Fair Value Unaccrued - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Fair Value Unaccrued - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 27d04c7b-a1a0-4eb0-856a-17d0d251073a

	measure 'Fair Value Unaccrued - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Fair Value Unaccrued - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Fair Value Unaccrued - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 553425e9-005f-4e03-86ed-50a8ff9d3d3c

	measure 'Fair Value Unaccrued - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Fair Value Unaccrued - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Fair Value Unaccrued - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 61370c3b-6744-42cb-91b4-18a70a22cc7a

	measure 'Original Cost - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Original Cost - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Original Cost - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: e915ec44-e5ee-48c8-8e20-78c1b0d4bea7

	measure 'Original Cost - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Original Cost - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Original Cost - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: fa09ccc2-4c63-4282-a4eb-d1f5882b1e9d

	measure 'Original Cost - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Original Cost - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Original Cost - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: a265ff28-566e-4085-9076-d28832a36909

	measure 'Original Cost - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Original Cost - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Original Cost - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 198cc1b8-b983-4d1c-ad83-ae712378a1eb

	measure 'Unrealized Gain/Loss - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Unrealized Gain/Loss - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Unrealized Gain/Loss - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 809be930-04fb-4b6f-9d08-f892fe584ce1

	measure 'Unrealized Gain/Loss - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Unrealized Gain/Loss - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Unrealized Gain/Loss - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 3be3f4d5-b8ef-4e9e-9e5b-431c349e2278

	measure 'Unrealized Gain/Loss - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Unrealized Gain/Loss - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Unrealized Gain/Loss - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 70350ab3-c083-4587-b0b0-2f7269801722

	measure 'Unrealized Gain/Loss - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Unrealized Gain/Loss - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Unrealized Gain/Loss - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 1e5f8d41-b774-4041-b8cd-ccc66543eb3d

	measure 'Unrealized Gain/Loss CCY - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Unrealized Gain/Loss CCY - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Unrealized Gain/Loss CCY - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: e89afd68-96c3-42ef-bd30-cc44da7f71e5

	measure 'Unrealized Gain/Loss CCY - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Unrealized Gain/Loss CCY - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Unrealized Gain/Loss CCY - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: da767333-35f9-4d22-ac37-2225cff8f046

	measure 'Unrealized Gain/Loss CCY - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Unrealized Gain/Loss CCY - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Unrealized Gain/Loss CCY - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 74b6657d-4b28-4a2c-a3fb-e7ff260559bf

	measure 'Unrealized Gain/Loss CCY - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Unrealized Gain/Loss CCY - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Unrealized Gain/Loss CCY - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: b7e219c7-51e7-4873-a6ed-05e348dea059

	measure 'Unrealized Gain/Loss Sec - CAD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Unrealized Gain/Loss Sec - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Unrealized Gain/Loss Sec - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 8f2bf31a-a865-4816-9d31-c59a7dff6849

	measure 'Unrealized Gain/Loss Sec - FUNC (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Unrealized Gain/Loss Sec - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Unrealized Gain/Loss Sec - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: f36512fd-ab60-4729-a82f-74fe1efeea89

	measure 'Unrealized Gain/Loss Sec - HKD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Unrealized Gain/Loss Sec - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Unrealized Gain/Loss Sec - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: ed290530-e2fb-4eb8-8e25-f4fadca79f9d

	measure 'Unrealized Gain/Loss Sec - USD (Sec Lots)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Lots Fact',
			        'Securities Lots Fact'[Unrealized Gain/Loss Sec - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[Unrealized Gain/Loss Sec - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 057a1e94-cf63-44f5-aabf-a9880644b154

	measure 'FV Final - Rep (Sec Lots)' = ```
			
			VAR vIFRS9Purpose = SUMMARIZE('Securities Lots Fact',Securities[Primary Security ID],'Securities Lots Fact'[IFRS9 Purpose])
			VAR vIFRS9Chk = ADDCOLUMNS(vIFRS9Purpose,"@IFRS9_Chk",IF('Securities Lots Fact'[IFRS9 Purpose] IN {"FVTPL","FVOCI"},1))
			VAR vIFRS9Max = ADDCOLUMNS(vIFRS9Chk,"@IFRS9_Max",CALCULATE(MAXX(vIFRS9Chk,[@IFRS9_Chk]),REMOVEFILTERS('Securities Lots Fact'[IFRS9 Purpose])))
			
			VAR vIAS39Purpose = SUMMARIZE('Securities Lots Fact',Securities[Primary Security ID],'Securities Lots Fact'[Purpose])
			VAR vIAS39Chk = ADDCOLUMNS(vIAS39Purpose,"@IAS39_Chk",IF('Securities Lots Fact'[Purpose] IN {"FVTPL","FVOCI","AFS"},1))
			VAR vIAS9Max = ADDCOLUMNS(vIAS39Chk,"@IAS39_Max",CALCULATE(MAXX(vIAS39Chk,[@IAS39_Chk]),REMOVEFILTERS('Securities Lots Fact'[Purpose])))
			
			VAR vResult =
			SWITCH(
			    SELECTEDVALUE (Framework[Framework]),    
			    "IFRS9",    
			    SUMX(
			        SUMMARIZE('Securities Lots Fact',[IFRS9 Purpose]),
			        IF([IFRS9 Purpose] IN {"FVTPL","FVOCI"},'Securities Lots Fact'[Carrying Value - Rep (Sec Lots)],[Fair Value Unaccrued - Rep (Sec Lots)]
			        )
			    )+SUMX(SUMMARIZE(vIFRS9Max,Securities[Primary Security ID],[@IFRS9_Max]),IF([@IFRS9_Max]=1,[Carrying Value - Adjustment Rep (Sec Lots)])),
			    "IAS39",
			    SUMX(
			        SUMMARIZE('Securities Lots Fact',[Purpose]),
			        IF([Purpose] IN {"FVTPL","FVOCI","AFS"},'Securities Lots Fact'[Carrying Value - Rep (Sec Lots)],[Fair Value Unaccrued - Rep (Sec Lots)]        
			        )
			    )+SUMX(SUMMARIZE(vIAS9Max,Securities[Primary Security ID],[@IAS39_Max]),IF([@IAS39_Max]=1,[Carrying Value - Adjustment Rep (Sec Lots)]))
			    ,[Fair Value Unaccrued - Rep (Sec Lots)]
			)
			
			RETURN vResult
			
			```
		lineageTag: 2e820803-171a-4ee1-86cd-b7b62de94c83

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FV Final - Local (Sec Lots)' = ```
			
			VAR vIFRS9Purpose = SUMMARIZE('Securities Lots Fact',Securities[Primary Security ID],'Securities Lots Fact'[IFRS9 Purpose])
			VAR vIFRS9Chk = ADDCOLUMNS(vIFRS9Purpose,"@IFRS9_Chk",IF('Securities Lots Fact'[IFRS9 Purpose] IN {"FVTPL","FVOCI"},1))
			VAR vIFRS9Max = ADDCOLUMNS(vIFRS9Chk,"@IFRS9_Max",CALCULATE(MAXX(vIFRS9Chk,[@IFRS9_Chk]),REMOVEFILTERS('Securities Lots Fact'[IFRS9 Purpose])))
			
			VAR vIAS39Purpose = SUMMARIZE('Securities Lots Fact',Securities[Primary Security ID],'Securities Lots Fact'[Purpose])
			VAR vIAS39Chk = ADDCOLUMNS(vIAS39Purpose,"@IAS39_Chk",IF('Securities Lots Fact'[Purpose] IN {"FVTPL","FVOCI","AFS"},1))
			VAR vIAS9Max = ADDCOLUMNS(vIAS39Chk,"@IAS39_Max",CALCULATE(MAXX(vIAS39Chk,[@IAS39_Chk]),REMOVEFILTERS('Securities Lots Fact'[Purpose])))
			
			VAR vResult =
			SWITCH(
			    SELECTEDVALUE (Framework[Framework]),    
			    "IFRS9",    
			    SUMX(
			        SUMMARIZE('Securities Lots Fact',[IFRS9 Purpose]),
			        IF([IFRS9 Purpose] IN {"FVTPL","FVOCI"},'Securities Lots Fact'[Carrying Value - Local (Sec Lots)],[Fair Value Unaccrued - Local (Sec Lots)]
			        )
			    )+SUMX(SUMMARIZE(vIFRS9Max,Securities[Primary Security ID],[@IFRS9_Max]),IF([@IFRS9_Max]=1,[Carrying Value - Adjustment Local (Sec Lots)])),
			    "IAS39",
			    SUMX(
			        SUMMARIZE('Securities Lots Fact',[Purpose]),
			        IF([Purpose] IN {"FVTPL","FVOCI","AFS"},'Securities Lots Fact'[Carrying Value - Local (Sec Lots)],[Fair Value Unaccrued - Local (Sec Lots)]        
			        )
			    )+SUMX(SUMMARIZE(vIAS9Max,Securities[Primary Security ID],[@IAS39_Max]),IF([@IAS39_Max]=1,[Carrying Value - Adjustment Local (Sec Lots)]))
			    ,[Fair Value Unaccrued - Local (Sec Lots)]
			)
			
			RETURN vResult
			
			```
		lineageTag: d71019b6-fe31-4bb3-beb2-e0e45f827684

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ultimate parent company (Sec Lots)' = ```
			
			    CALCULATE(
			        [Ultimate parent company (Entities)],
			        CROSSFILTER(Securities[Security NK],'Securities Lots Fact'[Security NK],BOTH)
			        )
			```
		lineageTag: 6388a796-b86b-4f17-a89c-6b2927df3729

	measure 'Ultimate parent LEI (Sec Lots)' = ```
			
			    CALCULATE(
			        [Ultimate parent LEI (Entities)],
			        CROSSFILTER(Securities[Security NK],'Securities Lots Fact'[Security NK],BOTH)
			        )
			```
		lineageTag: 9380d12e-39a2-4ba6-b997-a42d4f5bc108

	measure 'Ultimate parent location (Sec Lots)' = ```
			
			    CALCULATE(
			        [Ultimate parent location (Entities)],
			        CROSSFILTER(Securities[Security NK],'Securities Lots Fact'[Security NK],BOTH)
			        )
			```
		lineageTag: f109c69c-3e11-46ee-8c03-ad839eb9d53b

	measure 'Payment Method Name (Sec Lots)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Payment Method Name], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 0e961283-6dcf-4a7b-8020-0cd2ef10e6d1

	measure 'Calculated Unrealized Gain/Loss – Local' =
			
			[Fair Value Unaccrued - Local (Sec Lots)] -[Balance Book Value Native - Local (Sec Lots)]
		lineageTag: 17cf2ea9-11f5-4eb2-8966-d169d58f816c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Calculation Date Full (Sec Lots)' = MAX('Securities Lots Fact'[Calculation Date Full])
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		lineageTag: 62dc784c-c3a6-409c-9029-e81d8736e827

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Trading Philosophy Code - IAS39 (Sec Lots)' = ```
			
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] > MaxAsOfDate
			    )
			RETURN
			IF(COUNTROWS('Securities Lots Fact')>0,
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Lots Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    // TREATAS(BusEffFromTo,'Securities Transaction GA Fact'[Trade Date]),
			    BusEffFromTo,
			    KEEPFILTERS('Securities Lots Fact'[Framework Code] = "IAS39")
			))
			 
			```
		lineageTag: 21347e0f-a1b6-48c7-add3-fea9ae3295a7

	measure 'Trading Philosophy Code - IFRS (Sec Lots)' =
			
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] > MaxAsOfDate
			    )
			RETURN
			IF(COUNTROWS('Securities Lots Fact')>0,
			
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Lots Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    // TREATAS(BusEffFromTo,'Securities Transaction GA Fact'[Trade Date]),
			    BusEffFromTo,
			    KEEPFILTERS('Securities Lots Fact'[Framework Code] = "IFRS9")
			))
		lineageTag: 29d97300-f3c2-4dd7-9d2b-1bb3c9ea981c

	measure 'Trading Philosophy Code - JGAAP (Sec Lots)' = ```
			
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] > MaxAsOfDate
			    )
			RETURN
			IF(COUNTROWS('Securities Lots Fact')>0,
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Lots Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    // TREATAS(BusEffFromTo,'Securities Transaction GA Fact'[Trade Date]),
			    BusEffFromTo,
			    KEEPFILTERS('Securities Lots Fact'[Framework Code] = "JGAAP")
			))
			 
			```
		lineageTag: 2bb807ed-87aa-4ebf-a2f1-ce80ff2cb037

	measure 'Trading Philosophy Code - USGAAP (Sec Lots)' =
			
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] > MaxAsOfDate
			    )
			RETURN
			IF(COUNTROWS('Securities Lots Fact')>0,
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Lots Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    // TREATAS(BusEffFromTo,'Securities Transaction GA Fact'[Trade Date]),
			    BusEffFromTo,
			    KEEPFILTERS('Securities Lots Fact'[Framework Code] = "USGAAP")
			))
		isHidden
		lineageTag: ecab6ade-83f2-45af-adf4-6675d4e00148

		changedProperty = IsHidden

	measure 'Purpose Codes (Sec Lots) - TP' = ```
			
			 
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] >= MaxAsOfDate
			    )
			VAR TPvalue =
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Lots Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    BusEffFromTo
			    // KEEPFILTERS('Impairments Position Fact DQ'[Framework Code] = "IFRS9")
			)
			VAR FW =
			    SELECTEDVALUE ( Framework[Framework] )
			RETURN
			    CALCULATE (
			        IF (
			            FW = "IAS39",
			            TPvalue,
			            IF (
			                FW = "USGAAP",
			                TPvalue,
			                IF (
			                    FW = "JGAAP",
			                    TPvalue,
			                    IF (
			                        FW = "IFRS9",
			                       
			                        TPvalue,
			                        --(FW= "USTAX" || FW= "NAIC"),
			                        IF (
			                            NOT (
			                                ISEMPTY ( 'Securities Lots Fact' )
			                            ),
			                            "AFS"
			                        )
			                    )
			                )
			            )
			        ),
			        FILTER (
			            'Securities Lots Fact',
			            'Securities Lots Fact'[As Of Date]
			                = MAX ( 'Securities Lots Fact'[As Of Date] )
			        )
			    )
			```
		lineageTag: cd501c7c-0a0e-4663-b77d-a878bcf52e9b

	column 'Framework Code'
		dataType: string
		lineageTag: 0db595d2-9815-4274-b25b-c9631e78a3be
		summarizeBy: none
		sourceColumn: Framework Code

		annotation SummarizationSetBy = Automatic

	column 'Security NK'
		dataType: string
		lineageTag: c4e269e8-d35c-4a76-ae34-b3f4bf21077d
		summarizeBy: none
		sourceColumn: Security NK

		annotation SummarizationSetBy = Automatic

	column 'Portfolio NK'
		dataType: string
		lineageTag: 75c2375a-82c8-46bf-9755-49befaafe29b
		summarizeBy: none
		sourceColumn: Portfolio NK

		annotation SummarizationSetBy = Automatic

	column 'As Of Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 87f3cd9a-5589-4903-bad2-d09ea3d4b9ad
		summarizeBy: none
		sourceColumn: As Of Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'As Of Period'
		dataType: int64
		formatString: 0
		lineageTag: 9b5d1cc3-e2fb-47f3-a008-ba137c4e0bcb
		summarizeBy: sum
		sourceColumn: As Of Period

		annotation SummarizationSetBy = Automatic

	column 'Maturity Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: cfdde133-960e-41f2-990b-49efbd41841d
		summarizeBy: none
		sourceColumn: Maturity Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Sec Maturity Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d18f4943-5e1d-41be-9cc8-46dfa3bc3add
		summarizeBy: none
		sourceColumn: Sec Maturity Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Accounting Unit Code & Name'
		dataType: string
		lineageTag: 62889637-900f-4a50-a9c2-3abd4e1682de
		summarizeBy: none
		sourceColumn: Accounting Unit Code & Name

		annotation SummarizationSetBy = Automatic

	column 'Company Code & Name'
		dataType: string
		lineageTag: d747a85b-9c79-47b5-9862-47a3837c13fa
		summarizeBy: none
		sourceColumn: Company Code & Name

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Code & Name'
		dataType: string
		lineageTag: e17ae49a-96a3-4cee-ad98-a03efc42e825
		summarizeBy: none
		sourceColumn: Portfolio Code & Name

		annotation SummarizationSetBy = Automatic

	column 'GL Class'
		dataType: string
		lineageTag: e79f6f69-5711-469f-ab88-354cda63998b
		summarizeBy: none
		sourceColumn: GL Class

		annotation SummarizationSetBy = Automatic

	column Local
		dataType: string
		lineageTag: 90b678dc-2a38-4c16-9f19-7fd3118484ed
		summarizeBy: none
		sourceColumn: Local

		annotation SummarizationSetBy = Automatic

	column 'Src Positions ID'
		dataType: int64
		formatString: 0
		lineageTag: 8dfccec4-456b-453f-aa0d-9b84311dd4a8
		summarizeBy: count
		sourceColumn: Src Positions ID

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Src
		dataType: string
		lineageTag: d1b9c30e-4528-48ff-a525-490cc56e0393
		summarizeBy: none
		sourceColumn: Src

		annotation SummarizationSetBy = Automatic

	column 'Month End Status'
		dataType: string
		lineageTag: 862696b6-0892-42f1-911a-ac80f06977bd
		summarizeBy: none
		sourceColumn: Month End Status

		annotation SummarizationSetBy = Automatic

	column 'Int Trans Number Orig Trans'
		dataType: int64
		formatString: 0
		lineageTag: 3f9c258c-6498-44d7-b5d8-a8760ac09c0f
		summarizeBy: none
		sourceColumn: Int Trans Number Orig Trans

		annotation SummarizationSetBy = User

	column 'Base Currency Code'
		dataType: string
		lineageTag: 6ca66bbe-0c5e-4f5a-8048-3dae30d694c2
		summarizeBy: none
		sourceColumn: Base Currency Code

		annotation SummarizationSetBy = Automatic

	column 'Calculation Date Full'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		lineageTag: fbbdcd47-39e4-4b41-a972-84058acdb41d
		summarizeBy: none
		sourceColumn: Calculation Date Full

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Portfolio Group Objective'
		dataType: string
		lineageTag: df7d3ff4-b309-4c0c-afe8-acd972721930
		summarizeBy: none
		sourceColumn: Portfolio Group Objective

		annotation SummarizationSetBy = Automatic

	column 'Asset Portfolio Code'
		dataType: string
		lineageTag: 10dd404b-88d1-4760-8d2f-bd96f64038d2
		summarizeBy: none
		sourceColumn: Asset Portfolio Code

		annotation SummarizationSetBy = Automatic

	column 'Pool Factor'
		dataType: double
		lineageTag: fc5b6fef-4249-4dd4-9aaf-50d3d4861d0e
		summarizeBy: sum
		sourceColumn: Pool Factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Credit Impairment Stage'
		dataType: string
		lineageTag: 70edcac4-8995-4f06-80ae-d29140c2316d
		summarizeBy: none
		sourceColumn: Credit Impairment Stage

		annotation SummarizationSetBy = Automatic

	column 'Long Short Indicator'
		dataType: string
		lineageTag: e9f3ca87-4fbc-419f-a566-4fdf1c22f21e
		summarizeBy: none
		sourceColumn: Long Short Indicator

		annotation SummarizationSetBy = Automatic

	column 'Functional Ccy Code'
		dataType: string
		lineageTag: 12ad9a02-4e11-42c1-947d-25d2143b4f93
		summarizeBy: none
		sourceColumn: Functional Ccy Code

		annotation SummarizationSetBy = Automatic

	column 'Local To FUNC Rate'
		dataType: double
		lineageTag: 9bc6799a-8cdc-4c4b-8579-1bd0309eea7f
		summarizeBy: sum
		sourceColumn: Local To FUNC Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local To CAD Rate'
		dataType: double
		lineageTag: 21ae0fc7-2ec5-450c-9d1d-a5489f5891c9
		summarizeBy: sum
		sourceColumn: Local To CAD Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local To USD Rate'
		dataType: double
		lineageTag: 41449218-cdb5-470f-a5e1-504f7c9fc7a2
		summarizeBy: sum
		sourceColumn: Local To USD Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local To HKD Rate'
		dataType: double
		lineageTag: f90f70e7-99fd-4f31-95d1-f04eaa42d3e9
		summarizeBy: sum
		sourceColumn: Local To HKD Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Original Cost - Base'
		dataType: double
		lineageTag: fb134a1e-34ce-4167-a2fa-b234f2a0a4e9
		summarizeBy: sum
		sourceColumn: Original Cost - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Original Cost - Local'
		dataType: double
		lineageTag: 2bf2e70d-aca1-40da-b35b-3f0aebc279c8
		summarizeBy: sum
		sourceColumn: Original Cost - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Hedge Par'
		dataType: double
		lineageTag: eceaf9b9-c931-47e3-b66e-e2d35f020547
		summarizeBy: sum
		sourceColumn: AOCI Hedge Par

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Book Yield'
		dataType: double
		lineageTag: 9820dd70-546c-4e14-8420-aeca140bbfe2
		summarizeBy: sum
		sourceColumn: Book Yield

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Current Yield'
		dataType: double
		lineageTag: 5c18de5e-30f9-48fc-a4a7-15215c8dc9b9
		summarizeBy: sum
		sourceColumn: Current Yield

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Modified Duration'
		dataType: double
		lineageTag: 2b454354-e4be-4d6d-9d93-86cabefe931d
		summarizeBy: sum
		sourceColumn: Modified Duration

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Nominal
		dataType: double
		lineageTag: 7bf0158b-b0b8-4aa8-bd98-e1171ab8e47d
		summarizeBy: sum
		sourceColumn: Nominal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'BV / Unit - Base'
		dataType: double
		lineageTag: 223ac358-879e-420a-97aa-bb30e8b8b576
		summarizeBy: sum
		sourceColumn: BV / Unit - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'BV / Unit - Local'
		dataType: double
		lineageTag: 2db18183-be38-482f-8da4-4b774bb09e81
		summarizeBy: sum
		sourceColumn: BV / Unit - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost / Unit - Base'
		dataType: double
		lineageTag: bfaddd75-5b0c-4757-ad25-d2cb05be5fb8
		summarizeBy: sum
		sourceColumn: Cost / Unit - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cost / Unit - Local'
		dataType: double
		lineageTag: 6dc2681b-5385-414f-9732-5aad8b4063bb
		summarizeBy: sum
		sourceColumn: Cost / Unit - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local Exchange Rate'
		dataType: double
		formatString: 0.000000
		lineageTag: 771821f6-9a93-4ae5-81ee-47168640e5a4
		summarizeBy: sum
		sourceColumn: Local Exchange Rate

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column 'Lot ID'
		dataType: string
		lineageTag: 3790b2af-ea44-4248-96ad-7f1be1700466
		summarizeBy: none
		sourceColumn: Lot ID

		annotation SummarizationSetBy = Automatic

	column 'Issuer Name'
		dataType: string
		lineageTag: 7cb42afb-ea25-4de3-9c93-a2ce784fa219
		summarizeBy: none
		sourceColumn: Issuer Name

		annotation SummarizationSetBy = Automatic

	column 'Position Long Short Indicator'
		dataType: string
		lineageTag: 56541b83-f233-4720-8b4b-244aa76a0d3d
		summarizeBy: none
		sourceColumn: Position Long Short Indicator

		annotation SummarizationSetBy = Automatic

	column 'Match Index'
		dataType: int64
		formatString: 0
		lineageTag: 607b7e69-1738-405f-9588-fc57d9600f40
		summarizeBy: sum
		sourceColumn: Match Index

		annotation SummarizationSetBy = Automatic

	column 'Security Internal Rating'
		dataType: string
		lineageTag: 9c2107ba-637a-4483-972d-8b976c66297d
		summarizeBy: none
		sourceColumn: Security Internal Rating

		annotation SummarizationSetBy = Automatic

	column 'Original ML Rating'
		dataType: string
		lineageTag: 50dbf8b8-857f-4fb2-a871-d042eea721ae
		summarizeBy: none
		sourceColumn: Original ML Rating

		annotation SummarizationSetBy = Automatic

	column 'Private Place'
		dataType: string
		lineageTag: 46150a3f-c1da-4691-aa0c-acca969f1ea6
		summarizeBy: none
		sourceColumn: Private Place

		annotation SummarizationSetBy = Automatic

	column Coupon
		dataType: double
		lineageTag: e06c5dbc-3822-4015-8d2c-d1a0fe870581
		summarizeBy: none
		sourceColumn: Coupon

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Effective Matching Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d13160a6-76c0-4379-a324-0efeeaf298ad
		summarizeBy: none
		sourceColumn: Effective Matching Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Impaired Before'
		dataType: string
		lineageTag: 99e249f3-d551-43cf-997a-04e8b12d3b4b
		summarizeBy: none
		sourceColumn: Impaired Before

		annotation SummarizationSetBy = Automatic

	column 'First Loss Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 45d29154-d8b3-4df8-a500-0f8557e43639
		summarizeBy: none
		sourceColumn: First Loss Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Impaired Before Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: acd1bff0-c6c5-4c5a-9eea-8481ddbb13d5
		summarizeBy: none
		sourceColumn: Impaired Before Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Num of Days Impair'
		dataType: int64
		formatString: 0
		lineageTag: 483dc407-7085-4dcf-bf27-46b662648ff0
		summarizeBy: sum
		sourceColumn: Num of Days Impair

		annotation SummarizationSetBy = Automatic

	column 'Num of Days in Lost Position'
		dataType: int64
		formatString: 0
		lineageTag: 86a1ad01-7fd8-43e0-827c-4ac2edbb8f7e
		summarizeBy: sum
		sourceColumn: Num of Days in Lost Position

		annotation SummarizationSetBy = Automatic

	column 'Par Amount'
		dataType: double
		lineageTag: 261a2788-e47d-414e-8aa6-dc25ce3dbced
		summarizeBy: sum
		sourceColumn: Par Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fair Value Unaccrued - Local'
		dataType: double
		lineageTag: 1621db3b-d512-4c2a-9a99-4ac73a07ffe2
		summarizeBy: sum
		sourceColumn: Fair Value Unaccrued - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Security ID (Slicer -Sec Lots)' = RELATED('Securities'[SecurityID Slicer - Restated])
		lineageTag: cbb0385e-0139-4bf2-92fb-a9427a06459f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Asset Group (Sec Lots)' = RELATED('Securities'[Asset Group])
		lineageTag: 24eaccfa-13fb-4ab6-8eb3-f193222a8566
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Asset Class (Sec Lots)' = RELATED('Securities'[Asset Class])
		lineageTag: b8b4c00f-2f2c-49a3-91b9-dc787debb5c8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Asset Type (Sec Lots)' = RELATED('Securities'[Asset Type])
		lineageTag: 66d0e9ad-9f41-4f48-b7eb-87496ba41e81
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Transaction No'
		dataType: string
		lineageTag: 72ed34cf-fc21-469a-94af-097634349073
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Transaction No

		annotation SummarizationSetBy = Automatic

	column 'PenPar Trade Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 9fd1370b-57cf-46a4-81ca-fd6677900506
		summarizeBy: none
		sourceColumn: PenPar Trade Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Lot Trade Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 828dd730-5199-4ed5-9611-bf0524f3f76c
		summarizeBy: none
		sourceColumn: Lot Trade Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Secid = RELATED('Securities'[Security ID 2])
		lineageTag: 80b5f83f-6444-4453-8e0f-d93549befd23
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Public/Private Ind' = ```
			
			var secType = RELATED('Securities'[Asset Type])
			return Switch (True(),
			secType in {"PRV CNVPFD",
			"PRV PFD EQ",
			"PRV REIT",
			"Private Equity"}, "Private",
			NOT(secType  IN {"PRV CNVPFD",
			"PRV PFD EQ",
			"PRV REIT",
			"Private Equity"}), "Public", "All")
			
			```
		lineageTag: d20a1874-e968-428b-ad12-f69753f91375
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Process Flag' = "N"
		lineageTag: 1da6d61e-bdff-4fc8-a639-4ff59ecc03ff
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'SCD Impairment Tran Code' =
			
			IF(SELECTEDVALUE('Impairment Slicer'[Values])="Credit Recovery","ImpPartRevTaxLot","ImpStrtTaxLot")
		lineageTag: 2a5476e8-4e24-4b93-a6de-3f3378c192da
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '# of quarters in loss position' =
			
			SWITCH(
			TRUE(),
			'Securities Lots Fact'[Num of Days in Lost Position]<=91,"1",
			'Securities Lots Fact'[Num of Days in Lost Position]<=182,"2",
			'Securities Lots Fact'[Num of Days in Lost Position]<=273,"3",
			'Securities Lots Fact'[Num of Days in Lost Position]<=365,"4",
			'Securities Lots Fact'[Num of Days in Lost Position]<=456,"5",
			'Securities Lots Fact'[Num of Days in Lost Position]<=547,"6",
			'Securities Lots Fact'[Num of Days in Lost Position]<=638,"7",
			'Securities Lots Fact'[Num of Days in Lost Position]<=730,"8",
			'Securities Lots Fact'[Num of Days in Lost Position]<=821,"9",
			"10+")
		lineageTag: 720d2b26-1ea9-44f8-8b2d-8ead9f8eef1c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column '# of months in loss position' =
			
			SWITCH(TRUE(),
			'Securities Lots Fact'[Num of Days in Lost Position]<=91,"0 to 3 Months",
			'Securities Lots Fact'[Num of Days in Lost Position]<=182,"3 to 6 Months",
			'Securities Lots Fact'[Num of Days in Lost Position]<=273,"6 to 9 Months",
			'Securities Lots Fact'[Num of Days in Lost Position]<=365,"9 to 12 Months",
			'Securities Lots Fact'[Num of Days in Lost Position]<=730,"12 to 24 Months",
			"24 Months+"
			)
		lineageTag: 9d339d3f-a20b-4121-8a8d-aaa5f81168ae
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Original Drop %' =
			
			var calc =100 - ('Securities Lots Fact'[Fair Value Unaccrued - Local]/'Securities Lots Fact'[Original Cost - Local] )
			return
			if('Securities Lots Fact'[Original Cost - Local] = 0,BLANK(),calc)
		lineageTag: 456e31a7-826e-4248-b0b6-c8b53cf27f41
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Current Drop %' =
			
			var calc =100 - ('Securities Lots Fact'[Fair Value Unaccrued - Local]/'Securities Lots Fact'[Book Value - Base] )
			return
			if('Securities Lots Fact'[Book Value - Base] = 0,BLANK(),calc)
		lineageTag: 5c50a6fc-73f2-4414-b6a3-00c631d7a524
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Portfolio Code (Sec Lots)' = RELATED(Portfolios[Portfolio Code])
		lineageTag: 51973f56-5179-4ffb-a090-4803abc2b936
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID (Sec Lots)' = RELATED('Securities'[Primary Security ID])
		lineageTag: dbfd9fa6-d3b4-4dc6-8b9d-5b5caccf0787
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Ext Tax Lot No IK'
		dataType: int64
		formatString: 0
		lineageTag: d7973f29-e907-49fb-ad2c-168b9145316b
		summarizeBy: none
		sourceColumn: Ext Tax Lot No IK

		annotation SummarizationSetBy = User

	column 'Fair Value Unaccrued - Base'
		dataType: double
		lineageTag: cd58892b-5f22-4b67-83b4-38d0b981ebbe
		summarizeBy: sum
		sourceColumn: Fair Value Unaccrued - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Company Code' =
			
			var ac ='Securities Lots Fact'[Company Code & Name Display]
			var pos = IFERROR(SEARCH("-",ac),"")
			var calc = IFERROR(LEFT(ac,pos-2),"")
			return calc
		lineageTag: e5fab00d-74f5-4e95-ac05-0a598a16ed21
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Accounting Unit Code' =
			
			var ac ='Securities Lots Fact'[Accounting Unit Code & Name Display]
			var pos = IFERROR(SEARCH("-",ac),"")
			var calc = IFERROR(LEFT(ac,pos-2),"")
			return calc
		lineageTag: 27708652-5c31-4fda-ab71-f60f01bb44b5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID & Desc (Sec Lots)' = RELATED('Securities'[Primary Security ID & Desc])
		lineageTag: 58368eb3-1ed9-48ff-ab62-8ad937a5cd0b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 7729fac9-71e1-4b69-9433-c8ab22dfb4fd
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Src Security ID'
		dataType: string
		lineageTag: 1944fb26-96e0-40b1-b71d-6c450b369ce7
		summarizeBy: none
		sourceColumn: Src Security ID

		annotation SummarizationSetBy = Automatic

	column 'Src Market ID'
		dataType: string
		lineageTag: 59b2af30-cf6d-4d74-87a4-f101936072b7
		summarizeBy: none
		sourceColumn: Src Market ID

		annotation SummarizationSetBy = Automatic

	column 'Balance Int Appr - Base'
		dataType: double
		lineageTag: 32c6c193-3acd-48f4-b220-7818d1837f74
		summarizeBy: sum
		sourceColumn: Balance Int Appr - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Int Appr - Local'
		dataType: double
		lineageTag: 176b90f0-0e23-440f-8f86-13a36d6525bb
		summarizeBy: sum
		sourceColumn: Balance Int Appr - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance OID Appr - Base'
		dataType: double
		lineageTag: 2075f1ee-b7f9-4a80-bfac-83c2ec663018
		summarizeBy: sum
		sourceColumn: Balance OID Appr - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance OID Appr - Local'
		dataType: double
		lineageTag: 4adc2b7b-396f-43fa-8161-b3ae085dbc1b
		summarizeBy: sum
		sourceColumn: Balance OID Appr - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance CL Allowance - Base'
		dataType: double
		lineageTag: dfe6c72e-846e-48af-8352-ed569fe54bc6
		summarizeBy: sum
		sourceColumn: Balance CL Allowance - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance CL Allowance - Local'
		dataType: double
		lineageTag: 922e3cfb-f18c-41c6-93a1-cbe59592c7f6
		summarizeBy: sum
		sourceColumn: Balance CL Allowance - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Recog CL Allowance - Base'
		dataType: double
		lineageTag: b0df15df-1226-40f7-9c2c-0044551b109e
		summarizeBy: sum
		sourceColumn: Balance Recog CL Allowance - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Recog CL Allowance - Local'
		dataType: double
		lineageTag: 5b9c272b-79e9-4c36-90f0-78f3fd62cd97
		summarizeBy: sum
		sourceColumn: Balance Recog CL Allowance - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Impairment - Base'
		dataType: double
		lineageTag: 31f0fa61-f52d-476e-a931-7dfa50d143b7
		summarizeBy: sum
		sourceColumn: Balance Impairment - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Impairment - Local'
		dataType: double
		lineageTag: 818f75c6-e31e-41ba-8b3b-16a5eb55c83e
		summarizeBy: sum
		sourceColumn: Balance Impairment - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance CCY Impairment - Base'
		dataType: double
		lineageTag: 62894e63-61c1-4818-8f52-5fec64510dca
		summarizeBy: sum
		sourceColumn: Balance CCY Impairment - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Remain Balance BV - Base'
		dataType: double
		lineageTag: 5f672b4f-0157-4d7c-89de-a3950b0e9eb3
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance BV - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Remain Balance BV - Local'
		dataType: double
		lineageTag: fb36ba8b-c577-4dd3-a75f-8ddd75215d71
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance BV - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Deferred PL - Base'
		dataType: double
		lineageTag: 09ac15ab-78b6-4e67-a225-9af3c3a2d6b7
		summarizeBy: sum
		sourceColumn: Balance Deferred PL - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Deferred PL - Local'
		dataType: double
		lineageTag: 19aed490-a148-4ed4-b8a8-de491176edde
		summarizeBy: sum
		sourceColumn: Balance Deferred PL - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Carrying Value - Base'
		dataType: double
		lineageTag: 88727be3-28b0-4648-b0a3-d57b105f992b
		summarizeBy: sum
		sourceColumn: Carrying Value - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Carrying Value - Local'
		dataType: double
		lineageTag: 91a80564-0855-431f-9553-fb17bea22a1b
		summarizeBy: sum
		sourceColumn: Carrying Value - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Remain Balance Non BV - Base'
		dataType: double
		lineageTag: 078450e8-d86a-4372-ba42-e7fd788178f4
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance Non BV - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Remain Balance Non BV - Local'
		dataType: double
		lineageTag: 29475623-9503-4d2d-902f-55d46d54601a
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance Non BV - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Remain Balance Rep - Base'
		dataType: double
		lineageTag: e42e9ddd-39ce-4bd2-ab86-e6517113afd0
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance Rep - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Remain Balance Rep - Local'
		dataType: double
		lineageTag: f17df4cc-8e43-414a-87b3-dfa371cfa057
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance Rep - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Book Value - Base'
		dataType: double
		lineageTag: 8524a0b0-279e-46b4-a101-4333a02aa42b
		summarizeBy: sum
		sourceColumn: Book Value - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Book Value - Local'
		dataType: double
		lineageTag: bbb823be-75c0-4450-9fbe-87da20d1757a
		summarizeBy: sum
		sourceColumn: Book Value - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unrealized Gain/Loss Sec - Base'
		dataType: double
		lineageTag: da79c067-bf5f-468d-be4e-fd3feccee844
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss Sec - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unrealized Gain/Loss CCY - Base'
		dataType: double
		lineageTag: e2a3bb73-bb3b-4659-84c3-3a23c279a66e
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss CCY - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unrealized Gain/Loss - Base'
		dataType: double
		lineageTag: e5e4de47-826d-4574-9b7d-65faa1a44dc5
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unrealized Gain/Loss Sec - Local'
		dataType: double
		lineageTag: 286ecbda-e89b-4ee3-882e-bec673b5b755
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss Sec - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unrealized Gain/Loss CCY - Local'
		dataType: double
		lineageTag: 3afee84e-02db-4b9a-8eef-e73f071d5e3f
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss CCY - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unrealized Gain/Loss - Local'
		dataType: double
		lineageTag: a6f8588c-5624-4122-9da0-f89252ccc75c
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Created Ts'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		lineageTag: 12566b1d-5faa-4602-9ee0-d164f8df2913
		summarizeBy: none
		sourceColumn: Created Ts

		annotation SummarizationSetBy = Automatic

	column 'Updated Ts'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		lineageTag: 6ce959dd-b645-44f0-a3bb-24be2af7b2c1
		summarizeBy: none
		sourceColumn: Updated Ts

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Company Code & Name Display' =
			
			IF (
			    'Securities Lots Fact'[Company Code & Name]
			        IN { "Not Applicable - Not Applicable", "Not Available - Not Available" },
			    "9999 - Off Balance Sheet Company",
			    'Securities Lots Fact'[Company Code & Name]
			)
		lineageTag: b4431c67-c934-446d-a4a8-79c1b69ff509
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Accounting Unit Code & Name Display' =
			
			IF (
			    'Securities Lots Fact'[Accounting Unit Code & Name]
			        IN {"Not Applicable - Not Applicable", "Not Available - Not Available" },
			    "9999 - Off Balance Sheet Acct Unit",
			    'Securities Lots Fact'[Accounting Unit Code & Name]
			)
		lineageTag: 5e885ece-05db-429f-8171-ed67f57b3fcc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'SCD Security ID'
		dataType: string
		lineageTag: 7c8bf0be-574d-45d8-abfd-d438faaea4b6
		summarizeBy: none
		sourceColumn: SCD Security ID

		annotation SummarizationSetBy = Automatic

	column 'Month End Lots' = ```
			
			IF (
			    'Securities Lots Fact'[As Of Date]= EOMONTH ( 'Securities Lots Fact'[As Of Date], 0 ),
			    "Month End",
			    "Non Month End"
			)
			
			```
		lineageTag: cce15bec-5d3b-4ff4-8fba-2175c8e00195
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Balance Write Off - Local'
		dataType: double
		lineageTag: 3ae0e96f-372d-482b-82ac-f7855b2f0f91
		summarizeBy: sum
		sourceColumn: Balance Write Off - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Write Off - Base'
		dataType: double
		lineageTag: 4ac57930-069b-4734-a49a-00ba16835823
		summarizeBy: sum
		sourceColumn: Balance Write Off - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column component_no
		dataType: int64
		formatString: 0
		lineageTag: 50f3a8a5-c1ec-4b91-bb6d-0e4f37f39348
		summarizeBy: sum
		sourceColumn: component_no

		annotation SummarizationSetBy = Automatic

	column portfolio_calculation_ik
		dataType: int64
		formatString: 0
		lineageTag: b0b8fabc-6693-4284-89fa-f4b67b7afb8f
		summarizeBy: sum
		sourceColumn: portfolio_calculation_ik

		annotation SummarizationSetBy = Automatic

	column originating_system_no
		dataType: int64
		formatString: 0
		lineageTag: 58b037cb-05d0-419f-8a3d-6ea683eb10d5
		summarizeBy: sum
		sourceColumn: originating_system_no

		annotation SummarizationSetBy = Automatic

	column 'Adjusted Book Value Local'
		dataType: double
		lineageTag: d4b34c19-0f93-4c4d-9614-f2644ec9801c
		summarizeBy: sum
		sourceColumn: Adjusted Book Value Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adjusted Book Value Base'
		dataType: double
		lineageTag: 54266e1a-e33d-4875-b02d-b1f3fc519c6c
		summarizeBy: sum
		sourceColumn: Adjusted Book Value Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Issuer Long Comp Name (Sec Lots)' = RELATED(Securities[Issuer Long Comp Name])
		lineageTag: 88ca1f6f-2133-4dae-9c8e-90d109f65ef2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column GL_BUCKET
		dataType: string
		lineageTag: c5d7ffeb-3c1f-4037-ab5e-cd21ae887639
		summarizeBy: none
		sourceColumn: GL_BUCKET

		annotation SummarizationSetBy = Automatic

	column 'SCD Default Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: edbdd1e9-5fa9-4495-9feb-ac10459260c0
		summarizeBy: none
		sourceColumn: SCD Default Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Accrue In Default'
		dataType: string
		lineageTag: 9643d4e0-4ecf-474f-95df-584d55b03b81
		summarizeBy: none
		sourceColumn: Accrue In Default

		annotation SummarizationSetBy = Automatic

	column 'Trade Hedged Flag' = SWITCH(true(), 'Securities Lots Fact'[AOCI Hedge Par] = 0, "No",'Securities Lots Fact'[AOCI Hedge Par] = 'Securities Lots Fact'[Nominal], "Yes","Partially Hedged")
		isHidden
		lineageTag: 76733a13-1a04-4370-ad60-95453d6b1e2e
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Units
		dataType: double
		lineageTag: 42b9bdc7-acab-4f8a-a6c5-087b4d78755f
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Blue Book Code' = ```
			SWITCH(TRUE(), 
			
			RELATED(Securities[ML NAIC Report Part Cd]) = "BA" && 'Securities Lots Fact'[Primary Security ID (Sec Lots)] <> "40479@AA4" && 'Securities Lots Fact'[Primary Security ID (Sec Lots)] <> "40479*AA6" && 'Securities Lots Fact'[Primary Security ID (Sec Lots)] <> "40479*AB4", "BA",
			'Securities Lots Fact'[Primary Security ID (Sec Lots)] = "40479@AA4", "D1",
			'Securities Lots Fact'[Primary Security ID (Sec Lots)] = "40479*AA6", "D1",
			'Securities Lots Fact'[Primary Security ID (Sec Lots)] = "40479*AB4", "D1",
			
			//Exception List
			RELATED(Securities[SCD Security ID]) = "BBG000BBV9N3", "D1",
			RELATED(Securities[SCD Security ID]) = "BBG000PWXXY5", "D1",
			RELATED(Securities[SCD Security ID]) = "BBG000PWYVH7", "D1",
			RELATED(Securities[SCD Security ID]) = "BBG000PWZHX9", "D1",
			
			//Wash Sale Exceptions for the above securities
			
			RELATED(Securities[SCD Security ID]) = "WS1000259", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000393", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000624", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000625", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000627", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000648", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000651", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000652", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000653", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000656", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000657", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000691", "D1",
			
			RELATED(Securities[SCD Security ID]) = "50254692", "D2.2",
			RELATED(Securities[SCD Security ID]) = "50254693", "D2.2",
			RELATED(Securities[SCD Security ID]) = "50254212", "D2.2",
			RELATED(Securities[SCD Security ID]) = "50256903", "D2.2",
			RELATED(Securities[SCD Security ID]) = "BBG000006KY0", "D1",
			RELATED(Securities[SCD Security ID]) = "609990031", "BA",
			RELATED(Securities[SCD Security ID]) = "50185510", "BA",
			
			RELATED(Securities[SCD Security Type]) = "COVWARRANT", "D2.2",
			RELATED(Securities[SCD Security Type]) = "INV_IN_SUB", "D2.2",
			RELATED(Securities[SCD Security Type]) = "ADR", "D2.2",
			RELATED(Securities[SCD Security Type]) = "COMMON EQ", "D2.2",
			RELATED(Securities[SCD Security Type]) = "REIT", "D2.2",
			RELATED(Securities[SCD Security Type]) = "GDR", "D2.2",
			RELATED(Securities[SCD Security Type]) = "LP", "D2.2",
			RELATED(Securities[SCD Security Type]) = "RIGHT", "D2.2",
			RELATED(Securities[SCD Security Type]) = "ETF", "D2.2",
			RELATED(Securities[SCD Security Type]) = "OTH FUND", "D2.2",
			RELATED(Securities[SCD Security Type]) = "SEG FUND", "D2.2",
			RELATED(Securities[SCD Security Type]) = "WS_EQUITY", "D2.2",
			RELATED(Securities[SCD Security Type]) = "WS_PRDEBT", "D1",
			RELATED(Securities[SCD Security Type]) = "INC TRUST", "D2.2",
			RELATED(Securities[SCD Security Type]) = "REPO", "DA1",
			RELATED(Securities[SCD Security Type]) = "REV REPO", "DA1",
			RELATED(Securities[SCD Security Type]) = "RED PFD EQ", "D2.1",
			RELATED(Securities[SCD Security Type]) = "PRV WARRNT", "D2.2",
			RELATED(Securities[SCD Security Type]) = "PFD EQ", "D2.1",
			RELATED(Securities[SCD Security Type]) = "RMBS", "D1",
			RELATED(Securities[SCD Security Type]) = "LOAN CMO", "D1",
			RELATED(Securities[SCD Security Type]) = "LILO", "D1",
			RELATED(Securities[SCD Security Type]) = "CNV PFD EQ", "D2.1",
			RELATED(Securities[SCD Security Type]) = "ABS", "D1",
			RELATED(Securities[SCD Security Type]) = "CDO", "D1",
			RELATED(Securities[SCD Security Type]) = "CMBS", "D1",
			RELATED(Securities[SCD Security Type]) = "CMO", "D1",
			RELATED(Securities[SCD Security Type]) = "OIA BOND", "BA",
			RELATED(Securities[SCD Security Type]) = "OIA EA", "BA",
			RELATED(Securities[SCD Security Type]) = "OIA PFD", "BA",
			RELATED(Securities[SCD Security Type]) = "OIA STK", "BA",
			RELATED(Securities[SCD Security Type]) = "PRV REIT", "BA",
			RELATED(Securities[SCD Security Type]) = "FED AG BD", "D1",
			RELATED(Securities[SCD Security Type]) = "FED IDX BD", "D1",
			RELATED(Securities[SCD Security Type]) = "MUNI BD", "D1",
			RELATED(Securities[SCD Security Type]) = "PROV AG BD", "D1",
			RELATED(Securities[SCD Security Type]) = "WS_BOND", "D1",
			RELATED(Securities[SCD Security Type]) = "MUT FUND", "D2.2",
			RELATED(Securities[SCD Security Type]) = "PRV CNVPFD", "D2.1",
			RELATED(Securities[SCD Security Type]) = "PRV PFD EQ", "D2.1",
			RELATED(Securities[SCD Security Type]) = "PRIV EQ", "D2.2",
			
			RELATED(Securities[SCD Security Type]) = "LET CREDIT", "D1",
			RELATED(Securities[SCD Security Type]) = "LIN CREDIT", "D1",
			RELATED(Securities[SCD Security Type]) = "LOAN_LOC", "D1",
			
			RELATED(Securities[SCD Security Type]) = "PRV RED PF", "D2.1",
			RELATED(Securities[SCD Security Type]) = "WS_PRRDPFS", "D2.1",
			
			RELATED(Securities[SCD Security Type]) = "WS_PRPFEQT", "D2.1",
			RELATED(Securities[SCD Security Type]) = "WS_PREQT", "D2.2",
			RELATED(Securities[SCD Security Type]) = "WS_RDPFST", "D2.2",
			RELATED(Securities[SCD Security Type]) = "CRP IDX BD", "D1",
			
			RELATED(Securities[SCD Security Type]) = "CONV BD", "D2.2",
			RELATED(Securities[SCD Security Type]) = "WS_CONVBD", "D1",
			RELATED(Securities[SCD Security Type]) = "FED AG MBS", "D1",
			
			--STFIXINC & CEFIXINC
			RELATED(Securities[SCD Security Type]) = "CORP BD" && 'Securities Lots Fact'[GL_BUCKET] = "CCE", "E2",
			RELATED(Securities[SCD Security Type]) = "CORP BD" && 'Securities Lots Fact'[GL_BUCKET] = "ST", "DA1",
			RELATED(Securities[SCD Security Type]) = "CORP BD" && 'Securities Lots Fact'[GL_BUCKET] = BLANK(), "D1",
			RELATED(Securities[SCD Security Type]) = "CORP BD" && 'Securities Lots Fact'[GL_BUCKET] = "LT", "D1", 
			RELATED(Securities[SCD Security Type]) = "CORP BD" && 'Securities Lots Fact'[GL_BUCKET] = "NONE", "D1", 
			RELATED(Securities[SCD Security Type]) = "FED BD" && 'Securities Lots Fact'[GL_BUCKET] = "CCE", "E2",
			RELATED(Securities[SCD Security Type]) = "FED BD" && 'Securities Lots Fact'[GL_BUCKET] = "ST", "DA1",
			RELATED(Securities[SCD Security Type]) = "FED BD" && 'Securities Lots Fact'[GL_BUCKET] = BLANK(), "D1",
			RELATED(Securities[SCD Security Type]) = "FED BD" && 'Securities Lots Fact'[GL_BUCKET] = "LT", "D1",
			RELATED(Securities[SCD Security Type]) = "FED BD" && 'Securities Lots Fact'[GL_BUCKET] = "NONE", "D1",
			RELATED(Securities[SCD Security Type]) = "PROV BD" && 'Securities Lots Fact'[GL_BUCKET] = "ST", "DA1",
			RELATED(Securities[SCD Security Type]) = "PROV BD" && 'Securities Lots Fact'[GL_BUCKET] = BLANK(), "D1",
			RELATED(Securities[SCD Security Type]) = "PROV BD" && 'Securities Lots Fact'[GL_BUCKET] = "LT", "D1",
			RELATED(Securities[SCD Security Type]) = "PROV BD" && 'Securities Lots Fact'[GL_BUCKET] = "NONE", "D1",
			RELATED(Securities[SCD Security Type]) = "PROV BD" && 'Securities Lots Fact'[GL_BUCKET] = "CCE", "D1",
			
			--MM
			RELATED(Securities[SCD Security Type]) = "FED TBILL" && 'Securities Lots Fact'[GL_BUCKET] = BLANK(), "DA1",
			RELATED(Securities[SCD Security Type]) = "FED TBILL" && 'Securities Lots Fact'[GL_BUCKET] = "ST", "DA1",
			RELATED(Securities[SCD Security Type]) = "FED TBILL" && 'Securities Lots Fact'[GL_BUCKET] = "CCE", "E2",
			RELATED(Securities[SCD Security Type]) = "FED TBILL" && 'Securities Lots Fact'[GL_BUCKET] = "NONE", "DA1",
			RELATED(Securities[SCD Security Type]) = "FED TBILL" && 'Securities Lots Fact'[GL_BUCKET] = "LT", "DA1",
			RELATED(Securities[SCD Security Type]) = "PROV TBILL" && 'Securities Lots Fact'[GL_BUCKET] = BLANK(), "DA1",
			RELATED(Securities[SCD Security Type]) = "PROV TBILL" && 'Securities Lots Fact'[GL_BUCKET] = "ST", "DA1",
			RELATED(Securities[SCD Security Type]) = "PROV TBILL" && 'Securities Lots Fact'[GL_BUCKET] = "CCE", "E2",
			RELATED(Securities[SCD Security Type]) = "PROV TBILL" && 'Securities Lots Fact'[GL_BUCKET] = "NONE", "DA1",
			RELATED(Securities[SCD Security Type]) = "PROV TBILL" && 'Securities Lots Fact'[GL_BUCKET] = "LT", "DA1",
			RELATED(Securities[SCD Security Type]) = "CP" && 'Securities Lots Fact'[GL_BUCKET] = BLANK(), "DA1",
			RELATED(Securities[SCD Security Type]) = "CP" && 'Securities Lots Fact'[GL_BUCKET] = "ST", "DA1",
			RELATED(Securities[SCD Security Type]) = "CP" && 'Securities Lots Fact'[GL_BUCKET] = "CCE", "E2",
			RELATED(Securities[SCD Security Type]) = "CP" && 'Securities Lots Fact'[GL_BUCKET] = "NONE", "DA1",
			RELATED(Securities[SCD Security Type]) = "CP" && 'Securities Lots Fact'[GL_BUCKET] = "LT", "DA1",
			RELATED(Securities[SCD Security Type]) = "DEPOSIT" && 'Securities Lots Fact'[GL_BUCKET] = BLANK(), "DA1",
			RELATED(Securities[SCD Security Type]) = "DEPOSIT" && 'Securities Lots Fact'[GL_BUCKET] = "ST", "DA1",
			RELATED(Securities[SCD Security Type]) = "DEPOSIT" && 'Securities Lots Fact'[GL_BUCKET] = "CCE", "E2",
			RELATED(Securities[SCD Security Type]) = "DEPOSIT" && 'Securities Lots Fact'[GL_BUCKET] = "NONE", "DA1",
			RELATED(Securities[SCD Security Type]) = "DEPOSIT" && 'Securities Lots Fact'[GL_BUCKET] = "LT", "DA1",
			RELATED(Securities[SCD Security Type]) = "CD" && 'Securities Lots Fact'[GL_BUCKET] = BLANK(), "DA1",
			RELATED(Securities[SCD Security Type]) = "CD" && 'Securities Lots Fact'[GL_BUCKET] = "ST", "DA1",
			RELATED(Securities[SCD Security Type]) = "CD" && 'Securities Lots Fact'[GL_BUCKET] = "NONE", "DA1",
			RELATED(Securities[SCD Security Type]) = "CD" && 'Securities Lots Fact'[GL_BUCKET] = "LT", "DA1",
			RELATED(Securities[SCD Security Type]) = "CD" && 'Securities Lots Fact'[GL_BUCKET] = "CCE", "E2",
			
			--LOANBOND
			RELATED(Securities[SCD Security Type]) = "PRV CORPBD" && 'Securities Lots Fact'[GL_BUCKET] = BLANK() && 'Securities Lots Fact'[Primary Security ID (Sec Lots)] <> "50221#AA2", "D1",
			RELATED(Securities[SCD Security Type]) = "PRV CORPBD" && 'Securities Lots Fact'[GL_BUCKET] = "LT" && 'Securities Lots Fact'[Primary Security ID (Sec Lots)] <> "50221#AA2", "D1",
			RELATED(Securities[SCD Security Type]) = "PRV CORPBD" && 'Securities Lots Fact'[GL_BUCKET] = "NONE" && 'Securities Lots Fact'[Primary Security ID (Sec Lots)] <> "50221#AA2", "D1",
			RELATED(Securities[SCD Security Type]) = "PRV CORPBD" && 'Securities Lots Fact'[GL_BUCKET] = "CCE" && 'Securities Lots Fact'[Primary Security ID (Sec Lots)] <> "50221#AA2", "D1",
			RELATED(Securities[SCD Security Type]) = "PRV CORPBD" && 'Securities Lots Fact'[GL_BUCKET] = "ST" && 'Securities Lots Fact'[Primary Security ID (Sec Lots)] <> "50221#AA2", "DA1",
			'Securities Lots Fact'[Primary Security ID (Sec Lots)] = "50221#AA2", "B",
			RELATED(Securities[SCD Security Type]) = "REVOLVER" && 'Securities Lots Fact'[GL_BUCKET] = BLANK(), "D1",
			RELATED(Securities[SCD Security Type]) = "REVOLVER" && 'Securities Lots Fact'[GL_BUCKET] = "LT", "D1",
			RELATED(Securities[SCD Security Type]) = "REVOLVER" && 'Securities Lots Fact'[GL_BUCKET] = "NONE", "D1",
			RELATED(Securities[SCD Security Type]) = "REVOLVER" && 'Securities Lots Fact'[GL_BUCKET] = "CCE", "D1",
			RELATED(Securities[SCD Security Type]) = "REVOLVER" && 'Securities Lots Fact'[GL_BUCKET] = "ST", "DA1",
			RELATED(Securities[SCD Security Type]) = "TERM LOAN" && 'Securities Lots Fact'[GL_BUCKET] = BLANK(), "D1",
			RELATED(Securities[SCD Security Type]) = "TERM LOAN" && 'Securities Lots Fact'[GL_BUCKET] = "LT", "D1",
			RELATED(Securities[SCD Security Type]) = "TERM LOAN" && 'Securities Lots Fact'[GL_BUCKET] = "NONE", "D1",
			RELATED(Securities[SCD Security Type]) = "TERM LOAN" && 'Securities Lots Fact'[GL_BUCKET] = "CCE", "D1",
			RELATED(Securities[SCD Security Type]) = "TERM LOAN" && 'Securities Lots Fact'[GL_BUCKET] = "ST", "DA1",
			RELATED(Securities[SCD Security Type]) = "PRV CONVBD" && 'Securities Lots Fact'[GL_BUCKET] = BLANK(), "D1",
			RELATED(Securities[SCD Security Type]) = "PRV CONVBD" && 'Securities Lots Fact'[GL_BUCKET] = "LT", "D1",
			RELATED(Securities[SCD Security Type]) = "PRV CONVBD" && 'Securities Lots Fact'[GL_BUCKET] = "NONE", "D1",
			RELATED(Securities[SCD Security Type]) = "PRV CONVBD" && 'Securities Lots Fact'[GL_BUCKET] = "CCE", "D1",
			RELATED(Securities[SCD Security Type]) = "PRV CONVBD" && 'Securities Lots Fact'[GL_BUCKET] = "ST", "DA1",
			RELATED(Securities[SCD Security Type]) = "PRIV DEBT" && 'Securities Lots Fact'[GL_BUCKET] = BLANK(), "D1",
			RELATED(Securities[SCD Security Type]) = "PRIV DEBT" && 'Securities Lots Fact'[GL_BUCKET] = "LT", "D1",
			RELATED(Securities[SCD Security Type]) = "PRIV DEBT" && 'Securities Lots Fact'[GL_BUCKET] = "NONE", "D1",
			RELATED(Securities[SCD Security Type]) = "PRIV DEBT" && 'Securities Lots Fact'[GL_BUCKET] = "CCE", "D1",
			RELATED(Securities[SCD Security Type]) = "PRIV DEBT" && 'Securities Lots Fact'[GL_BUCKET] = "ST", "DA1",
			
			//New additional condition after prod testing by Kevin on 7/6 : Start
			//RELATED(Securities[SCD Security Type]) = "CP" && 'Securities Lots Fact'[GL_BUCKET] = "CCE" && RELATED(Securities[ML NAIC Report Part Cd]) = "1" , "E2",
			
			--RELATED(Securities[SCD Security Type]) = "PRV CONVBD" && 'Securities Lots Fact'[GL_BUCKET] = "LT" && RELATED(Securities[ML NAIC Report Part Cd]) = BLANK() , "D1",
			--RELATED(Securities[SCD Security Type]) = "PRV CONVBD" && 'Securities Lots Fact'[GL_BUCKET] = "NONE" && RELATED(Securities[ML NAIC Report Part Cd]) = BLANK() , "D1",
			
			RELATED(Securities[SCD Security Type]) = "PRIVSTK", "D2.2",
			//New additional condition after prod testing by Kevin on 7/6 : End
			BLANK())
			```
		lineageTag: 5cd91482-8f4c-4184-9ce7-1059cd4b208f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Unreal Real Int Appr Disc Local CCY'
		dataType: double
		lineageTag: 33886adb-c2dd-492d-9dd9-73ef9cea4942
		summarizeBy: sum
		sourceColumn: Unreal Real Int Appr Disc Local CCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unreal Real Int Appr Prem Local CCY'
		dataType: double
		lineageTag: 1c8ed1dc-3ead-4d6a-b34c-17d11078a225
		summarizeBy: sum
		sourceColumn: Unreal Real Int Appr Prem Local CCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unreal Oid Accretion Local CCY'
		dataType: double
		lineageTag: 3d6f2869-14cd-4ef8-872d-5c0a949ba1a1
		summarizeBy: sum
		sourceColumn: Unreal Oid Accretion Local CCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Bal Interest Appreciation Local CCY'
		dataType: double
		lineageTag: 05c83aed-d39d-46cc-9080-6559d10b915f
		summarizeBy: sum
		sourceColumn: Bal Interest Appreciation Local CCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Amortised Cost Sec Base CCY'
		dataType: double
		lineageTag: db778945-cee0-478a-928d-a1781c9876e5
		summarizeBy: sum
		sourceColumn: Balance Amortised Cost Sec Base CCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Amortised Cost Local CCY'
		dataType: double
		lineageTag: 1b006768-aa05-4ae6-b9a2-6d66e3f05b99
		summarizeBy: sum
		sourceColumn: Balance Amortised Cost Local CCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Amortised Cost CCY Base CCY'
		dataType: double
		lineageTag: 0117dfd7-0896-413c-a0ba-a51a686a82d7
		summarizeBy: sum
		sourceColumn: Balance Amortised Cost CCY Base CCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'De Minimis Rule Id'
		dataType: string
		lineageTag: 5d1e7e1e-148e-402f-ab13-8201559380c0
		summarizeBy: none
		sourceColumn: De Minimis Rule Id

		annotation SummarizationSetBy = Automatic

	column 'Oid De Minimis Rule Id'
		dataType: string
		lineageTag: fb586e9c-82a0-4262-b8ca-387041219d25
		summarizeBy: none
		sourceColumn: Oid De Minimis Rule Id

		annotation SummarizationSetBy = Automatic

	column 'Initial SVO Rating'
		dataType: string
		lineageTag: 5e0db5fc-2bed-41c9-9769-bb04ae7486f3
		summarizeBy: none
		sourceColumn: Initial SVO Rating

		annotation SummarizationSetBy = Automatic

	column 'IFRS9 Purpose'
		dataType: string
		lineageTag: 1a45e6bc-f12c-4018-8e63-1b0a0d31f611
		summarizeBy: none
		sourceColumn: IFRS9 Purpose

		annotation SummarizationSetBy = Automatic

	column 'Balance Book Value Local Native'
		dataType: double
		lineageTag: d75839df-f505-43f1-ba11-37be257b8824
		summarizeBy: sum
		sourceColumn: Balance Book Value Local Native

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Book Value Base Native'
		dataType: double
		lineageTag: 137a06c3-c999-4534-9679-ac49ae61d4ed
		summarizeBy: sum
		sourceColumn: Balance Book Value Base Native

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'FV / Unit - Local'
		dataType: double
		lineageTag: 5e8ba50e-0de7-467a-8a4d-e9ba6cf2eb58
		summarizeBy: sum
		sourceColumn: FV / Unit - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'FV / Unit - Base'
		dataType: double
		lineageTag: 3ea05d71-92f9-4603-bb1a-c5b85da4fa14
		summarizeBy: sum
		sourceColumn: FV / Unit - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Purpose
		dataType: string
		lineageTag: 6d593e29-fe72-4254-bc3a-87f427ca1d57
		summarizeBy: none
		sourceColumn: Purpose

		annotation SummarizationSetBy = Automatic

	column 'Yield For Math Adj'
		dataType: double
		lineageTag: 1290b31d-2de0-402d-9e86-a4ac701fea73
		summarizeBy: sum
		sourceColumn: Yield For Math Adj

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price - Local (D)'
		dataType: double
		lineageTag: 3c33491e-d65e-483c-80b7-b00c60223c84
		summarizeBy: sum
		sourceColumn: Price - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Initial Trans Type'
		dataType: string
		lineageTag: 95808f71-9690-4a6a-9d08-c4744d7f9ecd
		summarizeBy: none
		sourceColumn: Initial Trans Type

		annotation SummarizationSetBy = Automatic

	column 'FX Join Key'
		dataType: string
		lineageTag: 5b7b5622-ae2e-438b-a691-372f680a791d
		summarizeBy: none
		sourceColumn: FX Join Key

		annotation SummarizationSetBy = Automatic

	column 'Unique Lot ID'
		dataType: string
		lineageTag: d78f8f27-9771-4830-8c11-7e832a85ceab
		summarizeBy: none
		sourceColumn: Unique Lot ID

		annotation SummarizationSetBy = Automatic

	column 'Balance NAIC Carrying Value Local'
		dataType: double
		lineageTag: 291f3aa2-bcbe-499d-ac83-6afbb6122282
		summarizeBy: sum
		sourceColumn: Balance NAIC Carrying Value Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance NAIC Carrying Value Base'
		dataType: double
		lineageTag: 712920b9-f769-46ae-a544-58f548468d67
		summarizeBy: sum
		sourceColumn: Balance NAIC Carrying Value Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance NAIC Sec Adj Local'
		dataType: double
		lineageTag: c8b0f893-303d-4a36-bb00-50ff24ab741d
		summarizeBy: sum
		sourceColumn: Balance NAIC Sec Adj Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance NAIC Sec Adj Base'
		dataType: double
		lineageTag: a90656de-3837-4e5f-8480-3b5760d4a2b0
		summarizeBy: sum
		sourceColumn: Balance NAIC Sec Adj Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Average Cost Yield'
		dataType: double
		lineageTag: 1f505f1e-f983-4808-b7bf-683f4af7212a
		summarizeBy: sum
		sourceColumn: Average Cost Yield

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		type: calculated
		lineageTag: 33e8785b-aa0e-494a-b30e-9d60505cdac6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":"CALCULATE(MAXX('Securities Lots Fact', 'Securities Lots Fact'[Calculation Date Full - Copy]))"}

		annotation 277cc1b9-af89-4597-8e15-cacc25c0886b = ```
				Memory error: Memory Allocation failure . Try simplifying or reducing the number of queries.
				
				```

	partition 'Securities Lots Fact-5d128545-5d10-4bd5-a0f4-4c3dfc375498' = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs(HostName, HTTPPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null,CommandTimeout= #duration(0,5,0,0), EnableQueryResultDownload="0"]),
				    hive_metastore_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    inv_semantic_ga_Schema = hive_metastore_Database{[Name="inv_semantic_ga",Kind="Schema"]}[Data],
				    EDL_securities_lots_fact_dq = inv_semantic_ga_Schema{[Name="securities_lots_fact_dq",Kind="Table"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(EDL_securities_lots_fact_dq,{"FRAMEWORK_CD", "SECURITY_NK", "PORTFOLIO_NK", "EFFECTIVE_DATE", "REGION", "AS_OF_PERIOD", "MATURITY_DATE", "PENPAR_TRADE_DATE", "LOT_TRADE_DATE", "SEC_MATURITY_DATE", "ACCOUNTING_UNIT_CODE_NAME", "COMPANY_CODE_NAME", "PORTFOLIO_CODE_NM", "GL_CLASS", "LOCAL_CURRENCY_CODE", "LOT_ID", "TRANSACTION_NO", "EXT_TAX_LOT_NO_IK", "SRC_SECURITY_ID", "SCD_SECURITY_ID", "SRC_POSITIONS_ID", "SRC", "SRC_MARKET_ID", "MONTH_END_STATUS", "INT_TRANS_NUMBER_ORIG_TRANS", "BASE_CURRENCY_CODE", "CALCULATION_DATE_FULL", "PORTFOLIO_GROUP_OBJECTIVE", "ASSET_PORTFOLIO_CODE", "POOL_FACTOR", "CREDIT_IMPAIRMENT_STAGE", "LONG_SHORT_INDICATOR", "ISSUER_NAME", "POSITION_LONG_SHORT_INDICATOR", "MATCH_INDEX", "SECURITY_INTERNAL_RATING", "ORIG_ML_RATING", "PRVT_PLACE", "COUPON", "EFFECTIVE_MATCHING_DATE", "IMPAIRED_BEFORE", "FIRST_LOST_DATE", "IMPAIRED_BEFORE_DATE", "NUM_OF_DAYS_IMPAIR", "NUM_OF_DAYS_IN_LOST_POSITION", "FUNCTIONAL_CCY_CD", "LOCAL_EXCHANGE_RATE", "LOCAL_TO_FUNC_RATE", "LOCAL_TO_CAD_RATE", "LOCAL_TO_USD_RATE", "LOCAL_TO_HKD_RATE", "ORIGINAL_COST_BASE", "ORIGINAL_COST_LOCAL", "BAL_INTEREST_APPRECIATION_CCY_BASE", "BAL_INTEREST_APPRECIATION_CCY_LOCAL", "BALANCE_OID_APPR_CCY_BASE", "BALANCE_OID_APPR_CCY_LOCAL", "BALANCE_CL_ALLOWANCE_CCY_BASE", "BALANCE_CL_ALLOWANCE_CCY_LOCAL", "BALANCE_RECOG_CL_ALLOWANCE_CCY_BASE", "BALANCE_RECOG_CL_ALLOWANCE_CCY_LOCAL", "BALANCE_IMPAIRMENT_CCY_BASE", "BALANCE_IMPAIRMENT_CCY_LOCAL", "BALANCE_CCY_IMPAIRMENT_CCY_BASE", "AOCI_REMAIN_BALANCE_BV_CCY_BASE", "AOCI_REMAIN_BALANCE_BV_CCY_LOCAL", "BALANCE_DEFERRED_PL_CCY_BASE", "BALANCE_DEFERRED_PL_CCY_LOCAL", "CARRYING_VALUE_CCY_BASE", "CARRYING_VALUE_CCY_LOCAL", "AOCI_HEDGE_PAR", "AOCI_REMAIN_BALANCE_NON_BV_CCY_BASE", "AOCI_REMAIN_BALANCE_NON_BV_CCY_LOCAL", "AOCI_REMAIN_BALANCE_REP_CCY_BASE", "AOCI_REMAIN_BALANCE_REP_CCY_LOCAL", "BOOK_YIELD", "CURRENT_YIELD", "MODIFIED_DURATION", "NOMINAL", "BV_PER_UNIT_BASE", "BV_PER_UNIT_LOCAL", "COST_PER_UNIT_BASE", "COST_PER_UNIT_LOCAL", "PAR_AMT", "MARKET_VALUE_LOCAL", "MARKET_VALUE_BASE", "BALANCE_BOOK_VALUE_CCY_BASE", "BALANCE_BOOK_VALUE_CCY_LOCAL", "UNREAL_PL_BOOK_SEC_CCY_BASE", "UNREAL_CCY_PL_BOOK_CCY_BASE", "UNREALIZED_GAIN_LOSS_BASE", "UNREAL_PL_BOOK_SEC_CCY_LOCAL", "UNREAL_CCY_PL_BOOK_CCY_LOCAL", "UNREALIZED_GAIN_LOSS_LOCAL", "BALANCE_WRITE_OFF_LOCAL_CCY", "BALANCE_WRITE_OFF_BASE_CCY", "CREATED_TS", "UPDATED_TS", "component_no", "portfolio_calculation_ik", "originating_system_no", "ADJUSTED_BOOK_VALUE_LOCAL", "ADJUSTED_BOOK_VALUE_BASE", "GL_BUCKET", "SCD_DEFAULT_DATE", "SCD_DEFAULT_DATE_FC", "UNITS", "PURPOSE", "UNREAL_REAL_INT_APPR_DISC_LOCAL_CCY", "UNREAL_REAL_INT_APPR_PREM_LOCAL_CCY", "BAL_INTEREST_APPRECIATION_LOCAL_CCY", "UNREAL_OID_ACCRETION_LOCAL_CCY", "INITIAL_SVO_RATING", "BALANCE_AMORTISED_COST_CCY_BASE_CCY", "BALANCE_AMORTISED_COST_SEC_BASE_CCY", "BALANCE_AMORTISED_COST_LOCAL_CCY", "DE_MINIMIS_RULE_IK", "OID_DE_MINIMIS_RULE_IK", "IFRS9PURPOSE", "BALANCE_BOOK_VALUE_LOCAL_CCY_NATIVE", "BALANCE_BOOK_VALUE_BASE_CCY_NATIVE", "MARKET_PER_UNIT_LOCAL", "MARKET_PER_UNIT_BASE", "YIELD_FOR_MATH_ADJ", "MARKET_PRICE_LOCAL", "INITIAL_TRANS_TYPE", "UNIQUE_SUBLOT_ID", "FX_JOIN_KEY", "BALANCE_NAIC_CARRYING_VALUE_LOCAL_CCY", "BALANCE_NAIC_CARRYING_VALUE_BASE_CCY", "BALANCE_NAIC_SEC_ADJ_LOCAL_CCY", "BALANCE_NAIC_SEC_ADJ_BASE_CCY", "average_cost_yield"}),
				    #"Load data from specific date"= Table.SelectRows(#"Removed Other Columns",each [EFFECTIVE_DATE] >= pCutOffDate),
				    #"Renamed Columns" = Table.RenameColumns(#"Load data from specific date",{{"FRAMEWORK_CD", "Framework Code"}, {"SECURITY_NK", "Security NK"}, {"PORTFOLIO_NK", "Portfolio NK"}, {"EFFECTIVE_DATE", "As Of Date"}, {"REGION", "Region"}, {"AS_OF_PERIOD", "As Of Period"}, {"MATURITY_DATE", "Maturity Date"}, {"PENPAR_TRADE_DATE", "PenPar Trade Date"}, {"LOT_TRADE_DATE", "Lot Trade Date"}, {"SEC_MATURITY_DATE", "Sec Maturity Date"}, {"ACCOUNTING_UNIT_CODE_NAME", "Accounting Unit Code & Name"}, {"COMPANY_CODE_NAME", "Company Code & Name"}, {"PORTFOLIO_CODE_NM", "Portfolio Code & Name"}, {"GL_CLASS", "GL Class"}, {"LOCAL_CURRENCY_CODE", "Local"}, {"LOT_ID", "Lot ID"}, {"TRANSACTION_NO", "Transaction No"}, {"EXT_TAX_LOT_NO_IK", "Ext Tax Lot No IK"}, {"SRC_SECURITY_ID", "Src Security ID"}, {"SRC_POSITIONS_ID", "Src Positions ID"}, {"SRC", "Src"}, {"SRC_MARKET_ID", "Src Market ID"}, {"MONTH_END_STATUS", "Month End Status"}, {"INT_TRANS_NUMBER_ORIG_TRANS", "Int Trans Number Orig Trans"}, {"BASE_CURRENCY_CODE", "Base Currency Code"}, {"CALCULATION_DATE_FULL", "Calculation Date Full"}, {"PORTFOLIO_GROUP_OBJECTIVE", "Portfolio Group Objective"}, {"ASSET_PORTFOLIO_CODE", "Asset Portfolio Code"}, {"POOL_FACTOR", "Pool Factor"}, {"CREDIT_IMPAIRMENT_STAGE", "Credit Impairment Stage"}, {"LONG_SHORT_INDICATOR", "Long Short Indicator"}, {"ISSUER_NAME", "Issuer Name"}, {"POSITION_LONG_SHORT_INDICATOR", "Position Long Short Indicator"}, {"MATCH_INDEX", "Match Index"}, {"SECURITY_INTERNAL_RATING", "Security Internal Rating"}, {"ORIG_ML_RATING", "Original ML Rating"}, {"PRVT_PLACE", "Private Place"}, {"COUPON", "Coupon"}, {"EFFECTIVE_MATCHING_DATE", "Effective Matching Date"}, {"IMPAIRED_BEFORE", "Impaired Before"}, {"FIRST_LOST_DATE", "First Loss Date"}, {"IMPAIRED_BEFORE_DATE", "Impaired Before Date"}, {"NUM_OF_DAYS_IMPAIR", "Num of Days Impair"}, {"NUM_OF_DAYS_IN_LOST_POSITION", "Num of Days in Lost Position"}, {"FUNCTIONAL_CCY_CD", "Functional Ccy Code"}, {"LOCAL_EXCHANGE_RATE", "Local Exchange Rate"}, {"LOCAL_TO_FUNC_RATE", "Local To FUNC Rate"}, {"LOCAL_TO_CAD_RATE", "Local To CAD Rate"}, {"LOCAL_TO_USD_RATE", "Local To USD Rate"}, {"LOCAL_TO_HKD_RATE", "Local To HKD Rate"}, {"ORIGINAL_COST_BASE", "Original Cost - Base"}, {"ORIGINAL_COST_LOCAL", "Original Cost - Local"}, {"BAL_INTEREST_APPRECIATION_CCY_BASE", "Balance Int Appr - Base"}, {"BAL_INTEREST_APPRECIATION_CCY_LOCAL", "Balance Int Appr - Local"}, {"BALANCE_OID_APPR_CCY_BASE", "Balance OID Appr - Base"}, {"BALANCE_OID_APPR_CCY_LOCAL", "Balance OID Appr - Local"}, {"BALANCE_CL_ALLOWANCE_CCY_BASE", "Balance CL Allowance - Base"}, {"BALANCE_CL_ALLOWANCE_CCY_LOCAL", "Balance CL Allowance - Local"}, {"BALANCE_RECOG_CL_ALLOWANCE_CCY_BASE", "Balance Recog CL Allowance - Base"}, {"BALANCE_RECOG_CL_ALLOWANCE_CCY_LOCAL", "Balance Recog CL Allowance - Local"}, {"BALANCE_IMPAIRMENT_CCY_BASE", "Balance Impairment - Base"}, {"BALANCE_IMPAIRMENT_CCY_LOCAL", "Balance Impairment - Local"}, {"BALANCE_CCY_IMPAIRMENT_CCY_BASE", "Balance CCY Impairment - Base"}, {"BALANCE_DEFERRED_PL_CCY_BASE", "Balance Deferred PL - Base"}, {"BALANCE_DEFERRED_PL_CCY_LOCAL", "Balance Deferred PL - Local"}, {"CARRYING_VALUE_CCY_BASE", "Carrying Value - Base"}, {"CARRYING_VALUE_CCY_LOCAL", "Carrying Value - Local"}, {"AOCI_HEDGE_PAR", "AOCI Hedge Par"}, {"BOOK_YIELD", "Book Yield"}, {"CURRENT_YIELD", "Current Yield"}, {"MODIFIED_DURATION", "Modified Duration"}, {"NOMINAL", "Nominal"}, {"BV_PER_UNIT_BASE", "BV / Unit - Base"}, {"BV_PER_UNIT_LOCAL", "BV / Unit - Local"}, {"COST_PER_UNIT_BASE", "Cost / Unit - Base"}, {"COST_PER_UNIT_LOCAL", "Cost / Unit - Local"}, {"PAR_AMT", "Par Amount"}, {"MARKET_VALUE_LOCAL", "Fair Value Unaccrued - Local"}, {"MARKET_VALUE_BASE", "Fair Value Unaccrued - Base"}, {"BALANCE_BOOK_VALUE_CCY_LOCAL", "Book Value - Local"}, {"BALANCE_BOOK_VALUE_CCY_BASE", "Book Value - Base"}, {"UNREAL_PL_BOOK_SEC_CCY_BASE", "Unrealized Gain/Loss Sec - Base"}, {"UNREAL_CCY_PL_BOOK_CCY_BASE", "Unrealized Gain/Loss CCY - Base"}, {"UNREALIZED_GAIN_LOSS_BASE", "Unrealized Gain/Loss - Base"}, {"UNREAL_PL_BOOK_SEC_CCY_LOCAL", "Unrealized Gain/Loss Sec - Local"}, {"UNREAL_CCY_PL_BOOK_CCY_LOCAL", "Unrealized Gain/Loss CCY - Local"}, {"UNREALIZED_GAIN_LOSS_LOCAL", "Unrealized Gain/Loss - Local"}, {"CREATED_TS", "Created Ts"}, {"UPDATED_TS", "Updated Ts"}, {"BALANCE_AMORTISED_COST_SEC_BASE_CCY", "Balance Amortised Cost Sec Base CCY"}, {"BALANCE_AMORTISED_COST_LOCAL_CCY", "Balance Amortised Cost Local CCY"}, {"BALANCE_AMORTISED_COST_CCY_BASE_CCY", "Balance Amortised Cost CCY Base CCY"},{"DE_MINIMIS_RULE_IK","De Minimis Rule Id"},{"OID_DE_MINIMIS_RULE_IK","Oid De Minimis Rule Id"},{"MARKET_PER_UNIT_LOCAL","FV / Unit - Local"},{"MARKET_PER_UNIT_BASE","FV / Unit - Base"},{"MARKET_PRICE_LOCAL","Price - Local (D)"},{"FX_JOIN_KEY","FX Join Key"},{"UNIQUE_SUBLOT_ID","Unique Lot ID"},{"SCD_SECURITY_ID", "SCD Security ID"},{"ADJUSTED_BOOK_VALUE_BASE", "Adjusted Book Value Base"}, {"ADJUSTED_BOOK_VALUE_LOCAL", "Adjusted Book Value Local"},{"SCD_DEFAULT_DATE", "SCD Default Date"}, {"SCD_DEFAULT_DATE_FC", "Accrue In Default"}, {"UNITS", "Units"}, {"UNREAL_REAL_INT_APPR_DISC_LOCAL_CCY", "Unreal Real Int Appr Disc Local CCY"}, {"UNREAL_REAL_INT_APPR_PREM_LOCAL_CCY", "Unreal Real Int Appr Prem Local CCY"}, {"UNREAL_OID_ACCRETION_LOCAL_CCY", "Unreal Oid Accretion Local CCY"}, {"BAL_INTEREST_APPRECIATION_LOCAL_CCY", "Bal Interest Appreciation Local CCY"},{"INITIAL_SVO_RATING", "Initial SVO Rating"}, {"IFRS9PURPOSE", "IFRS9 Purpose"}, {"PURPOSE", "Purpose"}, {"BALANCE_BOOK_VALUE_LOCAL_CCY_NATIVE", "Balance Book Value Local Native"}, {"BALANCE_BOOK_VALUE_BASE_CCY_NATIVE", "Balance Book Value Base Native"}, {"YIELD_FOR_MATH_ADJ", "Yield For Math Adj"}, {"INITIAL_TRANS_TYPE", "Initial Trans Type"}, {"BALANCE_NAIC_CARRYING_VALUE_LOCAL_CCY", "Balance NAIC Carrying Value Local"}, {"BALANCE_NAIC_CARRYING_VALUE_BASE_CCY", "Balance NAIC Carrying Value Base"}, {"BALANCE_NAIC_SEC_ADJ_LOCAL_CCY", "Balance NAIC Sec Adj Local"}, {"BALANCE_NAIC_SEC_ADJ_BASE_CCY", "Balance NAIC Sec Adj Base"},{"average_cost_yield","Average Cost Yield"},{"AOCI_REMAIN_BALANCE_BV_CCY_BASE", "AOCI Remain Balance BV - Base"}, {"AOCI_REMAIN_BALANCE_BV_CCY_LOCAL", "AOCI Remain Balance BV - Local"}, {"AOCI_REMAIN_BALANCE_NON_BV_CCY_BASE", "AOCI Remain Balance Non BV - Base"}, {"AOCI_REMAIN_BALANCE_NON_BV_CCY_LOCAL", "AOCI Remain Balance Non BV - Local"}, {"AOCI_REMAIN_BALANCE_REP_CCY_BASE", "AOCI Remain Balance Rep - Base"}, {"AOCI_REMAIN_BALANCE_REP_CCY_LOCAL", "AOCI Remain Balance Rep - Local"}, {"BALANCE_WRITE_OFF_LOCAL_CCY", "Balance Write Off - Local"}, {"BALANCE_WRITE_OFF_BASE_CCY", "Balance Write Off - Base"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Transaction No", type text},{"Lot ID", type text}}),
				    #"Filtered Rows - Incremental Refresh" = Table.SelectRows(#"Changed Type", each [As Of Date] >= Date.From(RangeStart) and [As Of Date] < Date.From(RangeEnd))
				in
				    #"Filtered Rows - Incremental Refresh"

	annotation PBI_ResultType = Table

	annotation PBI_IsMQueryFoldable = True

	annotation PBI_NavigationStepName = Navigation

