table 'Securities Position Fact'
	lineageTag: 3da8a732-fd5d-48f7-8975-8ac0112d39a7

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: month
		rollingWindowPeriods: 16
		incrementalGranularity: month
		incrementalPeriods: 16
		pollingExpression = Securities_Position_Fact_PBI_Config
		sourceExpression = ```
			let
			LastNDays= Text.From(#"Last N Days Position Data"),
			Sql = "SELECT
			  spos.`SECURITY_NK` AS `Security NK`,
			  spos.`SECURITY_PAYMENT_NK` AS `Security Payment NK`,
			  spos.`AS_OF_DT` AS `As Of Date`,
			  spos.`AS_OF_PERIOD` AS `As Of Period`,
			  spos.`REGION` AS `Region`,
			  CAST(spos.`SRC_POSITION_ID` AS INT) AS `Src Position ID`,
			  spos.`SRC_SECURITY_ID` AS `Src Security ID`,
			  spos.`SRC_MARKET_ID` AS `Src Market ID`,
			  spos.`SRC_SECURITY` AS `Src Security`,
			  spos.`ASSET_PORTFOLIO_CODE` AS `Asset Portfolio Code`,
			  spos.`PORTFOLIO_GROUP_CODE` AS `Portfolio Group Code`,
			  spos.`PORTFOLIO_CD` AS `Portfolio Code`,
			  spos.`PORTFOLIO_NK` AS `Portfolio Nk`,
			  spos.`FRAMEWORK_CD` AS `Framework Code`,
			  spos.`GL_CLASS` AS `GL Class`,
			  spos.`WASH_SALE_PARENT_SECURITY_ID` AS `Wash Sale Parent Security ID`,
			  spos.`PORTFOLIO_CODE_NAME` AS `Portfolio Code & Name`,
			  spos.`ACCOUNTING_UNIT_CODE_NAME` AS `Accounting Unit Code & Name`,
			  spos.`COMPANY_CODE_NAME` AS `Company Code & Name`,
			  spos.`SCD_SECURITY_ID` AS `SCD Security ID`,
			  spos.`LEG` AS `Leg`,
			  spos.`CALCULATED_DATE` AS `Calculated Date`,
			  spos.`UNITS` AS `Units (D)`,
			  spos.`CONTRACTS` AS `Contracts`,
			  spos.`SETTLE_TRADE_BALANCE` AS `Settle Trade Balance`,
			  spos.`ORIGINAL_FACE` AS `Original Face (D)`,
			  spos.`POOL_FACTOR` AS `Pool Factor`,
			  spos.`UNIT_BASIS` AS `Unit Basis`,
			  spos.`NOMINAL` AS `Nominal (D)`,
			  spos.`QUOTE_FACTOR` AS `Quote Factor`,
			  spos.`CURRENT_FACE` AS `Current Face (D)`,
			  spos.`ACCRUED_MARKET_VALUE_BASE` AS `Fair Value Accrued - Base`,
			  spos.`MARKET_VALUE_BASE` AS `Fair Value Unaccrued - Base`,
			  spos.`COST_BASE` AS `Original Cost - Base`,
			  spos.`PRICE_BASE` AS `Price - Base`,
			  spos.`UNIT_COST_BASE` AS `Unit Cost - Base`,
			  spos.`UNREALIZED_ON_CURRENCY_BASE` AS `Unrealized Gain/Loss CCY - Base`,
			  spos.`UNREALIZED_ON_INVESTMENT_BASE` AS `Unrealized Gain/Loss Sec - Base`,
			  spos.`UNREALIZED_BASE` AS `Unrealized Gain/Loss - Base`,
			  spos.`ACCRUAL_BASE` AS `Accrual - Base`,
			  spos.`WITHELD_AMOUNT_BASE` AS `Withheld - Base`,
			  spos.`WITHHOLDING_RATE` AS `Withholding Rate`,
			  spos.`LOCAL_EXCHANGE_RATE` AS `Local Exchange Rate`,
			  spos.`ACCRUED_MARKET_VALUE_LOCAL` AS `Fair Value Accrued - Local (D)`,
			  spos.`ACCOUNTING_STATUS` AS `Accounting Status`,
			  spos.`PORTFOLIO_CALCULATION` AS `Portfolio Calculation`,
			  spos.`MARKET_VALUE_LOCAL` AS `Fair Value Unaccrued - Local (D)`,
			  spos.`PRICE_LOCAL` AS `Price - Local (D)`,
			  spos.`COST_LOCAL` AS `Original Cost - Local (D)`,
			  spos.`UNIT_COST_LOCAL` AS `Unit Cost - Local (D)`,
			  spos.`UNREALIZED_ON_CURRENCY_LOCAL` AS `Unrealized Gain/Loss CCY - Local (D)`,
			  spos.`UNREALIZED_ON_INVESTMENT_LOCAL` AS `Unrealized Gain/Loss Sec - Local (D)`,
			  spos.`UNREALIZED_LOCAL` AS `Unrealized Gain/Loss - Local (D)`,
			  spos.`ACCRUAL_LOCAL` AS `Accrual - Local (D)`,
			  spos.`WITHELD_AMOUNT_LOCAL` AS `Withheld - Local (D)`,
			  spos.`AMORTIZED_COST_BASE` AS `Amortized Cost - Base`,
			  spos.`AMORTIZED_COST_LOCAL` AS `Amortized Cost - Local (D)`,
			  spos.`YIELD` AS `Yield`,
			  spos.`YIELD_TO_WORST` AS `Yield To Worst`,
			  spos.`UNDERLIER_SECURITY_NK` AS `Underlier Security Nk`,
			  spos.`LOCAL_CCY_CD` AS `Local`,
			  spos.`BASE` AS `Base`,
			  spos.`LOCAL_CURRENCY` AS `Local Currency`,
			  spos.`COUNTRY` AS `SCD Country`,
			  spos.`COUNTRY_NAME` AS `Country Name`,
			  spos.`MATURITY_DATE` AS `Maturity Date Final`,
			  spos.`COUPON` AS `SCD Coupon (D)`,
			  spos.`NEXT_PAYMENT_LOCAL` AS `Next Payment - Local`,
			  spos.`NEXT_PAYMENT_BASE` AS `Next Payment - Base`,
			  spos.`REPO_MATURITY_AMOUNT` AS `Repo Maturity Amount`,
			  spos.`INDEX_VALUE` AS `Index Value`,
			  spos.`COMPOSITE_ID_BB_GLOBAL` AS `Composite ID BB Global`,
			  spos.`COUNTERPARTY` AS `Counterparty`,
			  spos.`ULTIMATE_PARENT_COUNTRY` AS `Ultimate Parent Country`,
			  spos.`NEXT_COUPON_DATE` AS `Next Coupon Date`,
			  spos.`SCD_SECURITY_TYPE` AS `SCD Security Type`,
			  spos.`ST_CLASSIFICATION` AS `St Classification`,
			  spos.`EQUITY_ASSET_CLASS` AS `Equity Asset Class`,
			  spos.`FIXED_INCOME_ASSET_CLASS` AS `Fixed Income Asset Class`,
			  spos.`SECURITY_ID_2` AS `Security ID 2`,
			  spos.`ISSUER_NAME` AS `Issuer Name`,
			  spos.`JR_ID` AS `Jr ID`,
			  spos.`JR_NAME` AS `Jr Name`,
			  spos.`PARENT_ISSUER` AS `Parent Issuer`,
			  spos.`PORTAMV` AS `Portamv`,
			  spos.`PORTBC` AS `Portbc`,
			  spos.`GROUPAMV` AS `Groupamv`,
			  spos.`GROUPBC` AS `Groupbc`,
			  spos.`BLOCKTRADE_BBG_ID` AS `Blocktrade Bbg ID`,
			  spos.`OFF_BALANCE_COST` AS `Off Balance Cost`,
			  spos.`SWAP_INDEX` AS `Swap Index`,
			  spos.`DAY_COUNT` AS `Day Count`,
			  spos.`PAY_FREQUENCY` AS `Pay Frequency`,
			  spos.`RESET_FREQUENCY` AS `Reset Frequency`,
			  spos.`MONTH_END_STATUS` AS `Month End Status`,
			  spos.`PRICE_DATE` AS `Price Date`,
			  spos.`PORTFOLIO_GROUP_OBJECTIVE` AS `Portfolio Group1`,
			  spos.`DOMICILE_COUNTRY_CODE` AS `Domicile Country Code`,
			  spos.`ASIA_ASSET_CLASS_CODE_IN` AS `Asia Asset Class Code Indonesia`,
			  spos.`ASIA_ASSET_CLASS_CODE_VI` AS `Asia Asset Class Code Vietnam`,
			  spos.`ASIA_ASSET_CLASS_DESC_IN` AS `Asia Asset Class Desc Indonesia`,
			  spos.`ASIA_ASSET_CLASS_DESC_VI` AS `Asia Asset Class Desc Vietnam`,
			  spos.`FUNCTIONAL_CCY_CD` AS `Functional Ccy Code`,
			  spos.`LOCAL_TO_FUNC_RATE` AS `Local to Func Rate`,
			  spos.`LOCAL_TO_CAD_RATE` AS `Local to CAD Rate`,
			  spos.`LOCAL_TO_USD_RATE` AS `Local to USD Rate`,
			  spos.`LOCAL_TO_HKD_RATE` AS `Local to HKD Rate`,
			  spos.`NEXT_COUPON_AMOUNT` AS `Next Coupon Amount (D)`,
			  spos.`AOCI_HEDGE_PAR` AS `AOCI Hedge Par`,
			  spos.`AOCI_REMAIN_BALANCE_NON_BV_CCY_BASE` AS `AOCI Remain Balance Non BV - Base`,
			  spos.`AOCI_REMAIN_BALANCE_NON_BV_CCY_LOCAL` AS `AOCI Remain Balance Non BV - Local (D)`,
			  spos.`AOCI_REMAIN_BALANCE_REP_CCY_BASE` AS `AOCI Remain Balance Rep - Base`,
			  spos.`AOCI_REMAIN_BALANCE_REP_CCY_LOCAL` AS `AOCI Remain Balance Rep - Local (D)`,
			  spos.`BALANCE_COMMITMENT_CCY_LOCAL` AS `Balance Commitment - Local`,
			  spos.`INCOME_DEFAULT_AMOUNT_CCY_LOCAL` AS `Income Default Amount - Local (D)`,
			  spos.`INCOME_DEFAULT_AMOUNT_CCY_BASE` AS `Income Default Amount - Base`,
			  spos.`NEXT_INTEREST_PAYMENT_CCY_LOCAL` AS `Next Interest Payment - Local`,
			  spos.`NEXT_INTEREST_PAYMENT_CCY_BASE` AS `Next Interest Payment - Base`,
			  spos.`NEXT_PRINCIPAL_PAYMENT_CCY_LOCAL` AS `Next Principal Payment - Local`,
			  spos.`NEXT_PRINCIPAL_PAYMENT_CCY_BASE` AS `Next Principal Payment - Base`,
			  spos.`BALANCE_UNPAID_COMMITMENT_CCY_LOCAL` AS `Balance Unpaid Commitment`,
			  spos.`POS_ACCRUAL_BASE` AS `Pos Accrual - Base`,
			  spos.`NEXT_DIVIDEND_CCY_LOCAL` AS `Next Dividend - Local (D)`,
			  spos.`BOOK_YIELD` AS `Current Yield Book Price (D)`,
			  spos.`CONVEXITY` AS `Convexity`,
			  spos.`CURRENT_YIELD` AS `Current Yield (D)`,
			  spos.`DIRTY_PRICE` AS `Dirty Price`,
			  spos.`MODIFIED_DURATION_YTM` AS `Modified Duration YTM`,
			  spos.`MODIFIED_DURATION_YC` AS `Modified Duration YC`,
			  spos.`ORIGINAL_BOOK_YIELD` AS `Original Book Yield (D)`,
			  spos.`BALANCE_COST_VALUE_CCY_LOCAL` AS `Balance Cost Value - Local`,
			  spos.`BALANCE_COST_VALUE_CCY_BASE` AS `Balance Cost Value - Base`,
			  spos.`BALANCE_BOOK_VALUE_CCY_LOCAL` AS `Book Value - Local (D)`,
			  spos.`BALANCE_BOOK_VALUE_CCY_BASE` AS `Book Value - Base`,
			  spos.`BALANCE_INT_APPR_CCY_LOCAL` AS `Balance Int Appr - Local`,
			  spos.`BALANCE_INT_APPR_CCY_BASE` AS `Balance Int Appr - Base`,
			  spos.`BALANCE_OID_APPR_CCY_LOCAL` AS `Balance OID Appr - Local`,
			  spos.`BALANCE_OID_APPR_CCY_BASE` AS `Balance OID Appr - Base`,
			  spos.`BALANCE_CL_ALLOWANCE_CCY_LOCAL` AS `Balance CL Allowance - Local`,
			  spos.`BALANCE_CL_ALLOWANCE_CCY_BASE` AS `Balance CL Allowance - Base`,
			  spos.`BALANCE_RECOG_CL_ALLOWANCE_CCY_LOCAL` AS `Balance Recog CL Allowance - Local`,
			  spos.`BALANCE_RECOG_CL_ALLOWANCE_CCY_BASE` AS `Balance Recog CL Allowance - Base`,
			  spos.`BALANCE_WRITE_OFF_CCY_LOCAL` AS `Balance Write Off - Local`,
			  spos.`BALANCE_WRITE_OFF_CCY_BASE` AS `Balance Write Off - Base`,
			  spos.`BALANCE_IMPAIRMENT_CCY_LOCAL` AS `Balance Impairment - Local`,
			  spos.`BALANCE_IMPAIRMENT_CCY_BASE` AS `Balance Impairment - Base`,
			  spos.`AOCI_REMAIN_BALANCE_BV_CCY_LOCAL` AS `AOCI Remain Balance BV - Local (D)`,
			  spos.`AOCI_REMAIN_BALANCE_BV_CCY_BASE` AS `AOCI Remain Balance BV - Base`,
			  spos.`BALANCE_DEFERRED_PL_CCY_LOCAL` AS `Balance Deferred PL - Local (D)`,
			  spos.`BALANCE_DEFERRED_PL_CCY_BASE` AS `Balance Deferred PL - Base`,
			  spos.`INCOME_ACCRUAL_CCY_LOCAL` AS `Income Accrual - Local (D)`,
			  spos.`INCOME_ACCRUAL_CCY_BASE` AS `Income Accrual - Base`,
			  spos.`BALANCE_EXPECTED_RESTITUT_CCY_LOCAL` AS `Balance Expected Restitution - Local`,
			  spos.`BALANCE_EXPECTED_RESTITUT_CCY_BASE` AS `Balance Expected Restitution - Base`,
			  spos.`CARRYING_VALUE_CCY_LOCAL` AS `Carrying Value - Local (D)`,
			  spos.`CARRYING_VALUE_CCY_BASE` AS `Carrying Value - Base`,
			  spos.`UPDATED_TS` AS `Updated Ts`,
			  spos.`ADJUSTED_BOOK_VALUE_LOCAL` AS `Adjusted Book Value Local`,
			  spos.`ADJUSTED_BOOK_VALUE_BASE` AS `Adjusted Book Value Base`,
			  spos.`ISSUER_LONG_COMP_NAME` AS `SCD Issuer Long Company Name`,
			  spos.`SCD_DEFAULT_DATE` AS `SCD Default Date`,
			  spos.`SCD_DEFAULT_DATE_FC` AS `Accrue In Default`,
			  spos.`UNSETTLED_INT_DIV_AMOUNT_BASE_CCY` AS `Unsettled Int Div Amount Base CCY`,
			  spos.`UNSETTLED_INT_DIV_AMOUNT_LOCAL_CCY` AS `Unsettled Int Div Amount Local CCY`,
			  spos.`BALANCE_ACQUISITION_PRE_DIS_BASE_CCY` AS `Balance Acquisition Pre Dis Base CCY`,
			  spos.`BALANCE_ACQUISITION_PRE_DIS_LOCAL_CCY` AS `Balance Acquisition Pre Dis Local CCY`,
			  spos.`PURPOSE` AS `Purpose`,
			  spos.`IFRS9PURPOSE` AS `IFRS9 Purpose`,
			  spos.`BALANCE_BOOK_VALUE_LOCAL_CCY_NATIVE` AS `Balance Book Value Local Native`,
			  spos.`BALANCE_BOOK_VALUE_BASE_CCY_NATIVE` AS `Balance Book Value Base Native`,
			  spos.`CALCULATION_DATE_FULL` AS `Calculation Date Full`,
			  spos.`LONG_SHORT_INDICATOR` AS `Long Short Indicator`,
			  spos.`ACCRUED_INTEREST_EOP_LOCAL_CCY` AS `Accrued Interest EOP Local`,
			  spos.`ACCRUED_INTEREST_EOP_BASE_CCY` AS `Accrued Interest EOP Base`,
			  spos.`BALANCE_RETURN_OF_CAPITAL_BASE_CCY` AS `Balance Return Of Capital Base`,
			  spos.`BALANCE_RETURN_OF_CAPITAL_LOCAL_CCY` AS `Balance Return Of Capital Local`,
			  spos.`BALANCE_CALLED_CAPITAL_BASE_CCY` AS `Balance Called Capital Base`,
			  spos.`BALANCE_CALLED_CAPITAL_LOCAL_CCY` AS `Balance Called Capital Local`,
			  spos.`BALANCE_RECALLABLE_BASE_CCY` AS `Balance Recallable Base`,
			  spos.`BALANCE_RECALLABLE_LOCAL_CCY` AS `Balance Recallable Local`,
			  spos.`FX_JOIN_KEY` AS `FX Join Key`,
			  spos.`BALANCE_NAIC_CARRYING_VALUE_LOCAL_CCY` AS `Balance NAIC Carrying Value Local`,
			  spos.`BALANCE_NAIC_CARRYING_VALUE_BASE_CCY` AS `Balance NAIC Carrying Value Base`,
			  spos.`BALANCE_NAIC_SEC_ADJ_LOCAL_CCY` AS `Balance NAIC Sec Adj Local`,
			  spos.`BALANCE_NAIC_SEC_ADJ_BASE_CCY` AS `Balance NAIC Sec Adj Base`,
			  spos.`CALCULATED_UNREALIZED_GAIN_LOSS_LOCAL` AS `Calculated Unrealized Gain/Loss – Local`,
			  spos.`ML_BUSINESS_GROUP` AS `ML Business Group`,
			  spos.`SCD_GL_CLASSIFICATION` AS `SCD GL Classification`,
			  spos.`issue_volume` AS `Issue Volume`,
			  spos.`structure` AS `Structure`,
			  spos.`ACCRUED_INTEREST_QC_STATIC` AS `Accrued Interest QC (Static)`,
			  spos.`ACCRUED_INTEREST_PC_STATIC` AS `Accrued Interest PC (Static)`
			from "&Catalog&".inv_semantic_ga.SECURITIES_POSITION_FACT_DQ as spos
			where 
			(
			    (
			        (as_of_dt=last_day(as_of_dt)) or 
			        datediff((select max(as_of_dt) from "&Catalog&".inv_semantic_ga.SECURITIES_POSITION_FACT_DQ),as_of_dt) <="&LastNDays&
			    ")"&
			    " and ( as_of_dt >= '"&Date.ToText(Date.From(RangeStart),"yyyy-M-d")&"' and as_of_dt<'"&Date.ToText(Date.From(RangeEnd),"yyyy-M-d") &"' )"&
			    " and ( as_of_dt >= '"&Date.ToText(Date.From(pCutOffDate),"yyyy-M-d")&"')"&
			")",
			    Source = Value.NativeQuery(Databricks.Catalogs(HostName, HTTPPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null,CommandTimeout= #duration(0,5,0,0)]){[Name=Catalog,Kind="Database"]}[Data], Sql, null, [EnableFolding=true]),
			    #"Filtered Rows" = Table.SelectRows(Source, each true)
			in
			    #"Filtered Rows"
			```

	measure 'Security Position Title' = ```
			
			VAR maxdate =
			    MAX ( 'Securities Position Fact'[As Of Date] )
			RETURN
			    "Security Position" & ", "
			        & SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) & ", "
			        & SELECTEDVALUE ( Framework[Framework Display] ) & ", "
			        & FORMAT ( maxdate, "dd-mmm-yy" )
			
			```
		lineageTag: fa1daf8d-ffc3-465a-a222-8436c193afd3

	measure 'Reporting Currency (Security Position)' = ```
			
			VAR SelectedCurrency =
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] )
			VAR ReportingCurrency =
			    IF (
			        NOT ISEMPTY ( 'Securities Position Fact' ),
			        IF (
			            SelectedCurrency = "Company",
			            FIRSTNONBLANK ( 'Securities Position Fact'[Functional Ccy Code], TRUE () ),
			            IF (
			                SelectedCurrency = "SCD Base",
			                FIRSTNONBLANK ( 'Securities Position Fact'[Base], TRUE () ),
			                SelectedCurrency
			            )
			        )
			    )
			RETURN
			    ReportingCurrency
			
			```
		lineageTag: ec12969e-9a03-4452-9249-b0bad4baaa35

	measure 'Rep Rate (Security Position)' = ```
			
			VAR maxd =
			    MAX ( 'Period'[Period] )
			VAR fxrate =
			    SWITCH (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			        "USD",
			            CALCULATE (
			                MIN ( 'Securities Position Fact'[Local to USD Rate] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Period] = maxd
			                )
			            ),
			        "CAD",
			            CALCULATE (
			                MIN ( 'Securities Position Fact'[Local to CAD Rate] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Period] = maxd
			                )
			            ),
			        "HKD",
			            CALCULATE (
			                MIN ( 'Securities Position Fact'[Local to HKD Rate] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Period] = maxd
			                )
			            ),
			        "Company",
			            CALCULATE (
			                MIN ( 'Securities Position Fact'[Local to Func Rate] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Period] = maxd
			                )
			            ),
			        "SCD Base",
			            CALCULATE (
			                MIN ( 'Securities Position Fact'[Local Exchange Rate] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Period] = maxd
			                )
			            )
			    )
			RETURN
			    fxrate
			
			```
		formatString: 0.000000
		lineageTag: 9fc8528b-3f4e-425e-b775-ddf4708a6b28

	measure 'Fair Value Accrued - Rep (Sec Pos)' = ```
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Fair Value Accrued - Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Fair Value Accrued - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			 IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX('Securities Position Fact', 'Securities Position Fact'[Fair Value Accrued - Local (D)]* 'Fx Rate DQ'[Rep Rate] ),
			
			            CALCULATE (
			                    SUMX('Securities Position Fact', 'Securities Position Fact'[Fair Value Accrued - Local (D)]* 'Fx Rate DQ'[Rep Rate] ),
			                LASTDATE('Securities Position Fact'[As Of Date])
			            )
			        ))
			/*VAR maxd =
			    MAX ( 'Securities Position Fact'[As Of Date] )
			VAR calc =
			    SWITCH (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			        "USD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Fair Value Accrued - USD]),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "CAD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Fair Value Accrued - CAD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "HKD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Fair Value Accrued - HKD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "Company",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Fair Value Accrued - FUNC] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "SCD Base",
			            CALCULATE (
			                SUM( 'Securities Position Fact'[Fair Value Accrued - Base] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            )
			    )
			RETURN
			    calc*/
			
			```
		lineageTag: 9543d058-02ae-4741-ac04-ecca03edf156

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Next Payment - Rep' = ```
			
			  SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Next Payment - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Next Payment - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Next Payment - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Next Payment - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*VAR maxd =
			    MAX ( 'Securities Position Fact'[As Of Date] )
			VAR calc =
			    SWITCH (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			        "USD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Next Payment - USD]),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "CAD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Next Payment - CAD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "HKD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Next Payment - HKD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "Company",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Next Payment - FUNC] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "SCD Base",
			            CALCULATE (
			                SUM( 'Securities Position Fact'[Next Payment - Base] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            )
			    )
			RETURN
			    calc*/
			
			```
		lineageTag: f1cb777a-d813-473a-8f84-e5191b20c089

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Price - Rep' = ```
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Price - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Price - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    AVERAGEX( 
			        'Securities Position Fact',
			        'Securities Position Fact'[Price - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        AVERAGEX( 
			            'Securities Position Fact',
			            'Securities Position Fact'[Price - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)) 
			/*VAR maxd =
			    MAX ( 'Securities Position Fact'[As Of Date] )
			VAR calc =
			    SWITCH (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			        "USD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Price - USD]),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "CAD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Price - CAD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "HKD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Price - HKD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "Company",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Price - FUNC] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "SCD Base",
			            CALCULATE (
			                SUM( 'Securities Position Fact'[Price - Base] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            )
			    )
			RETURN
			    calc*/
			
			```
		lineageTag: 7e0b89a7-9636-428d-bc4f-6d760a15bfd3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Withheld - Rep' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Withheld - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Withheld - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Withheld - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Withheld - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*CALCULATE (
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Position Fact'[Withheld - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Position Fact'[Withheld - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Position Fact'[Withheld - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Position Fact'[Withheld - FUNC] ),
							SUM ( 'Securities Position Fact'[Withheld - HKD] )
							)
						)
					)
				),
			    FILTER(
			        'Securities Position Fact',
			        'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
				)
			*/
			
			
			```
		formatString: #,0.00
		lineageTag: f951c5c3-6a63-4967-a810-ca439ec5c3ca

	measure 'Accrual - Rep' = [Accrual - Position Rep]+[Accrual - Adjustment Rep]
		lineageTag: 8bfbe243-ff14-4792-b4d0-a012a08c9bbb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Rep (Sec Pos)' = [Unrealized Gain/Loss - Position Rep (Sec Pos)]+[Unrealized Gain/Loss - Adjustment Rep (Sec Pos)]
		lineageTag: 43b5c4fb-8bc4-4254-aabf-9a2a84a676ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fair Value Unaccrued - Rep (Sec Pos)' = ```
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Fair Value Unaccrued - Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Fair Value Unaccrued - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Fair Value Unaccrued - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE( 
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Fair Value Unaccrued - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*VAR maxd =
			    MAX ( 'Securities Position Fact'[As Of Date] )
			VAR calc =
			    SWITCH (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			        "USD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Fair Value Unaccrued - USD]),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "CAD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Fair Value Unaccrued - CAD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "HKD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Fair Value Unaccrued - HKD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "Company",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Fair Value Unaccrued - FUNC] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "SCD Base",
			            CALCULATE (
			                SUM( 'Securities Position Fact'[Fair Value Unaccrued - Base] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            )
			    )
			RETURN
			    calc*/
			
			```
		lineageTag: 1b77f461-8b07-4060-a597-8a6230c75d53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Original Cost - Rep (Sec Pos)' = ```
			
			   SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Original Cost - Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Original Cost - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Original Cost - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Original Cost - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			
			/*VAR maxd =
			    MAX ( 'Securities Position Fact'[As Of Date] )
			VAR calc =
			    SWITCH (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			        "USD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Original Cost - USD]),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "CAD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Original Cost - CAD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "HKD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Original Cost - HKD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "Company",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Original Cost - FUNC] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "SCD Base",
			            CALCULATE (
			                SUM( 'Securities Position Fact'[Original Cost - Base] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            )
			    )
			RETURN
			    calc*/
			
			```
		formatString: #,0.00
		lineageTag: 22356c03-05b6-4989-9692-ffad68d2fd5c

	measure 'Book Value - Rep (Sec Pos)' = ```
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Book Value - Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Book Value - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Book Value - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Book Value - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			
			```
		lineageTag: 196489a1-c153-4382-9c33-096758c3a5b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Port MV' =
			
			DIVIDE (SUM ( 'Securities Position Fact'[Portamv] ),100 )
		formatString: #,0.00
		lineageTag: 8412f6a4-28b4-416d-9d20-836c0ce4129e

	measure '% Port BV' = DIVIDE(SUM('Securities Position Fact'[Portbc]),100)
		formatString: #,0.00
		lineageTag: 6b17d779-0dec-4ded-9475-f018210c66cf

	measure 'Position History Title' = ```
			
			VAR maxdate =
			    MAX ( 'Securities Position Fact'[As Of Date])
			RETURN
			    "Position History" & ", "
			        & SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) & ", "
			        & SELECTEDVALUE ( Framework[Framework Display] ) & ", "
			        & FORMAT ( maxdate, "dd-mmm-yy" )
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 36f70a22-f93b-4b80-91f0-82342e78a081

	measure 'Amortized Cost - Rep' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Amortized Cost - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Amortized Cost - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Amortized Cost - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Amortized Cost - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*CALCULATE (
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Position Fact'[Amortized Cost - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Position Fact'[Amortized Cost - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Position Fact'[Amortized Cost - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Position Fact'[Amortized Cost - FUNC] ),
							SUM ( 'Securities Position Fact'[Amortized Cost - HKD] )
							)
						)
					)
				),
			    FILTER(
			        'Securities Position Fact',
			        'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
				)*/
			
			
			
			```
		lineageTag: f4f0ab44-9b72-4345-b34d-a5ede9b6a6fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss CCY - Rep (Sec Pos)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Unrealized Gain/Loss CCY - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Unrealized Gain/Loss CCY - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss CCY - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss CCY - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			
			/*CALCULATE (
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Position Fact'[Unrealized Gain/Loss CCY - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Position Fact'[Unrealized Gain/Loss CCY - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Position Fact'[Unrealized Gain/Loss CCY - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Position Fact'[Unrealized Gain/Loss CCY - FUNC] ),
							SUM ( 'Securities Position Fact'[Unrealized Gain/Loss CCY - HKD] )
							)
						)
					)
				),
			    FILTER(
			        'Securities Position Fact',
			        'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
				)
			*/
			
			
			```
		lineageTag: 8c2a3ec6-46ff-44ff-a21c-26ba91cf775d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss Sec - Rep (Sec Pos)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Unrealized Gain/Loss Sec - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Unrealized Gain/Loss Sec - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss Sec - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss Sec - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*CALCULATE (
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Position Fact'[Unrealized Gain/Loss Sec - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Position Fact'[Unrealized Gain/Loss Sec - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Position Fact'[Unrealized Gain/Loss Sec - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Position Fact'[Unrealized Gain/Loss Sec - FUNC] ),
							SUM ( 'Securities Position Fact'[Unrealized Gain/Loss Sec - HKD] )
							)
						)
					)
				),
			    FILTER(
			        'Securities Position Fact',
			        'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
				)
			*/
			
			
			```
		lineageTag: f985dc8e-8eb7-49a5-a795-27916efa41e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure W/H% = SUM('Securities Position Fact'[Withholding Rate])*100
		formatString: #,0.00
		lineageTag: 14f69a81-3408-432b-8833-96f7ed3564eb

	measure 'Carrying Value - Rep (Sec Pos)' = ```
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Carrying Value - Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Carrying Value - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX('Securities Position Fact', 'Securities Position Fact'[Carrying Value - Local (D)] *'Fx Rate DQ'[Rep Rate]),
			
			            CALCULATE (
			                    SUMX('Securities Position Fact', 'Securities Position Fact'[Carrying Value - Local (D)] *'Fx Rate DQ'[Rep Rate]),
			                LASTDATE('Securities Position Fact'[As Of Date])
			            )
			        ))
			/*VAR maxd =
			    MAX ( 'Securities Position Fact'[As Of Date] )
			VAR calc =
			    SWITCH (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			        "USD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Carrying Value - USD]),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "CAD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Carrying Value - CAD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "HKD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Carrying Value - HKD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "Company",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Carrying Value - FUNC] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "SCD Base",
			            CALCULATE (
			                SUM( 'Securities Position Fact'[Carrying Value - Base] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            )
			    )
			RETURN
			    calc*/
			
			```
		lineageTag: 845894a4-8cea-4c41-a7e5-89c2a15ef079

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Exchange Rate' = FIRSTNONBLANK('Securities Position Fact'[Local Exchange Rate], TRUE())
		formatString: 0.000000
		lineageTag: 77922030-93cc-4759-9eb0-f14ef575a95e

	measure 'SCD Coupon' = ```
			
			    /*CALCULATE (
			                SUM ( 'Securities Position Fact'[Coupon (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[SCD Coupon (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[SCD Coupon (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			```
		formatString: 0.00
		lineageTag: 93df0aeb-9290-4bd6-98f5-e27750e2bef1

	measure 'Income Accrual - Rep' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Income Accrual - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Income Accrual - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Income Accrual - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Income Accrual - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*CALCULATE (
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Position Fact'[Income Accrual - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Position Fact'[Income Accrual - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Position Fact'[Income Accrual - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Position Fact'[Income Accrual - FUNC] ),
							SUM ( 'Securities Position Fact'[Income Accrual - HKD] )
							)
						)
					)
				),
			    FILTER(
			        'Securities Position Fact',
			        'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
				)*/
			
			
			```
		lineageTag: ef4ebf29-d8f6-480e-8ecc-99b82afc52e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Expected Restitution - Rep' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Expected Restitution - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Balance Expected Restitution - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Expected Restitution - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Expected Restitution - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*CALCULATE (
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Position Fact'[Balance Expected Restitution - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Position Fact'[Balance Expected Restitution - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Position Fact'[Balance Expected Restitution - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Position Fact'[Balance Expected Restitution - FUNC] ),
							SUM ( 'Securities Position Fact'[Balance Expected Restitution - HKD] )
							)
						)
					)
				),
			    FILTER(
			        'Securities Position Fact',
			        'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
				)
			*/
			
			
			```
		lineageTag: 902c78f4-da14-4957-92a3-c1a5c0324ae4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Amortization/Accretion - Rep (Sec Pos)' = ```
			
			 SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Int Appr - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Balance Int Appr - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Int Appr - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Int Appr - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*CALCULATE (
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Position Fact'[Balance Int Appr - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Position Fact'[Balance Int Appr - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Position Fact'[Balance Int Appr - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Position Fact'[Balance Int Appr - FUNC] ),
							SUM ( 'Securities Position Fact'[Balance Int Appr - HKD] )
							)
						)
					)
				),
			    FILTER(
			        'Securities Position Fact',
			        'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
				)
			*/
			
			
			```
		lineageTag: a7be080b-7068-4372-82fa-16725f9ddb9d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OID Amortization/Accretion - Rep (Sec Pos)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance OID Appr - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Balance OID Appr - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance OID Appr - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance OID Appr - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*CALCULATE (
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Position Fact'[Balance OID Appr - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Position Fact'[Balance OID Appr - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Position Fact'[Balance OID Appr - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Position Fact'[Balance OID Appr - FUNC] ),
							SUM ( 'Securities Position Fact'[Balance OID Appr - HKD] )
							)
						)
					)
				),
			    FILTER(
			        'Securities Position Fact',
			        'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
				)*/
			
			
			
			```
		lineageTag: a68217ba-880c-4f7c-8581-1bb75902dccb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTTI Impairment - Rep (Sec Pos)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Impairment - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Balance Impairment - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Impairment - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Impairment - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			    
			/*CALCULATE (
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Position Fact'[Balance Impairment - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Position Fact'[Balance Impairment - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Position Fact'[Balance Impairment - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Position Fact'[Balance Impairment - FUNC] ),
							SUM ( 'Securities Position Fact'[Balance Impairment - HKD] )
							)
						)
					)
				),
			    FILTER(
			        'Securities Position Fact',
			        'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
				)*/
			
			
			
			```
		lineageTag: 84cba97c-632e-46f7-826c-5db1d18134d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Remain Balance BV - Rep (Sec Pos)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[AOCI Remain Balance BV - Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[AOCI Remain Balance BV - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance BV - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance BV - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*VAR maxd =
			    MAX ( 'Securities Position Fact'[As Of Date] )
			VAR calc =
			    SWITCH (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			        "USD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[AOCI Remain Balance BV - USD]),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "CAD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[AOCI Remain Balance BV - CAD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "HKD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Carrying Value - HKD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "Company",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[AOCI Remain Balance BV - FUNC] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "SCD Base",
			            CALCULATE (
			                SUM( 'Securities Position Fact'[AOCI Remain Balance BV - Base] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            )
			    )
			RETURN
			    calc*/
			
			```
		lineageTag: f3794653-85e2-424f-9dc8-3cde8ad942a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Deferred PL - Rep (Sec Pos)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Deferred PL - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Balance Deferred PL - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Deferred PL - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Deferred PL - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*CALCULATE (
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Position Fact'[Balance Deferred PL - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Position Fact'[Balance Deferred PL - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Position Fact'[Balance Deferred PL - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Position Fact'[Balance Deferred PL - FUNC] ),
							SUM ( 'Securities Position Fact'[Balance Deferred PL - HKD] )
							)
						)
					)
				),
			    FILTER(
			        'Securities Position Fact',
			        'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
				)*/
			
			
			
			```
		lineageTag: 6f4b09ae-7709-472f-b27f-62f05ea83753

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income Tax Withholding - Local' = ```
			
			/*SUMX (
			    'Securities Position Fact',
			    'Securities Position Fact'[Income Accrual - Local (D)] * 'Securities Position Fact'[Withholding Rate]
			)*/
			/*IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Income Accrual - Local (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[Income Accrual - Local (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			    'Securities Position Fact',
			    'Securities Position Fact'[Income Accrual - Local (D)] * 'Securities Position Fact'[Withholding Rate]
			),
			    CALCULATE( 
			        SUMX (
			    'Securities Position Fact',
			    'Securities Position Fact'[Income Accrual - Local (D)] * 'Securities Position Fact'[Withholding Rate]
			),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			
			```
		lineageTag: 175f5266-762a-4505-aeae-76640d8700da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ECL/CECL Impairment - Rep (Sec Pos)' =
			
			SUMX(SUMMARIZE('Securities Position Fact',Securities[Asset Class]),
			IF(Securities[Asset Class] IN {"Equity","Other Invested Asset"},[OTTI Impairment - Rep (Sec Pos)],[ECL/CECL Impairment - Position Rep (Sec Pos)]))+[ECL/CECL Impairment - Adjustment Rep (Sec Pos)]
		lineageTag: 53bee58a-7477-4697-8d02-52402edbe434

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Local (Sec Pos)' = ```
			
			/*VAR prd =
			    MAX ( Period[Period End Date] )
			RETURN
			    CALCULATE (
			        FIRSTNONBLANK ( 'Securities Position Fact'[Local], TRUE () ),
			        FILTER ( 'Securities Position Fact', 'Securities Position Fact'[As Of Date] = prd )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SELECTEDVALUE ( 'Securities Position Fact'[Local] ),
			    CALCULATE( 
			        SELECTEDVALUE ( 'Securities Position Fact'[Local] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: f18624c1-8d3e-434d-806e-e743c66935a2

	measure 'Units (PH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			        SUM (
			            'Securities Position Fact'[Units (D)]
			        ),
			        ALL ( 'Period' ),
			        'Securities Position Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		formatString: #,0.000
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 078e4307-8ace-4f19-b809-9102cd5bff94

	measure 'Fair Value Accrued - Rep (PH)' = ```
			
			VAR Prd =
			    MAX ( 'Period'[Period] )
			RETURN 
			 IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
			    CALCULATE (
				SUM ( 'Securities Position Fact'[Fair Value Accrued - Base] ),
			        ALL('Period'),
			        'Securities Position Fact'[As Of Period] <= Prd
			        
			    ),
			 CALCULATE(SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Fair Value Accrued - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			        ALL('Period'),
			        'Securities Position Fact'[As Of Period] <= Prd
			        
			    ))
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: c7882166-50aa-4366-9d67-ade933c6c32b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Price - Rep (PH)' = ```
			
			VAR Prd =
			    MAX ( 'Period'[Period] )
			RETURN
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
			        CALCULATE (
			            AVERAGE ( 'Securities Position Fact'[Price - Base] ),
			            ALL ( 'Period' ),
			            'Securities Position Fact'[As Of Period] <= Prd
			        ),
			        CALCULATE (
			            AVERAGEX (
			                'Securities Position Fact',
			                'Securities Position Fact'[Price - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			            ),
			            ALL ( 'Period' ),
			            'Securities Position Fact'[As Of Period] <= Prd
			        )
			    )
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: c2d9d569-f85e-4325-b24d-a300f00cdddb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Rep (PH)' = ```
			
			VAR Prd =
			    MAX ( 'Period'[Period] )
			RETURN
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
			        CALCULATE (
			            /*SUM ( 'Securities Position Fact'[Book Value - Base] ),*/
			SUMX('Securities Position Fact','Securities Position Fact'[Book Value - Base]+'Securities Position Fact'[AOCI Remain Balance BV - Base]+'Securities Position Fact'[Balance Impairment - Base]),
			            ALL ( 'Period' ),
			            'Securities Position Fact'[As Of Period] <= Prd
			        ),
			        CALCULATE (
			           /* SUMX (
			                'Securities Position Fact',
			                'Securities Position Fact'[Book Value - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			            ),*/
			SUMX('Securities Position Fact',
			('Securities Position Fact'[Book Value - Local (D)] * 'Fx Rate DQ'[Rep Rate])+
			('Securities Position Fact'[AOCI Remain Balance BV - Local (D)]*  'Fx Rate DQ'[Rep Rate])+
			('Securities Position Fact'[Balance Impairment - Local] * 'Fx Rate DQ'[Rep Rate])),
			            ALL ( 'Period' ),
			            'Securities Position Fact'[As Of Period] <= Prd
			        )
			    )
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 3c149062-9e8f-4f63-bbd1-0f11a76d8fa0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Original Cost - Rep (PH)' = ```
			
			VAR Prd =
			    MAX ( 'Period'[Period] )
			RETURN
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
			        CALCULATE (
			            SUM ( 'Securities Position Fact'[Original Cost - Base] ),
			            ALL ( 'Period' ),
			            'Securities Position Fact'[As Of Period] <= Prd
			        ),
			        CALCULATE (
			            SUMX (
			                'Securities Position Fact',
			                'Securities Position Fact'[Original Cost - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			            ),
			            ALL ( 'Period' ),
			            'Securities Position Fact'[As Of Period] <= Prd
			        )
			    )
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: df2da222-4f6a-4700-b8dc-a762021efffb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accrual - Local (PH)' = ```
			
			VAR Prd =
			    MAX ( 'Period'[Period] )
			RETURN 
			    CALCULATE (
			        SUM('Securities Position Fact'[Accrual - Local (D)]),
			        ALL ( 'Period' ),
			        'Securities Position Fact'[As Of Period] <= Prd
			    )
			   /* CALCULATE (
			        IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Position Fact'[Accrual - Base] ),
			SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Accrual - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    )
				),
			        ALL ( 'Period' ),
			        'Securities Position Fact'[As Of Period] <= Prd
			    )*/
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: b0dea1af-4bf1-473f-afb7-f8a57d6536d1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Local Exchange Rate (PH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			        FIRSTNONBLANK ( 'Securities Position Fact'[Local Exchange Rate], TRUE () ),
			        ALL ( 'Period' ),
			        'Securities Position Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		formatString: 0.000000
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: f1cb3a5e-d347-4179-8193-05b43d9c1b4a

	measure 'Unrealized Gain/Loss CCY - Rep (PH)' = ```
			
			VAR Prd =
			    MAX ( 'Period'[Period] )
			
			RETURN
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
			        CALCULATE (
			            SUM ( 'Securities Position Fact'[Unrealized Gain/Loss CCY - Base] ),
			            ALL ( 'Period' ),
			            'Securities Position Fact'[As Of Period] <= Prd
			        ),
			        CALCULATE (
			            SUMX (
			                'Securities Position Fact',
			                'Securities Position Fact'[Unrealized Gain/Loss CCY - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			            ),
			            ALL ( 'Period' ),
			            'Securities Position Fact'[As Of Period] <= Prd
			        )
			    )
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: a08e345a-d75c-4394-86c6-97e8eb8d5252

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss Sec - Rep (PH)' = ```
			
			
			VAR Prd =
			    MAX ( 'Period'[Period] )
			
			RETURN
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
			        CALCULATE (
			            SUM ( 'Securities Position Fact'[Unrealized Gain/Loss Sec - Base] ),
			            ALL ( 'Period' ),
			            'Securities Position Fact'[As Of Period] <= Prd
			        ),
			        CALCULATE (
			            SUMX (
			                'Securities Position Fact',
			                'Securities Position Fact'[Unrealized Gain/Loss Sec - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			            ),
			            ALL ( 'Period' ),
			            'Securities Position Fact'[As Of Period] <= Prd
			        )
			    )
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 32921ffa-ca0f-49fe-9c31-53bcfa31ad48

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Face (PH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			VAR Dt =
			    CALCULATE (
			        SUM ( 'Securities Position Fact'[Current Face (D)] ),
			        ALL ( 'Period' ),
			        'Securities Position Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: 6f0a0170-08ac-40c4-b6dc-006dbd895a88

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ML IFRS 13 Level (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML IFRS 13 Level], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 02dcfa0b-04a6-4f4f-af9e-2fbd99b07ac0

	measure 'Accrual Currency (Sec Pos)' = ```
			
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Accrual Currency], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: c8d6b516-4b83-4715-a33f-37b77382e196

	measure 'Country Of Issue (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK('Securities'[Country Of Issue - NoBlank],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: dfe1c04e-284c-4492-a034-991b400e27d2

	measure 'Default Flag (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Default Flag], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: ec0de4c4-ffb4-49f4-8ef3-95667f595b41

	measure 'Exchange Country (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Exchange Country], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 42189b7d-517b-4923-9054-a14e10ba7af4

	measure 'Findur ID (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Findur ID], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: e7bdd6f4-78b2-418f-964a-d9d4f1055dc0

	measure 'Isin (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Isin], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 083a0bb9-ab45-4bc9-a6ab-5c979978ee51

	measure 'Islamic Indicator (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Islamic Indicator], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 5796959b-f865-418a-aa54-ed984eba322a

	measure 'Local ID (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Local ID], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 91ec016b-5cd6-4934-80cb-8a203f107828

	measure 'Price Point (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Price Point], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 181e1ea7-eeaf-44a2-b695-821bfc3ef56e

	measure 'Principal Exchange (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Principal Exchange], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: bd4f4024-9c77-4b1d-b595-20a6e9640f7c

	measure 'Private Placement (Sec Pos)' = CALCULATE(FIRSTNONBLANK(Securities[Private Placement (Adj)],TRUE()),CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH ))
		displayFolder: Security Values
		lineageTag: bc543b8b-6110-4bbc-9163-1764b451a05f

	measure 'Cusip (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Cusip], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 7de8f897-073c-4457-bafe-e80272c8f26a

	measure 'Official PPN (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Official PPN], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 32b640ec-5049-48ad-8981-3a39912a5653

	measure 'Carrying Value - Local' = ```
			
			   /* CALCULATE (
			                SUM ( 'Securities Position Fact'[Carrying Value - Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Carrying Value - Local (D)] ),
			
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Carrying Value - Local (D)] ),
			                LASTDATE('Securities Position Fact'[As Of Date])
			            )
			        )
			```
		lineageTag: 5ad0ab28-8a18-4c6f-9cd6-168247f664fd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fair Value Accrued - Local' = ```
			
			  /*  CALCULATE (
			                SUM ( 'Securities Position Fact'[Fair Value Accrued - Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Fair Value Accrued - Local (D)] ),
			
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Fair Value Accrued - Local (D)] ),
			                LASTDATE('Securities Position Fact'[As Of Date])
			            )
			        )
			```
		lineageTag: d28f9712-5322-4a07-acc9-729529eb96e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Local' = ```
			
			    /*CALCULATE (
			                SUM ( 'Securities Position Fact'[Book Value - Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Book Value - Local (D)] ),
			    CALCULATE (
			        SUM ( 'Securities Position Fact'[Book Value - Local (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: 0e34d70c-4a26-46c1-ae4e-55b4e7ea0935

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Original Cost - Local' =
			
			/*    CALCULATE (
			                SUM ( 'Securities Position Fact'[Original Cost - Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Original Cost - Local (D)] ),
			    CALCULATE (
			        SUM ( 'Securities Position Fact'[Original Cost - Local (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
		lineageTag: 7194f639-d90b-484c-ba7d-fda84b79cc3e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Amortized Cost - Local' = ```
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Amortized Cost - Local (D)]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Amortized Cost - Local (D)]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			   /* CALCULATE (
			                SUM ( 'Securities Position Fact'[Amortized Cost -  Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			
			```
		lineageTag: 393edb9d-2beb-4c66-a89f-15ceb4620578

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fair Value Unaccrued - Local' = ```
			
			   /* CALCULATE (
			                SUM ( 'Securities Position Fact'[Fair Value Unaccrued - Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Fair Value Unaccrued - Local (D)] ),
			    CALCULATE (
			        SUM ( 'Securities Position Fact'[Fair Value Unaccrued - Local (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: d5e9414d-2130-4c73-a725-327ee5910e02

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Local' = [Unrealized Gain/Loss - Position Local]+[Unrealized Gain/Loss - Adjustment Local]
		lineageTag: 7dd9afb9-19d0-494b-b004-02c2d4ef6662

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accrual - Local' = [Accrual - Position Local]+[Accrual - Adjustment Local]
		lineageTag: 1016a272-5232-459e-aad9-74abae74a8be

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Withheld - Local' = ```
			
			    /*CALCULATE (
			                SUM ( 'Securities Position Fact'[Withheld - Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Withheld - Local (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[Withheld - Local (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: 8a39135a-cd85-4a6e-9dc2-d9302c4e1fa4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Local (PH)' = ```
			
			VAR closePeriod =
			    MAX ( 'Period'[Period] )
			/*VAR Dt =
			    CALCULATE (
			        SUM('Securities Position Fact'[Book Value - Local (D)]),
			        ALL ( 'Period' ),
			        'Securities Position Fact'[As Of Period] <= closePeriod
			    )*/
			VAR Dt =  CALCULATE (
			SUMX('Securities Position Fact','Securities Position Fact'[Book Value - Local (D)]+'Securities Position Fact'[AOCI Remain Balance BV - Local (D)]+'Securities Position Fact'[Balance Impairment - Local]),
			        ALL ( 'Period' ),
			        'Securities Position Fact'[As Of Period] <= closePeriod
			    )
			RETURN
			    Dt
			
			```
		isHidden
		displayFolder: Position Research Attributes
		lineageTag: d0230a97-fa9f-40f2-a43c-22b0ff7a9c51

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Private Portf Ind (Sec Pos)' =
			
			CALCULATE (
			    SUM('Portfolios Attributes'[Private Portf Ind (D)]),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio Nk], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		formatString: 0
		displayFolder: Portfolio Attributes
		lineageTag: 5e658c19-cc5f-412f-ba75-7aa0cf7a9974

	measure 'Portfolio Sleeve Status (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Portfolio Sleeve Status],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio Nk], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 913c520e-4740-4ca3-aa98-216f5865e242

	measure 'Price - Local' = ```
			
			   /* CALCULATE (
			                AVERAGE( 'Securities Position Fact'[Price - Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    AVERAGE( 'Securities Position Fact'[Price - Local (D)] ),
			    CALCULATE(
			        AVERAGE( 'Securities Position Fact'[Price - Local (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: 08297bfd-9346-4cd7-8f46-479ab877b71d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Units = ```
			
			 IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Units (D)] ),
			
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Units (D)] ),
			                LASTDATE('Securities Position Fact'[As Of Date])
			            )
			        )
			/*IF (
			    ISFILTERED ( 'Period DQ'[Date] ),
			    SUM ( 'Securities Position Fact'[Units (D)] ),
			    IF (
			        ISBLANK (
			            CLOSINGBALANCEMONTH (
			                SUM ( 'Securities Position Fact'[Units (D)] ),
			                'Period DQ'[Date]
			            )
			        ),
			        CALCULATE (
			            SUM ( 'Securities Position Fact'[Units (D)] ),
			            FILTER (
			                'Securities Position Fact',
			                'Securities Position Fact'[As Of Date]
			                    = MAX ( 'Securities Position Fact'[As Of Date] )
			            )
			        ),
			        BLANK ()
			    )
			)*/
			/*VAR TRY = CALCULATE(SUM( 'Securities Position Fact'[Units (D)]),
			LASTNONBLANK(PARALLELPERIOD( 'Period DQ'[Date],0, MONTH),SUM( 'Securities Position Fact'[Units (D)])))*/
			```
		formatString: #,0.000
		lineageTag: 945142ee-6695-4987-9e2c-a72205bed17b

	measure 'Moodys (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Moodys], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 16f3fa0e-dcdb-4963-825a-0e07b12b1e5a

	measure 'S&P (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[S&P], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: b9c20064-6364-41bd-b9b4-155994830dd9

	measure 'Fitch (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Fitch], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 846e95e5-e89e-4a2f-b87c-fbd30c660bb6

	measure 'Internal (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Internal], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 7c2aa96c-85f6-4522-931b-a337d8f72297

	measure 'Full Shares Outstanding (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Full Shares Outstanding], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 58cbe988-0dfb-4da2-bafd-7f9192b78478

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income Accrual - Local' = ```
			
			   /* CALCULATE (
			                SUM ( 'Securities Position Fact'[Income Accrual - Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Income Accrual - Local (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[Income Accrual - Local (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: cef03fe8-8503-4fe4-a915-4c5fbf41f015

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Yield Book Price' = ```
			
			    /*CALCULATE (
			            SUM ( 'Securities Position Fact'[Book Yield (D)] ),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Current Yield Book Price (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[Current Yield Book Price (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			```
		lineageTag: e548c3de-99c3-42ce-ac6d-5f7d8ae85f9a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Original Book Yield' = ```
			
			    /*CALCULATE (
			            SUM ( 'Securities Position Fact'[Original Book Yield (D)] ),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Original Book Yield (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[Original Book Yield (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			```
		lineageTag: 93eda38a-a82f-4829-9eb4-00649b8578b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Portfolio Owner (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Portfolio Owner (D)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio Nk], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: b2fe5372-055a-4d24-a8a7-c445e37da44e

	measure 'Indonesian Positions Title' = ```
			
			VAR maxdate =
			    MAX ( 'Securities Position Fact'[As Of Date] )
			RETURN
			    "Indonesian Positions" & ", "
			        & SELECTEDVALUE ( Framework[Framework Display] ) & ", "
			        & FORMAT ( maxdate, "dd-mmm-yy" )
			
			```
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 08d57a09-a64d-46e4-b176-1abf78217b39

	measure 'Price - Local (Indo Pos)' = ```
			
			var calc =
			 CALCULATE ( SUM('Securities Position Fact'[Indonesian Price (Indo Pos)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
			    )
			RETURN
			    calc
			
			```
		formatString: 0.000000
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 5dd764ab-4d43-4bdc-9b4b-aeb2fbcc54cd

	measure 'Fair Value Unaccrued - Local (Indo Pos)' =
			
			--ml_price * Units
			VAR calc =
			    CALCULATE ( SUMX ('Securities Position Fact', 'Securities Position Fact'[Indonesian Price (Indo Pos)] * 'Securities Position Fact'[Units (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date]
			                = MAX ( 'Securities Position Fact'[As Of Date] )
			        )
			    )
			RETURN
			    calc
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: c83df3be-61a7-4475-b860-866b3e9012f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Local (Indo Pos)' = ```
			
			--Fair Value Unaccrued Local - Local Book Value
			VAR calc = 'Securities Position Fact'[Fair Value Unaccrued - Local (Indo Pos)]- 'Securities Position Fact'[Book Value - Local]
			 
			RETURN
			    calc
			
			```
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: b72c2701-1ddb-4a4f-89ef-3aa5cbd9f99e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fair Value Accrued - Local (Indo Pos)' = ```
			
			--Fair Value Unaccrued Local + Local Accrual   
			VAR calc = 'Securities Position Fact'[Fair Value Unaccrued - Local (Indo Pos)] + 'Securities Position Fact'[Accrual - Local]
			RETURN
			    calc
			
			```
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: fb23be5e-f8c0-4446-9ec3-5a4b2ca37e13

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Maximis Portfolio Number (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Maximis Portfolio Number],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 0ccae87c-5818-4efc-b89e-de8524e63254

	measure 'IAS39 Trading Philosophy Code (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[IAS39 Trading Philosophy Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 66a54731-a932-4ec1-bd59-b066ee0a8b48

	measure 'IFRS Trading Philosophy Code (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[IFRS Trading Philosophy Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: cda8740a-8ba2-4f04-8567-a6176dd2f4a2

	measure 'Portfolio Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Portfolio Name],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: c26b94d5-df4d-4641-a80e-ea48b0159f9a

	measure 'Investment Desk (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Investment Desk (D)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: bf1557c9-00ea-4a5e-aa2c-8fb3d1060117

	measure 'Portfolio Manager Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Portfolio Manager Name (D)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 656ac4a6-1e35-4a62-9024-f86cf50c494f

	measure 'Security Description (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Security Description], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 09563ac7-a854-4a2f-a2d8-4b467e2f70f3

	measure 'FI Type (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Fi Type], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 456b0e03-9b3e-41f0-a437-620878d6390f

	measure 'Issue Dt (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Issue Dt], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		formatString: yyyy-mm-dd
		displayFolder: Security Values
		lineageTag: 7eade2b4-4538-4b26-9e34-1c1c1ec1c2d4

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Private Security Position Title' = ```
			
			VAR maxdate =
			    MAX ( 'Securities Position Fact'[As Of Date] )
			RETURN
			    "Private Security Position" & ", "
			        & SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) & ", "
			        & SELECTEDVALUE ( Framework[Framework Display] ) & ", "
			        & FORMAT ( maxdate, "dd-mmm-yy" )
			
			```
		lineageTag: 5b2b25ad-1ac4-4383-94f6-c7a44259dffe

	measure 'SCD Instrument Type (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[SCD Instrument Type], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 02b3d208-6b10-4204-acf1-a1b16f55a2e7

	measure 'Previous Coupon Date (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Previous Coupon Date], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		formatString: yyyy-mm-dd
		displayFolder: Security Values
		lineageTag: 604dfb97-fbfe-43d2-a065-7fcfe75b8bb8

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'ML Vault ID (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Vault ID], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: fe519e73-b571-4ae5-a684-a8d875f8755b

	measure 'ML Vault Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Vault Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: e08d5102-0d43-4d68-a0b4-89292033a1d2

	measure 'Group Portfolio Manager Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Group Portfolio Manager Name],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 5f14a649-ecfd-4080-a43a-f7060beef190

	measure Nominal = ```
			
			    /*CALCULATE (
			                SUM ( 'Securities Position Fact'[Nominal (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Nominal (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[Nominal (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: 3c4ffa8a-0f75-4cc4-a78e-9a935ac58297

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ID BPL Pricing Strategy (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ID BPL Pricing Strategy], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 33d3eb6a-b0d5-4a8b-983c-bd19ef2e23e9

	measure 'JGAAP Trading Philosophy Code (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[JGAAP Trading Philosophy Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: bb8f55e0-f758-471b-a055-dc3cb179218c

	measure 'USGAAP Trading Philosophy Code (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[USGAAP Trading Philosophy Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 9344e9d9-ba29-450f-8037-155f2aa838f5

	measure 'ML Private Asset ID (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Private Asset ID], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: cccbb4d5-031f-45d0-9c97-534230a5b674

	measure 'Security Name (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Security Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 0ed598ba-2d18-4afb-aaf1-1b31443b07d6

	measure 'AOCI Remain Balance Non BV - Rep (Sec Pos)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[AOCI Remain Balance Non BV - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[AOCI Remain Balance Non BV - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance Non BV - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance Non BV - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*CALCULATE (
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Position Fact'[AOCI Remain Balance Non BV - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Position Fact'[AOCI Remain Balance Non BV - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Position Fact'[AOCI Remain Balance Non BV - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Position Fact'[AOCI Remain Balance Non BV - FUNC] ),
							SUM ( 'Securities Position Fact'[AOCI Remain Balance Non BV - HKD] )
							)
						)
					)
				),
			    FILTER(
			        'Securities Position Fact',
			        'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
				)
			*/
			
			
			```
		lineageTag: 856ac8fc-897d-4465-a751-98973690b85f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Remain Balance Rep - Rep (Sec Pos)' = ```
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[AOCI Remain Balance Rep - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[AOCI Remain Balance Rep - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance Rep - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance Rep - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*CALCULATE (
			IF (
				SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "SCD Base",
				SUM ( 'Securities Position Fact'[AOCI Remain Balance Rep - Base] ),
			    IF (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "USD",
			        SUM ( 'Securities Position Fact'[AOCI Remain Balance Rep - USD] ),
			        IF (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "CAD",
			            SUM ( 'Securities Position Fact'[AOCI Remain Balance Rep - CAD] ),
						IF (
							SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ) = "Company",
							SUM ( 'Securities Position Fact'[AOCI Remain Balance Rep - FUNC] ),
							SUM ( 'Securities Position Fact'[AOCI Remain Balance Rep - HKD] )
							)
						)
					)
				),
			    FILTER(
			        'Securities Position Fact',
			        'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
				)
			*/
			
			```
		lineageTag: 9cc22a58-9bc9-4c4f-b470-8094c3d36502

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Remain Balance BV - Local' = ```
			
			    /*CALCULATE (
			                SUM ( 'Securities Position Fact'[AOCI Remain Balance BV - Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[AOCI Remain Balance BV - Local (D)] ),
			    CALCULATE (
			        SUM ( 'Securities Position Fact'[AOCI Remain Balance BV - Local (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: 06ed3639-b2e6-403e-9fb1-3f8b5eb78419

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Remain Balance Non BV - Local' = ```
			
			  /*  CALCULATE (
			                SUM ( 'Securities Position Fact'[AOCI Remain Balance Non BV - Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[AOCI Remain Balance Non BV - Local (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[AOCI Remain Balance Non BV - Local (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: dbf1236a-275e-4dcc-8544-fc5933bd9188

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AOCI Remain Balance Rep - Local' = ```
			
			   /* CALCULATE (
			                SUM ( 'Securities Position Fact'[AOCI Remain Balance Rep - Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[AOCI Remain Balance Rep - Local (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[AOCI Remain Balance Rep - Local (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: ae083cd8-0959-4614-8392-251934212e37

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Coupon Type (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Coupon Type], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 5afaafcc-5faf-4cd5-88fc-d7daa4cf4f43

	measure 'Legacy Portfolio Code (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Legacy Portfolio Code],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: e50009f9-3b81-4e85-a331-7460fbcba937

	measure 'Current Face (Sec Pos)' = ```
			
			
			    /*CALCULATE (
			        SUM('Securities Position Fact'[Current Face (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Current Face (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[Current Face (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: 502453de-9033-45af-b2c4-f0f032e7e969

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Original Face' = ```
			
			
			    /*CALCULATE (
			        SUM('Securities Position Fact'[Original Face (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Original Face (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[Original Face (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: bd6fe9f8-546e-4160-96c5-bb8736d6f8c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Std Currency (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Std Currency], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 19a42b49-0f2c-4411-b892-1822112fb434

	measure 'Sleeve Manager Team List (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Sleeve Manager Team List],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: dc33fe10-f4a3-4452-98e1-75c8dd993045

	measure 'Maturity Date (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Maturity Date], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		formatString: yyyy-mm-dd
		isHidden
		displayFolder: Security Values
		lineageTag: 74513f9f-8b9c-418a-9272-55aca75a65bd

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Day Count (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Day Count], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: dc5d5bbc-252f-4858-9f34-5de05a974f2e

	measure 'ECL/CECL Impairment - Local (Sec Pos)' =
			
			SUMX(SUMMARIZE('Securities Position Fact',Securities[Asset Class]),
			IF(Securities[Asset Class] IN {"Equity","Other Invested Asset"},[OTTI Impairment - Local (Sec Pos)],[ECL/CECL Impairment - Position Local (Sec Pos)]))+[ECL/CECL Impairment - Adjustment Local (Sec Pos)]
		lineageTag: 2fbf0555-09ee-4ad8-b80d-e550f6a175a3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Purpose Codes (Sec Pos)' = ```
			
			VAR FW =
			    SELECTEDVALUE ( Framework[Framework] )
			RETURN
			    CALCULATE (
			        IF (
			            FW = "IAS39",
			            SELECTEDVALUE ( Portfolios[IAS39 Trading Philosophy Code (D)] ),
			            IF (
			                FW = "USGAAP",
			                SELECTEDVALUE ( Portfolios[USGAAP Trading Philosophy Code (D)] ),
			                IF (
			                    FW = "JGAAP",
			                    SELECTEDVALUE ( Portfolios[JGAAP Trading Philosophy Code (D)] ),
			                    IF (
			                        FW = "IFRS9",
			                        
			                        SELECTEDVALUE ( Portfolios[IFRS Trading Philosophy Code (D)] ),
			                        --(FW= "USTAX" || FW= "NAIC"),
			                        IF (
			                            NOT (
			                                ISEMPTY ( 'Securities Position Fact' )
			                            ),
			                            "AFS"
			                        )
			                    )
			                )
			            )
			        ),
			                FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date]
			                = MAX ( 'Securities Position Fact'[As Of Date] )
			        )
			    )
			
			```
		lineageTag: 14850d14-8632-4195-af4b-6b19ba6cbddf

	measure 'Unrealized Gain/Loss CCY - Local' = ```
			
			/*var rate = SELECTEDVALUE('Securities Position Fact'[Local Exchange Rate]) 
			return
			    CALCULATE (
			                SUM ( 'Securities Position Fact'[Unrealized Gain/Loss CCY - Base])/rate,
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Unrealized Gain/Loss CCY - Local (D)]),
			    CALCULATE( 
			        SUM('Securities Position Fact'[Unrealized Gain/Loss CCY - Local (D)]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: e8a1f731-ad49-4590-b608-1c4e0251d6b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss Sec - Local' = ```
			
			/*var rate = SELECTEDVALUE('Securities Position Fact'[Local Exchange Rate]) 
			return
			    CALCULATE (
			                SUM ( 'Securities Position Fact'[Unrealized Gain/Loss Sec - Base])/rate,
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Unrealized Gain/Loss Sec - Local (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[Unrealized Gain/Loss Sec - Local (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: d2cde7c4-1327-4348-b363-5b5891903f64

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Next Coupon Amount' = ```
			
			   /* CALCULATE (
			                SUM ( 'Securities Position Fact'[Next Coupon Amount (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Next Coupon Amount (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[Next Coupon Amount (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: 75f1ceda-ded8-4222-9a90-fe978cfba56e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Yield' = ```
			
			    /*CALCULATE (
			            SUM ( 'Securities Position Fact'[Current Yield (D)] ),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Current Yield (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[Current Yield (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			```
		lineageTag: e0a37573-7fd4-4e14-8900-e59ed49eac11

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ML Minor Type (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Minor Type], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: e9ef8179-5e84-44ee-bb43-d3facbe5b428

	measure 'Current Timestamp (Sec Pos)' = ```
			
			IF (
			    NOT ISEMPTY ( 'Securities Position Fact' ),
			    NOW (),
			    BLANK ()
			)
			
			```
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		lineageTag: ebbc098e-7035-4cea-8bda-7bc4ced78a1e

	measure 'Inv Lp Port Code (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Inv Lp Port Code (D)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: ae25f6be-a9e1-4f18-9d7c-eea0c6c54e04

	measure 'Lawson Legal ID (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Lawson Legal ID (D)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 3f461001-8f32-4836-9cfe-5f9dc85009dc

	measure 'Liability Surplus (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Liability Surplus (D)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 3fc9e528-96a9-423a-9e13-5d29d5f910ac

	measure 'Custodian Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Custodian Name (D)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 34159006-9526-45cc-bcf1-35e4a3709ff8

	measure 'S&P Short Term Rating (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[S&P Short Term Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: aed822b3-ccd9-4619-a5cd-597ba5921a06

	measure 'Fitch Short Term Rating (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Fitch Short Term Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 9809c3df-9bec-4f4e-b1be-b1e41de0b764

	measure 'Moodys Short Term Rating (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Moodys Short Term Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: df6ef881-a09c-40f9-9e02-318c21f072b3

	measure 'Dbrs (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Dbrs], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: a551c7f0-df4c-4079-ad08-8e7745af4f64

	measure 'Maturity Days (Sec Pos)' = ```
			
			var mat = 
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Maturity Days 2 (D)], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			var calc = 
			IF (
			    mat < 0,
			    mat * -1,
			    mat
			)
			return calc
			
			```
		formatString: 0
		displayFolder: Security Values
		lineageTag: 39b3cbde-3437-4b64-a4d8-3f20003941da

	measure 'Country Of Risk (Sec Pos)' = ```
			
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Country Of Risk], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 1f88eba0-b7e6-42cf-b4da-3a893b79b01a

	measure 'Ultimate Parent Company Name (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Ultimate Parent Company Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: f4920002-5bfc-40cf-aabc-ddd6201b6b63

	measure 'Custodian (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Custodian (D)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 23e199d4-d276-4a09-972d-cb7536b25227

	measure 'Sedol (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Sedol], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: a3a67579-c6e4-4ba3-ae66-1b0bb1046a70

	measure 'MRM Sector (Sec Pos)' = ```
			
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[MRM Sector (Private Sec)], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 9ce10e58-8266-4c4c-b505-27331082714c

	measure 'ML Investment Type Code (Sec Pos)' = ```
			
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Investment Type Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: e8c9ce85-255b-4a88-ac7f-f37d7db81aad

	measure 'Schedule BA Asset Category Code (Sec Pos)' = ```
			
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Schedule BA Asset Category Code], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 1603d5a6-9fcb-4415-8bab-8da808dd1ac5

	measure 'Calm Category (Sec Pos)' = ```
			
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Calm Category], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 617c8479-c278-41f5-9332-665ceda3d5b1

	measure 'On/Off Bal Sheet (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[On/Off Bal Sheet],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: e5e58634-6bd5-4565-badc-c8db3423132e

	measure 'Lawson Legal Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Lawson Legal Name],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 1abfdc50-cefb-418c-84c6-9678a9cdaa5f

	measure 'Primary Asset Type (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Primary Asset Type], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 867d893a-896f-4450-b95e-ef019e8f0f20

	measure 'BICS Level2 Industry Group Desc (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[BICS Level2 Industry Group Desc], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 302c6c05-6aa5-4877-acc7-d43f7aba5fe7

	measure 'BICS Level1 Sector Desc (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[BICS Level1 Sector Desc], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 317fb41f-b41b-49d1-9b32-53a651f9caa2

	measure 'BICS Level3 Industry Desc (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[BICS Level3 Industry Desc], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: b417b037-68ae-429d-ac3d-b3bbd8594974

	measure 'BICS Level4 Sub Industry Desc (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[BICS Level4 Sub Industry Desc], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 27059813-7050-4c13-abee-dc3a48d11a97

	measure 'Country of Incorporation (Sec Pos)' =
			
			CALCULATE (
			 FIRSTNONBLANK ( 'Securities'[Country of Incorporation], TRUE () ),
			 CROSSFILTER ( 'Securities'[Security NK],'Securities Position Fact'[Security NK], BOTH ))
		displayFolder: Security Values
		lineageTag: cc6bb53e-5b28-4660-afd4-4821d4de69d2

	measure 'Issuer Legal Entity Identifier (Sec Pos)' =
			
			CALCULATE (
			 FIRSTNONBLANK ( Entities[Legal Entity Identifier], TRUE () ),
			 CROSSFILTER ( 'Securities'[Entity Join Key],Entities[Entity Join NK], BOTH ),
			 CROSSFILTER ( 'Securities'[Security NK],'Securities Position Fact'[Security NK], BOTH ))
		displayFolder: Security Values
		lineageTag: aea19bd8-933c-4367-b0f8-e7b51682e11d

	measure 'Amortized Cost - Rep (Indo Pos)' = ```
			
			var calc =
			 CALCULATE ( SUM('Securities Position Fact'[Amortized Cost - Base]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
			    )
			RETURN
			    calc
			
			```
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 5723811a-0ffe-4940-b27f-8892d764b939

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Book Value - Rep (Indo Pos)' = ```
			
			var calc =
			 CALCULATE ( SUM('Securities Position Fact'[Book Value - Base]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
			    )
			RETURN
			    calc
			
			```
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 2e7ed261-8032-42bf-bc71-f1ff6e06ca86

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Original Cost - Rep (Indo Pos)' = ```
			
			var calc =
			 CALCULATE ( SUM('Securities Position Fact'[Original Cost - Base]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
			    )
			RETURN
			    calc
			
			```
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 07b53681-9ce5-44c8-a753-7567c2cf8e56

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accrual - Rep (Indo Pos)' = ```
			
			var calc =
			 CALCULATE ( SUM('Securities Position Fact'[Accrual - Base]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] = MAX('Securities Position Fact'[As Of Date])
			        )
			    )
			RETURN
			    calc
			
			```
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: b387cf1d-f5df-430c-bacc-a6d966e44b22

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fair Value Unaccrued - Rep (Indo Pos)' = ```
			
			--SCD Base price * Units
			VAR calc =
			    CALCULATE ( SUMX( 'Securities Position Fact','Securities Position Fact'[Price - Base]  * 'Securities Position Fact'[Units (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date]
			                = MAX ( 'Securities Position Fact'[As Of Date] )
			        )
			    )
			RETURN
			    calc
			
			```
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 54e8d38b-21ae-404b-8ef2-30aefc3efd18

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fair Value Accrued - Rep (Indo Pos)' = ```
			
			--Fair Value Unaccrued Local + Accrual Rep in Base Currency
			VAR calc = 'Securities Position Fact'[Fair Value Unaccrued - Local (Indo Pos)]+'Securities Position Fact'[Accrual - Rep (Indo Pos)]
			RETURN
			    calc
			
			```
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 1bc5503b-48d0-44e3-8622-d6e213d5f018

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Rep (Indo Pos)' = ```
			
			--Fair Value Unaccrued Rep - Book Value Rep in Base Currency
			VAR calc = 'Securities Position Fact'[Fair Value Unaccrued - Rep (Indo Pos)]+'Securities Position Fact'[Book Value - Rep (Indo Pos)]
			RETURN
			    calc
			
			```
		isHidden
		displayFolder: Indonesian Positions Attributes
		lineageTag: 023a7c8a-023f-4e49-a058-83a4c576b884

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GGI Indicator (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Securities'[GGI Indicator],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 07cf2d98-663e-4a8c-a77a-cc3c74121808

	measure 'Is Perpetual (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Securities'[Is Perpetual],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: e6726908-ed0c-42ff-b2e3-e8efba259715

	measure 'Basic Spread (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Securities'[Basic Spread],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 8aae748a-0a5e-4a64-8028-1b314eb37373

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Coupon Typ Reset Dt (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Securities'[Fix To Float Date],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		formatString: yyyy-mm-dd
		displayFolder: Security Values
		lineageTag: 8a74287b-2456-4014-8ecf-bbd5cbf1cf1d

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Analyst Nm (Sec Pos)' = ```
			
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Analyst Nm], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: e803a873-fc80-4b95-9c72-63dc4a1d9436

	measure 'ML NAIC Instrument Type Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML NAIC Instrument Type Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 5ea88ed7-57f1-4c5d-984f-db8c5dec17d7

	measure 'ML Ba Avr Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Ba Avr Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 43127573-1347-4338-b79e-c1acb78eb22d

	measure 'NAIC Designation (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[NAIC Designation], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 39d6f6b4-54e3-42a9-ac35-9f46981f4646

	measure 'ML SD Class Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML SD Class Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 76813763-a9de-447b-8f86-47845974a4fa

	measure 'ML SD Class Desc (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML SD Class Desc], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: dde8e390-8c5e-455a-9376-aba60dacaca5

	measure 'ML SD Type Desc (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML SD Type Desc], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 2ff4b1b0-f2aa-444c-9004-d8218d773152

	measure 'ML SD Subclass Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML SD Subclass Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: ec473886-5acc-4ec7-83a4-a9a7cb43d6db

	measure 'ID Cins (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ID Cins], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 24ef8db2-78ed-4b91-8ee0-9dc5e0b43ef0

	measure 'ML Capital Structure Desc (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Capital Structure Desc], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: ecbb563d-6da5-46e2-a265-2893e5ecc2a4

	measure 'ML Stat Collateral Type Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Stat Collateral Type Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 6204bfe9-e3e4-4dd3-a7b8-d2a4e181eb4a

	measure 'ML Capital Structure Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Capital Structure Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 7a2ddd51-8c97-45b8-a698-7441c92cbe4a

	measure 'ML NAIC Report Part Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML NAIC Report Part Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 6323f40e-caaa-42f0-b5ee-ed5bc8f5ffde

	measure 'NAIC Rating (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[NAIC Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		formatString: 0
		displayFolder: Security Values
		lineageTag: e179afce-84e5-42f2-81da-b8048dfb5b4a

	measure 'ML SD Type Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML SD Type Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: df5da20a-ea27-4a42-9607-985718bc3be4

	measure 'Alm Segment Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Alm Segment Name (D)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: e37a3c02-9b74-42f9-95bc-1435dd431012

	measure 'ML MFC Equivalent Eff Dt (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML MFC Equivalent Eff Dt], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		formatString: yyyy-mm-dd
		displayFolder: Security Values
		lineageTag: 07fdb82e-cecd-4e68-a7f1-db8e7723b796

	measure 'ML Mim Na Rating Eff Dt (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Mim Na Rating Eff Dt], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		formatString: yyyy-mm-dd
		displayFolder: Security Values
		lineageTag: f37c9318-3e36-45ae-b26e-775aaae0e980

	measure 'Primary Rating Effective Dt (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Primary Rating Effective Dt], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		formatString: yyyy-mm-dd
		displayFolder: Security Values
		lineageTag: 005776b8-1ef1-41c0-9cda-5b1e245f42af

	measure 'ML Primary Rating Code (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Primary Rating Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: e3903789-596e-4f3b-8d69-9bc7107de135

	measure 'Alm Segment Currency (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Alm Segment Currency],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: b528ea55-5173-4547-9aa3-a429a9ca041b

	measure 'Amortization/Accretion - Local (Sec Pos)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Int Appr - Local]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Balance Int Appr - Local]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
		lineageTag: fc525aeb-90e0-4976-a137-a787c573f7a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Deferred PL - Local' =
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Deferred PL - Local (D)]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Balance Deferred PL - Local (D)]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
		lineageTag: a2a292fd-cb02-4fca-9546-ccbedaa900c2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Expected Restitution - Local (Sec Pos)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Expected Restitution - Local]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Balance Expected Restitution - Local]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
		lineageTag: 14115239-bcde-4db2-8cc0-cc3a04027703

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Next Payment - Local (Sec Pos)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Next Payment - Local]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Next Payment - Local]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
		lineageTag: 9e0119e2-18dc-4956-8368-41f0d80b1afd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OTTI Impairment - Local (Sec Pos)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Impairment - Local]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Balance Impairment - Local]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
		lineageTag: 19781a99-d760-4f8c-aad4-b7193139e5d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Securities Menu Title' = ```
			
			VAR maxdate =
			    CALCULATE(MAX ( 'Securities Position Fact'[As Of Date]),
			ALL(Period),ALL(Framework))
			RETURN
			    "with data through " & 
			     FORMAT ( maxdate, "dd-MMM-yy" )
			
			```
		lineageTag: 7e99b268-0892-4280-b9b0-de10667fc99e

	measure 'Rep Rate (Sec Pos)' = AVERAGEX( 'Securities Position Fact', 1 * 'Fx Rate DQ'[Rep Rate])
		formatString: 0.000000
		lineageTag: e980f905-1036-44d5-9445-16bb0692ce0f

	measure 'Current Book Value - Local (Sec Pos)' = [Book Value - Local]+[Current Book Value - Adjustment Local (Sec Pos)]
		lineageTag: 2bc22866-49d8-47bb-b289-eabbb9412137

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Book Value - Rep (Sec Pos)' = [Book Value - Rep (Sec Pos)]+[Current Book Value - Adjustment Rep (Sec Pos)]
		lineageTag: 8685887e-afce-4d98-a2d2-b50c5ceb4910

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Units - Rep (Sec Pos)' = ```
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX('Securities Position Fact', 'Securities Position Fact'[Units (D)] *'Securities Position Fact'[Local Exchange Rate]),
			    CALCULATE (
			            SUMX('Securities Position Fact', 'Securities Position Fact'[Units (D)] *'Securities Position Fact'[Local Exchange Rate]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX('Securities Position Fact', 'Securities Position Fact'[Units (D)] *'Fx Rate DQ'[Rep Rate]),
			
			            CALCULATE (
			                    SUMX('Securities Position Fact', 'Securities Position Fact'[Units (D)] *'Fx Rate DQ'[Rep Rate]),
			                LASTDATE('Securities Position Fact'[As Of Date])
			            )
			        ))
			
			```
		lineageTag: 7bdc2c3f-69ff-45d0-b08a-c61c038d4d68

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SR Loan (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[SR Loan], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: beb10a44-e7e4-46ec-b58d-7e52b1dda81b

	measure 'Bpl Issuer (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Bpl Issuer], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 97493d8e-cdc1-4295-b502-91fd5afde82c

	measure 'Balance Write Off - Rep (Sec Pos)' =
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Write Off - Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Balance Write Off - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Write Off - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Write Off - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
		lineageTag: 4e11ce64-d8db-4618-8f29-d69d1bfcdd4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance CL Allowance - Rep (Sec Pos)' =
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance CL Allowance - Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Balance CL Allowance - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance CL Allowance - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance CL Allowance - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
		lineageTag: ac5f2690-341e-409c-8dd9-50d40d74e769

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Recog CL Allowance - Rep (Sec Pos)' =
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Recog CL Allowance - Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Balance Recog CL Allowance - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Recog CL Allowance - Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Recog CL Allowance - Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
		lineageTag: 4f91bc8b-f7af-4c47-a05c-0af3b9942fa3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// For use in Security
	measure 'Asset Portfolio Code (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Portfolios Attributes'[Asset Portfolio Code],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios Attributes'[Portfolio Nk], BOTH )
			)
		displayFolder: Portfolio Attributes
		lineageTag: 6d9c3ad5-d9a4-4684-b845-de804e78b020

	measure 'ML Private/Public Asset ID (Sec Pos)' =
			
			var priv = CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML Private Asset ID], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			var pub = CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Primary Security ID], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			return
			COALESCE(priv,pub)
		displayFolder: Security Values
		lineageTag: 19ec01b7-d67e-48db-9ade-45567fd87c0e

	measure 'Coupon Frequency (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Coupon Frequency], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 83ba2e39-343c-49f2-b424-daf004d5bf1b

	measure '144A Flag (Sec Pos)' = ```
			
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[144A Flag], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 5d51ad56-df7a-4ab8-9c7f-6ec1dd7c6dd2

	measure 'RTG SP LT LC Issuer Credit (Sec Pos)' =
			
			CALCULATE (
			 FIRSTNONBLANK ( Entities[RTG SP LT LC Issuer Credit], TRUE () ),
			 CROSSFILTER ( 'Securities'[Entity Join Key],Entities[Entity Join NK], BOTH ),
			 CROSSFILTER ( 'Securities'[Security NK],'Securities Position Fact'[Security NK], BOTH ))
		displayFolder: Security Values
		lineageTag: 8f3240ce-37d8-40dd-b861-334dd5a0df07

	measure 'Int Acc Date (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Int Acc Date], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		formatString: yyyy-mm-dd
		displayFolder: Security Values
		lineageTag: ff58b2d7-e81b-4dd5-951d-9cf7b563ee02

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'State Code (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[State Code], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: f167318f-aab2-420d-8e3d-ed01b027d9cf

	measure 'NAIC Deposit Category (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[NAIC Deposit Category], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		displayFolder: Security Values
		lineageTag: 1f1ea33f-6276-4621-a692-7a678077b9ff

	measure 'Final Maturity Date (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Final Maturity Date], TRUE () ),
			    CROSSFILTER ( 'Securities Lots Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		formatString: yyyy-mm-dd
		displayFolder: Security Values
		lineageTag: 93011281-d542-48d5-93e7-095c171c6e4b

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Country a' = ```
			
			if(sum('Securities Position Fact'[Country_Blank_nk])>0, 
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			         max( 'Securities Position Fact'[SCD Country] ),
			    CALCULATE( 
			        max( 'Securities Position Fact'[SCD Country]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),BLANK())
			```
		isHidden
		lineageTag: bf9101ff-a979-44c0-8e52-5b91559e7372

	measure 'Issuer Long Comp Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Issuer Long Comp Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 483b826c-0410-49ca-9448-7908e633ae88

	measure 'Country (Sec Pos)' =
			
			CALCULATE (
			FIRSTNONBLANK ( 'Securities'[Country], TRUE () ),
			CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: e92f7bcc-deef-400c-802e-d50a8dbd643a

	measure 'Mid Price (Sec Pos)' =
			
			CALCULATE (SUM('Securities'[Mid Price]),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 63b79211-31b6-48a7-82ee-6573cb0c101e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bid Price (Sec Pos)' =
			
			CALCULATE (SUM('Securities'[Bid Price]),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: c1ee328e-ec11-4c8c-ad45-545f0afb5a44

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Last Price (Sec Pos)' =
			
			CALCULATE (SUM('Securities'[Indonesian Price]),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: d7fd8bfa-117c-48e3-baab-a8b6a688cda4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ask Price (Sec Pos)' =
			
			CALCULATE (SUM('Securities'[Ask Price]),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 1b69f473-1cc9-456f-8d58-d41de8994335

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ml Pricing (Sec Pos)' =
			
			CALCULATE (FIRSTNONBLANK('Securities'[Ml Pricing Source],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 7c85d0f2-772f-449a-a311-9fb936b18f99

	measure 'MRM Industry Group Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Industry Group Name], TRUE () ),
			    'Securities Position Fact'
			)
		lineageTag: f141b521-8f01-4e2b-9545-0f265f15ece3

	measure 'MRM Industry Sector Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Industry Sector Name], TRUE () ),
			    'Securities Position Fact'
			)
		lineageTag: 63a92111-87af-4ea7-8980-485aa3d9e086

	measure 'MRM Industry Subgroup Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Industry Subgroup Name], TRUE () ),
			    'Securities Position Fact'
			)
		lineageTag: 5ef7dbcd-39e7-4394-b5a0-ddb6b897d952

	measure 'MRM Sector Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Sector Name], TRUE () ),
			    'Securities Position Fact'
			)
		lineageTag: 705a3f55-da63-42e1-98c3-fbc388a4e639

	measure 'Income Impairment - Local (Sec Pos)' =
			
			IF (
			    COUNTROWS ( 'Securities Position Fact' ) > 0,
			    CALCULATE (
			        SUM ( 'Securities Transaction GA Fact'[Book Value - Local unsigned] ) * -1,
			        //Step1: Identify the impairments for the position
			        TREATAS (
			            VALUES ( 'Securities Position Fact'[Src Position ID] ),
			            'Securities Transaction GA Fact'[POS Trans Link]
			        ),
			        'Securities Transaction GA Fact'[Bus Trans Code] = "TaxLotCorr",
			        'Securities Transaction GA Fact'[Transaction Purpose]
			            IN { "Income Impairment Reversal", "Income Impairment" },
			        'Securities Transaction GA Fact'[Trans Status] = "Active",
			        //Step2: Aggregate the cummulative impairment for the position
			        FILTER (
			            ALL ( Period[Date] ),
			            Period[Date] <= MAX ( Period[Date] )
			        ),
			        ALLSELECTED ( Securities ),
			        VALUES ( Securities[Primary Security ID] )
			    )
			)
		lineageTag: 6da94c57-e7f0-45c5-b1da-504327b38373

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income Impairment - Rep (Sec Pos)' =
			
			IF (
			    COUNTROWS ( 'Securities Position Fact' ) > 0,
			    CALCULATE (
			        SWITCH (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			            "SCD Base", SUM ( 'Securities Transaction GA Fact'[Book Value - Base unsigned] ) * -1,
			            SUMX (
			                'Securities Transaction GA Fact',
			                'Securities Transaction GA Fact'[Book Value - Local unsigned] * [Rep Rate]
			            ) * -1
			        ),
			        //Step1: Identify the impairments for the position
			        TREATAS (
			            VALUES ( 'Securities Position Fact'[Src Position ID] ),
			            'Securities Transaction GA Fact'[POS Trans Link]
			        ),
			        'Securities Transaction GA Fact'[Bus Trans Code] = "TaxLotCorr",
			        'Securities Transaction GA Fact'[Transaction Purpose]
			            IN { "Income Impairment Reversal", "Income Impairment" },
			        'Securities Transaction GA Fact'[Trans Status] = "Active",
			        //Step2: Aggregate the cummulative impairment for the position
			        FILTER (
			            ALL ( Period[Date] ),
			            Period[Date] <= MAX ( Period[Date] )
			        ),
			        ALLSELECTED ( Securities ),
			        VALUES ( Securities[Primary Security ID] )
			    )
			)
		lineageTag: 95bb2fe5-654a-4c1e-bc68-148810bb8180

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Is PublicPP Ind (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[Is PublicPP Ind], TRUE () ),
			    'Securities Position Fact'
			)
			
			```
		lineageTag: 1fc54b00-6d96-4481-a17f-94624343f3bc

	measure 'Unsettled Int Div Amount - Rep' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Unsettled Int Div Amount Base CCY]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Unsettled Int Div Amount Base CCY]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unsettled Int Div Amount Local CCY] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unsettled Int Div Amount Local CCY] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )))
		lineageTag: cb79590c-d142-43f4-9321-f58fcecb15a1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Deposit Rate (Sec Pos)' =
			
			CALCULATE (
			    Sum( Securities[SCD Deposit Rate]),
			    'Securities Position Fact'
			)
		lineageTag: 4ed9e3f1-cce0-4649-9b7b-57fb4ca8d357

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Book Value - Adjustment Local (Sec Pos)' = ```
			
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//          'CAT Adjmt Config Table'[Measure Name] ="Book Value")
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// RETURN 
			// SUMX(summarize('Securities Position Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			//  CALCULATE(SUM('Securities GL Txn fact'[Local Txn Amt]),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  vDateRange
			//      )
			// )
			// )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Book Value"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SUM ( 'Consolidated GL Balance Fact'[Local Balance Amt] ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: fe51173d-7047-4a74-b7a2-969d807e8a1c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Book Value - Adjustment Rep (Sec Pos)' = ```
			
			// VAR vSelectedCurrency = SELECTEDVALUE ('Reporting Currency'[Rep In Currency])
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//          'CAT Adjmt Config Table'[Measure Name] ="Book Value")
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// VAR vResult= 
			// SUMX(summarize('Securities Position Fact',Securities[Primary Security ID]),
			// IF(CALCULATE(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			//     CALCULATE( 
			//      SWITCH (
			//              vSelectedCurrency,
			//              "CAD",[Adjustment Amount (CAD)],
			//                 "USD",[Adjustment Amount (USD)],
			//                 "HKD",[Adjustment Amount (HKD)],
			//                 [Adjustment Amount (Func)]
			//      ),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  vDateRange
			//  )
			// )
			// )
			// RETURN VResult
			VAR vSelectedCurrency =
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] )
			VAR vListofGLAccts =
			    CALCULATETABLE (
			        VALUES ( 'CAT Adjmt Config Table'[GL Acct Num] ),
			        'CAT Adjmt Config Table'[Measure Name] = "Book Value"
			    )
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SWITCH (
			                    vSelectedCurrency,
			                    "CAD", [Adjustment_Amount (CAD)],
			                    "USD", [Adjustment_Amount (USD)],
			                    "HKD", [Adjustment_Amount (HKD)],
			                    [Adjustment_Amount (Func)]
			                ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: 4fc3f1e8-80df-4aec-acd0-95d193435dc6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Book Value - Position Local (Sec Pos)' =
			
			/*'Securities Position Fact'[Book Value - Local]+'Securities Position Fact'[AOCI Remain Balance BV - Local]+ 'Securities Position Fact'[OTTI Impairment - Local (Sec Pos)]*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Adjusted Book Value Local] ),
			    CALCULATE (
			        SUM ( 'Securities Position Fact'[Adjusted Book Value Local] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
		isHidden
		lineageTag: 7752c94b-8dc2-4802-84ce-12316f265106

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Book Value - Position Rep (Sec Pos)' =
			
			/*'Securities Position Fact'[Book Value - Rep (Sec Pos)]+'Securities Position Fact'[AOCI Remain Balance BV - Rep (Sec Pos)]+ 'Securities Position Fact'[OTTI Impairment - Rep (Sec Pos)]*/
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Adjusted Book Value Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Adjusted Book Value Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Adjusted Book Value Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Adjusted Book Value Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
		isHidden
		lineageTag: e8b0d713-8f46-49ab-9f0c-e7c715859e87

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ECL/CECL Impairment - Adjustment Local (Sec Pos)' = ```
			
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//          'CAT Adjmt Config Table'[Measure Name] ="ECL Impairment")
			
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// RETURN 
			// SUMX(summarize('Securities Position Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			//  CALCULATE(SUM('Securities GL Txn fact'[Local Txn Amt]),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  vDateRange
			//      )
			// )
			// )
			VAR vListofGLAccts=CALCULATETABLE(
			            VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			            'CAT Adjmt Config Table'[Measure Name] ="ECL Impairment")
			
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SUM ( 'Consolidated GL Balance Fact'[Local Balance Amt] ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: f393389f-3ec9-4819-bd36-d7bca158eeac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ECL/CECL Impairment - Adjustment Rep (Sec Pos)' = ```
			
			// VAR vSelectedCurrency = SELECTEDVALUE ('Reporting Currency'[Rep In Currency])
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//          'CAT Adjmt Config Table'[Measure Name] ="ECL Impairment")
			
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// VAR vResult= 
			// SUMX(summarize('Securities Position Fact',Securities[Primary Security ID]),
			// IF(CALCULATE(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			//     CALCULATE( 
			//      SWITCH (
			//              vSelectedCurrency,
			//              "CAD",[Adjustment Amount (CAD)],
			//                 "USD",[Adjustment Amount (USD)],
			//                 "HKD",[Adjustment Amount (HKD)],
			//                 [Adjustment Amount (Func)]
			//      ),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  vDateRange
			//  )
			// )
			// )
			// RETURN VResult
			VAR vSelectedCurrency = SELECTEDVALUE ('Reporting Currency'[Rep In Currency])
			VAR vListofGLAccts=CALCULATETABLE(
			            VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			            'CAT Adjmt Config Table'[Measure Name] ="ECL Impairment")
			
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SWITCH (
			                    vSelectedCurrency,
			                    "CAD", [Adjustment_Amount (CAD)],
			                    "USD", [Adjustment_Amount (USD)],
			                    "HKD", [Adjustment_Amount (HKD)],
			                    [Adjustment_Amount (Func)]
			                ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: fe638a0a-747e-469a-bf21-bb4b34b7e8f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ECL/CECL Impairment - Position Local (Sec Pos)' = ```
			
			
			SWITCH(SELECTEDVALUE ( Framework[Framework] ),
			"IFRS9",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			            SUM ( 'Securities Position Fact'[Balance CL Allowance - Local] )
			            + SUM ( 'Securities Position Fact'[Balance Write Off - Local] ),
			    CALCULATE (
			                SUM ( 'Securities Position Fact'[Balance CL Allowance - Local] )
			            + SUM ( 'Securities Position Fact'[Balance Write Off - Local] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )),
			"USGAAP",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			        SUM ( 'Securities Position Fact'[Balance Recog CL Allowance - Local] )
			            + SUM ( 'Securities Position Fact'[Balance Write Off - Local] ),
			    CALCULATE (
			        SUM ( 'Securities Position Fact'[Balance Recog CL Allowance - Local] )
			            + SUM ( 'Securities Position Fact'[Balance Write Off - Local] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )),
			"IAS39",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			        SUM ( 'Securities Position Fact'[Balance Impairment - Local] )
			            + SUM ( 'Securities Position Fact'[Balance Write Off - Local] ),
			    CALCULATE (
			        SUM ( 'Securities Position Fact'[Balance Impairment - Local] )
			            + SUM ( 'Securities Position Fact'[Balance Write Off - Local] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )),
			"JGAAP",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			        SUM ( 'Securities Position Fact'[Balance Impairment - Local] )
			            + SUM ( 'Securities Position Fact'[Balance Write Off - Local] ),
			    CALCULATE(
			        SUM ( 'Securities Position Fact'[Balance Impairment - Local] )
			            + SUM ( 'Securities Position Fact'[Balance Write Off - Local] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )),
			"NAIC",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			        SUM ( 'Securities Position Fact'[Balance Impairment - Local] )
			            + SUM ( 'Securities Position Fact'[Balance Write Off - Local] ),
			    CALCULATE (
			        SUM ( 'Securities Position Fact'[Balance Impairment - Local] )
			            + SUM ( 'Securities Position Fact'[Balance Write Off - Local] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    ))
			,BLANK())
			/*VAR FW =
			    SELECTEDVALUE ( Framework[Framework] )
			VAR IFRS9_FW =
			    CALCULATE (
			        SUM ( 'Securities Position Fact'[Balance CL Allowance - Local] )
			            + SUM ( 'Securities Position Fact'[Balance Write Off - Local] ),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )
			VAR USGAAP_FW =
			    CALCULATE (
			        SUM ( 'Securities Position Fact'[Balance Recog CL Allowance - Local] )
			            + SUM ( 'Securities Position Fact'[Balance Write Off - Local] ),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )
			VAR IAS39_JGAAP_NAIC_FW =
			    CALCULATE (
			        SUM ( 'Securities Position Fact'[Balance Impairment - Local] )
			            + SUM ( 'Securities Position Fact'[Balance Write Off - Local] ),
			       FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )
			RETURN
			    IF (
			        FW = "IFRS9",
			        IFRS9_FW,
			        IF (
			            FW = "USGAAP",
			            USGAAP_FW,
			            IF (
			                ( FW = "IAS39"
			                    || FW = "JGAAP"
			                    || FW = "NAIC" ),
			                IAS39_JGAAP_NAIC_FW,
			                BLANK ()
			            )
			        )
			    )*/
			
			```
		lineageTag: b5215e16-19ce-4c71-8890-2487771a8d7d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ECL/CECL Impairment - Position Rep (Sec Pos)' = ```
			
			VAR FW =
			    SELECTEDVALUE ( Framework[Framework] )
			VAR IFRS9_FW = 'Securities Position Fact'[Balance CL Allowance - Rep (Sec Pos)] + 'Securities Position Fact'[Balance Write Off - Rep (Sec Pos)]
			VAR USGAAP_FW = 'Securities Position Fact'[Balance Recog CL Allowance - Rep (Sec Pos)] + 'Securities Position Fact'[Balance Write Off - Rep (Sec Pos)]
			VAR IAS39_JGAAP_NAIC_FW = 'Securities Position Fact'[OTTI Impairment - Rep (Sec Pos)] + 'Securities Position Fact'[Balance Write Off - Rep (Sec Pos)]
			RETURN
			    SWITCH(
			        TRUE(),
			        FW = "IFRS9",IFRS9_FW,
			        FW = "USGAAP",USGAAP_FW,
			        FW = "IAS39"|| FW = "JGAAP"|| FW = "NAIC",IAS39_JGAAP_NAIC_FW,
			        BLANK ()    
			    )
			
			```
		lineageTag: 52da3671-e662-43ef-99d3-872f483924bc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accrual - Position Local' = ```
			
			    /*CALCULATE (
			                SUM ( 'Securities Position Fact'[Accrual - Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Accrual - Local (D)] ),
			    CALCULATE( 
			        SUM ( 'Securities Position Fact'[Accrual - Local (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			
			```
		lineageTag: 5fed799e-abfb-4dd1-ad1a-2b4964a57325

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accrual - Position Rep' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Accrual - Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Accrual - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Accrual - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Accrual - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*VAR maxd =
			    MAX ( 'Securities Position Fact'[As Of Date] )
			VAR calc =
			    SWITCH (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			        "USD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Accrual - USD]),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "CAD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Accrual - CAD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "HKD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Accrual - HKD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "Company",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Accrual - FUNC] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "SCD Base",
			            CALCULATE (
			                SUM( 'Securities Position Fact'[Accrual - Base] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            )
			    )
			RETURN
			    calc
			)*/
		lineageTag: 26450546-0574-4eba-9c14-250778b25357

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accrual - Adjustment Local' = ```
			
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//          'CAT Adjmt Config Table'[Measure Name] ="Accrual")
			
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// RETURN 
			// SUMX(summarize('Securities Position Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			//  CALCULATE(SUM('Securities GL Txn fact'[Local Txn Amt]),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  vDateRange
			//      )
			// )
			// )
			VAR vListofGLAccts=CALCULATETABLE(
			            VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			            'CAT Adjmt Config Table'[Measure Name] ="Accrual")
			
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SUM ( 'Consolidated GL Balance Fact'[Local Balance Amt] ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: 8ffe363d-4c93-4833-aef7-0b458fbf7c6d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accrual - Adjustment Rep' = ```
			
			// VAR vSelectedCurrency = SELECTEDVALUE ('Reporting Currency'[Rep In Currency])
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//          'CAT Adjmt Config Table'[Measure Name] ="Accrual")
			
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// VAR vResult= 
			// SUMX(summarize('Securities Position Fact',Securities[Primary Security ID]),
			// IF(CALCULATE(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			//     CALCULATE( 
			//      SWITCH (
			//              vSelectedCurrency,
			//              "CAD",[Adjustment Amount (CAD)],
			//                 "USD",[Adjustment Amount (USD)],
			//                 "HKD",[Adjustment Amount (HKD)],
			//                 [Adjustment Amount (Func)]
			//      ),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  vDateRange
			//  )
			// )
			// )
			// RETURN VResult
			VAR vSelectedCurrency = SELECTEDVALUE ('Reporting Currency'[Rep In Currency])
			VAR vListofGLAccts=CALCULATETABLE(
			            VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			            'CAT Adjmt Config Table'[Measure Name] ="Accrual")
			
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SWITCH (
			                    vSelectedCurrency,
			                    "CAD", [Adjustment_Amount (CAD)],
			                    "USD", [Adjustment_Amount (USD)],
			                    "HKD", [Adjustment_Amount (HKD)],
			                    [Adjustment_Amount (Func)]
			                ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: 4ea0ee6e-4171-4cd1-a66e-cce2f731f619

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Position Local' = ```
			
			   /* CALCULATE (
			                SUM ( 'Securities Position Fact'[Unrealized Gain/Loss - Local (D)]),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date] =  MAX('Securities Position Fact'[As Of Date])
			        )
			    )*/
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM ( 'Securities Position Fact'[Unrealized Gain/Loss - Local (D)] ),
			    CALCULATE (
			        SUM ( 'Securities Position Fact'[Unrealized Gain/Loss - Local (D)] ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
			```
		lineageTag: e3be357d-c703-4a8d-a071-d18223b44b0e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Position Rep (Sec Pos)' = ```
			
			  SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Unrealized Gain/Loss - Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Unrealized Gain/Loss - Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			 IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss - Local (D)] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
			/*VAR maxd =
			    MAX ( 'Securities Position Fact'[As Of Date] )
			VAR calc =
			    SWITCH (
			        SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			        "USD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Unrealized Gain/Loss - USD]),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "CAD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Unrealized Gain/Loss - CAD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "HKD",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Unrealized Gain/Loss - HKD] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "Company",
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Unrealized Gain/Loss - FUNC] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            ),
			        "SCD Base",
			            CALCULATE (
			                SUM( 'Securities Position Fact'[Unrealized Gain/Loss - Base] ),
			                FILTER (
			                    'Securities Position Fact',
			                    'Securities Position Fact'[As Of Date] = maxd
			                )
			            )
			    )
			RETURN
			    calc*/
			
			```
		lineageTag: dffa7ab4-464f-400e-8bf1-a7a0e3926ba2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Adjustment Rep (Sec Pos)' = ```
			
			// VAR vSelectedCurrency = SELECTEDVALUE ('Reporting Currency'[Rep In Currency])
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//          'CAT Adjmt Config Table'[Measure Name] ="Unrealized")
			
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// VAR vResult= 
			// SUMX(summarize('Securities Position Fact',Securities[Primary Security ID]),
			// IF(CALCULATE(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			//     CALCULATE( 
			//      SWITCH (
			//              vSelectedCurrency,
			//              "CAD",[Adjustment Amount (CAD)],
			//                 "USD",[Adjustment Amount (USD)],
			//                 "HKD",[Adjustment Amount (HKD)],
			//                 [Adjustment Amount (Func)]
			//      ),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  vDateRange
			//  )
			// )
			// )
			// RETURN VResult
			VAR vSelectedCurrency = SELECTEDVALUE ('Reporting Currency'[Rep In Currency])
			VAR vListofGLAccts=CALCULATETABLE(
			            VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			            'CAT Adjmt Config Table'[Measure Name] ="Unrealized")
			
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SWITCH (
			                    vSelectedCurrency,
			                    "CAD", [Adjustment_Amount (CAD)],
			                    "USD", [Adjustment_Amount (USD)],
			                    "HKD", [Adjustment_Amount (HKD)],
			                    [Adjustment_Amount (Func)]
			                ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: 3c2855ea-09ec-47d8-ad14-c55fcfd52e22

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unrealized Gain/Loss - Adjustment Local' = ```
			
			// VAR vListofGLAccts=CALCULATETABLE(
			//             VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			//          'CAT Adjmt Config Table'[Measure Name] ="Unrealized")
			
			// VAR vMaxSelectedDate=MAX(Period[Date])
			// VAR vDateRange = FILTER(ALL(Period[Date]),Period[Date]<=vMaxSelectedDate)
			// RETURN 
			// SUMX(summarize('Securities Position Fact',Securities[Primary Security ID]),
			// IF(calculate(COUNTROWS('Securities GL Txn fact'),vDateRange)>0 && (NOT ISBLANK(Securities[Primary Security ID])),
			//  CALCULATE(SUM('Securities GL Txn fact'[Local Txn Amt]),
			//  TREATAS(vListOfGLAccts,'Securities GL Txn fact'[Account]),
			//  vDateRange
			//      )
			// )
			// )
			VAR vListofGLAccts=CALCULATETABLE(
			            VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			            'CAT Adjmt Config Table'[Measure Name] ="Unrealized")
			
			VAR vMaxSelectedDate =
			    MAX ( Period[Date] )
			VAR vMaxAsOfPeriod =
			    MAX ( 'Consolidated GL Balance Fact'[As of Period] )
			RETURN
			    IF (
			        ISEMPTY (
			            CALCULATETABLE (
			                'Consolidated GL Balance Fact',
			                Period[Date] = vMaxSelectedDate
			            )
			        ),
			        BLANK (),
			        SUMX (
			            VALUES ( Securities[Primary Security ID] ),
			            CALCULATE (
			                SUM ( 'Consolidated GL Balance Fact'[Local Balance Amt] ),
			                TREATAS ( vListOfGLAccts, 'Consolidated GL Balance Fact'[GL Acct (6 digits)] ),
			                Period[Date] = vMaxSelectedDate,
			                'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			            )
			        )
			    )
			```
		lineageTag: 6c6b96ec-77bb-4001-bf0f-c7c2483854fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reset Freq Description (Sec Pos)' =
			
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[Reset Freq Description], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 2736c6e3-dfd6-476b-8412-148f8709a974

	measure 'Yield For Math Adj (Sec Pos)' =
			
			CALCULATE(
			MAX('Securities Transaction GA Fact'[Yield For Math Adj]),
			TREATAS(
			VALUES('Securities Position Fact'[Src Position ID]),'Securities Transaction GA Fact'[POS Trans Link]
			))
		isHidden
		lineageTag: 5c7f9050-b440-4782-b33f-5dcb8ae163b9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Acquisition Pre Dis Local' =
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Acquisition Pre Dis Local CCY]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Balance Acquisition Pre Dis Local CCY]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
		lineageTag: 00c3ab4a-177e-48d2-9092-6ac7658d9129

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Acquisition Pre Dis Rep' = ```
			
			SWITCH (
			    SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			    "SCD Base",
			        IF (
			            ISFILTERED ( 'Period'[Date] ),
			            SUM ( 'Securities Position Fact'[Balance Acquisition Pre Dis Base CCY] ),
			            CALCULATE (
			                SUM ( 'Securities Position Fact'[Balance Acquisition Pre Dis Base CCY] ),
			                LASTDATE ( 'Securities Position Fact'[As Of Date] )
			            )
			        ),
			    IF (
			        ISFILTERED ( 'Period'[Date] ),
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Acquisition Pre Dis Local CCY] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        CALCULATE (
			            SUMX (
			                'Securities Position Fact',
			                'Securities Position Fact'[Balance Acquisition Pre Dis Local CCY] * 'Fx Rate DQ'[Rep Rate]
			            ),
			            LASTDATE ( 'Securities Position Fact'[As Of Date] )
			        )
			    )
			)
			
			```
		lineageTag: 739e821b-edc2-4a47-9f87-c1135addf70c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Book Value Native - Local (Sec Pos)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Book Value Local Native]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Balance Book Value Local Native]),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		lineageTag: b5564091-2317-4095-b49d-893e0c03a210

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Book Value Native - Rep (Sec Pos)' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Book Value Base Native]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Balance Book Value Base Native]),
			        LASTDATE ( 'Securities Lots Fact'[As Of Date] )
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Book Value Local Native] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Book Value Local Native] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			))
		lineageTag: 00107884-f7f1-4abb-97e4-8eb0796c4a2c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NAIC Private Placement Indicator' = SWITCH(TRUE(),'Securities Position Fact'[144A Flag (Sec Pos)]=="Y","144A",'Securities Position Fact'[Private Placement (Sec Pos)] =="Y","PRIVATE")
		lineageTag: a038681e-f72f-4288-8dab-a12a1cd85d27

	measure 'Wash Sale Parent Security Id(Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Wash Sale Parent Security Id], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 88f25d4b-fa82-4353-8a1a-440b972f9039

	measure 'ML LICAT Inferred Rating (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[ML LICAT Inferred Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 644e774b-0a09-4ae6-971e-17347c8b5d9d

	measure 'ML MFC Equivalent Rating (Sec Pos)' =
			CALCULATE(
			    FIRSTNONBLANK(Securities[ML MFC Equivalent Rtg],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH ))
		displayFolder: Security Values
		lineageTag: c0727f83-d740-4f86-8c10-e5fb531e75f3

	measure 'Endorsement Indicator (Sec Pos)' =
			calculate(FIRSTNONBLANK('Securities'[Endorsement Indicator],TRUE () ),
			CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 44f98042-7917-4da6-a064-e3dad559e0cf

	measure 'ML IRR Rating (Sec Pos)' =
			CALCULATE(
			    FIRSTNONBLANK(Securities[ML IRR Rating (Adj)],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH ))
		displayFolder: Security Values
		lineageTag: 169026bf-b3ab-459f-86e3-3ef93c471268

	measure 'Position Book Yield(Sec Pos)' = ```
			
			Var vListOfPositions = VALUES('Securities Position Fact'[Src Position ID])
			/*var  vNominalYield= 
			CALCULATE(
			    SUMX('Securities Lots Fact','Securities Lots Fact'[Nominal]*'Securities Lots Fact'[Yield For Math Adj]),
			    value('Securities Lots Fact'[Src Positions ID]) IN vListOfPositions
			)*/
			var  vBookYield =
			CALCULATE(
			    SUMX('Securities Lots Fact','Securities Lots Fact'[Book Value - Local]*'Securities Lots Fact'[Yield For Math Adj]),
			    value('Securities Lots Fact'[Src Positions ID]) IN vListOfPositions
			)
			/*VAR vNominal=
			CALCULATE(
			    SUM('Securities Lots Fact'[Nominal]),
			    value('Securities Lots Fact'[Src Positions ID]) IN vListOfPositions
			)*/
			VAR vBook=
			CALCULATE(
			    SUM('Securities Lots Fact'[Book Value - Local]),
			    value('Securities Lots Fact'[Src Positions ID]) IN vListOfPositions
			)
			RETURN
			DIVIDE(vBookYield,vBook)
			```
		lineageTag: 43cfa20a-403f-42a6-a115-f9f9daba00eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Country of Issue - Long(Sec Pos)' =
			
			CALCULATE(
			    FIRSTNONBLANK(Securities[Country of Issue - Long],TRUE()),
			    CROSSFILTER('Securities Position Fact'[Security NK],'Securities'[Security NK],BOTH))
		lineageTag: 89c0877a-0516-401c-b606-c9821daf846b

	measure 'Country of Issue - Short(Sec Pos)' =
			
			CALCULATE(
			    FIRSTNONBLANK(Securities[Country of Issue - Short],TRUE()),
			    CROSSFILTER('Securities Position Fact'[Security NK],'Securities'[Security NK],BOTH))
		lineageTag: de5cd658-02e4-41c3-b793-175fc2f8fa33

	measure 'Effective Date Format (Sec Pos)' = FORMAT(SELECTEDVALUE('Securities Position Fact'[As Of Date]),"YYYYMMDD")
		lineageTag: ece67989-a680-459b-a24d-76704acc9562

	measure 'SCD Framework (Sec Pos)' =
			
			var fw = SELECTEDVALUE('Securities Lots Fact'[Framework Code])
			return
			IF(fw = "NAIC","STAT",fw)
		lineageTag: 561e0308-dd19-46fe-ac28-e3e013994a49

	measure 'JGAAP Impairment (Sec Pos)' = IF(SELECTEDVALUE(Framework[Framework])="JGAAP","IMPAIRMENT",BLANK())
		lineageTag: f7859280-b7a5-4210-a02a-20317da27ddc

	measure 'Impairment Amount Allowed (Sec Pos)' = ```
			
			var bv = SELECTEDVALUE('Book Values'[Book Values])
			var curr = SELECTEDVALUE('Securities Position Fact'[Local])
			return
			SWITCH(TRUE(),
			bv = "Original Book Value" && curr in {"IDR","JPY","KRW","VND"}, 
			    ROUND(SUM('Securities Position Fact'[Fair Value Unaccrued - Local (D)])-SUM('Securities Position Fact'[Original Cost - Local (D)]),0),
			bv = "Original Book Value",
			    SUM('Securities Position Fact'[Fair Value Unaccrued - Local (D)])-SUM('Securities Position Fact'[Original Cost - Local (D)]),
			curr in {"IDR","JPY","KRW","VND"},
			    ROUND(SUM('Securities Position Fact'[Fair Value Unaccrued - Local (D)])-SUM('Securities Position Fact'[Book Value - Local (D)]),0),
			SUM('Securities Position Fact'[Fair Value Unaccrued - Local (D)])-SUM('Securities Position Fact'[Book Value - Local (D)]))
			```
		lineageTag: df943b21-17e6-49ea-a438-2f5bbe8c563b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Impairment Amount Allowed - Rep (Sec Pos)' =
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    [Impairment Amount Allowed (Sec Pos)],
			    CALCULATE (
			[Impairment Amount Allowed (Sec Pos)],
			LASTDATE ( 'Securities Position Fact'[As Of Date] )
			)
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        [Impairment Amount Allowed (Sec Pos)] * [Rep Rate (IS)]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            [Impairment Amount Allowed (Sec Pos)] *  [Rep Rate (IS)]
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			))
		lineageTag: 185c8fc4-b234-4381-b87d-a1c46e647ad5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Impairment Loss (OTTI Sec Pos)' = ```
			
			var frmwrk = SELECTEDVALUE(Framework[Framework])
			VAR ias39 = SELECTEDVALUE('Securities Position Fact'[Original Cost - Local (D)])- SELECTEDVALUE('Securities Position Fact'[Fair Value Unaccrued - Local (D)])
			var naic_jgaap = SELECTEDVALUE('Securities Position Fact'[Book Value - Base])-SELECTEDVALUE('Securities Position Fact'[Fair Value Unaccrued - Local (D)])
			var calc = IF(frmwrk = "IAS39", ias39, naic_jgaap)
			return calc
			
			```
		lineageTag: e5ad9bac-d69f-4c83-8ac0-9ea2bd321b32

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Impairment Loss Allowed (Sec Pos)' = SELECTEDVALUE('Securities Position Fact'[Book Value - Base]) - SELECTEDVALUE('Securities Position Fact'[Fair Value Unaccrued - Local (D)])
		lineageTag: 1a3bfe7a-dcad-4c4d-997d-8b4d20fa8d7b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Impairment Amount QC (Sec Pos)' = ```
			
			VAR curr = 
			SELECTEDVALUE('Securities Position Fact'[Local])
			VAR activity =
			    SELECTEDVALUE ( 'Impairment Slicer'[Values] )
			VAR target =
			    SWITCH(TRUE(),
			    NOT curr IN {"KRW","VND","JPY","IDR"},
			        SELECTEDVALUE(  'Securities Position Fact'[Nominal (D)] ) * (1-SELECTEDVALUE ( 'Target Loss'[Loss Percent] )/100),
			        ROUND(SELECTEDVALUE(  'Securities Position Fact'[Nominal (D)] ) * (1-SELECTEDVALUE ( 'Target Loss'[Loss Percent] )/100),0))
			
			VAR BV =
			    SUM ( 'Securities Position Fact'[Book Value - Base] )
			VAR calc =
			    IF (
			        activity = "Credit Impairment",
			        BV - target,
			        IF (
			            activity = "Credit Recovery",
			            target - BV,
			            SELECTEDVALUE( 'Securities Position Fact'[Fair Value Unaccrued - Local (D)] ) - BV
			        )
			    )
			RETURN
			    calc
			```
		lineageTag: f258bbfa-ae6f-4e77-888e-a7358a2281a8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ratio of Local FV / BV (Sec Pos)' =
			
			DIVIDE(SUM ( 'Securities Position Fact'[Fair Value Unaccrued - Local (D)] ),SUM ( 'Securities Position Fact'[Original Cost - Local (D)] ),0)
		lineageTag: 3567e7a1-8440-4728-837f-52ef1e79b3ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Percentage Difference (Sec Pos)' =
			
			DIVIDE(
			    SUM('Securities Position Fact'[Fair Value Unaccrued - Local (D)])-SUM('Securities Position Fact'[Book Value - Local (D)]),
			    SUM('Securities Position Fact'[Book Value - Local (D)]),0)
		lineageTag: f44ea8e5-dcb3-4377-af34-84b78e884ead

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Decline Category (Sec Pos)' =
			
			SWITCH(
			    TRUE(),
			    [Percentage Difference (Sec Pos)]>0,"Gain",
			    AND([Percentage Difference (Sec Pos)]<0,[Percentage Difference (Sec Pos)]>=-0.1),"0%-10%",
			    AND([Percentage Difference (Sec Pos)]<-0.1,[Percentage Difference (Sec Pos)]>=-0.2),"11%-20%",
			    AND([Percentage Difference (Sec Pos)]<-0.2,[Percentage Difference (Sec Pos)]>=-0.3),"21%-30%",
			    AND([Percentage Difference (Sec Pos)]<-0.3,[Percentage Difference (Sec Pos)]>=-0.4),"31%-40%",
			    AND([Percentage Difference (Sec Pos)]<-0.4,[Percentage Difference (Sec Pos)]>=-0.5),"41%-50%",
			    AND([Percentage Difference (Sec Pos)]<-0.5,[Percentage Difference (Sec Pos)]>=-0.6),"51%-60%",
			    AND([Percentage Difference (Sec Pos)]<-0.6,[Percentage Difference (Sec Pos)]>=-0.7),"61%-70%",
			    AND([Percentage Difference (Sec Pos)]<-0.7,[Percentage Difference (Sec Pos)]>=-0.8),"71%-80%",
			    AND([Percentage Difference (Sec Pos)]<-0.8,[Percentage Difference (Sec Pos)]>=-0.9),"81%-90%",
			    "100%")
		lineageTag: ed56b4db-cf91-4bea-adc8-adc45bd7a4f0

	measure 'Activity Filter (Sec Pos)' = ```
			
			var activitytype = SELECTEDVALUE('Impairment Slicer'[Values])
			return
			SWITCH(
			    TRUE(),
			    AND(activitytype = "Private Equity OTTI Impairment",SELECTEDVALUE('Securities Position Fact'[Public/Private Indicator]) = [Activity Slicer (Sec Pos)]), 1, 
			    AND(activitytype = "Public Equity OTTI Impairment",AND(SELECTEDVALUE('Securities position Fact'[Public/Private Indicator]) = [Activity Slicer (Sec Pos)],[Activity Slicer (Sec Pos)]<>"Fixed Income")), 1, 
			     AND(FIND("Credit",activitytype,1,0) = 1,SELECTEDVALUE('Securities Position Fact'[Asset Class (Sec Pos)]) = [Activity Slicer (Sec Pos)]),1,0)
			```
		formatString: 0
		lineageTag: b0d8813e-27ca-4104-a3ea-adfeba40c99b

	measure 'Activity Slicer (Sec Pos)' = ```
			
			var activityType= SELECTEDVALUE('Impairment Slicer'[Values])
			var sectype = SELECTEDVALUE('Securities Position Fact'[Asset Class (Sec Pos)])
			var ret = 
			SWITCH(TRUE(),  activityType = "Private Equity OTTI Impairment",  "Private",
			AND(activityType = "Public Equity OTTI Impairment" ,NOT(sectype="Fixed Income")),"Public",
			"Fixed Income"
			)
			return ret
			```
		lineageTag: 94e48c12-b8a6-419b-8619-22186bfa0b9d

	measure 'Impairment Candidates Title Position' =
			
			VAR maxdate =
			    MAX ( 'Securities Position Fact'[As Of Date] )
			RETURN
			    "Impairment Candidates Position" & ", "
			        & SELECTEDVALUE ( Framework[Framework Display] ) & ", "
			        & FORMAT ( maxdate, "dd-mmm-yy" )
		lineageTag: 97d1b826-bfde-4c9f-aba1-55f466263613

	measure 'Issuer Country Cd (Sec Pos)' =
			
			CALCULATE (
			 FIRSTNONBLANK ( 'Securities'[Issuer Country Cd], TRUE () ),
			 CROSSFILTER ( 'Securities'[Security NK],'Securities Position Fact'[Security NK], BOTH ))
		lineageTag: 38a39032-5708-44ba-af65-17b60b2da90f

	measure 'Maturity Date' = ```
			
			VAR Pos_Maturity_Date = MIN ( 'Securities Position Fact'[Maturity Date Final] )
			VAR Sec_Maturity_Date = CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Maturity Date], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			RETURN COALESCE ( Pos_Maturity_Date, Sec_Maturity_Date )
			
			```
		formatString: yyyy-mm-dd
		lineageTag: bee6da90-23f1-4fcf-a8d6-48d83b6f3b18

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Internal Sec Id Type (Sec Pos)' =
			
			CALCULATE (
			 FIRSTNONBLANK ( 'Securities'[Internal Sec Id Type], TRUE () ),
			 CROSSFILTER ( 'Securities Position Fact'[Security NK],'Securities'[Security NK], BOTH ))
		lineageTag: 79e525c4-e7aa-45a9-a06b-d1b286c0f08a

	measure 'ML Review CAT CD (Sec Pos)' =
			
			CALCULATE (
			 FIRSTNONBLANK ( 'Securities'[ML Review CAT CD], TRUE () ),
			 CROSSFILTER ( 'Securities Position Fact'[Security NK],'Securities'[Security NK], BOTH ))
		lineageTag: 8765ccc4-d899-4ffa-85d8-9ed72a8ebbc5

	measure 'ML Issue Txt (Sec Pos)' =
			
			CALCULATE (
			 FIRSTNONBLANK ( 'Securities'[ML Issue Txt], TRUE () ),
			 CROSSFILTER ( 'Securities Position Fact'[Security NK],'Securities'[Security NK], BOTH ))
		lineageTag: 7417f756-44a6-4c2b-80f5-49b025ff294a

	measure 'Fair Value Unaccrued - Adjustment Local' = [Current Book Value - Adjustment Local (Sec Pos)]+ [Unrealized Gain/Loss - Adjustment Local]
		isHidden
		lineageTag: f3781dca-7103-4490-ae2f-4b0814602f19

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Fair Value Unaccrued - Adjustment Rep' = [Current Book Value - Adjustment Rep (Sec Pos)] + [Unrealized Gain/Loss - Adjustment Rep (Sec Pos)]
		isHidden
		lineageTag: d1ea0d1b-1cd4-47b7-939f-3002d7866a14

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carrying Value - Adjustment Local' =
			[Current Book Value - Adjustment Local (Sec Pos)] + [Unrealized Gain/Loss - Adjustment Local]
			/*
			IF(NOT (ISBLANK('Securities Position Fact'[Carrying Value - Local]) )&& NOT(ISBLANK('Securities Position Fact'[Fair Value Unaccrued - Local])),
			IF (
			     'Securities Position Fact'[Carrying Value - Local]='Securities Position Fact'[Fair Value Unaccrued - Local], 'Securities Position Fact'[Unrealized Gain/Loss - Adjustment Local])
			)*/
		lineageTag: 25369c74-4afc-485d-a5da-36bb2daa3832

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carrying Value - Adjustment Rep' = ```
			[Current Book Value - Adjustment Rep (Sec Pos)] + [Unrealized Gain/Loss - Adjustment Rep (Sec Pos)] 
			/*
			IF(NOT (ISBLANK([Carrying Value - Rep (Sec Pos)]) )&& NOT(ISBLANK([Fair Value Unaccrued - Rep (Sec Pos)])),
			IF (
			     [Carrying Value - Rep (Sec Pos)]=[Fair Value Unaccrued - Rep (Sec Pos)], [Unrealized Gain/Loss - Adjustment Rep (Sec Pos)] )
			)*/
			```
		lineageTag: 3c7242f1-218b-40c1-8672-bc19267d966c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carrying Value Final - Local' = [Carrying Value - Local]+[Carrying Value - Adjustment Local]
		lineageTag: 4d02d09b-9cdc-4a52-b133-41180eee7dc6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Carrying Value Final - Rep' = [Carrying Value - Rep (Sec Pos)]+[Carrying Value - Adjustment Rep]
		lineageTag: bc93cd65-9fe4-41ed-bfdb-ccbcbbbbc958

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Legal Structure Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK('Securities'[Legal Structure Cd],TRUE()),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 2b7142d7-4eaf-493f-9b9b-bffd879ec33c

	measure 'Adjusted GL Class (Sec Pos)' = ```
			
			VAR vMaxPeriodDate = MAX(Period[Date])
			VAR vAddRankFlagTable = 
			CALCULATETABLE(
			    ADDCOLUMNS(
			        'Adjust GL Reclass Fact',
			        "@Rank",RANKX('Adjust GL Reclass Fact','Adjust GL Reclass Fact'[Txn Dt])
			    ),
			    REMOVEFILTERS(period),
			    'Adjust GL Reclass Fact'[Txn Dt]<=vMaxPeriodDate
			)
			
			RETURN 
			IF(COUNTROWS('Securities Position Fact')>0,
			MAXX(
			    vAddRankFlagTable, IF ([@Rank]=1 , 'Adjust GL Reclass Fact'[gl classification] )
			)
			)
			```
		lineageTag: ebb37aee-6652-4604-9619-3d099efd1573

	measure 'Balance Called Capital - Rep (Sec Pos)' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Called Capital Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Balance Called Capital Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Called Capital Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Called Capital Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
		lineageTag: 1ca69419-446c-448c-88f2-58ea16c7ff48

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Recallable - Rep (Sec Pos)' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Recallable Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Balance Recallable Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Recallable Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Recallable Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
		lineageTag: 1c935592-d287-407a-ae27-a4d1fe11c7f8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance Return Of Capital - Rep (Sec Pos)' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance Return Of Capital Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Balance Return Of Capital Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Return Of Capital Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Return Of Capital Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
		lineageTag: 7e3f76ac-5714-4977-8842-f9bbd7f49b0b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Eqy Sic Cd (Sec Pos)' = ```
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Eqy Sic Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		lineageTag: 121aeb5f-420b-48d8-91e3-d3d4c023d443

	measure 'Balance NAIC Carrying Value - Local (Sec Pos)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance NAIC Carrying Value Local]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Balance NAIC Carrying Value Local]),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		lineageTag: 7eb7cc87-7459-4da4-a0d1-7b4ad84d9c4f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance NAIC Carrying Value - Rep (Sec Pos)' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance NAIC Carrying Value Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Balance NAIC Carrying Value Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance NAIC Carrying Value Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance NAIC Carrying Value Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
		lineageTag: 3edc4955-dd68-4373-ade2-b547a5353610

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance NAIC Sec Adj - Local (Sec Pos)' =
			
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance NAIC Sec Adj Local]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Balance NAIC Sec Adj Local]),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		lineageTag: d3c3b256-5f48-423a-9b3d-714be7e900d2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Balance NAIC Sec Adj - Rep (Sec Pos)' =
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Balance NAIC Sec Adj Base]),
			    CALCULATE(
			        SUM('Securities Position Fact'[Balance NAIC Sec Adj Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance NAIC Sec Adj Local] * 'Fx Rate DQ'[Rep Rate]
			    ),
			    CALCULATE(
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance NAIC Sec Adj Local] * 'Fx Rate DQ'[Rep Rate]
			        ),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			))
		lineageTag: 834522e6-9400-4748-98f5-c7ab9e806267

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accrual - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Accrual - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Accrual - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: b80a394e-8ac3-4caa-b4a7-5b116c8d8ce7

	measure 'Accrual - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Accrual - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Accrual - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 6f4e1432-98a0-4377-b858-adc87d2cb673

	measure 'Accrual - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Accrual - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Accrual - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 35d93b6b-550e-4375-a49d-0b5c99c39f31

	measure 'Accrual - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Accrual - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Accrual - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 97e020b6-527a-449f-b7a9-b8cafa8bda36

	measure 'Amortized Cost - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Amortized Cost - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Amortized Cost - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 8c599887-71d7-48b4-8bd4-b02796415688

	measure 'Amortized Cost - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Amortized Cost - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Amortized Cost - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 5b9e520d-6170-47bb-b6df-32a51364bfc1

	measure 'Amortized Cost - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Amortized Cost - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Amortized Cost - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 69d089b5-12c5-4eaa-a554-295611bbd056

	measure 'Amortized Cost - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Amortized Cost - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Amortized Cost - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 4fe65421-d906-4faa-abe5-41c2939a187c

	measure 'AOCI Remain Balance BV - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance BV - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance BV - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: eb09a675-7ee9-4cb3-a1dc-5215a06e01a2

	measure 'AOCI Remain Balance BV - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance BV - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance BV - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 9c3717be-127e-42be-ab51-6afd7d7f969b

	measure 'AOCI Remain Balance BV - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance BV - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance BV - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 1be4ac2a-5294-4623-8393-046778bd3ad4

	measure 'AOCI Remain Balance BV - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance BV - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance BV - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 823ef7d7-deff-4396-b267-b8653fb8fa8d

	measure 'AOCI Remain Balance Non BV - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance Non BV - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance Non BV - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 41f925c6-4cb4-486b-8829-7cf288badb5e

	measure 'AOCI Remain Balance Non BV - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance Non BV - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance Non BV - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 380a7fb6-c927-45a5-8263-96383b847bec

	measure 'AOCI Remain Balance Non BV - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance Non BV - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance Non BV - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 1055eec7-d3a6-436a-8289-eec3c0c8ef4f

	measure 'AOCI Remain Balance Non BV - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance Non BV - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance Non BV - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: ce0805b5-cdb5-48d7-8875-8066a1955587

	measure 'AOCI Remain Balance Rep - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance Rep - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance Rep - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: b8275644-5bfe-435d-b311-3bf6951f5f0f

	measure 'AOCI Remain Balance Rep - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance Rep - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance Rep - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 7dafcaae-d936-4846-b696-1394f015b686

	measure 'AOCI Remain Balance Rep - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance Rep - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance Rep - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: faf490b0-c4fc-43bd-abf3-bcec469af086

	measure 'AOCI Remain Balance Rep - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[AOCI Remain Balance Rep - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[AOCI Remain Balance Rep - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 5f7efc87-d463-43a7-a373-b0c3d191099a

	measure 'Balance Deferred PL - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Deferred PL - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Deferred PL - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 3a900d4e-6bfc-420d-a052-0612a725727d

	measure 'Balance Deferred PL - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Deferred PL - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Deferred PL - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 2a427dca-6034-4a51-a9af-bae2051c5e94

	measure 'Balance Deferred PL - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Deferred PL - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Deferred PL - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: d9cf25ea-f18e-4be5-8289-72bf004b1873

	measure 'Balance Deferred PL - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Deferred PL - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Deferred PL - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 4d2e1f9f-ea4c-476d-83e7-480d3a257bd3

	measure 'Book Value - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Book Value - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Book Value - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 031540e5-b615-4270-a499-c7c927b2ebe9

	measure 'Book Value - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Book Value - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Book Value - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 5be01d41-5fb3-428c-a45d-100ff9b4a99c

	measure 'Book Value - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Book Value - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Book Value - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: dfd68cf5-b7e1-4db1-a3ca-43c0acb6e6b5

	measure 'Book Value - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Book Value - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Book Value - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 63c3a08b-07e4-4ab7-9950-869eefc0052f

	measure 'Carrying Value - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Carrying Value - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Carrying Value - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: d633761d-6223-4c2a-8399-635ec207c427

	measure 'Carrying Value - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Carrying Value - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Carrying Value - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 126baa44-df96-4716-9570-d6e3f1bb318f

	measure 'Carrying Value - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Carrying Value - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Carrying Value - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 6dbd2736-ab6a-44fd-a419-42f56801daf9

	measure 'Carrying Value - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Carrying Value - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Carrying Value - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 52590747-6efa-45e1-bc4a-7b72b79ddf14

	measure 'Fair Value Accrued - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Fair Value Accrued - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Fair Value Accrued - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: ab13f06e-81c9-48ca-a7eb-b96fdae5e93a

	measure 'Fair Value Accrued - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Fair Value Accrued - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Fair Value Accrued - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 225dee82-e841-4c33-b1a3-e430b016eba9

	measure 'Fair Value Accrued - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Fair Value Accrued - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Fair Value Accrued - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 2a5852f0-47a7-48dd-94c9-d783f38429a5

	measure 'Fair Value Accrued - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Fair Value Accrued - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Fair Value Accrued - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 20dda013-b24f-4e8b-ad12-10106eedc751

	measure 'Fair Value Unaccrued - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Fair Value Unaccrued - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Fair Value Unaccrued - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 2e3cc675-48d8-4d74-a64c-0b09e2f601e0

	measure 'Fair Value Unaccrued - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Fair Value Unaccrued - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Fair Value Unaccrued - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 74c35800-bc76-4bbc-bbc8-9bc8a913faa0

	measure 'Fair Value Unaccrued - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Fair Value Unaccrued - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Fair Value Unaccrued - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 736763e5-a254-4bd4-91ba-144d8fedd9e9

	measure 'Fair Value Unaccrued - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Fair Value Unaccrued - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Fair Value Unaccrued - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: d2352520-8439-4f3d-86e0-7a47bef7f150

	measure 'Income Accrual - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Income Accrual - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Income Accrual - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 4beb399b-694e-4d94-9698-1e986824fec3

	measure 'Income Accrual - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Income Accrual - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Income Accrual - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 0c8732ca-b6f4-4a4a-9446-25a224bf9f1f

	measure 'Income Accrual - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Income Accrual - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Income Accrual - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 992341e0-0c0a-4d54-9d72-d559736ecfaa

	measure 'Income Accrual - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Income Accrual - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Income Accrual - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 53f8e4a2-164e-431b-8cbe-50b1cdb079ab

	measure 'Original Cost - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Original Cost - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Original Cost - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 10e3219d-81c1-4f4c-a782-b62560d2177d

	measure 'Original Cost - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Original Cost - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Original Cost - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 4ef7365c-8ed2-4cdb-a31c-962ea83fc40b

	measure 'Original Cost - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Original Cost - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Original Cost - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 8659a214-8c1f-497e-ae38-e49659440eec

	measure 'Original Cost - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Original Cost - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Original Cost - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 21c7bbc1-417d-4b41-9af8-7901d1ec476c

	measure 'Price - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Price - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Price - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: aabdcaba-cc91-4668-be1e-df6d5e5202b7

	measure 'Price - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Price - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Price - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 57fdb8a5-7845-4809-825e-5f63fdb27b70

	measure 'Price - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Price - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Price - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: c2dfe45a-bb8e-4b84-b616-22895f0e9219

	measure 'Price - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Price - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Price - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 2a776e93-6f18-4a85-be69-a9d39317c296

	measure 'Unrealized Gain/Loss - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 9d815643-9b8b-4604-97df-11e703167731

	measure 'Unrealized Gain/Loss - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 2bf2ec84-01fe-4d8c-9e5d-c37b0deb8abe

	measure 'Unrealized Gain/Loss - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 12e1e606-1a7e-4ec8-9f33-004251f14f46

	measure 'Unrealized Gain/Loss - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: dfb4d45e-47b7-4712-b62c-438c4769314c

	measure 'Unrealized Gain/Loss CCY - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss CCY - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss CCY - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 3ff8cf37-09df-4de6-9c67-e8b438f2c521

	measure 'Unrealized Gain/Loss CCY - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss CCY - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss CCY - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: a92583db-dfe5-4200-9d70-b03a05b433c3

	measure 'Unrealized Gain/Loss CCY - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss CCY - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss CCY - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 69cfa36e-49a0-4c07-a01f-bd66c60ad2a7

	measure 'Unrealized Gain/Loss CCY - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss CCY - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss CCY - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 9abcee92-1bfd-41cc-b1dc-d752fac26ed1

	measure 'Unrealized Gain/Loss Sec - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss Sec - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss Sec - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 71b48d99-56ab-494f-9079-b177f1e2c10d

	measure 'Unrealized Gain/Loss Sec - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss Sec - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss Sec - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: fbc308d3-525e-4f98-91d1-f508836b09b8

	measure 'Unrealized Gain/Loss Sec - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss Sec - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss Sec - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 7cc97279-6d26-457d-9472-b7c90d048122

	measure 'Unrealized Gain/Loss Sec - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Unrealized Gain/Loss Sec - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Unrealized Gain/Loss Sec - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: ca8482fe-428d-4c88-934f-2d531ada84a1

	measure 'Balance CL Allowance - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: e37201dc-5243-467e-b619-ff45ed8cdc83

	measure 'Balance CL Allowance - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 44dda5e7-3dad-4c2e-9f86-48af5700ef97

	measure 'Balance CL Allowance - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: f8ca0ad6-632b-4040-a959-c803e4aca036

	measure 'Balance CL Allowance - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: d4017005-f7d6-4d1b-9f86-024d5a0bcc16

	measure 'Balance Expected Restitution - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Expected Restitution - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Expected Restitution - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: daebf88f-e361-4998-8fe8-d8dd41fa1a79

	measure 'Balance Expected Restitution - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Expected Restitution - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Expected Restitution - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 5830be5c-2f75-4830-8c9f-d4e04f82084a

	measure 'Balance Expected Restitution - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Expected Restitution - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Expected Restitution - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 9e328929-b2be-4f99-9e26-b3a9463b7b1a

	measure 'Balance Expected Restitution - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Expected Restitution - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Expected Restitution - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 1e22781d-b789-47aa-93dc-f13c25be8925

	measure 'Balance Impairment - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Impairment - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Impairment - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: c2df1861-07f4-4325-9d07-4df194c0a1de

	measure 'Balance Impairment - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Impairment - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Impairment - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 4d78f154-04f8-4e75-957c-82dc0dd2adba

	measure 'Balance Impairment - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Impairment - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Impairment - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 41852a38-0bf5-4ba4-b263-9c96c87359dd

	measure 'Balance Impairment - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Impairment - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Impairment - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 580e4853-e2c6-4fd5-96de-5c7b319d297d

	measure 'Balance Int Appr - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Int Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Int Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 801aadd7-9802-404f-b87d-d2a0437b755c

	measure 'Balance Int Appr - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Int Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Int Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 35755df4-f1a0-4e96-9898-fcefda9e1fc7

	measure 'Balance Int Appr - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Int Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Int Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 9025b49a-b414-4299-ae57-b4caff82845b

	measure 'Balance Int Appr - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Int Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Int Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 7202a0c2-5420-4e41-a22a-885230f6a401

	measure 'Balance OID Appr - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance OID Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance OID Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 63cab1a1-133e-403e-9952-bb9b2c25ff5b

	measure 'Balance OID Appr - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance OID Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance OID Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: dedd2e62-dde1-4635-bbc8-b9375124bb19

	measure 'Balance OID Appr - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance OID Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance OID Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 6eb4afce-369b-42c7-a3bd-c64c81885802

	measure 'Balance OID Appr - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance OID Appr - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance OID Appr - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: de474dbe-9cdb-4b25-94be-fc1c6ad48197

	measure 'Balance Recog CL Allowance - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Recog CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Recog CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: ec344bf9-ba61-4f20-aeee-bf96fc921c57

	measure 'Balance Recog CL Allowance - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Recog CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Recog CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 3642412a-4694-4b69-bc41-1e272ce14c38

	measure 'Balance Recog CL Allowance - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Recog CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Recog CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 5fccefe3-8134-4084-963b-91890a26f6bf

	measure 'Balance Recog CL Allowance - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Recog CL Allowance - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Recog CL Allowance - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 93562432-df04-40ef-86e5-060a8b14cf45

	measure 'Balance Write Off - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Write Off - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Write Off - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 56fb54f6-1162-4987-bba0-895ca1eea898

	measure 'Balance Write Off - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Write Off - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Write Off - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 12b5e96b-b164-4228-bc6e-0d10a895ac10

	measure 'Balance Write Off - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Write Off - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Write Off - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: ff68eb39-551b-49ee-9984-d8022a136f1e

	measure 'Balance Write Off - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Balance Write Off - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Balance Write Off - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 29f7609b-72d0-4b46-a1e0-a1d5baa4f744

	measure 'Next Payment - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Next Payment - Local]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Next Payment - Local]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 07063cd8-78d7-41dd-adf6-123a58465474

	measure 'Next Payment - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Next Payment - Local]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Next Payment - Local]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 9bcd3538-399c-43a9-be23-9b6c6856d639

	measure 'Next Payment - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Next Payment - Local]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Next Payment - Local]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: b8b9f12c-94bf-4c18-9348-a7d7c809193f

	measure 'Next Payment - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Next Payment - Local]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Next Payment - Local]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: b8a30e97-5b69-4cbc-814e-c8e6b6517358

	measure 'Withheld - USD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Withheld - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Withheld - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[USD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 28b21861-890c-4218-b6e0-bd6013a3f193

	measure 'Withheld - HKD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Withheld - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Withheld - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[HKD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: bfcb85e5-b78a-4319-87ab-2375a5dffbc4

	measure 'Withheld - FUNC (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Withheld - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Withheld - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[Func BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 7cee5fce-4bd7-49a6-a18a-1e33c948e971

	measure 'Withheld - CAD (Sec Pos)' =
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX (
			        'Securities Position Fact',
			        'Securities Position Fact'[Withheld - Local (D)]
			            * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			    ),
			    CALCULATE (
			        SUMX (
			            'Securities Position Fact',
			            'Securities Position Fact'[Withheld - Local (D)]
			                * RELATED ( 'Fx Rate DQ'[CAD BS Rate] )
			        ),
			        LASTDATE ( 'Securities Position Fact'[As Of Date] )
			    )
			)
		displayFolder: Currency Measures
		lineageTag: 6207f07b-4907-45c9-a610-2f0904e9f3b0

	measure 'FV Final - Local (Sec Pos)' = ```
			
			VAR vIFRS9Purpose = SUMMARIZE('Securities Position Fact',Securities[Primary Security ID],'Securities Position Fact'[IFRS9 Purpose])
			VAR vIFRS9Chk = ADDCOLUMNS(vIFRS9Purpose,"@IFRS9_Chk",IF('Securities Position Fact'[IFRS9 Purpose] IN {"FVTPL","FVOCI"},1))
			VAR vIFRS9Max = ADDCOLUMNS(vIFRS9Chk,"@IFRS9_Max",CALCULATE(MAXX(vIFRS9Chk,[@IFRS9_Chk]),REMOVEFILTERS('Securities Position Fact'[IFRS9 Purpose])))
			
			VAR vIAS39Purpose = SUMMARIZE('Securities Position Fact',Securities[Primary Security ID],'Securities Position Fact'[Purpose])
			VAR vIAS39Chk = ADDCOLUMNS(vIAS39Purpose,"@IAS39_Chk",IF('Securities Position Fact'[Purpose] IN {"FVTPL","FVOCI","AFS"},1))
			VAR vIAS9Max = ADDCOLUMNS(vIAS39Chk,"@IAS39_Max",CALCULATE(MAXX(vIAS39Chk,[@IAS39_Chk]),REMOVEFILTERS('Securities Position Fact'[Purpose])))
			
			VAR vResult =
			SWITCH(
			    SELECTEDVALUE (Framework[Framework]),    
			    "IFRS9",    
			    SUMX(
			        SUMMARIZE('Securities Position Fact',[IFRS9 Purpose]),
			        IF([IFRS9 Purpose] IN {"FVTPL","FVOCI"},'Securities Position Fact'[Carrying Value - Local],[Fair Value Unaccrued - Local]
			        )
			    )+SUMX(SUMMARIZE(vIFRS9Max,Securities[Primary Security ID],[@IFRS9_Max]),IF([@IFRS9_Max]=1,[Carrying Value - Adjustment Local])),
			    "IAS39",
			    SUMX(
			        SUMMARIZE('Securities Position Fact',[Purpose]),
			        IF([Purpose] IN {"FVTPL","FVOCI","AFS"},'Securities Position Fact'[Carrying Value - Local],[Fair Value Unaccrued - Local]        
			        )
			    )+SUMX(SUMMARIZE(vIAS9Max,Securities[Primary Security ID],[@IAS39_Max]),IF([@IAS39_Max]=1,[Carrying Value - Adjustment Local]))
			    ,[Fair Value Unaccrued - Local]
			)
			
			RETURN vResult
			
			```
		lineageTag: 2713e153-31c0-41f3-83c8-b03ab5d5260b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FV Final - Rep (Sec Pos)' = ```
			
			VAR vIFRS9Purpose = SUMMARIZE('Securities Position Fact',Securities[Primary Security ID],'Securities Position Fact'[IFRS9 Purpose])
			VAR vIFRS9Chk = ADDCOLUMNS(vIFRS9Purpose,"@IFRS9_Chk",IF('Securities Position Fact'[IFRS9 Purpose] IN {"FVTPL","FVOCI"},1))
			VAR vIFRS9Max = ADDCOLUMNS(vIFRS9Chk,"@IFRS9_Max",CALCULATE(MAXX(vIFRS9Chk,[@IFRS9_Chk]),REMOVEFILTERS('Securities Position Fact'[IFRS9 Purpose])))
			
			VAR vIAS39Purpose = SUMMARIZE('Securities Position Fact',Securities[Primary Security ID],'Securities Position Fact'[Purpose])
			VAR vIAS39Chk = ADDCOLUMNS(vIAS39Purpose,"@IAS39_Chk",IF('Securities Position Fact'[Purpose] IN {"FVTPL","FVOCI","AFS"},1))
			VAR vIAS9Max = ADDCOLUMNS(vIAS39Chk,"@IAS39_Max",CALCULATE(MAXX(vIAS39Chk,[@IAS39_Chk]),REMOVEFILTERS('Securities Position Fact'[Purpose])))
			
			VAR vResult =
			SWITCH(
			    SELECTEDVALUE (Framework[Framework]),    
			    "IFRS9",    
			    SUMX(
			        SUMMARIZE('Securities Position Fact',[IFRS9 Purpose]),
			        IF([IFRS9 Purpose] IN {"FVTPL","FVOCI"},'Securities Position Fact'[Carrying Value - Rep (Sec Pos)],[Fair Value Unaccrued - Rep (Sec Pos)]
			        )
			    )+SUMX(SUMMARIZE(vIFRS9Max,Securities[Primary Security ID],[@IFRS9_Max]),IF([@IFRS9_Max]=1,[Carrying Value - Adjustment Rep])),
			    "IAS39",
			    SUMX(
			        SUMMARIZE('Securities Position Fact',[Purpose]),
			        IF([Purpose] IN {"FVTPL","FVOCI","AFS"},'Securities Position Fact'[Carrying Value - Rep (Sec Pos)],[Fair Value Unaccrued - Rep (Sec Pos)]        
			        )
			    )+SUMX(SUMMARIZE(vIAS9Max,Securities[Primary Security ID],[@IAS39_Max]),IF([@IAS39_Max]=1,[Carrying Value - Adjustment Rep]))
			    ,[Fair Value Unaccrued - Rep (Sec Pos)]
			)
			
			RETURN vResult
			
			```
		lineageTag: 3d3f9f9e-0609-40b3-9486-ab24cff97bbb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SCD MTG Exp Maturity Dt (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[SCD MTG EXP Maturity Dt], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		formatString: General Date
		lineageTag: ac44639f-b50b-4e65-bc05-a1f66585be28

	measure 'Ultimate parent company (Sec Pos)' = ```
			
			    CALCULATE(
			        [Ultimate parent company (Entities)],
			        CROSSFILTER(Securities[Security NK],'Securities Position Fact'[Security NK],BOTH)
			        )
			```
		lineageTag: a0a0b337-18df-4e75-b55a-f1ee6c551925

	measure 'Ultimate parent LEI (Sec Pos)' = ```
			
			    CALCULATE(
			        [Ultimate parent LEI (Entities)],
			        CROSSFILTER(Securities[Security NK],'Securities Position Fact'[Security NK],BOTH)
			        )
			```
		lineageTag: bdacfa1a-90d4-4a48-ba4d-9d92af91d76d

	measure 'Ultimate parent location (Sec Pos)' = ```
			
			    CALCULATE(
			        [Ultimate parent location (Entities)],
			        CROSSFILTER(Securities[Security NK],'Securities Position Fact'[Security NK],BOTH)
			        )
			```
		lineageTag: 7e38ca77-19bb-4e7d-959f-66882d18b7f8

	measure 'NAIC Designation Modifier (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[NAIC Designation Modifier], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: e57137d6-ee1d-4e52-a582-32b2af6d6d3a

	measure 'SCD Svo Suffix (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[SCD Svo Suffix], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		displayFolder: Security Values
		lineageTag: 067143d9-c9eb-4083-9e04-1090827f2261

	measure 'Make Whole Call Spread Num (Sec Pos)' =
			
			CALCULATE (MAX('Securities'[Make Whole Call Spread Num]),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: e3950232-5031-4ee4-8df0-9adcf6e7e50d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Make Whole Termination Dt (Sec Pos)' =
			
			CALCULATE (MAX('Securities'[Make Whole Termination Dt]),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		formatString: yyyy-mm-dd
		lineageTag: ae5e93db-e35e-497a-ad93-8e75136954a4

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'Payment Method Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Payment Method Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: a08518c0-1497-483e-b8a8-8c467d9fd760

	measure 'SCD GL Classification (Sec Pos)' =
			
			CALCULATE (
			    COALESCE(MAX('Securities'[SCD GL Classification]),MAX('Securities Position Fact'[SCD GL Classification])),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 9daaeb2a-13ff-4474-8e72-2a97542f486b

	measure 'Make Whole Call (Sec Pos)' =
			
			CALCULATE (MAX('Securities'[Make Whole Call]),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 97cda364-6816-4d82-bced-c1b8ea2c7343

	measure 'MFC Equivalent(Risk) (Sec Pos)' =
			
			CALCULATE (
			 FIRSTNONBLANK ( Entities[MFC Equivalent(Risk)], TRUE () ),
			 CROSSFILTER ( 'Securities'[Entity Join Key], Entities[Entity Join NK], BOTH ),
			 CROSSFILTER ( 'Securities'[Security NK], 'Securities Position Fact'[Security NK], BOTH ))
		lineageTag: 9ed99053-6f17-4b2f-9994-b9e1a40d1cd7

	measure 'SCD Instrument Category (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[SCD Instrument Category], TRUE () ),
			    CROSSFILTER ('Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 4a1739a6-5fa5-45d4-af1d-bd3252f9ee28

	measure 'Structure (Sec Pos)' =
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    FIRSTNONBLANK('Securities Position Fact'[Structure],TRUE()),
			    CALCULATE(
			        FIRSTNONBLANK('Securities Position Fact'[Structure],TRUE()),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
		lineageTag: 78694abf-4c7e-435d-a63b-39177e074463

	measure 'Issue Volume (Sec Pos)' =
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    FIRSTNONBLANK('Securities Position Fact'[Issue Volume],TRUE()),
			    CALCULATE(
			        FIRSTNONBLANK('Securities Position Fact'[Issue Volume],TRUE()),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
		lineageTag: 2f4ca94b-cb33-438c-9b94-c5b86d8aedfe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bank Account (Sec Pos)' =
			
			CALCULATE (
			    MAX ('Portfolios'[Bank Account (D)]),
			    CROSSFILTER ('Securities Position Fact'[Portfolio NK], 'Portfolios'[Portfolio NK], BOTH)
			)
		lineageTag: 8409b1af-2464-478a-9714-01e92c4de2e9

	measure 'MIM Indicator (Sec Pos)' =
			
			CALCULATE (
			        SUM ( Portfolios[Mim Indicator (D)] ),
			        CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios'[Portfolio NK], BOTH )
			    )
		formatString: 0
		lineageTag: 0843e34c-4d53-424a-893c-6eb24f274f33

	measure 'Regulated Account Indicator (Sec Pos)' =
			
			CALCULATE (
			        FIRSTNONBLANK(Portfolios[Regulated Account Indicator (D)],TRUE() ),
			        CROSSFILTER ( 'Securities Position Fact'[Portfolio NK], 'Portfolios'[Portfolio NK], BOTH )
			    )
		lineageTag: 4d4d2bcf-3efa-4645-894b-11988c8ab44c

	measure 'Next Call Date (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Next Call Date], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH ))
		formatString: yyyy-mm-dd
		lineageTag: 790f73f9-89a2-436d-8ba4-76e729ca9a2c

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'MRM Issuer Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 9a6b34e8-062a-455d-a384-d913984f1c66

	measure 'MRM Issuer Irr Rating Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Irr Rating Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 51310178-0153-411b-84fd-dcc24e9f8884

	measure 'MRM Issuer Country Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Country Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 4ef77f9f-0efd-490a-992e-300db3de4cf3

	measure 'MRM Issuer Parent Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Parent Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 7ed4412f-4900-493f-8ada-e15b523f36b2

	measure 'MRM Issuer Parent Country Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Parent Country Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: fdfeb272-f9ea-4da8-ba91-808cd62a3158

	measure 'MRM Issuer Parent Irr Rating Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Parent Irr Rating Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 129413f6-effe-4542-8279-68c1c90cf725

	measure 'MRM Issuer Ultparent Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Ultparent Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 295995ee-34fd-4b53-a9c7-af19ae4bbf30

	measure 'MRM Issuer Ultparent Country Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Ultparent Country Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 34b8c4a7-52e4-43f5-8e85-630af57e02d5

	measure 'MRM Issuer Ultparent Irr Rating Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Ultparent Irr Rating Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: da97bb3b-f456-4329-80e2-033c95461a51

	measure 'Equity Fund Ind (Sec Pos)' = ```
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[Equity Fund Ind], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
			
			```
		lineageTag: 600003b3-1504-4800-ab59-45711a5def2c

	measure 'GCLMS Collateral Quality Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[GCLMS Collateral Quality Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 7aeb3b1b-501c-48d7-9e6b-1454d932227e

	measure 'MRM Issuer Cascade Rating Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Cascade Rating Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 6021c734-8c2d-4409-9533-689c5280df67

	measure 'MRM Issuer Parent Cascade Rating Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Parent Cascade Rating Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: da249cd6-dafd-4b60-abbd-b86b6820bfed

	measure 'MRM Issuer Ultparent Cascade Rating Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[MRM Issuer Ultparent Cascade Rating Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 2edb1ab6-6728-4b33-b5af-b8c36c18e1be

	measure 'Cur Cpn (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[Cur Cpn], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 0b71dfa9-bacc-49b5-9f99-c7e42b78be02

	measure 'GCLMS Issuer Parent Cascade Rtg Cd (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[GCLMS Issuer Parent Cascade Rtg Cd], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: bf4f550c-1b17-453d-beaf-24bc99f5178d

	measure 'Guarantor Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( Securities[Guarantor Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: a34a5d2a-cbdb-4fdc-adff-591764dffd85

	measure 'Capital Structure Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Capital Structure Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 58fb3eaa-34c0-4dbb-b547-1410f1e02774

	measure 'Accrued Interest EOP - Rep (Sec Pos)' = ```
			
			
			SWITCH(
			SELECTEDVALUE('Reporting Currency'[Rep In Currency]),
			"SCD Base",
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUM('Securities Position Fact'[Accrued Interest EOP Base]),
			    CALCULATE (
			        SUM('Securities Position Fact'[Accrued Interest EOP Base]),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			),
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    SUMX('Securities Position Fact', 'Securities Position Fact'[Accrued Interest EOP Local] *'Fx Rate DQ'[Rep Rate]),
			
			            CALCULATE (
			                    SUMX('Securities Position Fact', 'Securities Position Fact'[Accrued Interest EOP Local] *'Fx Rate DQ'[Rep Rate]),
			                LASTDATE('Securities Position Fact'[As Of Date])
			            )
			    )   
			)
			```
		lineageTag: 6b5c84b2-41d1-4e72-b2e9-07a826be9a34

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Alt Fee Asset Name (Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Alt Fee Asset Name], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 6902dd61-d6a0-4488-9a6a-9b7cbed339ac

	measure 'Callable (Sec Pos)' =
			
			CALCULATE(
			        MAXX(
			            'Securities',
			            IF(
			                Securities[Next Call Date] = BLANK(),
			                "N",
			                'Securities'[Callable]
			            )
			        ),
			        CROSSFILTER(
			            'Securities Position Fact'[Security NK],
			            'Securities'[Security NK],
			            Both
			        )
			    )
		lineageTag: 15345207-98f9-457a-baad-d44a70d74723

	measure 'Accrued Interest PC Static(Sec Pos)' =
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    FIRSTNONBLANK('Securities Position Fact'[Accrued Interest PC (Static)],TRUE()),
			    CALCULATE(
			        FIRSTNONBLANK('Securities Position Fact'[Accrued Interest PC (Static)],TRUE()),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
		lineageTag: 1cfa9d8c-05e3-43ab-bb88-fd7a7efe4356

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accrued Interest QC Static(Sec Pos)' =
			
			IF (
			    ISFILTERED ( 'Period'[Date] ),
			    FIRSTNONBLANK('Securities Position Fact'[Accrued Interest QC (Static)],TRUE()),
			    CALCULATE(
			        FIRSTNONBLANK('Securities Position Fact'[Accrued Interest QC (Static)],TRUE()),
			        LASTDATE('Securities Position Fact'[As Of Date])
			    )
			)
		lineageTag: dc2d77a8-6531-48b9-b5a7-0a1f7d8c85f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Multi Cpn Schedule Typ (Sec Pos)' =
			
			CALCULATE (MAX('Securities'[Multi Cpn Schedule Typ]),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 777cacb4-feeb-4a57-904e-7f6a306afddc

	measure 'Ram Rating(Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Ram Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: 06c13e16-8717-4301-8f39-382ed7a78e9e

	measure 'Marc Rating(Sec Pos)' =
			
			CALCULATE (
			    FIRSTNONBLANK ( 'Securities'[Marc Rating], TRUE () ),
			    CROSSFILTER ( 'Securities Position Fact'[Security NK], 'Securities'[Security NK], BOTH )
			)
		lineageTag: af4c64e0-f271-4c48-9902-6e3e9da0ac28

	measure 'Trading Philosophy Code - IAS39 (Sec Pos)' =
			
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] > MaxAsOfDate
			    )
			RETURN
			IF(COUNTROWS('Securities Position Fact')>0,
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Position Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    // TREATAS(BusEffFromTo,'Securities Transaction GA Fact'[Trade Date]),
			    BusEffFromTo,
			    KEEPFILTERS('Securities Position Fact'[Framework Code] = "IAS39")
			))
		lineageTag: d0c7d23a-aef5-4473-aa89-3f70d35371da

	measure 'Trading Philosophy Code - JGAAP (Sec Pos)' =
			
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] > MaxAsOfDate
			    )
			RETURN
			IF(COUNTROWS('Securities Position Fact')>0,
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Position Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    // TREATAS(BusEffFromTo,'Securities Transaction GA Fact'[Trade Date]),
			    BusEffFromTo,
			    KEEPFILTERS('Securities Position Fact'[Framework Code] = "JGAAP")
			))
		lineageTag: d3e046ce-523a-4ba1-8201-5b030071e153

	measure 'Trading Philosophy Code - USGAAP (Sec Pos)' =
			
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] > MaxAsOfDate
			    )
			RETURN
			IF(COUNTROWS('Securities Position Fact')>0,
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Position Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    // TREATAS(BusEffFromTo,'Securities Transaction GA Fact'[Trade Date]),
			    BusEffFromTo,
			    KEEPFILTERS('Securities Position Fact'[Framework Code] = "USGAAP")
			))
		lineageTag: cd2f09d4-1fa6-4c82-85dc-eb1fb90ab85d

	measure 'Purpose Codes (Sec Pos) - TP' = ```
			
			 
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] >= MaxAsOfDate
			    )
			VAR TPvalue =
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Position Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    BusEffFromTo
			    // KEEPFILTERS('Impairments Position Fact DQ'[Framework Code] = "IFRS9")
			)
			VAR FW =
			    SELECTEDVALUE ( Framework[Framework] )
			RETURN
			    CALCULATE (
			        IF (
			            FW = "IAS39",
			            TPvalue,
			            IF (
			                FW = "USGAAP",
			                TPvalue,
			                IF (
			                    FW = "JGAAP",
			                    TPvalue,
			                    IF (
			                        FW = "IFRS9",
			                       
			                        TPvalue,
			                        --(FW= "USTAX" || FW= "NAIC"),
			                        IF (
			                            NOT (
			                                ISEMPTY ( 'Securities Position Fact' )
			                            ),
			                            "AFS"
			                        )
			                    )
			                )
			            )
			        ),
			        FILTER (
			            'Securities Position Fact',
			            'Securities Position Fact'[As Of Date]
			                = MAX ( 'Securities Position Fact'[As Of Date] )
			        )
			    )
			```
		lineageTag: b24a98d3-8a63-4842-8850-359095e7cbe3

	measure 'Trading Philosophy Code - IFRS (Sec Pos)' =
			
			VAR MaxAsOfDate = MAX(Period[Date])
			VAR PortfolioCodes = VALUES(Portfolios[Portfolio Code])
			VAR FrameworkCodes = VALUES(Framework[Framework Display])
			VAR AssetTypes = VALUES('Securities'[SCD GL Classification])
			VAR BusEffFromTo =
			    FILTER(
			        'Accounting Framework Philosophy',
			        'Accounting Framework Philosophy'[Bus Eff Date From] <= MaxAsOfDate &&
			        'Accounting Framework Philosophy'[Bus Eff Date To] > MaxAsOfDate
			    )
			RETURN
			IF(COUNTROWS('Securities Position Fact')>0,
			CALCULATE(
			    FIRSTNONBLANK('Accounting Framework Philosophy'[Trading Philosophy], TRUE()),
			    CROSSFILTER('Securities Position Fact'[Security NK], Securities[Security NK], BOTH),
			    TREATAS(PortfolioCodes, 'Accounting Framework Philosophy'[Portfolio Cd]),
			    TREATAS(FrameworkCodes, 'Accounting Framework Philosophy'[Accounting Framework]),
			    TREATAS(AssetTypes, 'Accounting Framework Philosophy'[Asset Type Cd]),
			    // TREATAS(BusEffFromTo,'Securities Transaction GA Fact'[Trade Date]),
			    BusEffFromTo,
			    KEEPFILTERS('Securities Position Fact'[Framework Code] = "IFRS9")
			))
		lineageTag: dd7df964-7f9e-4a75-a854-b363c7be83f5

	measure 'Income Impairment Details - Local (Sec Pos)' = ```
			
			    CALCULATE (
			        SUM ( 'Securities Transaction GA Fact'[Book Value - Local unsigned] ) * -1,
			        //Step1: Identify the impairments for the position
			        /*TREATAS (
			            VALUES ( 'Securities Position Fact'[Src Position ID] ),
			            'Securities Transaction GA Fact'[POS Trans Link]
			        ),*/
			        'Securities Transaction GA Fact'[Bus Trans Code] = "TaxLotCorr",
			        'Securities Transaction GA Fact'[Transaction Purpose]
			            IN { "Income Impairment Reversal", "Income Impairment" },
			        'Securities Transaction GA Fact'[Trans Status] = "Active",
			        //Step2: Aggregate the cummulative impairment for the position
			        FILTER (
			            ALL ( Period[Date] ),
			            Period[Date] <= MAX ( Period[Date] )
			        ),
			    ALLSELECTED ( Securities ),
			        VALUES ( Securities[Primary Security ID] )
			    )
			
			```
		lineageTag: 9a1ab2bc-f79a-4ff9-a73e-c782014162f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income Impairment Details - Rep (Sec Pos)' = ```
			
			    CALCULATE (
			        SWITCH (
			            SELECTEDVALUE ( 'Reporting Currency'[Rep In Currency] ),
			            "SCD Base", SUM ( 'Securities Transaction GA Fact'[Book Value - Base unsigned] ) * -1,
			            SUMX (
			                'Securities Transaction GA Fact',
			                'Securities Transaction GA Fact'[Book Value - Local unsigned] * [Rep Rate]
			            ) * -1
			        ),
			        //Step1: Identify the impairments for the position
			        /*TREATAS (
			            VALUES ( 'Securities Position Fact'[Src Position ID] ),
			            'Securities Transaction GA Fact'[POS Trans Link]
			        ),*/
			        'Securities Transaction GA Fact'[Bus Trans Code] = "TaxLotCorr",
			        'Securities Transaction GA Fact'[Transaction Purpose]
			            IN { "Income Impairment Reversal", "Income Impairment" },
			        'Securities Transaction GA Fact'[Trans Status] = "Active",
			        //Step2: Aggregate the cummulative impairment for the position
			        FILTER (
			            ALL ( Period[Date] ),
			            Period[Date] <= MAX ( Period[Date] )
			        ),
			        ALLSELECTED ( Securities ),
			        VALUES ( Securities[Primary Security ID] )
			    )
			
			```
		lineageTag: 0ea59777-8600-443e-8e0a-0c5b2e2bbad2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Accrual - Adjustment Local - opt' = ```
			
			VAR vListofGLAccts =
			    CALCULATETABLE(
			        VALUES('CAT Adjmt Config Table'[GL Acct Num]),
			        'CAT Adjmt Config Table'[Measure Name] = "Accrual"
			    )
			 
			VAR vMaxSelectedDate = MAX(Period[Date])
			VAR vMaxAsOfPeriod =
			    MAX('Consolidated GL Balance Fact'[As of Period])
			 
			RETURN
			IF (
			    ISEMPTY(
			        CALCULATETABLE(
			            'Consolidated GL Balance Fact',
			            Period[Date] = vMaxSelectedDate
			        )
			    ),
			    BLANK(),
			    SUMX(
			        VALUES(Securities[Primary Security ID]),
			        CALCULATE(
			            SUM('Consolidated GL Balance Fact'[Local Balance Amt]),
			            TREATAS(
			                vListofGLAccts,
			                'Consolidated GL Balance Fact'[GL Acct (6 digits)]
			            ),
			            Period[Date] = vMaxSelectedDate,
			            'Consolidated GL Balance Fact'[As of Period] = vMaxAsOfPeriod
			        )
			    )
			)
			 
			```
		lineageTag: 2136feaa-3f86-49eb-85ec-e714f47fcc05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PortSecKey = ```
			
			'Securities Position Fact'[Portfolio Code] & " - "
			    & RELATED ( 'Securities'[Src Security ID] )
			
			```
		lineageTag: 956b545b-7ff7-4fd2-a33c-4d7ddb5ec55b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month End Pos' = ```
			
			IF (
			    'Securities Position Fact'[As Of Date]
			        = EOMONTH ( 'Securities Position Fact'[As Of Date], 0 ),
			    "Month End",
			    "Non Month End"
			)
			
			```
		lineageTag: e9e68a8d-2585-465b-85ae-56509e1ac90c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Asset Group (Sec Pos)' = RELATED('Securities'[Asset Group])
		displayFolder: Security Values
		lineageTag: d31eff90-468b-4ef3-8d2e-366338725581
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Security ID (Slicer -Sec Pos)' = RELATED('Securities'[SecurityID Slicer - Restated])
		lineageTag: 89a3034e-34a7-41ee-8b8a-e8fc62d6b4dc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Asset Type (Sec Pos)' = RELATED('Securities'[Asset Type])
		displayFolder: Security Values
		lineageTag: a71e5033-c78c-402d-bf20-8a5e63c3ddf1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID & Desc (Sec Pos)' = RELATED('Securities'[Primary Security ID & Desc])
		lineageTag: bb46d145-0607-4444-acbf-fd6b8c11ec5c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID (Sec Pos)' = RELATED('Securities'[Primary Security ID])
		lineageTag: 3de0f8e2-592f-425e-b6af-0e6adc65351e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Company Code & Name Display' =
			
			IF (
			    'Securities Position Fact'[Company Code & Name]
			        IN { "Not Applicable - Not Applicable", "Not Available - Not Available" },
			    "9999 - Off Balance Sheet Company",
			    'Securities Position Fact'[Company Code & Name]
			)
		lineageTag: 62b9ab91-61ef-4a71-85d0-b2f08fb708b2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Accounting Unit Code & Name Display' =
			
			IF (
			    'Securities Position Fact'[Accounting Unit Code & Name]
			        IN {"Not Applicable - Not Applicable", "Not Available - Not Available" },
			    "9999 - Off Balance Sheet Acct Unit",
			    'Securities Position Fact'[Accounting Unit Code & Name]
			)
		lineageTag: 9f8cc959-f238-4994-af26-4526b6ff02fe
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Public/Private Indicator' = ```
			
			var code = RELATED('Securities'[ML Investment Type CD])
			return 
			IF(code IN {"Private","Secondary Private"},"Private","Public")
			```
		lineageTag: c2ac8829-304b-4d18-b93b-11068c14de31
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'FX Join Key'
		dataType: string
		lineageTag: 0498295e-6d22-45e7-a7e3-3a32f984bc2c
		summarizeBy: none
		sourceColumn: FX Join Key

		annotation SummarizationSetBy = Automatic

	column 'Coupon Freq Description' = ```
			
			var cond = if( RELATED( 'Securities'[Coupon Frequency] ) <> BLANK(),RELATED( 'Securities'[Coupon Frequency] ),BLANK())
			VAR calc =
			    SWITCH (
					cond
			        ,
			        "0",
			           "AT MATURITY" ,
			        "1",
			            "ANNUAL",
			        "2",
			           "SEMI-ANNUAL" ,
			        "3",
			           "3 TIMES/YR" ,
			        "4",
			           "QUARTERLY" ,
					"6",
			           "6 TIMES/YR" ,
					"7",
			           "7 DAY" ,
					"12",
			           "MONTHLY" ,
					"28",
			           "28 DAY" ,
					"35",
			           "35 DAY" ,
					"49",
			           "49 DAY" ,
					"360",
			           "DAILY" 
					--,
			          --  BLANK()
			    )
			RETURN
			    calc
			```
		lineageTag: d5b182c4-02c9-4958-993e-ae568f1816c7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Country_Blank_nk = if(ISBLANK([SCD Country]),1,0)
		isHidden
		formatString: 0
		lineageTag: 4a3a34eb-be24-4725-8066-d785b28467cc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Ml Pricing Source' = RELATED(Securities[Ml Pricing Source])
		isHidden
		lineageTag: 77e2dbd3-b9e8-4102-ab05-c537d62d3af6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Latest As of Dt Slicer(Sec Pos)' =
			
			VAR vLatestPositionPerFramework = CALCULATE(MAX('Securities Position Fact'[As Of Date]),ALLEXCEPT('Securities Position Fact','Securities Position Fact'[Framework Code],'Securities Position Fact'[Company Code & Name Display],'Securities Position Fact'[Accounting Unit Code & Name Display],'Securities Position Fact'[Portfolio Code & Name],'Securities Position Fact'[As Of Period]))
			RETURN IF(vLatestPositionPerFramework='Securities Position Fact'[As Of Date],"Latest",FORMAT('Securities Position Fact'[As Of Date],"DD-MM-YYYY"))
		isHidden
		lineageTag: 9c80448d-46de-4e5c-bfbe-2ad2974f6275
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Indonesian Price (Indo Pos)' = RELATED('Securities'[Indonesian Price])
		displayFolder: Indonesian Positions Attributes
		lineageTag: 4e5ae060-ff89-4e86-b3a6-6e367c2c0c85
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Reset Freq Description' = RELATED(Securities[Reset Freq Description])
		lineageTag: 0fb3c1a8-f584-4532-98ed-61b78e231ade
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'ML IRR Rating' = RELATED(Securities[ML IRR Rating])
		lineageTag: 19a18f13-d184-4d02-b9ba-33e1a7e55078
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Process Flag' = "N"
		lineageTag: 2499c9ae-dc75-4100-ad7e-f60d91ebac48
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'SCD Impairment Tran Code' =
			
			IF(SELECTEDVALUE('Impairment Slicer'[Values])="Credit Recovery","ImpPartRevTaxLot","ImpStrtTaxLot")
		lineageTag: 546833b7-1226-4ee3-b383-23b51a998975
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Original Drop %' =
			
			var calc =100 - ('Securities Position Fact'[Fair Value Unaccrued - Local (D)]/'Securities Position Fact'[Original Cost - Local (D)] )
			return
			if('Securities Position Fact'[Original Cost - Local (D)] = 0,BLANK(),calc)
		lineageTag: fcc1ea21-51b5-495b-be9c-8400f33a53e5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Current Drop %' =
			
			var calc =100 - ('Securities Position Fact'[Fair Value Unaccrued - Local (D)]/'Securities Position Fact'[Book Value - Base] )
			return
			if('Securities Position Fact'[Book Value - Base] = 0,BLANK(),calc)
		lineageTag: b23ce307-9feb-4874-913f-48c8ea0da820
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Company Code' =
			
			var ac ='Securities Position Fact'[Company Code & Name Display]
			var pos = IFERROR(SEARCH("-",ac),"")
			var calc = IFERROR(LEFT(ac,pos-2),"")
			return calc
		lineageTag: 155ad89b-3300-4fff-82fe-0bd1a6c9f1ca
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Accounting Unit Code' =
			
			var ac ='Securities Position Fact'[Accounting Unit Code & Name Display]
			var pos = IFERROR(SEARCH("-",ac),"")
			var calc = IFERROR(LEFT(ac,pos-2),"")
			return calc
		lineageTag: c4c3cd3d-def3-4540-ba65-2a383e1457aa
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Asset Class (Sec Pos)' = RELATED('Securities'[Asset Class])
		lineageTag: 631a0c36-4db9-4163-aa8e-874d44a1f781
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'As of date Slicer Formatted' =
			
			
			VAR vMaxPosDate = MAX('Securities Position Fact'[As Of Date])
			
			RETURN
			
			SWITCH(
			
			TRUE(),
			
			'Securities Position Fact'[As Of Date]=vMaxPosDate,"Latest",
			
			ENDOFMONTH('Securities Position Fact'[As Of Date])='Securities Position Fact'[As Of Date],"Latest",
			
			FORMAT('Securities Position Fact'[As Of Date],"DD-MMM-YYYY")
			
			)
		lineageTag: 1922a073-c55b-48d5-aba0-18de1e625a33
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Blue Book Code (Position Only OIA Securities)' = ```
			SWITCH(TRUE(), 
			RELATED(Securities[ML NAIC Report Part Cd]) = "BA" && RELATED(Securities[SCD Security ID]) <> "40479@AA4" && RELATED(Securities[SCD Security ID]) <> "40479*AA6" && RELATED(Securities[SCD Security ID]) <> "40479*AB4", "BA",
			RELATED('Securities'[Primary Security ID]) = "40479@AA4", "D1",
			RELATED('Securities'[Primary Security ID]) = "40479*AA6", "D1",
			RELATED('Securities'[Primary Security ID]) = "40479*AB4", "D1",
			
			RELATED(Securities[SCD Security ID]) = "BBG000BBV9N3", "D1",
			RELATED(Securities[SCD Security ID]) = "BBG000PWXXY5", "D1",
			RELATED(Securities[SCD Security ID]) = "BBG000PWYVH7", "D1",
			RELATED(Securities[SCD Security ID]) = "BBG000PWZHX9", "D1",
			
			//Position only exception shared by Ling Chen (USTAX) - Need to revalidate exception logic later
			
			RELATED(Securities[SCD Security ID]) = "RR 25660161", "E2",
			RELATED(Securities[SCD Security ID]) = "RR 25661232", "E2",
			RELATED(Securities[SCD Security ID]) = "DEP1075929", "E2",
			RELATED(Securities[SCD Security ID]) = "DEP1075932", "E2",
			RELATED(Securities[SCD Security ID]) = "DEP1075935", "E2",
			RELATED(Securities[SCD Security ID]) = "DEP1075938", "E2",
			RELATED(Securities[SCD Security ID]) = "DEP1076110", "E2",
			
			//Wash Sale Exceptions for the above BBG000 securities
			
			RELATED(Securities[SCD Security ID]) = "WS1000259", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000393", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000624", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000625", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000627", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000648", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000651", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000652", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000653", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000656", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000657", "D1",
			RELATED(Securities[SCD Security ID]) = "WS1000691", "D1",
			
			RELATED(Securities[SCD Security ID]) = "50254692", "D2.2",
			RELATED(Securities[SCD Security ID]) = "50254693", "D2.2",
			RELATED(Securities[SCD Security ID]) = "50254212", "D2.2",
			RELATED(Securities[SCD Security ID]) = "50256903", "D2.2",
			RELATED(Securities[SCD Security ID]) = "BBG000006KY0", "D1",
			RELATED(Securities[SCD Security ID]) = "609990031", "BA",
			RELATED(Securities[SCD Security ID]) = "50185510", "BA",
			
			RELATED(Securities[SCD Security Type]) = "OIA BOND", "BA",
			RELATED(Securities[SCD Security Type]) = "OIA EA", "BA",
			RELATED(Securities[SCD Security Type]) = "OIA PFD", "BA",
			RELATED(Securities[SCD Security Type]) = "OIA STK", "BA",
			RELATED(Securities[SCD Security Type]) = "COVWARRANT", "D2.2",
			RELATED(Securities[SCD Security Type]) = "PRV WARRNT", "D2.2",
			RELATED(Securities[SCD Security Type]) = "DEPOSIT", "DA1",
			RELATED(Securities[SCD Security Type]) = "REPO", "DA1",
			RELATED(Securities[SCD Security Type]) = "REV REPO", "DA1",
			BLANK())
			```
		lineageTag: 519b5cae-073f-4fc3-8914-7179ab06138a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Security NK'
		dataType: string
		lineageTag: 53ebc379-12e9-47e7-bbec-be4f34f626d3
		summarizeBy: none
		sourceColumn: Security NK

		annotation SummarizationSetBy = Automatic

	column 'Security Payment NK'
		dataType: string
		lineageTag: 3ad9e90a-2bb8-40ca-9885-4314f8b0aa3d
		summarizeBy: none
		sourceColumn: Security Payment NK

		annotation SummarizationSetBy = Automatic

	column 'As Of Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: ac99b5f9-7ca1-47ce-a117-11982c959412
		summarizeBy: none
		sourceColumn: As Of Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'As Of Period'
		dataType: int64
		formatString: 0
		lineageTag: 4d702d53-544a-46b3-936b-4f5f48a357c1
		summarizeBy: sum
		sourceColumn: As Of Period

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 165dd14b-de90-4935-9630-d39478105890
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Src Position ID'
		dataType: int64
		formatString: 0
		lineageTag: 655af53f-e837-4bd4-98bb-7601a516ac19
		summarizeBy: count
		sourceColumn: Src Position ID

		annotation SummarizationSetBy = Automatic

	column 'Src Security ID'
		dataType: string
		lineageTag: 0f8f1474-5562-4882-a5df-5013c5001487
		summarizeBy: none
		sourceColumn: Src Security ID

		annotation SummarizationSetBy = Automatic

	column 'Src Market ID'
		dataType: string
		lineageTag: 68ffff22-72b4-4697-9fea-d16d386da6af
		summarizeBy: none
		sourceColumn: Src Market ID

		annotation SummarizationSetBy = Automatic

	column 'Src Security'
		dataType: string
		lineageTag: 2b9679e7-a31c-4199-8000-5a2abd1d302e
		summarizeBy: none
		sourceColumn: Src Security

		annotation SummarizationSetBy = Automatic

	column 'Asset Portfolio Code'
		dataType: string
		lineageTag: 83f101bc-e65f-463e-bd40-18acf7c75b49
		summarizeBy: none
		sourceColumn: Asset Portfolio Code

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Group Code'
		dataType: string
		lineageTag: 2ceed88d-d0b9-452a-9543-8d3b6f0df96e
		summarizeBy: none
		sourceColumn: Portfolio Group Code

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Code'
		dataType: string
		lineageTag: 167a632e-40a9-4c34-b39f-75f7275342b2
		summarizeBy: none
		sourceColumn: Portfolio Code

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Nk'
		dataType: string
		lineageTag: a090c229-8caf-4b37-938b-1d13b4ccbec0
		summarizeBy: none
		sourceColumn: Portfolio Nk

		annotation SummarizationSetBy = Automatic

	column 'Framework Code'
		dataType: string
		lineageTag: 5fbe28e6-6405-49c2-8512-ec6a5ecdbb2a
		summarizeBy: none
		sourceColumn: Framework Code

		annotation SummarizationSetBy = Automatic

	column 'GL Class'
		dataType: string
		lineageTag: b3c1a642-e125-41bc-a052-a9a88999b04a
		summarizeBy: none
		sourceColumn: GL Class

		annotation SummarizationSetBy = Automatic

	column 'Wash Sale Parent Security ID'
		dataType: string
		lineageTag: 1287b767-777d-4983-89e4-99c3a4c8b9dc
		summarizeBy: none
		sourceColumn: Wash Sale Parent Security ID

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Code & Name'
		dataType: string
		lineageTag: 4270fdd6-60df-487e-a818-f9c647c600c2
		summarizeBy: none
		sourceColumn: Portfolio Code & Name

		annotation SummarizationSetBy = Automatic

	column 'Accounting Unit Code & Name'
		dataType: string
		lineageTag: c9d453a3-4982-4d16-9208-746df5a55d60
		summarizeBy: none
		sourceColumn: Accounting Unit Code & Name

		annotation SummarizationSetBy = Automatic

	column 'Company Code & Name'
		dataType: string
		lineageTag: 87d340d8-c102-4987-9cd1-0f2d1a08d338
		summarizeBy: none
		sourceColumn: Company Code & Name

		annotation SummarizationSetBy = Automatic

	column 'SCD Security ID'
		dataType: string
		lineageTag: 5c8b5f4f-1937-4407-b0a3-de3579d23c3a
		summarizeBy: none
		sourceColumn: SCD Security ID

		annotation SummarizationSetBy = Automatic

	column Leg
		dataType: double
		lineageTag: 305d252f-3ad8-4d37-8cce-d02f1fe139c1
		summarizeBy: sum
		sourceColumn: Leg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Calculated Date'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		lineageTag: 74d61306-9fb8-4fa6-809b-2048565c5ea9
		summarizeBy: none
		sourceColumn: Calculated Date

		annotation SummarizationSetBy = Automatic

	column 'Units (D)'
		dataType: double
		lineageTag: b6dd429c-b72a-4801-8f6d-df55476d64aa
		summarizeBy: sum
		sourceColumn: Units (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Contracts
		dataType: double
		lineageTag: be3cfdda-429d-4843-a1c6-cde61f28c602
		summarizeBy: sum
		sourceColumn: Contracts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Settle Trade Balance'
		dataType: double
		lineageTag: b587b345-e7a9-4847-8a17-675511b6d477
		summarizeBy: sum
		sourceColumn: Settle Trade Balance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Original Face (D)'
		dataType: double
		lineageTag: e0ee0949-0115-4715-a0bf-92948c94160e
		summarizeBy: sum
		sourceColumn: Original Face (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pool Factor'
		dataType: double
		lineageTag: ca18e94f-deb8-44a3-b7a2-32d0c59eb44c
		summarizeBy: sum
		sourceColumn: Pool Factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Basis'
		dataType: string
		lineageTag: 0ffd1a17-b791-483e-824f-137dc5b0b090
		summarizeBy: none
		sourceColumn: Unit Basis

		annotation SummarizationSetBy = Automatic

	column 'Nominal (D)'
		dataType: double
		lineageTag: d305b1cf-9e7c-4a9c-89c1-3d98ff251275
		summarizeBy: sum
		sourceColumn: Nominal (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quote Factor'
		dataType: double
		lineageTag: 8a002358-1b02-4283-8fb3-dfc25c5ca5c4
		summarizeBy: sum
		sourceColumn: Quote Factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Current Face (D)'
		dataType: double
		lineageTag: 2f9514fa-fdc1-4221-b2df-a2e76e276522
		summarizeBy: sum
		sourceColumn: Current Face (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fair Value Accrued - Base'
		dataType: double
		lineageTag: c14e5ae7-52f7-4ef3-ab8b-23e6071482fe
		summarizeBy: sum
		sourceColumn: Fair Value Accrued - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fair Value Unaccrued - Base'
		dataType: double
		lineageTag: e7939490-ecd2-4d28-84de-0daa59aa8449
		summarizeBy: sum
		sourceColumn: Fair Value Unaccrued - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Original Cost - Base'
		dataType: double
		lineageTag: fb41c3e9-3efd-4953-9d3c-8a58474ef95f
		summarizeBy: sum
		sourceColumn: Original Cost - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price - Base'
		dataType: double
		lineageTag: b9056c3e-05ab-4d1d-96d0-2378a4d4f44e
		summarizeBy: sum
		sourceColumn: Price - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Cost - Base'
		dataType: double
		lineageTag: 92562e9d-0572-446b-bc14-fef355b20e7b
		summarizeBy: sum
		sourceColumn: Unit Cost - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unrealized Gain/Loss CCY - Base'
		dataType: double
		lineageTag: dbb4743a-4a0e-4b5d-8b20-9b4f777cace8
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss CCY - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unrealized Gain/Loss Sec - Base'
		dataType: double
		lineageTag: 5229cb96-0f28-4355-bd24-8703994f8434
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss Sec - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unrealized Gain/Loss - Base'
		dataType: double
		lineageTag: 8da742e5-caf2-4911-8f8e-e755ef58419f
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Accrual - Base'
		dataType: double
		lineageTag: 892181c6-1807-40af-a9ae-de7634b75de9
		summarizeBy: sum
		sourceColumn: Accrual - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Withheld - Base'
		dataType: double
		lineageTag: 577091a2-f77e-47ac-8e31-281ea0d42215
		summarizeBy: sum
		sourceColumn: Withheld - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Withholding Rate'
		dataType: double
		lineageTag: f080fc22-10b7-4b81-8c32-82d7ab7aa840
		summarizeBy: sum
		sourceColumn: Withholding Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local Exchange Rate'
		dataType: double
		lineageTag: 4860150d-5a45-4fc4-9748-ff5782299f48
		summarizeBy: sum
		sourceColumn: Local Exchange Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fair Value Accrued - Local (D)'
		dataType: double
		lineageTag: 4161339a-401a-4b6f-92cd-bea67cdfad60
		summarizeBy: sum
		sourceColumn: Fair Value Accrued - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Accounting Status'
		dataType: string
		lineageTag: c8d7a23a-6a59-4272-9469-28eb3cae5f06
		summarizeBy: none
		sourceColumn: Accounting Status

		annotation SummarizationSetBy = Automatic

	column 'Portfolio Calculation'
		dataType: string
		lineageTag: c7860a14-6faa-49f6-afc7-0e2e79c5bd79
		summarizeBy: none
		sourceColumn: Portfolio Calculation

		annotation SummarizationSetBy = Automatic

	column 'Fair Value Unaccrued - Local (D)'
		dataType: double
		lineageTag: 823b86e7-fd78-4632-ba0e-789f408f4aa1
		summarizeBy: sum
		sourceColumn: Fair Value Unaccrued - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price - Local (D)'
		dataType: double
		lineageTag: 63c0c6f4-536b-4a9e-8f91-481c0a62c6b5
		summarizeBy: sum
		sourceColumn: Price - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Original Cost - Local (D)'
		dataType: double
		lineageTag: 12f738cb-f1ce-4189-91b0-7d277dea398e
		summarizeBy: sum
		sourceColumn: Original Cost - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Cost - Local (D)'
		dataType: double
		lineageTag: 0d603ea5-fc14-4108-a6ee-9773b4bd33bf
		summarizeBy: sum
		sourceColumn: Unit Cost - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unrealized Gain/Loss CCY - Local (D)'
		dataType: double
		lineageTag: dc30070c-4db4-4f66-bac6-4626386f7258
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss CCY - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unrealized Gain/Loss Sec - Local (D)'
		dataType: double
		lineageTag: 90215048-425c-498c-a7df-1365927b477f
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss Sec - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unrealized Gain/Loss - Local (D)'
		dataType: double
		lineageTag: fb6efe40-43f9-4fc2-be22-760bfb544265
		summarizeBy: sum
		sourceColumn: Unrealized Gain/Loss - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Accrual - Local (D)'
		dataType: double
		lineageTag: 162d0b50-20fb-4c0b-9fc9-f611454e9da8
		summarizeBy: sum
		sourceColumn: Accrual - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Withheld - Local (D)'
		dataType: double
		lineageTag: 7dc18825-e479-48e5-84d4-55edca5850f8
		summarizeBy: sum
		sourceColumn: Withheld - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Amortized Cost - Base'
		dataType: double
		lineageTag: a7885a77-3511-4966-b770-eb1bb5c540d1
		summarizeBy: sum
		sourceColumn: Amortized Cost - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Yield
		dataType: double
		lineageTag: 02b9ce97-366e-4430-9cf6-eea07a380343
		summarizeBy: sum
		sourceColumn: Yield

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Yield To Worst'
		dataType: double
		lineageTag: 8b0c6ca0-948c-4ee0-9bba-09d08c487a49
		summarizeBy: sum
		sourceColumn: Yield To Worst

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Underlier Security Nk'
		dataType: string
		lineageTag: f128ddf1-463f-4c82-8da8-1f285c92e6cd
		summarizeBy: none
		sourceColumn: Underlier Security Nk

		annotation SummarizationSetBy = Automatic

	column Local
		dataType: string
		lineageTag: 991591fa-83c1-40ef-8ba1-c0dc20fbb9fd
		summarizeBy: none
		sourceColumn: Local

		annotation SummarizationSetBy = Automatic

	column Base
		dataType: string
		lineageTag: 928b6905-2f1f-414c-8a39-da35b88a3b29
		summarizeBy: none
		sourceColumn: Base

		annotation SummarizationSetBy = Automatic

	column 'Local Currency'
		dataType: string
		lineageTag: 5bf69dcd-3c83-4895-b367-892ed0ed42ce
		summarizeBy: none
		sourceColumn: Local Currency

		annotation SummarizationSetBy = Automatic

	column 'SCD Country'
		dataType: string
		lineageTag: feba8fcd-62a1-4de2-8d68-6e3fec44fa8d
		summarizeBy: none
		sourceColumn: SCD Country

		annotation SummarizationSetBy = Automatic

	column 'Country Name'
		dataType: string
		lineageTag: c6887d68-69e6-4f34-a833-27d1cd3c52d0
		summarizeBy: none
		sourceColumn: Country Name

		annotation SummarizationSetBy = Automatic

	column 'Maturity Date Final'
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: 1ef9349a-0b58-454a-ae68-a192a2b95360
		summarizeBy: none
		sourceColumn: Maturity Date Final

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'SCD Coupon (D)'
		dataType: double
		lineageTag: cd59abc0-eedd-466b-baf2-d179bab122bb
		summarizeBy: sum
		sourceColumn: SCD Coupon (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Next Payment - Local'
		dataType: double
		lineageTag: 6de685bf-1df4-4651-bb20-aa4b45254dd8
		summarizeBy: sum
		sourceColumn: Next Payment - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Next Payment - Base'
		dataType: double
		lineageTag: b0cfcda0-9407-4ef8-b6d0-60fddeb6f3ec
		summarizeBy: sum
		sourceColumn: Next Payment - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Repo Maturity Amount'
		dataType: double
		lineageTag: 06d73a4f-c2ca-4d84-acfd-aa845b931af3
		summarizeBy: sum
		sourceColumn: Repo Maturity Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Index Value'
		dataType: double
		lineageTag: f248a229-c64d-4aa8-b7c6-9d7466806669
		summarizeBy: sum
		sourceColumn: Index Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Composite ID BB Global'
		dataType: string
		lineageTag: 7e304bf6-469c-401a-98a3-a24875189673
		summarizeBy: none
		sourceColumn: Composite ID BB Global

		annotation SummarizationSetBy = Automatic

	column Counterparty
		dataType: string
		lineageTag: 0cd077bf-a6a3-4622-853f-0af8ccbcf28e
		summarizeBy: none
		sourceColumn: Counterparty

		annotation SummarizationSetBy = Automatic

	column 'Ultimate Parent Country'
		dataType: string
		lineageTag: d87fab2a-6157-4b99-87fc-34287e097e44
		summarizeBy: none
		sourceColumn: Ultimate Parent Country

		annotation SummarizationSetBy = Automatic

	column 'Next Coupon Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 266cd908-687d-4eb9-a725-067a9d1ca21e
		summarizeBy: none
		sourceColumn: Next Coupon Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'SCD Security Type'
		dataType: string
		lineageTag: 909cf378-d0fe-4512-8ae9-c7bb858ad716
		summarizeBy: none
		sourceColumn: SCD Security Type

		annotation SummarizationSetBy = Automatic

	column 'St Classification'
		dataType: string
		lineageTag: 5d15c606-6d1b-4e16-b212-259cb55a5718
		summarizeBy: none
		sourceColumn: St Classification

		annotation SummarizationSetBy = Automatic

	column 'Equity Asset Class'
		dataType: string
		lineageTag: a42ba4f4-236d-48cf-bbda-dbde71052d96
		summarizeBy: none
		sourceColumn: Equity Asset Class

		annotation SummarizationSetBy = Automatic

	column 'Fixed Income Asset Class'
		dataType: string
		lineageTag: 9c1c09cf-8102-4ca5-825f-f400f85fac46
		summarizeBy: none
		sourceColumn: Fixed Income Asset Class

		annotation SummarizationSetBy = Automatic

	column 'Security ID 2'
		dataType: string
		lineageTag: 29035763-3c47-4b03-9765-9e229225071e
		summarizeBy: none
		sourceColumn: Security ID 2

		annotation SummarizationSetBy = Automatic

	column 'Issuer Name'
		dataType: string
		lineageTag: 0aa9b098-4314-4371-91cc-e1f704c49ed8
		summarizeBy: none
		sourceColumn: Issuer Name

		annotation SummarizationSetBy = Automatic

	column 'Jr ID'
		dataType: string
		lineageTag: 40ac37e2-e9fc-467b-b7b5-63b980d46b8c
		summarizeBy: none
		sourceColumn: Jr ID

		annotation SummarizationSetBy = Automatic

	column 'Jr Name'
		dataType: string
		lineageTag: 9a109ab7-1da9-4cd5-bb9b-847bb2bd5fa1
		summarizeBy: none
		sourceColumn: Jr Name

		annotation SummarizationSetBy = Automatic

	column 'Parent Issuer'
		dataType: string
		lineageTag: d7d5e601-4f1f-41ce-a842-dc216202d37f
		summarizeBy: none
		sourceColumn: Parent Issuer

		annotation SummarizationSetBy = Automatic

	column Portamv
		dataType: double
		lineageTag: 84a01dff-6136-4146-bfb7-829f85c8f0b2
		summarizeBy: sum
		sourceColumn: Portamv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Portbc
		dataType: double
		lineageTag: aa8fda3e-eb1f-4511-bbad-48161159cdd4
		summarizeBy: sum
		sourceColumn: Portbc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Groupamv
		dataType: double
		lineageTag: 3df77cad-3ff2-479a-9548-dd919b4ecead
		summarizeBy: sum
		sourceColumn: Groupamv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Groupbc
		dataType: double
		lineageTag: 7f328042-d0e7-4483-ada5-ffd5409660b2
		summarizeBy: sum
		sourceColumn: Groupbc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Blocktrade Bbg ID'
		dataType: string
		lineageTag: 3b0eb8cb-e72f-4640-a041-75e710b4a981
		summarizeBy: none
		sourceColumn: Blocktrade Bbg ID

		annotation SummarizationSetBy = Automatic

	column 'Off Balance Cost'
		dataType: double
		lineageTag: 7662871a-2e13-4d5d-83da-4678fc9f8ec7
		summarizeBy: sum
		sourceColumn: Off Balance Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Swap Index'
		dataType: string
		lineageTag: bb9cf256-f286-4495-8c63-9b6fe4cc9859
		summarizeBy: none
		sourceColumn: Swap Index

		annotation SummarizationSetBy = Automatic

	column 'Day Count'
		dataType: string
		lineageTag: c5c715fe-41b9-485d-a64a-9e8556ad75ee
		summarizeBy: none
		sourceColumn: Day Count

		annotation SummarizationSetBy = Automatic

	column 'Pay Frequency'
		dataType: string
		lineageTag: cf5fabaa-e16b-4156-93cf-60a9823374e6
		summarizeBy: none
		sourceColumn: Pay Frequency

		annotation SummarizationSetBy = Automatic

	column 'Reset Frequency'
		dataType: string
		lineageTag: 2829aba3-8614-45a3-985b-c3d8ef073b7d
		summarizeBy: none
		sourceColumn: Reset Frequency

		annotation SummarizationSetBy = Automatic

	column 'Month End Status'
		dataType: string
		lineageTag: cb7140ea-0e93-4039-83f1-e1e77d1ace91
		summarizeBy: none
		sourceColumn: Month End Status

		annotation SummarizationSetBy = Automatic

	column 'Price Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 893d94c5-f1c4-47cb-b773-33753cd028e8
		summarizeBy: none
		sourceColumn: Price Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Domicile Country Code'
		dataType: string
		lineageTag: 8f5456ae-4e3f-4942-81ed-a36276042393
		summarizeBy: none
		sourceColumn: Domicile Country Code

		annotation SummarizationSetBy = Automatic

	column 'Asia Asset Class Code Indonesia'
		dataType: string
		lineageTag: cf38fcb2-4c42-48e2-980f-bda35139a4f3
		summarizeBy: none
		sourceColumn: Asia Asset Class Code Indonesia

		annotation SummarizationSetBy = Automatic

	column 'Asia Asset Class Code Vietnam'
		dataType: string
		lineageTag: b103d0df-4ace-4e9c-a731-c45ad664b5ce
		summarizeBy: none
		sourceColumn: Asia Asset Class Code Vietnam

		annotation SummarizationSetBy = Automatic

	column 'Asia Asset Class Desc Indonesia'
		dataType: string
		lineageTag: dcf97d8c-8365-4e89-9c03-42e4da994827
		summarizeBy: none
		sourceColumn: Asia Asset Class Desc Indonesia

		annotation SummarizationSetBy = Automatic

	column 'Asia Asset Class Desc Vietnam'
		dataType: string
		lineageTag: 67575036-d494-4f2e-ba3c-24859bdff7bd
		summarizeBy: none
		sourceColumn: Asia Asset Class Desc Vietnam

		annotation SummarizationSetBy = Automatic

	column 'Functional Ccy Code'
		dataType: string
		lineageTag: 6d6ff986-a594-4fd1-85fe-7bdad51d5ce1
		summarizeBy: none
		sourceColumn: Functional Ccy Code

		annotation SummarizationSetBy = Automatic

	column 'Local to Func Rate'
		dataType: double
		lineageTag: f8a5009e-a92e-408f-a961-283028c61deb
		summarizeBy: sum
		sourceColumn: Local to Func Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local to CAD Rate'
		dataType: double
		lineageTag: 40863a46-e083-4af9-80c9-ebd2553048c3
		summarizeBy: sum
		sourceColumn: Local to CAD Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local to USD Rate'
		dataType: double
		lineageTag: e39c1fe5-b96a-4905-9b45-026d47d606ef
		summarizeBy: sum
		sourceColumn: Local to USD Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local to HKD Rate'
		dataType: double
		lineageTag: b51ed1cd-f8a2-4e1a-961b-84b1bfa36282
		summarizeBy: sum
		sourceColumn: Local to HKD Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Next Coupon Amount (D)'
		dataType: double
		lineageTag: 3b53e091-234b-490c-8209-c8ff45d6fef1
		summarizeBy: sum
		sourceColumn: Next Coupon Amount (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Hedge Par'
		dataType: double
		lineageTag: ff486cd4-cd4a-464c-b9cf-efc1a46b5485
		summarizeBy: sum
		sourceColumn: AOCI Hedge Par

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Remain Balance Non BV - Base'
		dataType: double
		lineageTag: 8d7177ab-9e31-475a-b078-e6dbe94e868e
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance Non BV - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Remain Balance Non BV - Local (D)'
		dataType: double
		lineageTag: 40bc7fe1-8d02-4941-8f60-27f6fb7eb6fe
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance Non BV - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Remain Balance Rep - Base'
		dataType: double
		lineageTag: 9ddfee99-2fc2-4b41-8ac1-b1c1a988dbb0
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance Rep - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Remain Balance Rep - Local (D)'
		dataType: double
		lineageTag: a22810b9-f230-4fd6-ab13-fd696797052b
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance Rep - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Commitment - Local'
		dataType: double
		lineageTag: defd010f-894f-4d80-bdb3-32e270396291
		summarizeBy: sum
		sourceColumn: Balance Commitment - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Income Default Amount - Local (D)'
		dataType: double
		lineageTag: b24e01e7-f428-4f5f-8713-d50bd4e0d722
		summarizeBy: sum
		sourceColumn: Income Default Amount - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Income Default Amount - Base'
		dataType: double
		lineageTag: b09cda7e-8e8c-4c90-9f72-a21a129abcf4
		summarizeBy: sum
		sourceColumn: Income Default Amount - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Next Interest Payment - Local'
		dataType: double
		lineageTag: f15b322a-7cef-4361-94bb-75b4d3444f86
		summarizeBy: sum
		sourceColumn: Next Interest Payment - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Next Interest Payment - Base'
		dataType: double
		lineageTag: 2d77060b-46c5-4e1a-b2ac-5137e08328a9
		summarizeBy: sum
		sourceColumn: Next Interest Payment - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Next Principal Payment - Local'
		dataType: double
		lineageTag: e329e8da-d888-4055-989f-300c9f787e77
		summarizeBy: sum
		sourceColumn: Next Principal Payment - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Next Principal Payment - Base'
		dataType: double
		lineageTag: fe66df12-78d8-49cd-a0f6-9c8ee3ae729f
		summarizeBy: sum
		sourceColumn: Next Principal Payment - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pos Accrual - Base'
		dataType: double
		lineageTag: 4a51553b-c44c-41ea-b58d-8e61707f4fe7
		summarizeBy: sum
		sourceColumn: Pos Accrual - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Next Dividend - Local (D)'
		dataType: double
		lineageTag: 87989cad-2bdc-4202-819f-94a4b8405a4b
		summarizeBy: sum
		sourceColumn: Next Dividend - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Current Yield Book Price (D)'
		dataType: double
		lineageTag: 864ce250-2713-427d-a3d9-aeaf9d25a971
		summarizeBy: sum
		sourceColumn: Current Yield Book Price (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Convexity
		dataType: double
		lineageTag: 67527ab2-6221-46e1-8f28-b019b77025e2
		summarizeBy: sum
		sourceColumn: Convexity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Current Yield (D)'
		dataType: double
		lineageTag: 8fa8bd49-25f5-4b76-82e7-3b01b1fcaf3d
		summarizeBy: sum
		sourceColumn: Current Yield (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dirty Price'
		dataType: double
		lineageTag: 9f148561-0079-48ec-9f45-221a34d366a3
		summarizeBy: sum
		sourceColumn: Dirty Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Modified Duration YTM'
		dataType: double
		lineageTag: 6af5cd29-8b7d-473c-af4f-9d53cb7faaaa
		summarizeBy: sum
		sourceColumn: Modified Duration YTM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Modified Duration YC'
		dataType: double
		lineageTag: a0c82686-13b1-4c07-8698-2e964ba8ea0c
		summarizeBy: sum
		sourceColumn: Modified Duration YC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Original Book Yield (D)'
		dataType: double
		lineageTag: 6aed75b2-21bc-4b99-aa98-cbc2c99bfdaf
		summarizeBy: sum
		sourceColumn: Original Book Yield (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Cost Value - Local'
		dataType: double
		lineageTag: 4313e513-9f3b-42a5-a902-44cdecd10ffd
		summarizeBy: sum
		sourceColumn: Balance Cost Value - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Cost Value - Base'
		dataType: double
		lineageTag: 7e661569-a007-4990-ba79-2e957a6416aa
		summarizeBy: sum
		sourceColumn: Balance Cost Value - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Book Value - Local (D)'
		dataType: double
		lineageTag: 68fde057-d560-44d6-92dc-d0f8654a8f5d
		summarizeBy: sum
		sourceColumn: Book Value - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Book Value - Base'
		dataType: double
		lineageTag: 5d209ffc-92f9-401d-9285-d86bdfc2a5ff
		summarizeBy: sum
		sourceColumn: Book Value - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Int Appr - Local'
		dataType: double
		lineageTag: b9625fa5-d9d9-468e-b76c-706514ea386f
		summarizeBy: sum
		sourceColumn: Balance Int Appr - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Int Appr - Base'
		dataType: double
		lineageTag: 7b956b4a-ac46-4636-8b05-a07cc11335ba
		summarizeBy: sum
		sourceColumn: Balance Int Appr - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance OID Appr - Local'
		dataType: double
		lineageTag: 971d7831-57e8-4011-87be-e6aaee412999
		summarizeBy: sum
		sourceColumn: Balance OID Appr - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance OID Appr - Base'
		dataType: double
		lineageTag: 7e51362f-28a5-42bf-bdc1-8ffdabcf6e19
		summarizeBy: sum
		sourceColumn: Balance OID Appr - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance CL Allowance - Local'
		dataType: double
		lineageTag: ac33c782-b605-4479-8f9a-01a522b19266
		summarizeBy: sum
		sourceColumn: Balance CL Allowance - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance CL Allowance - Base'
		dataType: double
		lineageTag: aaea43bb-e94f-42f8-9865-5d54bdf70110
		summarizeBy: sum
		sourceColumn: Balance CL Allowance - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Recog CL Allowance - Local'
		dataType: double
		lineageTag: 1d24650a-2d35-403a-a63a-94828bf749a6
		summarizeBy: sum
		sourceColumn: Balance Recog CL Allowance - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Recog CL Allowance - Base'
		dataType: double
		lineageTag: 2e653219-959c-4ef0-b006-2627f526fe25
		summarizeBy: sum
		sourceColumn: Balance Recog CL Allowance - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Write Off - Local'
		dataType: double
		lineageTag: 6b37b71c-f23a-40f6-9ba3-cc955b3295bf
		summarizeBy: sum
		sourceColumn: Balance Write Off - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Write Off - Base'
		dataType: double
		lineageTag: 6766f4ce-08d4-46fe-b510-346ac66b5d98
		summarizeBy: sum
		sourceColumn: Balance Write Off - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Impairment - Local'
		dataType: double
		lineageTag: c4302e49-4e32-4f6c-a7be-4a1e90bf46d2
		summarizeBy: sum
		sourceColumn: Balance Impairment - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Impairment - Base'
		dataType: double
		lineageTag: 23be3aa1-ba34-4605-bc30-cea9409bfb31
		summarizeBy: sum
		sourceColumn: Balance Impairment - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Remain Balance BV - Local (D)'
		dataType: double
		lineageTag: 86a8d99f-92fc-46bc-8e7a-6ed3bba94e9e
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance BV - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AOCI Remain Balance BV - Base'
		dataType: double
		lineageTag: 2ef58381-d7f2-4452-bbf5-ebb2747a5682
		summarizeBy: sum
		sourceColumn: AOCI Remain Balance BV - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Deferred PL - Local (D)'
		dataType: double
		lineageTag: 630d27c5-e314-4c35-92a1-59f1f9fff777
		summarizeBy: sum
		sourceColumn: Balance Deferred PL - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Deferred PL - Base'
		dataType: double
		lineageTag: 2f424abd-05ed-4bcf-addf-53749e6ce2cc
		summarizeBy: sum
		sourceColumn: Balance Deferred PL - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Income Accrual - Local (D)'
		dataType: double
		lineageTag: 915228e4-9395-4405-bc41-b1bab194af3d
		summarizeBy: sum
		sourceColumn: Income Accrual - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Income Accrual - Base'
		dataType: double
		lineageTag: 13db261c-5c41-48d4-ab91-37dfbf54cfab
		summarizeBy: sum
		sourceColumn: Income Accrual - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Expected Restitution - Local'
		dataType: double
		lineageTag: b13a64be-32d0-4854-9deb-fc94533be5d2
		summarizeBy: sum
		sourceColumn: Balance Expected Restitution - Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Expected Restitution - Base'
		dataType: double
		lineageTag: 4ff75c62-a3a0-4565-adc5-1c9d5e8326c2
		summarizeBy: sum
		sourceColumn: Balance Expected Restitution - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Carrying Value - Local (D)'
		dataType: double
		lineageTag: c7ad0920-f4b5-48b8-bde3-d69d92ed0406
		summarizeBy: sum
		sourceColumn: Carrying Value - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Carrying Value - Base'
		dataType: double
		lineageTag: 5484a76f-2443-4d9a-b20e-fd180075c431
		summarizeBy: sum
		sourceColumn: Carrying Value - Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Updated Ts'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss AM/PM
		lineageTag: 2df0be10-e3c5-41e9-bdc9-3558fd82b5f4
		summarizeBy: none
		sourceColumn: Updated Ts

		annotation SummarizationSetBy = Automatic

	column 'Adjusted Book Value Local'
		dataType: double
		lineageTag: df95898d-dd05-4693-b2bd-568ca170b8f3
		summarizeBy: sum
		sourceColumn: Adjusted Book Value Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adjusted Book Value Base'
		dataType: double
		lineageTag: d960b131-5d79-4294-be8f-d44b0ce3ba77
		summarizeBy: sum
		sourceColumn: Adjusted Book Value Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SCD Issuer Long Company Name'
		dataType: string
		lineageTag: 7cabd884-08ba-4dd1-ad86-c058e86cf626
		summarizeBy: none
		sourceColumn: SCD Issuer Long Company Name

		annotation SummarizationSetBy = Automatic

	column 'SCD Default Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 8896093c-db8d-41c9-bc84-ef1dd91b7a80
		summarizeBy: none
		sourceColumn: SCD Default Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Accrue In Default'
		dataType: string
		lineageTag: b9e1305d-f230-48be-abe9-7da6d57a0494
		summarizeBy: none
		sourceColumn: Accrue In Default

		annotation SummarizationSetBy = Automatic

	column 'Unsettled Int Div Amount Base CCY'
		dataType: double
		lineageTag: 4612ac3d-ad06-4281-b42b-7e6ef2296ecf
		summarizeBy: sum
		sourceColumn: Unsettled Int Div Amount Base CCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unsettled Int Div Amount Local CCY'
		dataType: double
		lineageTag: 95a15a43-dd2a-453a-89fd-5e5e675e5b62
		summarizeBy: sum
		sourceColumn: Unsettled Int Div Amount Local CCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Acquisition Pre Dis Base CCY'
		dataType: double
		lineageTag: 6be2027d-4390-41d8-a0e0-688f8d0d5451
		summarizeBy: sum
		sourceColumn: Balance Acquisition Pre Dis Base CCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Acquisition Pre Dis Local CCY'
		dataType: double
		lineageTag: 0eb5fef9-8003-400b-bf6b-2f1b485fd2dc
		summarizeBy: sum
		sourceColumn: Balance Acquisition Pre Dis Local CCY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Purpose
		dataType: string
		lineageTag: 4213af6a-9973-4e43-8c6f-d0ceb36b1a83
		summarizeBy: none
		sourceColumn: Purpose

		annotation SummarizationSetBy = Automatic

	column 'IFRS9 Purpose'
		dataType: string
		lineageTag: 8a62a695-401f-4e46-b0be-3ac2842877ee
		summarizeBy: none
		sourceColumn: IFRS9 Purpose

		annotation SummarizationSetBy = Automatic

	column 'Balance Book Value Local Native'
		dataType: double
		lineageTag: 5c950ff0-9744-4140-bee2-6d28b2796f7b
		summarizeBy: sum
		sourceColumn: Balance Book Value Local Native

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Book Value Base Native'
		dataType: double
		lineageTag: 460c0d5e-b33b-4b1b-9f72-8dab0cd99523
		summarizeBy: sum
		sourceColumn: Balance Book Value Base Native

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Calculation Date Full'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 5f7553f3-cf81-4e38-995d-db97d88c5ec0
		summarizeBy: none
		sourceColumn: Calculation Date Full

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Long Short Indicator'
		dataType: string
		lineageTag: 53d73d3c-8354-46b1-9608-e8d27029bb02
		summarizeBy: none
		sourceColumn: Long Short Indicator

		annotation SummarizationSetBy = Automatic

	column 'Accrued Interest EOP Local'
		dataType: double
		lineageTag: 1d3da0bf-b92f-4a4a-8286-4094e1788b77
		summarizeBy: sum
		sourceColumn: Accrued Interest EOP Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Accrued Interest EOP Base'
		dataType: double
		lineageTag: 824436cf-c316-43a7-83e8-4169f30e6597
		summarizeBy: sum
		sourceColumn: Accrued Interest EOP Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Return Of Capital Base'
		dataType: double
		lineageTag: 3f3d20d1-f096-44ad-938b-695fea02763c
		summarizeBy: sum
		sourceColumn: Balance Return Of Capital Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Return Of Capital Local'
		dataType: double
		lineageTag: 31f3397a-6d60-4dc0-8484-7aa1d5554ad4
		summarizeBy: sum
		sourceColumn: Balance Return Of Capital Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Called Capital Base'
		dataType: double
		lineageTag: 6da14a77-738d-4f6b-9fed-d2bfea7527f3
		summarizeBy: sum
		sourceColumn: Balance Called Capital Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Called Capital Local'
		dataType: double
		lineageTag: 195d3cc2-a818-47d1-b405-1c6c8d4b26c4
		summarizeBy: sum
		sourceColumn: Balance Called Capital Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Recallable Base'
		dataType: double
		lineageTag: a43fd929-95df-43b9-8a63-f0dead107a09
		summarizeBy: sum
		sourceColumn: Balance Recallable Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance Recallable Local'
		dataType: double
		lineageTag: bfe5c6e8-a315-49f9-92ce-2e501df9e319
		summarizeBy: sum
		sourceColumn: Balance Recallable Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance NAIC Carrying Value Local'
		dataType: double
		lineageTag: aac06614-f875-429d-8784-091afbfbb444
		summarizeBy: sum
		sourceColumn: Balance NAIC Carrying Value Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance NAIC Carrying Value Base'
		dataType: double
		lineageTag: 3487ef99-e2f8-4bc2-b057-d3e16e9aecfb
		summarizeBy: sum
		sourceColumn: Balance NAIC Carrying Value Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance NAIC Sec Adj Local'
		dataType: double
		lineageTag: 02aa18fb-fb8c-4428-af56-87e53c4e55ec
		summarizeBy: sum
		sourceColumn: Balance NAIC Sec Adj Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Balance NAIC Sec Adj Base'
		dataType: double
		lineageTag: e9aadb73-3b70-46ca-9c46-a93baf815e16
		summarizeBy: sum
		sourceColumn: Balance NAIC Sec Adj Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Amortized Cost - Local (D)'
		dataType: double
		lineageTag: 256d9392-c529-484a-a627-ce331a7fa94d
		summarizeBy: sum
		sourceColumn: Amortized Cost - Local (D)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Calculated Unrealized Gain/Loss – Local'
		dataType: double
		sourceProviderType: float
		lineageTag: 8c166774-6f13-4bce-8487-ca6c90906c5e
		summarizeBy: sum
		sourceColumn: Calculated Unrealized Gain/Loss – Local

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ML Business Group'
		dataType: string
		lineageTag: 342161b5-43f3-4277-992e-e099adf67170
		summarizeBy: none
		sourceColumn: ML Business Group

		annotation SummarizationSetBy = Automatic

	column 'SCD GL Classification'
		dataType: string
		lineageTag: 3f82517e-3c3a-45a9-b87a-7d88d2389b2d
		summarizeBy: none
		sourceColumn: SCD GL Classification

		annotation SummarizationSetBy = Automatic

	column 'Issue Volume'
		dataType: double
		lineageTag: b53e1cf4-dc17-477e-ab43-6ab6ca151103
		summarizeBy: sum
		sourceColumn: Issue Volume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Structure
		dataType: string
		lineageTag: 05bb8e34-1fbb-4aaf-a785-0c447710527c
		summarizeBy: none
		sourceColumn: Structure

		annotation SummarizationSetBy = Automatic

	column 'Accrued Interest QC (Static)'
		dataType: double
		lineageTag: e03d51f0-a757-49f9-9e3d-1331a839a576
		summarizeBy: sum
		sourceColumn: Accrued Interest QC (Static)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Accrued Interest PC (Static)'
		dataType: double
		lineageTag: d96e70a2-9127-45ad-989d-828f3cadc2c7
		summarizeBy: sum
		sourceColumn: Accrued Interest PC (Static)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Portfolio Group1'
		dataType: string
		lineageTag: e9423705-3ff0-4188-96d1-c7a80e3d6726
		summarizeBy: none
		sourceColumn: Portfolio Group1

		annotation SummarizationSetBy = Automatic

	column 'Balance Unpaid Commitment'
		dataType: double
		lineageTag: af9937b0-fcc2-4723-9251-1f1e4f109691
		summarizeBy: sum
		sourceColumn: Balance Unpaid Commitment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Securities Position Fact-45d0d83e-38e2-4c71-8ba0-390013020027' = m
		mode: import
		source = ```
				let
				LastNDays= Text.From(#"Last N Days Position Data"),
				Sql = "SELECT
				  spos.`SECURITY_NK` AS `Security NK`,
				  spos.`SECURITY_PAYMENT_NK` AS `Security Payment NK`,
				  spos.`AS_OF_DT` AS `As Of Date`,
				  spos.`AS_OF_PERIOD` AS `As Of Period`,
				  spos.`REGION` AS `Region`,
				  CAST(spos.`SRC_POSITION_ID` AS INT) AS `Src Position ID`,
				  spos.`SRC_SECURITY_ID` AS `Src Security ID`,
				  spos.`SRC_MARKET_ID` AS `Src Market ID`,
				  spos.`SRC_SECURITY` AS `Src Security`,
				  spos.`ASSET_PORTFOLIO_CODE` AS `Asset Portfolio Code`,
				  spos.`PORTFOLIO_GROUP_CODE` AS `Portfolio Group Code`,
				  spos.`PORTFOLIO_CD` AS `Portfolio Code`,
				  spos.`PORTFOLIO_NK` AS `Portfolio Nk`,
				  spos.`FRAMEWORK_CD` AS `Framework Code`,
				  spos.`GL_CLASS` AS `GL Class`,
				  spos.`WASH_SALE_PARENT_SECURITY_ID` AS `Wash Sale Parent Security ID`,
				  spos.`PORTFOLIO_CODE_NAME` AS `Portfolio Code & Name`,
				  spos.`ACCOUNTING_UNIT_CODE_NAME` AS `Accounting Unit Code & Name`,
				  spos.`COMPANY_CODE_NAME` AS `Company Code & Name`,
				  spos.`SCD_SECURITY_ID` AS `SCD Security ID`,
				  spos.`LEG` AS `Leg`,
				  spos.`CALCULATED_DATE` AS `Calculated Date`,
				  spos.`UNITS` AS `Units (D)`,
				  spos.`CONTRACTS` AS `Contracts`,
				  spos.`SETTLE_TRADE_BALANCE` AS `Settle Trade Balance`,
				  spos.`ORIGINAL_FACE` AS `Original Face (D)`,
				  spos.`POOL_FACTOR` AS `Pool Factor`,
				  spos.`UNIT_BASIS` AS `Unit Basis`,
				  spos.`NOMINAL` AS `Nominal (D)`,
				  spos.`QUOTE_FACTOR` AS `Quote Factor`,
				  spos.`CURRENT_FACE` AS `Current Face (D)`,
				  spos.`ACCRUED_MARKET_VALUE_BASE` AS `Fair Value Accrued - Base`,
				  spos.`MARKET_VALUE_BASE` AS `Fair Value Unaccrued - Base`,
				  spos.`COST_BASE` AS `Original Cost - Base`,
				  spos.`PRICE_BASE` AS `Price - Base`,
				  spos.`UNIT_COST_BASE` AS `Unit Cost - Base`,
				  spos.`UNREALIZED_ON_CURRENCY_BASE` AS `Unrealized Gain/Loss CCY - Base`,
				  spos.`UNREALIZED_ON_INVESTMENT_BASE` AS `Unrealized Gain/Loss Sec - Base`,
				  spos.`UNREALIZED_BASE` AS `Unrealized Gain/Loss - Base`,
				  spos.`ACCRUAL_BASE` AS `Accrual - Base`,
				  spos.`WITHELD_AMOUNT_BASE` AS `Withheld - Base`,
				  spos.`WITHHOLDING_RATE` AS `Withholding Rate`,
				  spos.`LOCAL_EXCHANGE_RATE` AS `Local Exchange Rate`,
				  spos.`ACCRUED_MARKET_VALUE_LOCAL` AS `Fair Value Accrued - Local (D)`,
				  spos.`ACCOUNTING_STATUS` AS `Accounting Status`,
				  spos.`PORTFOLIO_CALCULATION` AS `Portfolio Calculation`,
				  spos.`MARKET_VALUE_LOCAL` AS `Fair Value Unaccrued - Local (D)`,
				  spos.`PRICE_LOCAL` AS `Price - Local (D)`,
				  spos.`COST_LOCAL` AS `Original Cost - Local (D)`,
				  spos.`UNIT_COST_LOCAL` AS `Unit Cost - Local (D)`,
				  spos.`UNREALIZED_ON_CURRENCY_LOCAL` AS `Unrealized Gain/Loss CCY - Local (D)`,
				  spos.`UNREALIZED_ON_INVESTMENT_LOCAL` AS `Unrealized Gain/Loss Sec - Local (D)`,
				  spos.`UNREALIZED_LOCAL` AS `Unrealized Gain/Loss - Local (D)`,
				  spos.`ACCRUAL_LOCAL` AS `Accrual - Local (D)`,
				  spos.`WITHELD_AMOUNT_LOCAL` AS `Withheld - Local (D)`,
				  spos.`AMORTIZED_COST_BASE` AS `Amortized Cost - Base`,
				  spos.`AMORTIZED_COST_LOCAL` AS `Amortized Cost - Local (D)`,
				  spos.`YIELD` AS `Yield`,
				  spos.`YIELD_TO_WORST` AS `Yield To Worst`,
				  spos.`UNDERLIER_SECURITY_NK` AS `Underlier Security Nk`,
				  spos.`LOCAL_CCY_CD` AS `Local`,
				  spos.`BASE` AS `Base`,
				  spos.`LOCAL_CURRENCY` AS `Local Currency`,
				  spos.`COUNTRY` AS `SCD Country`,
				  spos.`COUNTRY_NAME` AS `Country Name`,
				  spos.`MATURITY_DATE` AS `Maturity Date Final`,
				  spos.`COUPON` AS `SCD Coupon (D)`,
				  spos.`NEXT_PAYMENT_LOCAL` AS `Next Payment - Local`,
				  spos.`NEXT_PAYMENT_BASE` AS `Next Payment - Base`,
				  spos.`REPO_MATURITY_AMOUNT` AS `Repo Maturity Amount`,
				  spos.`INDEX_VALUE` AS `Index Value`,
				  spos.`COMPOSITE_ID_BB_GLOBAL` AS `Composite ID BB Global`,
				  spos.`COUNTERPARTY` AS `Counterparty`,
				  spos.`ULTIMATE_PARENT_COUNTRY` AS `Ultimate Parent Country`,
				  spos.`NEXT_COUPON_DATE` AS `Next Coupon Date`,
				  spos.`SCD_SECURITY_TYPE` AS `SCD Security Type`,
				  spos.`ST_CLASSIFICATION` AS `St Classification`,
				  spos.`EQUITY_ASSET_CLASS` AS `Equity Asset Class`,
				  spos.`FIXED_INCOME_ASSET_CLASS` AS `Fixed Income Asset Class`,
				  spos.`SECURITY_ID_2` AS `Security ID 2`,
				  spos.`ISSUER_NAME` AS `Issuer Name`,
				  spos.`JR_ID` AS `Jr ID`,
				  spos.`JR_NAME` AS `Jr Name`,
				  spos.`PARENT_ISSUER` AS `Parent Issuer`,
				  spos.`PORTAMV` AS `Portamv`,
				  spos.`PORTBC` AS `Portbc`,
				  spos.`GROUPAMV` AS `Groupamv`,
				  spos.`GROUPBC` AS `Groupbc`,
				  spos.`BLOCKTRADE_BBG_ID` AS `Blocktrade Bbg ID`,
				  spos.`OFF_BALANCE_COST` AS `Off Balance Cost`,
				  spos.`SWAP_INDEX` AS `Swap Index`,
				  spos.`DAY_COUNT` AS `Day Count`,
				  spos.`PAY_FREQUENCY` AS `Pay Frequency`,
				  spos.`RESET_FREQUENCY` AS `Reset Frequency`,
				  spos.`MONTH_END_STATUS` AS `Month End Status`,
				  spos.`PRICE_DATE` AS `Price Date`,
				  spos.`PORTFOLIO_GROUP_OBJECTIVE` AS `Portfolio Group1`,
				  spos.`DOMICILE_COUNTRY_CODE` AS `Domicile Country Code`,
				  spos.`ASIA_ASSET_CLASS_CODE_IN` AS `Asia Asset Class Code Indonesia`,
				  spos.`ASIA_ASSET_CLASS_CODE_VI` AS `Asia Asset Class Code Vietnam`,
				  spos.`ASIA_ASSET_CLASS_DESC_IN` AS `Asia Asset Class Desc Indonesia`,
				  spos.`ASIA_ASSET_CLASS_DESC_VI` AS `Asia Asset Class Desc Vietnam`,
				  spos.`FUNCTIONAL_CCY_CD` AS `Functional Ccy Code`,
				  spos.`LOCAL_TO_FUNC_RATE` AS `Local to Func Rate`,
				  spos.`LOCAL_TO_CAD_RATE` AS `Local to CAD Rate`,
				  spos.`LOCAL_TO_USD_RATE` AS `Local to USD Rate`,
				  spos.`LOCAL_TO_HKD_RATE` AS `Local to HKD Rate`,
				  spos.`NEXT_COUPON_AMOUNT` AS `Next Coupon Amount (D)`,
				  spos.`AOCI_HEDGE_PAR` AS `AOCI Hedge Par`,
				  spos.`AOCI_REMAIN_BALANCE_NON_BV_CCY_BASE` AS `AOCI Remain Balance Non BV - Base`,
				  spos.`AOCI_REMAIN_BALANCE_NON_BV_CCY_LOCAL` AS `AOCI Remain Balance Non BV - Local (D)`,
				  spos.`AOCI_REMAIN_BALANCE_REP_CCY_BASE` AS `AOCI Remain Balance Rep - Base`,
				  spos.`AOCI_REMAIN_BALANCE_REP_CCY_LOCAL` AS `AOCI Remain Balance Rep - Local (D)`,
				  spos.`BALANCE_COMMITMENT_CCY_LOCAL` AS `Balance Commitment - Local`,
				  spos.`INCOME_DEFAULT_AMOUNT_CCY_LOCAL` AS `Income Default Amount - Local (D)`,
				  spos.`INCOME_DEFAULT_AMOUNT_CCY_BASE` AS `Income Default Amount - Base`,
				  spos.`NEXT_INTEREST_PAYMENT_CCY_LOCAL` AS `Next Interest Payment - Local`,
				  spos.`NEXT_INTEREST_PAYMENT_CCY_BASE` AS `Next Interest Payment - Base`,
				  spos.`NEXT_PRINCIPAL_PAYMENT_CCY_LOCAL` AS `Next Principal Payment - Local`,
				  spos.`NEXT_PRINCIPAL_PAYMENT_CCY_BASE` AS `Next Principal Payment - Base`,
				  spos.`BALANCE_UNPAID_COMMITMENT_CCY_LOCAL` AS `Balance Unpaid Commitment`,
				  spos.`POS_ACCRUAL_BASE` AS `Pos Accrual - Base`,
				  spos.`NEXT_DIVIDEND_CCY_LOCAL` AS `Next Dividend - Local (D)`,
				  spos.`BOOK_YIELD` AS `Current Yield Book Price (D)`,
				  spos.`CONVEXITY` AS `Convexity`,
				  spos.`CURRENT_YIELD` AS `Current Yield (D)`,
				  spos.`DIRTY_PRICE` AS `Dirty Price`,
				  spos.`MODIFIED_DURATION_YTM` AS `Modified Duration YTM`,
				  spos.`MODIFIED_DURATION_YC` AS `Modified Duration YC`,
				  spos.`ORIGINAL_BOOK_YIELD` AS `Original Book Yield (D)`,
				  spos.`BALANCE_COST_VALUE_CCY_LOCAL` AS `Balance Cost Value - Local`,
				  spos.`BALANCE_COST_VALUE_CCY_BASE` AS `Balance Cost Value - Base`,
				  spos.`BALANCE_BOOK_VALUE_CCY_LOCAL` AS `Book Value - Local (D)`,
				  spos.`BALANCE_BOOK_VALUE_CCY_BASE` AS `Book Value - Base`,
				  spos.`BALANCE_INT_APPR_CCY_LOCAL` AS `Balance Int Appr - Local`,
				  spos.`BALANCE_INT_APPR_CCY_BASE` AS `Balance Int Appr - Base`,
				  spos.`BALANCE_OID_APPR_CCY_LOCAL` AS `Balance OID Appr - Local`,
				  spos.`BALANCE_OID_APPR_CCY_BASE` AS `Balance OID Appr - Base`,
				  spos.`BALANCE_CL_ALLOWANCE_CCY_LOCAL` AS `Balance CL Allowance - Local`,
				  spos.`BALANCE_CL_ALLOWANCE_CCY_BASE` AS `Balance CL Allowance - Base`,
				  spos.`BALANCE_RECOG_CL_ALLOWANCE_CCY_LOCAL` AS `Balance Recog CL Allowance - Local`,
				  spos.`BALANCE_RECOG_CL_ALLOWANCE_CCY_BASE` AS `Balance Recog CL Allowance - Base`,
				  spos.`BALANCE_WRITE_OFF_CCY_LOCAL` AS `Balance Write Off - Local`,
				  spos.`BALANCE_WRITE_OFF_CCY_BASE` AS `Balance Write Off - Base`,
				  spos.`BALANCE_IMPAIRMENT_CCY_LOCAL` AS `Balance Impairment - Local`,
				  spos.`BALANCE_IMPAIRMENT_CCY_BASE` AS `Balance Impairment - Base`,
				  spos.`AOCI_REMAIN_BALANCE_BV_CCY_LOCAL` AS `AOCI Remain Balance BV - Local (D)`,
				  spos.`AOCI_REMAIN_BALANCE_BV_CCY_BASE` AS `AOCI Remain Balance BV - Base`,
				  spos.`BALANCE_DEFERRED_PL_CCY_LOCAL` AS `Balance Deferred PL - Local (D)`,
				  spos.`BALANCE_DEFERRED_PL_CCY_BASE` AS `Balance Deferred PL - Base`,
				  spos.`INCOME_ACCRUAL_CCY_LOCAL` AS `Income Accrual - Local (D)`,
				  spos.`INCOME_ACCRUAL_CCY_BASE` AS `Income Accrual - Base`,
				  spos.`BALANCE_EXPECTED_RESTITUT_CCY_LOCAL` AS `Balance Expected Restitution - Local`,
				  spos.`BALANCE_EXPECTED_RESTITUT_CCY_BASE` AS `Balance Expected Restitution - Base`,
				  spos.`CARRYING_VALUE_CCY_LOCAL` AS `Carrying Value - Local (D)`,
				  spos.`CARRYING_VALUE_CCY_BASE` AS `Carrying Value - Base`,
				  spos.`UPDATED_TS` AS `Updated Ts`,
				  spos.`ADJUSTED_BOOK_VALUE_LOCAL` AS `Adjusted Book Value Local`,
				  spos.`ADJUSTED_BOOK_VALUE_BASE` AS `Adjusted Book Value Base`,
				  spos.`ISSUER_LONG_COMP_NAME` AS `SCD Issuer Long Company Name`,
				  spos.`SCD_DEFAULT_DATE` AS `SCD Default Date`,
				  spos.`SCD_DEFAULT_DATE_FC` AS `Accrue In Default`,
				  spos.`UNSETTLED_INT_DIV_AMOUNT_BASE_CCY` AS `Unsettled Int Div Amount Base CCY`,
				  spos.`UNSETTLED_INT_DIV_AMOUNT_LOCAL_CCY` AS `Unsettled Int Div Amount Local CCY`,
				  spos.`BALANCE_ACQUISITION_PRE_DIS_BASE_CCY` AS `Balance Acquisition Pre Dis Base CCY`,
				  spos.`BALANCE_ACQUISITION_PRE_DIS_LOCAL_CCY` AS `Balance Acquisition Pre Dis Local CCY`,
				  spos.`PURPOSE` AS `Purpose`,
				  spos.`IFRS9PURPOSE` AS `IFRS9 Purpose`,
				  spos.`BALANCE_BOOK_VALUE_LOCAL_CCY_NATIVE` AS `Balance Book Value Local Native`,
				  spos.`BALANCE_BOOK_VALUE_BASE_CCY_NATIVE` AS `Balance Book Value Base Native`,
				  spos.`CALCULATION_DATE_FULL` AS `Calculation Date Full`,
				  spos.`LONG_SHORT_INDICATOR` AS `Long Short Indicator`,
				  spos.`ACCRUED_INTEREST_EOP_LOCAL_CCY` AS `Accrued Interest EOP Local`,
				  spos.`ACCRUED_INTEREST_EOP_BASE_CCY` AS `Accrued Interest EOP Base`,
				  spos.`BALANCE_RETURN_OF_CAPITAL_BASE_CCY` AS `Balance Return Of Capital Base`,
				  spos.`BALANCE_RETURN_OF_CAPITAL_LOCAL_CCY` AS `Balance Return Of Capital Local`,
				  spos.`BALANCE_CALLED_CAPITAL_BASE_CCY` AS `Balance Called Capital Base`,
				  spos.`BALANCE_CALLED_CAPITAL_LOCAL_CCY` AS `Balance Called Capital Local`,
				  spos.`BALANCE_RECALLABLE_BASE_CCY` AS `Balance Recallable Base`,
				  spos.`BALANCE_RECALLABLE_LOCAL_CCY` AS `Balance Recallable Local`,
				  spos.`FX_JOIN_KEY` AS `FX Join Key`,
				  spos.`BALANCE_NAIC_CARRYING_VALUE_LOCAL_CCY` AS `Balance NAIC Carrying Value Local`,
				  spos.`BALANCE_NAIC_CARRYING_VALUE_BASE_CCY` AS `Balance NAIC Carrying Value Base`,
				  spos.`BALANCE_NAIC_SEC_ADJ_LOCAL_CCY` AS `Balance NAIC Sec Adj Local`,
				  spos.`BALANCE_NAIC_SEC_ADJ_BASE_CCY` AS `Balance NAIC Sec Adj Base`,
				  spos.`CALCULATED_UNREALIZED_GAIN_LOSS_LOCAL` AS `Calculated Unrealized Gain/Loss – Local`,
				  spos.`ML_BUSINESS_GROUP` AS `ML Business Group`,
				  spos.`SCD_GL_CLASSIFICATION` AS `SCD GL Classification`,
				  spos.`issue_volume` AS `Issue Volume`,
				  spos.`structure` AS `Structure`,
				  spos.`ACCRUED_INTEREST_QC_STATIC` AS `Accrued Interest QC (Static)`,
				  spos.`ACCRUED_INTEREST_PC_STATIC` AS `Accrued Interest PC (Static)`
				from "&Catalog&".inv_semantic_ga.SECURITIES_POSITION_FACT_DQ as spos
				where 
				(
				    (
				        (as_of_dt=last_day(as_of_dt)) or 
				        datediff((select max(as_of_dt) from "&Catalog&".inv_semantic_ga.SECURITIES_POSITION_FACT_DQ),as_of_dt) <="&LastNDays&
				    ")"&
				    " and ( as_of_dt >= '"&Date.ToText(Date.From(RangeStart),"yyyy-M-d")&"' and as_of_dt<'"&Date.ToText(Date.From(RangeEnd),"yyyy-M-d") &"' )"&
				    " and ( as_of_dt >= '"&Date.ToText(Date.From(pCutOffDate),"yyyy-M-d")&"')"&
				")",
				    Source = Value.NativeQuery(Databricks.Catalogs(HostName, HTTPPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null,CommandTimeout= #duration(0,5,0,0)]){[Name=Catalog,Kind="Database"]}[Data], Sql, null, [EnableFolding=true]),
				    #"Filtered Rows" = Table.SelectRows(Source, each true)
				in
				    #"Filtered Rows"
				```

	annotation PBI_ResultType = Table

	annotation PBI_IsMQueryFoldable = True

	annotation PBI_NavigationStepName = Navigation

