table Securities
	lineageTag: 19dbf567-4319-496c-aa31-a20ea241218a

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: month
		rollingWindowPeriods: 16
		incrementalGranularity: month
		incrementalPeriods: 16
		pollingExpression = Asset_Dim_PBI_Config
		sourceExpression =
			let
			    Source = Databricks.Catalogs(HostName, HTTPPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null,CommandTimeout= #duration(0,5,0,0), EnableQueryResultDownload="0"]),
			    hive_metastore_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
			    inv_semantic_ga_Schema = hive_metastore_Database{[Name="inv_semantic_ga",Kind="Schema"]}[Data],
			    EDL_asset_dim_dq = inv_semantic_ga_Schema{[Name="asset_dim_dq",Kind="Table"]}[Data],
			    #"Removed Other Columns" = Table.SelectColumns(EDL_asset_dim_dq,{"ASSET_KEY", "ASSET_ID", "ASSET_NAME", "AS_OF_DT", "SRC", "SCD_SRC_SECURITY_ID", "SCD_SRC_MARKET_ID", "SCD_SECURITY_ID", "SCD_SECURITY_ID_2", "SCD_TICKER_ISIN", "SCD_PPN_PRIVATE_ID", "SCD_SECURITY_NAME", "SCD_BLOOMBERG_ID", "SCD_ID_PRPL", "SCD_ID_BB_GLOBAL", "SCD_CUSIP", "SCD_ISIN", "SCD_TICKER", "SCD_PRINCIPAL_EXCHANGE", "SCD_SEDOL", "SCD_COLLATERAL_TYPE", "SCD_FACTOR", "SCD_LOCAL_CURRENCY_CD", "SCD_MOODYS", "SCD_MOODYS_RATING_CHANGE_DATE", "SCD_SP", "SCD_SP_RATING_CHANGE_DATE", "SCD_SP_RATING_OUTLOOK", "SCD_FITCH", "SCD_FITCH_RATING_CHANGE_DATE", "SCD_DBRS", "SCD_DBRS_RATING_CHANGE_DATE", "SCD_INTERNAL", "SCD_MAM_RATING", "SCD_ISSUER", "SCD_BPL_ISSUER", "SCD_INTERNAL_FUND", "SCD_COUPON", "SCD_SECURITY_ASSET_CLASS", "SCD_SECURITY_GROUP", "SCD_PRIMARY_ASSET_TYPE", "SCD_REPO_TYPE", "SCD_SECURITY_TYPE_2", "SCD_SECURITY_FUND_TYPE", "SCD_INSTRUMENT_TYPE", "SCD_INFLATION_LINKED", "SCD_VARIABLE_COUPON", "SCD_NEXT_COUPON_DATE", "SCD_PREVIOUS_COUPON_DATE", "SCD_MATURITY_DATE", "SCD_MATURITY_DAYS", "SCD_MATURITY_DAYS_2", "SCD_RESET_DAYS", "SCD_DIVIDEND_EX_DATE", "SCD_DIVIDEND_PAY_DATE", "SCD_DIVIDEND_RECORD_DATE", "SCD_DIVIDEND_RATE", "SCD_SHARES_OUTSTANDING", "SCD_FULL_SHARES_OUTSTANDING", "SCD_PRICE_SOURCE", "SCD_ISSUE_DT", "SCD_Country", "SCD_COUNTRY_OF_RISK", "SCD_COUNTRY_OF_ISSUE", "SCD_COUNTRY_OF_DOMICILE", "SCD_AMOUNT_ISSUED", "SCD_AMOUNT_OUTSTANDING", "SCD_MARKET_SECTOR", "SCD_UNDERLYING_ASSET_TYPE", "SCD_FUND_GEOGRAPHIC_FOCUS", "SCD_CONVERSION_RATIO", "SCD_CONVERSION_START_DATE", "SCD_CONVERSION_TO_TICKER", "SCD_VOTING_RIGHTS", "SCD_CONVERTIBLE_INDICATOR", "SCD_ISSUER_STATE_OF_DOMICILE", "SCD_ISSUER_STATE_OF_INCORPORATION", "SCD_144A_FLAG", "SCD_AGENCY_BACKED_MORTGAGE", "SCD_RESET_INDEX", "SCD_MORTGAGE_TRANCHE_TYPE_FULL", "SCD_MORTGAGE_TRANCHE_DESCRIPTION", "SCD_CALC_TYPE_DESCRIPTION", "SCD_NEXT_RESET_DATE", "SCD_CONTRACT_SIZE", "SCD_EXERCISE_DATE", "SCD_EXPIRY_DATE", "SCD_CONTRACT_SIDE", "SCD_FUTURE_CONTRACT_DATE", "SCD_ULTIMATE_PARENT_COMPANY_NAME", "SCD_US_ILLIQUID", "SCD_CA_ILLIQUID", "SCD_MUNICIPAL_LEASE_OBLIGATION", "SCD_REGULATORY_TYPE", "SCD_REG_S", "SCD_SINKABLE_INDICATOR", "SCD_NEXT_SINK_DATE", "SCD_ISLAMIC_INDICATOR", "SCD_MORTGAGE_PRINCIPAL_LOSSES", "SCD_MORTGAGE_INTEREST_SHORTFALL", "SCD_LOCAL_ID", "SCD_LOCAL_SECTOR", "SCD_ASIA_RATING", "SCD_RAM_RATING", "SCD_MARC_RATING", "SCD_ML_LIQUIDITY_CHANGE", "SCD_ML_MUNICIPAL_OBLIGOR", "SCD_OFFERING_TYPE", "SCD_REGULATORY_STRUCTURE", "SCD_EXCHANGE_COUNTRY", "SCD_ISSUER_TYPE", "SCD_MY_LOCAL_SEC_TYPE", "SCD_PRIVATE_PLACEMENT", "SCD_DEFAULT_FLAG", "SCD_FI_TYPE", "SCD_SP_SHORT_TERM_RATING", "SCD_MOODYS_SHORT_TERM_RATING", "SCD_FITCH_SHORT_TERM_RATING", "SCD_BPL_COUNTRY", "SCD_DISCOUNT_INDICATOR", "SCD_ST_COMPREHENSIVE", "SCD_EQ_SECTOR", "SCD_ACCRUAL_CURRENCY", "SCD_SETTLEMENT_TYPE", "SCD_SECTOR", "SCD_INDUSTRY_GROUP", "SCD_INDUSTRY", "SCD_SUB_INDUSTRY", "SCD_GICS_BICS", "SCD_SUBORD_TYPE", "SCD_ML_IFRS_13_LEVEL", "SCD_PRICE_POINT", "SCD_DAY_COUNT", "SCD_FINDUR_ID", "SCD_MANULIFE_LOCAL_PRICE", "SCD_YEAR", "SCD_PAYMENT_RANK", "SCD_ML_INVESTMENT_ID", "SCD_ML_INVESTMENT_TYPE_CD", "SCD_ASSET_CLASS", "SCD_CPN_FREQ", "SCD_GL_CLASSIFICATION", "SCD_GL_CLASSIFICATION_JGAAP", "SCD_GL_CLASSIFICATION_NAIC", "SCD_ML_CUSIP_PPN", "SCD_JAPAN_CREDIT_RATING_CD", "SCD_RI_RATING_CD", "SCD_ML_LOCAL_CHINA_ID", "SCD_ML_VAULT_ID", "SCD_ML_VAULT_NM", "SCD_ML_IRR_RATING", "SCD_ML_MFC_EQUIVALENT_RATING", "SCD_ML_PRIMARY_RATING_CD", "SCD_ML_JH_RATING_CD", "SCD_HAS_CPN_VARIABLE", "SCD_NXT_CALL_DT", "SCD_PRICE_CURRENCY", "SCD_NXT_CALL_PX", "SCD_NXT_PUT_PX", "SCD_NXT_PUT_DT", "SCD_MAKE_WHOLE_CALL", "SCD_CALLABLE", "SCD_PUTABLE", "SCD_STD_CURRENCY", "SCD_COUPON_TYPE", "SCD_ID_BPL_PRICING_STRATEGY", "SCD_ID_BPL_PRICE_POINT", "SCD_PX_LAST", "SCD_MRM_SECTOR", "SCD_CALM_CATEGORY", "SCD_SCHEDULE_BA_ASSET_CATEGORY_CD", "SCD_SEED_MONEY_IND", "SCD_ML_MINOR_TYPE", "SCD_BICS_LEVEL2_INDUSTRY_GRP_DES", "SCD_SECURITY_TYPE", "SCD_ISSUER_LONG_COMP_NAME", "SCD_ISSUER_NAME", "SCD_PAYING_AGENT", "SCD_LONG_COMPANY_NAME", "SCD_BICS_LEVEL1_SECTOR_DES", "SCD_BICS_LEVEL3_INDUSTRY_DES", "SCD_BICS_LEVEL4_SUB_INDUSTRY_DES", "SCD_ANALYSTTEAM", "SCD_ID_BB_COMPANY", "SCD_ID_BB_GLOBAL_COMPANY", "SCD_SECURITY_TYPE_DESC", "SCD_COUPON_SPREAD", "SCD_ML_IFRS_ACCOUNTING_METHOD", "SCD_ML_LGAAP_ACCOUNTING_METHOD", "SCD_ML_STAT_ACCOUNTING_METHOD", "SCD_ML_BA_AVR_CD", "SCD_CALLED_DT", "SCD_CALLED_PX", "SCD_IS_PERPETUAL", "SCD_BASIC_SPREAD", "SCD_COUPON_TYP_RESET_DT", "SCD_GGI_INDICATOR", "SCD_ML_SD_CLASS_DESC", "SCD_DG_ISSUER_CD", "SCD_ML_MFC_EQUIVALENT_EFF_DT", "SCD_ML_MIM_NA_RATING_EFF_DT", "SCD_ML_MIM_ASIA_RATING_EFF_DT", "SCD_ML_SPEQ_RATING", "SCD_ML_SPEQ_EFF_DT", "SCD_ML_JH_RATING_EFFECTIVE_DT", "SCD_JAPAN_CREDIT_RATING_EFFECTIVE_DT", "SCD_ML_IRR_EFF_DT", "SCD_RI_RATING_EFFECTIVE_DT", "SCD_ML_SD_TYPE_DESC", "SCD_ID_CINS", "SCD_ML_CAPITAL_STRUCTURE_CD", "SCD_ML_CAPITAL_STRUCTURE_DESC", "SCD_ML_STAT_COLLATERAL_TYPE_CD", "SCD_ML_NAIC_REPORT_PART_CD", "SCD_NAIC_DESIGNATION", "SCD_NAIC_RATING", "SCD_ANALYST_ID", "SCD_ANALYST_NM", "SCD_ANALYST_ROLE_CD", "SCD_PRIMARY_RATING_EFFECTIVE_DT", "SCD_ML_NAIC_INSTRUMENT_TYPE_CD", "SCD_ML_SD_CLASS_CD", "SCD_ML_SD_SUBCLASS_CD", "SCD_ML_SD_TYPE_CD", "SCD_LATEST_FLAG", "rtg_mdy_long_issue_level", "rtg_fitch_long", "rtg_mdy_issuer", "rtg_sp_long", "LAST_REFIX_DT", "SR_LOAN", "SCD_CNTRY_OF_INCORPORATION", "SCD_NAIC_DEPOSIT_CATEGORY", "SCD_INT_ACC_DT", "SCD_STATE_CODE", "SCD_FINAL_MATURITY_DATE", "SCD_PX_ASK", "SCD_PX_BID", "SCD_PX_MID", "SCD_ML_PRICING_SOURCE", "SCD_MRM_INDUSTRY_SECTOR_NM", "SCD_MRM_INDUSTRY_GROUP_NM", "SCD_MRM_INDUSTRY_SUBGROUP_NM", "SCD_SEC_MRM_INDUSTRY_SECTOR_NM", "SCD_SEC_MRM_INDUSTRY_GROUP_NM", "SCD_SEC_MRM_INDUSTRY_SUBGROUP_NM", "SCD_SEC_MRM_SECTOR_NM", "SCD_HAS_CPN_STEPDN_FLOAT", "SCD_HAS_CPN_STEPUP_FLOAT", "SCD_IS_FIX_TO_FLOAT", "SCD_FLOATER", "SCD_ML_ACCRUE_IN_DEFAULT_IND", "SCD_PREPAY_RISK", "SCD_NXT_REFIX_DT", "SCD_FIRST_CPN_DT", "SCD_DEFAULT_DATE", "SCD_SINKING_FUND_FACTOR", "SCD_CPN_FLOOR", "SCD_CPN_CAP", "SCD_IS_PUBLICPP_IND", "SCD_MXMS_ID", "SCD_DEPOSIT_RATE", "SCD_RESET_FREQ_DESCRIPTION", "SCD_WASH_SALE_PARENT_SECURITY_ID", "SCD_ML_LICAT_INFRD_RATING", "SCD_PRIVATE_PLACEMENT_INDICATOR", "SCD_ISSUER_INCORPORATED_COUNTRY_CODE", "SCD_PRIMARY_SECURITY_ID_TYPE", "SCD_INTERNAL_SEC_ID_TYPE", "SCD_ML_REVIEW_CAT_CD", "SCD_ML_ISSUE_TXT", "SCD_LEGAL_STRUCTURE_CD", "SCD_ENTITY_JOIN_NK", "SCD_GICS_SECTOR_CD", "SCD_GICS_INDUSTRY_CD", "SCD_GICS_SUB_INDUSTRY_CD", "SCD_GICS_INDUSTRY_GROUP_CD", "SCD_OPT_PUT_CALL", "SCD_EQY_SIC_CODE", "SCD_MTG_EXP_MATURITY_DT", "SCD_EQY_SIC_NAME", "SCD_SVO_SUFFIX", "SCD_NAIC_DESIGNATION_MODIFIER", "SCD_EXCH_CODE", "SCD_ID_MIC1", "SCD_ISSUE_PX", "SCD_FIRST_SETTLE_DT", "SCD_START_ACC_DT", "SCD_MTG_START_ACC_DT_SET_DT", "SCD_MAKE_WHOLE_CALL_SPREAD_NUM", "SCD_MAKE_WHOLE_TERMINATION_DT", "SCD_PAYMENT_METHOD_NM", "SCD_MRM_ISSUER_NM", "SCD_MRM_ISSUER_COUNTRY_NM", "SCD_MRM_ISSUER_IRR_RATING_CD", "SCD_MRM_ISSUER_PARENT_NM", "SCD_MRM_ISSUER_PARENT_COUNTRY_NM", "SCD_MRM_ISSUER_PARENT_IRR_RATING_CD", "SCD_MRM_ISSUER_ULTPARENT_NM", "SCD_MRM_ISSUER_ULTPARENT_COUNTRY_NM", "SCD_MRM_ISSUER_ULTPARENT_IRR_RATING_CD", "SCD_EQUITY_FUND_IND", "SCD_GCLMS_COLLATERAL_QUALITY_CD", "SCD_MRM_ISSUER_CASCADE_RATING_CD", "SCD_MRM_ISSUER_PARENT_CASCADE_RATING_CD", "SCD_MRM_ISSUER_ULTPARENT_CASCADE_RATING_CD", "SCD_CUR_CPN", "SCD_GCLMS_ISSUER_PARENT_CASCADE_RTG_CD", "SCD_GUARANTOR_NM", "SCD_CAPITAL_STRUCTURE_NM", "SCD_ALT_FEE_ASSET_NM","multi_cpn_schedule_typ"}),
			    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each ([SRC] = "SCD")),
			    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"SCD_PRIVATE_PLACEMENT_INDICATOR", "Scd Private Placement Indicator"}, {"SCD_MRM_INDUSTRY_SECTOR_NM", "MRM Industry Sector Name (Private Sec)"}, {"SCD_MRM_INDUSTRY_GROUP_NM", "MRM Industry Group Name (Private Sec)"}, {"SCD_MRM_INDUSTRY_SUBGROUP_NM", "MRM Industry Subgroup Name (Private Sec)"}, {"SCD_SEC_MRM_INDUSTRY_SECTOR_NM", "MRM Industry Sector Name (Sec)"}, {"SCD_SEC_MRM_INDUSTRY_GROUP_NM", "MRM Industry Group Name (Sec)"}, {"SCD_SEC_MRM_INDUSTRY_SUBGROUP_NM", "MRM Industry Subgroup Name (Sec)"}, {"SCD_SEC_MRM_SECTOR_NM", "MRM Sector Name (Sec)"}, {"SCD_IS_PUBLICPP_IND", "Is PublicPP Ind"}, {"SCD_ISSUER_INCORPORATED_COUNTRY_CODE", "Issuer Country Cd"}, {"SCD_PRIMARY_SECURITY_ID_TYPE", "Primary Security ID Type"}, {"SCD_NAIC_DESIGNATION_MODIFIER", "NAIC Designation Modifier"}, {"SCD_SVO_SUFFIX", "SCD Svo Suffix"}, {"AS_OF_DT", "As Of Dt"}, {"ASSET_ID", "Primary Security ID"}, {"ASSET_KEY", "Security NK"}, {"ASSET_NAME", "Security Description"}, {"SCD_144A_FLAG", "144A Flag"}, {"SCD_ACCRUAL_CURRENCY", "Accrual Currency"}, {"SCD_AGENCY_BACKED_MORTGAGE", "Agency Backed Mortgage"}, {"SCD_AMOUNT_ISSUED", "Amount Issued"}, {"SCD_AMOUNT_OUTSTANDING", "Amount Outstanding"}, {"SCD_ANALYST_ID", "Analyst ID"}, {"SCD_ANALYST_NM", "Analyst Nm"}, {"SCD_ANALYST_ROLE_CD", "Analyst Role Cd"}, {"SCD_ANALYSTTEAM", "Analyst Team"}, {"SCD_ASIA_RATING", "Asia Rating"}, {"SCD_BASIC_SPREAD", "Basic Spread"}, {"SCD_BICS_LEVEL1_SECTOR_DES", "BICS Level1 Sector Desc"}, {"SCD_BICS_LEVEL2_INDUSTRY_GRP_DES", "BICS Level2 Industry Group Desc"}, {"SCD_BICS_LEVEL3_INDUSTRY_DES", "BICS Level3 Industry Desc"}, {"SCD_BICS_LEVEL4_SUB_INDUSTRY_DES", "BICS Level4 Sub Industry Desc"}, {"SCD_BLOOMBERG_ID", "Bloomberg ID"}, {"SCD_BPL_COUNTRY", "Bpl Country"}, {"SCD_BPL_ISSUER", "Bpl Issuer"}, {"SCD_CA_ILLIQUID", "Ca Illiquid"}, {"SCD_CALC_TYPE_DESCRIPTION", "Calc Type Description"}, {"SCD_CALLABLE", "Callable"}, {"SCD_CALLED_DT", "Called Dt"}, {"SCD_CALLED_PX", "Called Px"}, {"SCD_CALM_CATEGORY", "Calm Category"}, {"SCD_COLLATERAL_TYPE", "Collateral Type"}, {"SCD_CONTRACT_SIDE", "Contract Side"}, {"SCD_CONTRACT_SIZE", "Contract Size"}, {"SCD_CONVERSION_RATIO", "Conversion Ratio"}, {"SCD_CONVERSION_START_DATE", "Conversion Start Date"}, {"SCD_CONVERSION_TO_TICKER", "Conversion To Ticker"}, {"SCD_CONVERTIBLE_INDICATOR", "Convertible Indicator"}, {"SCD_Country", "Country"}, {"SCD_COUNTRY_OF_DOMICILE", "Country Of Domicile"}, {"SCD_COUNTRY_OF_ISSUE", "Country Of Issue"}, {"SCD_COUNTRY_OF_RISK", "Country Of Risk"}, {"SCD_COUPON", "Coupon"}, {"SCD_COUPON_SPREAD", "Coupon Spread"}, {"SCD_COUPON_TYP_RESET_DT", "Fix To Float Date"}, {"SCD_COUPON_TYPE", "Coupon Type"}, {"SCD_CPN_FREQ", "Coupon Frequency"}, {"SCD_CUSIP", "Cusip"}, {"SCD_DAY_COUNT", "Day Count"}, {"SCD_DBRS", "Dbrs"}, {"SCD_DBRS_RATING_CHANGE_DATE", "Dbrs Rating Change Date"}, {"SCD_DEFAULT_FLAG", "Default Flag"}, {"SCD_DG_ISSUER_CD", "Dg Issuer Cd"}, {"SCD_DISCOUNT_INDICATOR", "Discount Indicator"}, {"SCD_DIVIDEND_EX_DATE", "Dividend Ex Date"}, {"SCD_DIVIDEND_PAY_DATE", "Dividend Pay Date"}, {"SCD_DIVIDEND_RATE", "Dividend Rate"}, {"SCD_DIVIDEND_RECORD_DATE", "Dividend Record Date"}, {"SCD_PRIMARY_ASSET_TYPE", "Primary Asset Type"}, {"SCD_EQ_SECTOR", "Eq Sector"}, {"SCD_EXCHANGE_COUNTRY", "Exchange Country"}, {"SCD_EXERCISE_DATE", "Exercise Date"}, {"SCD_EXPIRY_DATE", "Expiry Date"}, {"SCD_FACTOR", "Factor"}, {"SCD_FI_TYPE", "Fi Type"}, {"SCD_FINDUR_ID", "Findur ID"}, {"SCD_FITCH", "Fitch"}, {"SCD_FITCH_RATING_CHANGE_DATE", "Fitch Rating Change Date"}, {"SCD_FITCH_SHORT_TERM_RATING", "Fitch Short Term Rating"}, {"SCD_FULL_SHARES_OUTSTANDING", "Full Shares Outstanding"}, {"SCD_FUND_GEOGRAPHIC_FOCUS", "Fund Geographic Focus"}, {"SCD_FUTURE_CONTRACT_DATE", "Future Contract Date"}, {"SCD_GGI_INDICATOR", "GGI Indicator"}, {"SCD_GICS_BICS", "Gics Bics"}, {"SCD_GL_CLASSIFICATION", "SCD GL Classification"}, {"SCD_GL_CLASSIFICATION_JGAAP", "SCD GL Classification JGAAP"}, {"SCD_GL_CLASSIFICATION_NAIC", "SCD GL Classification NAIC"}, {"SCD_HAS_CPN_VARIABLE", "Has Coupon Variable"}, {"SCD_ID_BB_COMPANY", "ID BB Company"}, {"SCD_ID_BB_GLOBAL", "ID BB Global"}, {"SCD_ID_BB_GLOBAL_COMPANY", "ID BB Global Company"}, {"SCD_ID_BPL_PRICE_POINT", "ID BPL Price Point"}, {"SCD_ID_BPL_PRICING_STRATEGY", "ID BPL Pricing Strategy"}, {"SCD_ID_CINS", "ID Cins"}, {"SCD_ID_PRPL", "ID PRPL"}, {"SCD_INDUSTRY", "Industry"}, {"SCD_INDUSTRY_GROUP", "Industry Group"}, {"SCD_INFLATION_LINKED", "Inflation Linked"}, {"SCD_INSTRUMENT_TYPE", "SCD Instrument Category"}, {"SCD_INTERNAL", "Internal"}, {"SCD_INTERNAL_FUND", "Internal Fund"}, {"SCD_IS_PERPETUAL", "Is Perpetual"}, {"SCD_ISIN", "Isin"}, {"SCD_ISLAMIC_INDICATOR", "Islamic Indicator"}, {"SCD_ISSUE_DT", "Issue Dt"}, {"SCD_ISSUER", "Issuer"}, {"SCD_ISSUER_LONG_COMP_NAME", "Issuer Long Comp Name"}, {"SCD_ISSUER_NAME", "Issuer Name"}, {"SCD_ISSUER_STATE_OF_DOMICILE", "Issuer State Of Domicile"}, {"SCD_ISSUER_STATE_OF_INCORPORATION", "Issuer State Of Incorporation"}, {"SCD_ISSUER_TYPE", "Issuer Type"}, {"SCD_JAPAN_CREDIT_RATING_CD", "Japan Credit Rating Cd"}, {"SCD_JAPAN_CREDIT_RATING_EFFECTIVE_DT", "Japan Credit Rating Effective Dt"}, {"SCD_LOCAL_CURRENCY_CD", "Local"}, {"SCD_LOCAL_ID", "Local ID"}, {"SCD_LOCAL_SECTOR", "Local Sector"}, {"SCD_LONG_COMPANY_NAME", "Long Company Name"}, {"SCD_MAKE_WHOLE_CALL", "Make Whole Call"}, {"SCD_MAM_RATING", "Mam Rating"}, {"SCD_MANULIFE_LOCAL_PRICE", "Manulife Local Price"}, {"SCD_MARC_RATING", "Marc Rating"}, {"SCD_MARKET_SECTOR", "Market Sector"}, {"SCD_MATURITY_DATE", "Maturity Date"}, {"SCD_MATURITY_DAYS", "Maturity Days (D)"}, {"SCD_MATURITY_DAYS_2", "Maturity Days 2 (D)"}, {"SCD_ML_BA_AVR_CD", "ML Ba Avr Cd"}, {"SCD_ML_CAPITAL_STRUCTURE_CD", "ML Capital Structure Cd"}, {"SCD_ML_CAPITAL_STRUCTURE_DESC", "ML Capital Structure Desc"}, {"SCD_ML_CUSIP_PPN", "ML Private Asset ID"}, {"SCD_ML_IFRS_13_LEVEL", "ML Ifrs 13 Level"}, {"SCD_ML_IFRS_ACCOUNTING_METHOD", "ML Ifrs Accounting Method"}, {"SCD_ML_INVESTMENT_ID", "ML Investment Id"}, {"SCD_ML_INVESTMENT_TYPE_CD", "ML Investment Type Cd"}, {"SCD_ML_IRR_EFF_DT", "ML IRR Eff Dt"}, {"SCD_ML_IRR_RATING", "ML IRR Rating"}, {"SCD_ML_JH_RATING_CD", "ML JH Rating Cd"}, {"SCD_ML_JH_RATING_EFFECTIVE_DT", "ML JH Rating Effective Dt"}, {"SCD_ML_LGAAP_ACCOUNTING_METHOD", "ML Lgaap Accounting Method"}, {"SCD_ML_LIQUIDITY_CHANGE", "ML Liquidity Change"}, {"SCD_ML_LOCAL_CHINA_ID", "ML Local China ID"}, {"SCD_ML_MFC_EQUIVALENT_EFF_DT", "ML MFC Equivalent Eff Dt"}, {"SCD_ML_MFC_EQUIVALENT_RATING", "ML MFC Equivalent Rating"}, {"SCD_ML_MIM_ASIA_RATING_EFF_DT", "ML Mim Asia Rating Eff Dt"}, {"SCD_ML_MIM_NA_RATING_EFF_DT", "ML Mim Na Rating Eff Dt"}, {"SCD_ML_MINOR_TYPE", "ML Minor Type"}, {"SCD_ML_MUNICIPAL_OBLIGOR", "ML Municipal Obligor"}, {"SCD_ML_NAIC_INSTRUMENT_TYPE_CD", "ML NAIC Instrument Type Cd"}, {"SCD_ML_NAIC_REPORT_PART_CD", "ML NAIC Report Part Cd"}, {"SCD_ML_PRIMARY_RATING_CD", "ML Primary Rating Cd"}, {"SCD_ML_SD_CLASS_CD", "ML SD Class Cd"}, {"SCD_ML_SD_CLASS_DESC", "ML SD Class Desc"}, {"SCD_ML_SD_SUBCLASS_CD", "ML SD Subclass Cd"}, {"SCD_ML_SD_TYPE_CD", "ML SD Type Cd"}, {"SCD_ML_SD_TYPE_DESC", "ML SD Type Desc"}, {"SCD_ML_SPEQ_EFF_DT", "ML Speq Eff Dt"}, {"SCD_ML_SPEQ_RATING", "ML Speq Rating"}, {"SCD_ML_STAT_ACCOUNTING_METHOD", "ML Stat Accounting Method"}, {"SCD_ML_STAT_COLLATERAL_TYPE_CD", "ML Stat Collateral Type Cd"}, {"SCD_ML_VAULT_ID", "ML Vault ID"}, {"SCD_ML_VAULT_NM", "ML Vault Name"}, {"SCD_MOODYS", "Moodys"}, {"SCD_MOODYS_RATING_CHANGE_DATE", "Moodys Rating Change Date"}, {"SCD_MOODYS_SHORT_TERM_RATING", "Moodys Short Term Rating"}, {"SCD_MORTGAGE_INTEREST_SHORTFALL", "Mortgage Interest Shortfall"}, {"SCD_MORTGAGE_PRINCIPAL_LOSSES", "Mortgage Principal Losses"}, {"SCD_MORTGAGE_TRANCHE_DESCRIPTION", "Mortgage Tranche Description"}, {"SCD_MORTGAGE_TRANCHE_TYPE_FULL", "Mortgage Tranche Type Full"}, {"SCD_MRM_SECTOR", "MRM Sector (Private Sec)"}, {"SCD_MUNICIPAL_LEASE_OBLIGATION", "Municipal Lease Obligation"}, {"SCD_MY_LOCAL_SEC_TYPE", "My Local Sec Type"}, {"SCD_NAIC_DESIGNATION", "NAIC Designation"}, {"SCD_NAIC_RATING", "NAIC Rating"}, {"SCD_NEXT_COUPON_DATE", "Next Coupon Date"}, {"SCD_NEXT_RESET_DATE", "Next Reset Date"}, {"SCD_NEXT_SINK_DATE", "Next Sink Date"}, {"SCD_NXT_CALL_DT", "Next Call Date"}, {"SCD_NXT_CALL_PX", "Next Call PX"}, {"SCD_NXT_PUT_DT", "Next Put Dt"}, {"SCD_NXT_PUT_PX", "Next Put PX"}, {"SCD_OFFERING_TYPE", "Offering Type"}, {"SCD_PAYING_AGENT", "Paying Agent"}, {"SCD_PAYMENT_RANK", "Payment Rank"}, {"SCD_PPN_PRIVATE_ID", "Official PPN"}, {"SCD_PREVIOUS_COUPON_DATE", "Previous Coupon Date"}, {"SCD_PRICE_CURRENCY", "Price Currency"}, {"SCD_PRICE_POINT", "Price Point"}, {"SCD_PRICE_SOURCE", "Price Source"}, {"SCD_PRIMARY_RATING_EFFECTIVE_DT", "Primary Rating Effective Dt"}, {"SCD_PRINCIPAL_EXCHANGE", "Principal Exchange"}, {"SCD_PRIVATE_PLACEMENT", "Private Placement"}, {"SCD_PUTABLE", "Putable"}, {"SCD_PX_LAST", "Indonesian Price"}, {"SCD_RAM_RATING", "Ram Rating"}, {"SCD_REG_S", "Reg S"}, {"SCD_REGULATORY_STRUCTURE", "Regulatory Structure"}, {"SCD_REGULATORY_TYPE", "Regulatory Type"}, {"SCD_REPO_TYPE", "Repo Type"}, {"SCD_RESET_DAYS", "Reset Days"}, {"SCD_RESET_INDEX", "Reset Index"}, {"SCD_RI_RATING_CD", "RI Rating Cd"}, {"SCD_RI_RATING_EFFECTIVE_DT", "RI Rating Effective Dt"}, {"SCD_SCHEDULE_BA_ASSET_CATEGORY_CD", "Schedule BA Asset Category Code"}, {"SCD_SECTOR", "Sector"}, {"SCD_SECURITY_ASSET_CLASS", "Asset Class"}, {"SCD_SECURITY_FUND_TYPE", "Security Fund Type"}, {"SCD_SECURITY_GROUP", "Asset Group"}, {"SCD_SECURITY_ID", "SCD Security ID"}, {"SCD_SECURITY_ID_2", "Security ID 2"}, {"SCD_SECURITY_NAME", "Security Name"}, {"SCD_SECURITY_TYPE", "SCD Security Type"}, {"SCD_SECURITY_TYPE_2", "Security Type 2"}, {"SCD_SECURITY_TYPE_DESC", "Asset Type"}, {"SCD_SEDOL", "Sedol"}, {"SCD_SEED_MONEY_IND", "Seed Money Ind"}, {"SCD_SETTLEMENT_TYPE", "Settlement Type"}, {"SCD_SHARES_OUTSTANDING", "Shares Outstanding"}, {"SCD_SINKABLE_INDICATOR", "Sinkable Indicator"}, {"SCD_SP", "S&P"}, {"SCD_SP_RATING_CHANGE_DATE", "S&P Rating Change Date"}, {"SCD_SP_RATING_OUTLOOK", "S&P Rating Outlook"}, {"SCD_SP_SHORT_TERM_RATING", "S&P Short Term Rating"}, {"SCD_SRC_MARKET_ID", "Src Market ID"}, {"SCD_SRC_SECURITY_ID", "Src Security ID"}, {"SCD_ST_COMPREHENSIVE", "St Comprehensive"}, {"SCD_STD_CURRENCY", "Std Currency"}, {"SCD_SUB_INDUSTRY", "Sub Industry"}, {"SCD_SUBORD_TYPE", "Subord Type"}, {"SCD_TICKER", "Ticker"}, {"SCD_TICKER_ISIN", "Ticker Isin"}, {"SCD_ULTIMATE_PARENT_COMPANY_NAME", "Ultimate Parent Company Name"}, {"SCD_UNDERLYING_ASSET_TYPE", "Underlying Asset Type"}, {"SCD_US_ILLIQUID", "Us Illiquid"}, {"SCD_VARIABLE_COUPON", "Variable Coupon"}, {"SCD_VOTING_RIGHTS", "Voting Rights"}, {"SCD_YEAR", "Year"}, {"SRC", "Src"}, {"SCD_ASSET_CLASS", "SCD Instrument Type"}, {"SR_LOAN", "SR Loan"}, {"LAST_REFIX_DT", "Last Refix Date"}, {"rtg_sp_long", "RTG S&P Long"}, {"rtg_mdy_issuer", "RTG MDY Issuer"}, {"rtg_fitch_long", "RTG Fitch Long"}, {"rtg_mdy_long_issue_level", "RTG MDY Long Issue Level"}, {"SCD_LATEST_FLAG", "SCD Latest Flag"}, {"SCD_CNTRY_OF_INCORPORATION", "Country of Incorporation"}, {"SCD_STATE_CODE", "State Code"}, {"SCD_NAIC_DEPOSIT_CATEGORY", "NAIC Deposit Category"}, {"SCD_INT_ACC_DT", "Int Acc Date"}, {"SCD_FINAL_MATURITY_DATE", "Final Maturity Date"}, {"SCD_PX_ASK", "Ask Price"}, {"SCD_PX_BID", "Bid Price"}, {"SCD_PX_MID", "Mid Price"}, {"SCD_ML_PRICING_SOURCE", "Ml Pricing Source"}, {"SCD_HAS_CPN_STEPDN_FLOAT", "Step-down Floater Ind"}, {"SCD_HAS_CPN_STEPUP_FLOAT", "Step-up Floater Ind"}, {"SCD_IS_FIX_TO_FLOAT", "Income Rate Ind"}, {"SCD_FLOATER", "Float Not Var Ind"}, {"SCD_ML_ACCRUE_IN_DEFAULT_IND", "Accrue In Default Ind"}, {"SCD_PREPAY_RISK", "Pre Payment Risk"}, {"SCD_NXT_REFIX_DT", "Next Refix Date"}, {"SCD_FIRST_CPN_DT", "First Coupon Date"}, {"SCD_DEFAULT_DATE", "Default Date"}, {"SCD_SINKING_FUND_FACTOR", "Sink Fund PRN"}, {"SCD_CPN_FLOOR", "Coupon Floor"}, {"SCD_CPN_CAP", "Coupon Cap"}, {"SCD_MXMS_ID", "Mxms Id"}, {"SCD_DEPOSIT_RATE", "SCD Deposit Rate"}, {"SCD_RESET_FREQ_DESCRIPTION", "Reset Freq Description"}, {"SCD_MRM_ISSUER_NM", "MRM Issuer Name"}, {"SCD_MRM_ISSUER_COUNTRY_NM", "MRM Issuer Country Name"}, {"SCD_MRM_ISSUER_IRR_RATING_CD", "MRM Issuer Irr Rating Cd"}, {"SCD_MRM_ISSUER_PARENT_NM", "MRM Issuer Parent Name"}, {"SCD_MRM_ISSUER_PARENT_COUNTRY_NM", "MRM Issuer Parent Country Name"}, {"SCD_MRM_ISSUER_PARENT_IRR_RATING_CD", "MRM Issuer Parent Irr Rating Cd"}, {"SCD_MRM_ISSUER_ULTPARENT_NM", "MRM Issuer Ultparent Name"}, {"SCD_MRM_ISSUER_ULTPARENT_COUNTRY_NM", "MRM Issuer Ultparent Country Name"}, {"SCD_MRM_ISSUER_ULTPARENT_IRR_RATING_CD", "MRM Issuer Ultparent Irr Rating Cd"}, {"SCD_EQUITY_FUND_IND", "Equity Fund Ind"}, {"SCD_GCLMS_COLLATERAL_QUALITY_CD", "GCLMS Collateral Quality Cd"}, {"SCD_MRM_ISSUER_CASCADE_RATING_CD", "MRM Issuer Cascade Rating Cd"}, {"SCD_MRM_ISSUER_PARENT_CASCADE_RATING_CD", "MRM Issuer Parent Cascade Rating Cd"}, {"SCD_MRM_ISSUER_ULTPARENT_CASCADE_RATING_CD", "MRM Issuer Ultparent Cascade Rating Cd"}, {"SCD_CUR_CPN", "Cur Cpn"}, {"SCD_GCLMS_ISSUER_PARENT_CASCADE_RTG_CD", "GCLMS Issuer Parent Cascade Rtg Cd"}, {"SCD_GUARANTOR_NM", "Guarantor Name"}, {"SCD_CAPITAL_STRUCTURE_NM", "Capital Structure Name"}, {"SCD_ALT_FEE_ASSET_NM", "Alt Fee Asset Name"}, {"SCD_WASH_SALE_PARENT_SECURITY_ID", "Wash Sale Parent Security Id"}, {"SCD_ML_LICAT_INFRD_RATING", "ML LICAT Inferred Rating ORG"}, {"SCD_INTERNAL_SEC_ID_TYPE", "Internal Sec Id Type"}, {"SCD_ML_REVIEW_CAT_CD", "ML Review CAT CD"}, {"SCD_ML_ISSUE_TXT", "ML Issue Txt"}, {"SCD_LEGAL_STRUCTURE_CD", "Legal Structure Cd"}, {"SCD_OPT_PUT_CALL", "Opt Put Call"}, {"SCD_GICS_SECTOR_CD", "Gics Sector Cd"}, {"SCD_GICS_INDUSTRY_CD", "Gics Industry Cd"}, {"SCD_GICS_SUB_INDUSTRY_CD", "Gics Sub Industry Cd"}, {"SCD_GICS_INDUSTRY_GROUP_CD", "Gics Industry Group Cd"}, {"SCD_EQY_SIC_CODE", "Eqy Sic Cd"}, {"SCD_ENTITY_JOIN_NK", "Entity Join Key"}, {"SCD_MTG_EXP_MATURITY_DT", "SCD MTG EXP Maturity Dt"}, {"SCD_EQY_SIC_NAME", "Eqy Sic Name"}, {"SCD_ISSUE_PX", "Issue px"}, {"SCD_FIRST_SETTLE_DT", "First settle dt"}, {"SCD_START_ACC_DT", "Start acc dt"}, {"SCD_EXCH_CODE", "Exch code"}, {"SCD_ID_MIC1", "Id mic1"}, {"SCD_MTG_START_ACC_DT_SET_DT", "MTG start acc dt set dt"}, {"SCD_MAKE_WHOLE_CALL_SPREAD_NUM", "Make Whole Call Spread Num"}, {"SCD_MAKE_WHOLE_TERMINATION_DT", "Make Whole Termination Dt"}, {"SCD_PAYMENT_METHOD_NM", "Payment Method Name"}, {"multi_cpn_schedule_typ", "Multi Cpn Schedule Typ"}}),
			    #"Filtered Rows - Incremental Refresh" = Table.SelectRows(#"Renamed Columns", each [As Of Dt] >= Date.From(RangeStart) and [As Of Dt] < Date.From(RangeEnd))
			in
			    #"Filtered Rows - Incremental Refresh"

	measure 'Maturity Days' = ```
			
			--Flip signs
			IF (
			    MIN ( 'Securities'[Maturity Days (D)] ) < 0,
			    MIN ( 'Securities'[Maturity Days (D)] ) * -1,
			    MIN ( 'Securities'[Maturity Days (D)] )
			)
			
			```
		formatString: 0
		lineageTag: fdd208a4-3e62-43da-a680-caca14b4903d

	measure 'Days to Maturity' = ```
			
			IF (
			    MIN ( 'Securities'[Maturity Days 2 (D)] ) < 0,
			    MIN ( 'Securities'[Maturity Days 2 (D)] ) * -1,
			    MIN ( 'Securities'[Maturity Days 2 (D)] )
			)
			
			```
		formatString: 0
		lineageTag: c4fed4e6-e213-48d3-be0c-fd5e4c2cb095

	measure 'Held Securities Title DQ' =
			
			VAR FW =
			    SELECTEDVALUE ( Framework[Framework Display] )
			VAR prd =
			    MAX ( 'Securities'[As Of Dt] )
			RETURN
			    "Held Securities, " & FW & ", "
			        & FORMAT ( prd, "dd-mmm-yy" )
		lineageTag: e173b355-d6cc-4675-935e-225738be5e08

	measure 'All Securities Title_' = ```
			
			VAR prd =
			    MAX ( 'Securities'[As Of Dt] )
			RETURN
			    "All Securities, " & FORMAT ( prd, "dd-mmm-yy" )
			-- Display dynamic name
			
			```
		isHidden
		lineageTag: 7f178edf-50d2-44ae-8814-f49b2ffca998

		changedProperty = IsHidden

	measure 'Primary Security ID - Change' =
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Primary Security ID], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Primary Security ID], TRUE () ),
			        'Securities'[As Of Period]=maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period]=priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period]=maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE ( minval, CONCATENATE ( " -> ", maxval ) ),
			        IF ( AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ), maxval, BLANK () )
			    )
		displayFolder: Security Changes Measures
		lineageTag: 47f729ad-01fd-4771-8398-59602f7e87d0

	measure 'Next Call Date - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Next Call Date], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Next Call Date], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			            FORMAT ( minval, "DD-MMM-YY" ),
			            CONCATENATE ( " -> ", FORMAT ( maxval, "DD-MMM-YY" ) )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			            FORMAT ( maxval, "DD-MMM-YY" ),
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: 526995c5-7397-41a9-9374-7de6542caa97

	measure 'Asset Class - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asset Class], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asset Class], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			            minval, CONCATENATE ( " -> ",  maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval, 
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: f447e7c7-9914-4259-8726-9224236ebcee

	measure 'Asset Group - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asset Group], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asset Group], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: 44f4f7a1-aaad-47c9-9b95-a8417ba0601c

	measure 'Asset Type - Change' =
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asset Type], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asset Type], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			       IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
		displayFolder: Security Changes Measures
		lineageTag: 3759fa7c-40ca-480d-86a3-0599b98efc5e

	measure 'Security Description - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Security Description], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Security Description], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: a3589622-dcc6-44e3-92df-9aede7500b69

	measure 'Cusip - Change' =
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Cusip], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Cusip], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			       IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
		displayFolder: Security Changes Measures
		lineageTag: 740d4156-8135-4151-91d2-5e12f1e92213

	measure 'Coupon - Change' =
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Coupon], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Coupon], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			        IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
		displayFolder: Security Changes Measures
		lineageTag: 09439cfb-60fb-4077-be9f-eeba0f842f99

	measure 'Maturity Date - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Maturity Date], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Maturity Date], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			            FORMAT ( minval, "DD-MMM-YY" ),
			            CONCATENATE ( " -> ", FORMAT ( maxval, "DD-MMM-YY" ) )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			            FORMAT ( maxval, "DD-MMM-YY" ),
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: 10b04a51-0c60-4f18-a90e-9a4e9a42b2b8

	measure 'Next Call Price - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Next Call PX], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Next Call PX], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			      IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: b97540cf-8338-4fac-9bf4-b4d22ed5d00c

	measure 'Next Sink Date - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Next Sink Date], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Next Sink Date], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			            FORMAT ( minval, "DD-MMM-YY" ),
			            CONCATENATE ( " -> ", FORMAT ( maxval, "DD-MMM-YY" ) )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			            FORMAT ( maxval, "DD-MMM-YY" ),
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: e7f46c9a-0311-49d6-a6c2-6b1b94bef5b1

	measure 'Shares Outstanding - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Shares Outstanding], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Shares Outstanding], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			     IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: 9c4896b4-8e2c-401a-ae6c-597e7104882b

	measure 'Moodys Short Term Rating - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Moodys Short Term Rating], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Moodys Short Term Rating], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: d43096e0-d210-4b64-920d-c9f59b5ebde6

	measure 'Asia Rating - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asia Rating], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asia Rating], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: de981c87-b144-4cfb-b190-11080e8d63fd

	measure 'Fitch Short Term Rating - Change' =
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Fitch Short Term Rating], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Fitch Short Term Rating], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			        IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
		displayFolder: Security Changes Measures
		lineageTag: 8873e0f9-6d87-4220-9410-d015e9a81ecb

	measure 'S&P Short Term Rating - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[S&P Short Term Rating], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[S&P Short Term Rating], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			     IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: f37f4805-47f5-4e6c-8e60-d83db6f8d185

	measure 'Internal Risk Rating - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML IRR Rating], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML IRR Rating], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: d0e70e81-3881-40f2-b0c6-1832cf92ec57

	measure 'ML MFC Equivalent Rating - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML MFC Equivalent Rating], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML MFC Equivalent Rating], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: a9a318ce-25a6-472a-a34c-427a0c6c6e8e

	measure 'SCD Instrument Category - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[SCD Instrument Category], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[SCD Instrument Category], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: 4b252dc9-690a-4c70-bed3-9ebaeb51a56d

	measure 'Held Securities Changes Title DQ' = ```
			
			VAR FW =
			    SELECTEDVALUE ( Framework[Framework Display] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR MIN_PRD =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR MAX_PRD = MAX('Period'[Period])
			VAR startDate =
			    CALCULATE (
			        MAX('Securities'[As Of Dt]),
			        'Securities'[As of Period] = MIN_PRD
			    )
			VAR endDate =
			    CALCULATE (
			        MAX ( 'Securities'[As Of Dt] ),
			        'Securities'[As of Period] = MAX_PRD
			    )
			RETURN
			    "Held Securities Changes, " & FW & ", "
			        & FORMAT ( startDate, "dd-mmm-yy" ) & " - "
			        & FORMAT ( endDate, "dd-mmm-yy" )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: 6824d37e-8c6c-4adc-ab0a-d5a11f684583

	measure 'Primary Security ID & Desc Latest' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR maxPri =
			    CALCULATE (
			        LASTNONBLANK( 'Securities'[Primary Security ID], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR maxDesc =
			    CALCULATE (
			        LASTNONBLANK( 'Securities'[Security Description], TRUE () ),
			       'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    maxPri & " - " & maxDesc
			
			```
		lineageTag: f7db2289-cb7d-402a-bfa4-1a6992b4bb29

	measure 'Security - Change' = ```
			
			VAR maxDateRange =
			    MAX ( Period[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minDesc =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Security Description], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxDesc =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Security Description], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minCusip =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Cusip], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxCusip =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Cusip], TRUE () ),
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minCoupon =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Coupon], TRUE () ), 
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxCoupon =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Coupon], TRUE () ),  
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minmatdt =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Maturity Date], TRUE () ), 
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxmatdt =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Maturity Date], TRUE () ),
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minnxtcalldt =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Next Call Date], TRUE () ),
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxnxtcalldt =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Next Call Date], TRUE () ),   
			            'Securities'[As Of Period] = maxDateRange
			        )
			
			VAR minnxtsinkdt =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Next Sink Date], TRUE () ), 
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxnxtsinkdt =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Next Sink Date], TRUE () ), 
			            'Securities'[As Of Period] = maxDateRange
			        )
			   
			VAR minfltsp =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Coupon Spread], TRUE () ),    
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxfltsp =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Coupon Spread], TRUE () ),
			       'Securities'[As Of Period] = maxDateRange
			        )
			
			VAR minlsredt =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Last Refix Date], TRUE () ),
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxlsredt =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Last Refix Date], TRUE () ),   
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minnxtcallpx =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Next Call Px], TRUE () ),  
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxnxtcallpx =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Next Call Px], TRUE () ),
			            'Securities'[As Of Period] = maxDateRange
			        )
			   
			VAR minshrout =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Shares Outstanding], TRUE () ),
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxshrout =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Shares Outstanding], TRUE () ),
			       'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minmoodys =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Moodys], TRUE () ),   
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxmoodys =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Moodys], TRUE () ),   
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minsp =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[S&P], TRUE () ),   
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxsp =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[S&P], TRUE () ),   
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minfitch =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Fitch], TRUE () ),     
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxfitch =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Fitch], TRUE () ),   
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR mindbrs =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Dbrs], TRUE () ),   
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxdbrs =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Dbrs], TRUE () ), 
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minInternal =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Internal], TRUE () ),  
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxInternal =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Internal], TRUE () ),  
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minasia =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asia Rating], TRUE () ),   
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxasia =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asia Rating], TRUE () ),
			       'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minfitchshtterm =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Fitch Short Term Rating], TRUE () ),    
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxfitchshtterm =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Fitch Short Term Rating], TRUE () ),  
			            'Securities'[As Of Period] = maxDateRange
			        )
			   /* 
			VAR minmoodylgterm =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities DQ'[RTG Moody Long Term], TRUE () ),
			            'Securities DQ'[As Of Period] = priorDateRange
			        )
			    
			VAR maxmoodylgterm =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities DQ'[RTG Moody Long Term], TRUE () ),    
			            'Securities DQ'[As Of Period] = maxDateRange
			        )
			    */
			VAR minmoodyshtterm =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Moodys Short Term Rating], TRUE () ),   
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxmoodyshtterm =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Moodys Short Term Rating], TRUE () ),   
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minfitchlg =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG Fitch Long], TRUE () ),   
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxfitchlg =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG Fitch Long], TRUE () ),    
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minrtgmdyiss =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG MDY Issuer], TRUE () ),   
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxrtgmdyiss =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG MDY Issuer], TRUE () ),  
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minrtgsplg =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG S&P Long], TRUE () ),   
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxrtgsplg =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG S&P Long], TRUE () ),
			   'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minrtgspout =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[S&P Rating Outlook], TRUE () ),  
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxrtgspout =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[S&P Rating Outlook], TRUE () ),  
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minMLIRR =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML IRR Rating], TRUE () ),   
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxMLIRR =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML IRR Rating], TRUE () ),   
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minMLMFC =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML MFC Equivalent Rating], TRUE () ), 
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxMLMFC =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML MFC Equivalent Rating], TRUE () ),  
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minrtgmdylg =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG MDY Long Issue Level], TRUE () ),    
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxrtgmdylg =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG MDY Long Issue Level], TRUE () ),  
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minspshrtterm =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[S&P Short Term Rating], TRUE () ),    
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxspshrtterm =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[S&P Short Term Rating], TRUE () ),   
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minPsecId =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Primary Security ID], TRUE () ),   
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxPsecId =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Primary Security ID], TRUE () ),   
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minassettype =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asset Type], TRUE () ),  
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxassettype =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asset Type], TRUE () ),  
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minassetclass =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asset Class], TRUE () ),   
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxassetclass =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asset Class], TRUE () ),   
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minFAS157 =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML Ifrs 13 Level], TRUE () ),
			   
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxFAS157 =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML Ifrs 13 Level], TRUE () ),  
			            'Securities'[As Of Period] = maxDateRange
			        )
			   
			VAR minInstype =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[SCD Instrument Category], TRUE () ),
			      'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxInstype =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[SCD Instrument Category], TRUE () ), 
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minNAICIns =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML NAIC Instrument Type Cd], TRUE () ), 
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxNAICIns =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML NAIC Instrument Type Cd], TRUE () ),  
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			VAR minSecGroup =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asset Group], TRUE () ),  
			            'Securities'[As Of Period] = priorDateRange
			        )
			    
			VAR maxSecGroup =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Asset Group], TRUE () ),    
			            'Securities'[As Of Period] = maxDateRange
			        )
			    
			RETURN
			    IF (
			        AND ( OR ( minsec = 0, ISBLANK ( minsec ) ), maxsec > 0 ),
			        "New",
			        IF (
			            AND ( minsec > 0, OR ( maxsec = 0, ISBLANK ( maxsec ) ) ),
			            "Removed",
			            IF (
			                COALESCE ( minDesc, "" ) <> COALESCE ( maxDesc, "" )
			                    || COALESCE ( minCusip, "" ) <> COALESCE ( maxCusip, "" )
			                    || COALESCE ( minspshrtterm, "" ) <> COALESCE ( maxspshrtterm, "" )
			                    || COALESCE ( minCoupon, "" ) <> COALESCE ( maxCoupon, "" )
			                    || COALESCE ( minnxtcalldt, "" ) <> COALESCE ( maxnxtcalldt, "" )
			                    || COALESCE ( minnxtsinkdt, "" ) <> COALESCE ( maxnxtsinkdt, "" )
			                    || COALESCE ( minfltsp, "" ) <> COALESCE ( maxfltsp, "" )
			                    || COALESCE ( minlsredt, "" ) <> COALESCE ( maxlsredt, "" )
			                    || COALESCE ( minnxtcallpx, "" ) <> COALESCE ( maxnxtcallpx, "" )
			                    || COALESCE ( minshrout, "" ) <> COALESCE ( maxshrout, "" )
			                    || COALESCE ( minmoodys, "" ) <> COALESCE ( maxmoodys, "" )
			                    || COALESCE ( minsp, "" ) <> COALESCE ( maxsp, "" )
			                    || COALESCE ( minfitch, "" ) <> COALESCE ( maxfitch, "" )
			                    || COALESCE ( mindbrs, "" ) <> COALESCE ( maxdbrs, "" )
			                    || COALESCE ( minInternal, "" ) <> COALESCE ( maxInternal, "" )
			                   --|| COALESCE ( minmoodylgterm, "" ) <> COALESCE ( maxmoodylgterm, "" )
			                    || COALESCE ( minfitchlg, "" ) <> COALESCE ( maxfitchlg, "" )
			                    || COALESCE ( minPsecId, "" ) <> COALESCE ( maxPsecId, "" )
			                    || COALESCE ( minassettype, "" ) <> COALESCE ( maxassettype, "" )
			                    || COALESCE ( minassetclass, "" ) <> COALESCE ( maxassetclass, "" )
			                   || COALESCE ( minrtgmdyiss, "" ) <> COALESCE ( maxrtgmdyiss, "" )
			                   || COALESCE ( minrtgsplg, "" ) <> COALESCE ( maxrtgsplg, "" )
			                   || COALESCE ( minrtgspout, "" ) <> COALESCE ( maxrtgspout, "" )
			                    || COALESCE ( minMLIRR, "" ) <> COALESCE ( maxMLIRR, "" )
			                    || COALESCE ( minMLMFC, "" ) <> COALESCE ( maxMLMFC, "" )
			                    || COALESCE ( minfitchshtterm, "" ) <> COALESCE ( maxfitchshtterm, "" )
			                    || COALESCE ( minmatdt, "" ) <> COALESCE ( maxmatdt, "" )
			                    || COALESCE ( minasia, "" ) <> COALESCE ( maxasia, "" )
			                    || COALESCE ( minmoodyshtterm, "" ) <> COALESCE ( maxmoodyshtterm, "" )
			                   || COALESCE ( minrtgmdylg, "" ) <> COALESCE ( maxrtgmdylg, "" )
			                || COALESCE ( minNAICIns, "" ) <> COALESCE ( maxNAICIns, "" )
			                    || COALESCE ( minInstype, "" ) <> COALESCE ( maxInstype, "" )
			                    || COALESCE ( minSecGroup, "" ) <> COALESCE ( maxSecGroup, "" )
			                    || COALESCE ( minFAS157, "" ) <> COALESCE ( maxFAS157, "" ),
			                "Changed",
			                BLANK ()
			            )
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: 1ae38230-ff4b-4860-8ee4-7e0f4302c2a7

	measure 'Security - Change Filter' =
			
			VAR SecChange = 'Securities'[Security - Change]
			VAR slicer =
			    SELECTEDVALUE ( 'Portfolio Change Types'[Type] )
			RETURN
			    SWITCH (
			        TRUE (),
			        slicer = "All", 1,
			        SecChange = slicer, 1,
			        0
			    )
		formatString: 0
		displayFolder: Security Changes Measures
		lineageTag: d947fa76-fae5-4a07-8162-af06bbe1e8c6

	measure '#Secs - Changes' = DISTINCTCOUNTNOBLANK('Securities'[Src Security ID])
		formatString: 0
		displayFolder: Security Changes Measures
		lineageTag: 0379e59a-ed79-4678-b262-16ba396fbfcc

	measure 'Company Code & Name (Held Sec)' =
			
			var pos = DISTINCTCOUNT('Securities Position Fact'[Src Security Id])
			var trans = DISTINCTCOUNT('Securities Transaction GA Fact'[Src Security ID])
			var pos_com = FIRSTNONBLANK('Securities Position Fact'[Company Code & Name Display],TRUE())
			var trans_com = FIRSTNONBLANK('Securities Transaction GA Fact'[Company Code & Name Display],TRUE())
			var calc = if(pos>0,pos_com,if(trans>0,trans_com))
			return calc
		lineageTag: 96114bd3-6cfe-4eb4-bec3-2dbd042f2213

	measure 'Accounting Unit Code Name (Held Sec)' =
			
			var pos = DISTINCTCOUNT('Securities Position Fact'[Src Security Id])
			var trans = DISTINCTCOUNT('Securities Transaction GA Fact'[Src Security ID])
			var pos_com = FIRSTNONBLANK('Securities Position Fact'[Accounting Unit Code & Name Display],TRUE())
			var trans_com = FIRSTNONBLANK('Securities Transaction GA Fact'[Accounting Unit Code & Name Display],TRUE())
			var calc = if(pos>0,pos_com,if(trans>0,trans_com))
			return calc
		lineageTag: c0a670bf-120b-4c7f-844f-a08d41d209f7

	measure 'Asia Asset Class Code Vietnam (Held Sec)' =
			
			var pos = DISTINCTCOUNT('Securities Position Fact'[Src Security Id])
			var trans = DISTINCTCOUNT('Securities Transaction GA Fact'[Src Security ID])
			var pos_com = FIRSTNONBLANK('Securities Position Fact'[Asia Asset Class Code Vietnam],TRUE())
			var trans_com = FIRSTNONBLANK('Securities Transaction GA Fact'[Asia Asset Class Code Vietnam],TRUE())
			var calc = if(pos>0,pos_com,if(trans>0,trans_com))
			return calc
		lineageTag: d2a97378-ad76-4a93-8e45-26d1ff2388b5

	measure 'Asia Asset Class Desc Vietnam (Held Sec)' =
			
			var pos = DISTINCTCOUNT('Securities Position Fact'[Src Security Id])
			var trans = DISTINCTCOUNT('Securities Transaction GA Fact'[Src Security ID])
			var pos_com = FIRSTNONBLANK('Securities Position Fact'[Asia Asset Class Desc Vietnam],TRUE())
			var trans_com = FIRSTNONBLANK('Securities Transaction GA Fact'[Asia Asset Class Desc Vietnam],TRUE())
			var calc = if(pos>0,pos_com,if(trans>0,trans_com))
			return calc
		lineageTag: 070cb9ef-ffef-472a-a1bf-485276430b29

	measure 'Asia Asset Class Code Indonesia (Held Sec)' =
			
			var pos = DISTINCTCOUNT('Securities Position Fact'[Src Security Id])
			var trans = DISTINCTCOUNT('Securities Transaction GA Fact'[Src Security ID])
			var pos_com = FIRSTNONBLANK('Securities Position Fact'[Asia Asset Class Code Indonesia],TRUE())
			var trans_com = FIRSTNONBLANK('Securities Transaction GA Fact'[Asia Asset Class Code Indonesia],TRUE())
			var calc = if(pos>0,pos_com,if(trans>0,trans_com))
			return calc
		lineageTag: 53e40b06-4dbd-49fe-aa1b-bc8e560b209e

	measure 'Asia Asset Class Desc Indonesia (Held Sec)' =
			
			var pos = DISTINCTCOUNT('Securities Position Fact'[Src Security Id])
			var trans = DISTINCTCOUNT('Securities Transaction GA Fact'[Src Security ID])
			var pos_com = FIRSTNONBLANK('Securities Position Fact'[Asia Asset Class Desc Indonesia],TRUE())
			var trans_com = FIRSTNONBLANK('Securities Transaction GA Fact'[Asia Asset Class Desc Indonesia],TRUE())
			var calc = if(pos>0,pos_com,if(trans>0,trans_com))
			return calc
		lineageTag: 0e6b359d-34d0-4c7c-8703-49b332141e95

	measure #SrcSecID =
			
			var pos = DISTINCTCOUNT('Securities Position Fact'[Src Security Id])
			var trans = DISTINCTCOUNT('Securities Transaction GA Fact'[Src Security ID])
			var calc = if(pos>0,pos,if(trans>0,trans))
			return calc
		formatString: 0
		lineageTag: c9531b7f-bf95-4e66-8c53-3c1a96cb62b5

	measure #PortCount =
			
			var pos = DISTINCTCOUNT('Securities Position Fact'[Portfolio Code])
			var trans = DISTINCTCOUNT('Securities Transaction GA Fact'[Portfolio Code])
			var calc = if(pos>0,pos,if(trans>0,trans))
			return calc
		formatString: 0
		lineageTag: be418c1d-1239-4886-a570-8d98b37d0b22

	measure '#Secs Count' = DISTINCTCOUNT(Securities[Primary Security ID & Desc])
		formatString: 0
		lineageTag: 80c5c2b7-f857-43b6-aece-5796b8eaacac

	measure 'Coupon Spread - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Coupon Spread], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Coupon Spread], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: d6ab8af0-7e4d-43d7-8fd6-d618e84bb6f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Last Refix Date - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Last Refix Date], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Last Refix Date], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			            FORMAT ( minval, "DD-MMM-YY" ),
			            CONCATENATE ( " -> ", FORMAT ( maxval, "DD-MMM-YY" ) )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			            FORMAT ( maxval, "DD-MMM-YY" ),
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: 723179e1-95b3-4f4f-9fda-4e3ebe58c029

	measure 'Moodys - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Moodys], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Moodys], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: bf7c1abd-bf46-42c2-beba-fc1530e20530

	measure 'S&P - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[S&P], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[S&P], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			     IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: 6bd1ad16-f6bb-4523-9872-18b64712c464

	measure 'Fitch - Change' =
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Fitch], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Fitch], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			        IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
		displayFolder: Security Changes Measures
		lineageTag: 49e3a0c0-fc09-4da9-9dd8-bbc03a9fb7f2

	measure 'Dbrs - Change' =
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Dbrs], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Dbrs], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			        IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
		displayFolder: Security Changes Measures
		lineageTag: 0396e384-4c59-4820-9bd7-1839e6e1e8be

	measure 'Internal - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Internal], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[Internal], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: 71bd5784-fe9d-47b9-b605-063854f40fb3

	measure 'RTG Fitch Long - Change' =
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG Fitch Long], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG Fitch Long], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			        IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
		displayFolder: Security Changes Measures
		lineageTag: 9ddbd91d-4f5a-49af-8b43-69102743206b

	measure 'RTG MDY Issuer - Change' =
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG MDY Issuer], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG MDY Issuer], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			        IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
		displayFolder: Security Changes Measures
		lineageTag: 06007a1a-3994-4b82-b0ac-7975f7fedc14

	measure 'RTG S&P Long - Change' =
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG S&P Long], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG S&P Long], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			        IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
		displayFolder: Security Changes Measures
		lineageTag: 61da3e89-4134-4044-89b5-ae05347cebf1

	measure 'RTG MDY Long Issue Level - Change' =
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG MDY Long Issue Level], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[RTG MDY Long Issue Level], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			        IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
		displayFolder: Security Changes Measures
		lineageTag: 2eb69cc3-1716-44e2-a4e9-dd683f184d27

	measure 'S&P Rating Outlook - Change' =
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[S&P Rating Outlook], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[S&P Rating Outlook], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			        IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
		displayFolder: Security Changes Measures
		lineageTag: cf7a8564-4c15-4b28-b3a2-e021e330f04a

	measure 'ML Ifrs 13 Level - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML Ifrs 13 Level], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML Ifrs 13 Level], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: e072cc46-439f-412d-af82-d50b2d715495

	measure 'ML NAIC Instrument Type Cd - Change' = ```
			
			VAR maxDateRange =
			    MAX ( 'Period'[Period] )
			VAR _min =
			    EDATE ( MIN ( 'Period'[End of Month] ), -1 )
			VAR priorDateRange =
			    VALUE ( YEAR ( _min ) & FORMAT ( MONTH ( _min ), "00" ) )
			VAR minval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML NAIC Instrument Type Cd], TRUE () ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxval =
			    CALCULATE (
			        LASTNONBLANK ( 'Securities'[ML NAIC Instrument Type Cd], TRUE () ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			VAR minsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = priorDateRange
			    )
			VAR maxsec =
			    CALCULATE (
			        COUNTROWS ( 'Securities' ),
			        'Securities'[As Of Period] = maxDateRange
			    )
			RETURN
			    IF (
			        minsec > 0
			            && maxsec > 0
			            && minval <> maxval,
			        CONCATENATE (
			             minval,
			            CONCATENATE ( " -> ", maxval )
			        ),
			        IF (
			            AND ( ISBLANK ( minval ), NOT ( ISBLANK ( maxval ) ) ),
			             maxval,
			            BLANK ()
			        )
			    )
			
			```
		displayFolder: Security Changes Measures
		lineageTag: d3b478cb-eae9-4c1a-9350-1b03f53f9bb8

	measure 'Filter Date' = ```
			
			var maxSec = CALCULATE(MAX(Securities[As Of Dt]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]))
			var calc = IF(maxSec=MAX(Securities[As Of Dt]),1,0)
			return calc
			
			```
		formatString: 0
		isHidden
		lineageTag: 53d7cc80-17ac-4cec-a876-dc91ee9e0a82

	measure 'All Security Filter (Held/Transacted/Minor Type)' = ```
			
			VAR vSecurityType = SELECTEDVALUE(Securities[ML Minor Type])
			RETURN 
			IF(
			    vSecurityType IN {"SEEDMF","SEEDETF","SEEDSEG", "MUTUAL FUND", "SEGFUND", "ETF", "NON TRADITIONAL SEED"},
			    1,
			    [#SrcSecID]
			)
			```
		formatString: 0
		isHidden
		lineageTag: 18f5ec62-82f5-4992-b588-f3566d650be0

		changedProperty = IsHidden

	measure 'Is Active Security' =
			
			
			VAR vMenduPageDate = VALUE(FORMAT(MAX(period[date]),"YYYYMM"))
			
			RETURN CALCULATE(COUNTROWS(Securities),KEEPFILTERS(Securities[As Of Period]=vMenduPageDate))
		formatString: 0
		lineageTag: 0cb8fade-ee3f-4f7c-994d-c2473ddc4356

	measure 'Ultimate parent LEI (Entities)' = MAX ('Entities'[Lei Ultimate Parent Company])
		lineageTag: ccb99281-b2ff-4083-9042-b45f71c9635f

	measure 'Ultimate parent location (Entities)' = MAX ('Entities'[Country Of Domicile])
		lineageTag: 01e58b84-4045-4382-88e2-acb44e865e01

	measure 'Ultimate parent company (Entities)' = MAX ('Entities'[Ultimate Parent Company])
		lineageTag: 05d5ac2f-f54b-42a0-9ec1-5234e83364c1

	column 'Security NK'
		dataType: string
		lineageTag: 984a471c-a048-44d0-9cb9-99151e1fcd1b
		summarizeBy: none
		sourceColumn: Security NK

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID'
		dataType: string
		lineageTag: 32b0d54d-31e8-4293-8c6c-5a607bc9f63b
		summarizeBy: none
		sourceColumn: Primary Security ID

		annotation SummarizationSetBy = Automatic

	column 'Security Description'
		dataType: string
		lineageTag: 9c7d0909-c1dc-4e60-96df-37090ebfad1a
		summarizeBy: none
		sourceColumn: Security Description

		annotation SummarizationSetBy = Automatic

	column 'As Of Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: c9f7d2ed-3218-4a93-9d4d-592b877ea61e
		summarizeBy: none
		sourceColumn: As Of Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Src
		dataType: string
		lineageTag: 8e189d56-2b1a-4865-b600-421397d57df7
		summarizeBy: none
		sourceColumn: Src

		annotation SummarizationSetBy = Automatic

	column 'Src Security ID'
		dataType: string
		lineageTag: 43a778c0-0d73-40c9-85ee-431edc0c1982
		summarizeBy: none
		sourceColumn: Src Security ID

		annotation SummarizationSetBy = Automatic

	column 'Src Market ID'
		dataType: string
		lineageTag: 47deb3c1-730f-49b4-8a74-6e6f39b8e354
		summarizeBy: none
		sourceColumn: Src Market ID

		annotation SummarizationSetBy = Automatic

	column 'SCD Security ID'
		dataType: string
		lineageTag: edae8978-8a4a-433d-af43-e78cc4f90091
		summarizeBy: none
		sourceColumn: SCD Security ID

		annotation SummarizationSetBy = Automatic

	column 'Security ID 2'
		dataType: string
		lineageTag: 4dab984a-845e-445a-b6f8-86036f5a4736
		summarizeBy: none
		sourceColumn: Security ID 2

		annotation SummarizationSetBy = Automatic

	column 'Ticker Isin'
		dataType: string
		lineageTag: 32f39ea0-a0f6-4cd1-b1c2-e473da9b3a33
		summarizeBy: none
		sourceColumn: Ticker Isin

		annotation SummarizationSetBy = Automatic

	column 'Official PPN'
		dataType: string
		lineageTag: 90ca00d6-b104-4349-8660-67082f9885b5
		summarizeBy: none
		sourceColumn: Official PPN

		annotation SummarizationSetBy = Automatic

	column 'Security Name'
		dataType: string
		lineageTag: 02c90708-72a4-43d2-b606-89279f9a5fa1
		summarizeBy: none
		sourceColumn: Security Name

		annotation SummarizationSetBy = Automatic

	column 'Bloomberg ID'
		dataType: string
		lineageTag: d90f59c9-b3d5-430b-b724-fece2021914b
		summarizeBy: none
		sourceColumn: Bloomberg ID

		annotation SummarizationSetBy = Automatic

	column 'ID PRPL'
		dataType: string
		lineageTag: 3676fa20-2b31-4c2a-bddc-04eea011f8a9
		summarizeBy: none
		sourceColumn: ID PRPL

		annotation SummarizationSetBy = Automatic

	column 'ID BB Global'
		dataType: string
		lineageTag: 6703dd11-bf0b-4e49-b059-b9cfcc4c4913
		summarizeBy: none
		sourceColumn: ID BB Global

		annotation SummarizationSetBy = Automatic

	column Cusip
		dataType: string
		lineageTag: 2631ca71-3a54-486d-aca7-ed6dd698021f
		summarizeBy: none
		sourceColumn: Cusip

		annotation SummarizationSetBy = Automatic

	column Isin
		dataType: string
		lineageTag: 13e5fd95-89c4-4156-be25-7bc2ad27cb43
		summarizeBy: none
		sourceColumn: Isin

		annotation SummarizationSetBy = Automatic

	column Ticker
		dataType: string
		lineageTag: e5ab363c-0982-44b7-a724-d881603f00b9
		summarizeBy: none
		sourceColumn: Ticker

		annotation SummarizationSetBy = Automatic

	column 'Principal Exchange'
		dataType: string
		lineageTag: 1cd49b0a-23d6-4d84-b98c-eacb135654d7
		summarizeBy: none
		sourceColumn: Principal Exchange

		annotation SummarizationSetBy = Automatic

	column Sedol
		dataType: string
		lineageTag: 3a4fc141-f2d4-4375-bc05-12fa5bc34929
		summarizeBy: none
		sourceColumn: Sedol

		annotation SummarizationSetBy = Automatic

	column 'Collateral Type'
		dataType: string
		lineageTag: 45c21843-83d8-47aa-9041-99cd7fa4edc6
		summarizeBy: none
		sourceColumn: Collateral Type

		annotation SummarizationSetBy = Automatic

	column Factor
		dataType: double
		formatString: 0.000000
		lineageTag: e1e9b875-ff3a-4606-9e98-a485aa4b4015
		summarizeBy: sum
		sourceColumn: Factor

		annotation SummarizationSetBy = User

	column Local
		dataType: string
		lineageTag: 55d502a7-bfa4-41bb-80a0-598288d49585
		summarizeBy: none
		sourceColumn: Local

		annotation SummarizationSetBy = Automatic

	column Moodys
		dataType: string
		lineageTag: 6fdf0aeb-3ae0-4d19-a430-0691b8ce0a26
		summarizeBy: none
		sourceColumn: Moodys

		annotation SummarizationSetBy = Automatic

	column 'Moodys Rating Change Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: f5b0651a-029c-4f96-96ea-879779e5ccac
		summarizeBy: none
		sourceColumn: Moodys Rating Change Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column S&P
		dataType: string
		lineageTag: f6ab5386-9326-490f-8c5d-d53c2022d84d
		summarizeBy: none
		sourceColumn: S&P

		annotation SummarizationSetBy = Automatic

	column 'S&P Rating Change Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 3844b9df-c4dc-4f26-a8ca-141085775023
		summarizeBy: none
		sourceColumn: S&P Rating Change Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'S&P Rating Outlook'
		dataType: string
		lineageTag: 0d4526af-ef16-4bb9-84ec-3c928ee635f3
		summarizeBy: none
		sourceColumn: S&P Rating Outlook

		annotation SummarizationSetBy = Automatic

	column Fitch
		dataType: string
		lineageTag: fda4adb6-50db-42df-867c-c6d548b24e45
		summarizeBy: none
		sourceColumn: Fitch

		annotation SummarizationSetBy = Automatic

	column 'Fitch Rating Change Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 82d23089-2b04-46e0-bb43-6b2966a4509f
		summarizeBy: none
		sourceColumn: Fitch Rating Change Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Dbrs
		dataType: string
		lineageTag: 0128b3e7-749d-42e5-87f4-194b9a28b6a6
		summarizeBy: none
		sourceColumn: Dbrs

		annotation SummarizationSetBy = Automatic

	column 'Dbrs Rating Change Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: caaec76e-96cf-4e63-a996-69f15ed05917
		summarizeBy: none
		sourceColumn: Dbrs Rating Change Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Internal
		dataType: string
		lineageTag: f9bc8628-acb3-4968-9816-2c92fa3dff2d
		summarizeBy: none
		sourceColumn: Internal

		annotation SummarizationSetBy = Automatic

	column 'Mam Rating'
		dataType: string
		lineageTag: 339a5509-dc43-4229-ab8e-e0632ca4d287
		summarizeBy: none
		sourceColumn: Mam Rating

		annotation SummarizationSetBy = Automatic

	column Issuer
		dataType: string
		lineageTag: 0d2cb903-b848-4be5-9abf-3620fc899d35
		summarizeBy: none
		sourceColumn: Issuer

		annotation SummarizationSetBy = Automatic

	column 'Bpl Issuer'
		dataType: string
		lineageTag: d5a91c71-b0eb-4680-ac1a-4606dea25ded
		summarizeBy: none
		sourceColumn: Bpl Issuer

		annotation SummarizationSetBy = Automatic

	column 'Internal Fund'
		dataType: string
		lineageTag: 088a7a9c-10b3-47be-9425-2674db526617
		summarizeBy: none
		sourceColumn: Internal Fund

		annotation SummarizationSetBy = Automatic

	column Coupon
		dataType: string
		lineageTag: 3a5e8a14-c9fb-4e40-87ad-4154d29181fc
		summarizeBy: none
		sourceColumn: Coupon

		annotation SummarizationSetBy = Automatic

	column 'Asset Class'
		dataType: string
		lineageTag: 172e6180-3f3c-4579-99c4-70e0e547f1fa
		summarizeBy: none
		sourceColumn: Asset Class

		annotation SummarizationSetBy = Automatic

	column 'Asset Group'
		dataType: string
		lineageTag: 02d68a57-2538-4bed-bb2e-33e938c72e57
		summarizeBy: none
		sourceColumn: Asset Group

		annotation SummarizationSetBy = Automatic

	column 'Repo Type'
		dataType: string
		lineageTag: 6f856c92-6a63-4500-aa81-a9da8370d7e0
		summarizeBy: none
		sourceColumn: Repo Type

		annotation SummarizationSetBy = Automatic

	column 'Security Type 2'
		dataType: string
		lineageTag: b0f57334-3d65-4259-8f81-90e8eb995d75
		summarizeBy: none
		sourceColumn: Security Type 2

		annotation SummarizationSetBy = Automatic

	column 'Security Fund Type'
		dataType: string
		lineageTag: 678ee6fd-f1d6-4c37-9a4e-4ad76b117931
		summarizeBy: none
		sourceColumn: Security Fund Type

		annotation SummarizationSetBy = Automatic

	column 'SCD Instrument Category'
		dataType: string
		lineageTag: 88a1da38-8ede-457f-bc5a-5521a3f063ba
		summarizeBy: none
		sourceColumn: SCD Instrument Category

		annotation SummarizationSetBy = Automatic

	column 'Inflation Linked'
		dataType: string
		lineageTag: c3ffb2d9-53bb-42af-b739-41d13f7acc3f
		summarizeBy: none
		sourceColumn: Inflation Linked

		annotation SummarizationSetBy = Automatic

	column 'Variable Coupon'
		dataType: string
		lineageTag: d37ecbac-45b7-4202-8544-c1567a9135c2
		summarizeBy: none
		sourceColumn: Variable Coupon

		annotation SummarizationSetBy = Automatic

	column 'Next Coupon Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 604c06d3-6532-47b9-9f4c-02bd0d10f650
		summarizeBy: none
		sourceColumn: Next Coupon Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Previous Coupon Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: a8e6af7f-e237-4eed-bae5-033e70dda5f6
		summarizeBy: none
		sourceColumn: Previous Coupon Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Maturity Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: bf00eeab-de11-4415-bb53-efc923c59097
		summarizeBy: none
		sourceColumn: Maturity Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Maturity Days (D)'
		dataType: int64
		formatString: 0
		lineageTag: 36136b2a-0aac-4951-9365-c1e326ffbb37
		summarizeBy: sum
		sourceColumn: Maturity Days (D)

		annotation SummarizationSetBy = Automatic

	column 'Maturity Days 2 (D)'
		dataType: int64
		formatString: 0
		lineageTag: a52cee6f-bcbd-4a6d-bbcd-2be9551fced7
		summarizeBy: sum
		sourceColumn: Maturity Days 2 (D)

		annotation SummarizationSetBy = Automatic

	column 'Reset Days'
		dataType: int64
		formatString: 0
		lineageTag: 2ce12cca-d84b-43b3-96dd-bc0483c1f374
		summarizeBy: sum
		sourceColumn: Reset Days

		annotation SummarizationSetBy = Automatic

	column 'Dividend Ex Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 0aa6e1ce-2aa8-4c98-ad0a-d22892a2aa5c
		summarizeBy: none
		sourceColumn: Dividend Ex Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Dividend Pay Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: a96c6be3-c18d-4de7-bda2-3284547642da
		summarizeBy: none
		sourceColumn: Dividend Pay Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Dividend Record Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 133430f6-ed49-4ac6-bc63-19cb54cf8b52
		summarizeBy: none
		sourceColumn: Dividend Record Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Dividend Rate'
		dataType: double
		lineageTag: 9a01dbb4-a8b5-4b0b-8c01-53beb33c2f88
		summarizeBy: sum
		sourceColumn: Dividend Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Shares Outstanding'
		dataType: double
		lineageTag: 262e402b-1a76-4b52-a805-f840eeba20c0
		summarizeBy: sum
		sourceColumn: Shares Outstanding

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Full Shares Outstanding'
		dataType: double
		lineageTag: fa845b0c-d254-47d5-ba77-322b3a45a33b
		summarizeBy: sum
		sourceColumn: Full Shares Outstanding

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price Source'
		dataType: string
		lineageTag: 3d53f072-a82f-436f-9d01-cf4bc89bc684
		summarizeBy: none
		sourceColumn: Price Source

		annotation SummarizationSetBy = Automatic

	column 'Issue Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: a5a40b52-2a83-4b8c-a79d-2558fe7f554b
		summarizeBy: none
		sourceColumn: Issue Dt

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Country
		dataType: string
		lineageTag: bb4180b9-7504-4cdc-bbc9-f5bb2d248a01
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Country Of Risk'
		dataType: string
		lineageTag: 1cf25477-7605-4000-b1c8-03cef0aa15b4
		summarizeBy: none
		sourceColumn: Country Of Risk

		annotation SummarizationSetBy = Automatic

	column 'Country Of Issue'
		dataType: string
		lineageTag: b827e487-a5e7-4c6d-b86b-fdcc75d4cdf0
		summarizeBy: none
		sourceColumn: Country Of Issue

		annotation SummarizationSetBy = Automatic

	column 'Country Of Domicile'
		dataType: string
		lineageTag: 06580a89-b69d-48d7-9794-adea60acd3e7
		summarizeBy: none
		sourceColumn: Country Of Domicile

		annotation SummarizationSetBy = Automatic

	column 'Amount Issued'
		dataType: double
		lineageTag: c22478b2-8613-4d10-89db-274ad63cb868
		summarizeBy: sum
		sourceColumn: Amount Issued

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Amount Outstanding'
		dataType: double
		lineageTag: b31ce779-0b09-48d6-87f1-fb486970af2e
		summarizeBy: sum
		sourceColumn: Amount Outstanding

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Market Sector'
		dataType: string
		lineageTag: 16094615-c6aa-4370-85e5-641c74707d92
		summarizeBy: none
		sourceColumn: Market Sector

		annotation SummarizationSetBy = Automatic

	column 'Underlying Asset Type'
		dataType: string
		lineageTag: a2e48172-e7db-4090-96fa-dea3dc517429
		summarizeBy: none
		sourceColumn: Underlying Asset Type

		annotation SummarizationSetBy = Automatic

	column 'Fund Geographic Focus'
		dataType: string
		lineageTag: a291c651-5aea-4615-a738-acdaeb185f29
		summarizeBy: none
		sourceColumn: Fund Geographic Focus

		annotation SummarizationSetBy = Automatic

	column 'Conversion Ratio'
		dataType: double
		lineageTag: 2964bd74-816d-4eff-a250-d970d2c7ec6e
		summarizeBy: sum
		sourceColumn: Conversion Ratio

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Conversion Start Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 7f944797-0be2-4c5f-8eae-7aacbf9cd1e8
		summarizeBy: none
		sourceColumn: Conversion Start Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Conversion To Ticker'
		dataType: string
		lineageTag: 636bf640-f4dd-47f9-b7f3-68b6d54c1169
		summarizeBy: none
		sourceColumn: Conversion To Ticker

		annotation SummarizationSetBy = Automatic

	column 'Voting Rights'
		dataType: double
		lineageTag: 776ea03a-e027-4ead-a5cd-71914c469a5a
		summarizeBy: sum
		sourceColumn: Voting Rights

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Convertible Indicator'
		dataType: string
		lineageTag: 1c72f36d-17ad-48ce-8453-ebbb7f76b85c
		summarizeBy: none
		sourceColumn: Convertible Indicator

		annotation SummarizationSetBy = Automatic

	column 'Issuer State Of Domicile'
		dataType: string
		lineageTag: fccbcabf-8325-40d7-a0d4-73d13c5e95a8
		summarizeBy: none
		sourceColumn: Issuer State Of Domicile

		annotation SummarizationSetBy = Automatic

	column 'Issuer State Of Incorporation'
		dataType: string
		lineageTag: 7527dff1-7577-47de-a5b8-dbe0df37f070
		summarizeBy: none
		sourceColumn: Issuer State Of Incorporation

		annotation SummarizationSetBy = Automatic

	column '144A Flag'
		dataType: string
		lineageTag: 21843bbf-f019-4b0c-9b9e-50a8f9f1933a
		summarizeBy: none
		sourceColumn: 144A Flag

		annotation SummarizationSetBy = Automatic

	column 'Agency Backed Mortgage'
		dataType: string
		lineageTag: 16c772a1-0146-40d1-9a30-f7f02d3c3348
		summarizeBy: none
		sourceColumn: Agency Backed Mortgage

		annotation SummarizationSetBy = Automatic

	column 'Reset Index'
		dataType: string
		lineageTag: c473bd71-d203-4eac-810d-42898f2b2cbb
		summarizeBy: none
		sourceColumn: Reset Index

		annotation SummarizationSetBy = Automatic

	column 'Mortgage Tranche Type Full'
		dataType: string
		lineageTag: 8b20fae1-7de2-4aea-bd48-98aba555691f
		summarizeBy: none
		sourceColumn: Mortgage Tranche Type Full

		annotation SummarizationSetBy = Automatic

	column 'Mortgage Tranche Description'
		dataType: string
		lineageTag: c3d23c93-15a5-4711-8f49-f0e5e4d4df13
		summarizeBy: none
		sourceColumn: Mortgage Tranche Description

		annotation SummarizationSetBy = Automatic

	column 'Calc Type Description'
		dataType: string
		lineageTag: 49fdb63b-3869-4077-bd8d-bf449f75b706
		summarizeBy: none
		sourceColumn: Calc Type Description

		annotation SummarizationSetBy = Automatic

	column 'Next Reset Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 9e403aba-69d4-4f98-b2ff-f26fc4aaf199
		summarizeBy: none
		sourceColumn: Next Reset Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Contract Size'
		dataType: double
		lineageTag: 2c896789-dd0a-4d83-a3c0-fbb686695fa3
		summarizeBy: sum
		sourceColumn: Contract Size

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Exercise Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: a5e254b5-4616-44e1-88d2-6b081975a910
		summarizeBy: none
		sourceColumn: Exercise Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Expiry Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: fc399c5a-1aca-4982-95a8-68cbc7b5e1e0
		summarizeBy: none
		sourceColumn: Expiry Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Contract Side'
		dataType: string
		lineageTag: 096eb22c-e518-41a8-883a-06c733c670bc
		summarizeBy: none
		sourceColumn: Contract Side

		annotation SummarizationSetBy = Automatic

	column 'Future Contract Date'
		dataType: string
		lineageTag: bd9c4b52-b438-41ba-9527-98a740c0fdc3
		summarizeBy: none
		sourceColumn: Future Contract Date

		annotation SummarizationSetBy = Automatic

	column 'Ultimate Parent Company Name'
		dataType: string
		lineageTag: 5d1279d9-b6f6-4b72-b359-48d9ef96cf7f
		summarizeBy: none
		sourceColumn: Ultimate Parent Company Name

		annotation SummarizationSetBy = Automatic

	column 'Us Illiquid'
		dataType: string
		lineageTag: 19bdff00-aff1-4a9f-a026-b3849cd9f807
		summarizeBy: none
		sourceColumn: Us Illiquid

		annotation SummarizationSetBy = Automatic

	column 'Ca Illiquid'
		dataType: string
		lineageTag: 83379730-e91a-4b75-aed8-a35ba12755cb
		summarizeBy: none
		sourceColumn: Ca Illiquid

		annotation SummarizationSetBy = Automatic

	column 'Municipal Lease Obligation'
		dataType: string
		lineageTag: c5791e92-970a-410a-b38c-89ffb00062e3
		summarizeBy: none
		sourceColumn: Municipal Lease Obligation

		annotation SummarizationSetBy = Automatic

	column 'Regulatory Type'
		dataType: string
		lineageTag: bd4a10dc-7d87-4a55-9170-1cbc3f73c9d1
		summarizeBy: none
		sourceColumn: Regulatory Type

		annotation SummarizationSetBy = Automatic

	column 'Reg S'
		dataType: string
		lineageTag: 29c9272d-5574-4177-9c1e-73f0d1636895
		summarizeBy: none
		sourceColumn: Reg S

		annotation SummarizationSetBy = Automatic

	column 'Sinkable Indicator'
		dataType: string
		lineageTag: e5dc55eb-dc50-425e-bf31-7b498cf29f05
		summarizeBy: none
		sourceColumn: Sinkable Indicator

		annotation SummarizationSetBy = Automatic

	column 'Next Sink Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 2b68b766-35c7-4664-9dc3-a268683cf1db
		summarizeBy: none
		sourceColumn: Next Sink Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Islamic Indicator'
		dataType: string
		lineageTag: e574065b-38b0-44b3-9f65-c787a0b6f480
		summarizeBy: none
		sourceColumn: Islamic Indicator

		annotation SummarizationSetBy = Automatic

	column 'Mortgage Principal Losses'
		dataType: double
		lineageTag: b71ecb8a-75ae-430d-a9ef-ab5e98c20940
		summarizeBy: sum
		sourceColumn: Mortgage Principal Losses

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mortgage Interest Shortfall'
		dataType: double
		lineageTag: d6ee1d9b-7bf5-4f51-ac5e-6c19329f8ea7
		summarizeBy: sum
		sourceColumn: Mortgage Interest Shortfall

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Local ID'
		dataType: string
		lineageTag: 7ac50d65-1001-4b6f-a469-cb2336620d22
		summarizeBy: none
		sourceColumn: Local ID

		annotation SummarizationSetBy = Automatic

	column 'Local Sector'
		dataType: string
		lineageTag: 4ed30597-fd65-4291-8df5-93cfe1d98473
		summarizeBy: none
		sourceColumn: Local Sector

		annotation SummarizationSetBy = Automatic

	column 'Asia Rating'
		dataType: string
		lineageTag: fbc8ff72-eeb5-4b30-890c-e40b836b5c85
		summarizeBy: none
		sourceColumn: Asia Rating

		annotation SummarizationSetBy = Automatic

	column 'Ram Rating'
		dataType: string
		lineageTag: 0a66d151-6b78-4b5f-8bd6-8d7bb5971da7
		summarizeBy: none
		sourceColumn: Ram Rating

		annotation SummarizationSetBy = Automatic

	column 'Marc Rating'
		dataType: string
		lineageTag: 12f38dc2-54ec-4d24-84f7-19f2f754d012
		summarizeBy: none
		sourceColumn: Marc Rating

		annotation SummarizationSetBy = Automatic

	column 'ML Liquidity Change'
		dataType: string
		lineageTag: de487fd9-e8a8-4144-a363-0a57589013c1
		summarizeBy: none
		sourceColumn: ML Liquidity Change

		annotation SummarizationSetBy = Automatic

	column 'ML Municipal Obligor'
		dataType: string
		lineageTag: ef2cc9b3-0712-48fd-9fd3-d87328a710aa
		summarizeBy: none
		sourceColumn: ML Municipal Obligor

		annotation SummarizationSetBy = Automatic

	column 'Offering Type'
		dataType: string
		lineageTag: 5147a549-4f55-4dc6-a618-63d299aa3384
		summarizeBy: none
		sourceColumn: Offering Type

		annotation SummarizationSetBy = Automatic

	column 'Regulatory Structure'
		dataType: string
		lineageTag: 76ad6a88-36a4-4cf1-a15e-652aa6902176
		summarizeBy: none
		sourceColumn: Regulatory Structure

		annotation SummarizationSetBy = Automatic

	column 'Exchange Country'
		dataType: string
		lineageTag: 4847aae1-22cb-4e20-9e0b-dd6f42b89490
		summarizeBy: none
		sourceColumn: Exchange Country

		annotation SummarizationSetBy = Automatic

	column 'Issuer Type'
		dataType: string
		lineageTag: 19d50e15-a667-4866-a118-717ef7c63d94
		summarizeBy: none
		sourceColumn: Issuer Type

		annotation SummarizationSetBy = Automatic

	column 'My Local Sec Type'
		dataType: string
		lineageTag: 097127d8-c291-4664-91d9-504ec1e848de
		summarizeBy: none
		sourceColumn: My Local Sec Type

		annotation SummarizationSetBy = Automatic

	column 'Private Placement'
		dataType: string
		lineageTag: 62b8d173-dc48-4e8e-ad0a-7a29e79b0299
		summarizeBy: none
		sourceColumn: Private Placement

		annotation SummarizationSetBy = Automatic

	column 'Default Flag'
		dataType: string
		lineageTag: 0ee112c3-58a3-42f6-8d43-68a04477aafa
		summarizeBy: none
		sourceColumn: Default Flag

		annotation SummarizationSetBy = Automatic

	column 'Fi Type'
		dataType: string
		lineageTag: a7fadc91-ea9c-446e-a93e-419bb2e34528
		summarizeBy: none
		sourceColumn: Fi Type

		annotation SummarizationSetBy = Automatic

	column 'S&P Short Term Rating'
		dataType: string
		lineageTag: ffa875a3-37a6-4ac0-a909-bb55bbd49880
		summarizeBy: none
		sourceColumn: S&P Short Term Rating

		annotation SummarizationSetBy = Automatic

	column 'Moodys Short Term Rating'
		dataType: string
		lineageTag: 364b199a-4437-4d81-9b71-5d67717b6e95
		summarizeBy: none
		sourceColumn: Moodys Short Term Rating

		annotation SummarizationSetBy = Automatic

	column 'Fitch Short Term Rating'
		dataType: string
		lineageTag: 822c5108-8b7b-4075-9a2e-27320e1c129e
		summarizeBy: none
		sourceColumn: Fitch Short Term Rating

		annotation SummarizationSetBy = Automatic

	column 'Bpl Country'
		dataType: string
		lineageTag: 43b78144-6c5f-4759-852d-8bbcc0aedc36
		summarizeBy: none
		sourceColumn: Bpl Country

		annotation SummarizationSetBy = Automatic

	column 'Discount Indicator'
		dataType: string
		lineageTag: 43a6c56a-605c-42ac-836f-226fbfbeb2b7
		summarizeBy: none
		sourceColumn: Discount Indicator

		annotation SummarizationSetBy = Automatic

	column 'St Comprehensive'
		dataType: string
		lineageTag: f1dec84f-d9b1-433a-83e2-76cca3bb1787
		summarizeBy: none
		sourceColumn: St Comprehensive

		annotation SummarizationSetBy = Automatic

	column 'Eq Sector'
		dataType: string
		lineageTag: 13bb6ef0-55bd-4ecf-a419-2e6058a87632
		summarizeBy: none
		sourceColumn: Eq Sector

		annotation SummarizationSetBy = Automatic

	column 'Accrual Currency'
		dataType: string
		lineageTag: 27dd5347-4402-49a9-ab65-76ff3e1a8f2a
		summarizeBy: none
		sourceColumn: Accrual Currency

		annotation SummarizationSetBy = Automatic

	column 'Settlement Type'
		dataType: string
		lineageTag: d0a65e8b-1663-4e81-92ff-55955d0c4ed4
		summarizeBy: none
		sourceColumn: Settlement Type

		annotation SummarizationSetBy = Automatic

	column Sector
		dataType: string
		lineageTag: dd30e98a-5c98-4613-88eb-20d7db8fd883
		summarizeBy: none
		sourceColumn: Sector

		annotation SummarizationSetBy = Automatic

	column 'Industry Group'
		dataType: string
		lineageTag: 9f6da36e-5dce-4461-8b67-abb7ca7b2ba3
		summarizeBy: none
		sourceColumn: Industry Group

		annotation SummarizationSetBy = Automatic

	column Industry
		dataType: string
		lineageTag: e1f7cdbe-c4ab-49a7-89fe-ec4969d3a4f3
		summarizeBy: none
		sourceColumn: Industry

		annotation SummarizationSetBy = Automatic

	column 'Sub Industry'
		dataType: string
		lineageTag: 7d1c185c-e37b-4a1f-b927-0ff735a762a1
		summarizeBy: none
		sourceColumn: Sub Industry

		annotation SummarizationSetBy = Automatic

	column 'Gics Bics'
		dataType: string
		lineageTag: e682e4dd-346c-409c-8425-9fecdd1c4b03
		summarizeBy: none
		sourceColumn: Gics Bics

		annotation SummarizationSetBy = Automatic

	column 'Subord Type'
		dataType: string
		lineageTag: 09366bcb-3108-43d1-8b9e-70f540034fc4
		summarizeBy: none
		sourceColumn: Subord Type

		annotation SummarizationSetBy = Automatic

	column 'ML Ifrs 13 Level'
		dataType: string
		lineageTag: 61d777f5-3114-4faf-970d-94d810fa12ec
		summarizeBy: none
		sourceColumn: ML Ifrs 13 Level

		annotation SummarizationSetBy = Automatic

	column 'Price Point'
		dataType: string
		lineageTag: 78ed48a0-f522-4ed0-a7de-db357abe39ff
		summarizeBy: none
		sourceColumn: Price Point

		annotation SummarizationSetBy = Automatic

	column 'Day Count'
		dataType: string
		lineageTag: 84ab69cf-77c5-474e-a8c6-2bc307e617cf
		summarizeBy: none
		sourceColumn: Day Count

		annotation SummarizationSetBy = Automatic

	column 'Findur ID'
		dataType: string
		lineageTag: 0cd6167d-cf75-4ad7-bc42-6062b288615c
		summarizeBy: none
		sourceColumn: Findur ID

		annotation SummarizationSetBy = Automatic

	column 'Manulife Local Price'
		dataType: double
		lineageTag: 07c46b26-d42b-4aca-bdce-30d19eb3f89a
		summarizeBy: sum
		sourceColumn: Manulife Local Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: aa828db3-e613-47b7-82bf-463f1118908d
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Payment Rank'
		dataType: string
		lineageTag: 76943de4-041d-4dd6-a609-d1d37ef98984
		summarizeBy: none
		sourceColumn: Payment Rank

		annotation SummarizationSetBy = Automatic

	column 'ML Investment Id'
		dataType: string
		lineageTag: 57366eef-0187-4617-bd0d-e7ff34be4f6a
		summarizeBy: none
		sourceColumn: ML Investment Id

		annotation SummarizationSetBy = Automatic

	column 'ML Investment Type Cd'
		dataType: string
		lineageTag: b4c98bc4-301a-4fbe-b78e-da574b22338f
		summarizeBy: none
		sourceColumn: ML Investment Type Cd

		annotation SummarizationSetBy = Automatic

	column 'Coupon Frequency'
		dataType: string
		lineageTag: bb02a4c9-ea58-415d-ad1e-96f5158943bb
		summarizeBy: none
		sourceColumn: Coupon Frequency

		annotation SummarizationSetBy = Automatic

	column 'SCD GL Classification'
		dataType: string
		lineageTag: 93ab23d1-e15a-4018-a5f3-dd0420fe3a9f
		summarizeBy: none
		sourceColumn: SCD GL Classification

		annotation SummarizationSetBy = Automatic

	column 'SCD GL Classification JGAAP'
		dataType: string
		lineageTag: 4a13e311-16cc-4273-80de-f7a36ad59603
		summarizeBy: none
		sourceColumn: SCD GL Classification JGAAP

		annotation SummarizationSetBy = Automatic

	column 'SCD GL Classification NAIC'
		dataType: string
		lineageTag: b5cc7833-ba76-43ec-a565-21c32b17ae3c
		summarizeBy: none
		sourceColumn: SCD GL Classification NAIC

		annotation SummarizationSetBy = Automatic

	column 'ML Private Asset ID'
		dataType: string
		lineageTag: c4553a99-ab3c-4961-8109-6d5b06b60ea2
		summarizeBy: none
		sourceColumn: ML Private Asset ID

		annotation SummarizationSetBy = Automatic

	column 'Japan Credit Rating Cd'
		dataType: string
		lineageTag: 3ddedc9e-115a-4024-827f-b20e288655cf
		summarizeBy: none
		sourceColumn: Japan Credit Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'RI Rating Cd'
		dataType: string
		lineageTag: 68029965-9368-42d7-b52d-477ea5d55a70
		summarizeBy: none
		sourceColumn: RI Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'ML Local China ID'
		dataType: string
		lineageTag: 4e4ddcb4-a548-4240-96fd-ec0406150ef5
		summarizeBy: none
		sourceColumn: ML Local China ID

		annotation SummarizationSetBy = Automatic

	column 'ML Vault ID'
		dataType: string
		lineageTag: a34006d6-6998-4173-a85f-3853719ec4b5
		summarizeBy: none
		sourceColumn: ML Vault ID

		annotation SummarizationSetBy = Automatic

	column 'ML Vault Name'
		dataType: string
		lineageTag: 8e66de88-2f1c-4dae-8f25-43b7abc12a2c
		summarizeBy: none
		sourceColumn: ML Vault Name

		annotation SummarizationSetBy = Automatic

	column 'ML IRR Rating'
		dataType: string
		lineageTag: cd388e5d-e0c8-4892-9921-be672e58364c
		summarizeBy: none
		sourceColumn: ML IRR Rating

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ML MFC Equivalent Rating'
		dataType: string
		isHidden
		lineageTag: f3be8307-fa06-4d5b-ac1b-efda2185fb0c
		summarizeBy: none
		sourceColumn: ML MFC Equivalent Rating

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ML Primary Rating Cd'
		dataType: string
		lineageTag: 9634f54b-4527-4760-9b11-3cd5ed8361d4
		summarizeBy: none
		sourceColumn: ML Primary Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'ML JH Rating Cd'
		dataType: string
		lineageTag: 26fbe0c9-6b2d-435b-968e-3d527cf1f8e5
		summarizeBy: none
		sourceColumn: ML JH Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'Has Coupon Variable'
		dataType: string
		lineageTag: a7c8b0d6-79e5-493f-8537-efc4ee870d03
		summarizeBy: none
		sourceColumn: Has Coupon Variable

		annotation SummarizationSetBy = Automatic

	column 'Next Call Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 34fc218d-4f87-4a42-a9a6-36ae0ea984dd
		summarizeBy: none
		sourceColumn: Next Call Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Price Currency'
		dataType: string
		lineageTag: e8b0f1eb-7174-4313-ba93-a366ac80f62c
		summarizeBy: none
		sourceColumn: Price Currency

		annotation SummarizationSetBy = Automatic

	column 'Next Call PX'
		dataType: double
		lineageTag: 7b7f09b9-c3bb-41fc-b3cb-d4c4fa9a1a6e
		summarizeBy: sum
		sourceColumn: Next Call PX

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Next Put PX'
		dataType: double
		lineageTag: 02da532d-63a9-4941-a3a0-335ee3b6e120
		summarizeBy: sum
		sourceColumn: Next Put PX

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Next Put Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: ff0cbd43-1a15-4f24-a191-600906314faf
		summarizeBy: none
		sourceColumn: Next Put Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Make Whole Call'
		dataType: string
		lineageTag: c6a54014-9dcb-4f79-ba10-cf96422d8626
		summarizeBy: none
		sourceColumn: Make Whole Call

		annotation SummarizationSetBy = Automatic

	column Callable
		dataType: string
		lineageTag: ed2f242b-4f22-4464-bcc4-f5c0295661fd
		summarizeBy: none
		sourceColumn: Callable

		annotation SummarizationSetBy = Automatic

	column Putable
		dataType: string
		lineageTag: 45ace53e-6234-4afd-8b61-3f83f8684fe1
		summarizeBy: none
		sourceColumn: Putable

		annotation SummarizationSetBy = Automatic

	column 'Std Currency'
		dataType: string
		lineageTag: dca5bfb4-6f89-44c3-adef-82b6a10da3cd
		summarizeBy: none
		sourceColumn: Std Currency

		annotation SummarizationSetBy = Automatic

	column 'Coupon Type'
		dataType: string
		lineageTag: 409b147f-6997-44d8-93f3-47e736cf3783
		summarizeBy: none
		sourceColumn: Coupon Type

		annotation SummarizationSetBy = Automatic

	column 'ID BPL Pricing Strategy'
		dataType: string
		lineageTag: 0f197b67-3d1b-4cd4-879f-c7d5c8d92067
		summarizeBy: none
		sourceColumn: ID BPL Pricing Strategy

		annotation SummarizationSetBy = Automatic

	column 'ID BPL Price Point'
		dataType: string
		lineageTag: 723f6b5e-fca7-4ce6-9e58-91fd48cf949a
		summarizeBy: none
		sourceColumn: ID BPL Price Point

		annotation SummarizationSetBy = Automatic

	column 'Indonesian Price'
		dataType: double
		lineageTag: 97f74dce-a00c-4a07-be74-0610faf5b6da
		summarizeBy: sum
		sourceColumn: Indonesian Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'MRM Sector (Private Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: 431ef170-5298-4fe9-a35d-a76a12474146
		summarizeBy: none
		sourceColumn: MRM Sector (Private Sec)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Calm Category'
		dataType: string
		lineageTag: 7c6dcd3c-e418-4cd9-b10e-f5ab8aefad80
		summarizeBy: none
		sourceColumn: Calm Category

		annotation SummarizationSetBy = Automatic

	column 'Schedule BA Asset Category Code'
		dataType: string
		lineageTag: 0881a3ec-1c65-49a6-809d-1af88df541b0
		summarizeBy: none
		sourceColumn: Schedule BA Asset Category Code

		annotation SummarizationSetBy = Automatic

	column 'Seed Money Ind'
		dataType: string
		lineageTag: 9a13730c-8e7d-4c34-8322-5558e8953b0d
		summarizeBy: none
		sourceColumn: Seed Money Ind

		annotation SummarizationSetBy = Automatic

	column 'ML Minor Type'
		dataType: string
		lineageTag: 2e619a5a-cfd2-4910-a841-941c2af9db91
		summarizeBy: none
		sourceColumn: ML Minor Type

		annotation SummarizationSetBy = Automatic

	column 'BICS Level2 Industry Group Desc'
		dataType: string
		lineageTag: 5a21f03f-a7b6-45f1-ba0c-944b398aebb4
		summarizeBy: none
		sourceColumn: BICS Level2 Industry Group Desc

		annotation SummarizationSetBy = Automatic

	column 'SCD Security Type'
		dataType: string
		lineageTag: 18141fe2-9a57-4c2c-b07c-51467e3638c5
		summarizeBy: none
		sourceColumn: SCD Security Type

		annotation SummarizationSetBy = Automatic

	column 'Issuer Long Comp Name'
		dataType: string
		lineageTag: b81d42d9-755f-496e-b417-e057a79fcec1
		summarizeBy: none
		sourceColumn: Issuer Long Comp Name

		annotation SummarizationSetBy = Automatic

	column 'Issuer Name'
		dataType: string
		lineageTag: fad30931-7182-4e69-a528-db86059909f4
		summarizeBy: none
		sourceColumn: Issuer Name

		annotation SummarizationSetBy = Automatic

	column 'Paying Agent'
		dataType: string
		lineageTag: 753c6fef-424b-424e-85b4-e1aa4fb3ef56
		summarizeBy: none
		sourceColumn: Paying Agent

		annotation SummarizationSetBy = Automatic

	column 'Long Company Name'
		dataType: string
		lineageTag: 1d70912a-e423-4239-bf27-75d731fa8fa1
		summarizeBy: none
		sourceColumn: Long Company Name

		annotation SummarizationSetBy = Automatic

	column 'BICS Level1 Sector Desc'
		dataType: string
		lineageTag: bb310859-54fe-4164-a6a6-71ea86f092ac
		summarizeBy: none
		sourceColumn: BICS Level1 Sector Desc

		annotation SummarizationSetBy = Automatic

	column 'BICS Level3 Industry Desc'
		dataType: string
		lineageTag: d0e53a3a-f4ba-46be-be52-92677eebdfb9
		summarizeBy: none
		sourceColumn: BICS Level3 Industry Desc

		annotation SummarizationSetBy = Automatic

	column 'BICS Level4 Sub Industry Desc'
		dataType: string
		lineageTag: ffebe8df-da35-4189-b684-a4a35e54adbc
		summarizeBy: none
		sourceColumn: BICS Level4 Sub Industry Desc

		annotation SummarizationSetBy = Automatic

	column 'Analyst Team'
		dataType: string
		lineageTag: 901e438d-0ace-41b4-a02b-1237d91933da
		summarizeBy: none
		sourceColumn: Analyst Team

		annotation SummarizationSetBy = Automatic

	column 'ID BB Company'
		dataType: string
		lineageTag: 0e22bc62-f95e-4314-a2a5-a3bffd8400b9
		summarizeBy: none
		sourceColumn: ID BB Company

		annotation SummarizationSetBy = Automatic

	column 'ID BB Global Company'
		dataType: string
		lineageTag: f3e8b010-4300-4c9e-bf84-3c8c89cd72f3
		summarizeBy: none
		sourceColumn: ID BB Global Company

		annotation SummarizationSetBy = Automatic

	column 'Asset Type'
		dataType: string
		lineageTag: 7f40e837-3797-410c-89cc-01766eb30394
		summarizeBy: none
		sourceColumn: Asset Type

		annotation SummarizationSetBy = Automatic

	column 'Coupon Spread'
		dataType: double
		lineageTag: 478316ce-02fb-4792-8242-441bf3367e15
		summarizeBy: sum
		sourceColumn: Coupon Spread

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ML Ifrs Accounting Method'
		dataType: string
		lineageTag: fd67a412-bd85-4793-ac69-3b8d7af7ae9c
		summarizeBy: none
		sourceColumn: ML Ifrs Accounting Method

		annotation SummarizationSetBy = Automatic

	column 'ML Lgaap Accounting Method'
		dataType: string
		lineageTag: 1b81605c-dadf-487f-89f0-2a92ebdcb791
		summarizeBy: none
		sourceColumn: ML Lgaap Accounting Method

		annotation SummarizationSetBy = Automatic

	column 'ML Stat Accounting Method'
		dataType: string
		lineageTag: 2b35f58b-69ad-49e2-bde8-0b5301e45a0f
		summarizeBy: none
		sourceColumn: ML Stat Accounting Method

		annotation SummarizationSetBy = Automatic

	column 'ML Ba Avr Cd'
		dataType: string
		lineageTag: 9be7ed19-e01a-4384-a245-1da33e1575c7
		summarizeBy: none
		sourceColumn: ML Ba Avr Cd

		annotation SummarizationSetBy = Automatic

	column 'Called Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 4b8faac1-910d-4112-a140-1a1e0d9e8a01
		summarizeBy: none
		sourceColumn: Called Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Called Px'
		dataType: double
		lineageTag: c978a306-04ae-490d-b85c-733c5db4bf5d
		summarizeBy: sum
		sourceColumn: Called Px

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Is Perpetual'
		dataType: string
		lineageTag: 0586420d-5731-492a-a319-4cada893b5a6
		summarizeBy: none
		sourceColumn: Is Perpetual

		annotation SummarizationSetBy = Automatic

	column 'Basic Spread'
		dataType: double
		lineageTag: a5dbf4a4-a869-4051-b939-7037dcb71711
		summarizeBy: sum
		sourceColumn: Basic Spread

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Fix To Float Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 89e29b02-e133-4a95-aa57-797160e19c4b
		summarizeBy: none
		sourceColumn: Fix To Float Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'GGI Indicator'
		dataType: string
		lineageTag: 21049ea4-11a0-4487-aa2f-bf05624ae34b
		summarizeBy: none
		sourceColumn: GGI Indicator

		annotation SummarizationSetBy = Automatic

	column 'ML SD Class Desc'
		dataType: string
		lineageTag: c8181aca-a379-4533-9a43-1e8aaf72637b
		summarizeBy: none
		sourceColumn: ML SD Class Desc

		annotation SummarizationSetBy = Automatic

	column 'Dg Issuer Cd'
		dataType: string
		lineageTag: 8f7d6604-ef02-4684-8edf-2f704e306cd4
		summarizeBy: none
		sourceColumn: Dg Issuer Cd

		annotation SummarizationSetBy = Automatic

	column 'ML MFC Equivalent Eff Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: e508750f-c2ec-4460-86d5-1d8bcf445ca5
		summarizeBy: none
		sourceColumn: ML MFC Equivalent Eff Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ML Mim Na Rating Eff Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 938e2464-0d0a-494a-8e54-9414b973e0b9
		summarizeBy: none
		sourceColumn: ML Mim Na Rating Eff Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ML Mim Asia Rating Eff Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 93724d86-c086-455d-98ee-ab087c05be12
		summarizeBy: none
		sourceColumn: ML Mim Asia Rating Eff Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ML Speq Rating'
		dataType: string
		lineageTag: 6ea937f5-ae2d-4142-b0ff-49fc66d35086
		summarizeBy: none
		sourceColumn: ML Speq Rating

		annotation SummarizationSetBy = Automatic

	column 'ML Speq Eff Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: f00a363c-94bf-45b3-8aa2-6d1930099b35
		summarizeBy: none
		sourceColumn: ML Speq Eff Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ML JH Rating Effective Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: cde7df24-fd14-46ef-82fb-2096414973fd
		summarizeBy: none
		sourceColumn: ML JH Rating Effective Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Japan Credit Rating Effective Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 26bc9aa7-5749-44c1-be70-1a4a5a9dd686
		summarizeBy: none
		sourceColumn: Japan Credit Rating Effective Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ML IRR Eff Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: c37f33fc-953e-46de-b90c-85217a7dee6a
		summarizeBy: none
		sourceColumn: ML IRR Eff Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'RI Rating Effective Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 54e4cf11-c6ed-4a13-91a6-478f936f75f4
		summarizeBy: none
		sourceColumn: RI Rating Effective Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ML SD Type Desc'
		dataType: string
		lineageTag: 4e4d4e30-d2e0-4f67-b06b-60accd25570b
		summarizeBy: none
		sourceColumn: ML SD Type Desc

		annotation SummarizationSetBy = Automatic

	column 'ID Cins'
		dataType: string
		lineageTag: d870952f-8440-4508-95e6-cd2f4ed8919b
		summarizeBy: none
		sourceColumn: ID Cins

		annotation SummarizationSetBy = Automatic

	column 'ML Capital Structure Cd'
		dataType: string
		lineageTag: 20153e8b-7fab-400f-81c7-cacb9258c4c7
		summarizeBy: none
		sourceColumn: ML Capital Structure Cd

		annotation SummarizationSetBy = Automatic

	column 'ML Capital Structure Desc'
		dataType: string
		lineageTag: 95218bd5-ab13-4f1b-aa19-2a32ceb3c9b9
		summarizeBy: none
		sourceColumn: ML Capital Structure Desc

		annotation SummarizationSetBy = Automatic

	column 'ML Stat Collateral Type Cd'
		dataType: string
		lineageTag: 16358a45-a9a2-4f2a-85b0-642002643616
		summarizeBy: none
		sourceColumn: ML Stat Collateral Type Cd

		annotation SummarizationSetBy = Automatic

	column 'ML NAIC Report Part Cd'
		dataType: string
		lineageTag: ceddbbed-6ebb-47e7-b71e-6ad479d20011
		summarizeBy: none
		sourceColumn: ML NAIC Report Part Cd

		annotation SummarizationSetBy = Automatic

	column 'NAIC Designation'
		dataType: string
		lineageTag: e9fce774-bc98-4896-9559-f319c6fb9109
		summarizeBy: none
		sourceColumn: NAIC Designation

		annotation SummarizationSetBy = Automatic

	column 'NAIC Rating'
		dataType: int64
		formatString: 0
		lineageTag: 25131bd2-cdc5-4e14-ab23-e5869f73a4b8
		summarizeBy: sum
		sourceColumn: NAIC Rating

		annotation SummarizationSetBy = Automatic

	column 'Analyst ID'
		dataType: string
		lineageTag: fa6f4b99-1626-4924-9b09-351efde63b81
		summarizeBy: none
		sourceColumn: Analyst ID

		annotation SummarizationSetBy = Automatic

	column 'Analyst Nm'
		dataType: string
		lineageTag: 17447f35-ed92-414b-a3da-ea53be6bddd3
		summarizeBy: none
		sourceColumn: Analyst Nm

		annotation SummarizationSetBy = Automatic

	column 'Analyst Role Cd'
		dataType: string
		lineageTag: ae4c29c4-7d32-4f0d-bc36-d106b10881ea
		summarizeBy: none
		sourceColumn: Analyst Role Cd

		annotation SummarizationSetBy = Automatic

	column 'Primary Rating Effective Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: a92f99ec-a3fb-4ad1-afbd-9cddb9d5217d
		summarizeBy: none
		sourceColumn: Primary Rating Effective Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ML NAIC Instrument Type Cd'
		dataType: string
		lineageTag: f9f4d490-0f75-4d27-b6c0-70546aad0fc9
		summarizeBy: none
		sourceColumn: ML NAIC Instrument Type Cd

		annotation SummarizationSetBy = Automatic

	column 'ML SD Class Cd'
		dataType: string
		lineageTag: dacd9b1e-d8b0-4bab-967a-142dbacc8409
		summarizeBy: none
		sourceColumn: ML SD Class Cd

		annotation SummarizationSetBy = Automatic

	column 'ML SD Subclass Cd'
		dataType: string
		lineageTag: c0ffa7f3-5c09-47fc-8a75-f72283219079
		summarizeBy: none
		sourceColumn: ML SD Subclass Cd

		annotation SummarizationSetBy = Automatic

	column 'ML SD Type Cd'
		dataType: string
		lineageTag: 8231ae4c-502a-4577-a58a-88605e2b6f85
		summarizeBy: none
		sourceColumn: ML SD Type Cd

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID & Desc' = ```
			
			'Securities'[Primary Security ID] & " - " & 'Securities'[Security Description]
			
			```
		lineageTag: ace9c8ae-25e0-463b-a093-79a090583889
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Country Of Issue - NoBlank' = ```
			
			var country = 'Securities'[Country Of Issue]
			var calc = 
			if(country= BLANK(),LEFT('Securities'[Local],2),country)
			return calc
			```
		lineageTag: 60b004f1-959f-49ed-9ed6-39dd5479fb32
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Country - NoBlank' = ```
			
			var country = 'Securities'[Country]
			var calc = 
			if(country= BLANK(),LEFT('Securities'[Local],2),country)
			return calc
			```
		lineageTag: 9700af55-180d-481e-ac65-5b75b2b983ec
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Public/Private Indicator' = ```
			
			var code = 'Securities'[ML Investment Type Cd]
			return 
			IF(code IN {"Private","Secondary Private"},"Private","Public")
			```
		lineageTag: e2ac4830-99d2-4588-acc8-dce491666271
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'As Of Period' = YEAR('Securities'[As Of Dt])*100+MONTH('Securities'[As Of Dt])
		formatString: 0
		lineageTag: ad49522b-b92b-4f04-b73d-dc6eb46b6cbd
		summarizeBy: none

		annotation SummarizationSetBy = User

	column 'SCD Instrument Type'
		dataType: string
		lineageTag: 2c1044de-193e-421e-857e-b296484e61a8
		summarizeBy: none
		sourceColumn: SCD Instrument Type

		annotation SummarizationSetBy = Automatic

	column 'SCD Latest Flag'
		dataType: string
		lineageTag: eabb732f-2352-44fd-a653-e0411edb8290
		summarizeBy: none
		sourceColumn: SCD Latest Flag

		annotation SummarizationSetBy = Automatic

	column 'RTG MDY Long Issue Level'
		dataType: string
		lineageTag: 3d990814-3ae4-4492-a69b-0129e1376a7a
		summarizeBy: none
		sourceColumn: RTG MDY Long Issue Level

		annotation SummarizationSetBy = Automatic

	column 'RTG Fitch Long'
		dataType: string
		lineageTag: 5420038d-0594-4d9a-837f-a49ddae6fc37
		summarizeBy: none
		sourceColumn: RTG Fitch Long

		annotation SummarizationSetBy = Automatic

	column 'RTG MDY Issuer'
		dataType: string
		lineageTag: c53375bb-3da8-4d3a-b0ee-e38403895496
		summarizeBy: none
		sourceColumn: RTG MDY Issuer

		annotation SummarizationSetBy = Automatic

	column 'RTG S&P Long'
		dataType: string
		lineageTag: 72f1efb2-3faf-44b9-b72b-65b4eb2aa4d2
		summarizeBy: none
		sourceColumn: RTG S&P Long

		annotation SummarizationSetBy = Automatic

	column 'Last Refix Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: cbdea0cf-79ba-40b3-9a49-164c0e3d0810
		summarizeBy: none
		sourceColumn: Last Refix Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'SR Loan'
		dataType: string
		lineageTag: 6619aa88-76cb-428c-b31a-a5f1b0ed7c24
		summarizeBy: none
		sourceColumn: SR Loan

		annotation SummarizationSetBy = Automatic

	column 'Country of Incorporation'
		dataType: string
		lineageTag: 4a21c21b-6cd0-4a07-8258-45552c02be10
		summarizeBy: none
		sourceColumn: Country of Incorporation

		annotation SummarizationSetBy = Automatic

	column 'Primary Asset Type'
		dataType: string
		lineageTag: 6ee75cdf-9f77-4730-a370-715a09ec2043
		summarizeBy: none
		sourceColumn: Primary Asset Type

		annotation SummarizationSetBy = Automatic

	column 'NAIC Deposit Category'
		dataType: string
		lineageTag: 39ba84aa-a838-46f9-b590-af47866cb992
		summarizeBy: none
		sourceColumn: NAIC Deposit Category

		annotation SummarizationSetBy = Automatic

	column 'Int Acc Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d3d5e9b7-9026-4f03-bb4f-fc666cc5c9df
		summarizeBy: none
		sourceColumn: Int Acc Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'State Code'
		dataType: string
		lineageTag: 0b81d1f2-a69f-4d08-aba2-d6583ab880f9
		summarizeBy: none
		sourceColumn: State Code

		annotation SummarizationSetBy = Automatic

	column 'Final Maturity Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 12e83ce2-4002-4707-8cec-e2cd882f279c
		summarizeBy: none
		sourceColumn: Final Maturity Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Ask Price'
		dataType: double
		lineageTag: a91c888a-4d94-412b-9549-e75631228961
		summarizeBy: sum
		sourceColumn: Ask Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Bid Price'
		dataType: double
		lineageTag: 8b3c3764-cb4d-4bb8-9696-c33ac6893a9a
		summarizeBy: sum
		sourceColumn: Bid Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Mid Price'
		dataType: double
		lineageTag: d4dcc90b-b155-4bfc-9160-013e5bb3f742
		summarizeBy: sum
		sourceColumn: Mid Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Ml Pricing Source'
		dataType: string
		lineageTag: f85af0e6-e916-4016-93bf-0f622a75e4d7
		summarizeBy: none
		sourceColumn: Ml Pricing Source

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Security Description - Restated' =
			
			VAR vLatestAsOfDate = CALCULATE(MAX(Securities[As Of Dt]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]))
			VAR vRestatedValue= CALCULATE(MAX(Securities[Security Description]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]),Securities[As Of Dt]=vLatestAsOfDate)
			RETURN vRestatedValue
		isHidden
		lineageTag: 0eb02102-7346-4330-af7f-9c5ac4c0e290
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Security ID 2 - Restated' =
			
			VAR vLatestAsOfDate = CALCULATE(MAX(Securities[As Of Dt]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]))
			VAR vRestatedValue= CALCULATE(MAX(Securities[Security ID 2]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]),Securities[As Of Dt]=vLatestAsOfDate)
			RETURN vRestatedValue
		isHidden
		lineageTag: 846dd223-22ff-46fa-af1a-37eaac70a700
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Isin - Restated' =
			
			VAR vLatestAsOfDate = CALCULATE(MAX(Securities[As Of Dt]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]))
			VAR vRestatedValue= CALCULATE(MAX(Securities[Isin]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]),Securities[As Of Dt]=vLatestAsOfDate)
			RETURN vRestatedValue
		isHidden
		lineageTag: a0eaaf77-4146-4949-95cf-4de51475a25d
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sedol - Restated' =
			
			VAR vLatestAsOfDate = CALCULATE(MAX(Securities[As Of Dt]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]))
			VAR vRestatedValue= CALCULATE(MAX(Securities[Sedol]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]),Securities[As Of Dt]=vLatestAsOfDate)
			RETURN vRestatedValue
		isHidden
		lineageTag: a077db62-6c75-449d-9018-3de08a4b38a7
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ticker - Restated' =
			
			VAR vLatestAsOfDate = CALCULATE(MAX(Securities[As Of Dt]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]))
			VAR vRestatedValue= CALCULATE(MAX(Securities[Ticker]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]),Securities[As Of Dt]=vLatestAsOfDate)
			RETURN vRestatedValue
		isHidden
		lineageTag: cf7afece-f1d4-4428-9f3c-56d4f21b5474
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID - Restated' =
			
			VAR vLatestAsOfDate = CALCULATE(MAX(Securities[As Of Dt]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]))
			VAR vRestatedValue= CALCULATE(MAX(Securities[Primary Security ID]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]),Securities[As Of Dt]=vLatestAsOfDate)
			RETURN vRestatedValue
		isHidden
		lineageTag: b71810dd-1201-4486-bca6-77296892b8e8
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'SCD Security ID - Restated' = ```
			
			VAR vLatestAsOfDate = CALCULATE(MAX(Securities[As Of Dt]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]))
			VAR vRestatedValue= CALCULATE(MAX(Securities[SCD Security ID]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]),Securities[As Of Dt]=vLatestAsOfDate)
			RETURN vRestatedValue
			
			```
		isHidden
		lineageTag: 7f9703e1-084c-4a72-8e7e-b5f59685a03e
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Cusip - Restated' =
			
			VAR vLatestAsOfDate = CALCULATE(MAX(Securities[As Of Dt]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]))
			VAR vRestatedValue= CALCULATE(MAX(Securities[Cusip]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]),Securities[As Of Dt]=vLatestAsOfDate)
			RETURN vRestatedValue
		isHidden
		lineageTag: 52f57547-32af-4d67-94df-ba44600be7dc
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Official PPN - Restated' =
			
			VAR vLatestAsOfDate = CALCULATE(MAX(Securities[As Of Dt]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]))
			VAR vRestatedValue= CALCULATE(MAX(Securities[Official PPN]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]),Securities[As Of Dt]=vLatestAsOfDate)
			RETURN vRestatedValue
		isHidden
		lineageTag: 71de06e5-cbfb-4e30-a475-1df63a63e2b0
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ML Private Asset ID - Restated' =
			
			VAR vLatestAsOfDate = CALCULATE(MAX(Securities[As Of Dt]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]))
			VAR vRestatedValue= CALCULATE(MAX(Securities[ML Private Asset ID]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]),Securities[As Of Dt]=vLatestAsOfDate)
			RETURN vRestatedValue
		isHidden
		lineageTag: 1dbcf4c8-a7b9-4c2e-a007-be996ebb2f27
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'SecurityID Slicer - Restated' =
			'Securities'[Security Description - Restated] & " - "
			            & 'Securities'[Security ID 2 - Restated]
			            & " - "
			            & IF ( 'Securities'[Isin - Restated] <> "N/S", 'Securities'[Isin - Restated] )
			            & " - "
			            & 'Securities'[Sedol - Restated]
			            & " - "
			            & 'Securities'[Ticker - Restated]
			            & " - "
			            & IF ( 'Securities'[ID BB Global - Restated]  <> "Not Specified", 'Securities'[ID BB Global - Restated] )
			            & " - "
			            & 'Securities'[Primary Security ID - Restated]
			            & " - "
			            & 'Securities'[Src Security ID]
			            & " - "
			            & 'Securities'[SCD Security ID - Restated]
			            & " - "
			            & 'Securities'[Cusip - Restated]
			            & " - "
			            & 'Securities'[Official PPN - Restated]
			            & " - "
			            & 'Securities'[ML Private Asset ID - Restated]
		lineageTag: 46e5874c-0fea-418a-8f62-a72ae60eef6d
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ID BB Global - Restated' =
			
			VAR vLatestAsOfDate = CALCULATE(MAX(Securities[As Of Dt]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]))
			VAR vRestatedValue= CALCULATE(MAX(Securities[ID BB Global]),ALLEXCEPT(Securities,Securities[Src Security ID],Securities[Src Market ID]),Securities[As Of Dt]=vLatestAsOfDate)
			RETURN vRestatedValue
		isHidden
		lineageTag: 62e34c0c-4382-465b-bfa9-01b5333e1bc1
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Sector Name (Private Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: 38b733ba-e388-4d49-acca-16fc836479dd
		summarizeBy: none
		sourceColumn: MRM Industry Sector Name (Private Sec)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Group Name (Private Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: 922275b7-75bc-4761-a981-07020e69c6a7
		summarizeBy: none
		sourceColumn: MRM Industry Group Name (Private Sec)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Subgroup Name (Private Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: 633827c0-e010-4640-bc9b-1eb0adf4cca4
		summarizeBy: none
		sourceColumn: MRM Industry Subgroup Name (Private Sec)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Sector Name (Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: 38fc5344-ae6f-4be3-a0ea-c920e70cd7b2
		summarizeBy: none
		sourceColumn: MRM Industry Sector Name (Sec)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Group Name (Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: 03377b3f-14e4-43a0-8d3b-e1d4d53e439e
		summarizeBy: none
		sourceColumn: MRM Industry Group Name (Sec)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Subgroup Name (Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: efce9913-e209-4320-8094-2d7e114f6e81
		summarizeBy: none
		sourceColumn: MRM Industry Subgroup Name (Sec)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'MRM Sector Name (Sec)'
		dataType: string
		isHidden
		displayFolder: MRM Fields
		lineageTag: bd1af01e-fc55-4983-9cb0-d72bccc36c58
		summarizeBy: none
		sourceColumn: MRM Sector Name (Sec)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'MRM Sector Name' =
			
			IF(
			    Securities[ML Investment Type Cd] IN {"Private","Secondary Private"},
			    COALESCE(Securities[MRM Sector (Private Sec)],Securities[MRM Sector Name (Sec)]),
			    COALESCE(Securities[MRM Sector Name (Sec)],Securities[MRM Sector (Private Sec)])
			)
		displayFolder: MRM Fields
		lineageTag: ccd1301f-643b-4481-b5ce-e16f6b0eb62f
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Sector Name' =
			
			IF(
			    Securities[ML Investment Type Cd] IN {"Private","Secondary Private"},
			    COALESCE(Securities[MRM Industry Sector Name (Private Sec)],Securities[MRM Industry Sector Name (Sec)]),
			    COALESCE(Securities[MRM Industry Sector Name (Sec)],Securities[MRM Industry Sector Name (Private Sec)])
			)
		displayFolder: MRM Fields
		lineageTag: f0774273-5a62-43a7-a53c-bd9196ca9ba2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Group Name' =
			
			IF(
			    Securities[ML Investment Type Cd] IN {"Private","Secondary Private"},
			    COALESCE(Securities[MRM Industry Group Name (Private Sec)],Securities[MRM Industry Group Name (Sec)]),
			    COALESCE(Securities[MRM Industry Group Name (Sec)],Securities[MRM Industry Group Name (Private Sec)])
			)
		displayFolder: MRM Fields
		lineageTag: 2c7a9c62-feb1-4f63-b264-2812135cee49
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'MRM Industry Subgroup Name' =
			
			IF(
			    Securities[ML Investment Type Cd] IN {"Private","Secondary Private"},
			    COALESCE(Securities[MRM Industry Subgroup Name (Private Sec)],Securities[MRM Industry Subgroup Name (Sec)]),
			    COALESCE(Securities[MRM Industry Subgroup Name (Sec)],Securities[MRM Industry Subgroup Name (Private Sec)])
			)
		displayFolder: MRM Fields
		lineageTag: d335d504-c3b8-479b-b3a5-56d3c99601a5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Step-down Floater Ind'
		dataType: string
		lineageTag: e157ad39-456c-49ce-b44f-100aaf84bbd7
		summarizeBy: none
		sourceColumn: Step-down Floater Ind

		annotation SummarizationSetBy = Automatic

	column 'Step-up Floater Ind'
		dataType: string
		lineageTag: dc6f81c8-7948-4c6e-bc1f-c238c91df723
		summarizeBy: none
		sourceColumn: Step-up Floater Ind

		annotation SummarizationSetBy = Automatic

	column 'Income Rate Ind'
		dataType: string
		lineageTag: 6ba7345c-175e-44de-99fc-2fc09b291281
		summarizeBy: none
		sourceColumn: Income Rate Ind

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Float Not Var Ind'
		dataType: string
		lineageTag: 8245a1b8-c45d-426d-a7ba-c247b0c78d76
		summarizeBy: none
		sourceColumn: Float Not Var Ind

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Accrue In Default Ind'
		dataType: string
		lineageTag: 692ef2b0-b9c7-430b-8ca6-9a320aa3cf6d
		summarizeBy: none
		sourceColumn: Accrue In Default Ind

		annotation SummarizationSetBy = Automatic

	column 'Pre Payment Risk'
		dataType: string
		lineageTag: c90d2726-5474-42aa-95bd-40fde15a5bdf
		summarizeBy: none
		sourceColumn: Pre Payment Risk

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Next Refix Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 47302b8d-4581-4e3e-8fe7-499aa13a009d
		summarizeBy: none
		sourceColumn: Next Refix Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'First Coupon Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 5dbe1d2e-1b71-42ef-9327-e0fb0b3c4fd2
		summarizeBy: none
		sourceColumn: First Coupon Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Default Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 7bf902d2-48e8-424f-8d71-135a9a65bd99
		summarizeBy: none
		sourceColumn: Default Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Sink Fund PRN'
		dataType: double
		lineageTag: 48d4174b-a464-4b13-b352-18adc7dcfdab
		summarizeBy: sum
		sourceColumn: Sink Fund PRN

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Coupon Floor'
		dataType: double
		lineageTag: 59faa012-8dea-4c3d-9264-a727398144bc
		summarizeBy: sum
		sourceColumn: Coupon Floor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Coupon Cap'
		dataType: double
		lineageTag: 5e93b21e-e4db-44de-a949-726008d444bd
		summarizeBy: sum
		sourceColumn: Coupon Cap

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Is PublicPP Ind'
		dataType: string
		lineageTag: ed7adff9-1876-47f9-be57-5918201d43f8
		summarizeBy: none
		sourceColumn: Is PublicPP Ind

		annotation SummarizationSetBy = Automatic

	column 'Mxms Id'
		dataType: string
		lineageTag: e1d94d86-e784-4e6e-8341-b165d906be55
		summarizeBy: none
		sourceColumn: Mxms Id

		annotation SummarizationSetBy = Automatic

	column 'SCD Deposit Rate'
		dataType: double
		lineageTag: f8701b63-9490-479c-b830-0b9ae9b5046b
		summarizeBy: sum
		sourceColumn: SCD Deposit Rate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Reset Freq Description'
		dataType: string
		lineageTag: 694fcf9f-440c-411c-9ed7-67b7bdee2cf1
		summarizeBy: none
		sourceColumn: Reset Freq Description

		annotation SummarizationSetBy = Automatic

	column 'Latest As of Dt' =
			
			
			VAR vMaxPosDate = MAX('Securities Position Fact'[As Of Date])
			
			RETURN
			
			SWITCH(
			
			TRUE(),
			
			Securities[As Of Dt]=vMaxPosDate,"Latest",
			
			ENDOFMONTH(Securities[As Of Dt])=Securities[As Of Dt],"Latest",
			
			FORMAT(Securities[As Of Dt],"DD-MMM-YYYY")
			
			)
		lineageTag: 26a267ac-2cf1-49de-8ef6-974d8638e32d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID & Desc - Never Use' = Securities[Primary Security ID & Desc]
		isHidden
		lineageTag: efde13c3-a4d8-47c7-9392-769d9f92372a
		summarizeBy: none
		sortByColumn: 'As Of Dt'

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Wash Sale Parent Security Id'
		dataType: string
		lineageTag: 0ac88fbc-78ba-4e45-af51-87798df0ef75
		summarizeBy: none
		sourceColumn: Wash Sale Parent Security Id

		annotation SummarizationSetBy = Automatic

	column 'ML LICAT Inferred Rating ORG'
		dataType: string
		lineageTag: 228f0f03-2613-41ba-b07b-8cc36fa9970f
		summarizeBy: none
		sourceColumn: ML LICAT Inferred Rating ORG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Scd Private Placement Indicator'
		dataType: string
		lineageTag: 12976378-01bc-4367-bc50-d9f1cd42303c
		summarizeBy: none
		sourceColumn: Scd Private Placement Indicator

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Actual S&P' = LEFT(Securities[S&P],FIND("*",Securities[S&P],1,10)-1)
		lineageTag: 609192a7-0653-4671-b8c0-c15cc8d5783d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Country of Issue - Long' = ```
			
			VAR VCountryofIssue = Securities[Country Of Issue]
			VAR VCountryDim = 
			                CALCULATE(
			                    FIRSTNONBLANK('Country Dim'[Country Long Nm],TRUE()), 
			                    'Country Dim'[ISO2 Country Cd]=VCountryofIssue)
			RETURN 
			VCountryDim
			```
		lineageTag: e5ff7ff8-c1c2-4d53-b1a4-f052ed2fc63e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Country of Issue - Short' = ```
			
			VAR VcountryCode = Securities[Country Of Issue] 
			VAR VCountryDim = 
			     CALCULATE (
			          FIRSTNONBLANK('Country Dim'[Country Short Nm],TRUE()),'COUNTRY DIM'[ISO2 Country Cd] = VcountryCode )
			RETURN
			    VCountryDim
			```
		lineageTag: 071044d1-e97a-4b1b-af6f-58617eaf47cd
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'ML IRR Rating (Adj)' = ```
			
			VAR vSecurityNK=Securities[Security NK]
			VAR Vratingfromsecurityratingperiod = Calculate(SELECTEDVALUE('Security Ratings Periods Fact'[Rating CD]),
			'Security Ratings Periods Fact'[Security NK]= vSecurityNK,
			'Security Ratings Periods Fact'[Rating Agency CD]="MANULIFE INTERNAL RISK RATING")
			
			RETURN
			COALESCE('Securities'[ML IRR Rating],Vratingfromsecurityratingperiod
			)
			
			```
		lineageTag: 9b6761e5-ede2-4cc2-a0a8-04e4219735e9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'ML MFC Equivalent Rtg' = ```
			
			VAR vSecurityNK=Securities[Security NK]
			VAR vRatingFromSecurityRatingPeriod = 
			CALCULATE(
			    SELECTEDVALUE('Security Ratings Periods Fact'[Rating CD]),
			   'Security Ratings Periods Fact'[Security NK]= vSecurityNK,
			   'Security Ratings Periods Fact'[Rating Agency CD]= "MANULIFE EQUIVALENT RATING"
			)
			RETURN
			COALESCE(Securities[ML MFC Equivalent Rating],vRatingFromSecurityRatingPeriod)
			```
		lineageTag: b405fd62-5ac6-4aea-ac10-a52cfaeba04b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Private Placement (Adj)' =
			
			COALESCE(securities[Private Placement],Securities[Scd Private Placement Indicator])
		lineageTag: 443d90b0-455f-4aab-895a-f6c1100d792d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'ML LICAT Inferred Rating' =
			
			
			VAR vSecurityNK=Securities[Security NK]
			
			VAR vRatingFromSecurityRatingTable=
			
			CALCULATE(
			
			    SELECTEDVALUE('Security Ratings Periods Fact'[Rating CD]),
			
			    'Security Ratings Periods Fact'[Security NK]= vSecurityNK,
			
			    'Security Ratings Periods Fact'[Rating Agency CD]= "MANULIFE LICAT INFERRED RATING"
			
			)
			RETURN
			
			COALESCE(Securities[ML LICAT Inferred Rating ORG],vRatingFromSecurityRatingTable)
		lineageTag: 16c1b665-c7b9-4b6f-9c22-6705528ba9b6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Endorsement Indicator' =
			
			VAR vSecurityNK=Securities[Security NK]
			Var VendorsementFromSecurtiyRating = calculate(SELECTEDVALUE('Security Ratings Periods Fact'[Endorsement Indicator]),
			'Security Ratings Periods Fact'[Security NK]= vSecurityNK,
			'Security Ratings Periods Fact'[Rating Agency CD]="MANULIFE EQUIVALENT RATING")
			RETURN
			COALESCE(VendorsementFromSecurtiyRating,"")
		lineageTag: 2cd6c299-3776-41cf-9089-9d924ac4ecf8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Issuer Country Cd'
		dataType: string
		lineageTag: 1cfb66ab-99a3-46b9-b28e-3c82738153fe
		summarizeBy: none
		sourceColumn: Issuer Country Cd

		annotation SummarizationSetBy = Automatic

	column 'Primary Security ID Type'
		dataType: string
		lineageTag: 942578e0-9a22-4e78-96e1-ac6bdd78059c
		summarizeBy: none
		sourceColumn: Primary Security ID Type

		annotation SummarizationSetBy = Automatic

	column 'Internal Sec Id Type'
		dataType: string
		lineageTag: a26492a0-a154-4352-b644-90752f83a252
		summarizeBy: none
		sourceColumn: Internal Sec Id Type

		annotation SummarizationSetBy = Automatic

	column 'ML Review CAT CD'
		dataType: string
		lineageTag: 3b94f499-245e-42d8-a5f2-6c287893369c
		summarizeBy: none
		sourceColumn: ML Review CAT CD

		annotation SummarizationSetBy = Automatic

	column 'ML Issue Txt'
		dataType: string
		lineageTag: badc4736-9636-41cd-b79f-3c58d7f9731a
		summarizeBy: none
		sourceColumn: ML Issue Txt

		annotation SummarizationSetBy = Automatic

	column 'Legal Structure Cd'
		dataType: string
		lineageTag: b2db8b36-dca2-4bba-8e49-b5851bc8b9b5
		summarizeBy: none
		sourceColumn: Legal Structure Cd

		annotation SummarizationSetBy = Automatic

	column 'Gics Sector Cd'
		dataType: string
		lineageTag: afd06abc-5dc4-44db-8954-269da7aa0902
		summarizeBy: none
		sourceColumn: Gics Sector Cd

		annotation SummarizationSetBy = Automatic

	column 'Gics Industry Cd'
		dataType: string
		lineageTag: adafddef-6602-49ac-8156-98449aa64c0c
		summarizeBy: none
		sourceColumn: Gics Industry Cd

		annotation SummarizationSetBy = Automatic

	column 'Gics Sub Industry Cd'
		dataType: string
		lineageTag: 0a28ad66-5bfc-4cc2-b6fc-8927bb71c179
		summarizeBy: none
		sourceColumn: Gics Sub Industry Cd

		annotation SummarizationSetBy = Automatic

	column 'Gics Industry Group Cd'
		dataType: string
		lineageTag: 017ea77a-3df7-4132-9add-58bd181f4649
		summarizeBy: none
		sourceColumn: Gics Industry Group Cd

		annotation SummarizationSetBy = Automatic

	column 'Opt Put Call'
		dataType: string
		lineageTag: f856d0f6-69a6-484e-91fc-43246a01a776
		summarizeBy: none
		sourceColumn: Opt Put Call

		annotation SummarizationSetBy = Automatic

	column 'Eqy Sic Cd'
		dataType: string
		lineageTag: 694f6010-5f84-4ac6-b875-b6cee3699daf
		summarizeBy: none
		sourceColumn: Eqy Sic Cd

		annotation SummarizationSetBy = Automatic

	column 'Entity Join Key'
		dataType: string
		lineageTag: be434b08-0dd5-4f7c-ad2b-8aa88e6d598d
		summarizeBy: none
		sourceColumn: Entity Join Key

		annotation SummarizationSetBy = Automatic

	column 'SCD MTG EXP Maturity Dt'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a7eb1e90-f2c5-43f3-8fa4-2b6d8bc8307e
		summarizeBy: none
		sourceColumn: SCD MTG EXP Maturity Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Eqy Sic Name'
		dataType: string
		lineageTag: b7552b42-2885-468e-8804-2473c04d82ff
		summarizeBy: none
		sourceColumn: Eqy Sic Name

		annotation SummarizationSetBy = Automatic

	column 'NAIC Designation Modifier'
		dataType: string
		sourceProviderType: varchar(50)
		lineageTag: d976ef6a-b51a-47ea-ba7c-61e03187f638
		summarizeBy: none
		sourceColumn: NAIC Designation Modifier

		annotation SummarizationSetBy = Automatic

	column 'SCD Svo Suffix'
		dataType: string
		sourceProviderType: varchar(50)
		lineageTag: c48fad69-1fce-4a70-a649-7c1ea6c18423
		summarizeBy: none
		sourceColumn: SCD Svo Suffix

		annotation SummarizationSetBy = Automatic

	column 'Issue px'
		dataType: string
		lineageTag: f18184bf-70ba-4181-8cfa-ca95ed8a2438
		summarizeBy: none
		sourceColumn: Issue px

		annotation SummarizationSetBy = Automatic

	column 'First settle dt'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7dc55c2b-aa77-4afc-8769-b9f606f51fa4
		summarizeBy: none
		sourceColumn: First settle dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start acc dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: f402a43f-1881-4cf6-85c6-4f0fb65dc9ed
		summarizeBy: none
		sourceColumn: Start acc dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Exch code'
		dataType: string
		lineageTag: 1e03b075-d4c3-4fb0-9b54-110db04463f5
		summarizeBy: none
		sourceColumn: Exch code

		annotation SummarizationSetBy = Automatic

	column 'Id mic1'
		dataType: string
		lineageTag: 5312e791-d09a-446a-b6b1-27430b1b1bcb
		summarizeBy: none
		sourceColumn: Id mic1

		annotation SummarizationSetBy = Automatic

	column 'MTG start acc dt set dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 00c87ed5-665c-412e-b9c4-d0ec4c2b6f5e
		summarizeBy: none
		sourceColumn: MTG start acc dt set dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Make Whole Call Spread Num'
		dataType: double
		lineageTag: 6261ffac-7f39-4a1e-ad0a-53957fff7ea9
		summarizeBy: sum
		sourceColumn: Make Whole Call Spread Num

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Make Whole Termination Dt'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 3f13e851-eb1b-4324-8fce-210f58aa3afc
		summarizeBy: none
		sourceColumn: Make Whole Termination Dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Payment Method Name'
		dataType: string
		lineageTag: fdc0e969-3e48-4e9c-a6c1-3069a0401ea0
		summarizeBy: none
		sourceColumn: Payment Method Name

		annotation SummarizationSetBy = Automatic

	column 'MRM Issuer Name'
		dataType: string
		lineageTag: b42d3928-f34f-41c9-adb0-8fc08008d127
		summarizeBy: none
		sourceColumn: MRM Issuer Name

		annotation SummarizationSetBy = Automatic

	column 'MRM Issuer Country Name'
		dataType: string
		lineageTag: 7ec98a3b-f352-4582-b602-2e484e0dc322
		summarizeBy: none
		sourceColumn: MRM Issuer Country Name

		annotation SummarizationSetBy = Automatic

	column 'MRM Issuer Irr Rating Cd'
		dataType: string
		lineageTag: 8674969f-37ed-4d61-a84e-3a92b7038b5f
		summarizeBy: none
		sourceColumn: MRM Issuer Irr Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'MRM Issuer Parent Name'
		dataType: string
		lineageTag: 2da081aa-b8ff-4fb7-a25f-35cc7b47be8d
		summarizeBy: none
		sourceColumn: MRM Issuer Parent Name

		annotation SummarizationSetBy = Automatic

	column 'MRM Issuer Parent Country Name'
		dataType: string
		lineageTag: 59f772f7-b09d-4ae7-8f14-e5683c2b3066
		summarizeBy: none
		sourceColumn: MRM Issuer Parent Country Name

		annotation SummarizationSetBy = Automatic

	column 'MRM Issuer Parent Irr Rating Cd'
		dataType: string
		lineageTag: f72a4a83-b99e-4546-ae09-05203697c0aa
		summarizeBy: none
		sourceColumn: MRM Issuer Parent Irr Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'MRM Issuer Ultparent Name'
		dataType: string
		lineageTag: f4e0eaab-1e4f-4751-a2a1-9e7b7b59e188
		summarizeBy: none
		sourceColumn: MRM Issuer Ultparent Name

		annotation SummarizationSetBy = Automatic

	column 'MRM Issuer Ultparent Country Name'
		dataType: string
		lineageTag: 9b452a1f-af2d-451c-8ee3-4cea49c00bef
		summarizeBy: none
		sourceColumn: MRM Issuer Ultparent Country Name

		annotation SummarizationSetBy = Automatic

	column 'MRM Issuer Ultparent Irr Rating Cd'
		dataType: string
		lineageTag: f20c0128-3a9f-4578-bc00-f9d60f57db9b
		summarizeBy: none
		sourceColumn: MRM Issuer Ultparent Irr Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'Equity Fund Ind'
		dataType: string
		lineageTag: ed734371-47d9-463a-9243-e5fb817136ac
		summarizeBy: none
		sourceColumn: Equity Fund Ind

		annotation SummarizationSetBy = Automatic

	column 'GCLMS Collateral Quality Cd'
		dataType: string
		lineageTag: 937f8583-ec2f-4557-893d-6b7a7a04ac86
		summarizeBy: none
		sourceColumn: GCLMS Collateral Quality Cd

		annotation SummarizationSetBy = Automatic

	column 'MRM Issuer Cascade Rating Cd'
		dataType: string
		lineageTag: 6806fb48-322c-4358-b82f-14a05f9dc503
		summarizeBy: none
		sourceColumn: MRM Issuer Cascade Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'MRM Issuer Parent Cascade Rating Cd'
		dataType: string
		lineageTag: 7f7abfe5-0bc9-4b3b-a805-40b76b870a63
		summarizeBy: none
		sourceColumn: MRM Issuer Parent Cascade Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'MRM Issuer Ultparent Cascade Rating Cd'
		dataType: string
		lineageTag: 8f143af0-643c-4521-9676-c05a500f4aa6
		summarizeBy: none
		sourceColumn: MRM Issuer Ultparent Cascade Rating Cd

		annotation SummarizationSetBy = Automatic

	column 'Cur Cpn'
		dataType: double
		lineageTag: 40a44894-8316-43df-a4d6-b81c9b3cfbff
		summarizeBy: sum
		sourceColumn: Cur Cpn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GCLMS Issuer Parent Cascade Rtg Cd'
		dataType: string
		lineageTag: 9b13d087-b32b-4d7f-9129-c3d2a15b2c02
		summarizeBy: none
		sourceColumn: GCLMS Issuer Parent Cascade Rtg Cd

		annotation SummarizationSetBy = Automatic

	column 'Guarantor Name'
		dataType: string
		lineageTag: b00656d2-d1fd-404b-a2b1-4ebf2cc5167e
		summarizeBy: none
		sourceColumn: Guarantor Name

		annotation SummarizationSetBy = Automatic

	column 'Capital Structure Name'
		dataType: string
		lineageTag: 3c8e1b6c-5aad-465a-a572-d90ab54677e0
		summarizeBy: none
		sourceColumn: Capital Structure Name

		annotation SummarizationSetBy = Automatic

	column 'Alt Fee Asset Name'
		dataType: string
		lineageTag: fd9fb985-5a6a-46ba-914f-4ce9767e84ef
		summarizeBy: none
		sourceColumn: Alt Fee Asset Name

		annotation SummarizationSetBy = Automatic

	column 'Multi Cpn Schedule Typ'
		dataType: int64
		formatString: 0
		lineageTag: c4dcee91-0eba-4936-af8e-e89550b0b330
		summarizeBy: sum
		sourceColumn: Multi Cpn Schedule Typ

		annotation SummarizationSetBy = Automatic

	column 'AssetID Date Key' = COMBINEVALUES("-",Securities[Security NK],Securities[Primary Security ID])
		lineageTag: f13f1a72-0a74-4f93-bdcd-e7957c9a7a86
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Securities-aae7ee1e-5a83-4e41-baa4-00d4d9b88d7a = m
		mode: import
		queryGroup: 'Infor GL'
		source =
				let
				    Source = Databricks.Catalogs(HostName, HTTPPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null,CommandTimeout= #duration(0,5,0,0), EnableQueryResultDownload="0"]),
				    hive_metastore_Database = Source{[Name=Catalog,Kind="Database"]}[Data],
				    inv_semantic_ga_Schema = hive_metastore_Database{[Name="inv_semantic_ga",Kind="Schema"]}[Data],
				    EDL_asset_dim_dq = inv_semantic_ga_Schema{[Name="asset_dim_dq",Kind="Table"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(EDL_asset_dim_dq,{"ASSET_KEY", "ASSET_ID", "ASSET_NAME", "AS_OF_DT", "SRC", "SCD_SRC_SECURITY_ID", "SCD_SRC_MARKET_ID", "SCD_SECURITY_ID", "SCD_SECURITY_ID_2", "SCD_TICKER_ISIN", "SCD_PPN_PRIVATE_ID", "SCD_SECURITY_NAME", "SCD_BLOOMBERG_ID", "SCD_ID_PRPL", "SCD_ID_BB_GLOBAL", "SCD_CUSIP", "SCD_ISIN", "SCD_TICKER", "SCD_PRINCIPAL_EXCHANGE", "SCD_SEDOL", "SCD_COLLATERAL_TYPE", "SCD_FACTOR", "SCD_LOCAL_CURRENCY_CD", "SCD_MOODYS", "SCD_MOODYS_RATING_CHANGE_DATE", "SCD_SP", "SCD_SP_RATING_CHANGE_DATE", "SCD_SP_RATING_OUTLOOK", "SCD_FITCH", "SCD_FITCH_RATING_CHANGE_DATE", "SCD_DBRS", "SCD_DBRS_RATING_CHANGE_DATE", "SCD_INTERNAL", "SCD_MAM_RATING", "SCD_ISSUER", "SCD_BPL_ISSUER", "SCD_INTERNAL_FUND", "SCD_COUPON", "SCD_SECURITY_ASSET_CLASS", "SCD_SECURITY_GROUP", "SCD_PRIMARY_ASSET_TYPE", "SCD_REPO_TYPE", "SCD_SECURITY_TYPE_2", "SCD_SECURITY_FUND_TYPE", "SCD_INSTRUMENT_TYPE", "SCD_INFLATION_LINKED", "SCD_VARIABLE_COUPON", "SCD_NEXT_COUPON_DATE", "SCD_PREVIOUS_COUPON_DATE", "SCD_MATURITY_DATE", "SCD_MATURITY_DAYS", "SCD_MATURITY_DAYS_2", "SCD_RESET_DAYS", "SCD_DIVIDEND_EX_DATE", "SCD_DIVIDEND_PAY_DATE", "SCD_DIVIDEND_RECORD_DATE", "SCD_DIVIDEND_RATE", "SCD_SHARES_OUTSTANDING", "SCD_FULL_SHARES_OUTSTANDING", "SCD_PRICE_SOURCE", "SCD_ISSUE_DT", "SCD_Country", "SCD_COUNTRY_OF_RISK", "SCD_COUNTRY_OF_ISSUE", "SCD_COUNTRY_OF_DOMICILE", "SCD_AMOUNT_ISSUED", "SCD_AMOUNT_OUTSTANDING", "SCD_MARKET_SECTOR", "SCD_UNDERLYING_ASSET_TYPE", "SCD_FUND_GEOGRAPHIC_FOCUS", "SCD_CONVERSION_RATIO", "SCD_CONVERSION_START_DATE", "SCD_CONVERSION_TO_TICKER", "SCD_VOTING_RIGHTS", "SCD_CONVERTIBLE_INDICATOR", "SCD_ISSUER_STATE_OF_DOMICILE", "SCD_ISSUER_STATE_OF_INCORPORATION", "SCD_144A_FLAG", "SCD_AGENCY_BACKED_MORTGAGE", "SCD_RESET_INDEX", "SCD_MORTGAGE_TRANCHE_TYPE_FULL", "SCD_MORTGAGE_TRANCHE_DESCRIPTION", "SCD_CALC_TYPE_DESCRIPTION", "SCD_NEXT_RESET_DATE", "SCD_CONTRACT_SIZE", "SCD_EXERCISE_DATE", "SCD_EXPIRY_DATE", "SCD_CONTRACT_SIDE", "SCD_FUTURE_CONTRACT_DATE", "SCD_ULTIMATE_PARENT_COMPANY_NAME", "SCD_US_ILLIQUID", "SCD_CA_ILLIQUID", "SCD_MUNICIPAL_LEASE_OBLIGATION", "SCD_REGULATORY_TYPE", "SCD_REG_S", "SCD_SINKABLE_INDICATOR", "SCD_NEXT_SINK_DATE", "SCD_ISLAMIC_INDICATOR", "SCD_MORTGAGE_PRINCIPAL_LOSSES", "SCD_MORTGAGE_INTEREST_SHORTFALL", "SCD_LOCAL_ID", "SCD_LOCAL_SECTOR", "SCD_ASIA_RATING", "SCD_RAM_RATING", "SCD_MARC_RATING", "SCD_ML_LIQUIDITY_CHANGE", "SCD_ML_MUNICIPAL_OBLIGOR", "SCD_OFFERING_TYPE", "SCD_REGULATORY_STRUCTURE", "SCD_EXCHANGE_COUNTRY", "SCD_ISSUER_TYPE", "SCD_MY_LOCAL_SEC_TYPE", "SCD_PRIVATE_PLACEMENT", "SCD_DEFAULT_FLAG", "SCD_FI_TYPE", "SCD_SP_SHORT_TERM_RATING", "SCD_MOODYS_SHORT_TERM_RATING", "SCD_FITCH_SHORT_TERM_RATING", "SCD_BPL_COUNTRY", "SCD_DISCOUNT_INDICATOR", "SCD_ST_COMPREHENSIVE", "SCD_EQ_SECTOR", "SCD_ACCRUAL_CURRENCY", "SCD_SETTLEMENT_TYPE", "SCD_SECTOR", "SCD_INDUSTRY_GROUP", "SCD_INDUSTRY", "SCD_SUB_INDUSTRY", "SCD_GICS_BICS", "SCD_SUBORD_TYPE", "SCD_ML_IFRS_13_LEVEL", "SCD_PRICE_POINT", "SCD_DAY_COUNT", "SCD_FINDUR_ID", "SCD_MANULIFE_LOCAL_PRICE", "SCD_YEAR", "SCD_PAYMENT_RANK", "SCD_ML_INVESTMENT_ID", "SCD_ML_INVESTMENT_TYPE_CD", "SCD_ASSET_CLASS", "SCD_CPN_FREQ", "SCD_GL_CLASSIFICATION", "SCD_GL_CLASSIFICATION_JGAAP", "SCD_GL_CLASSIFICATION_NAIC", "SCD_ML_CUSIP_PPN", "SCD_JAPAN_CREDIT_RATING_CD", "SCD_RI_RATING_CD", "SCD_ML_LOCAL_CHINA_ID", "SCD_ML_VAULT_ID", "SCD_ML_VAULT_NM", "SCD_ML_IRR_RATING", "SCD_ML_MFC_EQUIVALENT_RATING", "SCD_ML_PRIMARY_RATING_CD", "SCD_ML_JH_RATING_CD", "SCD_HAS_CPN_VARIABLE", "SCD_NXT_CALL_DT", "SCD_PRICE_CURRENCY", "SCD_NXT_CALL_PX", "SCD_NXT_PUT_PX", "SCD_NXT_PUT_DT", "SCD_MAKE_WHOLE_CALL", "SCD_CALLABLE", "SCD_PUTABLE", "SCD_STD_CURRENCY", "SCD_COUPON_TYPE", "SCD_ID_BPL_PRICING_STRATEGY", "SCD_ID_BPL_PRICE_POINT", "SCD_PX_LAST", "SCD_MRM_SECTOR", "SCD_CALM_CATEGORY", "SCD_SCHEDULE_BA_ASSET_CATEGORY_CD", "SCD_SEED_MONEY_IND", "SCD_ML_MINOR_TYPE", "SCD_BICS_LEVEL2_INDUSTRY_GRP_DES", "SCD_SECURITY_TYPE", "SCD_ISSUER_LONG_COMP_NAME", "SCD_ISSUER_NAME", "SCD_PAYING_AGENT", "SCD_LONG_COMPANY_NAME", "SCD_BICS_LEVEL1_SECTOR_DES", "SCD_BICS_LEVEL3_INDUSTRY_DES", "SCD_BICS_LEVEL4_SUB_INDUSTRY_DES", "SCD_ANALYSTTEAM", "SCD_ID_BB_COMPANY", "SCD_ID_BB_GLOBAL_COMPANY", "SCD_SECURITY_TYPE_DESC", "SCD_COUPON_SPREAD", "SCD_ML_IFRS_ACCOUNTING_METHOD", "SCD_ML_LGAAP_ACCOUNTING_METHOD", "SCD_ML_STAT_ACCOUNTING_METHOD", "SCD_ML_BA_AVR_CD", "SCD_CALLED_DT", "SCD_CALLED_PX", "SCD_IS_PERPETUAL", "SCD_BASIC_SPREAD", "SCD_COUPON_TYP_RESET_DT", "SCD_GGI_INDICATOR", "SCD_ML_SD_CLASS_DESC", "SCD_DG_ISSUER_CD", "SCD_ML_MFC_EQUIVALENT_EFF_DT", "SCD_ML_MIM_NA_RATING_EFF_DT", "SCD_ML_MIM_ASIA_RATING_EFF_DT", "SCD_ML_SPEQ_RATING", "SCD_ML_SPEQ_EFF_DT", "SCD_ML_JH_RATING_EFFECTIVE_DT", "SCD_JAPAN_CREDIT_RATING_EFFECTIVE_DT", "SCD_ML_IRR_EFF_DT", "SCD_RI_RATING_EFFECTIVE_DT", "SCD_ML_SD_TYPE_DESC", "SCD_ID_CINS", "SCD_ML_CAPITAL_STRUCTURE_CD", "SCD_ML_CAPITAL_STRUCTURE_DESC", "SCD_ML_STAT_COLLATERAL_TYPE_CD", "SCD_ML_NAIC_REPORT_PART_CD", "SCD_NAIC_DESIGNATION", "SCD_NAIC_RATING", "SCD_ANALYST_ID", "SCD_ANALYST_NM", "SCD_ANALYST_ROLE_CD", "SCD_PRIMARY_RATING_EFFECTIVE_DT", "SCD_ML_NAIC_INSTRUMENT_TYPE_CD", "SCD_ML_SD_CLASS_CD", "SCD_ML_SD_SUBCLASS_CD", "SCD_ML_SD_TYPE_CD", "SCD_LATEST_FLAG", "rtg_mdy_long_issue_level", "rtg_fitch_long", "rtg_mdy_issuer", "rtg_sp_long", "LAST_REFIX_DT", "SR_LOAN", "SCD_CNTRY_OF_INCORPORATION", "SCD_NAIC_DEPOSIT_CATEGORY", "SCD_INT_ACC_DT", "SCD_STATE_CODE", "SCD_FINAL_MATURITY_DATE", "SCD_PX_ASK", "SCD_PX_BID", "SCD_PX_MID", "SCD_ML_PRICING_SOURCE", "SCD_MRM_INDUSTRY_SECTOR_NM", "SCD_MRM_INDUSTRY_GROUP_NM", "SCD_MRM_INDUSTRY_SUBGROUP_NM", "SCD_SEC_MRM_INDUSTRY_SECTOR_NM", "SCD_SEC_MRM_INDUSTRY_GROUP_NM", "SCD_SEC_MRM_INDUSTRY_SUBGROUP_NM", "SCD_SEC_MRM_SECTOR_NM", "SCD_HAS_CPN_STEPDN_FLOAT", "SCD_HAS_CPN_STEPUP_FLOAT", "SCD_IS_FIX_TO_FLOAT", "SCD_FLOATER", "SCD_ML_ACCRUE_IN_DEFAULT_IND", "SCD_PREPAY_RISK", "SCD_NXT_REFIX_DT", "SCD_FIRST_CPN_DT", "SCD_DEFAULT_DATE", "SCD_SINKING_FUND_FACTOR", "SCD_CPN_FLOOR", "SCD_CPN_CAP", "SCD_IS_PUBLICPP_IND", "SCD_MXMS_ID", "SCD_DEPOSIT_RATE", "SCD_RESET_FREQ_DESCRIPTION", "SCD_WASH_SALE_PARENT_SECURITY_ID", "SCD_ML_LICAT_INFRD_RATING", "SCD_PRIVATE_PLACEMENT_INDICATOR", "SCD_ISSUER_INCORPORATED_COUNTRY_CODE", "SCD_PRIMARY_SECURITY_ID_TYPE", "SCD_INTERNAL_SEC_ID_TYPE", "SCD_ML_REVIEW_CAT_CD", "SCD_ML_ISSUE_TXT", "SCD_LEGAL_STRUCTURE_CD", "SCD_ENTITY_JOIN_NK", "SCD_GICS_SECTOR_CD", "SCD_GICS_INDUSTRY_CD", "SCD_GICS_SUB_INDUSTRY_CD", "SCD_GICS_INDUSTRY_GROUP_CD", "SCD_OPT_PUT_CALL", "SCD_EQY_SIC_CODE", "SCD_MTG_EXP_MATURITY_DT", "SCD_EQY_SIC_NAME", "SCD_SVO_SUFFIX", "SCD_NAIC_DESIGNATION_MODIFIER", "SCD_EXCH_CODE", "SCD_ID_MIC1", "SCD_ISSUE_PX", "SCD_FIRST_SETTLE_DT", "SCD_START_ACC_DT", "SCD_MTG_START_ACC_DT_SET_DT", "SCD_MAKE_WHOLE_CALL_SPREAD_NUM", "SCD_MAKE_WHOLE_TERMINATION_DT", "SCD_PAYMENT_METHOD_NM", "SCD_MRM_ISSUER_NM", "SCD_MRM_ISSUER_COUNTRY_NM", "SCD_MRM_ISSUER_IRR_RATING_CD", "SCD_MRM_ISSUER_PARENT_NM", "SCD_MRM_ISSUER_PARENT_COUNTRY_NM", "SCD_MRM_ISSUER_PARENT_IRR_RATING_CD", "SCD_MRM_ISSUER_ULTPARENT_NM", "SCD_MRM_ISSUER_ULTPARENT_COUNTRY_NM", "SCD_MRM_ISSUER_ULTPARENT_IRR_RATING_CD", "SCD_EQUITY_FUND_IND", "SCD_GCLMS_COLLATERAL_QUALITY_CD", "SCD_MRM_ISSUER_CASCADE_RATING_CD", "SCD_MRM_ISSUER_PARENT_CASCADE_RATING_CD", "SCD_MRM_ISSUER_ULTPARENT_CASCADE_RATING_CD", "SCD_CUR_CPN", "SCD_GCLMS_ISSUER_PARENT_CASCADE_RTG_CD", "SCD_GUARANTOR_NM", "SCD_CAPITAL_STRUCTURE_NM", "SCD_ALT_FEE_ASSET_NM","multi_cpn_schedule_typ"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each ([SRC] = "SCD")),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"SCD_PRIVATE_PLACEMENT_INDICATOR", "Scd Private Placement Indicator"}, {"SCD_MRM_INDUSTRY_SECTOR_NM", "MRM Industry Sector Name (Private Sec)"}, {"SCD_MRM_INDUSTRY_GROUP_NM", "MRM Industry Group Name (Private Sec)"}, {"SCD_MRM_INDUSTRY_SUBGROUP_NM", "MRM Industry Subgroup Name (Private Sec)"}, {"SCD_SEC_MRM_INDUSTRY_SECTOR_NM", "MRM Industry Sector Name (Sec)"}, {"SCD_SEC_MRM_INDUSTRY_GROUP_NM", "MRM Industry Group Name (Sec)"}, {"SCD_SEC_MRM_INDUSTRY_SUBGROUP_NM", "MRM Industry Subgroup Name (Sec)"}, {"SCD_SEC_MRM_SECTOR_NM", "MRM Sector Name (Sec)"}, {"SCD_IS_PUBLICPP_IND", "Is PublicPP Ind"}, {"SCD_ISSUER_INCORPORATED_COUNTRY_CODE", "Issuer Country Cd"}, {"SCD_PRIMARY_SECURITY_ID_TYPE", "Primary Security ID Type"}, {"SCD_NAIC_DESIGNATION_MODIFIER", "NAIC Designation Modifier"}, {"SCD_SVO_SUFFIX", "SCD Svo Suffix"}, {"AS_OF_DT", "As Of Dt"}, {"ASSET_ID", "Primary Security ID"}, {"ASSET_KEY", "Security NK"}, {"ASSET_NAME", "Security Description"}, {"SCD_144A_FLAG", "144A Flag"}, {"SCD_ACCRUAL_CURRENCY", "Accrual Currency"}, {"SCD_AGENCY_BACKED_MORTGAGE", "Agency Backed Mortgage"}, {"SCD_AMOUNT_ISSUED", "Amount Issued"}, {"SCD_AMOUNT_OUTSTANDING", "Amount Outstanding"}, {"SCD_ANALYST_ID", "Analyst ID"}, {"SCD_ANALYST_NM", "Analyst Nm"}, {"SCD_ANALYST_ROLE_CD", "Analyst Role Cd"}, {"SCD_ANALYSTTEAM", "Analyst Team"}, {"SCD_ASIA_RATING", "Asia Rating"}, {"SCD_BASIC_SPREAD", "Basic Spread"}, {"SCD_BICS_LEVEL1_SECTOR_DES", "BICS Level1 Sector Desc"}, {"SCD_BICS_LEVEL2_INDUSTRY_GRP_DES", "BICS Level2 Industry Group Desc"}, {"SCD_BICS_LEVEL3_INDUSTRY_DES", "BICS Level3 Industry Desc"}, {"SCD_BICS_LEVEL4_SUB_INDUSTRY_DES", "BICS Level4 Sub Industry Desc"}, {"SCD_BLOOMBERG_ID", "Bloomberg ID"}, {"SCD_BPL_COUNTRY", "Bpl Country"}, {"SCD_BPL_ISSUER", "Bpl Issuer"}, {"SCD_CA_ILLIQUID", "Ca Illiquid"}, {"SCD_CALC_TYPE_DESCRIPTION", "Calc Type Description"}, {"SCD_CALLABLE", "Callable"}, {"SCD_CALLED_DT", "Called Dt"}, {"SCD_CALLED_PX", "Called Px"}, {"SCD_CALM_CATEGORY", "Calm Category"}, {"SCD_COLLATERAL_TYPE", "Collateral Type"}, {"SCD_CONTRACT_SIDE", "Contract Side"}, {"SCD_CONTRACT_SIZE", "Contract Size"}, {"SCD_CONVERSION_RATIO", "Conversion Ratio"}, {"SCD_CONVERSION_START_DATE", "Conversion Start Date"}, {"SCD_CONVERSION_TO_TICKER", "Conversion To Ticker"}, {"SCD_CONVERTIBLE_INDICATOR", "Convertible Indicator"}, {"SCD_Country", "Country"}, {"SCD_COUNTRY_OF_DOMICILE", "Country Of Domicile"}, {"SCD_COUNTRY_OF_ISSUE", "Country Of Issue"}, {"SCD_COUNTRY_OF_RISK", "Country Of Risk"}, {"SCD_COUPON", "Coupon"}, {"SCD_COUPON_SPREAD", "Coupon Spread"}, {"SCD_COUPON_TYP_RESET_DT", "Fix To Float Date"}, {"SCD_COUPON_TYPE", "Coupon Type"}, {"SCD_CPN_FREQ", "Coupon Frequency"}, {"SCD_CUSIP", "Cusip"}, {"SCD_DAY_COUNT", "Day Count"}, {"SCD_DBRS", "Dbrs"}, {"SCD_DBRS_RATING_CHANGE_DATE", "Dbrs Rating Change Date"}, {"SCD_DEFAULT_FLAG", "Default Flag"}, {"SCD_DG_ISSUER_CD", "Dg Issuer Cd"}, {"SCD_DISCOUNT_INDICATOR", "Discount Indicator"}, {"SCD_DIVIDEND_EX_DATE", "Dividend Ex Date"}, {"SCD_DIVIDEND_PAY_DATE", "Dividend Pay Date"}, {"SCD_DIVIDEND_RATE", "Dividend Rate"}, {"SCD_DIVIDEND_RECORD_DATE", "Dividend Record Date"}, {"SCD_PRIMARY_ASSET_TYPE", "Primary Asset Type"}, {"SCD_EQ_SECTOR", "Eq Sector"}, {"SCD_EXCHANGE_COUNTRY", "Exchange Country"}, {"SCD_EXERCISE_DATE", "Exercise Date"}, {"SCD_EXPIRY_DATE", "Expiry Date"}, {"SCD_FACTOR", "Factor"}, {"SCD_FI_TYPE", "Fi Type"}, {"SCD_FINDUR_ID", "Findur ID"}, {"SCD_FITCH", "Fitch"}, {"SCD_FITCH_RATING_CHANGE_DATE", "Fitch Rating Change Date"}, {"SCD_FITCH_SHORT_TERM_RATING", "Fitch Short Term Rating"}, {"SCD_FULL_SHARES_OUTSTANDING", "Full Shares Outstanding"}, {"SCD_FUND_GEOGRAPHIC_FOCUS", "Fund Geographic Focus"}, {"SCD_FUTURE_CONTRACT_DATE", "Future Contract Date"}, {"SCD_GGI_INDICATOR", "GGI Indicator"}, {"SCD_GICS_BICS", "Gics Bics"}, {"SCD_GL_CLASSIFICATION", "SCD GL Classification"}, {"SCD_GL_CLASSIFICATION_JGAAP", "SCD GL Classification JGAAP"}, {"SCD_GL_CLASSIFICATION_NAIC", "SCD GL Classification NAIC"}, {"SCD_HAS_CPN_VARIABLE", "Has Coupon Variable"}, {"SCD_ID_BB_COMPANY", "ID BB Company"}, {"SCD_ID_BB_GLOBAL", "ID BB Global"}, {"SCD_ID_BB_GLOBAL_COMPANY", "ID BB Global Company"}, {"SCD_ID_BPL_PRICE_POINT", "ID BPL Price Point"}, {"SCD_ID_BPL_PRICING_STRATEGY", "ID BPL Pricing Strategy"}, {"SCD_ID_CINS", "ID Cins"}, {"SCD_ID_PRPL", "ID PRPL"}, {"SCD_INDUSTRY", "Industry"}, {"SCD_INDUSTRY_GROUP", "Industry Group"}, {"SCD_INFLATION_LINKED", "Inflation Linked"}, {"SCD_INSTRUMENT_TYPE", "SCD Instrument Category"}, {"SCD_INTERNAL", "Internal"}, {"SCD_INTERNAL_FUND", "Internal Fund"}, {"SCD_IS_PERPETUAL", "Is Perpetual"}, {"SCD_ISIN", "Isin"}, {"SCD_ISLAMIC_INDICATOR", "Islamic Indicator"}, {"SCD_ISSUE_DT", "Issue Dt"}, {"SCD_ISSUER", "Issuer"}, {"SCD_ISSUER_LONG_COMP_NAME", "Issuer Long Comp Name"}, {"SCD_ISSUER_NAME", "Issuer Name"}, {"SCD_ISSUER_STATE_OF_DOMICILE", "Issuer State Of Domicile"}, {"SCD_ISSUER_STATE_OF_INCORPORATION", "Issuer State Of Incorporation"}, {"SCD_ISSUER_TYPE", "Issuer Type"}, {"SCD_JAPAN_CREDIT_RATING_CD", "Japan Credit Rating Cd"}, {"SCD_JAPAN_CREDIT_RATING_EFFECTIVE_DT", "Japan Credit Rating Effective Dt"}, {"SCD_LOCAL_CURRENCY_CD", "Local"}, {"SCD_LOCAL_ID", "Local ID"}, {"SCD_LOCAL_SECTOR", "Local Sector"}, {"SCD_LONG_COMPANY_NAME", "Long Company Name"}, {"SCD_MAKE_WHOLE_CALL", "Make Whole Call"}, {"SCD_MAM_RATING", "Mam Rating"}, {"SCD_MANULIFE_LOCAL_PRICE", "Manulife Local Price"}, {"SCD_MARC_RATING", "Marc Rating"}, {"SCD_MARKET_SECTOR", "Market Sector"}, {"SCD_MATURITY_DATE", "Maturity Date"}, {"SCD_MATURITY_DAYS", "Maturity Days (D)"}, {"SCD_MATURITY_DAYS_2", "Maturity Days 2 (D)"}, {"SCD_ML_BA_AVR_CD", "ML Ba Avr Cd"}, {"SCD_ML_CAPITAL_STRUCTURE_CD", "ML Capital Structure Cd"}, {"SCD_ML_CAPITAL_STRUCTURE_DESC", "ML Capital Structure Desc"}, {"SCD_ML_CUSIP_PPN", "ML Private Asset ID"}, {"SCD_ML_IFRS_13_LEVEL", "ML Ifrs 13 Level"}, {"SCD_ML_IFRS_ACCOUNTING_METHOD", "ML Ifrs Accounting Method"}, {"SCD_ML_INVESTMENT_ID", "ML Investment Id"}, {"SCD_ML_INVESTMENT_TYPE_CD", "ML Investment Type Cd"}, {"SCD_ML_IRR_EFF_DT", "ML IRR Eff Dt"}, {"SCD_ML_IRR_RATING", "ML IRR Rating"}, {"SCD_ML_JH_RATING_CD", "ML JH Rating Cd"}, {"SCD_ML_JH_RATING_EFFECTIVE_DT", "ML JH Rating Effective Dt"}, {"SCD_ML_LGAAP_ACCOUNTING_METHOD", "ML Lgaap Accounting Method"}, {"SCD_ML_LIQUIDITY_CHANGE", "ML Liquidity Change"}, {"SCD_ML_LOCAL_CHINA_ID", "ML Local China ID"}, {"SCD_ML_MFC_EQUIVALENT_EFF_DT", "ML MFC Equivalent Eff Dt"}, {"SCD_ML_MFC_EQUIVALENT_RATING", "ML MFC Equivalent Rating"}, {"SCD_ML_MIM_ASIA_RATING_EFF_DT", "ML Mim Asia Rating Eff Dt"}, {"SCD_ML_MIM_NA_RATING_EFF_DT", "ML Mim Na Rating Eff Dt"}, {"SCD_ML_MINOR_TYPE", "ML Minor Type"}, {"SCD_ML_MUNICIPAL_OBLIGOR", "ML Municipal Obligor"}, {"SCD_ML_NAIC_INSTRUMENT_TYPE_CD", "ML NAIC Instrument Type Cd"}, {"SCD_ML_NAIC_REPORT_PART_CD", "ML NAIC Report Part Cd"}, {"SCD_ML_PRIMARY_RATING_CD", "ML Primary Rating Cd"}, {"SCD_ML_SD_CLASS_CD", "ML SD Class Cd"}, {"SCD_ML_SD_CLASS_DESC", "ML SD Class Desc"}, {"SCD_ML_SD_SUBCLASS_CD", "ML SD Subclass Cd"}, {"SCD_ML_SD_TYPE_CD", "ML SD Type Cd"}, {"SCD_ML_SD_TYPE_DESC", "ML SD Type Desc"}, {"SCD_ML_SPEQ_EFF_DT", "ML Speq Eff Dt"}, {"SCD_ML_SPEQ_RATING", "ML Speq Rating"}, {"SCD_ML_STAT_ACCOUNTING_METHOD", "ML Stat Accounting Method"}, {"SCD_ML_STAT_COLLATERAL_TYPE_CD", "ML Stat Collateral Type Cd"}, {"SCD_ML_VAULT_ID", "ML Vault ID"}, {"SCD_ML_VAULT_NM", "ML Vault Name"}, {"SCD_MOODYS", "Moodys"}, {"SCD_MOODYS_RATING_CHANGE_DATE", "Moodys Rating Change Date"}, {"SCD_MOODYS_SHORT_TERM_RATING", "Moodys Short Term Rating"}, {"SCD_MORTGAGE_INTEREST_SHORTFALL", "Mortgage Interest Shortfall"}, {"SCD_MORTGAGE_PRINCIPAL_LOSSES", "Mortgage Principal Losses"}, {"SCD_MORTGAGE_TRANCHE_DESCRIPTION", "Mortgage Tranche Description"}, {"SCD_MORTGAGE_TRANCHE_TYPE_FULL", "Mortgage Tranche Type Full"}, {"SCD_MRM_SECTOR", "MRM Sector (Private Sec)"}, {"SCD_MUNICIPAL_LEASE_OBLIGATION", "Municipal Lease Obligation"}, {"SCD_MY_LOCAL_SEC_TYPE", "My Local Sec Type"}, {"SCD_NAIC_DESIGNATION", "NAIC Designation"}, {"SCD_NAIC_RATING", "NAIC Rating"}, {"SCD_NEXT_COUPON_DATE", "Next Coupon Date"}, {"SCD_NEXT_RESET_DATE", "Next Reset Date"}, {"SCD_NEXT_SINK_DATE", "Next Sink Date"}, {"SCD_NXT_CALL_DT", "Next Call Date"}, {"SCD_NXT_CALL_PX", "Next Call PX"}, {"SCD_NXT_PUT_DT", "Next Put Dt"}, {"SCD_NXT_PUT_PX", "Next Put PX"}, {"SCD_OFFERING_TYPE", "Offering Type"}, {"SCD_PAYING_AGENT", "Paying Agent"}, {"SCD_PAYMENT_RANK", "Payment Rank"}, {"SCD_PPN_PRIVATE_ID", "Official PPN"}, {"SCD_PREVIOUS_COUPON_DATE", "Previous Coupon Date"}, {"SCD_PRICE_CURRENCY", "Price Currency"}, {"SCD_PRICE_POINT", "Price Point"}, {"SCD_PRICE_SOURCE", "Price Source"}, {"SCD_PRIMARY_RATING_EFFECTIVE_DT", "Primary Rating Effective Dt"}, {"SCD_PRINCIPAL_EXCHANGE", "Principal Exchange"}, {"SCD_PRIVATE_PLACEMENT", "Private Placement"}, {"SCD_PUTABLE", "Putable"}, {"SCD_PX_LAST", "Indonesian Price"}, {"SCD_RAM_RATING", "Ram Rating"}, {"SCD_REG_S", "Reg S"}, {"SCD_REGULATORY_STRUCTURE", "Regulatory Structure"}, {"SCD_REGULATORY_TYPE", "Regulatory Type"}, {"SCD_REPO_TYPE", "Repo Type"}, {"SCD_RESET_DAYS", "Reset Days"}, {"SCD_RESET_INDEX", "Reset Index"}, {"SCD_RI_RATING_CD", "RI Rating Cd"}, {"SCD_RI_RATING_EFFECTIVE_DT", "RI Rating Effective Dt"}, {"SCD_SCHEDULE_BA_ASSET_CATEGORY_CD", "Schedule BA Asset Category Code"}, {"SCD_SECTOR", "Sector"}, {"SCD_SECURITY_ASSET_CLASS", "Asset Class"}, {"SCD_SECURITY_FUND_TYPE", "Security Fund Type"}, {"SCD_SECURITY_GROUP", "Asset Group"}, {"SCD_SECURITY_ID", "SCD Security ID"}, {"SCD_SECURITY_ID_2", "Security ID 2"}, {"SCD_SECURITY_NAME", "Security Name"}, {"SCD_SECURITY_TYPE", "SCD Security Type"}, {"SCD_SECURITY_TYPE_2", "Security Type 2"}, {"SCD_SECURITY_TYPE_DESC", "Asset Type"}, {"SCD_SEDOL", "Sedol"}, {"SCD_SEED_MONEY_IND", "Seed Money Ind"}, {"SCD_SETTLEMENT_TYPE", "Settlement Type"}, {"SCD_SHARES_OUTSTANDING", "Shares Outstanding"}, {"SCD_SINKABLE_INDICATOR", "Sinkable Indicator"}, {"SCD_SP", "S&P"}, {"SCD_SP_RATING_CHANGE_DATE", "S&P Rating Change Date"}, {"SCD_SP_RATING_OUTLOOK", "S&P Rating Outlook"}, {"SCD_SP_SHORT_TERM_RATING", "S&P Short Term Rating"}, {"SCD_SRC_MARKET_ID", "Src Market ID"}, {"SCD_SRC_SECURITY_ID", "Src Security ID"}, {"SCD_ST_COMPREHENSIVE", "St Comprehensive"}, {"SCD_STD_CURRENCY", "Std Currency"}, {"SCD_SUB_INDUSTRY", "Sub Industry"}, {"SCD_SUBORD_TYPE", "Subord Type"}, {"SCD_TICKER", "Ticker"}, {"SCD_TICKER_ISIN", "Ticker Isin"}, {"SCD_ULTIMATE_PARENT_COMPANY_NAME", "Ultimate Parent Company Name"}, {"SCD_UNDERLYING_ASSET_TYPE", "Underlying Asset Type"}, {"SCD_US_ILLIQUID", "Us Illiquid"}, {"SCD_VARIABLE_COUPON", "Variable Coupon"}, {"SCD_VOTING_RIGHTS", "Voting Rights"}, {"SCD_YEAR", "Year"}, {"SRC", "Src"}, {"SCD_ASSET_CLASS", "SCD Instrument Type"}, {"SR_LOAN", "SR Loan"}, {"LAST_REFIX_DT", "Last Refix Date"}, {"rtg_sp_long", "RTG S&P Long"}, {"rtg_mdy_issuer", "RTG MDY Issuer"}, {"rtg_fitch_long", "RTG Fitch Long"}, {"rtg_mdy_long_issue_level", "RTG MDY Long Issue Level"}, {"SCD_LATEST_FLAG", "SCD Latest Flag"}, {"SCD_CNTRY_OF_INCORPORATION", "Country of Incorporation"}, {"SCD_STATE_CODE", "State Code"}, {"SCD_NAIC_DEPOSIT_CATEGORY", "NAIC Deposit Category"}, {"SCD_INT_ACC_DT", "Int Acc Date"}, {"SCD_FINAL_MATURITY_DATE", "Final Maturity Date"}, {"SCD_PX_ASK", "Ask Price"}, {"SCD_PX_BID", "Bid Price"}, {"SCD_PX_MID", "Mid Price"}, {"SCD_ML_PRICING_SOURCE", "Ml Pricing Source"}, {"SCD_HAS_CPN_STEPDN_FLOAT", "Step-down Floater Ind"}, {"SCD_HAS_CPN_STEPUP_FLOAT", "Step-up Floater Ind"}, {"SCD_IS_FIX_TO_FLOAT", "Income Rate Ind"}, {"SCD_FLOATER", "Float Not Var Ind"}, {"SCD_ML_ACCRUE_IN_DEFAULT_IND", "Accrue In Default Ind"}, {"SCD_PREPAY_RISK", "Pre Payment Risk"}, {"SCD_NXT_REFIX_DT", "Next Refix Date"}, {"SCD_FIRST_CPN_DT", "First Coupon Date"}, {"SCD_DEFAULT_DATE", "Default Date"}, {"SCD_SINKING_FUND_FACTOR", "Sink Fund PRN"}, {"SCD_CPN_FLOOR", "Coupon Floor"}, {"SCD_CPN_CAP", "Coupon Cap"}, {"SCD_MXMS_ID", "Mxms Id"}, {"SCD_DEPOSIT_RATE", "SCD Deposit Rate"}, {"SCD_RESET_FREQ_DESCRIPTION", "Reset Freq Description"}, {"SCD_MRM_ISSUER_NM", "MRM Issuer Name"}, {"SCD_MRM_ISSUER_COUNTRY_NM", "MRM Issuer Country Name"}, {"SCD_MRM_ISSUER_IRR_RATING_CD", "MRM Issuer Irr Rating Cd"}, {"SCD_MRM_ISSUER_PARENT_NM", "MRM Issuer Parent Name"}, {"SCD_MRM_ISSUER_PARENT_COUNTRY_NM", "MRM Issuer Parent Country Name"}, {"SCD_MRM_ISSUER_PARENT_IRR_RATING_CD", "MRM Issuer Parent Irr Rating Cd"}, {"SCD_MRM_ISSUER_ULTPARENT_NM", "MRM Issuer Ultparent Name"}, {"SCD_MRM_ISSUER_ULTPARENT_COUNTRY_NM", "MRM Issuer Ultparent Country Name"}, {"SCD_MRM_ISSUER_ULTPARENT_IRR_RATING_CD", "MRM Issuer Ultparent Irr Rating Cd"}, {"SCD_EQUITY_FUND_IND", "Equity Fund Ind"}, {"SCD_GCLMS_COLLATERAL_QUALITY_CD", "GCLMS Collateral Quality Cd"}, {"SCD_MRM_ISSUER_CASCADE_RATING_CD", "MRM Issuer Cascade Rating Cd"}, {"SCD_MRM_ISSUER_PARENT_CASCADE_RATING_CD", "MRM Issuer Parent Cascade Rating Cd"}, {"SCD_MRM_ISSUER_ULTPARENT_CASCADE_RATING_CD", "MRM Issuer Ultparent Cascade Rating Cd"}, {"SCD_CUR_CPN", "Cur Cpn"}, {"SCD_GCLMS_ISSUER_PARENT_CASCADE_RTG_CD", "GCLMS Issuer Parent Cascade Rtg Cd"}, {"SCD_GUARANTOR_NM", "Guarantor Name"}, {"SCD_CAPITAL_STRUCTURE_NM", "Capital Structure Name"}, {"SCD_ALT_FEE_ASSET_NM", "Alt Fee Asset Name"}, {"SCD_WASH_SALE_PARENT_SECURITY_ID", "Wash Sale Parent Security Id"}, {"SCD_ML_LICAT_INFRD_RATING", "ML LICAT Inferred Rating ORG"}, {"SCD_INTERNAL_SEC_ID_TYPE", "Internal Sec Id Type"}, {"SCD_ML_REVIEW_CAT_CD", "ML Review CAT CD"}, {"SCD_ML_ISSUE_TXT", "ML Issue Txt"}, {"SCD_LEGAL_STRUCTURE_CD", "Legal Structure Cd"}, {"SCD_OPT_PUT_CALL", "Opt Put Call"}, {"SCD_GICS_SECTOR_CD", "Gics Sector Cd"}, {"SCD_GICS_INDUSTRY_CD", "Gics Industry Cd"}, {"SCD_GICS_SUB_INDUSTRY_CD", "Gics Sub Industry Cd"}, {"SCD_GICS_INDUSTRY_GROUP_CD", "Gics Industry Group Cd"}, {"SCD_EQY_SIC_CODE", "Eqy Sic Cd"}, {"SCD_ENTITY_JOIN_NK", "Entity Join Key"}, {"SCD_MTG_EXP_MATURITY_DT", "SCD MTG EXP Maturity Dt"}, {"SCD_EQY_SIC_NAME", "Eqy Sic Name"}, {"SCD_ISSUE_PX", "Issue px"}, {"SCD_FIRST_SETTLE_DT", "First settle dt"}, {"SCD_START_ACC_DT", "Start acc dt"}, {"SCD_EXCH_CODE", "Exch code"}, {"SCD_ID_MIC1", "Id mic1"}, {"SCD_MTG_START_ACC_DT_SET_DT", "MTG start acc dt set dt"}, {"SCD_MAKE_WHOLE_CALL_SPREAD_NUM", "Make Whole Call Spread Num"}, {"SCD_MAKE_WHOLE_TERMINATION_DT", "Make Whole Termination Dt"}, {"SCD_PAYMENT_METHOD_NM", "Payment Method Name"}, {"multi_cpn_schedule_typ", "Multi Cpn Schedule Typ"}}),
				    #"Filtered Rows - Incremental Refresh" = Table.SelectRows(#"Renamed Columns", each [As Of Dt] >= Date.From(RangeStart) and [As Of Dt] < Date.From(RangeEnd))
				in
				    #"Filtered Rows - Incremental Refresh"

	annotation PBI_ResultType = Table

	annotation PBI_IsMQueryFoldable = True

	annotation PBI_NavigationStepName = Navigation

